### ISSUE TITLE
Support for non-latin slug pattern

### ISSUE THREAD

**Issue by BayCo** [vendure-ecommerce/vendure#1006]
**Is your feature request related to a problem? Please describe.**
For now only latin type characters are supported in localized slug

**Describe the solution you'd like**
In my use case I want to implement cyrilyc type characters

**Comment by MajidNajafi** [comment]
As a temporary workaround, you can monkey-patch Vendure packages.

First, go to `node_modules/@vendure/admin-ui-plugin`, find and replace the validation pattern on the slug input. Current pattern is `[a-z0-9_-]+` and I replaced it with `a-z0-9\u0600-\u06FF_-]+` which adds support for Arabic and Persian characters.

Then go to `node_modules/@vendure/core` package and find the `slug-validator.js`.
find the following line:
`t.slug = normalize_string_1.normalizeString(t.slug, '-');`
and replace it with:
`t.slug = encodeURI(normalize_string_1.normalizeString(t.slug, '-'));`

Don't forget to generate the path files with `patch-package`.

**Comment by michaelbromley** [comment]
@MajidNajafi thanks for your suggestions! I am working on this now and researching the implications of these changes. 

Using the pattern `[\p{Letter}0-9_-]+` in the slug input seems to allow cyrillic, arabic, and chinese/japanese/korean scripts etc by making use of the [unicode property escape](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes#general_categories) syntax.

As far as I can tell, the `encodeURI` part would only be needed at the point where you want to put the non-latin slug in the browser address bar right? I.e. a link in your storefront based on the slug?

When I tried adding the `encodeURI()` step into the `normalizeString()` helper, it causes issues as it saves the encoded string to the DB and the admin UI then ends up like this: 
![image](https://user-images.githubusercontent.com/6275952/130678678-bf92e18f-341c-4798-980b-739d7fe9f5df.png)

**Comment by MajidNajafi** [comment]
@michaelbromley 

> As far as I can tell, the `encodeURI` part would only be needed at the point where you want to put the non-latin slug in the browser address bar right? I.e. a link in your storefront based on the slug?

Yes, actually we don't need the `encodeURI` at the server-side and the slug should be saved without encoding.
But there is another problem here, the slug-based GraphQL queries, like `collection(slug: "تست")`  will not be able to find the entity we're looking for.

So, tweaking the `findOneBySlug` to be able to find non-latin (and not encoded) slugs is all we need at the server-side.

**Comment by michaelbromley** [comment]
> But there is another problem here, the slug-based GraphQL queries, like collection(slug: "تست") will not be able to find the entity we're looking for.

Per my tests this just works without any changes. Perhaps it depends on the character encoding set in the database?

**Comment by lynx-r** [comment]
I found this issue in Google when tried to solve same problem for cyrillic names. As suggested Google AI I created DB Subscriber which overwrites slug on `beforeInsert` Event.

```typescript
// plugins/slug-transliteration/slug.subscriber.ts

import slugify from "slugify";
import {
  EventSubscriber,
  InsertEvent,
  ObjectLiteral,
  Repository,
  UpdateEvent,
} from "typeorm";
import { SLUG_TRANSLATION_RU } from "./consts";
import { LangTranslation, SlugField, SlugParameter } from "./types";

// TypeORM subscriber that automatically generates unique slugs and codes before entity insertion
@EventSubscriber()
export class SlugSubscriber<T> {
  // Hook called before inserting an entity
  async beforeInsert(event: InsertEvent<T>) {
    const entity = event.entity;

    // Generate slug for entities with name and slug fields
    if (this.guardSlugTranslation(entity)) {
      await this.generateUniqueSlug(event, entity);
    }

    // Generate code for entities with code field using Russian translation
    if (this.guardCodeTranslation(entity)) {
      const translation = this.getTranslation(entity);
      if (!translation) {
        return;
      }
      await this.generateUniqueCode(event, entity, translation.name);
    }
  }

  // Extract Russian translation from entity's translations array
  private getTranslation(entity: ObjectLiteral): LangTranslation | undefined {
    return entity.translations?.find(
      ({ languageCode, name }: LangTranslation) =>
        languageCode === SLUG_TRANSLATION_RU && !!name,
    );
  }

  // Type guard to check if entity has name and slug fields
  private guardSlugTranslation(
    entity: T | ObjectLiteral | undefined,
  ): entity is ObjectLiteral {
    return (
      !!entity &&
      typeof entity === "object" &&
      "name" in entity &&
      "slug" in entity
    );
  }

  // Generate a unique slug from entity name
  private async generateUniqueSlug(
    event: InsertEvent<T> | UpdateEvent<T>,
    entity: ObjectLiteral,
  ) {
    entity.slug = await this.getUniqueSlug(event, entity.name, "slug");
  }

  // Type guard to check if entity has a code field
  private guardCodeTranslation(
    entity: T | ObjectLiteral | undefined,
  ): entity is ObjectLiteral {
    return !!entity && typeof entity === "object" && "code" in entity;
  }

  // Generate a unique code from entity name
  private async generateUniqueCode(
    event: InsertEvent<T> | UpdateEvent<T>,
    entity: ObjectLiteral,
    name: string,
  ) {
    entity.code = await this.getUniqueSlug(event, name, "code");
  }

  // Create a unique slug/code by appending numeric suffix if needed
  private async getUniqueSlug(
    event: InsertEvent<T> | UpdateEvent<T>,
    name: string,
    fieldName: SlugField,
  ) {
    const baseSlug = this.createSlug(name);

    let uniqueSlug = baseSlug;
    let suffix = 1;

    const repo = event.manager.getRepository(event.metadata.target);

    // Increment suffix until a unique slug is found
    while (true) {
      const exists = await this.codeExists(repo, fieldName, {
        [fieldName]: uniqueSlug,
      });
      if (!exists) {
        break;
      }
      uniqueSlug = `${baseSlug}-${suffix}`;
      suffix++;
    }

    return uniqueSlug;
  }

  // Check if a slug/code already exists in the database
  private async codeExists(
    repo: Repository<ObjectLiteral>,
    fieldName: SlugField,
    fieldParameter: SlugParameter,
  ): Promise<boolean> {
    const query = repo
      .createQueryBuilder("t")
      .where(`t.${fieldName} = :${fieldName}`, fieldParameter);

    return query.getExists();
  }

  // Convert a name to a URL-friendly slug using Russian locale
  private createSlug(name: string) {
    return slugify(name, {
      lower: true,
      strict: true,
      locale: SLUG_TRANSLATION_RU,
    });
  }
}
```

A few files just for consistency.
```typescript
// plugins/slug-transliteration/types.ts

export type SlugField = "slug" | "code";
export type SlugParameter = Partial<Record<SlugField, string>>;
export type LangTranslation = {
  languageCode: string;
  name: string;
};
```

```typescript
// plugins/slug-transliteration/consts.ts

export const SLUG_TRANSLATION_RU = "ru";
```

And then I added `dbConnectionOptions.subscribers` in `vendure-config.ts`
```typescript
  dbConnectionOptions: {
    ...
    subscribers: [SlugSubscriber],
   ...    
```

**Comment by lynx-r** [comment]
Finally I solved my problem by defining [CustomSlugStrategy](https://docs.vendure.io/current/core/reference/typescript-api/configuration/slug-strategy) from the guide [Strategies & Configurable Operations](https://docs.vendure.io/current/core/developer-guide/strategies-configurable-operations#strategies)
