### ISSUE TITLE
Promotions added and remove inconsistently

### ISSUE THREAD

**Issue by mattgills** [vendure-ecommerce/vendure#1012]
**Describe the bug**
Promotions removed when conditions are no longer satisfied, but the conditions are no longer satisfied because the promotion was applied.

**To Reproduce**

1. Configure a promotion has a requirement to only be applied to an order with a minimum order total of $500 and discounts the order by $200
2. Add an item to the order that costs $600
3. The promotion will appear in the cart
4. Trigger a cart update, by entering the shipping, billing, and shipping method items during checkout
5. You will see that promotion disappear because the conditions are no longer satisfied
6. Return to the home page
7. Refresh the page
8. Return to checkout
9. Trigger a cart update, by entering the shipping, billing, and shipping method items during checkout
10. You will see the promotion reappear

**Expected behavior**
The issue with the above is that the promotion is constantly toggling itself back and forth. The desired behavior is to either never have the promotion applied (i.e. check if the conditions are still satisfied if the promo is applied) or the promotion should be retained (i.e. check if the conditions are satisfied if the promo is not applied).

**Environment (please complete the following information):**
 - @vendure/core version: 1.0.3
 - Nodejs version: 14.17.0
 - Database (mysql/postgres etc): postgres

**Additional context**
N/A

**Comment by michaelbromley** [comment]
Thanks for the report, this sounds like a "fun" problem to solve 😆

**Comment by michaelbromley** [comment]
Hi, I've been looking into this and cannot reproduce. I first tried setting up a failing e2e test that:

1. Creates a Promotion that gives $50 off orders over $100
2. Adds a item at $100
3. Asserts that the promotion is applied
4. Executes `setOrderShippingAddress` and then `setOrderShippingMethod`, the latter of which will trigger an order price recalculation.
5. Asserts that the promotion is still applied.

The test passes. 

I then tested the same flow manually on a dev server and cannot reproduce the issue.

Looking into this, I got to this code here from the OrderCalculator: https://github.com/vendure-ecommerce/vendure/blob/aaa83937b40075a51eea707ac50352da4aa3a383/packages/core/src/service/helpers/order-calculator/order-calculator.ts#L277-L291

During the price calculation, when checking whether or not to apply promotions, this code will first of all remove any promotion discounts from all OrderItems, and then re-calculate the order totals _before_ checking. This is supposed to prevent the issue that you describe above from occurring. And in my testing, it seems to be working.

Could there be some aspect of your case that I am missing here?

**Comment by michaelbromley** [comment]
This issue is being closed because further data was needed but was not provided. If you want to continue the thread, comment below with the required information and the issue can be re-opened.

**Comment by kaushal-enstead** [comment]
@michaelbromley 
This will be a case when there is custom logic in promotion condition like

```ts
        const { availablePoints } = await loyaltyService.getWalletOrThrow(ctx, order.customerId);
// availablePoints = points - freezePoints;
        if (points < .maxRedeemablePoints) {
            return false;
        }


onActivate -> we freeze those points
onDeactivate -> we un-freeze those points

```

So during applyPromotion the condition is true as availablePoints were more then that, but during set shiping method, its again checking promotion which now does not met as availablePoints are lesser now, in some cases

**Comment by kaushal-enstead** [comment]
@michaelbromley  Futhermore, side-effects like onActivate and onDeactivate should only run once when coupon is applied, if its runs more than once, it will lead to issues? Or there should be config like we can pass that it should validte this promotion only once and should run onActivate and onDeactivate only at that time,
