### ISSUE TITLE
ElasticSearch plugin: update Collection

### ISSUE THREAD

**Issue by hendrik-advantitge** [vendure-ecommerce/vendure#1015]
**Describe the bug**
In the ElasticSearch plugin, a product or productVariant contains a list of collection slugs. When a collection is updatet, the indexer service is only triggered when the collection filters are changed. When the collection slug is updatet without changing the filters, the reindexing is not carried out and the products remain in ElasticSearch with the wrong slug.

**To Reproduce**
1. Create collection with slug `slug-1`
2. Add product to collection
3. Update collection so that slug is now `slug-2`
4. Elastic still contains the product with `slug-1`

**Expected behavior**
Collection updates should be propagated correctly to the ElasticSearch Plugin.

**Environment (please complete the following information):**
 - @vendure/core version: v1.0.3

**Comment by Izayda** [comment]
I can get this

**Comment by michaelbromley** [comment]
Thanks @Izayda. Might also be an issue with the DefaultSearchPlugin too - maybe you can check that when you work on this?

**Comment by Izayda** [comment]
Yeah, will look at this problem in DefaultSearchPlugin also
