### ISSUE TITLE
The collection's "tree dropdown" max-width is too narrow

### ISSUE THREAD

**Issue by BenVuti** [vendure-ecommerce/vendure#1042]
The max-width of the `dropdown-menu` CSS class makes it hard to read long collection names
![image](https://user-images.githubusercontent.com/29640337/129894457-1c532d1c-b2e4-4e83-bded-e74775f426ab.png)

**Comment by michaelbromley** [comment]
Thanks. What would be your expected solution to this? 

A simple fix I can think of is to add a `title` attribute to the list item, so that the entire name will pop up on hover. Downside is that this would not work on touch devices.

Another solution is to allow the line to wrap.
