### ISSUE TITLE
deletion of facets without facet-values

### ISSUE THREAD

**Issue by werkzeugh** [vendure-ecommerce/vendure#105]
**Describe the bug**
when trying to delete a facet which has no facet-values system tries to query non-existing 
facet-values 

**To Reproduce**

- create new facet
- delete new facet
- see error: 

> error 5/28/19, 11:26 AM - [TypeORM] Query error: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1, "SELECT `product`.`id` AS `product_id`, `product`.`createdAt` AS `product_createdAt`, `product`.`updatedAt` AS `product_updatedAt`, `product`.`deletedAt` AS `product_deletedAt`, `product`.`enabled` AS `product_enabled`, `product`.`featuredAssetId` AS `product_featuredAssetId`, `product`.`customFieldsDimensions` AS `product_customFieldsDimensions`, `facetValues`.`id` AS `facetValues_id`, `facetValues`.`createdAt` AS `facetValues_createdAt`, `facetValues`.`updatedAt` AS `facetValues_updatedAt`, `facetValues`.`code` AS `facetValues_code`, `facetValues`.`facetId` AS `facetValues_facetId` FROM `product` `product` LEFT JOIN `product_facet_values_facet_value` `product_facetValues` ON `product_facetValues`.`productId`=`product`.`id` LEFT JOIN `facet_value` `facetValues` ON `facetValues`.`id`=`product_facetValues`.`facetValueId` WHERE `facetValues`.`id` IN (?)" -- []

**Environment:**

- @vendure/core version: 0.1.2-beta.2
- Nodejs version: 10.13.0
- Database (mysql/postgres etc): mariadb 10

**Comment by michaelbromley** [comment]
Note: does not throw SQL error when using sqlite, so cannot write a failing e2e test. Will include the test anyway to catch regressions which may have other causes.
