### ISSUE TITLE
Unhandled routes should respond with 404, not 500

### ISSUE THREAD

**Issue by jyotman** [vendure-ecommerce/vendure#1062]
**Describe the bug**
Unhandled routes on the BE API throw 500. They should instead throw 404. It's misleading.
Some of the common example routes - 
1.  Error: Cannot GET /
2. Cannot GET /favicon.ico

This leads to a lot of pollution in the error logs.

**To Reproduce**
Just make a GET call to any of the above routes or any unhandled path.

**Expected behavior**
The API should respond with client error 404 instead of server error. 

**Environment (please complete the following information):**
 - @vendure/core version: 1.1.3
 - Nodejs version: 14
 - Database (mysql/postgres etc): Postgres

**Comment by michaelbromley** [comment]
Perhaps I am misunderstanding but I cannot reproduce this on the current master branch:

```
* Preparing request to http://localhost:3000/
* Current time is 2021-09-13T12:13:47.999Z
* Connected to localhost (::1) port 3000 (#12)

> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: insomnia/2021.5.2
> Cookie: session.sig=5QHfg_OO5CFTZP9NjaySUU5Mr5Q; session=eyJ0b2tlbiI6IjgxNWMwYzA5MjY1YmIzZGNiMmY4MzI0OTNhYWNmOWQ3ZDZhMDE3Y2YyMDdiMmRiMWFlMTM4NDk2YjFjMTJjNTAifQ==
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Vary: Origin
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: vendure-auth-token
< Content-Type: application/json; charset=utf-8
< Content-Length: 93
< ETag: W/"5d-n8HDn7BDlkWxzSgjKF7RgQ+rbVI"
< Date: Mon, 13 Sep 2021 12:13:48 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```

and the response body look like this:

```json
{
  "statusCode": 404,
  "message": "Cannot GET /",
  "timestamp": "2021-09-13T12:13:48.031Z",
  "path": "/"
}
```

**Comment by jyotman** [comment]
Hi, I just made a fresh installation, and yes it doesn't happen in the new installation. 
I'm not sure what I've done wrong in my actual app which leads to 500. I'll try to figure it out and get back on this. 
Thanks!

**Comment by jyotman** [comment]
I installed a separate version of Nestjs/common package which was causing this for some reason. Removing that dependency and using the internal common module fixed the issue.
