### ISSUE TITLE
is it possible to add  new tabs from product details pages from admin panel.

### ISSUE THREAD

**Issue by selva-harivara** [vendure-ecommerce/vendure#1067]
Hi team,
please can update any one of this feature from new dynamic tabs and pages in product details page.

**Comment by michaelbromley** [comment]
Hi,
I'm just revisiting this issue and I don't fully understand what is being requested here. Could you provide more detail and examples?

**Comment by michaelbromley** [comment]
It is now possible in current versions to add tabs to existing pages in the Admin UI.
