### ISSUE TITLE
some wrong when I execute 'npx @vendure/create some-demo'

### ISSUE THREAD

**Issue by misternian** [vendure-ecommerce/vendure#1076]
install failed. cli report:

> verbose 20.0187255 Error: Couldn't find package "mjml-carousel@4.10.2" required by "mjml-preset-core@4.10.2" on the "npm" registry.

how I can solve this problem,  with appreciative

**Comment by michaelbromley** [comment]
Could this perhaps be a temporary npm issue? That package does exist: https://www.npmjs.com/package/mjml-carousel/v/4.10.2

Can you try again and see if it is resolved?

**Comment by misternian** [comment]
Thank you, I will try again. Because i am in china,  some strange problems are usually due to network reasons
