### ISSUE TITLE
Incorrect default width of custom fields

### ISSUE THREAD

**Issue by xvonabur** [vendure-ecommerce/vendure#1077]
**Describe the bug**
Custom fields has incorrect input fields width. It's much shorter, than original fields.

**To Reproduce**
1. Create default project with npx
2. Add custom field "Middle name" for Customer
3. Go to admin page: http://localhost:3000/admin/customer/customers/create
4. See different width size of "First name" and "Middle name" fields

**Expected behavior**
"First name" and "Middle name" fields must have same width

**Environment (please complete the following information):**
 - @vendure/core version: 1.2.0
 - Nodejs version: 16.9.0
 - Database (mysql/postgres etc): Postgres 13
 - Browser: Chrome 93.0.4577.63 on macOS

**Additional context**
See attached screenshot:
<img width="622" alt="Screen Shot 2021-09-10 at 14 58 27" src="https://user-images.githubusercontent.com/616857/132850735-95890653-e2cb-4690-8138-b41a0fd829be.png">

**Comment by xvonabur** [comment]
Adding CSS style "flex: 1" to vdr-dynamic-form-input and "width: 100%" to nested input fixes the issue. See attached screenshot with opened Chrome Dev Tools.

<img width="1115" alt="Screen Shot 2021-09-10 at 15 22 57" src="https://user-images.githubusercontent.com/616857/132853201-36e3008e-fc6c-4d4f-bb50-75b8fc374361.png">


Unfortunately I don't know Angular, so I cannot send a PR.

**Comment by michaelbromley** [comment]
Thanks for the report and advice on the potential fix. Will look into this soon.
