### ISSUE TITLE
Warning (error.forbidden) logs on user session validation

### ISSUE THREAD

**Issue by Draykee** [vendure-ecommerce/vendure#1080]
**Describe the bug**
Currently the query to authenticate a user (`me`) will log a warning (`[Vendure Server] FORBIDDEN: error.forbidden`) when a authentication token is not valid anymore. The warning also occures for other queries or mutation and this pollutes the log a lot. Furthermore this information shouldn't be categorized as a warning, because it's an expected behaviour.

**To Reproduce**
1. Store the authentication token from a valid session (example: user was already signed in)
2. Call the `me` query to get the current user from the session (example: to skip login page)
3. Invalidate/Remove the authentication token`(example: user has signed out)
4. Now when the `me` query is used again to see if the user is already sign in, we get the warning in the log

**Expected behavior**
The `[Vendure Server] FORBIDDEN: error.forbidden` should be logged on a lower log level like verbose.

**Environment (please complete the following information):**
 - @vendure/core version: 1.2.0

**Comment by michaelbromley** [comment]
Agreed, this should be Verbose. I think the initial rationale to make it Warning was because it was first implemented as a response to a failed login attempt.
