### ISSUE TITLE
BullMQJobQueuePlugin always tries to connect to localhost redis server

### ISSUE THREAD

**Issue by huseyinalp** [vendure-ecommerce/vendure#1097]
**Describe the bug**
Even if specify external Redis server, it tries to connect 127.0.0.1:6379.

**To Reproduce**
1-) Replace DefaultJobQueuePlugin with BullMQJobQueuePlugin. 
2-) Update dev-config like below;
`
BullMQJobQueuePlugin.init({
      connection: {
          host: "134.122.XX.XXX",
          port: 6379,
      },
  })
`
**Expected behavior**
It should be connected to specified redis server instead of localhost

**Environment (please complete the following information):**
 - @vendure/core version:10.2.2
 - Nodejs version : v14.16.1
 - Database (mysql/postgres etc): postgres

**Additional context**

Logs:
[run:vendure:worker] info 9/17/21, 3:46 PM - [Vendure Worker] Vendure Worker is ready 
[run:vendure:worker] info 9/17/21, 3:46 PM - [JobQueue] Starting queue: check-worker-health 
[run:vendure:worker] info 9/17/21, 3:46 PM - [JobQueue] Starting queue: apply-collection-filters 
[run:vendure:worker] info 9/17/21, 3:46 PM - [JobQueue] Starting queue: send-email 
[run:vendure:worker] info 9/17/21, 3:46 PM - [JobQueue] Starting queue: update-search-index 
[run:vendure:worker] Error: Connection is closed.
[run:vendure:worker]     at Redis.errorHandler (/Users/alp/shopencode/ecommerce-app/node_modules/bullmq/src/classes/redis-connection.ts:81:16)
[run:vendure:worker]     at Object.onceWrapper (events.js:422:26)
[run:vendure:worker]     at Redis.emit (events.js:315:20)
[run:vendure:worker]     at Redis.EventEmitter.emit (domain.js:467:12)
[run:vendure:worker]     at Redis.silentEmit (/Users/alp/shopencode/ecommerce-app/node_modules/ioredis/built/redis/index.js:544:26)
[run:vendure:worker]     at Socket.<anonymous> (/Users/alp/shopencode/ecommerce-app/node_modules/ioredis/built/redis/event_handler.js:190:14)
[run:vendure:worker]     at Object.onceWrapper (events.js:422:26)
[run:vendure:worker]     at Socket.emit (events.js:327:22)
[run:vendure:worker]     at Socket.EventEmitter.emit (domain.js:467:12)
[run:vendure:worker]     at emitErrorNT (internal/streams/destroy.js:106:8)
[run:vendure:worker] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[run:vendure:worker]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

I have also tried to connect redis server like below;\

...
`const redisConnection = await new IORedis(6379, '134.122.XX.XXX');`
...
`BullMQJobQueuePlugin.init({
      connection: redisConnection,
  }),
`

**Comment by michaelbromley** [comment]
I've just tried to reproduce this and cannot. If I put an alternative good IP like this:

```ts
 BullMQJobQueuePlugin.init({
            connection: {
                host: '192.168.8.103',
                port: 6379,
            },
        }),
```

it connects successfully and when I inspect the internal IORedis connection, it is indeed using the configured host: 
![image](https://user-images.githubusercontent.com/6275952/134500899-741b05fc-2fdf-4e88-a958-8bb9a537a88c.png)

One thing that came to mind is that maybe you need to build your ts files before running? Could there be something stale that needs updating?

**Comment by michaelbromley** [comment]
Note - extra information was provided via Slack which allowed me to locate the source of the error.
