### ISSUE TITLE
Asset video support

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#110]
**Describe the solution you'd like**
The ability to create an Asset which links to a remote URL (e.g. Vimeo or YouTube) and the AssetServerPlugin generates an appropriate preview image and treats the Asset in a way that the video can then be used e.g. in product detail pages.

**Additional context**
Self-hosted video binaries could also be supported in this way, but in practice it seems unlikely that we'd want to just stream a plain mp4 file to the browser. This would be a great way to use all bandwith without any video streaming optimizations performed by a dedicated video hosting service.

**Comment by dariobanfi** [comment]
hey, do you accepts PRs for this?

**Comment by michaelbromley** [comment]
Hi! Thanks for you interest in helping on this. Before doing a PR, maybe you could tell me your idea for solving it and I can provide feedback.

**Comment by anant-barlota** [comment]
Hi, is this possible?
I have an mp4 file that I'd like to be part of a product's asset. Right now it show a plain icon:
![image](https://github.com/vendure-ecommerce/vendure/assets/20843991/2d1e16e6-01a2-4aed-8fd1-8bae846fe6c8)

**Comment by anant-barlota** [comment]
Can it be so that I can run this video on the store or a gif to allow users to see a 360 view of the product.
Like:

![ring](https://github.com/vendure-ecommerce/vendure/assets/20843991/2547082b-c373-49e4-ba69-cbcd1fc85507)

**Comment by michaelbromley** [comment]
Yes that should be possible. Just bear in mind that a gif of that size would be very very large for a storefront - the one above is almost 10MB!

**Comment by anant-barlota** [comment]
I'll keep the file size low, but the gif is shown as a static image right now in the storefront. Should this need an additional config?

**Comment by michaelbromley** [comment]
Try getting the `source` file rather than `preview` - that should be the original animated version.

**Comment by michaelbromley** [comment]
Closing this since it turns out that, in practice a simple string-based custom field pointing to a video URL is actually the more practical solution.
