### ISSUE TITLE
Search: allow random sort

### ISSUE THREAD

**Issue by Izayda** [vendure-ecommerce/vendure#1105]
**Is your feature request related to a problem? Please describe.**
Now sorting at search is consistent in all search plugins. So, all results are consistent for everyone. Sometimes, it would be great to random sort in some scope (for example, in session). 

**Describe the solution you'd like**
Add ability to random sort by salt, provided into api.

**Describe alternatives you've considered**
Do nothing :)

**Comment by michaelbromley** [comment]
Sorry, I don't understand what you mean by this. Can you explain a bit more maybe with an example use-case?

**Comment by Izayda** [comment]
When i send similar search requests in a row, i'll get two similar search results.
As a user, every visit i see on my frontend the same product listing.
Idea is to allow me to randomize search results for every different visit.

**Comment by skid** [comment]
You can easily implement this with your own GraphQL resolver and API extension @Izayda. There's good documentation on that here: https://www.vendure.io/docs/plugins/writing-a-vendure-plugin/

**Comment by Izayda** [comment]
Thank you, @skid! Yeah, I know, that I can implement my own plugin. But it will duplicate half of logic of elastic search plugin and default search plugin (beside indexing logic). So, my suggestion is to expand this plugins.

**Comment by skid** [comment]
Sorry - it wasn't clear that you wanted this for the elasticsearch plugin :)

**Comment by michaelbromley** [comment]
Thanks, I understand the use-case now. Do you have any idea about the actual implementation of something like this? Can it be done using the existing extension points provided by the plugin?

**Comment by Izayda** [comment]
I think about salt approach. Frontend provide to api (for example through SearchResultSortParameter) some string (salt). 

Elastic approach:
Salt is sent to elastic. Sort is applied as `order by hash(_id,salt) asc` https://stackoverflow.com/a/9803517

Default search plugin approach:
Salt is applied at db level as `order by hash(_id,salt) asc`

**Comment by giosueDelgado** [comment]
I think this can be done at plugin config level for only elasticsearch plugin. 
Because the default search plugin it means to have a basic search this I think is an advanced feature to add only on elasticsearch plugin.


To achieve this on elasticsearch plugin you can create a custom logic on mapSort or mapQuery to execute a runtime logic.

So this is possible with the actual plugin elasticsearch.

**Comment by michaelbromley** [comment]
Closing this as it is not something we plan to support in core, and it is possible to solve via custom code.
