### ISSUE TITLE
Event bus fires events during a transaction

### ISSUE THREAD

**Issue by skid** [vendure-ecommerce/vendure#1107]
**Describe the bug**
Maybe this is working as intended, but there's a nasty side effect which is that if the event is fired in the middle of a transaction, any code triggered by the event **won't be aware** of the changes made by that transaction, which is probably not what you want.

This happens because you intentionally remove the transaction because of #520.

**To Reproduce**

(Note: this needs to have #1102 merged because 'created' events are not fired for ProductVariant ATM)

Write some code where you use the internal services to:
1. Create a product
2. Create a product variant for that product
3. Subscribe to a `ProductVariantEvent('created')` and try to query the productId of that variant.
4. You won't get results for the product

**Expected behavior**
You SHOULD get results for the product. Trigger the event after all pending transactions commit.

One way to implement it is to add a method to the RequestContext `onAllTransactionsCompleted( callback: () => void )`

**Environment (please complete the following information):**
 - @vendure/core version: 1.2
 - Nodejs version: any
 - Database (mysql/postgres etc): any

**Comment by michaelbromley** [comment]
> One way to implement it is to add a method to the `RequestContext onAllTransactionsCompleted( callback: () => void )`

This is an interesting suggesting, I shall explore the possibility of some kind of API to await the completion of open transactions.

**Comment by michaelbromley** [comment]
I think I've found an elegant way to solve this by using a TypeORM subscriber to listen for transaction commits/rollbacks.

It strikes me that we could event have this happen automatically - i.e. when an event is published, if the `event.ctx` object contains reference to an active transaction, it can await commit/rollback before actually publishing the event. In this way, the EventBus subscriber function does not ever have to worry about manually awaiting open transactions - they will be guaranteed to be completed by the time the subscriber runs.

**Comment by skid** [comment]
That's the best solution, IMO - unless you explicitly want the event to be triggered before transactions commit (can't think of a reason why).
