### ISSUE TITLE
Typesense Plugin

### ISSUE THREAD

**Issue by amesas** [vendure-ecommerce/vendure#1113]
**Is your feature request related to a problem? Please describe.**
Elasticsearch can be cumbersome to keep on and going. It has a lot of moving parts.
It's very powerful but has a ton of features not needed for an "instant search service".

**Describe the solution you'd like**
We have been running Typesense in production and we are more than happy with it.

**Describe alternatives you've considered**
We have tested Meilisearch, but still no cloud service availble, some problems with stability, and some missing features.

**Comment by Izayda** [comment]
There will be soon separate enterprise advanced search plugin https://www.vendure.io/plugins/

It is based on typesense

**Comment by michaelbromley** [comment]
Yes, as @Izayda mentioned, the upcoming advanced search plugin is built on Typesense (for all the reasons you mentioned in respect to Elasticsearch). Therefore there are no plans to support an official open-source Typesense search plugin at the moment. 

> We have been running Typesense in production and we are more than happy with it.

Is this with a Vendure project? If you already created a plugin and wish to share it, I'm sure others would appreciate that.

**Comment by amesas** [comment]
Hi @michaelbromley not Vendure related. We are still exploring Vendure.

If we go with Vendure I'm sure we will publish some plugins for it :)

**Comment by michaelbromley** [comment]
@amesas got it. OK well if you have any questions while evaluating Vendure, feel free to ask me in our [Slack group](https://join.slack.com/t/vendure-ecommerce/shared_invite/enQtNzA1NTcyMDY3NTg0LTMzZGQzNDczOWJiMTU2YjAyNWJlMzdmZGE3ZDY5Y2RjMGYxZWNlYTI4NmU4Y2Q1MDNlYzE4MzQ5ODcyYTdmMGU). 

I'll close this issue now.
