### ISSUE TITLE
Reindexing crashes on big installations

### ISSUE THREAD

**Issue by Izayda** [vendure-ecommerce/vendure#1120]
**Describe the bug**
Installation has 120k products * 12 channels. While reindexing it generates 4millions of operations.

It has two problems:
1. RAM consumption of both DefaultSearchPlugin and ElasticSearchPlugin
2. ERRCONNRESET on Elastic after sending operations to bulk api 

**To Reproduce**
Steps to reproduce the behavior (needs test):
1. Generate many variants with many channels
2. Try to reindex

**Expected behavior**
Reindex complete successfully with reasonable RAM consumption.

**Environment (please complete the following information):**
 - @vendure/core version: 1.2.0

**Additional context**
From slack: https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1632655423007600

**Comment by michaelbromley** [comment]
Perhaps I have a totally wrong mental model of what is going on here, but the way I read the code, it currently seems to work like this:

1. The `try-catch-finally` block starting on line 241 creates a new index for the reindexing. (242)
2. The original index gets copied over to this new index (265)
3. Point the variants alias at this new index (286)
4. Remove the alias which was pointing to the original index (294)
5. Delete the original index (313)
6. Delete the temp "reindex" alias (324)
7. After all that is done, we run the actual deletions and additions to the index from line 338 onwards. This is where we start populang all the bulk commands into the `operations` array, which gets really big.
8. On line 369 we actually execute these operations on the variant index.
9. Then the function immediately returns.

So given that, I if at line 369 we just update like 10% of the SKUs, then the variants index will be in a partially-complete state until the rest of the batched operations complete. That's what I don't get.

**Comment by Izayda** [comment]
Yeah, you are right. I'm sorry, I was pretty sure, that we implemented "silent" update of variants. But only "silent" index recreation on start of reindex job was implemented here https://github.com/vendure-ecommerce/vendure/pull/996 

But, as i can see, "silent" update of variants can be easily achieved just moving block of operations processing upper.

**Comment by ttournie** [comment]
We also go the issue because we have a huge amount of product in production and get the issue.

I am working on a fix for this issue.

Has a quick fix I tried to simply chunk the operation but I get some error on some chunks about channelID.

The best approche seems to chunk the request to the database (now we get ALL the product at once) and create all the operation related. Instead we could request X amount of  products, create the operation, then send them to ES, and continue for X more.

And Switch the alias when it's done. What do you think ?

**Comment by michaelbromley** [comment]
@ttournie yes, I agree with this approach. Are you planning to submit a PR for this?

**Comment by ttournie** [comment]
Sorry I did not see the msg.
I fixed it for us, but I guess I can make it into Vendure has a pull request :)

**Comment by ttournie** [comment]
I tried to make a PR : https://github.com/vendure-ecommerce/vendure/pull/1292
