### ISSUE TITLE
Cannot initialize project using npx, tried on ubuntu and windows

### ISSUE THREAD

**Issue by sparkdevv** [vendure-ecommerce/vendure#1121]
**Bug**
  ✔ Installing dependencies
  ✔ Generating app scaffold
  ✖ Initializing server
    →                                    ~~~~~~~~~~~~~~~~~~~
{"diagnosticText":"\u001b[96msrc/vendure-config.ts\u001b[0m:\u001b[93m44\u001b[0m:\u001b[93m33\u001b[0m - \u001b[91merror\u001b[0m\u001b[90m TS2322: \u001b[0mType 'PaymentMethodHandler<{ automaticSettle: { type: string; label: { languageCode: any; value: string; }[]; description: { languageCode: any; value: string; }[]; required: true; defaultValue: boolean; }; }>' is not assignable to type 'PaymentMethodHandler<ConfigArgs>'.\n  Type '{ automaticSettle: { type: string; label: { languageCode: any; value: string; }[]; description: { languageCode: any; value: string; }[]; required: true; defaultValue: boolean; }; }' is not assignable to type 'ConfigArgs'.\n    Property 'automaticSettle' is incompatible with index signature.\n      Type '{ type: string; label: { languageCode: any; value: string; }[]; description: { languageCode: any; value: string; }[]; required: true; defaultValue: boolean; }' is not assignable to type '(ConfigArgCommonDef<\"int\"> & WithArgConfig<{ inputType?: \"default\" | \"percentage\" | \"money\" | undefined; }>) | (ConfigArgCommonDef<\"float\"> & WithArgConfig<...>) | (ConfigArgCommonDef<...> & WithArgConfig<...>) | (ConfigArgCommonDef<...> & WithArgConfig<...>) | (ConfigArgCommonDef<...> & WithArgConfig<...>) | (Confi...'.\n        Type '{ type: string; label: { languageCode: any; value: string; }[]; description: { languageCode: any; value: string; }[]; required: true; defaultValue: boolean; }' is not assignable to type 'ConfigArgCommonDef<\"string\"> & WithArgConfig<{ options?: StringFieldOption[] | undefined; }>'.\n          Type '{ type: string; label: { languageCode: any; value: string; }[]; description: { languageCode: any; value: string; }[]; required: true; defaultValue: boolean; }' is not assignable to type 'ConfigArgCommonDef<\"string\">'.\n            Types of property 'type' are incompatible.\n              Type 'string' is not assignable to type '\"string\"'.\n\n\u001b[7m44\u001b[0m         paymentMethodHandlers: [dummyPaymentHandler],\n\u001b[7m  \u001b[0m \u001b[91m                                ~~~~~~~~~~~~~~~~~~~\u001b[0m\n","diagnosticCodes":[2322],"context":{"configFile":"/root/playground/shop-server/src/vendure-config.ts"}}

**To Reproduce**
1. npx @vendure/create shop-server
2. Error pops up

**Environment **
 - @vendure/core version: 1.1.5, 1.2.0, 1.2.2
 - Nodejs version: LTS
 - Database (mysql/postgres etc): sqlite

**Additional context**
It was working fine a month ago **BUT NOW ONLY WORKS WHEN LANGUAGE IS JAVASCRIPT**

**Comment by michaelbromley** [comment]
Thanks, I've had other reports on this. I think perhaps a dependency update may be to blame. I'll investigate this.

**Comment by michaelbromley** [comment]
Should be fixed in v1.2.3
