### ISSUE TITLE
[TypeOrmModule] Unable to connect to the database

### ISSUE THREAD

**Issue by islamian1337** [vendure-ecommerce/vendure#1135]
ORM is not getting connected to database even I have my configurations correct.

QueryFailedError: Can't DROP FOREIGN KEY `FK_20958e5bdb4c996c18ca63d18e4`; check that it exists
[run:server]     at new QueryFailedError (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\src\error\QueryFailedError.ts:9:9)
[run:server]     at Query.onResult (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\src\driver\mysql\MysqlQueryRunner.ts:193:37)
[run:server]     at Query.execute (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\node_modules\mysql2\lib\commands\command.js:31:14)
[run:server]     at PoolConnection.handlePacket (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\node_modules\mysql2\lib\connection.js:456:32)
[run:server]     at PacketParser.onPacket (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\node_modules\mysql2\lib\connection.js:85:12)
[run:server]     at PacketParser.executeStart (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
[run:server]     at Socket.<anonymous> (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\node_modules\mysql2\lib\connection.js:92:25)
[run:server]     at Socket.emit (events.js:400:28)
[run:server]     at Socket.emit (domain.js:470:12)
[run:server]     at addChunk (internal/streams/readable.js:290:12)
[run:server] error 10/6/21, 8:32 PM - [TypeOrmModule] Unable to connect to the database. Retrying (2)...
[run:server] QueryFailedError: Cannot drop index 'FK_43ac602f839847fdb91101f30ec': needed in a foreign key constraint
[run:server]     at new QueryFailedError (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\src\error\QueryFailedError.ts:9:9)
[run:server]     at Query.onResult (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\src\driver\mysql\MysqlQueryRunner.ts:193:37)
[run:server]     at Query.execute (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\node_modules\mysql2\lib\commands\command.js:31:14)
[run:server]     at PoolConnection.handlePacket (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\node_modules\mysql2\lib\connection.js:456:32)
[run:server]     at PacketParser.onPacket (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\node_modules\mysql2\lib\connection.js:85:12)
[run:server]     at PacketParser.executeStart (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
[run:server]     at Socket.<anonymous> (C:\Users\bitsnio\Desktop\Vue-Storefront-Vendure\backend\node_modules\mysql2\lib\connection.js:92:25)
[run:server]     at Socket.emit (events.js:400:28)
[run:server]     at Socket.emit (domain.js:470:12)
[run:server]     at addChunk (internal/streams/readable.js:290:12)

**Comment by michaelbromley** [comment]
This issue is being closed because further data was needed but was not provided. If you want to continue the thread, comment below with the required information and the issue can be re-opened.

**Comment by kaushal-enstead** [comment]
```
  dbConnectionOptions: {
        type: 'mysql',
        synchronize: true,
}
```
Version >= 3.3.8 throws this error when `synchronize: true`,
