### ISSUE TITLE
Delete Product 

### ISSUE THREAD

**Issue by TA50** [vendure-ecommerce/vendure#1175]
**Describe the bug**
When deleting a product and then query the orders or the product variants the query fails.
Orders query:  picture no 1
 ![picture no 1 orders-query](https://user-images.githubusercontent.com/38036633/137958961-65730143-1576-4e7f-8fdb-3156829ae877.png)
Error message:  picture no 2
 
![picture no 2 error message](https://user-images.githubusercontent.com/38036633/137958969-1b099c7e-4784-4190-9f21-5f1cc4e7af1e.png)

The error only arise when I try to extend into a product i.e. getting the product name from the variant.
**To Reproduce**
1. Go to Products page in the admin storefront.
2. Click on Actions in a product -> Delete

**Expected behavior**
The mechanism use to delete a product is a SoftDelete by setting the ‘DeleteAt’. I expect to delete all its relations as well i.e. product variants, order item, order line and so on. 

**Environment:**
 - @vendure/core version: 1.1.3
 - Nodejs version: 16.7.0
 - Database (mysql/postgres etc): mysql
    "@vendure/admin-ui-plugin": "^1.1.5",
    "@vendure/asset-server-plugin": "1.0.0-beta.4",
    "@vendure/core": "^1.1.3",
    "@vendure/email-plugin": "1.0.0-beta.4",
    "@vendure/ui-devkit": "^1.2.3",
    "firebase-admin": "^9.5.0",
    "google-libphonenumber": "^3.2.19",
    "mysql2": "^2.2.5",
    "typescript": "4.1.5"

**Additional context**
Deleted Product from the database: as you can see the DeletetAt field is set. picture no 3
 
![picture no 3 deleted product](https://user-images.githubusercontent.com/38036633/137958972-05369741-1436-4a7c-aed5-85a8296ac8e1.png)
The product variant related to the deleted product: as you can see the DeleteAt field is not set which causes the conflict. picture no 4
 
![picture no 4 related product variant](https://user-images.githubusercontent.com/38036633/137958974-d282dd2b-1626-48e0-a8c3-22ba9b88bf8d.png)

** attached 4 pictures.

**Comment by michaelbromley** [comment]
Hi,

First of all, I'm a bit confused by the screenshots - I don't see any errors there and you are not selecting the productVariant.product fields. Am I missing something?

But your description of the issue sounds like it is the same as #1125, which was fixed in v1.3. Can you upgrade and see if it is fixed for you?

**Comment by TA50** [comment]
Sorry for the confusion, it is my first issue on Github ever :). 
Yes, it seems close to #1125 I will upgrade and try to test it. 
Thanks.

**Comment by TA50** [comment]
I tried version 1.3 and it is now fixed
