### ISSUE TITLE
Allow adding a custom field to the PaymentMethod, ShippingMethod, CustomerGroup entities

### ISSUE THREAD

**Issue by nemo-js** [vendure-ecommerce/vendure#1185]
It would be very helpful, if we could create a custom field for PaymentMethods and ShippingMethods.

The use-case we want to implement is the following:
At the front-end we should display a different UI depending on the payment method (ie on cash just proceed, on Stripe redirect to Stripe etc)
Another use-case is that we want to hide the address UI when the Order is store-pickup

**Comment by michaelbromley** [comment]
I'll be adding custom field support on:

* CustomerGroup
* PaymentMethod
* Promotion
* TaxCategory
* TaxRate
* Zone

(ShippingMethod is actually already supported)
