### ISSUE TITLE
AdminUIPlugin's devMode unusable

### ISSUE THREAD

**Issue by manuelaguirre** [vendure-ecommerce/vendure#1190]
**Describe the bug**
When running `AdminUIPlugin` with `devMode: true` I get the log in page and I cannot login because the app is making requests to `localhost:4200/admin-api` that return a 404 error. Maybe it should be rewrited to point to `localhost:3000/admin-api` instead?

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version:1.3.0
 - Nodejs version: 14.16.0
 - Database (mysql/postgres etc): PostgreSQL

**Comment by manuelaguirre** [comment]
```
import {
    dummyPaymentHandler,
    DefaultJobQueuePlugin,
    DefaultSearchPlugin,
    VendureConfig,
} from '@vendure/core';
import { defaultEmailHandlers, EmailPlugin } from '@vendure/email-plugin';
import { AssetServerPlugin } from '@vendure/asset-server-plugin';
import { AdminUiPlugin } from '@vendure/admin-ui-plugin';
import { compileUiExtensions } from '@vendure/ui-devkit/compiler';
import path from 'path';

export const config: VendureConfig = {
    apiOptions: {
        port: 3000,
        adminApiPath: 'admin-api',
        adminApiPlayground: {
            settings: {
                'request.credentials': 'include',
            } as any,
        },// turn this off for production
        adminApiDebug: true, // turn this off for production
        shopApiPath: 'shop-api',
        shopApiPlayground: {
            settings: {
                'request.credentials': 'include',
            } as any,
        },// turn this off for production
        shopApiDebug: true,// turn this off for production
    },
    authOptions: {
        superadminCredentials: {
            identifier: 'superadmin',
            password: 'superadmin',
        },
        cookieOptions: {
            secret: process.env.COOKIE_SECRET || 'cookie-secret',
        },
    },
    dbConnectionOptions: {
        type: 'postgres',
        synchronize: true, // turn this off for production
        logging: false,
        database: 'vendure',
        host: 'localhost',
        port: 5432,
        username: 'vendure',
        password: 'vendure',
        migrations: [path.join(__dirname, '../migrations/*.ts')],
    },
    paymentOptions: {
        paymentMethodHandlers: [dummyPaymentHandler],
    },
    customFields: {},
    plugins: [
        AssetServerPlugin.init({
            route: 'assets',
            assetUploadDir: path.join(__dirname, '../static/assets'),
        }),
        DefaultJobQueuePlugin.init({ useDatabaseForBuffer: true }),
        DefaultSearchPlugin.init({ bufferUpdates: false, indexStockStatus: true }),
        EmailPlugin.init({
            devMode: true,
            outputPath: path.join(__dirname, '../static/email/test-emails'),
            route: 'mailbox',
            handlers: defaultEmailHandlers,
            templatePath: path.join(__dirname, '../static/email/templates'),
            globalTemplateVars: {
                // The following variables will change depending on your storefront implementation
                fromAddress: '"example" <noreply@example.com>',
                verifyEmailAddressUrl: 'http://localhost:8080/verify',
                passwordResetUrl: 'http://localhost:8080/password-reset',
                changeEmailAddressUrl: 'http://localhost:8080/verify-email-address-change'
            },
        }),
        AdminUiPlugin.init({
            route: 'admin',
            port: 3000,
            app: compileUiExtensions({
                outputPath: path.join(__dirname, 'admin-ui'),
                extensions: [{
                    extensionPath: path.join(__dirname, 'ui-extensions'),
                    ngModules: [{
                        type: 'lazy',
                        route: 'upload-file',
                        ngModuleFileName: 'file-uploader.module.ts',
                        ngModuleName: 'FileUploaderModule',
                    }],
                }],
                devMode: true
            }),
        }),
    ],
};

```

**Comment by manuelaguirre** [comment]
I get this message: `[run:server] ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/admin **` when I start it up and it got me confused. Thanks!

**Comment by HendrikMennen** [comment]
Now I have the same problem. Except that for me I can't use localhost:3000 in devmode. Without devmode everything works

**Comment by HendrikMennen** [comment]
![image](https://user-images.githubusercontent.com/25281882/199322952-789adf62-bd92-46f3-ad1f-622d53feb735.png)

**Comment by michaelbromley** [comment]
> Except that for me I can't use localhost:3000 in devmode.

What occurs when accessing localhost:3000/admin?

Also note that it can take a couple of minutes until the admin ui app has compiled and is ready to receive requests.

**Comment by HendrikMennen** [comment]
Seems like it compiles fine:
![image](https://user-images.githubusercontent.com/25281882/199324249-a3e092fb-acc4-4fb5-af3a-48dee5f16450.png)
I am still confused by setting the port for admin UI. If I have it on 3002 or 3000 does not seem to make a difference at all and it will start on 3000.

On 4200, I can access the admin UI but it fails finding the API
![image](https://user-images.githubusercontent.com/25281882/199324550-16fc2c49-a497-4f3c-b52d-92b147d1e8b9.png)

**Comment by michaelbromley** [comment]
Ah good. So what happens is that the Admin UI app actually runs on port 3002 (prod mode) or port 4200 (dev mode), but the AdminUiPlugin proxies that to port 3000/admin. That means you _always_ access it on port 3000, no matter what mode it is running in.

The reason that you see those Http failure errors when you try to access it on port 4200 is that there is a json file `vendure-ui-config.json` that is loaded during bootstrap (check your network tab) and this file tells the admin UI app what the url of the Admin API is. It defaults to `auto`, which means "use the same domain as whatever the admin ui app is running on", hence that causes an error when running on port 4200 because there is no corresponding API on that port.

**Comment by HendrikMennen** [comment]
Okay that makes sense but still doesn't solve my issue, or does it?
On localhost:3000/admin all resources seem to be missing
![image](https://user-images.githubusercontent.com/25281882/199326932-7dd06014-7f99-4ce0-959b-55d93b4d88dc.png)

**Comment by michaelbromley** [comment]
oh ok. What's the full url of eg. the styles.css request there?

And can you check the html source of the html file and see if there is a base tag in the head?

Also is your setup just a standard `@vendure/create` install with the ui-devkit added?

**Comment by HendrikMennen** [comment]
![image](https://user-images.githubusercontent.com/25281882/199332876-e1abf93a-0380-41c6-8a80-a2dab10e9821.png)

**Comment by michaelbromley** [comment]
hmm... strange that the base is just `/`. That is probably what's causing the assets to 404. 

Oh one important question - what version of Vendure are you using?

**Comment by HendrikMennen** [comment]
1.8.1 with Node v16.18.0 on Windows.

I tried to use v18.12.0 but had issues compiling.

**Comment by michaelbromley** [comment]
ok, this is strange. You can also try this:

```ts
 AdminUiPlugin.init({
      route: "admin",
      port: 3002,
      app: compileUiExtensions({
        outputPath: path.join(__dirname, "../admin-ui"),
        extensions: [
        ],
        devMode: true
      }),
     adminUiConfig: {
       apiHost: 'http://localhost',
       apiPort: 3000,
     }
```

and then see if it works on port 4200 in the browser.

**Comment by HendrikMennen** [comment]
Thanks, that does seem to work for me :)
