### ISSUE TITLE
Should we need to clear shippingLines while we save new shippingAddress for active order each time?

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#1195]
**Describe the bug**
while we first setShippingAddress for order, then we choosed a `eligible` shipping method

but while we changed shipping address to another, maybe before saved `shippingLines` is not `eligible` at this time,  we have no chance to reset `shippingLines`

1.  first we need to clear shippingLines for this order. provider us mutation `cleanOrderShippingMethod` for us.
2. or while we invoke  mutation`setOrderShippingAddress`, it will automatically check if current if `shippingMethod is `eligible` it not remove it automatically.

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 1.3.1
 - Nodejs version 14+
 - Database (mysql/postgres etc): mysql

**Additional context**

**Comment by michaelbromley** [comment]
Based on further discussion on Slack, the behaviour is fine now, but there exists 1 unhandled case:

When the current ShippingMethod becomes ineligible, and there is _no other_ eligible method, the `shippingLines` should be cleared (set to `[]`). Currently this does not happen - the ineligible method & shippingLines remain on the Order.
