### ISSUE TITLE
`@vendure/create` TypeORM SSL Option

### ISSUE THREAD

**Issue by Sean12697** [vendure-ecommerce/vendure#1205]
**Is your feature request related to a problem? Please describe.**

Yes, currently my `npx @vendure/create` log looks like the following, and I'm certain it's due to SSL being off / false (and should not be strict in development).

```bash
sean@pop-os:~/temp/e2e-vendure$ NODE_TLS_REJECT_UNAUTHORIZED='0' npx @vendure/create project-name
(node:23618) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

Welcome to @vendure/create v1.3.2!

Let's configure a new Vendure project. First a few questions:

✔ Which database are you using? › Postgres
✔ What's the database host address? … ec2-xx-xx-xxx-xxxx.eu-west-1.compute.amazonaws.com
✔ What port is the database listening on? … 5432
✔ What's the name of the database? … xxxxxxxxxxxxxxxxxxxx
✔ What's the database user name? … xxxxxxxx
✔ What's the database password? … ****************************************************************
✔ Which programming language will you be using? › TypeScript
✔ Populate with some sample product data? … no / yes
✔ What identifier do you want to use for the superadmin user? … superadmin
✔ What password do you want to use for the superadmin user? … superadmin

Setting up your new Vendure project in /home/sean/temp/e2e-vendure/project-name
This may take a few minutes...

  ✔ Installing dependencies
  ✔ Generating app scaffold
  ⠙ Initializing server
Error: Could not connect to the database. Please check the connection settings in your Vendure config.
[no pg_hba.conf entry for host "xxx.xxx.xxx.xx", user "xxxxxxxx", database "xxxxxxxxxxxxxxxxxxxx", SSL off]
    at throwConnectionError (/home/sean/.npm/_npx/fca31bc9a717a0f3/node_modules/@vendure/create/src/helpers.ts:345:11)
    at checkPostgresDbExists (/home/sean/.npm/_npx/fca31bc9a717a0f3/node_modules/@vendure/create/src/helpers.ts:336:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
  ✔ Installing dependencies
  ✔ Generating app scaffold
  ✖ Initializing server
    → [no pg_hba.conf entry for host "185.205.172.64", user "xxxxxxxx", database "xxxxxxxxxxxxxxxxxxxx", SSL off]
{"context":{"configFile":"/home/sean/temp/e2e-vendure/project-name/src/vendure-config.ts"}}
sean@pop-os:~/temp/e2e-vendure$
```

**Describe the solution you'd like**

An SSL option added into the the following user response gather and the value integrated into all of the relevant area's when initiating the project and then creating the `dbConnectionOptions` config.

https://github.com/vendure-ecommerce/vendure/blob/9bb676e5606716916cf71c0921a7f83fdf4cbe9d/packages/create/src/gather-user-responses.ts#L23-L107

**Additional context**

Even though the `npx @vendure/create` run does error, it does still generate the project. Modifying the `vendure-config.ts` files `dbConnectionOptions` to include `ssl: true` is a valid / hacky solution, although it does not populate the database with some sample product data if that option was selected during the create process.

**Comment by michaelbromley** [comment]
Thanks for the report. I think adding an ssl option to the prompts is a good solution.

**Comment by dipanshuhappy** [comment]
> Thanks for the report. I think adding an ssl option to the prompts is a good solution.

Hey any plan on this ? on when it will be released ?

**Comment by michaelbromley** [comment]
Hi, thanks for bringing this back to my attention.

I'm actually not that familiar with the ssl option, and looking at the docs for [node-postgres](https://node-postgres.com/features/ssl) and for [mysql](https://github.com/mysqljs/mysql#ssl-options) it looks like they take an object which specifies paths to certs.

It's not clear to me what setting it to `true` actually does. The TypeORM docs don't go into it - they just link to the mysql docs and there it does not even mention the boolean option.

Do you have an idea about this?

**Comment by dipanshuhappy** [comment]
> Hi, thanks for bringing this back to my attention.
> 
> I'm actually not that familiar with the ssl option, and looking at the docs for [node-postgres](https://node-postgres.com/features/ssl) and for [mysql](https://github.com/mysqljs/mysql#ssl-options) it looks like they take an object which specifies paths to certs.
> 
> It's not clear to me what setting it to `true` actually does. The TypeORM docs don't go into it - they just link to the mysql docs and there it does not even mention the boolean option.
> 
> Do you have an idea about this?

yes i do , actually its just required if you are using neon or azure postgres so it would be helpful if ssl mode would be set to true , at most it gonna affect the connection protocol
