### ISSUE TITLE
Collection Foreign key constraint error upon creating new

### ISSUE THREAD

**Issue by HarunKilic** [vendure-ecommerce/vendure#1215]
**Describe the bug**
When trying to create a new collection trough Admin UI, i get following error: 

`
insert or update on table "collection" violates foreign key constraint "FK_4257b61275144db89fa0f5dc059"
[run:server] QueryFailedError: insert or update on table "collection" violates foreign key constraint "FK_4257b61275144db89fa0f5dc059"
`

**To Reproduce**
1. Start a brand new project using `yarn create @vendure my-app`
2. Try to create a new collection with graphql, which should fail. Eg: 
`
mutation CreateCollection {
  createCollection(
    input: {
      filters: [{ code: "noexist", arguments: { name: "nop", value: "no" } }]
      translations: [
        {
          languageCode: en
          slug: "test"
          name: "test"
          description: "Just testing"
        }
      ]
    }
  ) {
    id
  }
}
`
3.  You should get an error that says code not found
4.  Try to create a new collection trough Admin UI
5.  Error occures

**Expected behavior**
There should not be any constraint errors, as the collection did not get created. 

**Environment (please complete the following information):**
 - @vendure/core version: 1.3.3
 - Nodejs version: 16.11.1
 - Database (mysql/postgres etc): postgres

**Comment by HarunKilic** [comment]
Workaround for this would simply to restart the server

**Comment by michaelbromley** [comment]
I reproduced this in the dev-server by doing the following:

1. Drop the `vendure-dev` database in postgres via pgadmin
2. start the dev server, using `DB=postgres`
3. Login as admin via Insomnia
4. Run this query via Insomnia:
    ```
    mutation {
	createCollection(
		input: {
			filters: [{ code: "noexist", arguments: { name: "nop", value: "no" } }]
			translations: [
				{
					languageCode: en
					slug: "test"
					name: "test"
					description: "Just testing"
				}
			]
		}
	) {
		id
	}
    }
    ```
5. Login to Admin UI
6. Attempt to create a new Collection with name "test".

Full error object:
```
{
  "message": "insert or update on table \"collection\" violates foreign key constraint \"FK_4257b61275144db89fa0f5dc059\"",
  "length": 282,
  "name": "QueryFailedError",
  "severity": "ERROR",
  "code": "23503",
  "detail": "Key (parentId)=(1) is not present in table \"collection\".",
  "schema": "public",
  "table": "collection",
  "constraint": "FK_4257b61275144db89fa0f5dc059",
  "file": "ri_triggers.c",
  "line": "2474",
  "routine": "ri_ReportViolation",
  "query": "INSERT INTO \"collection\"(\"createdAt\", \"updatedAt\", \"isRoot\", \"position\", \"isPrivate\", \"filters\", \"featuredAssetId\", \"parentId\") VALUES (DEFAULT, DEFAULT, DEFAULT, $1, DEFAULT, $2, DEFAULT, $3) RETURNING \"createdAt\", \"updatedAt\", \"isRoot\", \"isPrivate\", \"id\"",
  "parameters": [
    1,
    "[]",
    1
  ]
}
```

I'm pretty sure this has something to do with the caching of the `rootCollection`, but I need to debug more the exact sequence which causes the error.
