### ISSUE TITLE
[Admin UI] Product list is always empty when database is sql.js

### ISSUE THREAD

**Issue by vrosa** [vendure-ecommerce/vendure#1217]
**Describe the bug**
Product list view on Admin UI always displays an empty list when the data store is sql.js. Once you add a product using the UI or the GraphQL API you can see it in the database and the `products` query works fine but `search` (used behind the scenes on the Admin UI) doesn't.

**To Reproduce**
Steps to reproduce the behavior on a fresh new installation:
1. Click the 'Products' menu item under 'Catalog'
2. Click the '+ new product' button
3. Enter the details of a product and click 'Create'
4. Click the 'Products' menu item under 'Catalog' again

**Expected behavior**
The product you just added should be displayed on the list.

**Actual behavior**
The product list is empty.

**Environment (please complete the following information):**
 - @vendure/core version: 1.3.2
 - Nodejs version: v14.18.1
 - Database (mysql/postgres etc): sql.js

**Additional context**
Other entities such as Collections, Assets and Facets seem to work fine. I just started using Vendure so I'm not sure if the same issue is present elsewhere though.

**Comment by michaelbromley** [comment]
Hi,
Can you confirm that this only affects sql.js? Did it work as expected with another DB driver like SQLite?

From the description it sounds like maybe the worker is not functioning properly, since the search index is populated by way of a background job which runs on the worker process.

**Comment by vrosa** [comment]
It works fine with SQLite - I haven't tried others yet though. I'm doing bulk imports from Shopify locally using the Admin GraphQL API and faced several "database is locked" issues with SQLite so I moved to sql.js and everything went well except for the product list.

**Comment by michaelbromley** [comment]
I think I'm seeing the same problem with sql.js. Can you confirm whether you get the following error in your server console (from the worker process)?
```
"Expression tree is too large (maximum depth 1000)",
```

**Comment by vrosa** [comment]
I don't get that error message. It's unrelated to this problem but I do get a couple `MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process].` warnings when adding collections and products in a loop using the GraphQL API. I enabled tracing but the stack trace is not helpful unfortunately.

I'm not familiar yet with TypeORM or sql.js but if I add `console.log(qb.getQuery())` just before [this return statement](https://github.com/vendure-ecommerce/vendure/blob/6bc01aae230646118fac3c103793896b326d68c6/packages/core/src/plugin/default-search-plugin/search-strategy/sqlite-search-strategy.ts#L108) the query works, and even if I remove it and restart the server the list of products still returns fine from there on 🤷🏻‍♂️

**Comment by vrosa** [comment]
I'm closing this issue as it's not relevant to me anymore. Updating the search index gets the job done.
