### ISSUE TITLE
More Events for each entity

### ISSUE THREAD

**Issue by Draykee** [vendure-ecommerce/vendure#1219]
**Is your feature request related to a problem? Please describe.**
I would like to know when a user get's verified. Currently there is no event for this. Having more events can be extremly helpful for analyzing activities.

**Describe the solution you'd like**
A event for each entity and every special activity (like coupon code usage, promotions, etc.)
Maybe we should make a list first, but implementing it should be easy.

**Describe alternatives you've considered**
Overwriting each resolver. But that's a hughe overhead

**Comment by Draykee** [comment]
@michaelbromley somehow like this? 

So at first I think we can generalize it to this:
```
EntityEvent<T> extends VendureEvent {
  type: 'created' | 'updated' | 'deleted',
  entity: T;
}
```

### Address
_Example: Maybe a plugin that groups customer by locations_
- [x] CustomerAddressEvent

### Administrator
_Example: Maybe to add notifications for more security_
- [ ] AdministratorEvent (`EntityEvent<Administrator>`)

### Asset
_Example: Maybe the creator is important for copyrights_
- [x] AssetEvent (maybe also reword with `EntityEvent` and the `creator: User`)

### Channel
_Example: For all marketplace plugins to create additional data for a newly generated channel_
- [ ] ChannelEvent (`EntityEvent<Channel>`, `creator: User`)

### Collection
_Example: Maybe a plugin that auto disables a collection after some time, so we need to start a cronjob when created_
- [ ] CollectionEvent (`EntityEvent<Collection>`, `creator: User`)

### Country
_Example: - no clue -_
- [ ] CountryEvent (`EntityEvent<Country>`)

### Customer
- [x] CustomerEvent

### CustomerGroup
- [x] CustomerGroupEvent

etc.

**Comment by michaelbromley** [comment]
Yes perfect, though I don't think we need to list examples.

**Comment by Draykee** [comment]
I've updated the list. Maybe we can ask on slack if someone needs a special event. (We need a `UserVerifiedEvent` for example)

**Comment by Draykee** [comment]
What do you think about this:
```
class VendureEntityEvent<T> extends VendureEvent {
  type: 'created' | 'updated' | 'deleted',
  entity: T;
  input?: any; // the mutation input used for the event
  initiator?: User; // the user that initiated the entity operation
}
```

Optional properties `input` and `initiator`:
**PRO**: More information on the context where/how the event was published
**CON**: It's only optional and maybe not always present

**Comment by michaelbromley** [comment]
@Draykee yes this makes sense. We could deprecate the specific `<entity type>Event` events and replace them with this. For now we'd have to publish both, but remove the specific versions in v2.0.

Rather than the `initiator` field, why not include `ctx`, since it is possible to get the initiatior from that object using `ctx.activeUserId` already, plus RequestContext provides a whole bunch of other useful info, like which API & channel was being used etc.

**Comment by Draykee** [comment]
@michaelbromley This feature is pretty urgent for my master thesis about gamification. So maybe I'll start working on this soon.

One more question, shall I place every event inside the events directory? Or inside the related entity directory?

**Comment by michaelbromley** [comment]
Put any new events next to the existing ones in the "events" dir. If you want to work on this, make a PR against the `minor` branch and we can get this into the v1.4 release, which I expect to land in the next month-ish.

**Comment by Draykee** [comment]
@michaelbromley  In an `type: 'update'` event, is it better to store the "before" entity or the "updated" entity? I think the "before" entity might be better, because the event subscriber can still get the new updated one from database but not the one before updating it. Furthermore the `input` property can be used to understand what changed.

**Comment by Draykee** [comment]
Are `ProductOptionGroup`s and `ProductOption`s never deleted? At least I couldn't find a function for that inside the services.

**Comment by Draykee** [comment]
@michaelbromley I think I now covered most of the Entity Events. I just would like to ask for assitance with the Order entity.
I don't really know what operations can be executed and which one are covered by the stage transition events.

**Comment by Draykee** [comment]
Resolved with: https://github.com/vendure-ecommerce/vendure/pull/1222
