### ISSUE TITLE
elasticsearch-plugin: Allow custom sort parameter input

### ISSUE THREAD

**Issue by Draykee** [vendure-ecommerce/vendure#1220]
**Is your feature request related to a problem? Please describe.**
Currently we can only sort by price and name using the elasticsearch plugin.

```GraphQL
"Current definition of sort parameter"
input SearchResultSortParameter {
    name: SortOrder
    price: SortOrder
}
```
Those fields are then hardcoded and parsed into the `sort` field of the elasticseach request body.
```JS
const sortArray = [];
    if (sort) {
        if (sort.name) {
            sortArray.push({
                'productName.keyword': { order: sort.name === SortOrder.ASC ? 'asc' : 'desc' },
            });
        }
        if (sort.price) {
            const priceField = 'price';
            sortArray.push({ [priceField]: { order: sort.price === SortOrder.ASC ? 'asc' : 'desc' } });
        }
    }
```

**Describe the solution you'd like**
I would like to have an option to push additional sort parameters to the `sortArray`. I guess the only way to do that is another option inside the `searchConfig` configuration.

```TS
mapSort?: (input: SearchInput) => string[]; // default = [ ]
 ```

The biggest problem is that we are not able to extend a graphQL input (defined in `packages/core/src/api/schema/common/common-types.graphql`). Maybe a search plugin needs to define those to generate them at runtime?

**Describe alternatives you've considered**
I'm not sure if we are able to apply sorting within the query, but if not there is no alternative.

**Comment by michaelbromley** [comment]
Hi, could this not be solved with the existing [ExtendSearchInputType](https://www.vendure.io/docs/typescript-api/elasticsearch-plugin/elasticsearch-options/#extendsearchinputtype) option, combined with mapQuery?

**Comment by Draykee** [comment]
No this is not possible. 
1. `ExtendSearchInputType` only allows primitive graphql types and not the SortOrder type.
2. `mapQuery` is only used for the `query` property in the elasticsearch request body. I think sort parameters needs to be applied with the `sort` property. (But I'm not 100% sure)

**Comment by michaelbromley** [comment]
OK got it, thanks for clarifying. I'll review the PR later today 👍

**Comment by Draykee** [comment]
Resolved with: https://github.com/vendure-ecommerce/vendure/pull/1230
