### ISSUE TITLE
Allow collections to filter by different methods

### ISSUE THREAD

**Issue by HarunKilic** [vendure-ecommerce/vendure#1223]
**Is your feature request related to a problem? Please describe.**

As of now, the collections will calculate products by parent collections. 
The product itself should not be aware of the structure in the collection tree. It should just concern about the facet itself. 
Problems is that: 

1. The manager has to know how the collection tree is, and then assign facets to the product by collection tree structure. 
2. When a collection is changed. Those products which is assigned to this collection, will not be displayed, as the parent might get changed and the products won't have the right facets. 

**Describe the solution you'd like**
I would like to have the collections isolated. So that it won't care about its parents, but only the filters it has. 
It would be better if the parents included the products by its own filters, AND also the products by its children. 

**Describe alternatives you've considered**
Maybe different strategies. I can imagine that in some usecase the current parent filtering would fit better. So choosing between strategies would be nice. Maybe also coding custom strategies.

**Comment by michaelbromley** [comment]
I think this is now solved by #1382, which allows you to control filter inheritance from parent collections.
