### ISSUE TITLE
Allow for a bullMqJobQueue to be drained

### ISSUE THREAD

**Issue by alexisvigoureux** [vendure-ecommerce/vendure#1228]
**Is your feature request related to a problem? Please describe.**
We use BullMQJobQueuePlugin. When importing many products/variants a lot of jobs are created (update-search-index, apply-collection-filters). Even with a high concurrency, these jobs take several hours to be processed.

**Describe the solution you'd like**
We would like to be able to drained the `update-search-index` queue of all these pending jobs so that we can run a job to rebuild the index.

Here is a quick proposal, what do you think?
```Typescript
//class BullMQJobQueueStrategy
async drainJobs(queueNames?: string[]): Promise<any> {
        const jobsToDelete = await this.findMany({
            options: {
                filter: {
                    queueName: {
                        in: queueNames
                    },
                    state: {
                        in: ['wait', 'delayed'] // We could also propose this as a parameter
                    }
                },
                filterOperator: LogicalOperator.AND
            }
        } as JobListOptions)

        try {
            return await Promise.all(jobsToDelete.items.map(item => {
                if (item.id) {
                   return this.queue.remove(item.id.toString())
                }
            }))
        } catch (e) {
            Logger.error(e.message, loggerCtx, e.stack);
            return 0;
        }
    }
```

**Describe alternatives you've considered**
Open a new connection to the queue in a plugin.

**Comment by alexisvigoureux** [comment]
Progress point, we have decided to use https://taskforce.sh/ in the exceptional case where we need to drain the job queue.

**Comment by michaelbromley** [comment]
OK, glad to see you found a solution you can work with right away. Also that you are supporting the BullMQ team by using their paid product 👍 

For the record, it should be possible to use a [JobBuffer](https://www.vendure.io/docs/typescript-api/job-queue/job-buffer/) to have fine-grained control over what jobs get eventually passed to BullMQ.
