### ISSUE TITLE
customField with List and Options Error upon saving

### ISSUE THREAD

**Issue by bbtronald** [vendure-ecommerce/vendure#1241]
Hi Guys,

I created customField type string with list true, But when i update the customer profile there is an error even the variable input is correct.

**ERROR**
`The custom field 'interested_in' value ['Womenswear,Menswear,Childrenswear,Petswear,Experiences'] is invalid. Valid options are ['Womenswear', 'Menswear', 'Childrenswear', 'Petswear', 'Experiences']`

**Query Variable**
![image](https://user-images.githubusercontent.com/78782661/143204227-9f5ae7b4-f539-4ec0-9b77-a79fd7733e82.png)

**ADMIN UI**
![image](https://user-images.githubusercontent.com/78782661/143203550-5563ea74-d23d-4ee2-a7e7-e9b6d74fed25.png)

**customField CONFIG**
`{
      name: 'interested_in',
      label: [{
        languageCode: LanguageCode.en,
        value: "I'm interested in"
      }],
      type: 'string',
      list: true,
      options: [
        { value: 'Womenswear' },
        { value: 'Menswear' },
        { value: 'Childrenswear' },
        { value: 'Petswear' },
        { value: 'Experiences' },
      ],
      nullable: true
    },`

**Comment by bbtronald** [comment]
Hi @michaelbromley  how can i download the fixes on this one? is there a beta version that i can use to edit my package.json?

**Comment by michaelbromley** [comment]
Hi, you can update your packages to v1.4.0-beta.0 which contains the fix. I am also planning to release v1.4.0 later today, so you can also just wait for that.
