### ISSUE TITLE
Enable Slack Bot Notification

### ISSUE THREAD

**Issue by bobby91560** [vendure-ecommerce/vendure#1244]
**Is your feature request related to a problem? Please describe.**
Hello ! 👋 
My team and I would like to get all new notification about issues, release and so on... from your repository with the slack github plugin help

**Describe the solution you'd like**
To achieve that, you just have to enable it for you repo. 
Issue describe here : https://github.com/integrations/slack/issues/454

It would be so great to have that !
Thanks in advance

**Comment by michaelbromley** [comment]
Hi!

Ok, I enabled the slack integration. Can you confirm whether it is working for you now?

**Comment by bobby91560** [comment]
It works !!
Thank you 🙏
