### ISSUE TITLE
Not catch exception in asset.service create function

### ISSUE THREAD

**Issue by ttournie** [vendure-ecommerce/vendure#1246]
**Describe the bug**
if there is an exception in the `createAssetInternal` function called in the `create` function of the asset.service, there is an error message saying that the error was not managed/catch.

**To Reproduce**
1. Simply make the `createAssetInternal` function throw when calling create

**Expected behavior**
This error should be managed, the `create` function should reject.
You can fix that by adding a Try/catch in the create function around `createAssetInternal` and reject in the catch

**Environment (please complete the following information):**
 - @vendure/core version: 1.3.2
 - Nodejs : 14.17
 - Database postgres

**Comment by michaelbromley** [comment]
Thanks for the report. Do you have any idea what particular part of the asset creation process failed? Or is there no indication?

**Comment by ttournie** [comment]
This is the error I get 

error: Could not create Asset preview image: Input buffer contains unsupported image format

**Comment by michaelbromley** [comment]
Perfect, thank you 👍
