### ISSUE TITLE
Coupons support

### ISSUE THREAD

**Issue by rcorzogutierrez** [vendure-ecommerce/vendure#125]
Add in the "marketing" section the option to generate coupons.
The coupons are very used incentives in e-commerce. They are usually a combination of words associated with a marketing promotion. It is important that these coupons have an associated budget limited, as well as a date term. In addition the conditions must be defined (in purchases of $ 50 or more)

**Comment by michaelbromley** [comment]
Hi, thanks for the suggestion. Coupons are planned, and will be an extension of the existing "promotions" mechanism. Date limits and compound conditions (e.g. minimum order amount) are already supported, so should work together as you describe.

> It is important that these coupons have an associated budget limited

Can you elaborate on this part?

**Comment by rcorzogutierrez** [comment]
The idea is to have control of the use of coupons and that these never exceed the estimated budget. The coupons are discounts that will be made to the total of an order. For example if I put a budgeted ceiling value of $ 10,000 dollars, once they were consumed, the system would not allow more to apply it by the customer. The option of "unlimited budget" could also be considered..

**Comment by michaelbromley** [comment]
So a given coupon code could be used over multiple orders until its budget is exhausted? Kinda like a prepaid store card (Starbucks card etc)?

**Comment by rcorzogutierrez** [comment]
The dynamic is that this coupon code is used only once for a placed order. A customer should not use the same coupon in different orders. It is not a budget per client, it is a budget for specific promotion. In general, this amount is assumed by the marketing area, to encourage customers to buy, so it is considered an expense.

**Comment by michaelbromley** [comment]
> The dynamic is that this coupon code is used only once for a placed order. A customer should not use the same coupon in different orders.

Got it. That's the way I am planning to implement. Not sure exactly when this will be done, but probably sometime in the next couple of months.

**Comment by michaelbromley** [comment]
Closed in favour of #174
