### ISSUE TITLE
Type ORM doesn't return foreign keys

### ISSUE THREAD

**Issue by SamanFekri** [vendure-ecommerce/vendure#1252]
**Describe the bug**
I want to filter product based on an custom field which is a relation.
The type orm doesn't return it and doesn't filter query by that.

**Environment (please complete the following information):**
- Type orm module

**Comment by SamanFekri** [comment]
Hi
I customize my product entity with adding custom field to it in `vendure-config.ts`:
```
{
    name: "seller", type: "relation", entity: Customer
  },
```
and after that in a resolver I want to make filter it by Id.
I get it by this code
```
let x = await this.connection.getRepository(Product).find()
console.log(x)
```

I check all the data there was no sellerId in it. I must use raw query for this purpose and we know raw queries are dangerous.

**Comment by michaelbromley** [comment]
Thanks. Try it like this:
```ts
const product= await this.connection
  .getRepository(ctx, Product)
  .find({ 
    relations: ['customFields.seller'],  
  });
```

**Comment by SamanFekri** [comment]
This works for me. I think the method you said is also works. thanks alot.
```
private readonly relations = ['featuredAsset', 'assets', 'channels', 'facetValues', 'facetValues.facet', 'customFields.seller'];
this.listQueryBuilder
      .build(Product, options, {
        relations: this.relations,
        channelId: ctx.channelId,
        where: {deletedAt: null, customFields:{ seller: {id: 2}}},
        ctx,
      })
      .getManyAndCount()
      .then(async ([products, totalItems]) => {
        const items = products.map(product =>
          translateDeep(product, ctx.languageCode, ['facetValues', ['facetValues', 'facet']]),
        );
```
