### ISSUE TITLE
Use a custom interceptor into internal resolver

### ISSUE THREAD

**Issue by bobby91560** [vendure-ecommerce/vendure#1253]
Hello ! 👋 
**Is your feature request related to a problem? Please describe.**
I would like to know if there was a way to use a custom interceptor in an internal resolver?
We would like to put some logic before the payment resolver was called and we thought that interceptor is the best way to add it
**Describe the solution you'd like**
Maybe there is a way by making a 'general' interceptor hack that checks the endpoint in the context to trigger

Thanks in advance !

**Comment by michaelbromley** [comment]
Hi!
Yes this should be possible. 

You can define a global interceptor using this format in your plugin metadata:
```ts
 providers: [
    {
      provide: APP_INTERCEPTOR,
      useClass: MyInterceptor,
    },
  ],
```

In your interceptor's `intercept()` method, you can extract data about the current GraphQL operation:
```ts
import { GqlExecutionContext } from '@nestjs/graphql';

// ...

const graphQlContext = GqlExecutionContext.create(context);
const info = graphQlContext.getInfo();
```

**Comment by bobby91560** [comment]
Ok perfect it works like a charm ! 
Thank you 😊
