### ISSUE TITLE
Add OrderEvent (created - updated - deleted)

### ISSUE THREAD

**Issue by davidspiessens** [vendure-ecommerce/vendure#1256]
**Is your feature request related to a problem? Please describe.**
I want to react to updates on custom fields on an order.

**Describe the solution you'd like**
Add OrderEvent

**Describe alternatives you've considered**
none

**Additional context**
none

I can make a PR for this?

**Comment by michaelbromley** [comment]
Hi,

This is a good suggestion and should go into v1.4, which will probably be released this week. A PR is welcome.

Are you thinking of publishing the event when a call is made to `setOrderCustomFields`? 

This issue also made me realize that we are missing events for OrderLine. Would you like to also have a go at adding an OrderLineEvent?

**Comment by michaelbromley** [comment]
@davidspiessens I'm planning on cutting the v1.4 release tomorrow probably. Do you think this PR will be ready by then?

**Comment by michaelbromley** [comment]
The original issue was already implemented (forgot to close this at the time), and the OrderLine events feature is covered by #1316 , so I'll close this one now.
