### ISSUE TITLE
Allow `ID` type can be list on `xxxxFilterParameter`, For filter `ID` allow it to be filtered by Equals, Not equals,In,NotIn

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#1259]
**Is your feature request related to a problem? Please describe.**

Allow `ID` type can be list on `xxxxFilterParameter`, For filter `ID` allow it to be filtered by Equals, Not equals,In,NotIn

in some case like below  i have `entity` as follow code
```

  /**
   * https://typeorm.io/#/relations/joincolumn-options
   */
  @ManyToOne(() => LensProcessOption)
  lensProcessOption: LensProcessOption;

  /**
   * ID type 
   */
  @Column()
  lensProcessOptionId: ID;

  /** 
   * https://typeorm.io/#/relations/joincolumn-options
   */
  @ManyToOne(() => LensProcessTemplate)
  lensProcessTemplate: LensProcessTemplate;

  /**
   *  ID type 
   */
  @Column()
  lensProcessTemplateId: ID;
```

in service layer i have below code
```ts
 Promise<PaginatedList<LensProcessConfigItem>> {
    return this.listQueryBuilder
      .build(LensProcessConfigItem, options, {
        ctx,
        relations: ['lensProcessOption', 'lensProcessOption.translations', 'lensProcessTemplate'],
      })
```
the query Builder , options   it support me query filter like
```ts
filter.lensProcessOptionId = {
          eq: String(lensProcessOptionId),
        };
      }
```
but in front end , if LensProcessConfigItemFilterParameter don't allow me using `lensProcessOptionId`  i  have to write below `Query`
```ts
extend type Query {
    "Query all lens process template config item list"
    lensProcessConfigItems(
// manually add it as parameter
      lensProcessTemplateId: ID
// manually add it as parameter
      lensProcessOptionId: ID
      options: LensProcessConfigItemListOptions
    ): LensProcessConfigItemList!
```

manually add
```ts
 lensProcessTemplateId: ID
  lensProcessOptionId: ID
```

 in fact if the options (LensProcessConfigItemListOptions) can list ID type as listOption, i can avoid this duplicated works

**Describe the solution you'd like**

Allow `ID` type can be list on `XXX FilterParameter`, For a filter on ID, it would make sense to allow it to be filtered by:
Equals
Not equals
In
Not in

**Additional context**
vendure@ v1.4.0-beta.0

**Comment by Draykee** [comment]
To be honest I don't quite get what you need. I don't get why you have both `lensProcessOption` and `lensProcessOptionId`. I think you can just use `@JoinColumn()` to indicate that the you want the id (foreign key) to be on this side of the relation.

Do you want "_smarter_" generated FilterOptions for paginated lists?

**Comment by tianyingchun** [comment]
use  @JoinColumn()  and have both lensProcessOption and lensProcessOptionId is because i query this entity avoid  using `relation` join.

**Comment by tianyingchun** [comment]
because it can be auto list on `graphql` `xxxxFilterParameter`( lensProcessOptionId) in the front, i don't need wirte duplicated `Query` parameter to do this.
