### ISSUE TITLE
Google Analytics support

### ISSUE THREAD

**Issue by rcorzogutierrez** [vendure-ecommerce/vendure#126]
You can't just depend upon the analytics reports provided by your shopping cart. It should be complemented with Google Analytics Ecommerce tracking. It's only by using Google Analytics ecommerce tracking, you can correlate sales data with website usage data like sessions, bounce rate, traffic source/medium, landing page etc.

**Comment by michaelbromley** [comment]
Is there some aspect of GA support that should be implemented on the server? As far as I know it is a client-side thing (adding the script tag to the storefront).

**Comment by rcorzogutierrez** [comment]
everything is on the client's side, but a more complex implementation needs to be done on the confirmation page

**Comment by michaelbromley** [comment]
Ok, that's what I thought. To clarify, this repo is only the backend (a GraphQL API server), so nothing here relates to the client side. The idea with Vendure is that you use this backend and build your own front-end client application, in which you are free to implement Google Analytics support etc.
