### ISSUE TITLE
EmailPlugin smtp: allow to use smtp-url

### ISSUE THREAD

**Issue by macrozone** [vendure-ecommerce/vendure#1261]
**Is your feature request related to a problem? Please describe.**

server environments might define a env var with the full smtp url. Something like:

```
MAIL_URL=smtp://username:password@hostname.example.org:2525
```

**Describe the solution you'd like**

smtp-transport allows to use `url` instead of host/port/auth as an alternative

**Describe alternatives you've considered**

none

**Additional context**

none

**Comment by michaelbromley** [comment]
Yes, we can expose this option, that sounds reasonable. For now you'll have to parse the url into its parts as a work-around.

**Comment by amadeusalfa** [comment]
I also came across this and (in the meantime?) this should be possible:

```ts
    EmailPlugin.init({
      ...
      transport: {
        type: 'smtp',
        url: '...',
      },
    }),
```

See: https://github.com/vendure-ecommerce/vendure/pull/1781

**Comment by michaelbromley** [comment]
Ah thanks for pointing that out! So this can be closed then 👍
