### ISSUE TITLE
Custom field relation list component not rendered (vendure 1.4-beta.0)

### ISSUE THREAD

**Issue by Draykee** [vendure-ecommerce/vendure#1282]
**Describe the bug**
Before update to 1.4:
![image](https://user-images.githubusercontent.com/19676051/145616780-0d155cec-e7f7-4bf9-8b8b-decbfa680ad7.png)

After update to 1.4:
![image](https://user-images.githubusercontent.com/19676051/145616837-322cc998-7b3f-4330-ab5b-de43c5c85875.png)

My changes done to fit the component to the vendure 1.4 style with `FormInputComponent`:
![image](https://user-images.githubusercontent.com/19676051/145617303-3ad60c5a-b21e-4162-a652-035a775c3383.png)
I don't even get the console log print from the `ngOnInit` lifecycle function.

```TS
// inside my module
providers: [
        // Deprecated way of implementing the component (was workin pre 1.4)
        // registerCustomFieldComponent('FacetValue', 'childFacetValue', ChildFacetValueComponent),
        // Attempt for vendure 1.4
        registerFormInputComponent('child-facet-value-input', ChildFacetValueComponent),
 ]
```

```TS
/// plugin.ts
config.customFields.FacetValue.push({
            name: 'childFacetValue',
            type: 'relation',
            entity: FacetValue,
            list: true,
            public: true,
            eager: false, // can't load eager because of ring dependency
            ui: { component: 'child-facet-value-input' }, // attempt for 1.4
        });
```

My guess is that the ui for either `non-eager loaded` or `list loaded` customFields are not working.

**To Reproduce**
1. See screenshots and code snippets

**Expected behavior**
A custom component used for the customField

**Environment (please complete the following information):**
 - @vendure/core version: 1.4-beta.0

**Comment by michaelbromley** [comment]
Thanks for the report! Fixed.
