### ISSUE TITLE
Allow EntityHydratorService to hydrate customField relations

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#1284]
**Describe the bug**

if we have defined customized fields named `visualFrameAsset` on `productVariant`  entity via

 ```ts
// it wont't be list on productVariant.customFields.

    type: 'relation',
    name: 'visualFrameAsset',
    nullable: true,
    entity: Asset,
    eager: true,
    public: true,
  },
```
while we access `visualFrameAsset` via `orderLine.productVariant.customFields.visualFrameAsset` it not automatically list in orderLine context.

if we defined normal customized field like below (it works fine)

``` ts
type: 'int',
    name: 'costPrice',
    nullable: false,
    public: false,
    defaultValue: 0,
```

**To Reproduce**
1. Write an plugin A , extends customized fields `visualFrameAsset` via `config.customFields.ProductVariant.push(...productVariantCustomFields);`
in `productVariantCustomFields` we defined as below
```ts
  {
    // ”镜片流程中的“可视化展示的透明镜框正面图
    type: 'relation',
    name: 'visualFrameAsset',
    nullable: true,
    entity: Asset,
    eager: true,
    public: true,
  },
```
2. in front end `Query` active  order, access `orderLine.productVariant.customFields` it could not list property `visualFrameAsset`

**Expected behavior**
it can correctly list type ===`relation` field via `orderLine.productVariant.customFields.visualFrameAsset`.

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.0-beta-0
 - Nodejs version 14+
 - Database (mysql/postgres etc): mysql

**Additional context**

**Comment by michaelbromley** [comment]
After further discussion in Slack, the actual issue here is that when you have a relation custom field defined, it is not automatically joined when working _in a resolver_. When accessing via the GraphQL API it works fine.

So the solution we came to is that the EntityHydratorService should also be able to hydrate custom field relations:

```ts
await this.entityHydratorService.hydrate(ctx, productVariant, { relations: ['customFields.myRelation'] });
```
