### ISSUE TITLE
Timeout on indexing buffer of collection jobs

### ISSUE THREAD

**Issue by alexisvigoureux** [vendure-ecommerce/vendure#1287]
**Is your feature request related to a problem? Please describe.**
We use [BullMQJobQueuePlugin](https://www.vendure.io/docs/typescript-api/job-queue-plugin/bull-mqjob-queue-plugin/) for our indexing jobs with `bufferUpdates: true`. The timeout on the collection indexing job is 3 minutes [here](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/plugin/default-search-plugin/search-job-buffer/search-job-buffer.service.ts#L57). 
This is problematic for our application because the job lasts longer. So we have this error:
```
Error: Job 39039 update polling timed out after 180000ms. The job may still be running.
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
at processTimers (internal/timers.js:500:7)
at listOnTimeout (internal/timers.js:557:17)
...
at TapSubscriber._tapNext (/application/node_modules/@vendure/core/dist/job-queue/subscribable-job.js:51:27)
```

The collection indexing jobs work well but it logs errors.

**Describe the solution you'd like**
A solution could be to make this polling deactivatable or to make the timeout configurable.
Other solution can be to try/catch the subscribableCollectionJobs in a debug log.

**Comment by michaelbromley** [comment]
Hi, thanks for the report. Can you give me an idea of how many collections & product variants you are working with, and how long the collection filters job usually takes?
