### ISSUE TITLE
Initializing server crashes

### ISSUE THREAD

**Issue by Badyl1g** [vendure-ecommerce/vendure#129]
**Describe the bug**
After running npx @vendure/create vendure-example I get an error:
`Interface field PaginatedList.items expects type [Node!]! but ProductList.items is type [Product!]!.`

**To Reproduce**
1. Run npx @vendure/create <app-name>

**Expected behavior**
Server should initialize without errors

**Environment (please complete the following information):**
 - @vendure/core version:
 - Nodejs version: v10.15.3
 - Database (mysql/postgres etc): SQLite

**Additional context**
Screenshot: 
<img width="1172" alt="vendure-error" src="https://user-images.githubusercontent.com/27491471/61277866-50514a00-a7b3-11e9-9bf3-38fb63e6f5b6.png">

**Comment by michaelbromley** [comment]
Thanks for the report. I'm investigating right now. I suspect it may be due to some dependency version which has increased with a breaking change...

**Comment by michaelbromley** [comment]
@Badyl1g I just published 0.1.2-beta.8. This should fix the issue.

**Comment by Badyl1g** [comment]
Great! Thanks for spending time on this
