### ISSUE TITLE
Job data truncates after large list product variants or channel need to be indexed

### ISSUE THREAD

**Issue by simpian** [vendure-ecommerce/vendure#1298]
**Describe the bug**

I have about 15 channels and 1200 variants, when we add/update new product variants, vendure job kicks in to update index, however whenever we add/update a new channel, system is sending a request to job queue to update index for that specific channel and job data can be huge, when i use default job queue, job data gets truncated and resulted in a malformed JSON string.

Here's the article for different simple column types for text, right now, job data column is using `simple-json` and translated to `text` in MySQL, i wonder if we could change this to `longtext` which can store more strings hence enabling default job queue to handle larger job data

https://chartio.com/resources/tutorials/understanding-strorage-sizes-for-mysql-text-data-types/

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version:
 - Nodejs version
 - Database (mysql/postgres etc):

**Additional context**

**Comment by michaelbromley** [comment]
I've revisited this, here are some relevant issues in the TypeORM repo:

- https://github.com/typeorm/typeorm/issues/6017
- https://github.com/typeorm/typeorm/pull/6152#issuecomment-640115629

So to support longer data types for MySQL, we'd need to move away from the `simple-json` type we currently use. This could be potentially be quite disruptive, so I'd like to avoid it.

The options for people running into this are therefore:

- Use postgres, where the `text` type [has unlimited length](https://www.postgresql.org/docs/9.6/datatype-character.html)
- Use an alternative job queue strategy, such as our BullMQ (Redis) integration.
