### ISSUE TITLE
Make it easier to obtain links to assets

### ISSUE THREAD

**Issue by skid** [vendure-ecommerce/vendure#1305]
I would like to be able to use Vendure as an asset manager for a rudimentary CMS plugin. For example, I can add my own images via Markdown or plain HTML, but for that I'll need to copy an image asset URL. Currently the way to do this is to right-click -> copy image URL.

It would be nice to have several copyable links for different previews sizes displayed in the asset manager UI.

**Comment by xXWarMachineRoXx** [comment]
Hi,

It's nice to see links in the admin. but the link urls are dynamic and I cannot form a query that would provide me a link for the asset image.

Is this already possible?
