### ISSUE TITLE
Mollie payments - Orders are not updated to canceled 

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#1319]
**Describe the bug**
When an order in Mollie gets canceled, it calls a webhook (Vendure instance). Currently, the Mollie plugin only updates orders when incoming webhook status is `paid`.

Order should also be updated for statuses canceled and expired.

:warning: **Open point: Once an order is canceled, a user cannot try and pay for the order again and looses his cart/order. How should we handle this?**

**To Reproduce**
1. Pay for an order with a Mollie test account
2. Click on 'failed payment'
3. Order in Vendure is still PaymentAuthorized.

**Expected behavior**
Order should be updated to canceled.

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.3
 - Nodejs version 14
 - Database (mysql/postgres etc): mysql

**Additional context**
[Slack thread](https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1640687008041800)
[Mollie docs](https://docs.mollie.com/payments/status-changes)

**Comment by martijnvdbrug** [comment]
I'm looking into this :+1:

**Comment by michaelbromley** [comment]
> Open point: Once an order is canceled, a user cannot try and pay for the order again and looses his cart/order. How should we handle this?

We don't want to make a customer re-construct an entire order in the case of rejection (card rejected for whatever reason). 

If the customer explicitly chooses "cancel" while doing the Mollie flow, then still I'm not sure. They might click "cancel" because they realized they want to use some different payment method, e.g. they have a gift card. 

I'd question the use-case for cancelling an order _at all_ before the checkout is completed. Even if the customer decides to abandon the purchase completely, it might still make sense to leave the order intact as they can in any case remove unwanted items if they choose to order at some point in future.

**Comment by martijnvdbrug** [comment]
The order is set to `PaymentAuthorized` before you are redirected to Mollie. There is no way back to `AddingItems` from there. Even without cancelling the order, there is no way for the user to start another payment from the storefront because of this status.

It would be nice if the status could stay on `ArrangingPayment` in the paymentMethodHandler, but that's beyond the scope of this issue.
![image](https://user-images.githubusercontent.com/6604455/147907791-d2ec73f9-c736-47d5-9b82-1de1d5630466.png)


I can see 2 options now:
1. We keep the Mollie plugin as is, because in the future Vendure will support re-trying payments by allowing `ArrangingPayment` before payment
2. Implement canceling orders, because right now there is no way to re-try a payment.

**Comment by martijnvdbrug** [comment]
@michaelbromley Option one has my preference. What do you think?

**Comment by michaelbromley** [comment]
Yes, option 1 is preferable, and will allow us to better support flows like this I think. It would be a new feature for v1.5 then.

**Comment by martijnvdbrug** [comment]
Alright. I will close this issue and open a new one for option 1

**Comment by martijnvdbrug** [comment]
Closing this issue, as the problem can be solved without changing the Mollie plugin. New issue here https://github.com/vendure-ecommerce/vendure/issues/1330
