### ISSUE TITLE
Braintree plugin config issue

### ISSUE THREAD

**Issue by tlodge** [vendure-ecommerce/vendure#1320]
**Describe the bug**
It does not seem possible to configure a Braintree payment method in the admin interface.  When the configuration options are displayed after selecting 'braintree payments' as the payment handler (in the admin interface), the option to create remains greyed out even after all configuration options are provided.  The console logs look as though the textboxes are misconfiguring or not accepting initial null values:

```
core.js:6479 ERROR TypeError: Cannot read properties of null (reading 'ui')
    at ts.get suffix [as suffix] (text-form-input.component.ts:31)
    at template (text-form-input.component.html:2)
    at Lo (core.js:9599)
    at xo (core.js:9465)
    at Qo (core.js:10636)
    at core.js:9261
    at xo (core.js:9259)
    at core.js:10590
    at xo (core.js:10583)
    at core.js:10590
```

**To Reproduce**

Install the plugin as per instructions (so in the dev-server/dev-config.ts add the braintree imports:)

```
import {BraintreePlugin} from '../payments-plugin/src/braintree';
import { Environment } from 'braintree';
```

and plugin:
```
BraintreePlugin.init({
            environment: Environment.Sandbox,
            // This allows saving customer payment
            // methods with Braintree
            storeCustomersInBraintree: true,
        }),
```

Click on 'settings->payment methods'
Click on 'create new payment method'
Provide a name eg: 'test payment'
Then select braintree payments as the payment handler

**Expected behavior**
Expect to be able to add the configuration and for the 'create' button to be enabled.

**Environment (please complete the following information):**
 - @vendure/core version:
 Vendure server (v1.4.1)

 - Nodejs version
 16.13.1

 - Database (mysql/postgres etc):
postgres

Tested in chrome on mac osx.

**Comment by tlodge** [comment]
A couple more points.  I have the same issue when I try and install Mollie payments - I get the same errors in the console when I try to add config details to the text boxes.  I have tried importing from the yarn libs:
```
import { BraintreePlugin } from '@vendure/payments-plugin/package/braintree'
```
and from the plugins in the src tree:

```
import {BraintreePlugin} from '../payments-plugin/src/braintree'
```

I'm assuming that I have some kind of version incompatibility between vedure core and the payment plugins but any pointers would be gratefully received!

**Comment by michaelbromley** [comment]
Hi, can you try upgrading to the latest version and see if the problem persists?

**Comment by tlodge** [comment]
Thanks for the quick response!  I've upgraded to the latest problem and the problem has resolved.  Many thanks!
