### ISSUE TITLE
Filtering Jobs query is not working (BullMQJobQueuePlugin)

### ISSUE THREAD

**Issue by HarunKilic** [vendure-ecommerce/vendure#1327]
**Describe the bug**
Options in the `jobs` query does not work. It won't react on it. 

**To Reproduce**
1. Stop worker
2. Start a Job (Just let it stay as PENDING state)
3. use query: 
```
  jobs(options: { filter: { queueName: { eq: "NOT_EVEN_CLOSE" } } }) {
    items {
      id
      progress
      queueName
    }
    totalItems
  }
```
4. See that the job will append, even tho queueName filter is set.

**Expected behavior**
Expected no jobs to appear, as the queueName is something that is not in the Job.

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.3
 - Nodejs version: 16.13.1
 - Database (mysql/postgres etc): postgres

**Comment by michaelbromley** [comment]
Thanks for the report. Are you using the DefaultJobQueuePlugin?

**Comment by HarunKilic** [comment]
Forgot to mention that. But i am using BullMQ(Redis)
