### ISSUE TITLE
Error when deleting product with deleted variants

### ISSUE THREAD

**Issue by ttournie** [vendure-ecommerce/vendure#1328]
**Describe the bug**
When using the productService.softDelete on product with deleted variants, we get `error.entity-with-id-not-found` for each variant that is deleted.

It's because the soft delete of the product tries to delete all the variant but when the variant is already deleted, we got an error 

**To Reproduce**
1. Soft delete a Variant
2. Soft delete the product

**Expected behavior**
When should not get any error

**Environment (please complete the following information):**
 - @vendure/core version: 1.3.4

**Comment by michaelbromley** [comment]
Hi,

I just tried to reproduce on current master (v1.4.3) and cannot. Here's what I did:

1. Created a new product with 3 variants.
2. Using the "manage variants" screen of the Admin UI, deleted 1 variant.
3. In the product list view, deleted the product

Response was 
```json
{
  "data": {
    "deleteProduct": {
      "result": "DELETED",
      "message": null,
      "__typename": "DeletionResponse"
    }
  }
}
```
and no error in the vendure server terminal. Can you give me exact steps that you use to reproduce?
