### ISSUE TITLE
Remove or Update fields on common types

### ISSUE THREAD

**Issue by Rommel96** [vendure-ecommerce/vendure#1339]
**Describe the bug**

I try remove/update some fields in CurrencyCode, but get this response 
``Error: Type "CurrencyCode" already exists in the schema. It cannot also be defined in this type definition``

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.4
 - Nodejs version: v14.17.6
 - Database (mysql/postgres etc): mariadb

**Additional context**

Im using `extend`, but this just me allow added field

```
extend enum CurrencyCode {
        FOO
}
```

**Comment by michaelbromley** [comment]
Hi,

> I try remove/update some fields in CurrencyCode

Can you show me exactly what you are trying to do (your code), and what the expected result should be?

**Comment by Rommel96** [comment]
> Hi,
> 
> > I try remove/update some fields in CurrencyCode
> 
> Can you show me exactly what you are trying to do (your code), and what the expected result should be?

I want override enum CurrencyCode to: 

Expected
```
enum CurrencyCode {
        ETH
        BT
 }
```

I am use: 
![image](https://user-images.githubusercontent.com/52289346/149025333-c49866c4-b281-4fb4-841c-08caf5f3034c.png)


Error: 
`**Type "CurrencyCode" already exists in the schema. It cannot also be defined in this type definition.**`

**Comment by michaelbromley** [comment]
Ah I see. So you want to get rid of the existing currencies and just have e.g ETH and BT? OK, I think this won't be possible. 

I'm not certain whether everything will even work when you add items to that enum - I've never tried it.

**Comment by martijnvdbrug** [comment]
Extending enums works the way you defined it, we are doing something similar with HistoryEntry:
```graphql
      extend enum HistoryEntryType {
        SENDCLOUD_NOTIFICATION
      }
 ```

Overriding the enum type indeed isn't possible, it's part of Vendure Core, and 'hardcoded' in `currency-code.graphql`. There are also parts in Vendure's code that reference `CurrencyCode.USD` as a fallback/default, so removing that would break Vendure.

If you really want to override other currencies, you could override the `UpdateChannel` mutation and prohibit any other currencies.
