### ISSUE TITLE
Save chosen Mollie payment method (creditcard, paypal and so on) in payment metadata of vendure

### ISSUE THREAD

**Issue by nabbl** [vendure-ecommerce/vendure#1340]
It would be great if the mollie payment plugin would save the selected payment method from mollie into the database.

So that when we have to make some reports we can include that information for the customer.

**Comment by michaelbromley** [comment]
Hi, thanks for the suggestion. 

The way this would be done is to put the additional data in the `metadata` object [here](https://github.com/vendure-ecommerce/vendure/blob/42c0be4b49d9e234677206ea1a7eb4f5f034ae0f/packages/payments-plugin/src/mollie/mollie.controller.ts#L48) I think. It probably also makes sense to save additional metadata which might also be useful in debugging payment issues etc. It would be something like this:

```
dbPayment.metadata = {
    ...dbPayment.metadata,
    status: molliePayment.status,
    paidAt: molliePayment.paidAt,
    amount: molliePayment.amount,
    amountCaptured: molliePayment.amountCaptured,
    description: molliePayment.description,
    method: molliePayment.method,
    profileId: molliePayment.profileId,
    settlementAmount: molliePayment.settlementAmount,
    settlementId: molliePayment.settlementId,
    customerId: molliePayment.customerId,
    orderId: molliePayment.orderId,
};
await this.connection.getRepository(Payment).save(dbPayment);
``` 

Would you be interested in having a go at a PR for this?

**Comment by martijnvdbrug** [comment]
Sure. I'm currently workin on #1432 aswell, so I can also do this one. Hopefully I will have a PR somewhere next week.
