### ISSUE TITLE
Assets named in traditional chinese (zh_Hant) cannot be displayed

### ISSUE THREAD

**Issue by WeitingC219** [vendure-ecommerce/vendure#1343]
**Describe the bug**
Images named in traditional Chinese (zh_Hant) do not show up correctly after being uploaded. Those images cannot be previewed as well.

**Environment (please complete the following information):**
 - @vendure/core version: 1.3.2
 - Nodejs version: v14.17.0
 - Database (mysql/postgres etc): postgres

**Comment by michaelbromley** [comment]
I have a question about best practice here:

Let's say we upload an image file, `白飯.jpg`

The asset server plugin will create the corresponding file on the server ok.

Now when we query for that asset, it will return a preview url of e.g.: `http://localhost:3038/assets/preview\3f\白飯__preview.jpg`

My question is: **should the filename be url-encoded at this stage?**, i.e. `http://localhost:3038/assets/preview%03f%E7%99%BD%E9%A3%AF__preview.jpg`

Or do we just keep it in the original characters, and do the encoding internally when processing the request? Do you have any insight into what is the norm?

**Comment by WeitingC219** [comment]
I'm not really familiar with the norm here. But from the user point of view, if the query string stays with the original file name, it would be easier for them to share or preview with the full understanding of which asset they are looking at.
