### ISSUE TITLE
Latest order summary in dashboard is incorrect while using Postgres

### ISSUE THREAD

**Issue by WeitingC219** [vendure-ecommerce/vendure#1344]
**Describe the bug**
Latest order summary only shows cancelled orders. In addition, placed time for those orders are displayed as "Invalid Date", while they are showing correctly in the order page. I'm using Postgres and it seems like a bug specific to Postgres.

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.4
 - Nodejs version: v14.17.0
 - Database (mysql/postgres etc): postgres

**Comment by michaelbromley** [comment]
Hi,
This _should_ have been fixed in v1.4.3 (https://github.com/vendure-ecommerce/vendure/blob/master/CHANGELOG.md#143-2021-12-22). If you are using ui-devkit, can you try deleting and re-building your admin-ui folder and see if the problem persists?

**Comment by WeitingC219** [comment]
Hi Michael,
Thank you for the update. It works after I re-build the admin-ui folder. But I'm still wondering if the order time can be calculated based on local time. Since I'm in UTC+8 time zone, my order time is always >= 8hr.

**Comment by michaelbromley** [comment]
Is that the case for all dates, e.g. on the order list page too?

**Comment by WeitingC219** [comment]
Yes, it is the case for all dates. However, I found this occurs only when using localhost. If the code is deployed to AWS, all dates seem to work normally.

**Comment by justsee** [comment]
I've just run into this with dashboard dates being out with a local dev instance, and after confirming data and db timezone were fine the temporary solution was to run the node processes in a utc timezone as well:

```
  "scripts": {
    "run:server": "TZ=utc ts-node ./src/index.ts",
    "run:worker": "TZ=utc ts-node ./src/index-worker.ts"
```

Inspecting the `pg_dump` file and the timestamps are all using a `timestamp without timezone`, so no `Z` at the end to denote a UTC time.

[PostgreSQL says](https://wiki.postgresql.org/wiki/Don't_Do_This) to prefer using a `timestampz` timestamp: `Don't use the timestamp type to store timestamps, use timestamptz (also known as timestamp with time zone) instead.`

Vendure docs mention dates are stored in UTC so wondering if something's just off with the local setup here.

**Comment by michaelbromley** [comment]
I'm going to close this in favour of 

- #1719

which is tracking the same underlying issue.
