### ISSUE TITLE
The Admin UI assets file path are not correct when mount to an URL not root

### ISSUE THREAD

**Issue by Mraky09** [vendure-ecommerce/vendure#1346]
**Describe the bug**
The UI admin is blank because can't load the JS files assets.
**To Reproduce**
1. Mount the Vendure application into an endpoint not root. Ex: (https://localhost:3000/backend)
The URLs for each components should be:
Shop API: https://localhost:3000/backend/shop-api
Admin API: https://localhost:3000/backend/admin-api
Admin UI: https://localhost:3000/backend/admin
2. Go to Admin UI
3. The UI is blank

![image](https://user-images.githubusercontent.com/22260918/149351547-2523136b-a2e5-4cb6-957e-3fa46002c39e.png)

**Expected behavior**
Actual: https://localhost:3000/admin/styles.104e8aef5ce52b83ce9b.css
Expected: https://localhost:3000/backend/admin/styles.104e8aef5ce52b83ce9b.css

**Environment (please complete the following information):**
 - @vendure/core version: 1.3.4
 - Nodejs version: 16.13.2
 - Database (mysql/postgres etc): Postgres

**Additional Context**
Vendure config for AdminUi

```typescript
 AdminUiPlugin.init({
      route: 'admin',
      port: 3002
}),
```

**Comment by michaelbromley** [comment]
Hi,

Can you explain this part more precisely:

> Mount the Vendure application into an endpoint not root. Ex: (https://localhost:3000/backend)

How are you doing that? Can you share your config/code for that part?

Normally this would be done by setting:
```ts
AdminUiPlugin.init({
      route: 'backend',
      port: 3002
}),
```

**Comment by michaelbromley** [comment]
Thanks. And does it not work if you combine that gateway config with

```ts
AdminUiPlugin.init({
      route: 'backend',
      port: 3002
}),
```
?

**Comment by Mraky09** [comment]
> 

Yes, I've tried this as well :(

**Comment by michaelbromley** [comment]
Can you try it without using any kind of gateway, i.e. just run the vendure server locally and see if the admin ui works at localhost:3000/backend (it does for me when testing locally). If so, this might be some configuration issue with your gateway.
