### ISSUE TITLE
Locking not supported on given driver.

### ISSUE THREAD

**Issue by vaibhavsanap** [vendure-ecommerce/vendure#1349]
**Describe the bug**
I have deployed the vendure with cockroachDB and elasticsearch.  Vendure server is deployed successfully but worker is crashing continuously. 

```
(node:29) UnhandledPromiseRejectionWarning: LockNotSupportedOnGivenDriverError: Locking not supported on given driver.
    at new LockNotSupportedOnGivenDriverError (/usr/src/app/node_modules/typeorm/error/LockNotSupportedOnGivenDriverError.js:10:28)
    at SelectQueryBuilder.createLockExpression (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1254:27)
    at SelectQueryBuilder.getQuery (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:54:21)
    at SelectQueryBuilder.QueryBuilder.getQueryAndParameters (/usr/src/app/node_modules/typeorm/query-builder/QueryBuilder.js:243:26)
    at SelectQueryBuilder.<anonymous> (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1594:50)
    at step (/usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at /usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/src/app/node_modules/typeorm/node_modules/tslib/tslib.js:111:16)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**To Reproduce**
1. Deploy vendure with cockroach DB as database and elasticsearch

**Expected behavior**
Successful deployment of vendure worker 

**Environment (please complete the following information):**
 - @vendure/core version: ^1.0.0
 - Nodejs version
 - "typescript": "4.5.4"
 - "@elastic/elasticsearch": "~7.11.0",
 - Database (mysql/postgres etc): CockroachDB

**Additional context**
I am able to login to vendure admin console.
In admin console DB status and elasticsearch status is shows as UP

**Comment by michaelbromley** [comment]
Hi, thanks for the report. Linking the corresponding issue in the cockroachdb project: https://github.com/cockroachdb/cockroach/issues/74796

Are you using the DefaultJobQueuePlugin? If so, I suspect the locking part is related to that plugin. You could consider trying the [BullMQJobQueuePlugin](https://www.vendure.io/docs/typescript-api/job-queue-plugin/bull-mqjob-queue-plugin/) which will use redis for the job queue. It is also much more performant and can massively reduce load on the DB.

In terms of a fix for the actual issue, I'm not sure but will have time to look into it more deeply next week.

**Comment by vaibhavsanap** [comment]
@michaelbromley I am using defaultJobQueuePlugin. I will try to setup BullMQJobQueuePlugin.

**Comment by vaibhavsanap** [comment]
After setting up BullMQ I am able to resolve this issue.

We are facing following issue while connecting to elasticsearch

`          "headers": {
            "user-agent": "elasticsearch-js/7.16.0 (linux 5.4.156-83.273.amzn2.x86_64-x64; Node.js v14.18.3)",
            "x-elastic-client-meta": "es=7.16.0,js=14.18.3,t=7.16.0,hc=14.18.3"
          },
          "querystring": "",
          "timeout": 30000
        },
        "options": {},
        "id": 77
      },
      "name": "elasticsearch-js",
      "connection": {
        "url": "https://eck.twomatches.click/",
        "id": "https://eck.twomatches.click/",
        "headers": {},
        "deadCount": 80,
        "resurrectTimeout": 1642527092661,
        "_openRequests": 0,
        "status": "dead",
        "roles": {
          "master": true,
          "data": true,
          "ingest": true,
          "ml": false
        }
      },
      "attempts": 3,
      "aborted": false
    }
  }
} `

```
error 1/18/22, 4:59 PM - [ElasticsearchPlugin] Error when attempting to run bulk operations [ConnectionError: self signed certificate in certificate chain] 
error 1/18/22, 4:59 PM - [ElasticsearchPlugin] Error details: undefined 
error 1/18/22, 4:59 PM - [ElasticsearchPlugin] Error when attempting to run bulk operations [ConnectionError: self signed certificate in certificate chain] 
```

Elasticsearch option configuration is as below

```
ElasticsearchPlugin.init({
            host:'https://******',
            port: 443,
            rejectUnauthorized: false,
            clientOptions: {
                node: 'https://***********',
                auth: {
                    username: '******',
                    password: '******'
                  },
                ssl: {
                     rejectUnauthorized: false
                   }
            }
        }),
```

My Observation
1) From admin UI elasticsearch status is up
2) Looks like admin ui considers the `clientOptions`
3) But while updating the index clientOptions are ignored thats why while connecting it it not considering the flag `rejectUnauthorized: false`
4) I am suspecting the above issue because while debugging i found that while connecting to elasticsearch it was not even using node filed provided in clientoptions so I had to provide the host and port explicitly.

**Comment by vaibhavsanap** [comment]
As this perticular issue is resolved. I am closing this ticket. 
@michaelbromley  Thank you for helping us. With help from you we are able to integrate vendure with cockroachDB, elasticseatch and redis
