### ISSUE TITLE
Incorrect createdAt, updateAt timezone event if we setup db options timezone ='Z'

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#1375]
**Describe the bug**
Incorrect createdAt, updateAt timezone event if we setup db options timezone ='Z'

**To Reproduce**
1.  delploy vendure server, in front end place an order, please see db order record, the `createdAt`,` updatedAt` is local date(not applied specificed `timezone `, 

![image](https://user-images.githubusercontent.com/2833251/150955442-a5baa603-faac-4b49-abe3-88e2f46fdb17.png)

2. Please see vendure base entity `@CreateDateColumn()` it has related issue links as below
https://github.com/typeorm/typeorm/issues/6306
https://github.com/typeorm/typeorm/issues/5841

**Expected behavior**
the `createdAt`,`updatedAt` should have consistency of `orderPlacedAt`

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.5
 - Nodejs version v14+
 - Database (mysql/postgres etc): mysql

**Additional context**

**Comment by michaelbromley** [comment]
Related: https://github.com/typeorm/typeorm/issues/8296

I just read through a bunch of issue about this. There seems to be 2 proposed solutions:

1. Set the timezone of the DB to UTC
2. Change the `type` column of the createdAt / updatedAt to something like `TIMESTAMP` mysql

> MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval.

Can you help investigate this by 

1. Double-check your mysql server `time_zone` and `system_time_zone` settings to ensure they are set to UTC.
2. Try modifying the [base entity columns](https://github.com/vendure-ecommerce/vendure/blob/1427399eda64a23e7af4f9f88a8ebc0cca722847/packages/core/src/entity/base/base.entity.ts#L25-L27) to define a different data type, and see if that fixes the problem for you.

**Comment by tianyingchun** [comment]
**Test scenario one**

1. `show VARIABLES LIKE '%zone%'` 
BTW our local timezone is '+8:00'

```
|system_time_zone|	CST|
|time_zone|	+00:00. (changed it  to UTC)|
```

2. create new order the createdAt, updatedAt  query order db storage records is 
`SELECT createdAt, updatedAt, code, orderPlacedAt from glass_order ORDER BY id DESC`

2022-01-28 16:18:43.033883	2022-01-28 16:23:22.000000	46ST261B1YAVLVVJ	2022-01-28 08:23:22

the `createdAt`, `updatedAt` is also store as `+8:00` is incorrect, the placedOrderAt is correct.

**Comment by tianyingchun** [comment]
Test scenario two, recovery to local zone.
`SHOW VARIABLES LIKE '%zone%'`

system_time_zone	CST
time_zone	SYSTEM

2. create new order then.
3. `SELECT createdAt, updatedAt, code, orderPlacedAt from glass_order ORDER BY id DESC`

2022-01-28 16:30:33.196489	2022-01-28 16:30:48.000000	QW84KV27RCFYZ7WC	2022-01-28 08:30:47

**Comment by tianyingchun** [comment]
it seems that Whether I change the local zone to UTC or not, ·`@CreateDateColumn() createdAt: Date;` always use local timezone to store date value, and `orderPlacedAt` is programing assign it to `new Date()` it seems that always store using UTC case of we specificed connection as `Z`

**Comment by tianyingchun** [comment]
Test scenario three change decorator of @CreateDateColumn()
```__decorate([
    entity_id_decorator_1.PrimaryGeneratedId(),
    __metadata("design:type", Object)
], VendureEntity.prototype, "id", void 0);
__decorate([
    typeorm_1.CreateDateColumn({
      type:'timestamp'
    }),
    __metadata("design:type", Date)
], VendureEntity.prototype, "createdAt", void 0);
__decorate([
    typeorm_1.UpdateDateColumn({
      type:'timestamp'
    }),
    __metadata("design:type", Date)
], VendureEntity.prototype, "updatedAt", void 0);
exports.VendureEntity = VendureEntity;
//# sourceMappingURL=base.entity.js.map
```

add ` type:'timestamp'`

`SELECT createdAt, updatedAt, code, orderPlacedAt from glass_order ORDER BY id DESC`
2022-01-28 16:41:34.770568	2022-01-28 16:43:29.000000	B7UVWJZARCTPL4E8	2022-01-28 08:43:29

as above shown: the `orderPlacedAt` always use connection timezone `Z` configuration

but `@CreateDateColumn()`, `@UpdateDateColumn()` is always use local timezone formatted stored in db.

**Comment by tianyingchun** [comment]
Test case 4

in mysql i found `@CreateDateColumn(), @UpdateDateColumn() ` it refrected in mysql as `type: datetime` ,`lenght: 6`, defaultValue is `CURRENT_TIMESTAMP`, after multi tryings variants test case as below `conclusion`:

`CURRENT_TIMESTAMP`in mysql is stored as UTC but retrieved as the current timezone, you can affect your server's timezone setting with the --default_time_zone option for retrieval. This allows your retrieval to always be in UTC.
By default, the option is 'SYSTEM' which is how your system time zone is set (which may or may not be UTC!):

Soltions here for mysql:

1. We changed mysql global variables `time_zone` to '+0:00' It won't work
2. We must initialized mysql instance while mysql process startup phase with parameter `--default_time_zone` to `+0:00` it works
3. The  `--default_time_zone` available values are `[SYSTEM|-12:00|-11:00|-10:00|-9:00|-8:00|-7:00|-6:00|-5:00|-4:00|-3:00|-2:00|-1:00|+0:00|+1:00|+2:00|+3:00|+4:00|+5:00|+5:30|+5:45|+6:00|+6:30|+7:00|+8:00|+9:00|+10:00|+11:00|+12:00|+13:00]`
4. Normally for cloud server it provider these startup parameters allow us customized, **very very important.**
5.

**Comment by michaelbromley** [comment]
OK, thanks for the testing on this. So to be clear - this is a config issue on the DB server right? In that case, I think the best solution is to add documentation about this to the deployment guide.

**Comment by tianyingchun** [comment]
yes, the better solution is config global db instance startup parameters.
