### ISSUE TITLE
Admin UI not working with bearer auth method

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#138]
**Describe the bug**
If the `authOptions.tokenMethod` config option is set to 'bearer', the admin ui app will not work.

**To Reproduce**
1. Set tokenMethod to "bearer"
2. Attempt to log in to the admin ui
3. Any gql operation will kick you out with " Your session has expired. Please log in"

**Expected behavior**
The admin ui should work with bearer token auth if that is configured on the server.

**Environment (please complete the following information):**
 - @vendure/core version: 0.1.2-beta.11
 - Nodejs version: 12.4.0
 - Database (mysql/postgres etc): any

**Comment by hsensh** [comment]
This is still not working. Are you sure it is fixed?

**Comment by michaelbromley** [comment]
Yes, it is fixed. But if you are running into something that looks similar, could you provide steps to reproduce from a clean install?
