### ISSUE TITLE
Order line items. fulfillments alway can not return to front end client.

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#1381]
**Describe the bug**

Order line items. fulfillments alway can not return to front end client.

**To Reproduce**
1. crete new order from front end, and make payment
2. in admin, create fulfillment for this order for all orderlines 
3.  back to front end, load this order, always return `null` 
![image](https://user-images.githubusercontent.com/2833251/151136445-30b9bbc9-9791-4e01-9e54-43db2efadbea.png)

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.5
 - Nodejs version 16+
 - Database (mysql/postgres etc): mysql

**Additional context**

**Comment by michaelbromley** [comment]
> back to front end, load this order, always return null

Can you provide me with the exact query which reproduces this? I am trying to write a failing test case first and so far the queries I tried (`order` and `orderByCode` in the Shop API) _do_ include the fulfillment.

**Comment by tianyingchun** [comment]
```gql
{
  activeCustomer {
    orders(options:{
      skip:0,
      take:5,
      sort:{createdAt:DESC},
      filter:{active:{eq:false}}
    }) {
      totalItems
      items { 
        id
    		code
    		state
        lines {
          id
          items {
            id
            fulfillment {
                id
                state
                method
                trackingCode
            }
          }
        }
      }
    }
	}
}
```
