### ISSUE TITLE
error when trying to subscribe to a websocket

### ISSUE THREAD

**Issue by danieldflrss** [vendure-ecommerce/vendure#1385]
Hello, when I try to subscribe to a service through graphql, I get the following error:
TypeError: Cannot read property 'userHasPermissions' of undefined
on the file
node_modules\@vendure\core\src\api\middleware\auth-guard.ts:81:14

A possible solution would be adding:
return parentType !== 'Query' && parentType !== 'Mutation' **&& parentType !== 'Subscription**';
to the **isFieldResolver** function in the file vendure\core\src\api\middleware\auth-guard.ts

**Comment by martijnvdbrug** [comment]
Fixed in https://github.com/vendure-ecommerce/vendure/pull/1881
