### ISSUE TITLE
Address duplicated when changing defaults.

### ISSUE THREAD

**Issue by LaurPat** [vendure-ecommerce/vendure#1388]
**Describe the bug**
In the admin UI, when changing default billing and shipping addresses, the address gets duplicated.

**To Reproduce**
Steps to reproduce the behaviour:
1. in the admin UI, open a customer record.
2. create a second address
3. Using the More... button, assign the new address as 'default shipping address'
4. Update
5. See duplicated address.

**Expected behavior**
address should not duplicate

**Environment (please complete the following information):**
 - @vendure/core version: v1.4.5
 - Nodejs version  any
 - Database (mysql/postgres etc):  postgres

**Comment by michaelbromley** [comment]
Cannot duplicate this. I'm going to close it for now. If anyone else runs into it please comment and I'll reopen.
