### ISSUE TITLE
Guest checkout not working with vue-storefront 

### ISSUE THREAD

**Issue by tylik1** [vendure-ecommerce/vendure#1398]
**Describe the bug**
I've installed vendure and added vue-storefont. 
From the first glance everything works as expected, but i can't navigate to shipping step with unauthorized user.
When i filled in name/email in `/checkout/customer` route, and clicked "Continue Shipping" button, I'am redirected to Home page.

**To Reproduce**
1. Go to '/checkout/customer'
2. Fill in user name and email
3. Click 'Continue Shipping'
4. In api request `setCustomerForOrder` there is error:
 `{
    "errorCode": "NO_ACTIVE_ORDER_ERROR",
    "message": "There is no active Order associated with the current session",
    "__typename": "NoActiveOrderError"
}`

**Expected behavior**
Unauthorized user should be able to proceed with checkout

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.5
 - Nodejs version: v14.16.1
 - Database : postgres

**Comment by michaelbromley** [comment]
Hi, have you already added an item to the order before attempting guest checkout?

**Comment by tylik1** [comment]
> Hi, have you already added an item to the order before attempting guest checkout?

yep, one item was int the basket

**Comment by michaelbromley** [comment]
OK. Double-check you set the correct vendure config as covered [here](https://docs.vuestorefront.io/vendure/guide/configuration.html#requirements), and if that is not working still, please open an issue in this repo instead: https://github.com/vuestorefront-community/vendure/

**Comment by tylik1** [comment]
> OK. Double-check you set the correct vendure config as covered [here](https://docs.vuestorefront.io/vendure/guide/configuration.html#requirements), and if that is not working still, please open an issue in this repo instead: https://github.com/vuestorefront-community/vendure/

ok thanks. checked, everything is correct. The problem is within api which comes from Vendure app, that's why i thought it might be related with Vendure, not with storefront. BTW on the store example  from the link below, i can see that no api request is sent, when i've filled in user/email information.
https://demo.vendure.io/storefront/checkout/shipping

Anyways thanks for help, will try to dig further.

**Comment by michaelbromley** [comment]
In the demo storefront, the `setCustomerForOrder` _does_ get called, but only once you submit your payment details.

Guest checkout do seem to be working with Vendure (I just tested the guest checkout flow in the demo storefront), so I think the error is either with the VSF integration project, or some other config setting perhaps.
