### ISSUE TITLE
Improve TypeScript API wrt relations

### ISSUE THREAD

**Issue by heiko-r** [vendure-ecommerce/vendure#1407]
**Is your feature request related to a problem? Please describe.**
From the [Slack discussion](https://vendure-ecommerce.slack.com/archives/CKYMF0SU8/p1644267216445819):

1. It's not obvious which relations are loaded for entities returned by Vendure's services, e.g.: `OrderService.findOne(): Promise<Order | undefined>` loads many relations, while `OrderService.findOneByCode(): Promise<Order | undefined>` loads none.
2. Loading all relations in every service method obviously has a huge performance impact.
3. The `EntityHydrator` can be used to ensure that certain relations are loaded, but it comes with a performance impact over loading the required relations directly.
4. Still, in any case, there remains a risk of inadvertently accessing an unhydrated relation.

**Describe the solution you'd like**

1. Vendure's services could make use of TypeScript's `Omit<>` type to indicate which relations of the returned entities are unhydrated. The rough idea in the Slack thread was to wrap the methods of `TransactionalConnection` to achieve this.
2. For performance improvement, we could add an optional `relations?: EntityRelationPaths<>[]` parameter to the standard `.find...()` methods, e.g.
   ```typescript
   async findMultipleBySkus(ctx: RequestContext, skus: string[], relations?: EntityRelationPaths<ProductVariant>[]): Promise<ProductVariant[]> {
        let variants: ProductVariant[] = [];
        const qb = this.connection.getRepository(ctx, ProductVariant).createQueryBuilder('variant');
        if (relations) {
            FindOptionsUtils.applyFindManyOptionsOrConditionsToQueryBuilder(qb, { relations: relations });
        }
        FindOptionsUtils.joinEagerRelations(qb, qb.alias, qb.expressionMap.mainAlias!.metadata);
        ...
    ```
    and possibly not load any relations by default.

**Describe alternatives you've considered**
Using `EntityHydrator` works well, but has worse performance than loading the required relations directly, and has a risk of accessing relations which are usually (but not always) loaded and hence possibly forgotten to explicitly hydrate.

**Additional context**
I wonder, as a first, partial fix, if it might be possible to set a service method's return type based on the `relations` parameter (for methods which implement it), without wrapping TypeORM.

**Comment by mschipperheyn** [comment]
I would say that for certain entities and queries there is a presumption on which relations will be loaded without adding entity resolvers to load relations that are not part of the query.

I would recommend that any relation should always have an entity field resolver that gets the data. So that if someone goes outside of the box, they don't run into unexpected errors

**Comment by martijnvdbrug** [comment]
Thanks for your report! 
Most services in the latest versions of Vendure support passing in relations now, for example `OrderService.findOneByCode(ctx, '12354', ['customer'])`. If your custom code needs specific relations, you should always be explicit about it. It does automatically change the TS return type yet. 

If you are missing the relations argument in any of the services, I suggest creating a separate/specific GH issue for that.
