### ISSUE TITLE
Building admin-ui with bugged angular version

### ISSUE THREAD

**Issue by zgaduj** [vendure-ecommerce/vendure#1408]
I got an error in building process by CI/CD:
`Error: /***/admin-ui/src/extensions/3e028bd5b95260d976957876dc5c4a46269bbd0efc0970818375e4f4485be551/checklist-products/checklist-products.component.scss from Css Minimizer
Error: Transform failed with 1 error:
error: Invalid version: "15.2-15.3"`

admin-ui in version 1.4.6 using angular in version 12.2.2

https://stackoverflow.com/questions/70925649/angular-12-error-from-css-minimizer-transform-failer-with-1-error-invalid/70925650

Angular issue was added 10 days ago: https://github.com/angular/angular-cli/issues/22606

I want to know how it's possible that no one have that issue after few days :O
And how was published 1.4.6 (2022-02-04)? How was it built?

In local dev without updated packages - OK
CI/CD - ERROR because building from scratch...

@michaelbromley you don't using Docker to build and check if everything is fine?

How can I inject `.browserslistrc` file to building process?

**Environment:**
 - @vendure/core version: 1.4.6
 - @vendure/admin-ui: 1.4.6

**Comment by michaelbromley** [comment]
Hi, thanks for the report.

I think the reason it has not been picked up in Vendure's CI is because we have the yarn lockfile under version control, so we're not getting this latest version which includes the error. I'd guess that goes for others building the admin ui too - the lockfile will only get updated when the explicitly tell it to update to a newer version.

**Comment by zgaduj** [comment]
Why you working with lockfile when you publishing? It's critical case for people who using your project.
Think about who just starting with wrong version and lockfile will be always corrupted?

I need quickly fix this issue and I don't know now how without `hacking` angular versions in `package.json` :|

**Comment by michaelbromley** [comment]
We don't publish with a lockfile. I'm talking about our CI workflows which build the admin ui from this Vendure monorepo.

There is not currently a CI workflow which does an install of ui-devkit and then builds a version of the admin ui based on that. If there was, we probably would have caught this issue. If you are using yarn you should be able to use the `resolutions` feature to specify a specific version of a transitive dependency.

**Comment by zgaduj** [comment]
Quick hack and overriding package in `package.json` (https://github.com/nrwl/nx/issues/8768#issuecomment-1027714216): 
`"caniuse-lite": "1.0.30001303"`
