### ISSUE TITLE
Typescript 4.5.5 (latest) breaks build

### ISSUE THREAD

**Issue by deusama** [vendure-ecommerce/vendure#1409]
**Describe the bug**
When I upgrade `typescript` to the latest version 4.5.5 in my `package.json` I cannot build vendure.

**To Reproduce**
1. Set `"typescript": "4.5.5"` as a dependency in your `package.json` (or just run `yarn upgrade --latest`)
2. Run `yarn build`
3. You will see this:
```
node_modules/@vendure/core/dist/common/types/entity-relation-paths.d.ts:33:131 - error TS2344: Type 'T[K]' does not satisfy the constraint 'VendureEntity'.
  Type 'T[EntityRelationKeys<T>]' is not assignable to type 'VendureEntity'.
    Type 'T[Required<T>[Extract<keyof T, string>] extends VendureEntity | null ? Extract<keyof T, string> : Required<T>[Extract<...>] extends VendureEntity[] ? Extract<...> : never]' is not assignable to type 'VendureEntity'.
      Type 'T[Extract<keyof T, string>] | T[Required<T>[Extract<keyof T, string>] extends VendureEntity[] ? Extract<keyof T, string> : never]' is not assignable to type 'VendureEntity'.
        Type 'T[Extract<keyof T, string>]' is not assignable to type 'VendureEntity'.
          Type 'T[string]' is not assignable to type 'VendureEntity'.

33     [K in EntityRelationKeys<T>]: T[K] extends VendureEntity[] ? [K, PathsToStringProps1<T[K][number]>] : [K, PathsToStringProps1<T[K]>];
```

**Expected behavior**
A working build.

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.6 (latest)

**Comment by michaelbromley** [comment]
Hi, thanks for the report.
In general, it needs be to assumed that newer versions of TypeScript may break things, since TypeScript does not follow semantic versioning. That's the reason for this note in the [getting started guide](https://www.vendure.io/docs/getting-started/)

> The [supported TypeScript version](https://github.com/vendure-ecommerce/vendure/blob/master/packages/create/src/constants.ts#L7) is set upon installation. Upgrading to a newer version of TypeScript might result in compilation errors.

Having said that, it is worth trying to fix this issue in the next release if possible.
