### ISSUE TITLE
Typos in comments of generated types

### ISSUE THREAD

**Issue by Spielboerg** [vendure-ecommerce/vendure#1412]
**Describe the bug**
My IDE's spell checker found a few typos in the generated types.
Search for `Retured`, `attemting`, `chosed`, `speicified`, `relevence`.

https://github.com/vendure-ecommerce/vendure/search?q=retured+in%3Afile
https://github.com/vendure-ecommerce/vendure/search?q=attemting+in%3Afile
https://github.com/vendure-ecommerce/vendure/search?q=chosed+in%3Afile
https://github.com/vendure-ecommerce/vendure/search?q=speicified+in%3Afile
https://github.com/vendure-ecommerce/vendure/search?q=relevence+in%3Afile

Either `the` or `a` should be used here (`the a password`): https://github.com/vendure-ecommerce/vendure/blob/6a9efe9fffe0decbdb6cf70d5f4d45c07ee66e3a/packages/payments-plugin/e2e/graphql/generated-shop-types.ts#L1554

**Comment by michaelbromley** [comment]
Haha ok, sometimes I am typing too quickly for my own good 😆 

Would you like to PR a fix for these?
