### ISSUE TITLE
Should vendure builtin support  `products` sorting by `position` in search index item, also support variants SKU sorting by  `position` is better, also for` facets` filters sorting

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#1424]
**Is your feature request related to a problem? Please describe.**
1. in vendure `default search plugin` support  product `position` sorting.
2. in vendure `product Variants` support sku `position` sorting.

**Describe the solution you'd like**

**Describe alternatives you've considered**
 
**Additional context**
vedure@1.4.6

**Comment by tianyingchun** [comment]
consider below scene shown:

1. Allow us move some facets in before or after some one in front end, this behavior is very usefull, in most case, in the front end  facet filters , some important facet need to put the foremost
2. Product in catalog also want to above ability
3. All variants of product SKU1, SKU2, SKU3 also can be allow position it's ordering, for marketing purpose, sometimes we need make SKU2 show front SKU1

BTW: For marketing purpose above feature is very important. The best is it should be vendure builtin features 

as slack talking, these feature need to add a position to those entities before v2.0 because it is a breaking schema change.

So maybe it will plan to @vendure/core@V2.0

**Comment by giosueDelgado** [comment]
Needed also for us

Just some notes:

I build a similar structure adding a position field on productvariants and on productvariants and collection association 

This allow to have a specific position on collection and possibility to have a position on the global catalog
