### ISSUE TITLE
parseContext is a bit too restrictive to allow other kind of context

### ISSUE THREAD

**Issue by christopheblin** [vendure-ecommerce/vendure#1426]
**Describe the bug**

Because parseContext returns RestContext | GraphQLContext, if you add a plugin that uses another kind of context it "breaks"

The original use case was to add a RabbitMq listener so that when a user is updated inside our system, then vendure can eventually update the associated customer

https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1644851679410849

**To Reproduce**
1. Add dependency "@golevelup/nestjs-rabbitmq": "^2.2.0" and devDependency "@types/amqplib": "0.8.2",
2. Create a plugin with a service that uses the RMQ bus for a topic (see slack message)
3. Send a message to the RMQ
4. See error 14/02/22, 16:05 - [Vendure Server] req.get is not a function

**Expected behavior**

I do not expect vendure to break 😄 

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.5
 - Nodejs version : irrelevant
 - Database (mysql/postgres etc): irrelevant

**Additional context**

I can eventually do a workaround by calling the query customers and then the mutation updateCustomer in admin-api from a nestjs app with the listener outside vendure

However, up until now, we added all the code related to our shops inside vendure plugins so it would be great if we can continue like this

**Comment by christopheblin** [comment]
@michaelbromley 

I found a solution to my problem by using a plugin only in the worker (where there is no global AuthGuard so parseContext is not invoked)

The only drawback is that I cannot use the XxxService methods because they all require a context (which I do not have), so I need to look in the vendure code to copy paste the interesting bits here and there... (but I'd have the same problem in the server anyway)

Is there some valid Typescript API to create a context so we can use the internal services ?

I've look at https://www.vendure.io/docs/typescript-api/request/request-context/ but it does not explain how to create a context

BTW, seeing nodejs docs (https://docs.nestjs.com/fundamentals/execution-context#current-application-context), I think contextType should be used to detect rest and graphql and throw an exception otherwise (because in the server it should always be rest or gql, anything else should/could go in the worker)

```
if (context.getType() === 'http') {
    const httpContext = context.switchToHttp()
    return {
        isGraphQL: false,
        req: httpContext.getRequest(),
        res: httpContext.getResponse(),
    };
} else if (host.getType<GqlContextType>() === 'graphql') {
  const gqlContext = GqlExecutionContext.create(context as ExecutionContext);
      return {
        isGraphQL: true, 
        req: gqlContext.getContext().req,
        res: gqlContext.getContext().res,
        info: gqlContext.getInfo()
    };
} else  {
  throw new Error(`context ${context.getType()} is not supported`)
} 
```

This would allow the programmer to immediately see a clean error

**Comment by michaelbromley** [comment]
Thanks for the suggestion on detecting the context - I'll use that.

Regarding the RequestContext for calling service methods outside of an API request, you can use the [RequestContext.empty()](https://www.vendure.io/docs/typescript-api/request/request-context/#empty) static method for some uses, but this has limitations because you cannot set things like the channel or active user or apiType.

You can also construct a RequestContext manually, with something like:

```ts
private async getContext(): Promise<RequestContext> {
    const defaultChannel = await this.channelService.getDefaultChannel();
    const { superadminCredentials } = this.configService.authOptions;
    const superAdminUser = await this.connection
        .getRepository(User)
        .findOneOrFail({ where: { identifier: superadminCredentials.identifier } });
    return new RequestContext({
        channel: defaultChannel,
        apiType: 'admin',
        isAuthorized: true,
        authorizedAsOwnerOnly: false,
        session: {
            id: '',
            token: '',
            expires: new Date(),
            cacheExpiry: 999999,
            user: {
                id: superAdminUser.id,
                identifier: superAdminUser.identifier,
                verified: true,
                channelPermissions: [],
            },
        },
    });
}
```
