### ISSUE TITLE
SSO Login on Admin UI with bearer token - initial requests don't include authToken

### ISSUE THREAD

**Issue by sidings** [vendure-ecommerce/vendure#1427]
**Describe the bug**
When logging in with SSO on the admin UI, and using bearer tokens as the `tokenMethod`, the initial requests don't include the `vendure-token`. Because of this, when the `authGuard` checks to see if the user has permissions in `canActivate`, it will default to checking if the user has the correct permissions in the _default channel_ (channel 1) which leads to forbidden errors for the admin since the default channel is not the channel the admin is trying to access. Subsequent requests to the server will work fine, which leads the admin to be able to get into the admin UI but be unable to see certain data, such as Order data or Customer data.

**To Reproduce**
1. Setup your admin UI to use SSO login and your vendure config to use bearer tokens.
2. Create an admin with a non superadmin role and permissions in a channel other than the default channel.
3. Have your dev tools' network tab open to see the failing request.
4. Go to your admin UI and login with that admin's credentials.
5. In dev tools, notice the `GetServerConfig` query fails with a Forbidden error, but subsequent requests will return fine.

**Expected behavior**
An admin with permissions in any channel should be able to log in correctly and see all the data their role allows them to see. In this case, `GetServerConfig` should not return a forbidden error for the admin. Instead, the bearer token should get passed through correctly in the headers and the `canActivate` method of the `authGuard` should be able to use that in checking the user's permissions instead of defaulting to the default channel.

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.5
 - Nodejs version: 12
 - Database (mysql/postgres etc): postgres

**Comment by michaelbromley** [comment]
Closing in favour of https://github.com/vendure-ecommerce/vendure/issues/2363
