### ISSUE TITLE
Feature request - extended logging

### ISSUE THREAD

**Issue by Izayda** [vendure-ecommerce/vendure#1429]
**Is your feature request related to a problem? Please describe.**
I have strange perfomance issue on my production server and it is rather difficult to understand what api queries is causing it. 

**Describe the solution you'd like**
I would like to be able to turn on debug mode to monitor all api queries (sources of queries, content, method). More over i would like to link api queries with db queries.

Example of implementation:
1. Nginx generate RequestID and pass it as header
2. Express middleware get RequestID from header or generate their own RequestID
3. Express middleware log request with RequestID
4. Express middleware pass RequestID to RequestContext
5. Custom implementation of TypeORM Logging pass RequestID to logs

**Describe alternatives you've considered**
To use logging on nginx side or to turn on some service like GraphCDN.

**Additional context**
TypeORM custom logging: https://orkhan.gitbook.io/typeorm/docs/logging#using-custom-logger
Link to slack discussion: https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1644819689022989

**Comment by michaelbromley** [comment]
Dumping some additional context from our Slack discussion:

> Michael: ah ha ok, so maybe we can pass the RequestContext to the QueryRunner.data property. This could work since we're already passing ctx to basically every DB operation anyway as part of TransactionalConnection.

> Michael: Yes, seems like the only missing part in core would be to attach the RequestContext to QueryRunner inside the TransiactionalConnection getRepository() method.

So the missing part in core is that we can attach the RequestContext to the TypeORM QueryRunner.data property inside the TransactionalConnection methods. This means that, when writing a custom logger, you can access the express request, including any special IDs added by tracing tools.

**Comment by michaelbromley** [comment]
Spent some time working on this and I've come to the conclusion that it is not workable. See this lengthy discussion where someone wants to do basically the exact same thing in the same way: https://github.com/typeorm/typeorm/pull/7593

So I think the solution in this case would be to use [async local storage](https://www.npmjs.com/package/asynchronous-local-storage). You could create a Nest interceptor to start a hook and store any tracing data there, and then access it in your custom TypeORM logger.
