### ISSUE TITLE
Pending Updates are Blocking

### ISSUE THREAD

**Issue by xrev87** [vendure-ecommerce/vendure#1433]
**Describe the bug**
The run pending mutation appears to be blocking - with a large sku count the api becomes unresponsive and in my case my GKS healthcheck causes the instance to be brought down and back up.

Looking at the code - the process gets fired off on the server and applies to both collection population and search items.

This appears to be most prevalent when pending operations apply to sku counts in the 1000s.

I'm operating DefaultSearch with the Redis Queue plugin .

**To Reproduce**
1. Cause a large amount of pending updates
2. Run the pending mutation
3. Server becomes unresponsive

**Expected behavior**
The updates happen on the worker and the worker doesn't become unresponsive i.e. the health endpoint is still available throughout.

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.6
 - Nodejs version 16
 - Database (mysql/postgres etc): MySQL

**Comment by michaelbromley** [comment]
Thanks for the report. I managed to reproduce this with the following setup:

<details><summary>FillBufferPlugin, a plugin to fill up the job buffer with lots of search index jobs</summary>

```ts
import { Mutation, Query, Resolver } from '@nestjs/graphql';
import {
    CollectionService,
    Ctx,
    Logger,
    PluginCommonModule,
    ProductVariantService,
    RequestContext,
    VendurePlugin,
} from '@vendure/core';
import gql from 'graphql-tag';

@Resolver()
class FillBufferResolver {
    constructor(
        private productVariantService: ProductVariantService,
        private collectionService: CollectionService,
    ) {}

    @Mutation()
    async fillBuffer(@Ctx() ctx: RequestContext) {
        const { items: variants } = await this.productVariantService.findAll(ctx);
        const { items: collections } = await this.collectionService.findAll(ctx);
        const limit = 2000;
        for (let i = 0; i < limit; i++) {
            const variant = variants[i % variants.length];
            await this.productVariantService.update(ctx, [
                {
                    id: variant.id,
                    enabled: !variant.enabled,
                },
            ]);
            const collection = collections[i % collections.length];
            await this.collectionService.update(ctx, {
                id: collection.id,
                isPrivate: !collection.isPrivate,
            });
            if (i % 100 === 0) {
                Logger.info(`Updated ${i} / ${limit} items...`);
            }
        }
        Logger.info(`Done!`);
        return true;
    }
}

/**
 * Plugin to create a lot of buffered jobs to test help investigate and fix
 * issue https://github.com/vendure-ecommerce/vendure/issues/1433
 */
@VendurePlugin({
    imports: [PluginCommonModule],
    adminApiExtensions: {
        schema: gql`
            extend type Mutation {
                fillBuffer: Boolean!
            }
        `,
        resolvers: [FillBufferResolver],
    },
})
export class FillBufferPlugin {}
```
</details>


I also added some logging to the `SearchIndexJobBuffer` and `CollectionJobBuffer`. Using a dataset of 10,000 skus, I first triggered the `fillBuffer` mutation:
```
[run:server] info 18/02/22, 17:26 - [Vendure Server] Updated 0 / 2000 items...
[run:server] info 18/02/22, 17:26 - [Vendure Server] Updated 100 / 2000 items...
... omitted for brevity ...
[run:server] info 18/02/22, 17:29 - [Vendure Server] Updated 1900 / 2000 items...
[run:server] info 18/02/22, 17:29 - [Vendure Server] Done!
``` 

Then in the Admin UI I triggered the pending jobs:
```
[run:server] CollectionJobBuffer.reduce: start, 1687 collected jobs
[run:server] CollectionJobBuffer.reduce: end
[run:server] collection-buffer: 129.162ms
[run:server] SearchIndexJobBuffer.reduce: start, 2608 collected jobs
[run:server] SearchIndexJobBuffer.reduce: end
[run:server] search-buffer: 28.463s
```
At the same time, I made the following query to the API:
```gql
query {
  product(id: 1) {
    name
  }
} 
```
What should have taken ~20ms took 29.2s - more or less corresponding to the time taken to process the `SearchIndexJobBuffer.reduce()` function.

So the thesis that processing pending updates is blocking checks out!

Now I'll see how to fix it.

**Comment by xrev87** [comment]
> Wow, I traced this down to the use of the `unique` helper function [right here](https://github.com/vendure-ecommerce/vendure/blob/ced8ae50661fe44d7f08116e9473b5c52baa51a9/packages/core/src/plugin/default-search-plugin/search-job-buffer/search-index-job-buffer.ts#L46)
> 
> Turns out that the current implementation is _extremely_ inefficient, ie O(n^2) and that it is basically the root cause of this blocking behaviour.
> 
> When I re-wrote the implementation to be more efficient, that ~29s dropped to about 50ms(!!!).
> 
> This is a great discovery because the `unique` function is very widely used throughout many packages!

This is awesome! so quick as well!
