### ISSUE TITLE
FK constraint error when merging orders prevents login

### ISSUE THREAD

**Issue by skid** [vendure-ecommerce/vendure#1454]
Users are prevented to log in in a specific scenario due to an error. To reproduce:

1. Log in as a user and make sure you have an active, but **empty** order. You can do this by removing all items from the cart.
2. Open a different browser and add some products to the cart **before logging in**.
3. Log into the same account from step 1

This happens because of the order merging logic - i.e. if the existing order is empty but the guest order is not, Vendure tries to delete the existing order. However, because we use different browsers, the existing order still has a valid session pointing to it which triggers the error. This error interrupts the login process and to the user it appears as if nothing happens.

There is a "workaround" for this - namely only log in with an empty "guest" cart, but that's not working as intended.

**Comment by skid** [comment]
Since this poses an issue for us right now - do you have a suggestion on how to work around it until the fix lands?

**Comment by michaelbromley** [comment]
You could consider using [patch-package](https://www.npmjs.com/package/patch-package) to add a try-catch block around this line? https://github.com/vendure-ecommerce/vendure/blob/6b9b2a4fb647c4f92b7a2801c4dc9ad037f89e4a/packages/core/src/service/services/auth.service.ts#L94

**Comment by skid** [comment]
That will prevent the error from being raised, but won't it also leave some orders dangling? In fact, what happens to your existing session when you log in from a different device?
