### ISSUE TITLE
OrderTesting service is not exported in index.ts

### ISSUE THREAD

**Issue by teresaWienkBorgert** [vendure-ecommerce/vendure#1468]
**Describe the bug**
The OrderTesting service is not exported in the service/index.ts file like the other ones, so cannot be used in the implementation.

**Expected behavior**
The orderTesting service should also be included in the index.ts file.

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.6

**Comment by michaelbromley** [comment]
Closed in #1469
