### ISSUE TITLE
Can I integrate Vendure to Vue StoreFront ?

### ISSUE THREAD

**Issue by oldmember** [vendure-ecommerce/vendure#147]
Hello,
I am new to node.js and I want to ask that whether I can integrate Vendure to Vue StoreFront ?

**Comment by michaelbromley** [comment]
Hi!

Yes, it is indeed possible and is actually being done right now by another developer. I just checked and he plans to open-source the code needed to connect Vendure to VSF.

Pinging @lsimone for any additional input 😉

**Comment by oldmember** [comment]
That is awesome. Right now, I am learning Nest.js framework. Then I will learn Vendure and ping him :)

**Comment by michaelbromley** [comment]
Sounds like a plan 👍

You are welcome to join our Slack workspace where you can get direct help with learning Vendure (and Nest!): [Join Vendure Slack](https://vendure-ecommerce.slack.com/join/shared_invite/enQtNzA1NTcyMDY3NTg0LTMzZGQzNDczOWJiMTU2YjAyNWJlMzdmZGE3ZDY5Y2RjMGYxZWNlYTI4NmU4Y2Q1MDNlYzE4MzQ5ODcyYTdmMGU)

I'll close this issue now.

**Comment by paulvanbladel** [comment]
Great. @michaelbromley 
Do you have a link to a repo with the Vue storefront venture integration?

**Comment by michaelbromley** [comment]
Hi Paul, I don't know of any open-source repo for a Vue storefront integration at the moment. The one mentioned in the earlier comment was never open-sources as far as I know.
