### ISSUE TITLE
Cancelled items do not reduce the order total when in `ArrangingAdditionalPayment` state

### ISSUE THREAD

**Issue by skid** [vendure-ecommerce/vendure#1484]
**Describe the bug**

If a customer partially covers the order with a payment the order is in `ArrangingAdditionalPayment`. In this state, admins might need to cancel some order items instead of adding an additional payment to the order. However, cancelling items does not reduce the order total and it remains in `ArrangingAdditionalPayment` state.

**To Reproduce**

1. Create an order and add a payment that partially covers it to get it into `ArrangingAdditionalPayment`
2. As an admin, select "Refund and cancel Order"
3. Select some items to cancel and cancel them.
4. The order total remains the same.

**Expected behavior**
The order total is adjusted properly.

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.7
 - Nodejs version 16
 - Database (mysql/postgres etc): postgres 13

**Comment by michaelbromley** [comment]
Hi, 

I don't properly understand the workflow here:

When creating a new Payment which only partially covers the order totalWithTax, then the Order should remain in the `ArrangingPayment` state as far as I can tell based on [this line](https://github.com/vendure-ecommerce/vendure/blob/c6cf4d4e214f3941bc5f27017b0354dda732f9e0/packages/core/src/service/services/order.service.ts#L1001). Per the default [order state transitions](https://github.com/vendure-ecommerce/vendure/blob/26c1b7a2dbfe5aeb8275f45b7d73cf9f0484127e/packages/core/src/service/helpers/order-state-machine/order-state.ts#L33-L35) it could not directly transition to the `ArrangingAdditionalPayment` state from there.

Can you clarify this? E.g. list the precise sequence of mutations/admin actions leading to this state?

**Comment by martijnvdbrug** [comment]
@skid Are you experiencing this issue? If so, can you add some more info (see Michaels questions above)?

**Comment by skid** [comment]
Hmmm. This was a long time ago, so it's probably safe to close. I can't tell for sure if the issue still exists because we've created a custom admin screen for managing orders (we have a rather complex integration with our WMS).
