### ISSUE TITLE
Admin Ui Product Variants Page Size Weird Behavior

### ISSUE THREAD

**Issue by jacobfrantz1** [vendure-ecommerce/vendure#1486]
**Describe the bug**
Admin Ui freaks out when you select a page size other than 10 on product variants page (with more than 10 variants).
The page starts lagging and the items past 10 start appear and disappearing in rapid succession.

**To Reproduce**
1. Go to a product with more than 10 variants on the admin ui
2. Click on 'Product Variants'
3. Set the page size to 25
4. See weird behavior

**Expected behavior**
More than 10 variants show in the admin ui without it glitching around.

**Environment:**
 - @vendure/core version: 1.5.0
 - Nodejs version 16.14.2
 - Database: Postgresql 14.2

**Comment by michaelbromley** [comment]
Hi,
I just had a go at reproducing this locally on the current master branch, and can't see the issue as reported. Here's a video where I have a product with 12 variants. Changing the "items per page" setting works as expected with no strange behaviour.


https://user-images.githubusercontent.com/6275952/160478461-f29ce366-9202-406b-a020-bd381c0fccd6.mp4

Tested with both sqlite & postgres databases - both appear to work ok.

Could it be related to the browser? Maybe test in others and see if you see different results.

**Comment by jacobfrantz1** [comment]
Yeah, it looks like it does work with 12 variants, I was using a product with 144 variants and simply assumed I knew what the issue was. I don't know when exactly the issue occurs. I just saw it work with 26 variants which is more than a page of results at 25 per page.

**Comment by jacobfrantz1** [comment]
I was able to replicate the issue with 30 variants

**Comment by michaelbromley** [comment]
I just tried it with a product with 196 variants, and could not reproduce. Then tried with 30 variants like in your video - still could not reproduce! Tried in Brave and Chrome, but from your video you seem to be on Chrome too.

Very strange... there is some other variable here that we've not isolated yet.

Can you take a look at those requests that keep firing? What is the request body? Is it the same each time?

**Comment by jacobfrantz1** [comment]
It appears to be 2 separate queries.
```
query GetProductVariantList($options: ProductVariantListOptions!, $productId: ID) {
  productVariants(options: $options, productId: $productId) {
    items {
      ...ProductVariant
      __typename
    }
    totalItems
    __typename
  }
}
variables: {
  "options": {
    "skip": 0,
    "take": 25,
    "filterOperator": "OR"
  },
  "productId": "2"
}
```
```
query GetProductWithVariants($id: ID!, $variantListOptions: ProductVariantListOptions) {
  product(id: $id) {
    ...ProductDetail
    variantList(options: $variantListOptions) {
      items {
        ...ProductVariant
        __typename
      }
      totalItems
      __typename
    }
    __typename
  }
}

variables: {
  "id": "2",
  "variantListOptions": {
    "take": 10
  }
}
```

**Comment by jacobfrantz1** [comment]
I think this issue was fixed on the minor branch somewhere. I still get the issue when using 1.5.2 on the master branch, but not when using the minor branch. Though I have no clue as to what code could have fixed it. Tested using dev-server with postgres on windows.
