### ISSUE TITLE
External Auth Strategy for Admin Gives an Error of User <not found>

### ISSUE THREAD

**Issue by fahadaleem** [vendure-ecommerce/vendure#1489]
**Describe the bug**

**To Reproduce**
1. Clone this [repo](https://github.com/fahadaleem/Vendure-Custom-Auth) 
2. Perform the mutation on authentication with Input **strategy and externalIdentifier**
3. Now, open http://localhost:3000/admin/
4. See error **_No User with the id '<not found>' could be found_**

**Expected behavior**
Admin user should be logged in with the custom auth strategy, or with the externalIdentifier that I sent it from my client site. 

**Environment (please complete the following information):**
 - @vendure/core version:
 - Nodejs version
 - Database (postgres):

**Additional context**
I am trying to implement a custom auth for admin, for testing purposes I have just taken **auth strategy** and **external identifier** as an input in authenticate mutation and then allow it to check if there is admin available with these inputs, if the user exists then return the user else create a new one as mentioned on the vendure documentation. But it is showing an error while logging. 

![1](https://user-images.githubusercontent.com/55811140/160105548-76e7f775-476b-48e9-9fe8-54e1dba7805c.png)

**Here is the database tables snapshots**
***Administrator Table***
![administrator table](https://user-images.githubusercontent.com/55811140/160334007-72bb003c-cce9-4ee7-b653-1b93ff07e68f.png)
![administrator table1](https://user-images.githubusercontent.com/55811140/160334013-540e0c52-ddb2-4ff5-b490-0659d9d1710d.png)

***Users Table***
![users table](https://user-images.githubusercontent.com/55811140/160334246-4c63b909-eb68-466d-b62e-8cc11659f876.png)

***Authentication method table***
![auth method table1](https://user-images.githubusercontent.com/55811140/160334397-aea22436-f9c2-4b3b-a82e-ffba7d0063cc.PNG)
![auth method table2](https://user-images.githubusercontent.com/55811140/160334401-13977c41-a379-4e66-9db4-af7b3d92ba24.PNG)

**Comment by fahadaleem** [comment]
Hi, I have added the screenshots of the tables.

**Comment by michaelbromley** [comment]
Thanks for taking the time to create the repo. The problem is that the `identifier` field should match the email address:
```diff
return this.externalAuthenticationService.createAdministratorAndUser(ctx, {
  strategy: data.strategy,
  externalIdentifier: data.externalIdentifier,
-  identifier: "goldadmin",
+  identifier: "goldn@admin.com",
  emailAddress: "goldn@admin.com",
  firstName: "goldn",
  lastName: "admin",
  roles: [merchantRole],
});
```

Try that and let me know if it works for you.
