### ISSUE TITLE
unable to login as newly created admin user

### ISSUE THREAD

**Issue by azliabdullah** [vendure-ecommerce/vendure#149]
**Describe the bug**
After creating a new admin in admin-ui, and assigned him superadmin role, the newly created admin unable to login with error 'wrong credentials'. The password is correct.

**To Reproduce**

1. login to admin-ui as superadmin
2. go to Settings -> Administrators.
3. create new administrator.
4. fill in all info including password.
5. assign to superadmin role.
6. Save
7. Logout from superadmin user.
8. login as newly created user with correct password.

**Expected behavior**
- able to login into admin-ui

**Actual behavior**
- received error "The credentials did not match. Please check and try again"

**Environment (please complete the following information):**
@vendure/core version: 0.2.0 (master) and occurs in demo link as well.
Nodejs version: v12.9.0
Database (mysql/postgres etc): mariadb 10.3

**Comment by michaelbromley** [comment]
Thanks for the report. I'll investigate and update this issue about the fix.

**Comment by michaelbromley** [comment]
I tried to reproduce the issue following the reproduction steps, but it works for me. 

![2019-09-02_14-52-02](https://user-images.githubusercontent.com/6275952/64116150-cc1e4a80-cd91-11e9-9203-2b23449538aa.gif)

Can you double check you are entering the correct credentials?

**Comment by azliabdullah** [comment]
Thanks for the prompt response. Yes you're right, I have tested just now in demo link. I was able to login. I was so sure using correct passwords. But nevermind, I'll reopen if it happens again.
