### ISSUE TITLE
Make TypeORM health check timeout configurable 

### ISSUE THREAD

**Issue by mkucharz** [vendure-ecommerce/vendure#1494]
**Is your feature request related to a problem? Please describe.**
Sometimes default timeout for TypeORM health check (1000ms) is too low. I experienced it on smaller Cloud SQL (GCP) instances. 

**Describe the solution you'd like**
The solution is to add timeout to Vendure configuration and pass it to .pingCheck method.

**Additional context**
I guess it could be something like:

```
    systemOptions: {
        enableTypeORMHealthCheck: false,
        typeORMHealthCheckTimeout: 1000
    },
```

PS. I'm not sure about the naming, fell free to suggest something  different. 

It will require to add new config group `systemOptions` since it doesn't feel right to use any of existing groups.

**Comment by michaelbromley** [comment]
Just thought of another API which might be nice:

```ts
systemOptions: {
  healthChecks: HealthIndicatorFunction[];
}
```
and the default value is that it is populated with the `typeOrmHealthIndicator`. So to change the timeout you'd do it like this (pseudocode - need to define how to inject services here):
```ts
systemOptions: {
  healthChecks: [() => this.typeOrm.pingCheck('database', { timeout: 10000 })]
}
```

and if you want to omit it altogether, you just pass an empty array.

**Comment by mkucharz** [comment]
I guess that will be a bigger refactor of the default config, do you have an idea how to inject services here?
