### ISSUE TITLE
validateSlugs function always return value of a deleted product.

### ISSUE THREAD

**Issue by AbanoubAsaad** [vendure-ecommerce/vendure#1505]
**Describe the bug**
validateSlugs function always return value of a deleted product.

**To Reproduce**

1. Create new product with name product 1 => 
Expected => vedure generates slug product-1
Actual => vedure generates slug product-1

2. Create new product with the same name product 1
Expected => vedure generates slug product-2
Actual => vedure generates slug product-2

3. Delete the first product

4. Create new product with the same name product 1 
Expected => vedure generates slug product-1 (As the first product is deleted and product-1 slug is now free)
Actual => vedure generates slug product-1

5. Create new product with the same name product 
Expected => vedure generates slug product-3
Actual => vedure generates slug product-1

I released that the issue in the validateSlugs function inside the SlugValidator class.

**Suggested solution**

Line 60 ---->   if (match && !match.base.deletedAt)  => if (match) 
Line 68 ----> while (match && !match.base.deletedAt) => while (match)

**Comment by michaelbromley** [comment]
Fixed in https://github.com/vendure-ecommerce/vendure/commit/61de8575c72435d12dfdf3adfcdb0dbedf20007c
