### ISSUE TITLE
Epic: Core performance improvements

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#1506]
## Introduction

> first make it work, then make it right, and, finally, make it fast.
> -- [Kent Beck](https://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast)

Over the past ~1 year since Vendure v1.0 was released, we've collectively brought Vendure to the point that it handles all the basic commerce functionality well and does so in a pretty stable, correct way. In short, we've _made it work_ and we've also _made it right_, so now we need to concentrate on **making it fast**!

It must be said that Vendure is by no means _slow_, especially when compared to older e-commerce systems that pretty much required heavy use of caching to have anywhere near acceptable response times. However, there are a number of areas where we can hopefully get a _significant_ performance boost, especially when dealing with bigger instances (on the order of 100k - 1m orders, customers, product variants etc).

This issue is intended to tie together all current open performance-related issues so we can track overall progress.

## Areas of interest

There are 3 broad categories where we can potentially get some big improvements:

1. Optimizing the DB schema to make better use of indexes
2. Optimizing SQL queries to be more efficient
3. Using the dataloader pattern to batch calls and solve the "N + 1 problem".

The following existing issues explore these in more detail:

- #1502 
- #1475 
- #1503 
- #1370 
- Introspect selected fields and only fetch those using https://github.com/robrichard/graphql-fields

## Benchmarks

I plan to create a set of benchmarks by which we can attempt to objectively quantify any perf gains brought about by the above issues. Once created I'll publish baseline results here and then update after implementing solutions based on the above issues.

## Version

I would like to be able to release some or all of these improvements as part of a 1.x minor release, rather than waiting for Vendure 2.0. However, some (such as altering indexes) will result in breaking changes. In those cases, I will explore whether it is feasible to put these behind an opt-in config flag so that those who wish to benefit from the perf improvements may do so without having to use the v2.0 pre-release.

**Comment by nemo-js** [comment]
I am very exited about this feature!

We have an installation witch heavily relies on variants (ie each product have ~2k variants).
Admin UI is very slow on some operations (ie product save takes 30s+) 
and some jobs take too much time (ie collection filter takes 20mins).
I have not yet investigated why but I am planning to do it soon.

If I have some useful insights I will come back with an issue

**Comment by skid** [comment]
@nemo-js - If may ask - what kind of store do you have with 2k variants for each product?

**Comment by nemo-js** [comment]
@skid It has beds and matresses, which have many combinations of lengths and widths. I don't know if there is a better to way to handle it without using variants (or using less at least)

**Comment by edorivai** [comment]
Suggestion: perhaps some users of Vendure are already customers of [Apollo Studio](https://studio.apollographql.com/). I am at my day job, and it is the nr 1 tool I use to investigate API performance issues.

You get excellent graphs to break down response times:
![image](https://user-images.githubusercontent.com/765358/162171817-4c15cd97-b63c-4b8d-915d-21b0762041ab.png)

They subsequently allow you to dig into a particularly slow query sample, and see the response times _per field_:
![image](https://user-images.githubusercontent.com/765358/162171954-a6d02bca-66f6-4336-afff-54e931360bf0.png)

Different consumers of Vendure (the shops I mean) will have different access patterns and might run into vastly different performance bottlenecks. This will be extremely valuable data for @michaelbromley to crunch here.

Disclaimer:
Just a happy user of Apollo Studio, not affiliated with them at all.

**Comment by michaelbromley** [comment]
# Initial Benchmarks

Benchmark script added in the above-referenced commit

## Setup

```
$ cd packages/dev-server
$ yarn ts-node ./load-testing/benchmarks.ts --populate
```

This will populate 1000 products, each with 10 variants and 10k orders, each with 10 lines of 5 items each.

## Results

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-prod-list.js

...
http_reqs......................: 194     3.173058/s
iteration_duration.............: avg=315.12ms min=276.51ms med=299.56ms max=945.32ms p(90)=317.8ms  p(95)=363.91ms
iterations.....................: 193     3.156702/s
```

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js

...
http_reqs......................: 241     3.978276/s
iteration_duration.............: avg=251.35ms min=229.41ms med=248.16ms max=548.68ms p(90)=261.78ms p(95)=268.15ms
iterations.....................: 240     3.961769/s
```

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js --variant expanded

...
http_reqs......................: 260     4.293994/s
iteration_duration.............: avg=232.86ms min=208.4ms  med=231.69ms max=536.27ms p(90)=239.06ms p(95)=243.94ms
iterations.....................: 259     4.277479/s
```

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js --variant ids

...
http_reqs......................: 261     4.306887/s
iteration_duration.............: avg=232.17ms min=208.62ms med=229.8ms  max=548.33ms p(90)=240.31ms p(95)=247.98ms
iterations.....................: 260     4.290386/s
```

**Comment by michaelbromley** [comment]
## ListQueryBuilder optimization

The commit 8d87f05 introduces an optimization to the way relation joins are performed in the ListQueryBuilder. Here are the benchmarks run after this change:

### MariaDB

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-prod-list.js --db mysql
...
http_reqs......................: 224     3.684065/s
iteration_duration.............: avg=271.42ms min=220.46ms med=259.05ms max=645.17ms p(90)=305.33ms p(95)=336.43ms
```
```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js --db mysql
...
http_reqs......................: 811     13.385301/s
iteration_duration.............: avg=74.69ms min=59.05ms med=71.22ms max=544.88ms p(90)=86.99ms p(95)=91.44ms
```

### Postgres
```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-prod-list.js --db postgres
...
http_reqs......................: 188     3.092884/s
iteration_duration.............: avg=323.31ms min=246.25ms med=291.03ms max=851.16ms p(90)=438.48ms p(95)=500.03ms
```
```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js --db postgres
...
http_reqs......................: 965     15.933236/s
iteration_duration.............: avg=62.75ms min=46.99ms med=58.62ms max=557.92ms p(90)=76.88ms  p(95)=81.99ms
```

## Conclusion

This optimization speeds up the "orders" benchmark by around **4x**, which is good!

The "prod" benchmark is not significantly affected, because the poor perf of that one is mainly due to the n+1 problem when joining the `variants` field.

**Comment by michaelbromley** [comment]
## Relation fields optimization

The commit 063b5fef introduces a new `@Relations()` decorator that internally uses the [graphql-fields](https://github.com/robrichard/graphql-fields) package combined with introspection of the TypeORM metadata to return an array of TypeORM relations that are required based on the incoming query. Commit 04212851 applies this to the resolvers & service layer. 

<details><summary>MariaDB</summary>

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-prod-list.j
...
http_reqs......................: 303     4.999194/s
iteration_duration.............: avg=200.01ms min=167.25ms med=195.37ms max=604.13ms p(90)=216.19ms p(95)=226.12ms
```

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js
...
http_reqs......................: 1147    18.900468/s
iteration_duration.............: avg=52.89ms min=41.32ms med=50.28ms max=631.56ms p(90)=64.34ms p(95)=66.38ms
```

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js --variant expanded
...
http_reqs......................: 828     13.669382/s
iteration_duration.............: avg=73.14ms min=53.74ms med=69.14ms max=537.51ms p(90)=86.01ms  p(95)=92.51ms
```

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js --variant ids
...
http_reqs......................: 1400    23.116194/s
iteration_duration.............: avg=43.24ms min=31.5ms med=40.95ms max=557.4ms  p(90)=52.44ms  p(95)=55.41ms
```
</details>

<details><summary>Postgres</summary>

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-prod-list.js
...
http_reqs......................: 254     4.182275/s
iteration_duration.............: avg=239.07ms min=199.28ms med=225.91ms max=560.64ms p(90)=282.21ms p(95)=296.88ms
```

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js --db postgres
...
http_reqs......................: 1462    24.141314/s
iteration_duration.............: avg=41.41ms min=30.64ms med=39.26ms max=552.21ms p(90)=50.76ms  p(95)=53.94ms
```

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js --db postgres --variant expanded
...
http_reqs......................: 1034    17.048674/s
iteration_duration.............: avg=58.64ms min=43.48ms med=55.26ms max=580.39ms p(90)=72.22ms  p(95)=75.25ms
```

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js --db postgres --variant ids
...
http_reqs......................: 2742    45.278084/s
iteration_duration.............: avg=22.07ms min=15.55ms med=20.73ms max=541.54ms p(90)=27.21ms  p(95)=30.36ms
```
</details>

### Summary

This is a a good one. The smallest effect is seen in the product list query - again the bottleneck here is that the n+1 problem still exists. I did try to work around this but the code required became quite complex, so I decided that it is a relatively rare case to list products _and_ expand their variants too, so left it for now. So for that one, there is no significant improvement from that last set of benchmarks with the ListQueryBuilder optimization.

However, the order query benchmarks show some big gains since they fully leverage this optimization, especially with  postgres.

The MariaDB order list benchmarks see gains of **1.4 - 1.7x**
The postgres order list benchmarks see gains of **1.1 - 2.8x**

**Comment by michaelbromley** [comment]
## Adding Indexes to Postgres

The commit 16e52f26 introduces a new API which allows us to do low-level modifications to the DB schema of built-in entities without modifying core files. This commit also implements a function for this API which will add indexes to all many-to-one relations, as discussed in #1502.

```ts
import { addForeignKeyIndices, VendureConfig } from '@vendure/core';

export const config: VendureConfig = {
  // ...
  entityOptions: {
    metadataModifiers: [addForeignKeyIndices],
  },
};
```

<details><summary>Postgres</summary>

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-prod-list.js
...
http_reqs......................: 314     5.176688/s
iteration_duration.............: avg=193.16ms min=173.09ms med=187.57ms max=614.4ms  p(90)=199.48ms p(95)=209.33ms
```

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js --db postgres
...
http_reqs......................: 2230    36.82934/s
iteration_duration.............: avg=27.14ms min=21.62ms med=26.54ms max=523.11ms p(90)=29.35ms  p(95)=30.49ms
```

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js --db postgres --variant expanded
...
http_reqs......................: 1368    22.571053/s
iteration_duration.............: avg=44.29ms min=35.98ms med=41.88ms max=585.67ms p(90)=50.92ms  p(95)=56.97ms
```

```
$ yarn ts-node ./load-testing/benchmarks.ts --script bm-order-list.js --db postgres --variant ids
...
http_reqs......................: 2995    49.484889/s
iteration_duration.............: avg=20.19ms min=15.94ms med=19.66ms max=513.03ms p(90)=22.04ms  p(95)=23.25ms
```
</details>

### Summary

This change only applies to Postgres, because MySQL already adds indexes to FK relations by default. The results with Postgres are significant though - perf gains of **1.2 - 1.5x** over the previous benchmarks. And this is on a rather modest dataset - with a DB with 100k's of orders & 10k's of products/variants, this performance difference would likely be much more significant.
