### ISSUE TITLE
Unusable images  in admin-ui in case of custom asset server

### ISSUE THREAD

**Issue by ashitikov** [vendure-ecommerce/vendure#1514]
**Describe the bug**
If you use custom asset strategies or/and custom asset server where you don't need different set of image thumbnails, you will get something like this over the admin-ui:
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/8819544/162746677-68a811dc-9b2f-42fd-a4b8-905b1f2f4bba.png">

It can be fixed by applying following attributes to image:
```
object-fit: cover; 
width: 100%; 
height: 100%;
```
I'm not good at frontend, but seems _object-position_ attribute can be also helpful to implement focal point. 

**To Reproduce**
1. Implement asset strategies to avoid local thumbnail creation.
2. Go to admin-ui
3. Go to product list

**Expected behavior**
Correct size of asset images

**Environment (please complete the following information):**
 - @vendure/core version: 1.5.0
 - Nodejs version 14
 - Database (mysql/postgres etc): postgres

**Comment by martijnvdbrug** [comment]
If I understand correctly, this issue still persists. (I installed 1.5.2 and recompiled the admin)

To reproduce:
1. Go to the product list
2. Inspect one of the images and replace the `img src` with an image that is not 50x50, like this one: https://storage.googleapis.com/pinelab-shops-test-assets/preview/aa/webshop-001-003---25-september-2020---marc-de-fotograaf---4160-x-6240---web__02__preview.jpg
3. You will see that the image is still not resized.

If I add this to the element, it does resize the image:
```css
width: 50px;
height:50px;
object-fit: cover;
```

I tried to find the code and make a PR, but I have a hard time finding the correct css files...

This is what the admin does with not-resized images: 
![image](https://user-images.githubusercontent.com/6604455/164626004-529e3efe-b705-4d26-acb2-7d4d056dbe25.png)

**Comment by michaelbromley** [comment]
If you are using a custom Admin UI with ui-devkit, make sure to delete the generated files and re=build from scratch. I just tested the URL above on master and it seems to work as expected: 
![image](https://user-images.githubusercontent.com/6275952/164627528-2de8c3e3-5a38-4163-a9a9-de3e44a884ce.png)

**Comment by martijnvdbrug** [comment]
I deleted all generated files, but the issue persists, unfortunately.

Your screenshot shows the asset overview. It sort of works there for me, but it sometimes overlaps the name for not-square images: 
![image](https://user-images.githubusercontent.com/6604455/164642608-04cfaaa1-7797-4bb5-af39-489c49b9eca9.png)
:arrow_up: this is overseeable

However, on the **product list** it shows like this:
![image](https://user-images.githubusercontent.com/6604455/164643024-c1211552-80b3-47e4-861e-d4cd335113eb.png)

**Comment by tianyingchun** [comment]
if we defiend `assets` plugin `presets` maybe it should be dynamic write into stylings.

e.g. in my "assets" presets
```  presets: [
        { name: 'tiny', width: 150, height: 75, mode: 'resize' },
        { name: 'thumb', width: 150, height: 75, mode: 'resize' },
        { name: 'small', width: 300, height: 150, mode: 'resize' },
        { name: 'medium', width: 600, height: 300, mode: 'resize' },
        { name: 'large', width: 1200, height: 600, mode: 'resize' },
      ],
```
the correct style as below 
```
width: 100px;
height:50px;
object-fit: cover
```
it will perfect, for now i mannully replace `lib/admin-ui/index.html` to resolve this issue

``` ts
 try {
    const adminUICwd = require.resolve('@vendure/admin-ui-plugin').split('@vendure/admin-ui-plugin')[0];
    const adminUIIndex = join(adminUICwd, '@vendure/admin-ui-plugin', 'lib/admin-ui/index.html');
    const content = readFileSync(adminUIIndex, 'utf-8').replace(
      '</head>',
      '<style>.image-placeholder{width: 100px !important;  height: 50px;} img {max-width: 150px; height: auto !important;} </style></head>',
    );
    writeFileSync(adminUIIndex, content);
  } catch (err) {}

```

**Comment by martijnvdbrug** [comment]
@michaelbromley I also cannot reproduce it, sorry for wasting valuable time...
Not sure what went wrong on my end, I believe I was pretty thorough with deleting admin ui files.

Anyhow, this issue can be closed! :1st_place_medal:
