### ISSUE TITLE
SharedExtensionModule produces invalid syntax when no "shared" type module is present in extensions

### ISSUE THREAD

**Issue by EdwinObviousPeople** [vendure-ecommerce/vendure#1516]
https://github.com/vendure-ecommerce/vendure/blob/ce147dc13e139be6d734016f43f7abeed9fac8d9/packages/ui-devkit/src/compiler/scaffold.ts#L155-L162

The outer map should be preceded by a filter that checks for the presence of shared type modules inside the extension.

Currently the generated code can look like this.
```
@NgModule({
    imports: [CommonModule, , UIMenuItemsModule],
})
```

**Comment by michaelbromley** [comment]
Hi there,
thanks for the report! Would you like to submit a PR to fix this?

**Comment by michaelbromley** [comment]
I think this probably got fixed in the mean time, and we also changed our recommended approach for UI extensions since then, moving away from NgModules.
