### ISSUE TITLE
Race condition when modifying DB and running server & worker processes concurrently.

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#152]
**Describe the bug**
With `dbConnectionOptions.synchronize: true`, and changes to the DB (e.g. new CustomFields defined), running the server and worker processes concurrently results in errors presumably caused by a race condition as both of them attempt to make the necessary changes to the DB:

```
[run:server] info 9/6/19, 09:23 - [TypeORM] new columns added: customFieldsMayalsolike3id
[run:server] error 9/6/19, 09:23 - [TypeORM] Query error: Error: ER_DUP_FIELDNAME: Duplicate column name 'customFieldsMayalsolike3id', "ALTER TABLE `product` ADD `customFieldsMayalsolike3id` i
nt NULL" -- [undefined] 
[run:server] error 9/6/19, 09:23 - [TypeOrmModule] Unable to connect to the database. Retrying (1)... trace: 
[run:server] QueryFailedError: ER_DUP_FIELDNAME: Duplicate column name 'customFieldsMayalsolike3id'
[run:server]     at new QueryFailedError (C:\Development\vendure\vendure\src\error\QueryFailedError.ts:9:9)
[run:server]     at Query.<anonymous> (C:\Development\vendure\vendure\src\driver\mysql\MysqlQueryRunner.ts:166:37)
[run:server]     at Query.<anonymous> (C:\Development\vendure\vendure\node_modules\mysql\lib\Connection.js:525:10)
[run:server]     at Query._callback (C:\Development\vendure\vendure\node_modules\mysql\lib\Connection.js:491:16)
[run:server]     at Query.Sequence.end (C:\Development\vendure\vendure\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
[run:server]     at Query.ErrorPacket (C:\Development\vendure\vendure\node_modules\mysql\lib\protocol\sequences\Query.js:90:8)
[run:server]     at Protocol._parsePacket (C:\Development\vendure\vendure\node_modules\mysql\lib\protocol\Protocol.js:291:23)
[run:server]     at Parser._parsePacket (C:\Development\vendure\vendure\node_modules\mysql\lib\protocol\Parser.js:433:10)
[run:server]     at Parser.write (C:\Development\vendure\vendure\node_modules\mysql\lib\protocol\Parser.js:43:10)
[run:server]     at Protocol.write (C:\Development\vendure\vendure\node_modules\mysql\lib\protocol\Protocol.js:38:16)
[run:server] info 9/6/19, 09:23 - [TypeORM] columns changed in "customer". updating: deletedAt
[run:server] info 9/6/19, 09:23 - [TypeORM] columns changed in "product". updating: deletedAt
```
**To Reproduce**
1. Define a bunch of CustomFields in the VendureConfig)
2. Set `synchronize: true`
3. Start both processes with `concurrently`

**Expected behavior**
The DB should get updated only by the server process.

**Environment (please complete the following information):**
 - @vendure/core version: 0.2.0
 - Nodejs version: 12
 - Database (mysql/postgres etc): MariaDB

**Possible fix**
My immediate idea is to simple enforce that `synchronize` gets always set to `false` for the worker. This can be done internally in the `bootstrapWorker` function, so the end user does not need to think about it.

**Comment by Logic-Bits** [comment]
Hi!

![grafik](https://github.com/vendure-ecommerce/vendure/assets/2421123/c8736c2f-7e51-43eb-b5a7-0f1b5c2c4c11)

I believe in preBootstrapConfig, setConfig gets called.
And in Line 105 of the bootstrap.ts the config gets edited (syncronize to false).
The config will not be set again tho! Which means that ConnectionModule.forRoot (gets called in worker module) the synchronize option is still set to true!

Maybe im wrong :)

**Comment by michaelbromley** [comment]
Hi @Logic-Bits, are you running into some particular error that you think is related to this old issue?

**Comment by Logic-Bits** [comment]
I was testing some things with the worker on my end.
For a long time I did not enable to worker. When I enabled it, the worker actually deleted my custom fields / columns from the database.
I figured thats where the error came from.
