### ISSUE TITLE
Admin UI sidebar dissapearing when adding navigation items.

### ISSUE THREAD

**Issue by driccio98** [vendure-ecommerce/vendure#1521]
**Describe the bug**
When I follow the tutorial on adding navigation items to Admin UI it shows the new added item correctly, however when I click on any navigation items the sidebar disappears, I'm also adding an external react app to render in that new navigation item.

**To Reproduce**
1. Follow the tutorial on [here](https://www.vendure.io/docs/plugins/extending-the-admin-ui/adding-navigation-items/)
2. Route the navigation item to a react app.
3. Click on any navigation items in the Admin UI
5. See error (Sidebar disappears completely)

**Expected behavior**
The sidebar must not disappear because the only way to get it back is to reload the page

**Environment (please complete the following information):**
 - @vendure/core version: 1.5.1
 - Nodejs version: 16.14.2
 - Database (mysql/postgres etc): mysql

**Additional context**
Screenshots:
Before:
![image](https://user-images.githubusercontent.com/57051444/163852962-1f79ef24-4bf1-42e4-b576-c806dec880cc.png)
After: 
![image](https://user-images.githubusercontent.com/57051444/163853046-0f8ce8d0-3ecd-49ea-bb23-3396a25b005b.png)
NOTE: Ignore product images

Console Output:
`PS F:\Workspace\vendure-ui-extension> yarn start
yarn run v1.22.18
$ concurrently yarn:run:*
$ ts-node ./src/index-worker.ts
$ ts-node ./src/index.ts
[run:*server] info 4/18/22, 1:04 PM - [Vendure Server] Bootstrapping Vendure Server (pid: 20796)... 
[run:*worker] info 4/18/22, 1:04 PM - [Vendure Worker] Bootstrapping Vendure Worker (pid: 14044)... 
[run:*worker] info 4/18/22, 1:04 PM - [Vendure Worker] Vendure Worker is ready
[run:*worker] info 4/18/22, 1:04 PM - [JobQueue] Starting queue: apply-collection-filters 
[run:*worker] info 4/18/22, 1:04 PM - [JobQueue] Starting queue: send-email
[run:*worker] info 4/18/22, 1:04 PM - [JobQueue] Starting queue: update-search-index      
[run:*server] info 4/18/22, 1:04 PM - [AssetServerPlugin] Creating asset server middleware       
[run:*server] info 4/18/22, 1:04 PM - [EmailPlugin] Creating dev mailbox middleware
[run:*server] info 4/18/22, 1:04 PM - [AdminUiPlugin] Creating admin ui middleware (dev mode)    
[run:*server] info 4/18/22, 1:04 PM - [AdminUiPlugin] Compiling Admin UI app in development mode 
[run:*server] info 4/18/22, 1:04 PM - [RoutesResolver] HealthController {/health}: 
[run:*server] info 4/18/22, 1:04 PM - [RouterExplorer] Mapped {/health, GET} route 
[run:*server] info 4/18/22, 1:04 PM - [AdminUiPlugin] Admin UI compiling and watching for changes... 
$ ng serve --port=4200 --base-href=/admin/
[run:*server] info 4/18/22, 1:04 PM - [NestApplication] Nest application successfully started 
[run:*server] info 4/18/22, 1:04 PM - [Vendure Server] ================================================ 
[run:*server] info 4/18/22, 1:04 PM - [Vendure Server] Vendure server (v1.5.1) now running on port 3000 
[run:*server] info 4/18/22, 1:04 PM - [Vendure Server] ------------------------------------------------ 
[run:*server] info 4/18/22, 1:04 PM - [Vendure Server] Shop API:     http://localhost:3000/shop-api     
[run:*server] info 4/18/22, 1:04 PM - [Vendure Server] Admin API:    http://localhost:3000/admin-api    
[run:*server] info 4/18/22, 1:04 PM - [Vendure Server] Asset server: http://localhost:3000/assets       
[run:*server] info 4/18/22, 1:04 PM - [Vendure Server] Dev mailbox:  http://localhost:3000/mailbox      
[run:*server] info 4/18/22, 1:04 PM - [Vendure Server] Admin UI:     http://localhost:3000/admin
[run:*server] info 4/18/22, 1:04 PM - [Vendure Server] ================================================
[run:*server] Option "baseHref" is deprecated: Use the "baseHref" option in the browser builder instead.
[run:*server] - Generating browser application bundles (phase: setup)...
[run:*server] error 4/18/22, 1:04 PM - [Admin UI live reload] [HPM] Error occurred while proxying request localhost:3000/admin/sockjs-node/info?t=1650305053976 to http://localhost:4200/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors) 
[run:*server] ✔ Browser application bundle generation complete.
[run:*server] 
[run:*server] Initial Chunk Files                                                                                     | Names         |      Size
[run:*server] vendor.js                                                                                               | vendor        |  10.14 MB
[run:*server] styles.css, styles.js                                                                                   | styles        |   1.09 MB
[run:*server] polyfills.js                                                                                            | polyfills     | 563.05 kB
[run:*server] main.js                                                                                                 | main          |  15.83 kB
[run:*server] runtime.js                                                                                              | runtime       |  12.92 kB
[run:*server]
[run:*server]                                                                                                         | Initial Total |  11.81 MB
[run:*server]
[run:*server] Lazy Chunk Files                                                                                        | Names         |      Size
[run:*server] node_modules_vendure_admin-ui___ivy_ngcc___fesm2015_vendure-admin-ui-catalog_js.js                      | -             | 798.02 kB
[run:*server] node_modules_vendure_admin-ui___ivy_ngcc___fesm2015_vendure-admin-ui-order_js.js                        | -             | 676.79 kB
[run:*server] node_modules_vendure_admin-ui___ivy_ngcc___fesm2015_vendure-admin-ui-settings_js.js                     | -             | 675.96 kB
[run:*server] node_modules_vendure_admin-ui___ivy_ngcc___fesm2015_vendure-admin-ui-customer_js.js                     | -             | 278.48 kB
[run:*server] node_modules_vendure_admin-ui___ivy_ngcc___fesm2015_vendure-admin-ui-marketing_js.js                    | -             |  79.91 kB
[run:*server] node_modules_vendure_admin-ui___ivy_ngcc___fesm2015_vendure-admin-ui-dashboard_js.js                    | -             |  73.46 kB
[run:*server] node_modules_vendure_admin-ui___ivy_ngcc___fesm2015_vendure-admin-ui-system_js.js                       | -             |  65.12 kB
[run:*server] default-node_modules_vendure_common_lib_generated-shop-types_js.js                                      | -             |  33.30 kB
[run:*server] node_modules_vendure_admin-ui___ivy_ngcc___fesm2015_vendure-admin-ui-login_js.js                        | -             |  22.26 kB
[run:*server] common.js                                                                                               | common        |   4.60 kB
[run:*server] src_extensions_0948782e90c89826d1ceb616b763dfd88ac89048d2b07e05a70fa1ddb8618fd0_react-extensi-de33e7.js | -             |   2.98 kB
[run:*server]
[run:*server] Build at: 2022-04-18T18:04:30.743Z - Hash: 55c08a403e625bf8845e - Time: 16777ms
[run:*server]
[run:*server] ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/admin **
[run:*server]
[run:*server]
[run:*server] √ Compiled successfully.`

**Comment by michaelbromley** [comment]
Looks like a change in the Clarity UI library is responsible: https://github.com/vmware-clarity/ng-clarity/commit/af6c44ce23b47514c15dec60f1db07134cf62f1a

This commit seems to add the "hiding" logic, but I'm not totally sure why yet.

**Comment by michaelbromley** [comment]
Opened an issue on the Clarity repo: https://github.com/vmware-clarity/ng-clarity/issues/89

In the mean time I will find a work-around.
