### ISSUE TITLE
Admin and Customer accounts with the same email

### ISSUE THREAD

**Issue by skid** [vendure-ecommerce/vendure#1524]
Currently you can create a customer for `alice@example.com`, and an administrator for `alice@example.com`. This will create 2 different user entities and 2 different authentication methods. Then, if `alice@example.com` tries to log in as an admin, she can't because the `BaseAuthResolver` finds her customer authentication method and it can't find an admin user linked to it. 

Vendure should either:

1. Not allow administrators to use the same email as customers (effectively tie the email identifier with a user entity); OR
2. Allow two (admin and customer) accounts on the same email. 

I think that 2 is preferable, since with multi-tenant setups you might not want to ask your shop owners to use different emails for administration and shopping. Ideally you should have 2 separate sessions depending on whether you're logged on the admin-api or shop-api. This would require adding 2 session keys to the cookie, since both APIs are on the same domain.

**Comment by michaelbromley** [comment]
This was resolved by #2016
