### ISSUE TITLE
Integrating Vue Storefront & Vendure

### ISSUE THREAD

**Issue by jessicana** [vendure-ecommerce/vendure#1541]
**To Reproduce**
On a fresh ubuntu 22.04 instance. I installed node JS v16.15.0. I followed [this guide](https://www.vendure.io/blog/2021/10/fullstack-open-source-e-commerce-vue-storefront-vendure/) and all went well until I run: `yarn dev`

**Environment:**
 - @vendure/core version: 1.5.2
 - Nodejs version: 16.15.0
 - Database (mysql/postgres etc): SQLite

**Additional context**
When I run `yarn dev`, I got this error:

 ERROR  (node:16232) [DEP0128] DeprecationWarning: Invalid 'main' field in '/root/my-app/vue-storefront/node_modules/@vue-storefront/nuxt-theme/package.json' of 'lib/module.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

![image](https://user-images.githubusercontent.com/7415824/166120010-0d94da1c-327b-418d-bd11-bc0c8eae7aca.png)

I also tried `npm run start` and I got this error:
   │   ✖ Nuxt Fatal Error                                                                │
   │                                                                                     │
   │   Error: No build files found in /root/my-app/vue-storefront/.nuxt/dist/server.     │
   │   Use either `nuxt build` or `builder.build()` or start nuxt in development mode.  

![image](https://user-images.githubusercontent.com/7415824/166120045-4c20df7c-1e4a-43ef-963a-37f073add472.png)

Installation information:
![image](https://user-images.githubusercontent.com/7415824/166120128-98a58488-3796-408a-9312-005b94fcde22.png)

**Comment by michaelbromley** [comment]
Hi there,

Thanks for the report. Since the error seems specific to the VSF integration, could you instead report it in this repo (https://github.com/vuestorefront-community/vendure)? You'll likely get the attention of someone who can help better than I can.
