### ISSUE TITLE
Multiple stock location support

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#1545]
**Is your feature request related to a problem? Please describe.**
Currently each ProductVariant has a stockOnHand which represents the number of units in stock. Some businesses have multiple stock locations and it can be useful to be able to associate a stock level with a particular location. For example, this can allow the storefront to display the stock level at a given outlet.

**Describe the solution you'd like**
Allow the configuration of multiple stock locations, and each ProductVariant has a stock level at each location.

**Describe alternatives you've considered**
Some kind of custom solution using custom fields could probably be implemented already, but it would lack the first-class support for automatic stock tracking that is built in to Vendure.

**Comment by tufail** [comment]
Hi @michaelbromley 
Thank you for looking into this feature. When can we expect to be release this feature.

**Comment by michaelbromley** [comment]
@tufail it is planned for Vendure v2, which unfortunately I don't have a timeline for at the moment beyond "i want to release it this year". However, work on v2 has already begun and is available on the `major` branch and can also be used in your projects using the `@vendure/core@next` tag in npm. So it is possible that this specific feature will become available on the `next` tag sooner.

**Comment by asiz15** [comment]
Hi @michaelbromley !

Any news about this feature?
If not, could you briefly guide me on the solution you mention using custom fields?

Thanks!

**Comment by michaelbromley** [comment]
Hi @asiz15, any news will be reflected in this issue - so I've not started working on this yet.

So the idea with custom fields would be something like this:

- Define a new entity to represent a stock location 
- Define a new entity to represent an amount of stock of a given variant in a given location
- Create a customField on ProductVariant relating one of those entities for each stock location, representing the stock of that variant in the given location.
- You'd need to add some custom logic to manage whether customer can actually add an item to the order based on this data. E.g. you could override the `addItemToOrder` mutation to include this check.

**Comment by michaelbromley** [comment]
Here's a high-level outline of how I expect this to work:
![image](https://user-images.githubusercontent.com/6275952/213655153-6c049efd-e5a8-42ec-8e66-f32efea169b8.png)

### StockLocation

One or more `StockLocation` entities will exist. We will create a "default StockLocation" as part of migrating from the existing schema, and then additional locations can be defined. This entity will accept custom fields so you can store things like geo location, description, address - whatever.

This entity represents a physical location where stock exists.

### StockLevel

This entity represents the quantity of a given `ProductVariant` at a given `StockLocation`. So as part of the initial migration we would create a single `StockLevel` for every `ProductVariant`, and copy the current `stockOnHand` level over from the variant and relate it to the default `StockLocation`.

### StockLocationStrategy

We'll need a strategy for defining:

1. **How stock levels are calculated**. The obvious default is to sum up all the StockLevels for each location. But it is conceivable that you might want to customize this based on other factors - membership of a CustomerGroup, physical location, etc.
2. **How stock is allocated**. When someone buys an item, we need to define the logic which selects which StockLocation it comes from. Again, the rules for this are highly requirements-specific so this strategy will allow us to support everything.

### Other details

- Do we keep `ProductVariant.stockOnHand`? Technically it will be redundant because the value can be derived from the related StockLevel entities. However, I tend to think it makes sense to keep it for reasons of efficiency (deriving the value in real-time might get slow) and also for better backwards-compatibility. In this case we be really careful that it does not get out of sync, so some kind of constraint mechanism might be needed to prevent it getting wrongly assigned.

**Comment by giovramirez** [comment]
Hi @michaelbromley!

Could be these ideas related to have a strategy to look into a external inventory?

Let's say our stock levels for X item go to 0 but I would like to check with our wholesalers' inventory (using an API) if they have availably for that item.

**Comment by michaelbromley** [comment]
@giovramirez That's a good point. Yes, I think the strategy method that returns available stock levels could also e.g. make an API call if nothing is in stock locally.

**Comment by martijnvdbrug** [comment]
Ahh clear, my bad, thought that was already done :ok_hand:

**Comment by martijnvdbrug** [comment]
Question, not sure if it belongs here, but:

Let's say we want to track our inventory with an external service, like so:

(In our custom [StockLocationStrategy](https://github.com/vendure-ecommerce/vendure/blob/cc05af6647ea55a47aed4b0f18b9fbcc816d3e24/packages/core/src/config/catalog/stock-location-strategy.ts#L53) )
```ts
getAvailableStock(
        ctx: RequestContext,
        productVariantId: ID,
        stockLevels: StockLevel[],
    ): AvailableStock | Promise<AvailableStock> {
    
    return this.externalService.getStock(productVariantId)
}
```

How would we then handle allocation? I would actually like that Vendure doesn't do anything with allocation, but rather have the external service handle saleable/allocated stock levels. Is this possible, or does Vendure always use the concept of allocation?

**Comment by michaelbromley** [comment]
@martijnvdbrug I think that's worth a separate issue.
