### ISSUE TITLE
Default Email Handlers

### ISSUE THREAD

**Issue by anacchaves** [vendure-ecommerce/vendure#1547]
**Is your feature request related to a problem? Please describe.**
We can't change the language of the subject lines on emails sent from the `default-email-handler` , since they are defined inside `node_modules/@vendure/email-plugin`

**Describe the solution you'd like**
It would be ideal if the subject line could be passed as a variable - same way it's done with  `fromAddress`

**Describe alternatives you've considered**
We  thought about creating a new email handler that would replace the default, but couldn't find a way to make this change and still don't know if it would work.

**Comment by michaelbromley** [comment]
Hi there,

I think you should be able to achieve this by modifying the defaults to add your own subject lines:

```ts
import { orderConfirmationHandler } from '@vendure/email-plugin' 

// ...

EmailPlugin.init({
  handlers: [
      orderConfirmationHandler.setSubject('my subject'),
  ],
}
``` 

This should just change the subject line and otherwise keep the default handler working as it did before.

**Comment by anacchaves** [comment]
It worked! Thanks!

**Comment by michaelbromley** [comment]
Great! I'll close this issue then 👍
