### ISSUE TITLE
Audit Fields UpdatedBy and CreatedBy in the Base Entity

### ISSUE THREAD

**Issue by naga-sagarika** [vendure-ecommerce/vendure#1555]
Audit fields like UpdatedBy and CreatedBy in Base Entity would be a good to have feature.

**Comment by michaelbromley** [comment]
Yes this would be good, I agree. It'd be a breaking change though to the schema so it would be something I'll consider for v2.

**Comment by michaelbromley** [comment]
This is not planned for core currently. It's possible this will be made available as a enterprise-focused plugin in future.
