### ISSUE TITLE
Canceling an order in "ArrangingPayment" does a deallocation

### ISSUE THREAD

**Issue by ivasilov** [vendure-ecommerce/vendure#1557]
**Describe the bug**
When cancelling an order in `ArrangingPayment`, deallocation is done (even though no allocation happened because by default allocation happens in `PaymentSettled` state). 

**To Reproduce**
1. Get an order to `ArrangingPayment` state (it's easiest to do through the Admin panel)
2. Cancel the whole order 

**Expected behavior**
The `stockAllocated` field on the product variants in the order should be zero but they're set to negative value.

**Environment (please complete the following information):**
- Vendure 1.5.1

**Additional context**

**Comment by michaelbromley** [comment]
Note: possibly related to #1571 and #661

**Comment by ivasilov** [comment]
This bug happens when using the Admin UI.  This is our strategy:

```
export class OrderPlacedOnArrangingPaymentStrategy implements OrderPlacedStrategy {
  shouldSetAsPlaced(_ctx: RequestContext, fromState: OrderState, toState: OrderState): boolean {
    if (fromState === 'AddingItems' && toState === 'ArrangingPayment') {
      return true;
    }
    return false;
  }
}
```
We haven't changed the order process. I forgot about our `OrderPlacedStrategy`, sorry.
