### ISSUE TITLE
Canceling an item blocks the fullfilment on the order

### ISSUE THREAD

**Issue by ivasilov** [vendure-ecommerce/vendure#1558]
**Describe the bug**
If an admin first cancels an item, he's unable to create a fulfillment for an order.

**To Reproduce**
1. Get an order to `PaymentSettled`.
2. Cancel one item (without refund)
3. The `fulfill order` button is grayed out.

**Expected behavior**
The admin should be able to fulfill the non-cancelled order items without any issue.

**Environment (please complete the following information):**
 - @vendure/core version: 1.5.1
 - Nodejs version: v16
 - Database (mysql/postgres etc): Postgres

**Comment by ivasilov** [comment]
I figured out what's causing this bug so it may be useful when fixing the bug.

The issue is caused by:
- when there multiple items for a single line
- fullfilment has happened for some of the items, but not all
- the admin cancelled the rest of the items

When the admin cancelled the items, the order items in the DB are randomly picked and marked as cancelled. This includes items which have been fulfilled so you end up with cancelled fullfilled items while there's non-cancelled unfulfilled items.

An easy fix for this would be to add logic when cancelling items, the unfullfilled ones should be marked as cancelled first.

**Comment by michaelbromley** [comment]
Thanks for the investigation. Sounds like it should not be too much trouble to fix in the next patch version.
