### ISSUE TITLE
Collection.productVariants slow perf post 1.6

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#1578]
**Describe the bug**
In v1.6 we introduced the mechanism of graphql lookaheads to speed up list queries. This has given rise to a perf regression in a specific case when querying a Collection with its `productVariants` field (both the `collection` and `collections` queries are affected).

The reason for this is that the `@Relations()` decorator sees the `productVariants` field being selected, so it adds that to the list of relations to join. However, then the `Collection.productVariant` field resolver executes and _re-fetches_ the same productVariant relations. So the work is done twice and leads to slow queries.

In fact, there is _zero benefit_ to the lookahead for the `Collections.productVariants` relation, since the GraphQL type actually exposes a PaginatedList, so the field resolver _always_ has to run anyway.

So a better solution is to somehow communicate to the `Relations` decorator that certain relations should always be omitted from the resulting relations array. Not sure as to the best method for this yet. Needs some design.

**Environment (please complete the following information):**
 - @vendure/core version: 1.6.1
 - Nodejs version: any
 - Database (mysql/postgres etc): any

**Comment by ashitikov** [comment]
I think the better way is to have a special decorator for field resolver, that will try to resolve field from the corresponding field of parent object, and if undefined, will call original resolver function. To avoid excessive decoration, we can use field middleware technique: https://docs.nestjs.com/graphql/field-middleware.

**Comment by ashitikov** [comment]
Yes, like this one. If case with product variants: because list query builder already joined product variants due to the new `@Relations()` decorator, field resolver `productVariants` will just return product variants from its parent entity without an additional queries to database. 

Also maybe it worth to look at data loader pattern in graphql world.

**Comment by michaelbromley** [comment]
A similar issue applies to the following types/relations:

- `Customer.orders`
- `CustomerGroup.customers`
- `Product.variants`
- `Product.assets`
- `ProductVariant.assets`
- `Collection.assets`

**Comment by ashitikov** [comment]
Using global middleware will raise a problem if developers wants field resolver to be called even if we have this relation in parent entity. So I guess decorator or field middleware is more controllable solution. Like:
`
@ResolveField({ middleware: [tryResolveFromParent] })
async group(...) {
// No checks on parent entity data
...
}
`
