### ISSUE TITLE
Manage Variants creates issue on values mapping 

### ISSUE THREAD

**Issue by naga-sagarika** [vendure-ecommerce/vendure#1588]
The option values in createNewProductVariants in 
packages/admin-ui/src/lib/catalog/src/components/product-variants-editor/

gives a wrong result 

![image](https://user-images.githubusercontent.com/28944154/170620585-0e69d84a-8742-49c3-b61d-bed2b35f6fde.png)

**Comment by michaelbromley** [comment]
Hi,

Can you provide a bit more detail here? What is the expected result vs the actual (wrong) result?

**Comment by naga-sagarika** [comment]
If there are two options Storage and Ram , and say both are give option values as  16GB and 16GB. The variant creation will not happen. It throws an error.

**Comment by michaelbromley** [comment]
This issue relates to a version of Vendure that is no longer supported. If the issue persists in the latest version, please open a new issue.
