### ISSUE TITLE
Any plans to add multi-vendor support?

### ISSUE THREAD

**Issue by ch3ckmat3** [vendure-ecommerce/vendure#1601]
This seems promising, but like many other headless commerce offerings, this one also lacks multi-vendor support. Any plans to add this feature, and if it is not too rude to ask for any other open-source head-less planform which is offering multi-vendor at the moment.

Cheers

**Comment by michaelbromley** [comment]
Hi there! It currently *is* possible to build multi vendor apps (there are several I have heard of in development), but currently it not particularly straightforward. 
But to answer the question - yes, better multi vendor support is one of the main areas of focus for the next version, see https://github.com/vendure-ecommerce/vendure/issues/1329

> any other open-source head-less planform which is offering multi-vendor at the moment

Not really. You can check Medusa, there is a community extension that seems to enable some degree of multi vendor support but it also involves significant customization work and I don't know it well enough to say whether or not it is better or worse than what can be currently achieved with Vendure.

**Comment by ch3ckmat3** [comment]
Thank you for the reply, Looking forward to #1329.
