### ISSUE TITLE
Query orderLineById does not return correct quantity

### ISSUE THREAD

**Issue by christopheblin** [vendure-ecommerce/vendure#1606]
**Describe the bug**
The orderLineById always returns quantity = 0

> The query is alos undocumented in https://www.vendure.io/docs/graphql-api/admin/queries/

**To Reproduce**
![Capture d’écran 2022-06-07 à 08 57 41](https://user-images.githubusercontent.com/11044877/172316169-ee22a7f5-483b-4dd3-a250-354f883e4bc4.png)
![Capture d’écran 2022-06-07 à 08 57 34](https://user-images.githubusercontent.com/11044877/172316171-dd0ed4bc-7a83-4461-84bc-40e784bce966.png)

**Expected behavior**
Return the correct quantity

**Environment (please complete the following information):**
 - @vendure/core version: 1.5.1

**Comment by christopheblin** [comment]
@michaelbromley in 1.5.1, the query is inside our own plugin so I changed

```
  @Query()
  @Allow(Permission.ReadAdministrator)
  orderLineById(@Args() args: Args): Promise<OrderLine | undefined> {
    return this.conn.getRepository(OrderLine).findOne(id);
  }
```

by 

```
  @Query()
  @Allow(Permission.ReadAdministrator)
  orderLineById(@Args() args: Args): Promise<OrderLine | undefined> {
    return this.conn.getRepository(OrderLine).findOne(id, { relations: ['items'] });
  }
```

I am not sure this bug is in the vendure/core (and I am not sure the fix is correct...)

**Comment by michaelbromley** [comment]
It's not really a bug as such, since the `OrderLine.quantity` property is a getter which just returns `items.length`. But perhaps there could be some warning logged if you try to access it when the items have not been joined.

**Comment by michaelbromley** [comment]
OK I think a good way to handle this would be to modify this getter: https://github.com/vendure-ecommerce/vendure/blob/464924c2bc332c724a43df009f0250991cad1bcb/packages/core/src/entity/order-line/order-line.entity.ts#L264-L266

to log a warning like: 

```ts
get activeItems(): OrderItem[] {
  if (this.items == null) {
    Logger.warn(`some warning about needing to join the orders 'lines' relation`);
  }
  return (this.items || []).filter(i => !i.cancelled);
}
```
