### ISSUE TITLE
Does not show out of stock

### ISSUE THREAD

**Issue by anytimewp** [vendure-ecommerce/vendure#1608]
http://95.111.193.127:4000/product/59/bridal-kanchi-pattu--bkp7  when the product is out of stock, does not show out of stock.

I think the option to add to product should be hidden on product single page and even on catalog or category page add to cart button should be disabled and show in other color so people can identify easily.  Adding a label on top would be nice in category page.

**Comment by michaelbromley** [comment]
Hi, could you please open this on the https://github.com/vuestorefront-community/vendure repo instead?
