### ISSUE TITLE
Payment Method Custom Field Asset returning null in api

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#1610]
I have a custom field of type asset for payment method, the field is already populated with image, but I receive null in playground and API requests. Please fix it asap.

![image](https://user-images.githubusercontent.com/29729738/172380631-4f298068-70dd-43f2-98a8-353fbf610851.png)

**Comment by michaelbromley** [comment]
Thanks for the report, I'll look into it for the next patch release.

> Please fix it asap.

Just a note: I'm not sure if it's your intention, but in English this phrase comes across quite demanding and rude. It's the kind of thing I might expect my boss to say to me, if I had one 😄
