### ISSUE TITLE
listQueryBuilder return translations array only one record return

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#1611]
**Describe the bug**
 listQueryBuilder return translations array only one record return.

**To Reproduce**
1. consider below service query
```ts

  findAll(
    ctx: RequestContext,
    options?: ListQueryOptions<EdmEmailTemplate>,
    relations?: RelationPaths<EdmEmailTemplate>,
  ): Promise<PaginatedList<Translated<EdmEmailTemplate>>> {
    return this.listQueryBuilder
      .build(EdmEmailTemplate, options, {
        ctx,
        relations: relations ?? ['edmEmailTemplateType'],
      })
      .getManyAndCount()
      .then(([emailTemplates, totalItems]) => {
        const items = emailTemplates.map((bannerItem) => translateDeep(bannerItem, ctx.languageCode, []));
        return {
          items,
          totalItems,
        };
      });
  }
```
3. shop-api
4. query all items like 
```ts
{
   banners(options: {take:1}) {
    items{ 
      id
      name
      languageCode
      translations {
        id
        languageCode
        name
      }
     }
  }
}
```
6. See results
```ts
{
  "data": {
    "banners": {
      "items": [
        {
          "id": "1",
          "name": "KZFOO BOGO",
          "languageCode": "en",
          "translations": [
            {
              "id": "1",
              "languageCode": "en",
              "name": "KZFOO BOGO"
            }
          ]
        }
      ]
    }
  }
}
```

**Expected behavior**
the `translations` should return all records

**Environment (please complete the following information):**
 - @vendure/core version: 1.6.2
 - Nodejs version 17
 - Database (mysql/postgres etc): mysql

**Additional context**
 findOne is correct.

**Comment by michaelbromley** [comment]
This is a tough one! I've created some failing e2e tests (see commit above) but I'm not sure on how to solve it at the moment.

If anyone wants to have a go, convert the failing test from `xdescribe()` to `describe()` and the changes will be needed in this part: https://github.com/vendure-ecommerce/vendure/blob/0ce7caf56d7e0adfc25d1b3a738c4ce8c6d911c6/packages/core/src/service/helpers/list-query-builder/list-query-builder.ts#L532-L585

The SQL query is pretty complex as it has to cover many different scenarios, which are luckily all covered in existing e2e tests, so any regressions in attempting to solve this issue should become immediately apparent.
