### ISSUE TITLE
Bidirectional relation between assets and products

### ISSUE THREAD

**Issue by dima-pashchenko** [vendure-ecommerce/vendure#1617]
Only relation from [products to assets](https://github.com/vendure-ecommerce/vendure/blob/0dfa9d0b4b7f9f6af1c6406d44b096543c28db3e/packages/core/src/entity/product/product.entity.ts#L48) described in entities for now. In my case I need relation [from assets to products](https://github.com/vendure-ecommerce/vendure/blob/0dfa9d0b4b7f9f6af1c6406d44b096543c28db3e/packages/core/src/entity/asset/asset.entity.ts#L54). 

Extending by custom fields doesn't work for me, [described here](https://stackoverflow.com/questions/72546231/vendure-how-to-add-many-to-many-relation-custom-field-and-query-it)

**Comment by michaelbromley** [comment]
Hi,

From the info provided on the StackOverflow question, it looks like maybe the database didn't get updated. Did you run a migration after defining the custom field (or have the `dbConnectionOptions.synchronize` option set to `true`?) (docs: https://www.vendure.io/docs/developer-guide/migrations/)

**Comment by dima-pashchenko** [comment]
Hi @michaelbromley 
As far I understood we already have required schema to build relation many-to-many from asset to product via product_asset junction table 

As you recomended I've generated migration:
```
public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "asset_custom_fields_products_product" ADD CONSTRAINT "FK_e2e492480089c94e685b6ff4514" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "asset_custom_fields_products_product" ADD CONSTRAINT "FK_2404a1acc93bfc8b7ce84735328" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
}
```

But expectedly it fails because there is no "asset_custom_fields_products_product" table
```
error: error: relation "asset_custom_fields_products_product" does not exist
```

Am I missing something else?

**Comment by michaelbromley** [comment]
Hi,
Sorry, I'm not sure what the issue is in that case. If you can provide a minimal repo that reproduces it (also specify which DB & versions you are using) then I can try to reproduce when I have time.

**Comment by dlhck** [comment]
This issue is being closed because further data was needed but was not provided. If you want to continue the thread, comment below with the required information and the issue can be re-opened.
