### ISSUE TITLE
[admin-ui] enable user to add variants to an already created product

### ISSUE THREAD

**Issue by lsimone** [vendure-ecommerce/vendure#162]
**Description**
Right now there's no way to add variants to an already created product

**Describe the solution you'd like**
Provide a consistent UI to define a new option: keep the `add option` form that currently is hidden after the product creation.

![image](https://user-images.githubusercontent.com/3266650/64802501-1d48ee00-d58b-11e9-9bd0-956dbf088efe.png)

**Comment by michaelbromley** [comment]
This is done and will be available in the next release, v0.3.0
