### ISSUE TITLE
Failed applying promotion to order due to QueryFailedError

### ISSUE THREAD

**Issue by jihadkamil** [vendure-ecommerce/vendure#1624]
**Describe the bug**
- Failed applying promotion to order
- QueryFailedError: invalid input syntax for type integer: "NaN" 

 
**To Reproduce**
1. Go to orderService.applyCouponCode with 
2. order ={ ...order,
      "administration":{
         "items":[
            {
               "name":"Payment Fee",
               "label":"0",
               "value":0
            },
            {
               "name":"Tax",
               "value":445946,
               "label":"445946"
            }
         ],
         "total":0
      }}
3. See error

**Expected behavior**
success applyCouponCode

**Environment (please complete the following information):**
 - @vendure/core version: 1.3.1
 - Nodejs version 16.14.2
 - Database (mysql/postgres etc): postgres

**Additional context**
I found the problem is when we use applyCouponCode with order.administration[0].value = 0, the func calculateOrderTotals will assign NaN value to variable totalPrice & totalPriceWithTax. That's what caused  QueryFailedError: invalid input syntax for type integer: "NaN" => Failed applying promotion to order

**Comment by michaelbromley** [comment]
Hi,

I don't really understand what you are trying to do here - what's `order.administration`? Is this some customization of yours? 

Also, the `OrderService.applyCouponCode()` does not take an `order` object. This issue seems to be lacking some critical context that would allow me to assist better. Can you clarify?

**Comment by michaelbromley** [comment]
This issue is being closed because further data was needed but was not provided. If you want to continue the thread, comment below with the required information and the issue can be re-opened.
