### ISSUE TITLE
stock - important

### ISSUE THREAD

**Issue by anytimewp** [vendure-ecommerce/vendure#1628]
as the sock left is not exposed we are not able to lock the control on the frontend.  Where there are 2 products i do not want the users to add 3 or 4 quantity and try to add to cart and see failure, i want to lock max quantity to 2 only when we have 2 product quantity in stock.

**Comment by martijnvdbrug** [comment]
I think this can be solved using a custom `StockDisplayStrategy`: https://www.vendure.io/docs/typescript-api/configuration/stock-display-strategy/

You could return the stockLevel as string, or implement different levels:
very_low_stock=Max 5 items salable
low_stock=Max 10 items salable
etc.

This would then be returned as field on productVariant through the shop api.

**Comment by michaelbromley** [comment]
That answer from Martin is the correct approach. You are even free to directly return the number of saleable stock if you like. The only reason we don't do this by default is that it then opens up your API to allow potentially malicious actors to read your entire inventory and know what stock you have of each item. Depending on your circumstances this may not be a concern to you.
