### ISSUE TITLE
Problem with Product Variants in multilingual setup

### ISSUE THREAD

**Issue by nem3sys** [vendure-ecommerce/vendure#1631]
**Describe the bug**
Product Variants do not appear after swapping the default language

**To Reproduce**
1. I have an eshop with two languages 'en' and 'el'
2. The default language is 'en'
3. I create a new Product and the (default) Product Variant is visible in both languages
4. I change the default language from 'en' to 'el'
5. The Product Variant in 'el' is not visible any more
6. I press 'Manage Variants' in 'el', I select the default Product Variant, fill the sku, price and stock, but when I press the 'Add' button nothing happens

**Expected behavior**
Product Variants should be visible in all languages despite of the selected default language

**Environment (please complete the following information):**
 - @vendure/core version: 1.6.2
 - Nodejs version: 16.15.0
 - Database: MariaDB

**Additional context**
![image](https://user-images.githubusercontent.com/5901752/174994368-7f6e304c-d1ac-411b-8fb2-56d5b290e6d0.png)

**Comment by ashitikov** [comment]
Yeah, I got the same problem. I would like to say that it happens only on custom channel, not the default one. If you change your channel to default, the problem should gone.

**Comment by nem3sys** [comment]
I've got only the default channel.

![image](https://user-images.githubusercontent.com/5901752/182360188-0b73d152-d317-45ac-9f42-edb79db0afc4.png)

**Comment by michaelbromley** [comment]
I can reproduce this with just the default channel. I'm fairly certain this has something to do with the ListQueryBuilder's handling of translations: https://github.com/vendure-ecommerce/vendure/blob/a3f101ad9b373f9688f8c2018a6752d232a3809e/packages/core/src/service/helpers/list-query-builder/list-query-builder.ts#L520
