### ISSUE TITLE
Collect Customer IP address and geo location

### ISSUE THREAD

**Issue by blackyzero** [vendure-ecommerce/vendure#1634]
Hello,

**Is your feature request related to a problem? Please describe.**
Yes, in case we need to blacklist or track source of customer ip.

**Describe the solution you'd like**
- Add support for collecting Customer IP and geo location on completed checkout.
- Show Customer IP or geo info on storefront page.
- If possible blocking access by using Customer source ip.

Thank you.

**Comment by tianyingchun** [comment]
this feature is  make sense, +1

**Comment by tianyingchun** [comment]
+1 , it should not be include vendure/core it should be `cloud networking firewall feature`

**Comment by michaelbromley** [comment]
@blackyzero No, Vendure by default does nothing with IP addresses.

**Comment by blackyzero** [comment]
Any chance to get IP to show on customer's order from dashboard and also included into order confirmation email ?
Something likes, "order has been made from this ip x.x.x.x"

I am sure this would be useful in some various cases.
Thank you.

**Comment by michaelbromley** [comment]
For now I would suggest this be implemented as a custom field on the Order entity. You can also use the [onTransitionEnd](https://www.vendure.io/docs/typescript-api/orders/custom-order-process/#ontransitionend) hook of a CustomOrderProcess to get the IP from the `ctx.req` object and save the IP to the Order's custom field.
