### ISSUE TITLE
Display customFields in Order detail view

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#164]
A recent update allows custom fields to be defined on the Order entity.

The Admin UI does not check for and display these custom fields in the Order detail view.

The same mechanism as is used on Products etc can be used to display Order custom fields.

**Comment by agustif** [comment]
Could this be used to have a custom reservationPrice? We want to sell travel related services and we usually charge only a percentage of the total upfront, either as fixed $ or % from total

Thanks!

**Comment by michaelbromley** [comment]
@agustif So e.g. Product A has a price of $100, but the customer only has to pay e.g. $20 upon checkout? 

I think there might be a few ways to implement this. Possibly the simplest would be to actually set the price of Product A to $20, and then set a customField on the ProductVariant for the display price ($100) which is what you then show in the storefront.
