### ISSUE TITLE
Admin UI Refresh

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#1645]
Refresh of the Admin UI.

* Update the look & feel with a more polished, modern style
* Address UX pain-points

Technically, it makes sense to try to stick as much as we can to the existing markup & classes, but see how far we can push the custom CSS & variables. This will minimize the breaking UI changes for those with existing ui extensions.

**Comment by vrosa** [comment]
@michaelbromley just to confirm, is the revamped UI still using Clarity as the underlying design system? I'm asking because my team has been extensively creating new custom views and components on top of the framework so I wanted to make sure we won't have to rebuild everything all over again 😅

**Comment by michaelbromley** [comment]
Released in v2.0!
