### ISSUE TITLE
Admin UI Alerts

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#1646]
A notification system for Administrators which allows messages to be delivered to admins & possibly actions to be taken.

Use case: When the search plugin is set to buffer updates, it will currently only show this in the product list view. There needs to be a global alert notification area (e.g. top right by user menu) where we can indicate there are notifications that need attention.

An alert is different from the current "toast" notifications in that they are not transient, and may also have actions attached to them. E.g. in the case of the buffered updates, the message would read "5 search index updates pending" and a button "run updates" that is accessible from any route in the UI app.

Additional requirements:

* Permissions-aware, so alerts may be restricted based on Role of logged in Administrator
* Can be defined by plugins, allowing custom alerts to be issued.
* Can trigger arbitrary actions when supplied with a call-to-action button

**Comment by duypv** [comment]
Hello, any new here?

@michaelbromley do you have plan to implement this feature?

**Comment by michaelbromley** [comment]
Hi,
The first version is now implemented in the v2 admin ui. It's not yet documented however, but you can see how it can be used here: https://github.com/vendure-ecommerce/vendure/blob/dfddf0fa01c7e8f1b4faa0879c7911d8b8766a98/packages/admin-ui/src/lib/core/src/core.module.ts#L124

**Comment by michaelbromley** [comment]
This is now documented: https://docs.vendure.io/guides/extending-the-admin-ui/alerts/
