### ISSUE TITLE
can't fetch order inside payment handler

### ISSUE THREAD

**Issue by anacchaves** [vendure-ecommerce/vendure#1654]
**Describe the bug**
I need to access my product name inside a custom payment handler. I tried accessing this information by looking inside the `order` argument that comes inside `createPayment` by default. However, when I do log `order.lines[i].productVariant.product` it comes back undefined - even though it's predicted to be there.

**To Reproduce**
1. Create a custom payment handler
2. Try to get product name from `order`

**Expected behavior**
Product should not be `undefined`

**Environment (please complete the following information):**
 - @vendure/core version: 1.5.0
 - Nodejs version 16
 - Database (mysql/postgres etc): pgsql

**Comment by michaelbromley** [comment]
Hi there,

You can solve this by:

1. injecting the [EntityHydrator](https://www.vendure.io/docs/typescript-api/data-access/entity-hydrator/) into your handler, using the dependency injection pattern with the `init()` function described [here](https://www.vendure.io/docs/typescript-api/configurable-operation-def/#dependency-injection).
2. Use the EntityHydrator to ensure the relations you need are loaded.

**Comment by anacchaves** [comment]
This worked perfectly. Thanks so much!
