### ISSUE TITLE
Not getting and URL in admin and shop APIs for assets preview

### ISSUE THREAD

**Issue by etienneroudeix** [vendure-ecommerce/vendure#1661]
**Describe the bug**
I just moved my vendure app to a https domain name.
The app is run on the server and proxified by Phusion Passenger.
When i query any product with an asset preview, the value is not an url.
Query :
```
{
    "operationName": "SearchProducts",
    "variables": {
        "input": {
...
        }
    },
    "query":"query SearchProducts($input: SearchInput!) {
  search(input: $input) {
    items {
...
      productAsset {
        id
        preview
        __typename
      }
...
"}
```

The response :

```
{
  "data": {
    "search": {

      "items": [
        {
          ...
          "productAsset": {
            "id": "1",
            "preview": "https, https://api.myapp.com/assets/preview/bd/0__preview.webp",

            "__typename": "SearchResultAsset"
          },
          ...
          "__typename": "SearchResult"
        }
...
```

Note that if I hit from **http** I got a _correct_ response being `"preview": "http://api.myapp.com/assets/preview/bd/0__preview.webp",`

Note that this is _not_ happening if I configure the NestJS to run on https locally (using mkcert)

I have no idea where the `https, ` prefix comes from. I first thought it was like a protocols array `["https", "https"]` being roughly cast but it would not have a space in between.

**To Reproduce**
Run the admin or shop api behind a Phusion Passenger proxy and use a https domain name.
Run any query (both shop or admin) calling an asset.

**Expected behavior**
The preview result should be an url

**Environment (please complete the following information):**
 - @vendure/core version: 1.6.3
 - Nodejs version: 14.18.3
 - Database (mysql/postgres etc): postgres 9.2.24

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. In general, the solution to such issues is to set the [assetUrlPrefix](https://www.vendure.io/docs/typescript-api/asset-server-plugin/asset-server-options/#asseturlprefix) option in you AssetServerPlugin init config. 

The `https, http` part is strange, but I'm guessing it is coming from these lines: https://github.com/vendure-ecommerce/vendure/blob/1640ea72bc3c8abf1f129d46ebac627c23d68d78/packages/asset-server-plugin/src/common.ts#L10-L11

**Comment by etienneroudeix** [comment]
Hi @michaelbromley thank you for your answer.
Indeed everything works fine with the [assetUrlPrefix](https://www.vendure.io/docs/typescript-api/asset-server-plugin/asset-server-options/#asseturlprefix).
Furthermore I investigated (thanks to your code snipper guess) and the `request.headers['x-forwarded-proto']` do contains `https, https` as a string.
I guess this is a misguided config of the proxy by my hoster.
Sorry I hardly thought it could be a bug.
Thanks a lot.
