### ISSUE TITLE
Adds an OrderItem to the Order awalys incrementing an existing one instead create new line

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#1670]
**Describe the bug**
when invoke mutation `addItemToOrder` it always incrementing an existing order line , always don't touch created new  orderline.

after investigation, i found vendure. 1.6.3 do some refactor for `order-modifer.getExistingOrderLine()`

```ts
private async customFieldsAreEqual(
        ctx: RequestContext,
        orderLine: OrderLine,
        inputCustomFields: { [key: string]: any } | null | undefined,
        existingCustomFields?: { [key: string]: any },
    ): Promise<boolean> {
        const customFieldDefs = this.configService.customFields.OrderLine;
        if (inputCustomFields == null && typeof existingCustomFields === 'object') {
            // A null value for an OrderLine customFields input is the equivalent
            // of every property of an existing customFields object being null
            // or equal to the defaultValue
            for (const def of customFieldDefs) {
                const key = def.name;
                const existingValue = existingCustomFields?.[key];
               // FXIME: why there need to double check `def.defaultValue`
                if (existingValue !== null && def.defaultValue && existingValue !== def.defaultValue) {
                    return false;
                }
            }
            return true;
        }

```

**To Reproduce**
1.  define custom fields in plugin.
```ts
export const orderLineCustomFields: CustomFieldConfig[] = [
  {
    type: 'text',
    name: 'lensConfigs',
    nullable: true,
    public: true,
  },
];
config.customFields.OrderLine.push(...orderLineCustomFields);

```
2. first, `addItemToOrder` it will create new Orderline , and via adjustOrderLine attached customized `JSON` data on the `lensConfigs`
```gql
mutation {
  addItemToOrder(productVariantId:1, quantity:1) {
    __typename
  }
}
```
3. second,  invoke `saveUserProcessConfigStep`, internally i update orderLine `customFields.lensConfigs={...}`
```gql
mutation {
  saveUserProcessConfigStep(input: {
    step: T0,
    orderLineId: 1,
    quantity: 1,
    lensOptionInputs:[],
    t0LensCtxInput: {
      productId: 1,
      productVariantId:1
      collectionId: 1
    }
  }) {
    ... on Order {
      id
    
    }
  }
}
```
4. Invoke `AddItemToOrder` again  it should add new orderline rather than incrementing an existing line quantity.
```gql
mutation {
  addItemToOrder(productVariantId:1, quantity:1) {
    __typename
  }
}
```
5. below code always return `true` cause of code `&& def.defaultValue`
```ts
  if (existingValue !== null && def.defaultValue && existingValue !== def.defaultValue) {
                    return false;
                }
```

BTW we can add addItemToOrder with customFields: {} to fix, but it should be consider an break change againts 1.6.2

**Expected behavior**
 it should add new orderline while invoke `addItemToOrder`

**Environment (please complete the following information):**
 - @vendure/core version: 1.6.3
 - Nodejs version 16
 - Database (mysql/postgres etc):mysql

**Additional context**
BTW we can add `addItemToOrder` with `customFields: {}` to fix, but it should be consider an break change againts 1.6.2

**Comment by michaelbromley** [comment]
Note: the change in v1.6.3 was a fix for https://github.com/vendure-ecommerce/vendure/issues/1612.
