### ISSUE TITLE
non-nullable custom field possibly set to null.

### ISSUE THREAD

**Issue by ondratuma** [vendure-ecommerce/vendure#1680]
When creating Product with customField relation, and setting the relationId to non-existent entity, the product still gets created.

I would like to ask about the non-transactional behavior for customFields.

When I specify the field non-nullable, I would expect it to be non-nullable also on the database level.
It is however not how it works. But I would assume that this consistency would be ensured on another level, then. 

I presonally think that the updates should not fail silently inside https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/service/helpers/custom-field-relation/custom-field-relation.service.ts

I would also like what is the reason behind not keeping the updates inside single transaction, as it would enable for rollbacks and ensuring consistency.

**Comment by ondratuma** [comment]
I am otherwise really happy with Vendure, and I would have no problem implementing the fixes once we discuss it.

**Comment by michaelbromley** [comment]
Hi!
Thanks for the report. I agree that the current behaviour is unexpected.

There are 2 options here I think:

1. Enforce the non-nullability at the DB level. This would involve defining the `nullable` option [here](https://github.com/vendure-ecommerce/vendure/blob/b8fdbd8b311c8b1d7c229863ed011b2cc653118f/packages/core/src/entity/register-custom-entity-fields.ts#L84). I think the problem with this approach is that it might cause issues with all the existing rows that have no relation defined yet. It could make the migration after defining such a custom field very difficult.
2. Enforce it in the [app logic](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/service/helpers/custom-field-relation/custom-field-relation.service.ts#L51). Right now, if no relation is found for the given ID, we just do nothing. The correct behaviour should be to check the custom field config and if non-nullable, we should throw here.

> I would also like what is the reason behind not keeping the updates inside single transaction, as it would enable for rollbacks and ensuring consistency.

The updates _should_ be inside a transaction already. This is done by passing the `ctx` to the DB calls. The `ctx` holds a reference to any ongoing transaction (typically kicked off via the `@Transaction()` decorator on the resolver), and puts all DB operations inside that transaction.

**Comment by ondratuma** [comment]
Thank you, I missed the transaction decorator. It makes much more sense now.

Approach nr. 1 would be welcome from the developer's point of view, as that is imho the expected behavior. 
But this breaks even the code, as of now, the relation fields are set after saving the entity itself, if I see correctly.

Approach nr. 2 seems as the best way to go, as it would allow for non-breaking behavior. It would ensure consistency for now, and would be much easier to implement. 

But I would keep option 1 open for the future. Given that it would require much bigger developer effort and breaking migration for existing users. 
It could later be introduced as optional, being enabled by default in the template for new installations, thus not forcing existing users to migrate, while when combined with approach 2, ensuring that new cases would not appear.
