### ISSUE TITLE
image-size 1.0.2 make nodejs 12 not work

### ISSUE THREAD

**Issue by roytan883** [vendure-ecommerce/vendure#1681]
**Describe the bug**
vendure says it run on nodejs 12, but which dep lib "image-size" new version 1.0.2 runs only on 14 and later.
```
yarn install
error image-size@1.0.2: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.22.6"
```

**Comment by roytan883** [comment]
"sharp" 0.29 also has install error on nodejs 12. 
config package.json with 
```
"resolutions": {
    "sharp": "0.30.7",
    "image-size": "1.0.1"
  },
```
can work on nodejs 12.

**Comment by michaelbromley** [comment]
OK, thanks for the report. Out of interest, are you forced to use v12 in some environment you are using? I ask because v12 is no longer supported by Node (maintenance support ended in April 2022), and probably I should update the docs to start with v14 which is now the LTS release.

**Comment by roytan883** [comment]
@michaelbromley My mistake, sharp is 0.29 OK, my libvips download url has problem. But "image-size" 1.0.2 vs 1.0.1 only change nodejs version. 
My old system based on nodejs 12, upgrade need lots of testing, so vendure runs on nodejs 12 is good for me. If force to nodejs 14, will be very hard integrate to my old system.

**Comment by michaelbromley** [comment]
Closing this as our minimum supported Node.js version is currently v18+
