### ISSUE TITLE
AdminUI failed to use , decimal separator in shipping price field

### ISSUE THREAD

**Issue by etienneroudeix** [vendure-ecommerce/vendure#1682]
**Describe the bug**
Cannot use the `,` comma separator in the shipping price field :
<img width="514" alt="Capture d’écran 2022-07-25 à 09 39 46" src="https://user-images.githubusercontent.com/2012682/180805566-0c0888f0-bb22-4d13-ba96-1c38ce37b725.png">
It throw an error on testing:
<img width="549" alt="Capture d’écran 2022-07-25 à 09 47 20" src="https://user-images.githubusercontent.com/2012682/180805486-904f9b64-72df-4b79-b2d0-a7365e56ce5c.png">

**To Reproduce**
1. Go to `/admin/settings/shipping-methods`
2. Configure a shipping method using `Default Flat-Rate Shipping Calculator`
3. Set the shipping price with a decimal using the `,` decimal separator (expected by the field). You also can use the field arrows.
5. click the Update button.
6. Refresh the page
7. Scroll down to the Tester
8. Click test, got an error

Note that if you use a `.` separotor it works fine.

**Environment (please complete the following information):**
 - @vendure/core version: 1.6.3
 - Nodejs version : 14.19.1
 - Database (mysql/postgres etc): postgres

**Additional context:**
Vendure admin language is english

The error response id actually :

```json
{
    "errors": [
        {
            "message": "Int cannot represent non-integer value: NaN",
            "locations": [
                {
                    "line": 6,
                    "column": 7
                }
            ],
            "path": [
                "testShippingMethod",
                "quote",
                "priceWithTax"
            ]
        }
    ],
    "data": {
        "testShippingMethod": {
            "eligible": true,
            "quote": null,
            "__typename": "TestShippingMethodResult"
        }
    }
}
```

**Comment by michaelbromley** [comment]
Hi,
What display language settings do you have to get the input to display with a comma? 
![image](https://user-images.githubusercontent.com/6275952/184666431-7823a1a2-585f-4c0c-91fc-c7613a4693cc.png)

I tried various combinations but cannot get it to display with a comma in the money input field, and if I use a comma, it is ignored by the input altogether.

**Comment by etienneroudeix** [comment]
Hello @michaelbromley ,
Admin is in English
<img width="312" alt="Capture d’écran 2022-08-15 à 21 42 41" src="https://user-images.githubusercontent.com/2012682/184787293-d5fa9406-0688-4ac2-8d14-861b8a72b518.png">
Website language is only "French"
<img width="537" alt="Capture d’écran 2022-08-15 à 21 42 31" src="https://user-images.githubusercontent.com/2012682/184787327-b33c1353-9508-44ed-a508-7ac236546a7a.png">
Currency is EURO.
<img width="137" alt="Capture d’écran 2022-08-15 à 21 43 58" src="https://user-images.githubusercontent.com/2012682/184787342-5346c459-9701-49da-adb5-f8582bd1334b.png">

**Comment by michaelbromley** [comment]
I finally managed to get the comma separator by changing my browser language to French!

But I don't think that's the issue. Can you help me test a hypothesis:

1. Note the order of arguments in the shipping calculator card: price, taxRate, includesTax
2. Remove that calculator with the "x remove" button.
3. Re-add that calculator. Note the order of arguments. Is it now: price, includesTax, taxRate?
4. If so, fill out some values and try the test again.

Does this fix it for you?
