### ISSUE TITLE
Allow order history item with specificed tag and allow filtered by these tag.

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#1698]
**Is your feature request related to a problem? Please describe.**

As you know vendure provider `order history` in admin-ui, these `order history entry` can be set as `private` or `public` to customer. but in some case, we need write some history visible for `administrator`, such `issue order`, `some other tag commnet`,  and then we need to filter all order items by `these tag` that is fine.

**Describe the solution you'd like**

white `history entry comment` allow us choose `tag`, we can choose `tag` to search all order items.

**Describe alternatives you've considered**

**Additional context**
vendure @1.6.4

**Comment by michaelbromley** [comment]
Hi,
I don't have a clear concept of the feature you are asking for here. Do you want to be able to add tags to an order?

**Comment by tianyingchun** [comment]
yes, i wan to add some cusomized `tag` related specificed `order`
e.g.  `glass lens issue` on `order(id:1)`, and then we can search orders via tag `glass lens issue`

**Comment by tianyingchun** [comment]
yes, i wan to add some cusomized `tag` related specificed `order`
e.g.  `glass lens issue` on `order(id:1)`, and then we can search orders via tag `glass lens issue`

**Comment by michaelbromley** [comment]
OK. This sounds like a slightly different feature from the custom history entry.

**Comment by michaelbromley** [comment]
I'm going to close this for now as we don't have plans to add this to core currently, and it could be implemented with custom extensions.
