### ISSUE TITLE
Guest can set customer info and get orders

### ISSUE THREAD

**Issue by roytan883** [vendure-ecommerce/vendure#1699]
**Is your feature request related to a problem? Please describe.**
After a guest create order, and called `setCustomerForOrder` to that order. 
I saw customer info in the order detail. But call `activeCustomer` it return null.
Then i try to complete that order, it works good. But still  `activeCustomer` return null.
After the guest complete more order, the `activeCustomer` always return null.
The only way I found can get order list is activeCustomer->orders.
Is that meaning guest can not get order list ???

**Describe the solution you'd like**
1. Guest can get order list.
2. How to set guest's customer info ? The only way i found is `setCustomerForOrder` in order flow. But it `activeCustomer` return null.
3. How to make a guest customer become a registered customer? After that, can he still seeing those orders made by the guest time?

**Comment by michaelbromley** [comment]
Right now this is intended behaviour.

`activeCustomer` only returns data if the customer is logged in as a registered user.

There is a security reason for this: 

1. Let's say Person A places a guest order using the email address `persona@test.com`
2. Evil Hacker comes along and creates an Order and calls `setCustomerForOrder` with Person A's email address.
3. If we were to expose past orders at this point, Evil Hacker now has access to Person A's purchase and address details etc.

You can make a guest customer into a registered customer by just registering an account with the email address that was used for the guest orders. After successful email verification, the now-registered Customer will be able to see the order history including all orders that were placed as a guest prior to registration.

**Comment by roytan883** [comment]
Thanks for explain. 

How about third party login, like Google authentication? We already have our old user system and implement our auth config to `shopAuthenticationStrategy`. Can`externalAuthenticationService.createCustomerAndUser` `verified: true`  make a guest become registered, and saw old order list with same email address?

**Comment by michaelbromley** [comment]
Yes, this should be possible.
