### ISSUE TITLE
price 0 ?

### ISSUE THREAD

**Issue by roytan883** [vendure-ecommerce/vendure#1707]
**Describe the bug**
productVariant price 0

**To Reproduce**
I create my own RtsCart plugin which allow user add items to cart but not order. Then pick a few item to real order. Everything works good, and the `productVariantId` related `productVariant` most props is OK, only `price 0`, and `priceWithTax 0`
```
//gql
mutation addRtsCart($input: AddRtsCartInput!){
  addRtsCart(input: $input){
    id productVariantId  
    customer {
      rtsCartList (options: {take: 100}) {
        totalItems
        items {
          id productVariantId
          productVariant {
            id name price priceWithTax sku 
            assets {
              source preview
            }
          }
        }
      }
    }
  }
}

//plugin code
@ResolveField()
  async productVariant(@Parent() record: RtsCart, @Ctx() ctx: RequestContext) {
    let productVariant: ProductVariant | null = record.productVariant;
    if (!productVariant) {
      const recordWithProductVariant = await this.connection
        .getRepository(ctx, RtsCart)
        .findOne(record.id, {
          relations: ['productVariant'],
        });
      if (recordWithProductVariant) {
        productVariant = recordWithProductVariant.productVariant;
      }
    }
    if (productVariant) {
      return translateDeep(productVariant, ctx.languageCode);
    }
  }
```

**Comment by michaelbromley** [comment]
Hi,

You need to use the `ProductPriceApplicator` service. I just added an example which will be in the docs soon: https://github.com/vendure-ecommerce/vendure/commit/834c05c514ad2abfa94f56afa0560c3e205ea2ca#diff-4950820cafb41336053ef88b3c14bac5e3d049af523bbc8a1c18606ccb3ffcb2R16-R39

**Comment by roytan883** [comment]
OK, thanks. I will try it

**Comment by michaelbromley** [comment]
Ok, try joining the ProductVariant's `taxCategory` relation in your `findOne()` call: 

```ts
let productVariant = await this.connection
        .getRepository(ctx, ProductVariant)
        .findOne(record.productVariantId, { relations: ['taxCategory'] });
```

Let me know if that fixes it and I'll update the docs to include that detail.

**Comment by roytan883** [comment]
OK, it works now.

**Comment by roytan883** [comment]
@michaelbromley  after add `{ relations: ['taxCategory'] }`, it can get price now.
