### ISSUE TITLE
Shop API for Customer apply Refunds and Cancellation

### ISSUE THREAD

**Issue by roytan883** [vendure-ecommerce/vendure#1715]
**Is your feature request related to a problem? Please describe.**
I find it here: 
https://www.vendure.io/docs/user-guide/orders/#refunds
But, only in admin-ui. 
And I checked the shop-api, there no api for `Customer apply Refunds and Cancellation`
It is strange that admin-ui can do refund and reason by `customer required`, but there is no api for customer apply refund .....

**Describe the solution you'd like**
Provide Shop-APi for `Customer apply Refunds and Cancellation`.

**Comment by dlhck** [comment]
A refund always implies that money flows back from the company to the customer. Why should a customer trigger that itself? Customers usually create returns which then might (not always) trigger a refund. Anyway, that process can vary a lot. I will close this issue, but you can provide more info on your use case. I might open the issue again!
