### ISSUE TITLE
Admin ui - trix editor not working on chrome

### ISSUE THREAD

**Issue by forafish** [vendure-ecommerce/vendure#172]
When run the admin demo with chrome (same error on local and demo.vendure.io/admin), Trix editor component not properly initialized, maybe the problem of order of initialization of angular and trix webcomponent

```code
Uncaught TypeError: Cannot assign to read only property 'connectedCallback' of object '[object HTMLElement]'
    at wrapCustomElementCallback (polydev/src/document-context/measure-custom-elements.js:94)
    at CustomElementRegistry.wrappedDefineElement [as __zone_symbol__define] (polydev/src/document-context/measure-custom-elements.js:99)
    at CustomElementRegistry.target.<computed> [as define] (zone.js:2237)
    at trix-core.js:6
    at Object.e.registerElement (trix-core.js:6)
    at trix-core.js:6
    at trix-core.js:6
    at trix-core.js:12
    at trix-core.js:12
```

Environment: 
Google Chrome for Mac
Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. I am working on a Windows machine and cannot reproduce the error here on the demo at https://demo.vendure.io (currently Vendure v0.3.0).

Can you check in any other browsers and see if it is also an issue there? I have never encountered this error before.

**Comment by forafish** [comment]
Found the cause of the issue by disable all extensions of chrome, it caused by a chrome extension 'Polymer DevTools Extension
', which make the CustomerElement connectedCallback readonly. Remove the extension then it works perfect. close it.
