### ISSUE TITLE
Unique slug per channel instead of globally unique

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#1720]
**Is your feature request related to a problem? Please describe.**
When channel-A defined the slug for a collection or product as `clothing`, channel-B cannot use this slug anymore.

**Describe the solution you'd like**
I would like slugs to be unique per channel. I cannot think of a use case where slugs should be globally unique.

**Describe alternatives you've considered**
Just using the Vendure generated slug `clothing-2`

**Additional context**
This goes for both products and collections.

**Comment by michaelbromley** [comment]
This should be fairly straightforward - it should just involve modifying the [SlugValidator](https://github.com/vendure-ecommerce/vendure/blob/834c05c514ad2abfa94f56afa0560c3e205ea2ca/packages/core/src/service/helpers/slug-validator/slug-validator.ts#L51) class. An e2e test should go along with this to verify.

**Comment by jenia0jenia** [comment]
Hello!
There is one more situation.
What if I want to use SlugValidator for my custom entity that doesn't use channels?
