### ISSUE TITLE
Regression in 1.6.5 for querying customfields on product (maybe others).

### ISSUE THREAD

**Issue by jacobfrantz1** [vendure-ecommerce/vendure#1723]
**Describe the bug**
Vendure logs error: "product__customfields" alias was not found. Maybe you forgot to join it?

**To Reproduce**
Create a list relation customfield on product
Use the shop product query to query for a product and its custom fields

**Environment (please complete the following information):**
 - @vendure/core version: 1.6.5
 - Nodejs version: 16.16.0
 - Database (mysql/postgres etc): postgresql 14

**Additional context**
Works in Vendure 1.6.4

**Comment by michaelbromley** [comment]
Attempted to reproduce on master branch with the following config:

```ts
customFields: {
  Product: [{
    name: 'featuredFacet',
    type: 'relation',
    entity: Facet,
  }],
},
```

sent this query:
```gql
{
  product(slug: "laptop") {
    id
    name
    customFields {
      featuredFacet {
        id
        name
      }
    }
  }
}
```

and got the following response:

```json
{
  "data": {
    "product": {
      "id": "1",
      "name": "Läptop",
      "customFields": {
        "featuredFacet": {
          "id": "1",
          "name": "category"
        }
      }
    }
  }
}
```

Can you provide exact steps so I can reproduce this from a clean install?

**Comment by michaelbromley** [comment]
Attempted to reproduce on master branch with the following config:

```ts
customFields: {
  Product: [{
    name: 'featuredFacet',
    type: 'relation',
    entity: Facet,
    list: true,
  }],
},
```

sent this query:
```gql
{
  product(slug: "laptop") {
    id
    name
    customFields {
      featuredFacet {
        id
        name
      }
    }
  }
}
```

and got the following response:

```json
{
  "data": {
    "product": {
      "id": "1",
      "name": "Laptop",
      "customFields": {
        "featuredFacet": [{
          "id": "1",
          "name": "category"
        }]
      }
    }
  }
}
```

Can you provide exact steps so I can reproduce this from a clean install?

**Comment by jacobfrantz1** [comment]
My bad, it seems I misunderstood the issue.
It looks like nested relations on the entities on the customfields are causing the problems.
A minimal example would be this config
```ts
customFields: {
  Product: [{ name: 'optionGroup', entity: ProductOptionGroup, type: 'relation' }],
},
```
and this query
```gql
query product {
  product(slug: "laptop") {
    id
    name
    customFields {
      optionGroup {
        options {
          id
        }
      }
    }
  }
}
```
returning the error
```
"message": "\"product__customFields\" alias was not found. Maybe you forgot to join it?"
```
Omitting 'options' on the query avoids the error
You don't need to have any data on the customfields for the error to occur
Produced on master branch as of 8/25/22

**Comment by michaelbromley** [comment]
Ah ok thanks, I think this is the same issue as

- https://github.com/vendure-ecommerce/vendure/issues/1664
