### ISSUE TITLE
Import format for Collections

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#173]
**Is your feature request related to a problem? Please describe.**
There currently exists an (undocumented) CSV-based import format for Products & ProductVariants. Also a very basic JSON-based format exists for creating Collections. However, this format is very limited. Missing features are:

* Set assets for Collection
* Set visibility
* Set description
* Set multiple filters
* Set hierarchy (specify parent)

**Describe the solution you'd like**
A new format, similar to the product CSV format might make sense. The trickiest part will be to come up with a way to specify filters in such a format. However, this should be very much doable since the CollectionFilters are already string-serializable.

**Comment by itsgauravjain22** [comment]
A csv data import is very much needed in real world deployment. I have 1900 sku as google sheets data. The data is formatted as woocommerce product import csv schema [here](https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema). It might help in creating a robust product import functionality.

**Comment by michaelbromley** [comment]
There actually is a CSV import format - it's already used by the e2e tests but it's just not documented yet. I'll have to get around to that soon. You can learn a bit about it from [these testing docs](https://www.vendure.io/docs/developer-guide/testing/#initialize-the-server). FYI I am using it myself to import ~10k SKUs into a Vendure project.
