### ISSUE TITLE
Password change does not follow password validation strategy

### ISSUE THREAD

**Issue by Conor-Burns** [vendure-ecommerce/vendure#1734]
**Describe the bug**
when requesting a password change, the password isn’t verified against the default validation strategy

**To Reproduce**
1. Set up a default validation strategy
2. request a password change
3. type in new password which is miss-matching the validation strategy
4. submit and log in with weak password

**Expected behavior**
Password change should also use the default validation strategy 

**Environment (please complete the following information):**
 - @vendure/core version: 1.6.5
 - Nodejs version 16-lts
 - Database (mysql/postgres etc): postgres

**Additional context**

**Comment by michaelbromley** [comment]
The fix should be pretty simple: in the [UserService.updatePassword](https://github.com/vendure-ecommerce/vendure/blob/1640ea72bc3c8abf1f129d46ebac627c23d68d78/packages/core/src/service/services/user.service.ts#L365) method we need to add this: https://github.com/vendure-ecommerce/vendure/blob/1640ea72bc3c8abf1f129d46ebac627c23d68d78/packages/core/src/service/services/user.service.ts#L254-L257

and this will also require adding `PasswordValidationError` to the return type union.

Would you like to PR this?
