### ISSUE TITLE
Refunds total for an order modified multiple times

### ISSUE THREAD

**Issue by moamen-nour** [vendure-ecommerce/vendure#1753]
**Describe the bug**
When modifying an order multiple times by decreasing quantity and adding promos for ex. If the refunds created in the process all attach to the same payment and the payment amount is not enough the remainder amount of the refund doesn't get attached to the next available payment.

**To Reproduce**
Steps to reproduce the behavior on demo ui admin/shop:
1. Place an order with one product of price x (In shop ui)
2. Modify order to increment quantity to 2 -> This creates a new settled payment with price x
3. Modify order by adding a promo code (make it discount an amount less than x) and use the payment created in step 2 for the refund. Then settle the refund.
4. Modify order by decrementing the quantity back to 1 and use the payment created in step 2 as refund

**Expected behavior**
2 refunds should be created
One = payment created in step 2 amount - discount amount created in step 3 by promo (the promo refund). 
Another = the remainder and attached to the next available payment.

**Current behavior**
The remainder refund is not created.

**Environment:**
 - @vendure/core version: 1.5.1
 - Nodejs version: v16.16.0
 - Database (mysql/postgres etc): postgres
 
**Additional Context:**
I think the reason is due to these line in `createRefund` 
```
 const existingNonFailedRefunds =
            orderWithRefunds.payments
                ?.reduce((refunds, p) => [...refunds, ...p.refunds], [] as Refund[])
                .filter(refund => refund.state !== 'Failed') ?? [];
```

```
refundOutstanding = refundTotal - summate(existingNonFailedRefunds, 'total');
```
This takes into account the previous refunds created in previous order modifications as refunds that occurred for the current modification.

**Comment by michaelbromley** [comment]
Thanks for the reports on this and #1760! I'll be issuing a patch soon containing fixes for these 👍
