### ISSUE TITLE
Please add register date for each customer item in admin-ui

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#1756]
**Is your feature request related to a problem? Please describe.**

strongly recommend add "register date" for each customer item in admin-ui

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/2833251/187340276-1efb852f-4585-4d4e-967c-d5ce2e150f47.png">

**Describe the solution you'd like**
Please see above picture shown, add register date for each customer for the `listview`
**Describe alternatives you've considered**

**Additional context**

**Comment by michaelbromley** [comment]
In latest versions it's possible to show the createdAt date in the custom list.
