### ISSUE TITLE
Changing entityIdStrategy to UuidIdStrategy does not work

### ISSUE THREAD

**Issue by czelusniakdawid** [vendure-ecommerce/vendure#176]
**Describe the bug**
Changing entityIdStrategy to `UuidIdStrategy` does not work. 

**To Reproduce**
1. Create new PostgreSQL database.
2. Add `synchronize: true` to your db settings:
```
    dbConnectionOptions: {
        type: 'postgres',
        synchronize: true,
        logging: false,
        database: 'vendure',
        host: '127.0.0.1',
        port: 5432,
        username: 'postgres',
        password: 'postgres',
    },
    entityIdStrategy: new UuidIdStrategy(),
```
3. Run `index.ts` file with `ts-node` with several `console.log` statements:
```
$ ./node_modules/ts-node/dist/bin.js --version
v8.4.1
$ ./node_modules/ts-node/dist/bin.js index.ts
increment
bootstrap
preBootstrapConfig
setConfig
uuid
uuid
setConfig
uuid
info 10/4/19, 12:51 AM - [Vendure Server] Bootstrapping Vendure Server (pid: 82903)...
info 10/4/19, 12:51 AM - [NestApplication] Nest application successfully started
info 10/4/19, 12:51 AM - [Vendure Server] =================================================
info 10/4/19, 12:51 AM - [Vendure Server] Vendure server (v0.3.3) now running on port 3000
```
4. Inspect generated db tables:
```
                                           Table "public.product"
     Column      |            Type             | Collation | Nullable |               Default
-----------------+-----------------------------+-----------+----------+-------------------------------------
 id              | integer                     |           | not null | nextval('product_id_seq'::regclass)
 createdAt       | timestamp without time zone |           | not null | now()
 updatedAt       | timestamp without time zone |           | not null | now()
 deletedAt       | timestamp without time zone |           |          |
 enabled         | boolean                     |           | not null | true
 featuredAssetId | integer                     |           |          |
```

**Expected behavior**
Changing entityIdStrategy to `UuidIdStrategy` should result in `uuid` type of id column of all tables which entities inherit from `VendureEntity`.

**Environment (please complete the following information):**
 - @vendure/core version:
0.3.3
 - Nodejs version
v10.16.3
 - Database (mysql/postgres etc):
PostgreSQL 11

**Comment by michaelbromley** [comment]
This is because with the current implementation, the ID metadata that TypeORM uses is set as soon as the file containing the entity is evaluated. Up until now I have attempted to defer evaluation (i.e. importing) of the entity files until after the config has been set. 

This is an error-prone approach, as evidenced by this issue! I am currently re-thinking how this can work so that no thought needs to be given to order of evaluation issues.
