### ISSUE TITLE
UI : list of products : some products do not display preview of the asset

### ISSUE THREAD

**Issue by christopheblin** [vendure-ecommerce/vendure#1761]
**Describe the bug**
In the list of products, some products have a missing image when "Group by product" is checked

There is a thread in slack with JSON from the server and screenshots and a video : https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1661865588750149

The video is the best to "explain" what is going on

**To Reproduce**
There is no clear way to reproduce the bug, it looks like a "random" bug in the UI with angular

I did try to repro by creating new products (in new channels), updating products, removing assets, etc... and the bug does not occur

The only thing is that when the bug happens on a product, it constantly happens (i.e no matter the search term or facets that are used or the position of the product in the list etc...)

Another common point between "faulty" products is that some variants of the product have the same asset than the product itself (but some variants do not have assets and so should use the product asset)

> note : I do not know why my users did that ...

**Expected behavior**
Display the images

**Environment (please complete the following information):**
 - @vendure/core version: 1.5.1

**Comment by christopheblin** [comment]
Explanation of the bug

The server sends this JSON : 

```
{"data":{"search":{"totalItems":2,"items":[{"enabled":true,"productId":"6858e253-f703-4342-bab1-81416b303e82","productName":"Abonnement mensuel 26-64 ans","productAsset":{"id":"23d28518-02d7-4f9d-94ef-287880206977","preview":"https://vendure.svc/assets/preview/cc/26-64-ans-mensuel__preview.png","focalPoint":null,"__typename":"SearchResultAsset"},"productVariantId":"013021d0-0199-464d-8b61-4b1052d92d51","productVariantName":"Abonnement mensuel 26-64 ans août","productVariantAsset":{"id":"23d28518-02d7-4f9d-94ef-287880206977","preview":"","focalPoint":null,"__typename":"SearchResultAsset"},"sku":"solea-abonnement-mensuel-aout-2022","channelIds":["0f8166af-eac2-49a3-9d8b-6c253ae93fb4","e381816a-03f9-4f51-a7d9-c55877752529","a6491a50-d0cb-41c8-a767-15054df8614d","0f8166af-eac2-49a3-9d8b-6c253ae93fb4","e381816a-03f9-4f51-a7d9-c55877752529","a6491a50-d0cb-41c8-a767-15054df8614d","0f8166af-eac2-49a3-9d8b-6c253ae93fb4","a6491a50-d0cb-41c8-a767-15054df8614d","e381816a-03f9-4f51-a7d9-c55877752529","0f8166af-eac2-49a3-9d8b-6c253ae93fb4","e381816a-03f9-4f51-a7d9-c55877752529","a6491a50-d0cb-41c8-a767-15054df8614d","0f8166af-eac2-49a3-9d8b-6c253ae93fb4","a6491a50-d0cb-41c8-a767-15054df8614d","e381816a-03f9-4f51-a7d9-c55877752529","0f8166af-eac2-49a3-9d8b-6c253ae93fb4","a6491a50-d0cb-41c8-a767-15054df8614d","e381816a-03f9-4f51-a7d9-c55877752529","0f8166af-eac2-49a3-9d8b-6c253ae93fb4","e381816a-03f9-4f51-a7d9-c55877752529","a6491a50-d0cb-41c8-a767-15054df8614d","0f8166af-eac2-49a3-9d8b-6c253ae93fb4","a6491a50-d0cb-41c8-a767-15054df8614d","e381816a-03f9-4f51-a7d9-c55877752529","0f8166af-eac2-49a3-9d8b-6c253ae93fb4","a6491a50-d0cb-41c8-a767-15054df8614d","e381816a-03f9-4f51-a7d9-c55877752529","0f8166af-eac2-49a3-9d8b-6c253ae93fb4","e381816a-03f9-4f51-a7d9-c55877752529","a6491a50-d0cb-41c8-a767-15054df8614d","0f8166af-eac2-49a3-9d8b-6c253ae93fb4","e381816a-03f9-4f51-a7d9-c55877752529","a6491a50-d0cb-41c8-a767-15054df8614d","0f8166af-eac2-49a3-9d8b-6c253ae93fb4","a6491a50-d0cb-41c8-a767-15054df8614d","e381816a-03f9-4f51-a7d9-c55877752529"],"__typename":"SearchResult"},{"enabled":true,"productId":"ddbfd95a-f950-42e2-bd1b-ece30df90717","productName":"Abonnement annuel 26-64 ans","productAsset":{"id":"9072e406-cf95-4621-9f07-d1a298b5e1fa","preview":"https://vendure.svc/assets/preview/9e/26-64-ans-annuel__preview.png","focalPoint":null,"__typename":"SearchResultAsset"},"productVariantId":"261e68c8-06b4-4815-a32e-390b01188f73","productVariantName":"Abonnement annuel 26-64 ans","productVariantAsset":{"id":"9072e406-cf95-4621-9f07-d1a298b5e1fa","preview":"https://vendure.svc/assets/preview/9e/26-64-ans-annuel__preview.png","focalPoint":null,"__typename":"SearchResultAsset"},"sku":"solea-abonnement-annuel","channelIds":["0f8166af-eac2-49a3-9d8b-6c253ae93fb4","a6491a50-d0cb-41c8-a767-15054df8614d","e381816a-03f9-4f51-a7d9-c55877752529"],"__typename":"SearchResult"}],"facetValues":[{"count":2,"facetValue":{"id":"fe0450fe-f30b-40d3-acaa-bf4842c0c082","createdAt":"2022-08-29T11:34:56.255Z","updatedAt":"2022-08-29T11:34:56.255Z","name":"Abonnements","facet":{"id":"26daf812-a7e6-43d3-b611-f7d39c285860","createdAt":"2022-08-29T11:34:56.255Z","updatedAt":"2022-08-29T11:34:56.255Z","name":"Voyage","__typename":"Facet"},"__typename":"FacetValue"},"__typename":"FacetValueResult"}],"__typename":"SearchResponse"}}}
```

As you can see, for the first item : 
* productAsset has id = 23d28...6977 and preview = https://blabla
* productVariantAsset has the same id = 23d28...6977 and preview is empty string

Because admin-ui is using apollo client, it's using a cache based on the ID fields, so it's using Asset.id

Here, it seems that, in memory, the asset with the id 23d28...6977 has an empty preview (so the cache picked the productVariantAsset and not productAsset) and this is why in the DOM we can see that `img src="?preview=tiny"`

The "fix" would be that the server should correctly fill the preview field

As a matter of completion, the DB seems ok for this variant :
![Capture d’écran 2022-08-31 à 08 42 44](https://user-images.githubusercontent.com/11044877/187620147-bf1c6c62-bb07-491c-becc-1cb723fb2289.png)

**Comment by michaelbromley** [comment]
This issue relates to a version of Vendure that is no longer supported. If the issue persists in the latest version, please open a new issue.
