### ISSUE TITLE
Expose all Nodemailer options

### ISSUE THREAD

**Issue by hendrik-advantitge** [vendure-ecommerce/vendure#1777]
**Is your feature request related to a problem? Please describe.**
We would like to use a DKIM signature on outgoing mails sent using the email plugin. However, not alle settings from nodemailer are exposed in the email plugin typings. 

**Describe the solution you'd like**
All nodemailer options should be exposed instead of a subset.

**Describe alternatives you've considered**
We are currently using a patch to achieve this.

**Comment by michaelbromley** [comment]
This makes sense as a feature. Would you be interested in contributing a PR? If so, make it against the `minor` branch and it can go in v1.8.

**Comment by hendrik-advantitge** [comment]
I'll look into it!
