### ISSUE TITLE
Expose httpAdapter options

### ISSUE THREAD

**Issue by hendrik-advantitge** [vendure-ecommerce/vendure#1779]
**Is your feature request related to a problem? Please describe.**
We would like to configure Sentry as an application monitoring tool in Vendure. In an Express environment, it should be configured as middleware using
```
const app = express()
app.use(Sentry.Handlers.requestHandler())
app.use(Sentry.Handlers.tracingHandler())
```
In Vendure we currently have no access to this object.

**Describe the solution you'd like**
We would like to define an httpAdapter in the config settings for both the server and the worker.
For example:
```
-    const { hostname, port, cors, middleware } = config.apiOptions;
+    const { hostname, port, cors, middleware, serverHttpAdapter } = config.apiOptions;
     default_logger_1.DefaultLogger.hideNestBoostrapLogs();
-    const app = await core_1.NestFactory.create(appModule.AppModule, {
+    const app = await core_1.NestFactory.create(appModule.AppModule, serverHttpAdapter, {
         cors,
         logger: new vendure_logger_1.Logger(),
     });
```

**Describe alternatives you've considered**
Currently we do this using a patch on Vendure core

**Comment by hendrik-advantitge** [comment]
Hi Michael, I think that would work but then you are not able to put the Sentry logic inside a plugin? Maybe I'm missing something obvious.

**Comment by michaelbromley** [comment]
For a plugin I think you could inject [HttpAdapterHost](https://docs.nestjs.com/faq/http-adapter#in-context-strategy) and access the underlying express app that way - not tried this but if so, I'd say this issue should be to add some documentation about that.

**Comment by hendrik-advantitge** [comment]
That seems to work. We can inject `HttpAdapterHost` in the plugin and initialise Sentry `OnApplicationBootstrap`. The Sentry documentation tells us Sentry should be the first middleware, I'm not sure that is the case when we add it `OnApplicationBootstrap`. For now it does not seem to cause any issues
