### ISSUE TITLE
Export prorate function

### ISSUE THREAD

**Issue by hendrik-advantitge** [vendure-ecommerce/vendure#1782]
**Is your feature request related to a problem? Please describe.**
In our custom promotion actions, we would like to use the `prorate` function from Vendure. But it is not exported.

**Describe the solution you'd like**
Export the `prorate` function

**Describe alternatives you've considered**
We currently use a patch, but could also write our own `prorate` function. Both solutions are not desired.

**Comment by michaelbromley** [comment]
This is a matter of adding it to the `/service/index.ts` barrel file:
```
export * from './helpers/order-calculator/prorate';
```

PR welcome :)
