### ISSUE TITLE
Feat: Assign products to channels from a non-default channel

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#1784]
**Is your feature request related to a problem? Please describe.**
It would be great, if non-superadmins could assign products to other channels they have access to. 

**Describe the solution you'd like**
I am administrator for channel-A and channel-B (none are the default channel). I would like to assign some of my products from channel-A to channel-B, because I have admin access to both channels.

**Describe alternatives you've considered**
None yet. Custom admin UI buttons via plugin?

**Additional context**
I would like to see this channel field in non-default channels. In case of a non-superadmin it would only show the channels the logged in administrator has access to:

![image](https://user-images.githubusercontent.com/6604455/190162383-6176c7f8-d4ad-4333-93f3-9046962f4084.png)
When the logged in admin only has access to 1 channel, we can still hide the channel field.

Seems fairly straight forward, but maybe I am missing something?

**Comment by martijnvdbrug** [comment]
Update:

It does seem to work when we remove `*vdrIfDefaultChannelActive` from [this line](https://github.com/vendure-ecommerce/vendure/blob/a641bebb91d0b79c8083059ca56009cd047b7a67/packages/admin-ui/src/lib/catalog/src/components/product-detail/product-detail.component.html#L63) with some side-effects:
The test-administrator can assign products to other channels it has access to, but the product detail page will still only show the current channel, while it is actually assigned to the new channel:
![image](https://user-images.githubusercontent.com/6604455/190180778-bda35a36-7a83-47c5-80ee-e6fc63754946.png)
When you switch channels while being on the detail page, the same thing happens: still only shows the current channel in the channel field.

Another 'side effect': The user needs `Read channel` permission, which results in the user being able to see other channels he doesn't have access to.

**Comment by dlhck** [comment]
@martijnvdbrug any update on this one?

**Comment by martijnvdbrug** [comment]
Nope sorry, I haven't had time to continue on this. Other stuff has priority now.. Sorry for claiming the task but not finishing it!
