### ISSUE TITLE
[solved] ctx.session is undefined on first call to custom resolver

### ISSUE THREAD

**Issue by yasserlens** [vendure-ecommerce/vendure#1788]
I have a resolver that does the following:
- It receives metadata about an order with custom parameters, to be stored in a Custom entity
- It creates the Custom Entity, gets the ID of it
- Then it runs addItemToOrder(..., customEntityId: ID), and provides the ID of the newly created entity

I need to pass the ctx object to the addItemToOrder() call, which also expects a session to be defined. If no session is available, an exception is thrown. 

**Solution**
As of version 1.7.x of Vendure, Adding @Allow(Permission.Owner) to the resolver will run through AuthGuard which would created a new anonymous session and attach it to the context.

** What to do about it **
Please document that somewhere under resolvers (e.g. [here](https://www.vendure.io/docs/plugins/plugin-examples/extending-graphql-api/#override-built-in-resolvers)) - would be great to mention it in the CustomEntity example as well.

**Comment by michaelbromley** [comment]
Added some docs on this.
