### ISSUE TITLE
Make Mollie payment method selectable from storefront

### ISSUE THREAD

**Issue by koljam** [vendure-ecommerce/vendure#1809]
**Is your feature request related to a problem? Please describe.**
Most users are familiar with selecting the payment method on the stores page and then getting redirected to the payment provider. Right now this is not possible with the Mollie plugin, since we always get redirected to the Mollie method-selector, resulting in a slightly confusing checkout flow (Clicking "Buy now" before selecting payment method, or clicking "Buy now" on mollie.com which _may_ both violate german law).
There is a way to embed the method selection in the storefront described [in the Mollie Docs](https://docs.mollie.com/payments/build-your-own-checkout)

**Describe the solution you'd like**
Things that are needed:

1. A new query for getting the available mollie payment methods. [Mollie API Reference](https://docs.mollie.com/reference/v2/methods-api/list-methods)
2. Another CreateMolliePaymentIntent input for setting the mollie method. The method can be set [here](https://github.com/vendure-ecommerce/vendure/blob/master/packages/payments-plugin/src/mollie/mollie.service.ts#L82).
3. Error handling

**Describe alternatives you've considered**
Only hardcoded, hacky experiments I would rather not share.

**Additional context**
I would be willing to pay for the development of this feature, since I really need this for the optimal checkout flow. I would try it myself but I am not that good with typescript and the Vendure plugin architecture yet.
That being said: I really love Vendure and I am looking forward to the time I finish my new shop and I can swich from WooCommerce to Vendure!

**Comment by michaelbromley** [comment]
Hi @koljam,

Thanks for the report. I'm pinging @martijnvdbrug here as he wrote the current Mollie integration so I think he might have a better appreciation of the payment flow you're talking about and how feasible it would be to support that in our plugin.

Any feedback on this Martijn?

**Comment by martijnvdbrug** [comment]
Hi @koljam,

This seems feasable. From what I can see now we need to implement the following:
* A Graphql query to retrieve the PaymentMethods from the connected Mollie account
* Expand the existing `createMolliePaymentIntent()` mutation to accept a mollie-payment-method
From what I can see from the Mollie docs, we can just pass the paymentMethod to `payments.create` and Mollie does the rest.

I should be able to get this implemented somewhere in the coming 2 weeks. If you need faster ultra priority service, reach out to me on martijn@pinelab.studio or via the Vendure slack.

**Comment by koljam** [comment]
Thank you both for the rapid response! The coming weeks will totally work for me. Let me know if you need anything!

**Comment by martijnvdbrug** [comment]
@michaelbromley can you assign it to me?

**Comment by koljam** [comment]
Thanks a lot, it works like a charm!

**Comment by michaelbromley** [comment]
@koljam good to hear! And thank you for your recent sponsorship too 🙏
