### ISSUE TITLE
Manage Variants - problem when adding more than one option

### ISSUE THREAD

**Issue by nemo-js** [vendure-ecommerce/vendure#1812]
**Describe the bug**
Product -> Manage Variants -> Add more than one option -> 
option values are added to the first option, no matter where I type them

**To Reproduce**
1. Go to Product Manage Variants
2. Click on 'Add Option' twice
3. Add a value to the first option
4. Add a value to the second option
5. Second value is added to the first option instead of the first

**Expected behavior**
Value should be added to the second option

**Environment (please complete the following information):**
 - @vendure/core version: 1.7.3
 - Nodejs version: 16.3.2
 - Database (mysql/postgres etc): MariaDB

**Comment by dlhck** [comment]
This issue relates to a version of Vendure that is no longer supported. If the issue persists in the latest version, please open a new issue.
