### ISSUE TITLE
Pick an asset image when adding  a new option

### ISSUE THREAD

**Issue by 0xuhe** [vendure-ecommerce/vendure#1819]
We have to pick asset for each variant right now. 
But most of time, a product will have a color option with same image (like: red, black) and a size option (like: Large, Small).
This product will generate four variants automatically. Usually the variants with color red, red+large and red+small, will have same image, but we have to attach the asset image after the option Red created and for each variant, otherwise the variants will be attached with main product asset as default. It means we have to attach asset for these variants one by one.

I hope we could attatch image asset to the option, and each variant with this image option will attach this image also.

**Comment by michaelbromley** [comment]
Hi,
Thanks for the suggestion. This is not something that we have planned for now.
