### ISSUE TITLE
Issues about shipping fee with coupon code.

### ISSUE THREAD

**Issue by gillgill12** [vendure-ecommerce/vendure#1823]
**Describe the bug**
Issue:
The order have shipping fee. Apply the coupon code with fixed amount over order total get the negative amount.
Then remove the coupon code from order. the shipping fee will be disappear.

**To Reproduce**
1. Create an Order with shipping fee. 
2. Apply the coupon code. e.g. Discount (10000)
3. the order total will be negative.
4. remove the coupon code. 

we have a order with shipping fee.
<img width="1045" alt="Screenshot 2022-10-05 at 2 39 54 PM" src="https://user-images.githubusercontent.com/2081323/193996803-d92671cb-e313-4a0a-955a-f7bd13c0a43e.png">

and the coupon code discount order by fixed amount (over order price)
<img width="1586" alt="Screenshot 2022-10-05 at 2 22 12 PM" src="https://user-images.githubusercontent.com/2081323/193995063-b975cf18-6859-4c5f-8555-e630c148252f.png">
<img width="1152" alt="Screenshot 2022-10-05 at 2 14 59 PM" src="https://user-images.githubusercontent.com/2081323/193998022-cf7da801-9376-4b0b-92c8-06e2cde690fe.png">

when remove the coupon code 
<img width="1040" alt="Screenshot 2022-10-05 at 2 39 26 PM" src="https://user-images.githubusercontent.com/2081323/193997354-3289909c-701d-4a9c-b74e-58b1e37331e7.png">
the tax summary shipping tax removed auto.

Modifying the order also have same issue.

**Environment (please complete the following information):**
@vendure/core version: v1.7.3 
Nodejs version: 16.17.0
Database (mysql/postgres etc): postgres

**Comment by madinghk** [comment]
I got the same issue, I apply the coupon more than the total amount, the amount will become negative. So, I remove the coupon, but shipping address, method and fee also removed together. @michaelbromley

**Comment by michaelbromley** [comment]
Thanks for the report. The issue appears to be pretty simple - the `orderFixedDiscount` action is calculating the discount against the `order.total`, which _includes shipping_, whereas it should be calculated against `order.subtotal`.

> So, I remove the coupon, but shipping address, method and fee also removed togethe

I saw this too. I think this is a side-effect of the underlying issue: namely, when the total is negative, the default shipping eligibility checker condition of "minimum order value $0" becomes false, so Vendure (correctly) removes the now-ineligible shipping method.
