### ISSUE TITLE
Job Queue Plugin-  bullmq version miss-match.

### ISSUE THREAD

**Issue by radekdob** [vendure-ecommerce/vendure#1833]
**Describe the bug**
Following [the doc ](https://www.vendure.io/docs/typescript-api/job-queue-plugin/bull-mqjob-queue-plugin/) will lead to download the latest version of the bullmq npm package.

After registering **BullMQJobQueuePlugin** to the plugin list, app will not get up, due to missing class inside the latest bullmq package.
As you can see [here](https://docs.bullmq.io/changelog) a class **QueueScheduler** was removed in version 2.0.0.
This class is missing in the newer version which is by default installed with vendure plugin.

**To Reproduce**
1. Install job-queue-plugin v 1.7.3
2. Install redis
3. Register BullMQJobQueuePlugin as plugin
4. Run the app
5. See error

**Expected behavior**
The plugin should work.

**Environment (please complete the following information):**
 - @vendure/core version: 1.7.3
 - Nodejs version 16.10
 - Database (mysql/postgres etc): mysql

**Comment by michaelbromley** [comment]
This issue relates to a version of Vendure that is no longer supported. If the issue persists in the latest version, please open a new issue.
