### ISSUE TITLE
Indexing performance for products with many variants

### ISSUE THREAD

**Issue by alexisvigoureux** [vendure-ecommerce/vendure#1837]
**Is your feature request related to a problem? Please describe.**
We use the Elasticsearch plugin for indexing. We have products with a lot of variants (>1000 active). When indexing these products we notice a huge memory consumption.

![Capture d’écran 2022-10-10 à 11 15 10](https://user-images.githubusercontent.com/6134849/195275629-6dd89071-cae1-458d-bf65-0ce3b373fd78.png)

Our indexing is on a separate Kubernetes pod, and this consumption results in an OOM killed of the pod.

We have notice 2 problems:
- The size of the [product object](https://github.com/vendure-ecommerce/vendure/blob/master/packages/elasticsearch-plugin/src/indexing/indexer.controller.ts#L678) when deleting products in the index
- The size needed by the postgre lib to build the [product object](https://github.com/vendure-ecommerce/vendure/blob/master/packages/elasticsearch-plugin/src/indexing/indexer.controller.ts#L508) during indexing

Environment:
@vendure/core version: 1.7.2
Nodejs version: 16.16
Database: postgres

**Describe the solution you'd like**
We would like that the indexing jobs had a controllable heap size.

**PR**
- #1838 
- #1839

**Comment by michaelbromley** [comment]
Thanks for this issue & the 2 PRs! 

It seems that #1838 is causing the tests to fail: https://github.com/vendure-ecommerce/vendure/actions/runs/3234542632/jobs/5297771269#step:9:129

**Comment by michaelbromley** [comment]
Thank you for these valuable contributions! 🥳
