### ISSUE TITLE
Product Customer Entity Custom field error 

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#1844]
When I add customer as customfield relation with eager true option, I get a strange error in admin UI as below:

![image](https://user-images.githubusercontent.com/29729738/196218579-1cbad247-1ed8-4b0a-a803-9222e2ca9b37.png)

![image](https://user-images.githubusercontent.com/29729738/196218714-de669393-be1b-43c3-b313-8970354bdbb0.png)

The customfield config is as below:

config.customFields.ProductVariant.push({
```
            name: 'customer',
            label: [
                {
                    value: 'Customer',
                    languageCode: LanguageCode.en,
                },
            ],
            type: 'relation',
            entity: Customer,
            eager: true,
            nullable: true,
        });

```

**Comment by michaelbromley** [comment]
I just tried to reproduce this on current master (v1.7.4) with the provided custom field config, and do not see the issue.

Are you able to reproduce this issue from a clean `@vendure/create` install of the latest version?

**Comment by michaelbromley** [comment]
This issue is being closed because further data was needed but was not provided. If you want to continue the thread, comment below with the required information and the issue can be re-opened.
