### ISSUE TITLE
Cannot filter by standard field of relation order.customer

### ISSUE THREAD

**Issue by eric-mulhern** [vendure-ecommerce/vendure#1851]
**Describe the bug**
Right now our query looks like this:
```
const qb = this.listQueryBuilder
      .build(Rfq, options ?? {}, {
        ctx,
        relations: [
          'order', 
          'order.channels', 
          'order.customer',
          'order.customer.customFields.company',
          'lockedBy',
        ],
        customPropertyMap: {
          customerLastName: 'order.customer.lastName',
          customerEmailAddress: 'order.customer.emailAddress',
          companyName: 'order.customer.customFields.company.name',
          companyId: 'order.customer.customFields.company.id',
          orderCode: 'order.code',
          orderUpdatedAt: 'order.updatedAt',
          state: 'order.state',
        },
      })
      .leftJoin(
        (qb) => {
          return qb
            .select('MAX(version)', 'max_version')
            .addSelect('"rfqId"', 'rfq_id')
            .groupBy('rfq_id')
            .from(RfqVersion, 'version');
        },
        'latest_rfq_version',
        'latest_rfq_version.rfq_id = rfq.id'
      )
      .leftJoinAndSelect(
        'rfq.versions',
        'versions',
        'versions.version = latest_rfq_version.max_version'
      )
      .leftJoinAndSelect('versions.lines', 'lines', 'versions.id = lines."rfqVersionId"')
      .leftJoinAndSelect('rfq.order', 'order', 'order.id = rfq.orderId')
      .leftJoin('order.customer', 'customer')
      .leftJoin('order.channels', 'channels')
      .andWhere('channels.id = :channelId', { channelId: ctx.channelId });
```

We have a custom entity ‘rfq’ where each rfq row is associated with an order row. This query returns the list of all rfqs, and can be filtered by custom field ‘company name’, rfq id, rfq name, and customer last name.
For some reason, since 1.6.0 the query breaks when I pass in a filter option for customerLastName:
```
The customPropertyMap entry "customerLastName:order.customer.lastName" could not be resolved to a related table
```
It’s puzzling to me since we’re able to successfully filter by company name, which is a custom property on ‘customer’, but the lastName property of customer breaks it.

I am also unable to filter by customerEmail.

The error is being thrown from list-query-builder  > normalizeCustomPropertyMap . When I look at the qb.expressionMap.aliases array I don’t see an alias created for customer last name. I’m wondering if it might be caused by the logic which parses the entityPart and columnPart from the customPropertyMap? Or if there’s a change I can make to the syntax of the query to make it work.

**To Reproduce**
1. Create a listQueryBuilder query to a custom entity that joins with order and order.customer
2. Add a customPropertyMap to customerLastName and customerEmail on the order.customer table
3. Run this query, passing in customerLastName or customerEmail as a filter option
4. See error: *The customPropertyMap entry "customerLastName:order.customer.lastName" could not be resolved to a related table*

**Expected behavior**
I would expect to be able to filter by customerLastName custom property map

**Environment (please complete the following information):**
 - @vendure/core version: *1.7.4*
 - Nodejs version: *v16.15.1*
 - Database (mysql/postgres etc): *postgres*

**Comment by michaelbromley** [comment]
After some investigation it looks like this is related to #1774, including some optimizations which were introduced as part of v1.6 to minimize the amount of joins that are performed on list queries. That optimization is too aggressive (i.e. buggy). Looking at a fix for both this and the linked issue.
