### ISSUE TITLE
Error trying to remove an order line from a draft order

### ISSUE THREAD

**Issue by MarcusSantos37** [vendure-ecommerce/vendure#1855]
I'm trying to remove an order line from a draft order, and I'm getting the following error:
{
  "errors": [
    {
      "message": "SqliteError: FOREIGN KEY constraint failed",
      "locations": [
        {
          "line": 68,
          "column": 3
        }
      ],
      "path": [
        "removeDraftOrderLine"
      ]
    }
  ],
  "data": null
}

**Comment by michaelbromley** [comment]
Hi,
Thanks for the report. Can you provide instructions to reproduce?

Also small tip - if you enclose the code block in three backticks it will format nicely. See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by MarcusSantos37** [comment]
@michaelbromley 

Sorry for the bad description, I will better describe the error and how to reproduce it.

I'm using the vendure demo api to do some tests. I created a draft order and added any product to the cart, when changing the quantity of a product in the cart a few times and then trying to remove the product from the cart or even delete the order, I get the error:  **SqliteError: FOREIGN KEY constraint failed**

**To Reproduce**
Steps to reproduce the behavior:
1. Go to **https://demo.vendure.io/admin**
2. Create a draft order
3. Add some product in the draft order
4. Change the quantity of this product in the cart (Ex: if you have 1, change it to 5, if you have 8, change it to 3). Do this for a few times.
5. Try removing the product from the cart or deleting the order and you will see the error.

**Expected behavior**
It is expected that the item or order will be removed normally.

**Environment**
 - @vendure/core v1.8.2
 - Nodejs v18.10.0

**Comment by MarcusSantos37** [comment]
@michaelbromley 

Any feedback?

**Comment by michaelbromley** [comment]
It's in the backlog to handle for the next patch release, so I'll be able to look deeper into this soon.
