### ISSUE TITLE
TypeScript checks do not work correctly, when trying to filter with customFields

### ISSUE THREAD

**Issue by chregu** [vendure-ecommerce/vendure#1863]
**Describe the bug**
Trying to use `findAll` methods with filters for customFields will lead to TypeScript errors.

eg. does not work
```typescript
const products = await this.productService.findAll(ctx, { filter: { someCustomField: { eq: 'Foo' } } })
```

The workaround I found is to explicitly define a filter with a `CustomProductFields` in it.

This works then without complaints by the TS linter

```typescript
const filter: NullOptionals<FilterParameter<Product & CustomProductFields>> = {
    someCustomField: { eq: 'Foo' },
}
const products = await this.productService.findAll(ctx, { filter })
```

**To Reproduce**
See above, almost any (I guess) `findAll` service method with searching for customFields.

**Expected behavior**

The first code above should just work and not throw TS errors

**Environment (please complete the following information):**
 - @vendure/core version: 1.8
 - Nodejs version: 16, but irrelevant
 - Database (mysql/postgres etc): postgres, but irrelevant

**Additional context**

According to @michaelbromley [this definition](https://github.com/vendure-ecommerce/vendure/blob/94da850360030d6b614398fb9e936d789dfb2d9d/packages/core/src/common/types/common-types.ts#L103) needs to be improved. Unfortunately my TS foo is not good enough to actually try to fix it.

From this slack thread: https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1667636306318749

**Comment by dlhck** [comment]
This issue relates to a version of Vendure that is no longer supported. If the issue persists in the latest version, please open a new issue.
