### ISSUE TITLE
Not possible to install Vendure on Mac M1.

### ISSUE THREAD

**Issue by amesas** [vendure-ecommerce/vendure#1866]
**Describe the bug**
Not possible to install Vendure on Mac M1.

We get:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.30.7 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`

**To Reproduce**
1. npx @vendure/create my-sample-store
2. Accept default config
3. Wait....

**Expected behavior**
Vendure should install correctly :)

**Environment (please complete the following information):**
 - @vendure/core version: 1.8.2
 - Nodejs version: v14.18.1
 - Database (mysql/postgres etc): mysql

**Additional context**
From what we have seen in other projects, the problem comes from Sharp 0.30.
If you upgrade Sharp to 0.31, libvips get installed correctly.
We have not found any problems upgrading Sharp from 0.30 to 0.31.

**Comment by michaelbromley** [comment]
Thanks for the report! The sharp dependency will be updated in the next patch version coming soon 👍
