### ISSUE TITLE
Non-existent routes should respond with 404

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#187]
**Describe the bug**
Currently, when requesting a route that is not defined, the server will hang and not return any response.

**To Reproduce**
1. Start the Vendure server
2. In the browser request `http://localhost/bad-route`
3. Browser will hang, no response

**Expected behavior**
It should 404.

**Environment (please complete the following information):**
 - @vendure/core version: 0.4.0
 - Nodejs version: 12.4.0
 - Database (mysql/postgres etc): any

**Comment by Szbuli** [comment]
This issue still happens to 401

**Comment by Szbuli** [comment]
The error happened when i added an authguard to the controller endpoint, but not added the authguard to nestjs (not set passportmodule as an import, and not set the strategy as a provider)

**Comment by Szbuli** [comment]
If i throw a Forbidden error in a rest controller. It will not return 403 to the client, it will hang
