### ISSUE TITLE
Global Setting to chose if RootCollection will be shared by Channels

### ISSUE THREAD

**Issue by maurosergiosilva** [vendure-ecommerce/vendure#188]
**Is your feature request related to a problem? Please describe.**
The actual behavior of Channels is dont share same rootCollection, so every Channel has it owns rootCollection.  These works fine when Store has channels that has it owns Taxonomy, but sometimes you can have situations where Channels share same Taxonomy from Store.

**Describe the solution you'd like**
An possible solution is add a GlobalSeeting where you choose if Channels share same RootCollection or not, and refactor culd be done in collection.service.ts, to check if Channels share or not RootCollection

**Comment by michaelbromley** [comment]
Relates to #12

**Comment by michaelbromley** [comment]
The current implementation of one root per Channel may be a mistake. It might be better to have a single, global root Collection bound to the default Channel, and then use the `channels` property of individual Collections to assign them to one or more Channels. Needs a bit more investigation on my part.

**Comment by michaelbromley** [comment]
For the upcoming next release (v0.6.0) I've removed the multiple rootCollections per-channel. The ability to add/remove Collections to Channels is not yet implemented (although it will be possible to create a new Collection in a non-default Channel). Full channel handling for Collections will be enabled in a future release.
