### ISSUE TITLE
Tax calculation is wrong for TaxLineCalculationStrategy that returns multiple TaxLines

### ISSUE THREAD

**Issue by casabian** [vendure-ecommerce/vendure#1883]
**Describe the bug**
When implementing a custom TaxLineCalculationStrategy that returns multiple TaxLines, the price supplied to TaxRate.apply is not used in further tax calculation (see[Order#taxSummary](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/entity/order/order.entity.ts#L281-L301))

**To Reproduce**
Create MultiTaxTaxLineCalculationStrategy and ProductVariant custom fields as follows:
```ts
export class MultiTaxTaxLineCalculationStrategy implements TaxLineCalculationStrategy {
  private taxRateService!: TaxRateService;
  private zoneService!: ZoneService;
  private entityHydrator!: EntityHydrator;

  async calculate(args: CalculateTaxLinesArgs): Promise<TaxLine[]> {
    Logger.info("calculating tax lines");
    const { ctx, order, orderItem, orderLine, applicableTaxRate } = args;
    const productVariant = await this.entityHydrator.hydrate(ctx, orderLine.productVariant, {
      relations: ["customFields.bundlePartTaxCategory"],
    });

    const lineItemCustomFields = productVariant?.customFields as any;
    if (lineItemCustomFields?.bundlePartTaxCategory) {
      const zone = await this.zoneService.findOne(ctx, order.taxZoneId!);
      const taxRate = await this.taxRateService.getApplicableTaxRate(
        ctx,
        zone || ctx.channel.defaultTaxZone,
        lineItemCustomFields?.bundlePartTaxCategory,
      );
      return [
        applicableTaxRate.apply(orderItem.proratedUnitPrice - lineItemCustomFields.bundlePartPrice),
        taxRate.apply(lineItemCustomFields.bundlePartPrice),
      ];
    }

    return [applicableTaxRate.apply(orderItem.proratedUnitPrice)];
  }
  init(injector: Injector) {
    this.taxRateService = injector.get<TaxRateService>(TaxRateService);
    this.zoneService = injector.get<ZoneService>(ZoneService);
    this.entityHydrator = injector.get<EntityHydrator>(EntityHydrator);
  }
  destroy?: (() => void | Promise<void>) | undefined;
}
```

CustomFields on ProductVariant
```ts
...
  ProductVariant: [
    {
      name: "bundlePartTaxCategory",
      type: "relation",
      entity: TaxCategory,
      nullable: true,
      label: [
        { languageCode: LanguageCode.en, value: "Bundle Part Tax Category" },
        { languageCode: LanguageCode.de, value: "Bundle Steuerklasse" },
      ],
      ui: { component: "tax-category-form-input" },
    },
    {
      name: "bundlePartPrice",
      type: "float",
      nullable: true,
      label: [
        { languageCode: LanguageCode.en, value: "Bundle Part Price" },
        { languageCode: LanguageCode.de, value: "Bundle Teil Preis" },
      ],
      ui: { component: "currency-form-input" },
    },
  ],
...
```

**Expected behavior**
The price passed to TaxRate#apply should be used in tax calculation in Order#taxSummary.

**Environment (please complete the following information):**
 - @vendure/core version: all
 - Nodejs version: 16.x.x
 - Database (mysql/postgres etc): all

**Comment by michaelbromley** [comment]
Hi,
thanks for the report. Are you able to also supply a sample query that returns wrong data so I can be sure I am looking in the right place?

**Comment by casabian** [comment]
When creating an Order with the above configuration. The tax of the product always uses the complete price of the product as base price, no matter what you'll pass to TaxRate.apply. I figured out that current implementation splits the price by a proportion of the totalTaxRate. As implemented in [Order#taxSummary](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/entity/order/order.entity.ts#L281-L301)).

When looking at [OrderItem#proratedUnitPriceWithTax](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/entity/order-item/order-item.entity.ts#L159-L162) tax is calculated by the sum of all taxRates (see  [OrderItem#taxRate](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/entity/order-item/order-item.entity.ts#L107-L110))

**Comment by michaelbromley** [comment]
Thanks for the extra info. So is it just the taxSummary that is wrong?

What I'm really missing here as part of the issue report is a step by step instructions like

1. Set up this tax calc strategy (provided)
2. Add these custom fields (provided)
3. Run the following mutation...
4. Run the following query ....
5. The query field X returns Y, when it should actually be Z

Instructions like that take away all the guesswork for me to exactly reproduce the issue you are talking about. It vastly speeds things up for me and makes me way more likely to be able to rapidly resolve the issue.

If you can provide something like that, it would be great :)

**Comment by dlhck** [comment]
This issue is being closed because further data was needed but was not provided. If you want to continue the thread, comment below with the required information and the issue can be re-opened.
