### ISSUE TITLE
setCustomerForOrder throwing NO_ACTIVE_ORDER_ERROR

### ISSUE THREAD

**Issue by LorenzoRottigni** [vendure-ecommerce/vendure#1885]
**Describe the bug**
In my order flow i call several order APIs but the setCustomerForOrder for guest users it's returning NO_ACTIVE_ORDER_ERROR.
APIs called before and after (addItemToOrder, setOrderShippingAddress, setOrderPaymentMethod, ...) are working fine.

**To Reproduce**

**Expected behavior**
I expect that the setCustomerForOrder APIs doesn't throw error and i should be able to see the guest customer email inside the order

**Environment (please complete the following information):**
 - @vendure/core version: latest next
 - Nodejs version 16.14.0
 - Database (mysql/postgres etc): postgresQL

**Additional context**

**Comment by michaelbromley** [comment]
I cannot reproduce this on my live shop running on 2.0.0-next.22. Are there any customizations you have made which might be related?

**Comment by LorenzoRottigni** [comment]
There is nothing custom... How do you determine the activeOrder session in your logic?

**Comment by giosueDelgado** [comment]
@michaelbromley we see that in this api there id an if `if (ctx.authorizedAsOwnerOnly) {` in the first row of that function, and if I search the definition of `authorizedAsOwnerOnly` there is a comment that says:

```
/**
     * @description
     * True if the current anonymous session is only authorized to operate on entities that
     * are owned by the current session.
     */
    get authorizedAsOwnerOnly(): boolean {
        return this._authorizedAsOwnerOnly;
    }

```

Is a config that we can change? Can give us a better explanation?

Thanks
