### ISSUE TITLE
Typescript Error in Config When using Postgres

### ISSUE THREAD

**Issue by osseonews** [vendure-ecommerce/vendure#1888]
If you use the existing configuration docs for a postgres database as described here: https://www.vendure.io/docs/developer-guide/configuration/, the line with "port" will throw a typescript error: `Type 'string | undefined' is not assignable to type 'number | undefined`.  No idea how to fix this, but this prevents a build.  I assume you need to somehow convert the process.env value to a number, but unsure how that is done. ParseInt function doesn't help. Please update docs with correct way to do configuration for Port for TS. For now we just ts ignore that line. Thanks!

Thanks.

**Comment by osseonews** [comment]
Right, but how do we fix the error. The port is expecting a number, but process.env is a string. Sorry if this a simple question, just don't understand TS all that well or how to convert a process.env var into a number.

**Comment by michaelbromley** [comment]
The usual way to handle it is like this:

```ts
post: +process.env.PORT,
```

the `+` operator will cast to a number.

**Comment by osseonews** [comment]
That throws a new error: `Object is possibly 'undefined'.ts(2532)`

**Comment by michaelbromley** [comment]
If you combine the two techniques I mentioned it should work:

```ts
declare global {
    namespace NodeJS {
        interface ProcessEnv {
            PORT: string;
        }
    }
}

// ...

post: +process.env.PORT,
```
