### ISSUE TITLE
Add Channels Collections/Facets

### ISSUE THREAD

**Issue by maurosergiosilva** [vendure-ecommerce/vendure#189]
**Is your feature request related to a problem? Please describe.**
Sometimes, you have Channels that works in same segments, for example, Foods (Italian, Mexican etc) and you want present and filter Channels based in these Taxonomy (Collections).
**Describe the solution you'd like**
Add Channels Collection and Channels Facests.

**Comment by michaelbromley** [comment]
Relates to #12

**Comment by michaelbromley** [comment]
Can you expand on this a little? - I'm not sure I understand the use case.

Do you want to be able to more easily filter the Channels in the admin UI? How many Channels do you plan to have? And what does each Channel represent?

**Comment by maurosergiosilva** [comment]
In my case each channel represent a vendor/store.
Those collections are for store-front, that is an app made in react. I will give an example that is not exactly my case, but can illustrate better what I need. Let suppose that those channels sell food. In my home I want to show those collections in a slider with multiple items (i.e: Italian, Mexican, Brazilian) that links to collections landing, that shows only vendors that are part of these collections.
Facets are for search,  if I search for 'soup', for example, I want present results in tabs, one showing Channels that has sell soup, and another tab for products that are soup.
