### ISSUE TITLE
s3-asset-storage-strategy

### ISSUE THREAD

**Issue by maurosergiosilva** [vendure-ecommerce/vendure#191]
**Describe the solution you'd like**
Add suport to store assets on S3 Bukets.

**Comment by michaelbromley** [comment]
This is a good idea. I've no experience with S3 so I'm going to leave this as "contributions welcome" for now and see if anyone wants to work on it.

**Comment by maurosergiosilva** [comment]
feat(asset-server-plugin)

1. add AssetStorageStrategy to export interface AssetServerOptions ;
2. add  Minio via docker-compose.yml into asse-server-plugin; 
3. implement S3AssetStorageStrategy;
