### ISSUE TITLE
ChangedPriceHandlingStrategy init is not called

### ISSUE THREAD

**Issue by moamen-nour** [vendure-ecommerce/vendure#1916]
**Describe the bug**
ChangedPriceHandlingStrategy init is not called

**To Reproduce**
Implement and register a custom ChangedPriceHandlingStrategy and override init function to inject some service

**Expected behavior**
The required services can be retreived from DI container from within the init function

**Actual behavior**
The init function is not called

**Environment (please complete the following information):**
 - @vendure/core version:1.9
 - Nodejs version:16.0.0
 - Database (mysql/postgres etc):postgres

**Additional context**
We are hacking it currently by
```
bootstrap(config).then(async (AppModule) => {
  const configService = AppModule.get(ConfigService);
  if (
    typeof configService.orderOptions.changedPriceHandlingStrategy.init ===
    "function"
  )
    configService.orderOptions.changedPriceHandlingStrategy.init(
      AppModule as any
    );
});
```

**Comment by michaelbromley** [comment]
Thanks for the report! Fix coming in next patch release.
