### ISSUE TITLE
Feature request: Tier Pricing Feature and Price Lists

### ISSUE THREAD

**Issue by osseonews** [vendure-ecommerce/vendure#1920]
Please add tier pricing to Vendure as doing this with promotions is not really viable.  Tier pricing is sometimes known as bulk pricing.
Tier pricing is: Buy 1 of X for $100, or Buy 3 of X for $80, or Buy 10 of X for $50

An associated feature is to have each price associated with a price list, e.g. this is the price and tier price for CustomerGroupA and then this is the is the price and tier price for CustomerGroupB.

From what I can tell, Vendure is currently set up so that there is only one price per variant and you can only manipulate this price via promotions. However, the above functionality requires a bit of a different set up on the backend. 

Thanks.

**Comment by seminarian** [comment]
Nice to see this is already planned for v2! 

Would be awesome if Price Lists could have lots of configuration parameters (e.g. channel, facets, start date, end date, ..) and that they support two modes:
- Override modus who just changes the price of a Variant
- Sale modus which has a price and Original price so frontends can show a % discount on their pages!
