### ISSUE TITLE
Admin app shows empty page after extending the Admin UI.

### ISSUE THREAD

**Issue by revapp-tech** [vendure-ecommerce/vendure#1921]
**Describe the bug**
When try to extend admin ui, the admin app shows empty page and all related js files failed to load.

**To Reproduce**
1. In vendure-config.ts setup AdminUiPlugin as below
![Screenshot 2022-12-07 174452](https://user-images.githubusercontent.com/117645249/206241631-62ca4c50-b929-49eb-a4c3-b1655d9bff59.png)

3. Run `npm run dev`, the admin-ui is successfully compiled
![Screenshot 2022-12-07 1758172](https://user-images.githubusercontent.com/117645249/206242459-f787d28c-09ec-4c23-a2bf-b8e88013a18a.png)

4. Open http://localhost:3000/admin
6. The page is empty and js files failed to load
![Screenshot 2022-12-07 180140](https://user-images.githubusercontent.com/117645249/206243557-0d1b7401-11ea-4776-8fa0-a844fa0eb0ef.png)

**Expected behavior**
See login or dashboard screen instead of empty page.

**Please Note**
When I access http://localhost:4200 I can see the login page, but all network requests fails
![Screenshot 2022-12-07 180306](https://user-images.githubusercontent.com/117645249/206244021-ce221500-2d74-4a5b-847d-2dac008edd6c.png)

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.0
 - Nodejs version: 16.17.1

**Comment by michaelbromley** [comment]
Possibly related:

- https://github.com/vendure-ecommerce/vendure/issues/1794

**Comment by michaelbromley** [comment]
Closing this as it is probably stale. But if anyone still runs into this please comment and I'll re-open.
