### ISSUE TITLE
When using a entityIdStrategy, the query on facetValues in the admin produces an error

### ISSUE THREAD

**Issue by chregu** [vendure-ecommerce/vendure#1922]
**Describe the bug**
When using a `entityIdStrategy` which returns a "hashed" string instead of the actual ID in the DB, we get a `invalid input syntax for type integer: "foo_1"` error on `facetValues` query when updating a product in the admin backend.

**To Reproduce**
1. Use an entityIdStrategy which returns something different then the actual ID, eg.
```
import { EntityIdStrategy } from '@vendure/core'

export class MyIdStrategy implements EntityIdStrategy<'increment'> {
    readonly primaryKeyType = 'increment'
    decodeId(id: string): number {
        return Number(id.substr(4))
    }
    encodeId(primaryKey: number): string {
        return `foo_${primaryKey}`
    }
}

```
2. Go to the admin and edit a product.
3. You'll get an error reported, but the update still works.

The error happens in this GraphQL query
```
query GetFacetValueList($options: FacetValueListOptions) {
  facetValues(options: $options) {
    items {
      ...FacetValue
      __typename
    }
    totalItems
    __typename
  }
}
```
and `$options` being
```
{
  "options": {
    "filter": {
      "id": {
        "in": [
          "gGnNGY"
        ]
      }
    }
  }
}
```
Looks like that entityId is never decoded.

I don't know how easy it is to have that in filters, or if it was just some oversight somewhere.

With some input, I can maybe try to fix that by myself

**Expected behavior**
No error happens

**Environment (please complete the following information):**
 - @vendure/core version: 1.9
 - Nodejs version: 16
 - Database (mysql/postgres etc): postgresql

**Comment by michaelbromley** [comment]
Thanks for the report! In investigating the cause, it turned out to be quite fast to fix and verify. Don't worry though, there are still a few more bugs that you can take on in future for sure 😄
