### ISSUE TITLE
Failing to generate test email for OrderConfirmation with Default email handlers

### ISSUE THREAD

**Issue by nemo-js** [vendure-ecommerce/vendure#1931]
**Describe the bug**
When I press 'Generate Test' from the /mailbox for 'order-confirmation' template, nothing is generated and I get an error message to the console

Console error:
TypeError: Cannot read properties of undefined (reading 'headers')
at ctx (...\node_modules\@vendure\asset-server-plugin\src\common.ts:10:38)

**To Reproduce**
1. Go to /mailbox
2. Select 'order-confirmation'
3. Click 'Generate Test'
4. See error in vendure console

**Expected behavior**
An email should be generated like in other templates

**Environment (please complete the following information):**
 - @vendure/core version: 1.8.5, 1.91
 - Nodejs version 16
 - Database (mysql/postgres etc): MariaDb

**Comment by koljam** [comment]
This happens to me too, also when a payment is received from mollie. It seems like the ctx doesn't have a req in some cases [when it gets used here](https://github.com/vendure-ecommerce/vendure/blob/master/packages/email-plugin/src/default-email-handlers.ts#L104).

Here is my whole stacktrace:

```Cannot read property 'headers' of undefined
[dev:*server] TypeError: Cannot read property 'headers' of undefined
[dev:*server]     at ctx (C:\...\vendure\node_modules\@vendure\asset-server-plugin\src\common.ts:10:38)
[dev:*server]     at LocalAssetStorageStrategy.toAbsoluteUrlFn (C:\...\vendure\node_modules\@vendure\asset-server-plugin\src\default-asset-storage-strategy-factory.ts:17:24)
[dev:*server]     at transformOrderLineAssetUrls (C:\...\vendure\node_modules\@vendure\email-plugin\src\default-email-handlers.ts:104:46)
[dev:*server]     at EmailEventHandlerWithAsyncData._loadDataFn (C:\...\vendure\node_modules\@vendure\email-plugin\src\default-email-handlers.ts:34:9)
[dev:*server]     at EmailEventHandlerWithAsyncData.handle (C:\...\vendure\node_modules\@vendure\email-plugin\src\event-handler.ts:334:77)
[dev:*server]     at EmailPlugin.handleEvent (C:\...\vendure\node_modules\@vendure\email-plugin\src\plugin.ts:330:42)
[dev:*server]     at SafeSubscriber._next (C:\...\vendure\node_modules\@vendure\email-plugin\src\plugin.ts:317:29)
[dev:*server]     at SafeSubscriber.__tryOrUnsub (C:\...\vendure\node_modules\rxjs\src\internal\Subscriber.ts:265:10)
[dev:*server]     at SafeSubscriber.next (C:\...\vendure\node_modules\rxjs\src\internal\Subscriber.ts:207:14)
[dev:*server]     at Subscriber._next (C:\...\vendure\node_modules\rxjs\src\internal\Subscriber.ts:139:22)```
