### ISSUE TITLE
Customizable stripe metadata

### ISSUE THREAD

**Issue by mariotaran** [vendure-ecommerce/vendure#1935]
I want to add some other properties in stripe metadata. My request is about making stripe metadata editable.
The properties i want to add are customerEmail, customerName and orderId cause i want to see those in the stripe dashboard through metadata

Michael proposed this solution to me which I like.
A function that is used to build the metadata before creating the payment intent with Stripe.

The alternative to this would be for me to clone the stripe plugin and change the properties from there, but cloning the whole plugin just to add 3 properties doesn't make much sense.
@michaelbromley

**Comment by giosueDelgado** [comment]
There are some news?
