### ISSUE TITLE
BullMQ Job Queue Plugin throws TypeError: bullmq_1.QueueScheduler is not a constructor

### ISSUE THREAD

**Issue by intrinsic-blockchain** [vendure-ecommerce/vendure#1936]
**Describe the bug**
Vendure does not start up after configuring BullMQ Job Queue plugin in vendure config.

**To Reproduce**
1. Comment out the default job queue plugin:
`// DefaultJobQueuePlugin.init({ useDatabaseForBuffer: true }),`

2. Import the BullMQJobQueuePlugin:
`import { BullMQJobQueuePlugin } from '@vendure/job-queue-plugin/package/bullmq';`
`BullMQJobQueuePlugin.init({
            connection: {
              port: 6379
            },
            workerOptions: {
                concurrency: 10,
            },
          }),`

3. Setup redis and redis commander using docker

5. Run Vendure
`npm run dev`

6. See the error in console:
`[server] info 17/12/22, 6:32 pm - [BullMQJobQueuePlugin] Checking Redis connection... 
[server] info 17/12/22, 6:32 pm - [BullMQJobQueuePlugin] Connected to Redis ✔
[server] TypeError: bullmq_1.QueueScheduler is not a constructor
[server]     at BullMQJobQueueStrategy.init (C:\Users\....\node_modules\@vendure\job-queue-plugin\src\bullmq\bullmq-job-queue-strategy.ts:100:26)`

**Expected behavior**
Should run the vendure shop-api, admin-api, admin-ui without errors

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.1
 - Nodejs version: v18.12.1
 - Database (mysql/postgres etc): redis , postgres

**Additional context**
Here are the details in image
![image](https://user-images.githubusercontent.com/105105979/208244311-1f59a04c-d507-4fa3-b017-d27d747c6462.png)

**Comment by michaelbromley** [comment]
Hi,

Can you run `npm ls bullmq` and tell me what version of the `bullmq` package is installed?

**Comment by intrinsic-blockchain** [comment]
> Hi,
> 
> Can you run `npm ls bullmq` and tell me what version of the `bullmq` package is installed?

Thanks for taking a look, the version used is bullmq@3.4.2

**Comment by michaelbromley** [comment]
Ah ok. We need to update it to be compatible with newer versions. For now install bullmq v1.x, and let me know if that works.

**Comment by intrinsic-blockchain** [comment]
> Ah ok. We need to update it to be compatible with newer versions. For now install bullmq v1.x, and let me know if that works.

Thanks @michaelbromley it works with version 1.19.3.
