### ISSUE TITLE
Cannot checkout with coupons using Mollie payment since 1.9 (Mollie Orders API)

### ISSUE THREAD

**Issue by kyunal** [vendure-ecommerce/vendure#1939]
**Describe the bug**
The new Mollie plugin introduced in Vendure 1.9 cannot create payment intents if a coupon is applied due to a VAT mismatch.

@martijnvdbrug 

**To Reproduce**
1. Use the Mollie 1.9 plugin
2. Apply a coupon code to the order, e.g. 50%
3. Attempt to create a Mollie payment intent using the corresponding mutation
4. Creation will fail as the Orders API expects a different VAT than what is supplied

**Expected behavior**
Payment intent creation should work fine and applied coupons should be included the way Mollie expects them to: https://docs.mollie.com/orders/handling-discounts#discounts-and-vouchers

**Environment (please complete the following information):**
 - @vendure/core version: 1.9 and up
 - NodeJS 16
 - Database (mysql/postgres etc): postgres

**Additional context**
Example server output:
```
error 12/17/22, 11:45 PM - [Vendure Server] Order line 1 is invalid. VAT amount is off. Expected VAT amount to be €1.76 (€11.00 × (19.00% / 119.00%)), got €3.51
ApiError: Order line 1 is invalid. VAT amount is off. Expected VAT amount to be €1.76 (€11.00 × (19.00% / 119.00%)), got €3.51
    at Function.createFromResponse (/home/node/app/node_modules/@mollie/api-client/dist/mollie.cjs.js:355:12)
    at throwApiError (/home/node/app/node_modules/@mollie/api-client/dist/mollie.cjs.js:754:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by martijnvdbrug** [comment]
@michaelbromley you can assign this to me

**Comment by nabbl** [comment]
@martijnvdbrug when can we expect a fix for this?
Btw it doesnt even work on products without a coupon. it just generally doesent work

**Comment by kyunal** [comment]
I cannot confirm that 'normal' orders are also affected, we currently handle them with the new API just fine. If you have trouble with it you should be able to downgrade the payment plugin for the time being.

**Comment by nabbl** [comment]
So I tested this with various products now and I cant really get behind what is wrong.
With a certain Product which costs 99.00€ it works if I order only 1 item. As soon as I take 2 or more it fails with the error message from above.
But other products work just fine. I am at a loss whats happening.

I will try to downgrade the payment plugin.

**Comment by Conor-Burns** [comment]
Can reproduce @nabbl 
```
error 12/22/22, 11:18 AM - [Vendure Server] Order line 1 is invalid. VAT amount is off. Expected VAT amount to be €158.07 (€990.00 × (19.00% / 119.00%)), got €158.10
ApiError: Order line 1 is invalid. VAT amount is off. Expected VAT amount to be €158.07 (€990.00 × (19.00% / 119.00%)), got €158.10
    at Function.createFromResponse (/home/node/app/node_modules/@mollie/api-client/dist/mollie.cjs.js:355:12)
    at throwApiError (/home/node/app/node_modules/@mollie/api-client/dist/mollie.cjs.js:754:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
For items costing 99€ and 5 or more in checkout.
Downgraded our prod stack for now.

**Comment by martijnvdbrug** [comment]
> @martijnvdbrug when can we expect a fix for this? Btw it doesnt even work on products without a coupon. it just generally doesent work

Hi @nabbl That sounds pretty serious, could you open a separate issue with reproducible steps for this? 

I have the latest version of this plugin running on our development environment, that seems to work.

**Comment by martijnvdbrug** [comment]
> Can reproduce @nabbl
> 
> ```
> error 12/22/22, 11:18 AM - [Vendure Server] Order line 1 is invalid. VAT amount is off. Expected VAT amount to be €158.07 (€990.00 × (19.00% / 119.00%)), got €158.10
> ApiError: Order line 1 is invalid. VAT amount is off. Expected VAT amount to be €158.07 (€990.00 × (19.00% / 119.00%)), got €158.10
>     at Function.createFromResponse (/home/node/app/node_modules/@mollie/api-client/dist/mollie.cjs.js:355:12)
>     at throwApiError (/home/node/app/node_modules/@mollie/api-client/dist/mollie.cjs.js:754:22)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> For items costing 99€ and 5 or more in checkout. Downgraded our prod stack for now.

Could you create a separate issue for this with reproducible steps, including taxrates, prices etc? Sounds like this might be a rounding issue

**Comment by martijnvdbrug** [comment]
Sounds like a similar issue: https://github.com/mollie/Shopware6/issues/37. Will need to investigate further.

**Comment by martijnvdbrug** [comment]
@michaelbromley I know you have studied rounding errors a bit, do you maybe have any valuable input on this :arrow_down: ? 

Vendure uses unit rounding, but Mollie expects order line rounding. This causes Mollie to throw an error saying the order line VAT is off.

There is an example below (I'm using 21% taxrate) :
![image](https://user-images.githubusercontent.com/6604455/209163016-5f89a5b7-37d0-44ed-91c5-c3cbce8deb36.png)

```
// Order line rounding, this is what Mollie wants
24.25 / 1.21 = 20.04
```
```
// Unit rounding, what Vendure uses
4.01 * 5 = 20.05
```

What I propose we do, is to use the `line.proratedLinePriceWithTax` as base, and calculate the unit price with `lineproratedLinePriceWithTax / line.quantity`. This causes the Mollie unit price to be off by a few cents compared to Vendure in some cases, but for the totals and the paid amount it doesn't matter.

**Comment by michaelbromley** [comment]
@martijnvdbrug yeah, these rounding & tax issues are really horrible to deal with! 

I think your solution is reasonable. Are there any implications to having a discrepancy in the unit price between Vendure and Mollie? E.g. when creating a refund for part of an order line (e.g. refunding 1 out of 3 of ProductA), does Mollie expect the unit price of a refunded line to be specified?

**Comment by martijnvdbrug** [comment]
Very good point. Mollie allows for refunding arbitrary amounts via the [refund payment api](https://docs.mollie.com/reference/v2/refunds-api/create-payment-refund), so that's accounted for.

**Comment by Conor-Burns** [comment]
@martijnvdbrug 
> Could you create a separate issue for this with reproducible steps, including taxrates, prices etc? Sounds like this might be a rounding issue

Should I still create a new issue as it's basically the same rounding error?

If it helps: 19% VAT and 5 items costing 99€ each produced this error for me

**Comment by martijnvdbrug** [comment]
@Conor-Burns Nope, not neede, its indeed the same error. Thanks for the details.
