### ISSUE TITLE
Collection breadcrumbs should not include private collections in the breadcrumb path

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#1944]
**Describe the bug**
Scenario: Product "T-shirt" is part of 2 collections:

```
root > clothing > tops
root > sale (private) > clothing
```

When querying `Product.collections`, it will return both the "clothing" and "sale" collection, including breadcrumbs which expose the private "sale" collection.

**Expected behavior**
The private "sale" collection should not be exposed.

However, we probably don't want to omit the "clothing" collection altogether, since that one is _not_ private. 

The question is, what should we return for the "breadcrumbs" array of the "clothing" collection?

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.1
 - Nodejs version: any
 - Database (mysql/postgres etc): any

**Comment by michaelbromley** [comment]
I think we should just omit any private collections from the breadcrumb path when in the context of the Shop API.

/bounty $30

**Comment by ibishal** [comment]
/ attempt #1994 
can i get assigned

**Comment by ibishal** [comment]
Hey @michaelbromley why the bounty for this issue is removed?
