### ISSUE TITLE
programmatically creates a single fulfillment for multiple orders will introduce a bug where the fulfillment section of each order will show all items fulfilled from multiple orders

### ISSUE THREAD

**Issue by simpian** [vendure-ecommerce/vendure#1950]
**Describe the bug**
I have a worker that creates a single fulfillment for multiple orders for shipment, and when a single fulfillment is created, it only generates one fulfillment id. 

In order details, we have a fulfillment section where we show the details of the fulfillment, after upgrading to 1.8.5, I'm seeing that the fulfillment section is now showing all items fulfilled under the fulfillment id. Some order lines are from different orders, so we see a list of blank product variant names:

<img width="253" alt="image" src="https://user-images.githubusercontent.com/70731255/209297008-7a073e2d-1ad1-4fa3-a558-1fb58797daa7.png">

This cannot be done using the sample vendure app ui because vendure app ui assumes that we will create a fulfillment for each order.

**To Reproduce**

**Expected behavior**
I would expect that the fulfillment section shows just the fulfilled item for that specific order, even though the fulfillment may include items from other orders.

**Environment (please complete the following information):**
 - @vendure/core version:
 - Nodejs version
 - Database (mysql/postgres etc):

**Additional context**

**Comment by dlhck** [comment]
This issue is being closed because further data was needed but was not provided. If you want to continue the thread, comment below with the required information and the issue can be re-opened.
