### ISSUE TITLE
Custom field pattern validation not being applied when adding order line

### ISSUE THREAD

**Issue by sslotsky** [vendure-ecommerce/vendure#1953]
**Describe the bug**

Adding a `pattern` validation to a custom field on the `OrderLine` seems to have no effect when executing the `addItemToOrder` mutation. I seem able to submit any value for my custom field, no matter which pattern I choose.

**To Reproduce**

Add this custom field to the config:

```ts
  customFields: {
    OrderLine: [
      {
        name: "transformation",
        type: "string",
        // You can also try a simpler pattern like '^foo$' for testing, the result is the same
        pattern: '^tr:w\-\\d+(\.\\d+),h\-\\d+(\.\\d+),cm\-extract,x\-\\d+(\.\\d+),y\-\\d+(\.\\d+)?$'
      },
      { name: "fileId", type: "string" },
    ],
  },
```

Then generate/run migrations, restart the server, and go to the shop-api GraphQL playground. Execute a mutation with a value for `transformation` that doesn't match, e.g.

```gql
mutation AddToOrder {
  addItemToOrder(productVariantId: 1, quantity: 1, customFields:{
    transformation:"blahb lah"
```

**Expected behavior**

This should fail the validation and therefore return an error response from the GraphQL mutation, but instead it succeeds and adds the item to the order.

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.1
 - Nodejs version: 18.12.1
 - Database (mysql/postgres etc): postgres

**Comment by sslotsky** [comment]
Also tried adding a `validate` function instead, and I still can't get it to fail validation.

**Comment by michaelbromley** [comment]
Thanks for the report & additional info. I'll take a look at fixing this in the next patch version.
