### ISSUE TITLE
expose Collection.products resolver

### ISSUE THREAD

**Issue by macrozone** [vendure-ecommerce/vendure#1954]
**Is your feature request related to a problem? Please describe.**

you can currently only fetch productVariants from a collection. This is often very counter intuitive as you want to primarly have the base product name and description of a product and then show all variants.

**Describe the solution you'd like**

Collection should expose a resolver `products`. This way the graph makes logically more sense:

```
collection 
-> products
  -> productVariants
```

**Describe alternatives you've considered**

you have to load all variants with their product and then group by product. This results in more data beeing loaded.

**Comment by michaelbromley** [comment]
Hi,

The thing is, a Collection can include only _some_ variants of a given Product, not all. 

If your use-case is building a product list page for a storefront, then the recommended approach is to use the `search` query and filter by collection id/slug, as covered here: https://www.vendure.io/docs/storefront/shop-api-guide/#listing-products

This will also be much more performant than listing via the `Collection.variants` field.

**Comment by macrozone** [comment]
thanks @michaelbromley, will try that

currently, i regroup the products locally which also works (and is fast), but i will give search a try
