### ISSUE TITLE
Can't set customer details in GraphQL playground

### ISSUE THREAD

**Issue by sslotsky** [vendure-ecommerce/vendure#1955]
**Describe the bug**

Since I don't have my frontend ready, I need to test some flows through GraphQL Playground or the admin, but I can't move past the `AddingItems` state this way. The API sends `AlreadyLoggedInError` when executing the `setCustomerForOrder` mutation, even though the `activeCustomer` query returns null. In the admin, the active order customer appears as `Guest` and I can't transition the order to "Arranging payment" from here due to lack of customer details.

**To Reproduce**

Visit the GraphQL playground for your local shop-api and add use the `addItemToOrder` mutation to add some items to an order. Then use the following query and mutation to observe the problem:

```gql
query Customer {
  activeCustomer {
    firstName
    lastName
  }
}

mutation SetCustomer {
  setCustomerForOrder(input: {
    firstName: "Bob",
    lastName: "Loblaw",
    emailAddress: "bob@loblaw.com"
  }) {
    __typename
  }
}
```

**Expected behavior**

I should be able to simulate the guest checkout process through my local GraphQL playground, or transition a guest order all the way through to the "PaymentSettled" state through the admin, but it doesn't seem possible. This would be extremely helpful for me to be able to test some custom plugin behavior that's configured to run on "PaymentSettled".

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.1
 - Nodejs version: 18.12.1
 - Database (mysql/postgres etc): postgres

**Comment by michaelbromley** [comment]
Hi,
I suspect this may be because you are logged in to the admin ui in the same browser. You can verify this by running the playground in a private tab and see if the issue persists.

**Comment by sslotsky** [comment]
> Hi, I suspect this may be because you are logged in to the admin ui in the same browser. You can verify this by running the playground in a private tab and see if the issue persists.

Aha thanks!! Always glad when it's my fault 😅
