### ISSUE TITLE
CustomField on ProductVariant is not saved

### ISSUE THREAD

**Issue by nemo-js** [vendure-ecommerce/vendure#1962]
**Describe the bug**
With a custom plugin, I add a custom field to ProductVariant. The value of the field is not persisted, neither from UI not from API

`config.customFields.ProductVariant.push({ name: 'erp_id',  type: 'string', defaultValue: '', readonly: false, nullable: true, });`

**To Reproduce**
1. Create a plugin witch extends ProductVariant with a custom field (you can use the above code)
2. Go to the product variant page
3. Enter a value to the newly created field and Save
4. Refresh, and see that field is not updated
5. Same happen if you use the graphQL mutation to create a variant

**Expected behavior**
The field should be updated from the UI and the API

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.1
 - Nodejs version 16.13.2
 - Database (mysql/postgres etc): mysql

**Comment by michaelbromley** [comment]
Hi,

I am not able to reproduce this on the current master branch:

https://user-images.githubusercontent.com/6275952/210814363-bbf6dc09-a68e-42d0-ab72-28487be06627.mp4

Can you take a look for any other factors in your project which might be influencing the behaviour you are observing?

**Comment by nemo-js** [comment]
You are right, another pre-existing plugin was causing the problem.
I am sorry for the trouble
