### ISSUE TITLE
Cannot edit facetvalues when there are thousand in a single facet 

### ISSUE THREAD

**Issue by giosueDelgado** [vendure-ecommerce/vendure#1974]
**Describe the bug**

As I write here https://github.com/vendure-ecommerce/vendure/issues/1257#issuecomment-1375261002 when you have thousand of facetvalues in a single facet is impossible to edit because it takes many time to open and also when sometimes the browser can show the page you cannot save the changes.

**Expected behavior**
It can open fast facetvalue page and can save the changes

**Environment (please complete the following information):**
 - @vendure/core version: latest
 - Nodejs version
 - Database (mysql/postgres etc):

**Additional context**

**Comment by michaelbromley** [comment]
Closing this as we have not implemented pagination in the facet detail view for values.
