### ISSUE TITLE
Database issue when logging in just before checkout

### ISSUE THREAD

**Issue by eligoe** [vendure-ecommerce/vendure#1982]
**Describe the bug**

I have an issue when logging in just before starting the checkout actions.
To reproduce:
-Add items to an anonymous cart
-Log in using authenticate mutation with a user that already has a order/cart stored.
- After being logged in, immediately call setOrderShippingAddress mutation with data fetched from our user database.
Generates error
vendure-app:dev: [run:*server] error 11/01/23, 14:02 - [Vendure Server] ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vendure`.`order_item`, CONSTRAINT `FK_69384323444206753f0cdeb64e0` FOREIGN KEY (`lineId`) REFERENCES `order_line` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)
vendure-app:dev: [run:*server] QueryFailedError: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vendure`.`order_item`, CONSTRAINT `FK_69384323444206753f0cdeb64e0` FOREIGN KEY (`lineId`) REFERENCES `order_line` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)
vendure-app:dev: [run:*server] at QueryFailedError.TypeORMError [as constructor] (/home/node_modules/.pnpm/typeorm@0.2.45/node_modules/src/error/TypeORMError.ts:7:9)
vendure-app:dev: [run:*server] at new QueryFailedError (/node_modules/.pnpm/typeorm@0.2.45/node_modules/src/error/QueryFailedError.ts:9:9)
vendure-app:dev: [run:*server] at Query.<anonymous> (/home/node_modules/.pnpm/typeorm@0.2.45/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:196:37)
vendure-app:dev: [run:*server] at Query.<anonymous> (/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
vendure-app:dev: [run:*server] at Query._callback (/home/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:488:16)
vendure-app:dev: [run:*server] at Query.Sequence.end (/home/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
vendure-app:dev: [run:*server] at Query.ErrorPacket (/home/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
vendure-app:dev: [run:*server] at Protocol._parsePacket (/home/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
vendure-app:dev: [run:*server] at Parser._parsePacket (/home/elin/emoco-mono/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
vendure-app:dev: [run:*server] at Parser.write (/home/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Pa
If I catch the error and sleep for a second and retry the setOrderShippingAddress mutation again everything works as expected. It also works as expected if I log in first then add an item and the call the setOrderShippingAddress.
It seems as my first call uses the guest order that is being deleted.

**To Reproduce**
-Add items to an anonymous cart
-Log in using authenticate mutation with a user that already has a order/cart stored.
- After being logged in, immediately call setOrderShippingAddress mutation.
- Database fk_error as above.
- Next time everything works as exptected. 

**Expected behavior**
No error and update to the proper order/cart.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.0-next.27
 - Nodejs version 16.3.1
 - Database (mysql/postgres etc): ,mysql 8.0.21

**Additional context**

**Comment by michaelbromley** [comment]
Hi,
I notice this report was made with a pre-release of v2. Is this still an issue in the current stable version?

**Comment by eligoe** [comment]
Hi,
This is not an issue anymore.  Sorry I forgot about opening this issue.
