### ISSUE TITLE
Anonymous cart after logging in with verified user

### ISSUE THREAD

**Issue by eligoe** [vendure-ecommerce/vendure#1992]
When logging in at checkout moment with an existing user that hasn’t got anything in the cart from previous sessions. This time the order remains a guest order.
To reproduce:
- Add item to an anonymous cart.
- Log in using authenticate mutation with a user that hasn’t got a previous active order / cart (in status adding items).
-  The actitve order remains a guest order.  It is illustrated with the query below.
```
{
  me {
    id
    identifier
  }
  activeOrder {
    state
    lines {
      productVariant {
        name
      }
    }
    customer {
      emailAddress
    }
  }
}

{
  "data": {
    "me": {
      "id": "97098eca-524e-4207-b72a-cf5c16a0f897",
      "identifier": "a.customer@example.com"
    },
    "activeOrder": {
      "state": "AddingItems",
      "lines": [
        {
          "productVariant": {
            "name": "Contact Sensor Actuator Cable, PUR 1m"
          }
        }
      ],
      "customer": null
    }
  }
}

```How can we get the customer to be set on the activeOrder after login?
If I register a new user at time of checkout I everything works as expected. I get a new user that is attached to the order. It also works as expected if I first login with an existing user and then add items to the order/cart and then initiate the checkout functions. The two carts are merged and the customer is attached to the order. We use default setting for mergeStrategies. To avoid the effects of the previous reported issue we have now implemented functionality to retry to set the addresses until we don’t get an error.   Possibly related to https://github.com/vendure-ecommerce/vendure/issues/1982

**Comment by jezzzm** [comment]
is this still an issue? I can't see a clear way to automatically assign the anonymous active order to a newly logged-in user.
`setOrderCustomer` mutation only exists via the admin api.

it's pretty safe to assume that if a person is logging in on the checkout page, they want the current cart to become their active order, regardless of if they have a previous active order assigned.

@michaelbromley

**Comment by michaelbromley** [comment]
@jezzzm thanks for bringing this back to my attention. I'm closing this because I'm almost certain the reported behaviour was a manifestation of this issue that was since fixed:

- https://github.com/vendure-ecommerce/vendure/issues/2097
