### ISSUE TITLE
Products remain listed in sub-channel after deleting them in default channel

### ISSUE THREAD

**Issue by seminarian** [vendure-ecommerce/vendure#1998]
**Describe the bug**
If products are assigned to a sub-channel, after removing products in the default channel they are still listed in the Admin UI in the sub-channel.

**To Reproduce**
1. Create new vendure-app
2. Populate the database with proposed seed
3. Create a new channel
4. Assign products to the new channel
5. Remove all products from the default channel
6. List products for the new channel and see they are still there
7. Removal triggers following error message
![image](https://user-images.githubusercontent.com/9881519/213698990-cf41d72e-fc08-44ca-b8ce-570a4d1258cf.png)

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.2 (admin-ui version as well)
 - Nodejs version 16.19.0
 - Database (mysql/postgres etc): SQLite

**Comment by michaelbromley** [comment]
I suspect this was related to the fact that in v1.x, the product list relied on the search index. I'm closing this but please comment if this is still an issue in the current version and we can re-open.
