### ISSUE TITLE
Yarn and NPM  "Getting Started" Error

### ISSUE THREAD

**Issue by koljam** [vendure-ecommerce/vendure#2001]
**Describe the bug**
I followed the steps described in the Getting Started Docs to install a new project. NPX works, for the other two options I get these errors:

```
yarn create @vendure vendureproject
yarn create v1.22.19
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/create-vendureproject: Not found".
```

```
npm init @vendure vendureproject
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-vendureproject - Not found
npm ERR! 404
npm ERR! 404  'create-vendureproject@*' is not in this registry.
```

**To Reproduce**
1. Follow the Steps for [Getting Started](https://www.vendure.io/docs/getting-started/)
2. Change `my-app` to something else
3. Install using npm or yarn

**Expected behavior**
A normal installation

**Environment (please complete the following information):**
yarn -v
1.22.19

npm -v
9.2.0

node -v
v18.13.0

Windows 11, Framework Laptop, Intel i7

**Additional context**
-

**Comment by 60Watts** [comment]
Try adding the version number to the other options then they should work.

Example:
`npm init @vendure@1.9.2 my-app`
`yarn create @vendure@1.9.2 my-app`

**Comment by koljam** [comment]
That would probably work. But as is the Getting Started Docs don't work and new users can't start a new project following the docs. So the docs need to get updated.

**Comment by ykatyhoney** [comment]
Getting the same issues following `yarn create @vendure my-app`

`node --version`: 16.19.0
`yarn --version`: 1.22.19
`npm -v`: 8.19.3

**Comment by michaelbromley** [comment]
Hi,

I've been unable to reproduce this issue with Yarn and npm. My system:

- Windows 11
- Node v16.15.1, also tested Node v18.13.0
- Yarn v1.22.19

```sh
❯ yarn create @vendure vendureproject
yarn create v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "@vendure/create@1.9.2" with binaries:
      - create

Welcome to @vendure/create v1.9.2!

Let's configure a new Vendure project. First a few questions:

? Which database are you using? » - Use arrow-keys. Return to submit.
>   MySQL
    MariaDB
    Postgres
    SQLite
    SQL.js
```

```sh
❯ node -v
v18.13.0
micha in temp
❯ npm init @vendure vendureproject

Welcome to @vendure/create v1.9.2!

Let's configure a new Vendure project. First a few questions:

? Which database are you using? » - Use arrow-keys. Return to submit.
>   MySQL
    MariaDB
    Postgres
    SQLite
    SQL.js
```

Could it have been a temporary network issue? Or are there any other context details that may allow me to reproduce?

**Comment by koljam** [comment]
I just tried again and it seems to be a problem with Powershell. It works well in the normal cmd.exe but when I use Powershell, I get the error above...

**Comment by dlhck** [comment]
Closed because this is already outdated and we are not supporting Yarn v1.x anymore. Please look at the docs to see the current requirements of Vendure v3.
