### ISSUE TITLE
allow worker to process tasks from http request

### ISSUE THREAD

**Issue by macrozone** [vendure-ecommerce/vendure#2007]
**Is your feature request related to a problem? Please describe.**

The default job queue polls the db which has constant load and is not desirable for "headless" deployments, as it increases costs.

There is plenty of discussion about this problem and a Google cloud task plugin emerged from this https://github.com/vendure-ecommerce/vendure/discussions/968

unfortunatly the documentation and discussion is a bit unclear. It took me some days to realize how it is supposed to work:

- vendure web services will push a task to google cloud task
- google cloud task will do a http-request to cloud-tasks/handler to invoke the work.
- this request should ideally go to a dedicated worker instance, that does not process public request as it might do cpu-bound tasks.

The documentation of that plugin is very unclear how to setup the dedicated worker instance. As it turns out by this comment https://github.com/vendure-ecommerce/vendure/discussions/968#discussioncomment-1193489 its actually not possible to setup the worker with "bootstrapWorker" as this won't answer http request, instead you have to boot it up like a normal vendure app.

**Describe the solution you'd like**

having a different entry-point for the worker is desirable. This worker instance should only process cpu-expensive (or db -intensive) work. it should not answer normal public requests (you will probably not expose it anway).

It should however be able to do work based on a http-request. This is compatible with most headless approaches. 

**Describe alternatives you've considered**

As mentioned above, you can start the worker the same way as the normal app. But documentation is unclear about that and it might break with future versions of vendure, where worker and web-service might get further separated

**Comment by michaelbromley** [comment]
Hi Marco, thanks for the suggestion!

I think this could be supported using a similar mechanism to how we do the [health check http handler](https://github.com/vendure-ecommerce/vendure/blob/fd374b3fa477dec748286eef86164f7dba4830a7/packages/core/src/worker/vendure-worker.ts#L43) on the worker.

Do you have a concrete idea of what kind of http request the worker should accept? I.e. get, post, what kind of parameters or body arguments?

Maybe @martijnvdbrug might have some opinions on this, based on his experience with Google Cloud Tasks.

**Comment by macrozone** [comment]
@michaelbromley thanks for the swift response!

the worker should handle post requests as a unit of "work" has usually some (json-) payload. sending a POST there would have the same result as if you would have the default worker with the polling db i think. It should return any answer as json.

not sure if it should send a non-200 http status code on error or have an error field (i think looking in the cloud task or other task queues documentation should reveal a good practise here)


An alternative would be that plugins like the cloud-task-plugin could register an endpoint in the worker. But I think a general "do work" endpoint on the worker is the better solution  that could work for a bunch of "serverless/cloud native" products. 

Another use case are cronjobs. If you use google cloud, there is a cloud scheduler, which could also call your worker. (there is however an alternative to that: you can also execute a "cloud run job" based on a schedule, which would invoke a specified command on your container image)

**Comment by martijnvdbrug** [comment]
I think this can be achieved by updating the Cloud Tasks plugin to support incoming requests with `bootstrapWorker` and updating the docs? 

What would be the benefit of having a dedicated `/do-work/` endpoint in Vendure core, over having an endpoint defined in the plugin?
