### ISSUE TITLE
Mollie Payment Plugin is not deducting payments already present on order (e.g. giftcards)

### ISSUE THREAD

**Issue by koljam** [vendure-ecommerce/vendure#2026]
**Describe the bug**
Payments already present on the order are not deducted from the total amount passed to mollie.

**To Reproduce**
1. Add a payment which doesnt cover the whole amount of the order
2. Add a mollie payment intent
3. See the total amount, not the amount which is left to pay

**Expected behavior**
Deduct payments already present in the order.

**Additional context**
My proposal would be to import the function `totalCoveredByPayments` and change [this line](https://github.com/vendure-ecommerce/vendure/blob/7fdd875c770eb87b6921f9780be5fb8921e61588/packages/payments-plugin/src/mollie/mollie.service.ts#L117) to
`amount: toAmount(order.totalWithTax - totalCoveredByPayments(order), order.currencyCode),`

**Comment by martijnvdbrug** [comment]
@michaelbromley this can be assigned to me :-)

**Comment by martijnvdbrug** [comment]
It's going to be a bit more complex than changing that line, as Mollie is validating the total amount against the orderlines given. So we need to know which orderLines are already paid and which still need payment.

**Comment by koljam** [comment]
Ah okay, makes sense. Originally I wanted to try a small PR but I would be happy if you could add that functionality!

**Comment by michaelbromley** [comment]
> It's going to be a bit more complex than changing that line, as Mollie is validating the total amount against the orderlines given. So we need to know which orderLines are already paid and which still need payment.

OK so this scenario came up because Kolja is using our paid Gift Cards plugin. How about a situation where the customer buys Product A ($50) and uses a $30 gift voucher, and then needs to pay the rest using credit card via Mollie. In this case, the single order line is only partially paid. Is there a way that Mollie can handle that?

**Comment by martijnvdbrug** [comment]
The easiest way would be to just add another order line with a negative amount. We [also do this for surcharges](https://github.com/vendure-ecommerce/vendure/blob/7fdd875c770eb87b6921f9780be5fb8921e61588/packages/payments-plugin/src/mollie/mollie.helpers.ts#L52), which can also be negative amounts. So, we would do something like this:
```ts
// pseudo code
lines.push({
        name: 'Already paid',
        quantity: 1,
        unitPrice: -1200,
        vatRate: ???,
        vatAmount: ???,
    });
```
What about the tax-rate of the already paid amount, can we get that somehow?

Mollie only cares about the total, not necessarily which order lines have been paid and which not. It's a bit of a workaround, but at least we can know for sure that the total's match up.

**Comment by koljam** [comment]
The taxing of gift cards seems to be a bit more complicated, at least in the EU. This may have implications on how gift cards need to be handled in Vendure, not only for the Mollie payment. This has gotten a bit long but maybe it helps someone in the future trying to understand EU regulations of gift cards (but keep in mind I am not a tax lawyer!).

In the [Mollie Docs](https://docs.mollie.com/orders/handling-discounts) they suggest adding a line with 0 VAT and there is also this bit: 

> As a gift card is simply a means of payment and is untaxed, this does not affect the VAT amount charged to your customer.

**But this is not true for the EU anymore, which had new regulations in 2019.** I have been diving in the rabbit hole for the last few hours and this is what I found:

There are two types of vouchers: single-purpose vouchers and multi-purpose vouchers.

### Single-Purpose vouchers

In the context of VAT, single-purpose vouchers are treated differently from multi-purpose vouchers. When a single-purpose voucher is purchased, VAT is charged at the time of purchase, even though the voucher may not be redeemed immediately. This ensures that the VAT is paid up front, regardless of when the voucher is actually used.

When a gift card is redeemed, the total purchase amount is decreased by the value of the gift card. Since the gift card already includes VAT at the same rate as the products, both the tax and the total amount without tax are reduced by the amount that was paid upfront at the time of purchasing the gift card.

Example:
- Tom buys a giftcard for 100€. 20€ are included as tax (20%).
- Tom buys a chair for 300€ and uses his 100€ giftcard. He expects to pay 200€
- We add a line item for -100€ and -20€ tax. The total is 200€ including 40€ VAT
- In total we pay 20€ + 40€ = 60€ Tax to the government, which is 20% of 300€ for the chair.

### Multi-purpose vouchers

These are sold without tax, because we do not know the VAT rate on the items that will be purchased later on. This can be the case when you sell items with reduced VAT such as food or books, or if you operate across borders.

In this case we need to pay the whole tax when the gift card is redeemed. In practice we add a line item which a negative amount without any tax. The total is reduced, the tax amount stays the same.

Example:
- Tom buys a giftcard for 100€. No tax is applied.
- Tom buys a chair for 300€ and uses his 100€ giftcard. He expects to pay 200€
- We add a line item for -100€ and 0€ tax. The total is 200€ including 60€ VAT
- In total we pay 60€ tax to the government, which is 20% of 300€ for the chair. This also works with multiple different tax rates.

When gift cards expire, we probably don't need to pay the missing tax. But I found some conflicting info on that.

### What this means for Vendure

Multi-purpose vouchers should work with the current implementation. They are similar to how gift cards used to be handled: a form of (down-)payment. Single-Purpose vouchers on the other hand come with more problems:

[There is a really lengthy discussion over at Shopify regarding this issue](https://community.shopify.com/c/accounting-and-taxes/gift-cards-and-new-eu-vat-regulations/td-p/583703). They don't seem to handle single-Purpose vouchers yet.

**When using gift cards as a payment method, the total tax amount doesn't get reduced. And since we already paid tax when the customer bought the gift card, be end up paying tax twice.**

I think the best option would be to handle gift cards by adding them as a special line item, which has a tax rate (the same tax rate, that has been used for buying the gift card). By setting the tax rate for the gift card you decide between single-purpose vouchers and multi-purpose vouchers. Multi-purpose would probably be the way to go for people outside the EU.

Why we don't all use multi-purpose gift cards? Because it's the law I guess...

**Comment by koljam** [comment]
Hello there! I am currently in the process of releasing my shop, but this issue is holding me back a little. My suggestion is as follows:

@martijnvdbrug, would it be possible for you to add the payments made on the order as a line item with zero tax? I believe this would be sufficient for handling all multi-purpose vouchers. That should also handle things like down-payments since they also don't have a tax rate.

@michaelbromley, I will open a new issue for the gift-card plugin with a feature request for supporting EU single-purpose vouchers. When launching the shop I will disable the purchase of new giftcards, but with the additions in the mollie plugin, I should be able to accept existing giftcards.

Does this plan sound reasonable to you?

**Comment by martijnvdbrug** [comment]
@koljam That sounds reasonable to me. I will try and get to it next week

**Comment by michaelbromley** [comment]
It is quite likely there will be a patch before v2, so PR against master :)

**Comment by martijnvdbrug** [comment]
@koljam there is a PR ready, maybe you would also like to take a look? https://github.com/vendure-ecommerce/vendure/pull/2075
