### ISSUE TITLE
add dev-config.ts do .gitingnore

### ISSUE THREAD

**Issue by maurosergiosilva** [vendure-ecommerce/vendure#203]
**Is your feature request related to a problem? Please describe.**
When you wotk in forks, you will have yor own dev-config.ts, so its better has commited just a dev-config.ts.example insteand change dev-config.ts;
Add dev-config.ts to .gitignore and commint dev-config.ts.example;

**Comment by michaelbromley** [comment]
Not sure that I agree with this. How would this workflow be superior to creating a copy of dev-config.ts and pointing your index.ts and index-worker.ts files to it?

**Comment by maurosergiosilva** [comment]
Hi @michaelbromley , what I mean is about commit dev-config.ts with other name and ignore real config, just to avoid changes on it be reflected in pull requests.  
Other alternative is make same values came from .env.example files and be populated acording enviroments, like key-values secretes from CI-CD. Usualy when you work with .env files, you commit some .env.example just to show how .env should be, and .env are ignored using .gitignore.

**Comment by michaelbromley** [comment]
Couldn't you just not commit any changes you make to dev-config.ts? That's what I do.

I'm open to a pull request which implements some better way of doing things though!

**Comment by maurosergiosilva** [comment]
Yep, I will do these way.
Thanks @michaelbromley .
