### ISSUE TITLE
EmailPlugin: Allow Email SMTP settings per channel

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#2043]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have different SMTP settings per channel, preferably stored in the database, so that administrators can configure their own mail server.

**Describe the solution you'd like**
My initial thought is to transform the `transport` property in the `EmailPlugin.init()` to a function, so that developers can dictate where SMTP settings are coming from:
```ts
    EmailPlugin.init({
      transport: async (ctx) => {

        // Get your SMTP settings based on the requestContext
        const settings = await myService.getSmtpSettings(ctx);

          return {
            type: 'smtp',
            host: settings.host,
            port: settings.port,
            auth: {
              user: settings.user,
              pass: settings.password,
            }
          }
          ...
    })
```
This way we can, for example, get SMTP config stored on custom fields on a Channel

**Describe alternatives you've considered**
I am currently using a transactional mail service, that also enables me to send emails from different domains with a single SMTP connection, which works fine, but all channels are forced to use the same transactional email service.

I would like to hear your thoughts on this. Is this something that should be included in Vendure, or is this a use case for a separate plugin?

## Additional context
The process function is already async, so it shouldn't be to hard to resolve transport settings here: https://github.com/vendure-ecommerce/vendure/blob/7b0fae1bda1238d5022178ea4e7729085ead318a/packages/email-plugin/src/email-processor.ts#L77

**Comment by martijnvdbrug** [comment]
For future reference @is0utfitters

**Comment by michaelbromley** [comment]
Yes this proposal seems reasonable. We would also need to expose an `injector` instance so that you can inject your services into the method.

**Comment by martijnvdbrug** [comment]
Thanks for the response, can you assign this to me?
