### ISSUE TITLE
🔍 Add a search field for the admin panel

### ISSUE THREAD

**Issue by gdarchen** [vendure-ecommerce/vendure#2048]
**Is your feature request related to a problem? Please describe.**
In the `Dashboard` > `Administrators` page, when we have a lot of administrators, we have to browse every page to find some admin user.

**Describe the solution you'd like**
It would be really great to have a search field enabling to search for an admin on the following fields:
- `First name`
- `Last name`
- `Email address`

**Describe alternatives you've considered**
🤷‍♂️

**Additional context**

The search field could be displayed on the left of the primary button enabling to add a new administrator.

![Capture d’écran 2022-09-12 à 10](https://user-images.githubusercontent.com/17927632/220671700-10d64bbd-d112-44b7-9194-14f591b040f4.png)

**Comment by michaelbromley** [comment]
Hi,

Agreed, this is a missing feature and not hard to implement either. Would you be interested in attempting to implement this?

**Comment by Mizan3050** [comment]
> 

can you assign this to me?

**Comment by Mizan3050** [comment]
hi @michaelbromley I am adding a placeholder to the search input, my question is, do I have to update the json file for all the languages?

**Comment by michaelbromley** [comment]
Do English and any that you are able to (you could try ChatGPT for this). If only English that's also ok.
