### ISSUE TITLE
Add `ESM` support for typeorm Entity with `relation` 

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#2057]
**Describe the bug**
When you make a project in ESM, and have entities with a "one to many/many to one" relationship, the typeorm throws an error. This error doesn't occurs if you change the project type to a CommonJS (in "package.json" and "tsconfig.json").

 in your `tsconfig.json file`, set:
```
"module": "ESNext",
"moduleResolution": "node"

```

In `package.json` set
```
"type": "module"
```

In ESM, we must use the type Relation<T> when you declare a relationship (not required in CommonJS). Using this example:

`user.ts`

```ts
import { Entity, PrimaryGeneratedColumn, Column, BaseEntity, ManyToOne, Relation } from "typeorm";
import { UserType } from './user-type.js';

@Entity({ name: 'User' })
export class User extends BaseEntity {
    @PrimaryGeneratedColumn({ type: 'int' })
    id!: number

    @Column({ type: 'varchar', length: 20 })
    nick!: string;

    @Column({ type: 'varchar', length: 64 })
    pass!: string;

    @ManyToOne(() => UserType, r => r.users)
    userType!: Relation<UserType>;
}
```

`user-type.ts`

```ts
import { BaseEntity, Column, Entity, OneToMany, PrimaryGeneratedColumn, Relation } from 'typeorm';
import { User } from './user.js';

@Entity({ name: 'UserType' })
export class UserType extends BaseEntity {
    @PrimaryGeneratedColumn({ type: 'tinyint' })
    id!: number;

    @Column({ type: 'varchar', length: 20 })
    cod!: string;

    @Column({ type: 'varchar', length: 100 })
    desc!: string;

    @OneToMany(() => User, r => r.userType)
    users!: Relation<User[]>;
}

```

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 1.93
 - Nodejs version: 18
 - Database (mysql/postgres etc): mysql

**Additional context**

https://github.com/typeorm/typeorm/issues/9117
https://typeorm.io/faq#how-to-use-typeorm-in-esm-projects

**Comment by michaelbromley** [comment]
Hi,

I'm closing this because it's not really a bug in Vendure, but more of a docs issue related to TypeORM. Thanks for reporting and documenting the solution.
