### ISSUE TITLE
Unable to login to venture demo

### ISSUE THREAD

**Issue by Stefanyshyn** [vendure-ecommerce/vendure#2061]
**Describe the bug**
I got an error after clicking on the login button

<img src="https://i.ibb.co/4gV6qN2/image.png"  width="400">

**To Reproduce**
1. Go to [login page of Venture demo](https://demo.vendure.io/admin/login)
2. Enter default credentials
3. Click on the login button
4. See an error

**Comment by michaelbromley** [comment]
Thanks for the report. The demo has been re-deployed (it gets re-created every night anyway) and should be working now.

**Comment by Cheizr** [comment]
Not working :(
