### ISSUE TITLE
Best approach for Compare at Price

### ISSUE THREAD

**Issue by promisetochi** [vendure-ecommerce/vendure#2063]
**Is your feature request related to a problem? Please describe.**
Shopify has a `Compare at price` feature that causes a discount to be shown on the storefront for a product variant. For example, the product below will show up as having a 20% discount

<img width="409" alt="image" src="https://user-images.githubusercontent.com/20524675/222591170-0e0c3c3e-b9bf-42bc-b867-aba290fa527b.png">

**Describe the solution you'd like**
I'm more of soliciting the best approach to this problem since it doesn't seem to be supported out-of-the-box.

**Describe alternatives you've considered**
Would creating a `compareAtPrice` custom field on `ProductVariant` be a good approach to solving this problem?

**Additional context**

**Comment by michaelbromley** [comment]
Hi,
Yes, a custom field on ProductVariant is a good way to implement this 👍
