### ISSUE TITLE
Docs: Include supported TS versions for Admin UI compilation

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#2067]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when admin UI compilation fails with obscure errors, it's a reason to avoid admin UI customization for me. But, usually it's a dependency/version mismatch between angular and typescript. I feel like this could be easily prevented by adding supported version to the docs.

(Note to self: the [plugin-template](https://github.com/vendure-ecommerce/plugin-template) should include the latest supported TS version)

**Describe the solution you'd like**
It would be great to include the supported Typescript version in the Vendure docs: https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3

**Describe alternatives you've considered**
Stick with an old TS version so I know it works with Vendure's UI devkit

**Additional context**
[Add any other context or screenshots about the feature request here.](https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1678101626784699)

**Comment by michaelbromley** [comment]
It is in the docs: 
<img width="681" alt="image" src="https://user-images.githubusercontent.com/6275952/223102359-8e1d9b81-cbeb-4ff8-8a28-f029ea15d8c8.png">

But could of course be made more discoverable. How would you propose we present it?

**Comment by martijnvdbrug** [comment]
Oops, missed that one. Maybe we can add it to this page as well: https://www.vendure.io/docs/plugins/extending-the-admin-ui/ and include the version numer, instead of only a link.

Even better would be to log something like `Can not compile admin UI because you use TS 4.5.3` during compilation, but I am not sure how feasible that is.
