### ISSUE TITLE
Allow us customized to write value as customFields to session

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#2069]
**Is your feature request related to a problem? Please describe.**

Is there a way to add an customField  like `locale` to  the table `session`

**Describe the solution you'd like**
allow us customized to write `value` as `customFields` to `session`
e.g. i want to get `languageCode` from `ctx` and store on the `session` to statistic How many sessions come from where?

**Describe alternatives you've considered**
1. add `hook` allow us get `ctx` to  merge an  value to customFields(`locale`) to `Session`.
2. Allow us defined custom Fields `locale`

**Additional context**

**Comment by michaelbromley** [comment]
Custom field support will be added to Session as part of #3044
