### ISSUE TITLE
CI: Set up testing for all supported databases

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#207]
Currently in CI we run e2e tests against sql.js (SQLite). Generally, due to the use of the TypeORM layer, this means that things should work fine in the other supported database, namely mysql & postgres.

However, there *is* some DB-specific code (e.g. in the DefaultSearchPlugin) which has caused a couple of issues by being untested (e.g. #206).

It would be better to run all e2e tests against each database. This would require some re-working on the `@vendure/testing` package to allow other DBs to be used.

**Comment by rrubio** [comment]
@michaelbromley thank you, really appreciate it. In the meantime, is there anything i can do on my side to get rid of this error? https://github.com/vendure-ecommerce/vendure/issues/206

**Comment by michaelbromley** [comment]
@rrubio I'll release a patch (v0.6.1) today that includes the fix for that.

**Comment by rrubio** [comment]
@michaelbromley you rock! thank you man!

**Comment by rrubio** [comment]
AWESOME!!!! thank you so much!
