### ISSUE TITLE
Add the injector on elastichsearch plugin for custom mapping fields

### ISSUE THREAD

**Issue by giosueDelgado** [vendure-ecommerce/vendure#2076]
**Is your feature request related to a problem? Please describe.**
As talked on slack we need to use some services to calculate the custom mapping fields (on product and also variants)
So we need the injector in this point of code.

**Comment by giosueDelgado** [comment]
I try to clean the commits from other for the MR

**Comment by giosueDelgado** [comment]
New PR #2256

**Comment by giosueDelgado** [comment]
@michaelbromley I create a new pr on this, let me know as soon it can be merge, for us is very important!
Thanks

**Comment by michaelbromley** [comment]
Thanks, this is merged in `minor` now and will be in the next minor release (no date yet set on that).
