### ISSUE TITLE
Update S3 client library

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#2080]
**Is your feature request related to a problem? Please describe.**
When using the S3 strategy for asset storage, we are currently integrated with `aws-sdk` v2.0. This is going into maintenance mode and there is a new v3 available that we should move to.

**Describe the solution you'd like**
For Vendure v2 we should update the dependency and make the strategy compatible with the v3 sdk only. See https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md

**Comment by asonnleitner** [comment]
I've already done this implementation for our vendure, but it has the @aws-sdk/client-s3 as dependency. So the init function is different. Could also refactor to match the current implementation if you would like.

**Comment by michaelbromley** [comment]
Hi @asonnleitner, do you mean you'd be willing to make a PR with these changes? If so, yes I would welcome that.

**Comment by michaelbromley** [comment]
PR:

- https://github.com/vendure-ecommerce/vendure/pull/2102
