### ISSUE TITLE
Order filtreing in Custom Tab not working as it should

### ISSUE THREAD

**Issue by dalyathan** [vendure-ecommerce/vendure#2087]
**Describe the bug**
The custom tab in Order list allows the filtering of orders with the time of the placing of an order and the state of the order. When the AddingItems state filter is combined with the date filters it doesn't work. 

**To Reproduce**
1. Go to Order List page under Sales section of the side nav
2. Click on 'Custom' tab
3. Select 'Adding items' from the state dropdown.
4. Select a duration of date where one or more orders (if any) appear.
5. Now enter those dates into the 'Place at-from' and 'Placed at-Until' section.
6. You should see an empty list.

**Comment by michaelbromley** [comment]
This issue relates to a version of Vendure that is no longer supported. If the issue persists in the latest version, please open a new issue.
