### ISSUE TITLE
Cannot login with superamdin on adminUi

### ISSUE THREAD

**Issue by getwebM** [vendure-ecommerce/vendure#2089]
**Describe the bug**
After login with credentials from .env an error banner displays with following message:

**To Reproduce**
1. Go to '(http://localhost:3000/admin)'
2. Fill Loginform an click on login'

**Expected behavior**
Display Admin Dashboard

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.3
 - Nodejs version: 16.13.0
 - Database (mysql/postgres etc): 10.5.18-MariaDB

**Additional context**
It works with a fresh install.

**Comment by getwebM** [comment]
![image](https://user-images.githubusercontent.com/53661314/226560400-6e2e4cff-b527-4ffc-9b85-8f75f4a4d5cc.png)

**Comment by getwebM** [comment]
Unfortunately, I was no longer able to fully reproduce my changes.

**Comment by michaelbromley** [comment]
Alright, I'll close this issue then. If you run into it again and can provide some instructions to reproduce, please comment.
