### ISSUE TITLE
Absolute URL's for S3 + pre-generated sizes

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#2101]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could use the S3 asset plugin, and also leverage the CDN capabilities of S3. Currently the plugin routes all assets through the Vendure server.

**Describe the solution you'd like**
I would like to be able to configure the S3 plugin to use absolute URL's to S3 buckets. When we use absolute URL's it would also be nice to set some sizes that will be pregenerated, because we will not use the Asset Server anymore in this setup:

```ts
 storageStrategyFactory: configureS3AssetStorage({
      bucket: 'my-s3-bucket',
      credentials: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
      },
      useCdnUrls: true,
      pregeneratedSizes: [
         {
            name: "thumbnail",
            width: 500,
            height: 500,
            format: "webp"
         }
      ]
    }),
```
This would then add `thumbnail` to all Asset Fields

**Describe alternatives you've considered**
-

**Additional context**
The google cloud asset storage plugin does something similar: https://github.com/Pinelab-studio/pinelab-vendure-plugins/tree/master/packages/vendure-plugin-google-storage-assets

**Comment by StampixSMO** [comment]
Would also like to see this, how do you view the integration with the CDN itself (CloudFront)? I.e. which host to point to.

Additionally, I'm kind of assuming that the `thumbnail` pregenerated size would be the responsibility of the implementer then? Since AFAIK S3 does not have that functionality built-in.

**Comment by martijnvdbrug** [comment]
Good question, the Google storage plugin constructs the url by prefixing it with 'storage.apis...'. i would expect something similar for this implementation.

Pregeneration should indeed be handled by the S3 implementation

**Comment by StampixSMO** [comment]
S3 itself does not have a CDN, you need to set up a CloudFront distribution and point it to the S3 bucket. That CF distribution can have any domain you want, so somehow this will need to be configured in this strategy (perfectly fine).

**Comment by dlhck** [comment]
@martijnvdbrug S3 does not have any CDN capabilities. These are provided by AWS CloudFront. Pre-generation would need to happen through Vendure, this could be done through a new feature called "Scheduled Tasks" that we are currently looking at.

**Comment by martijnvdbrug** [comment]
> @martijnvdbrug S3 does not have any CDN capabilities. These are provided by AWS CloudFront. Pre-generation would need to happen through Vendure, this could be done through a new feature called "Scheduled Tasks" that we are currently looking at.

I am also rethinking the pregeneration for the Google Storage Plugin. So far I've come up with:

* Allow passing pregeneration settings into the plugin. Something like `pregenerate: [{thumbnail, original size, webp}, {square, 200 x 200, webp}]`
* Listen to AssetEvents: When an asset is created, pregenerate the sizes in via the worker and store in DB on asset.customFields
* Resolver checks asset.customFields, and returns additional pre-rendered sizes
* Absolute URL should also be configurable, as Google Storage also allows custom domains. Something like `constructAbsoluteUrl: (ctx, asset) => string`

**Comment by martijnvdbrug** [comment]
Anyhow, since it's not as easy as I thought with S3 as with Google Storage, I will close this one.
