### ISSUE TITLE
Memory error in BullMQ plugin queue 

### ISSUE THREAD

**Issue by giosueDelgado** [vendure-ecommerce/vendure#2109]
**Describe the bug**
The job are never removed also the completed one. This issue cause that in redis where is all stored in memory to complete use the memory the istance and block the application

The usage of bullmq plugin is suggested to use in production but if is used it block the application if the job are not flushed in some applicative way.

**Expected behavior**
When completed it can be removed automatycally or maybe configured the behavior in the option of the plugin

**Comment by michaelbromley** [comment]
In the latest versions we make use of the automatic removal of old jobs: https://docs.vendure.io/reference/core-plugins/job-queue-plugin/bull-mqjob-queue-plugin#removing-old-jobs
