### ISSUE TITLE
v1.9.5 - Shipping eligibility checker showing incorrect language

### ISSUE THREAD

**Issue by cl2898** [vendure-ecommerce/vendure#2118]
**Describe the bug**
Vendure v1.9.5, in "Shipping methods" module, "Shipping eligibility checker" showing in the list using the selected translation language (Traditional Chinese), instead of my admin ui selected language (English).

**To Reproduce**
![image](https://user-images.githubusercontent.com/2128048/231153218-e8dbdd02-638d-4c58-b178-a6c2f2098e67.png)

**Expected behavior**
Should show admin ui selected language.

**Environment (please complete the following information):**
 - @vendure/core version: v1.9.5
 - Nodejs version: v16.19.1
 - Database (mysql/postgres etc): mysql

**Comment by michaelbromley** [comment]
This issue relates to a version of Vendure that is no longer supported. If the issue persists in the latest version, please open a new issue.
