### ISSUE TITLE
 Product does not exist

### ISSUE THREAD

**Issue by rcorzogutierrez** [vendure-ecommerce/vendure#212]
It is very common for customers to share product links but sometimes it does not exist or is not available. It would be advisable that in these cases you will be redirected to a page of related products or categories and with their respective alternative text (Sorry .... bla bla). It also applies to some cases of completed promotions.

An admin could decide on the action to be taken through a section that allowed to add a link (landing page, etc) or select different redirection options (Categories, Related Products, etc). 

When a product is created, it must have a default action and if necessary, modify

**Comment by michaelbromley** [comment]
Hi, thanks for the suggestion. Here are my thoughts:

**Use-case: product does not exist**
If a bad link is shared, e.g `www.my-shop.com/products/bad-slug`, then the GraphQL query to `product(slug: "bad-slug")` will return `null`. 

In this case this is an entirely front-end (storefront app) concern which can be handled however you wish in your own storefront implementation. 

**Use-case: product not available**
I am not sure what exactly is meant by "not available" here. One meaning could be that all of the ProductVariants have no stock (note that currently the `stockOnHand` of a ProductVariant is not exposed via the Shop API).

Again, in this case I feel that it is a concern of the storefront app how to handle this.

My suggestion would be to add a custom field to the Product which allows the administrator to specify which action to take. The storefront app could then use this as a basis for how to handle.

**Comment by rcorzogutierrez** [comment]
Hi

When there is no existence of a product or the promotion is over, the storefront has no way of knowing what category that product was. The central idea is not to lose that intention of buying from the customer and always show some alternative closer to their expectations.

Thank

**Comment by michaelbromley** [comment]
> When there is no existence of a product or the promotion is over, the storefront has no way of knowing what category that product was

Yes, that makes sense. But by the same token, how would the storefront be able to lookup the correct redirect, if that is a property of the Product itself (which cannot be found)?

I think what this feature request is lacking is a concrete and exact description of the desired workflow, i.e. what specific sequence of GraphQL requests and responses would fulfil the requirement you have in mind.

If you can supply that (can be pseudo-code or just a bullet list of steps) then I can consider the idea more clearly.

**Comment by rcorzogutierrez** [comment]
> how would the storefront be able to lookup the correct redirect, if that is a property of the Product itself (which cannot be found)?

If the product in question existed at some time, the return should not be a bad link. You should return a query that includes the id of the category to which it belonged and in this way a list of related products is built from the storefrom

**Comment by michaelbromley** [comment]
Thanks for the clarification. Currently, there are 2 states that may be considered "unavailable" - `deleted` and `disabled`. With both of those, the product will not be found (the query will return `null` in the Shop API).

So you are describing a new state for the Product type which does not yet exist. It is available in that it is still returned from the query, but it is unavailable in that it can no longer be purchased.

You can quite trivially implement such a state yourself using CustomFields:
```ts
const config: VendureConfig = {
  // ...
  customFields: {
    Product: [
      {
        name: 'available',
        type: 'boolean',
        defaultValue: true,
      }
    ],
  }
}
```

Then in your storefront you can query:
```SDL
query {
  product(id: 123) {
    id
    collections {
      id
      name
    }
    customFields {
      available
    }
  }
}
```

And when you find that `available` is set to `false`, then you can e.g. redirect to one of the collections in which that Product appears. You could use a further custom field if you like to e.g. specify a specific  url to redirect to or whatever.
