### ISSUE TITLE
Add slide of image in the admin-ui panel

### ISSUE THREAD

**Issue by giosueDelgado** [vendure-ecommerce/vendure#2129]
**Is your feature request related to a problem? Please describe.**

We want to add a "<" and ">" when an image is opened in the admin-ui product page.

For example:

<img width="956" alt="image" src="https://user-images.githubusercontent.com/11545723/232731784-ff1fa3ad-e118-4a7d-b754-ba0176a37589.png">

**Describe the solution you'd like**

When click on < or > go in the next or previus image of the product.
This also for product and variant.

**Comment by michaelbromley** [comment]
This is a good suggestion! I will see if I have time to work this into the Admin UI refresh I am doing for v2.

**Comment by Mizan3050** [comment]
I can do this, let me know if there is any library that I can use to implement slide. Or is there anything existing component being used for slide.

**Comment by giosueDelgado** [comment]
Hi guys, can we give more attention to this point?

**Comment by giosueDelgado** [comment]
I see that clarity design not have a slider but maybe @michaelbromley do some component in other section that we can use.

**Comment by michaelbromley** [comment]
Hi, sorry for the lack of reply on this. I didn't get time to implement myself and no, there is no existing ui component which already does this. It would need to be created.

If we do this, it makes sense to generalize the solution to any place where we have a number of assets which can be opened in the dialog. So:

- product detail view
- product variant detail view
- collection detail view
- asset list view

This would involve modifying the [AssetPreviewDialogComponent](https://github.com/vendure-ecommerce/vendure/blob/f3b5fa873d779af04dc35f7ae97b6ac9471e977f/packages/admin-ui/src/lib/core/src/shared/components/asset-preview-dialog/asset-preview-dialog.component.ts#L31) to allow it to take an array of assets.

@Mizan3050 let me know if you are still interested in having a go at this, or anyone else for that matter.

**Comment by Mizan3050** [comment]
Yes, I can work on this.

**Comment by giosueDelgado** [comment]
Cool! @Mizan3050  Thanks for your support!!

**Comment by Mizan3050** [comment]
@michaelbromley Hii, sorry for the delay. I have raised a PR for this feature. Please review it and let me know if I can improve it.
