### ISSUE TITLE
Making docs more starter friendly

### ISSUE THREAD

**Issue by Mikaayel** [vendure-ecommerce/vendure#214]
**Is your feature request related to a problem? Please describe.**
As a new user of vendure I found it a little difficult to get started with the docs. I think the docs could do with more clear examples of which api might be used when for generic features such as showing historical orders for example.

The creation of a new plugin was more challenging and I found it difficult to understand what I needed to do from the example.

**Describe the solution you'd like**
Perhaps a flow chart of which graphql query would be used at which point of customer journey assuming a generic store layout perhaps? This might help people new to the project digest the organisation and layout quicker.

**Comment by michaelbromley** [comment]
As a start, I've added a new section to the docs with a guide to the common GraphQL API operations: https://www.vendure.io/docs/developer-guide/graphql-api-guide/

I also added some more examples to the Plugins page: https://www.vendure.io/docs/developer-guide/plugins/ as well as links to the real-world-vendure repo which demonstrates the various plugin configurations.

Let me know your feedback!
