### ISSUE TITLE
Where can I find the storefront demo for Next.js?

### ISSUE THREAD

**Issue by YogeshUmeshVaity** [vendure-ecommerce/vendure#2144]
[In this documentation page](https://www.vendure.io/docs/storefront/building-a-storefront/), it's mentioned that vendure offers integrations with popular front-end frameworks such as Next.js, Vue Storefront, Remix & Angular. When I click this [integrations link](https://www.vendure.io/integration/), I can see only Vue Storefront, Remix, Qwik & Angular. Next.js seems missing. Searching Github for Vendure and Next.js doesn't give me any great results either.

**Comment by michaelbromley** [comment]
Please see this recent announcement by vercel: https://github.com/vercel/commerce/pull/966

I'll remove the reference from the docs to avoid confusion.

**Comment by YogeshUmeshVaity** [comment]
Thanks for the update, @michaelbromley. It's unfortunate that Next.js Commerce dropped support for provider agnostic starter. I was really looking forward to get a project started quickly with the combo of Next.js + Vendure.

I'll be checking back again in the future. It would be great if Vendure decides to build their own Next.js starter kit tailored to their APIs, just like they have done with the Angular and Vue Storefront. Otherwise, I'll have to learn Angular but there are not as many beautiful Angular projects as there are Next.js projects on Github to learn and take inspiration from.
