### ISSUE TITLE
 I want to hide custom fields but keep them in database. I can't hide it on AdminUI

### ISSUE THREAD

**Issue by ducphat9928** [vendure-ecommerce/vendure#2145]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/126433525/234174732-d14ce9e2-5459-4cf3-a3d0-ca1ad0ea765b.png">

**Comment by michaelbromley** [comment]
Hi,
You can set it to `internal: true` and it won't be exposed via the APIs nor in the Admin UI. Is that workable for you? https://www.vendure.io/docs/developer-guide/customizing-models/#public-readonly--internal
