### ISSUE TITLE
Running Development Install README Instructions Fails

### ISSUE THREAD

**Issue by dylviz** [vendure-ecommerce/vendure#2163]
**Describe the bug**
The main top-level README describes steps that should be followed to:
1. `yarn`
2. `yarn bootstrap`
3. `yarn build`
4.  
```
cd packages/dev-server/
DB=<mysql|postgres|sqlite> yarn populate

``` 
5.
```
cd packages/dev-server
DB=<mysql|postgres|sqlite> yarn start
```

But fails with large error at step 3:
```
vendure $yarn build
yarn run v1.22.19
$ lerna run build
lerna notice cli v4.0.0
lerna info Executing command in 13 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@vendure/common' in 3.8s:
$ rimraf lib && tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/core' in 35.8s:
$ rimraf dist && tsc -p ./build/tsconfig.build.json && tsc -p ./build/tsconfig.cli.json && gulp -f ./build/gulpfile.ts build
[14:34:03] Requiring external module ts-node/register
[14:34:03] Working directory changed to ~/vendure/packages/core/build
[14:34:06] Using gulpfile ~/vendure/packages/core/build/gulpfile.ts
[14:34:06] Starting 'build'...
[14:34:06] Starting 'copySchemas'...
[14:34:06] Starting 'copyI18nMessages'...
[14:34:06] Finished 'copyI18nMessages' after 286 ms
[14:34:06] Finished 'copySchemas' after 384 ms
[14:34:06] Finished 'build' after 386 ms
lerna info run Ran npm script 'build' in '@vendure/create' in 24.8s:
$ yarn copy-assets && rimraf lib && tsc -p ./tsconfig.build.json
$ rimraf assets && ts-node ./build.ts
lerna info run Ran npm script 'build' in '@vendure/asset-server-plugin' in 28.4s:
$ rimraf lib && tsc -p ./tsconfig.build.json && node build.js
lerna info run Ran npm script 'build' in '@vendure/elasticsearch-plugin' in 22.9s:
$ rimraf lib && tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/email-plugin' in 19.9s:
$ rimraf lib && tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/harden-plugin' in 20.2s:
$ rimraf lib && tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/job-queue-plugin' in 24.8s:
$ rimraf package && tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/testing' in 14.4s:
$ tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/payments-plugin' in 13.4s:
$ rimraf package && tsc -p ./tsconfig.build.json
lerna ERR! yarn run build exited 1 in '@vendure/admin-ui-plugin'
lerna ERR! yarn run build stdout:
$ rimraf lib && node -r ts-node/register build.ts && yarn compile
Building admin-ui from source...
$ yarn ng build --configuration production
$ ng build --configuration production
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Could not build!
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
Warning: Support was requested for IE 11 in the project's browserslist configuration. IE 11 support is deprecated since Angular v12.
For more information, see https://angular.io/guide/browser-support
- Generating browser application bundles (phase: setup)...
Warning: Entry point '@clr/angular' contains deep imports into '/home/dylan/vendure/node_modules/@cds/core/icon', '/home/dylan/vendure/node_modules/@cds/core/icon/register'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @ngx-translate/core : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling apollo-angular : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling ngx-translate-messageformat-compiler : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling ngx-pagination : module as esm5
Compiling @angular/cdk/drag-drop : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015
Compiling @clr/angular : es2015 as esm2015
Compiling @ng-select/ng-select : es2015 as esm2015

Compiling @biesbjerg/ngx-translate-extract-marker : es2015 as esm2015
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/dylan/vendure/packages/admin-ui/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/dylan/vendure/packages/admin-ui/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/home/dylan/vendure/packages/admin-ui/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:70:8)
    at NormalModule._initBuildHash (/home/dylan/vendure/packages/admin-ui/node_modules/webpack/lib/NormalModule.js:880:17)
    at handleParseResult (/home/dylan/vendure/packages/admin-ui/node_modules/webpack/lib/NormalModule.js:946:10)
    at /home/dylan/vendure/packages/admin-ui/node_modules/webpack/lib/NormalModule.js:1040:4
    at processResult (/home/dylan/vendure/packages/admin-ui/node_modules/webpack/lib/NormalModule.js:755:11)
    at /home/dylan/vendure/packages/admin-ui/node_modules/webpack/lib/NormalModule.js:819:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
error Command failed with exit code 1.
error Command failed with exit code 1.
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@vendure/admin-ui-plugin'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
```

**To Reproduce**
1. Go to clone repo
5. cd into repo
6. `yarn`
7. `yarn bootstrap`
8. `yarn build`

**Expected behavior**
Builds without error

**Environment (please complete the following information):**
 - Everything is default/unchanged from cloned repo

**Additional context**
while running `yarn bootstrap`, I get the following:
```
vendure $yarn bootstrap
yarn run v1.22.19
$ lerna bootstrap
lerna notice cli v4.0.0
lerna info bootstrap root only
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "npm-packlist@1.1.12" is incompatible with requested version "npm-packlist@^2.1.4"
warning Resolution field "npm-packlist@1.1.12" is incompatible with requested version "npm-packlist@^2.1.4"
warning Resolution field "npm-packlist@1.1.12" is incompatible with requested version "npm-packlist@^3.0.0"
success Already up-to-date.
Done in 2.46s.
```

Not sure if that's normal. There's also a few unmet dependencies during the `yarn` install. Might be expected though.

**Comment by dylviz** [comment]
Linking a similar issue:
https://github.com/vendure-ecommerce/vendure/issues/1400#issue-1125690339

White space in path doesn't appear to be the problem in my case.

**Comment by denz93** [comment]
I run into this issue before and it maybe caused by some dependencies related to Webpack using MD4 hash algorithm.

Quick fix:
`NODE_OPTIONS=--openssl-legacy-provider yarn build`

**Comment by dylviz** [comment]
> @dylviz I run into this issue before and it maybe caused by some dependencies related to Webpack that using MD4 hash algorithm.
> 
> Quick fix: `NODE_OPTIONS=--openssl-legacy-provider yarn build`

Unfortunately, this makes a different error appear:
```
vendure $NODE_OPTIONS=--openssl-legacy-provider yarn build
yarn run v1.22.19
$ lerna run build
lerna notice cli v4.0.0
lerna info Executing command in 13 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@vendure/common' in 3.9s:
$ rimraf lib && tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/core' in 41.8s:
$ rimraf dist && tsc -p ./build/tsconfig.build.json && tsc -p ./build/tsconfig.cli.json && gulp -f ./build/gulpfile.ts build
[15:06:36] Requiring external module ts-node/register
[15:06:36] Working directory changed to ~/vendure/packages/core/build
[15:06:41] Using gulpfile ~/vendure/packages/core/build/gulpfile.ts
[15:06:41] Starting 'build'...
[15:06:41] Starting 'copySchemas'...
[15:06:41] Starting 'copyI18nMessages'...
[15:06:41] Finished 'copyI18nMessages' after 308 ms
[15:06:41] Finished 'copySchemas' after 467 ms
[15:06:41] Finished 'build' after 469 ms
lerna info run Ran npm script 'build' in '@vendure/create' in 32.3s:
$ yarn copy-assets && rimraf lib && tsc -p ./tsconfig.build.json
$ rimraf assets && ts-node ./build.ts
lerna info run Ran npm script 'build' in '@vendure/asset-server-plugin' in 42.5s:
$ rimraf lib && tsc -p ./tsconfig.build.json && node build.js
lerna info run Ran npm script 'build' in '@vendure/elasticsearch-plugin' in 25.9s:
$ rimraf lib && tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/email-plugin' in 19.0s:
$ rimraf lib && tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/harden-plugin' in 14.3s:
$ rimraf lib && tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/job-queue-plugin' in 20.6s:
$ rimraf package && tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/testing' in 15.6s:
$ tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/payments-plugin' in 19.9s:
$ rimraf package && tsc -p ./tsconfig.build.json
lerna info run Ran npm script 'build' in '@vendure/admin-ui' in 228.2s:
$ node scripts/copy-package-json.js && node scripts/set-version.js && node scripts/build-public-api.js && yarn ng build vendure-admin-lib --configuration production && node scripts/compile-styles.js
Copying main package.json to library...
Updating application version 1.9.6
Generating public apis...
Created /home/dylan/vendure/packages/admin-ui/src/lib/catalog/src/public_api.ts
Created /home/dylan/vendure/packages/admin-ui/src/lib/core/src/public_api.ts
Created /home/dylan/vendure/packages/admin-ui/src/lib/customer/src/public_api.ts
Created /home/dylan/vendure/packages/admin-ui/src/lib/dashboard/src/public_api.ts
Created /home/dylan/vendure/packages/admin-ui/src/lib/login/src/public_api.ts
Created /home/dylan/vendure/packages/admin-ui/src/lib/marketing/src/public_api.ts
Created /home/dylan/vendure/packages/admin-ui/src/lib/order/src/public_api.ts
Created /home/dylan/vendure/packages/admin-ui/src/lib/settings/src/public_api.ts
Created /home/dylan/vendure/packages/admin-ui/src/lib/system/src/public_api.ts
$ ng build vendure-admin-lib --configuration production
Building Angular Package

------------------------------------------------------------------------------
Building entry point '@vendure/admin-ui'
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Building entry point '@vendure/admin-ui/core'
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Building entry point '@vendure/admin-ui/catalog'
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Building entry point '@vendure/admin-ui/customer'
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Building entry point '@vendure/admin-ui/dashboard'
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Building entry point '@vendure/admin-ui/login'
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Building entry point '@vendure/admin-ui/marketing'
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Building entry point '@vendure/admin-ui/order'
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Building entry point '@vendure/admin-ui/settings'
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Building entry point '@vendure/admin-ui/system'
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Built Angular Package
 - from: /home/dylan/vendure/packages/admin-ui/src/lib
 - to:   /home/dylan/vendure/packages/admin-ui/package
------------------------------------------------------------------------------

Build at: 2023-05-04T22:09:34.584Z - Time: 208893ms

lerna ERR! yarn run build exited 1 in '@vendure/ui-devkit'
lerna ERR! yarn run build stdout:
$ yarn build:client && yarn build:compiler
$ rimraf ./client && rollup -c rollup.config.js --configProduction
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
Error loading `tslib` helper library.
[!] Error: Package subpath './package.json' is not defined by "exports" in /home/dylan/vendure/node_modules/rollup-plugin-typescript2/node_modules/tslib/package.json
Error: Package subpath './package.json' is not defined by "exports" in /home/dylan/vendure/node_modules/rollup-plugin-typescript2/node_modules/tslib/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:565:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/dylan/vendure/node_modules/rollup-plugin-typescript2/src/tslib.ts:11:23)

error Command failed with exit code 1.
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@vendure/ui-devkit'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
```

**Comment by denz93** [comment]
> > @dylviz I run into this issue before and it maybe caused by some dependencies related to Webpack that using MD4 hash algorithm.
> > Quick fix: `NODE_OPTIONS=--openssl-legacy-provider yarn build`
> 
> Unfortunately, this makes a different error appear:
> 
> ```
> vendure $NODE_OPTIONS=--openssl-legacy-provider yarn build
> yarn run v1.22.19
> $ lerna run build
> lerna notice cli v4.0.0
> lerna info Executing command in 13 packages: "yarn run build"
> lerna info run Ran npm script 'build' in '@vendure/common' in 3.9s:
> $ rimraf lib && tsc -p ./tsconfig.build.json
> lerna info run Ran npm script 'build' in '@vendure/core' in 41.8s:
> $ rimraf dist && tsc -p ./build/tsconfig.build.json && tsc -p ./build/tsconfig.cli.json && gulp -f ./build/gulpfile.ts build
> [15:06:36] Requiring external module ts-node/register
> [15:06:36] Working directory changed to ~/vendure/packages/core/build
> [15:06:41] Using gulpfile ~/vendure/packages/core/build/gulpfile.ts
> [15:06:41] Starting 'build'...
> [15:06:41] Starting 'copySchemas'...
> [15:06:41] Starting 'copyI18nMessages'...
> [15:06:41] Finished 'copyI18nMessages' after 308 ms
> [15:06:41] Finished 'copySchemas' after 467 ms
> [15:06:41] Finished 'build' after 469 ms
> lerna info run Ran npm script 'build' in '@vendure/create' in 32.3s:
> $ yarn copy-assets && rimraf lib && tsc -p ./tsconfig.build.json
> $ rimraf assets && ts-node ./build.ts
> lerna info run Ran npm script 'build' in '@vendure/asset-server-plugin' in 42.5s:
> $ rimraf lib && tsc -p ./tsconfig.build.json && node build.js
> lerna info run Ran npm script 'build' in '@vendure/elasticsearch-plugin' in 25.9s:
> $ rimraf lib && tsc -p ./tsconfig.build.json
> lerna info run Ran npm script 'build' in '@vendure/email-plugin' in 19.0s:
> $ rimraf lib && tsc -p ./tsconfig.build.json
> lerna info run Ran npm script 'build' in '@vendure/harden-plugin' in 14.3s:
> $ rimraf lib && tsc -p ./tsconfig.build.json
> lerna info run Ran npm script 'build' in '@vendure/job-queue-plugin' in 20.6s:
> $ rimraf package && tsc -p ./tsconfig.build.json
> lerna info run Ran npm script 'build' in '@vendure/testing' in 15.6s:
> $ tsc -p ./tsconfig.build.json
> lerna info run Ran npm script 'build' in '@vendure/payments-plugin' in 19.9s:
> $ rimraf package && tsc -p ./tsconfig.build.json
> lerna info run Ran npm script 'build' in '@vendure/admin-ui' in 228.2s:
> $ node scripts/copy-package-json.js && node scripts/set-version.js && node scripts/build-public-api.js && yarn ng build vendure-admin-lib --configuration production && node scripts/compile-styles.js
> Copying main package.json to library...
> Updating application version 1.9.6
> Generating public apis...
> Created /home/dylan/vendure/packages/admin-ui/src/lib/catalog/src/public_api.ts
> Created /home/dylan/vendure/packages/admin-ui/src/lib/core/src/public_api.ts
> Created /home/dylan/vendure/packages/admin-ui/src/lib/customer/src/public_api.ts
> Created /home/dylan/vendure/packages/admin-ui/src/lib/dashboard/src/public_api.ts
> Created /home/dylan/vendure/packages/admin-ui/src/lib/login/src/public_api.ts
> Created /home/dylan/vendure/packages/admin-ui/src/lib/marketing/src/public_api.ts
> Created /home/dylan/vendure/packages/admin-ui/src/lib/order/src/public_api.ts
> Created /home/dylan/vendure/packages/admin-ui/src/lib/settings/src/public_api.ts
> Created /home/dylan/vendure/packages/admin-ui/src/lib/system/src/public_api.ts
> $ ng build vendure-admin-lib --configuration production
> Building Angular Package
> 
> ------------------------------------------------------------------------------
> Building entry point '@vendure/admin-ui'
> ------------------------------------------------------------------------------
> 
> ------------------------------------------------------------------------------
> Building entry point '@vendure/admin-ui/core'
> ------------------------------------------------------------------------------
> 
> ------------------------------------------------------------------------------
> Building entry point '@vendure/admin-ui/catalog'
> ------------------------------------------------------------------------------
> 
> ------------------------------------------------------------------------------
> Building entry point '@vendure/admin-ui/customer'
> ------------------------------------------------------------------------------
> 
> ------------------------------------------------------------------------------
> Building entry point '@vendure/admin-ui/dashboard'
> ------------------------------------------------------------------------------
> 
> ------------------------------------------------------------------------------
> Building entry point '@vendure/admin-ui/login'
> ------------------------------------------------------------------------------
> 
> ------------------------------------------------------------------------------
> Building entry point '@vendure/admin-ui/marketing'
> ------------------------------------------------------------------------------
> 
> ------------------------------------------------------------------------------
> Building entry point '@vendure/admin-ui/order'
> ------------------------------------------------------------------------------
> 
> ------------------------------------------------------------------------------
> Building entry point '@vendure/admin-ui/settings'
> ------------------------------------------------------------------------------
> 
> ------------------------------------------------------------------------------
> Building entry point '@vendure/admin-ui/system'
> ------------------------------------------------------------------------------
> 
> ------------------------------------------------------------------------------
> Built Angular Package
>  - from: /home/dylan/vendure/packages/admin-ui/src/lib
>  - to:   /home/dylan/vendure/packages/admin-ui/package
> ------------------------------------------------------------------------------
> 
> Build at: 2023-05-04T22:09:34.584Z - Time: 208893ms
> 
> lerna ERR! yarn run build exited 1 in '@vendure/ui-devkit'
> lerna ERR! yarn run build stdout:
> $ yarn build:client && yarn build:compiler
> $ rimraf ./client && rollup -c rollup.config.js --configProduction
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> lerna ERR! yarn run build stderr:
> Error loading `tslib` helper library.
> [!] Error: Package subpath './package.json' is not defined by "exports" in /home/dylan/vendure/node_modules/rollup-plugin-typescript2/node_modules/tslib/package.json
> Error: Package subpath './package.json' is not defined by "exports" in /home/dylan/vendure/node_modules/rollup-plugin-typescript2/node_modules/tslib/package.json
>     at new NodeError (node:internal/errors:399:5)
>     at exportsNotFound (node:internal/modules/esm/resolve:361:10)
>     at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
>     at resolveExports (node:internal/modules/cjs/loader:565:36)
>     at Function.Module._findPath (node:internal/modules/cjs/loader:634:31)
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
>     at Function.Module._load (node:internal/modules/cjs/loader:920:27)
>     at Module.require (node:internal/modules/cjs/loader:1141:19)
>     at require (node:internal/modules/cjs/helpers:110:18)
>     at Object.<anonymous> (/home/dylan/vendure/node_modules/rollup-plugin-typescript2/src/tslib.ts:11:23)
> 
> error Command failed with exit code 1.
> error Command failed with exit code 1.
> lerna ERR! yarn run build exited 1 in '@vendure/ui-devkit'
> lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
> error Command failed with exit code 1.
> ```

Coincidentally, I also run into this exactly like you. 

My fix is: `Update Node to latest stable version`

**Comment by dylviz** [comment]
@denz93 I'm running 18.16. I suppose I can give v16 a shot though

**Comment by denz93** [comment]
> @denz93 I'm running 18.16. I suppose I can give v16 a shot though

18.16.0 should work cause it is stable LTS version: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.16.0

**Comment by dylviz** [comment]
> > @denz93 I'm running 18.16. I suppose I can give v16 a shot though
> 
> 18.16.0 should work cause it is stable LTS version: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.16.0

Interestingly enough, it actually works flawlessly now!  I switch to v16.20 then re-started from the top and everything seems to be running now. I appreciate the help @denz93. Now onto beta testing this multivendor plugin that everyone's talking about!
