### ISSUE TITLE
yarn populate failed with Unable to locate admin ui file: vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json

### ISSUE THREAD

**Issue by ganeshnayanajith** [vendure-ecommerce/vendure#2169]
info 5/7/23, 6:23 PM - [AdminUiPlugin] Creating admin ui middleware (prod mode)
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Checking for admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Unable to locate admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json (attempt 1)
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Checking for admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json 
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Unable to locate admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json (attempt 2)
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Checking for admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json 
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Unable to locate admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json (attempt 3)
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Checking for admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json 
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Unable to locate admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json (attempt 4)
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Checking for admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json 
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Unable to locate admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json (attempt 5)
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Checking for admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json 
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Unable to locate admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json (attempt 6)
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Checking for admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json 
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Unable to locate admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json (attempt 7)
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Checking for admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json 
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Unable to locate admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json (attempt 8)
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Checking for admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json 
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Unable to locate admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json (attempt 9)
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Checking for admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json 
verbose 5/7/23, 6:23 PM - [AdminUiPlugin] Unable to locate admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json (attempt 10)
error 5/7/23, 6:23 PM - [AdminUiPlugin] Unable to locate admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json 
Error: Unable to locate admin ui file: <path>\vendure\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json
    at AdminUiPlugin.pollForFile (<path>\vendure\vendure\packages\admin-ui-plugin\src\plugin.ts:323:15)
    at async AdminUiPlugin.overwriteAdminUiConfig (<path>\vendure\vendure\packages\admin-ui-plugin\src\plugin.ts:260:29)
    at async overwriteConfig (<path>\vendure\vendure\packages\admin-ui-plugin\src\plugin.ts:130:13)
    at async AdminUiPlugin.configure (<path>\vendure\vendure\packages\admin-ui-plugin\src\plugin.ts:193:17)
    at async MiddlewareModule.loadConfiguration (<path>\vendure\vendure\node_modules\@nestjs\core\middleware\middleware-module.js:47:9)
    at async loadMiddlewareConfiguration (<path>\vendure\vendure\node_modules\@nestjs\core\middleware\middleware-module.js:37:13)
    at async Promise.all (index 36)
    at async MiddlewareModule.resolveMiddleware (<path>\vendure\vendure\node_modules\@nestjs\core\middleware\middleware-module.js:40:9)
    at async MiddlewareModule.register (<path>\vendure\vendure\node_modules\@nestjs\core\middleware\middleware-module.js:31:9)
    at async NestApplication.registerModules (<path>\vendure\vendure\node_modules\@nestjs\core\nest-application.js:77:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by rodevandroid** [comment]
try yarn builb fist.. its create the files

**Comment by michaelbromley** [comment]
Hi,

This looks like a general support request rather than an issue specifically related to this project. For community support, you are welcome to join our [Discord community](https://vendure.io/community) where you can post your question in the #help channel.

If you think I've made a mistake and this is indeed an issue specific to this project, please reply and the issue can be re-opened if needed.
