### ISSUE TITLE
Incorrect column type for "float" custom field in Postgres

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#217]
**Describe the bug**
When a CustomField is defined with the data type of "float", then per the code below, the DB column type will be set to "double".

https://github.com/vendure-ecommerce/vendure/blob/1ed987c4aadb73122bb3eac88d4e1766e30b9145/packages/core/src/entity/register-custom-entity-fields.ts#L121-L122

However, per the issue at https://github.com/vendure-ecommerce/real-world-vendure/issues/1, this is causing an error with Postgres: 
```
 Data type "double" in "Product.reviewRating" is not supported by "postgres" database
```

**Solution**
Verify the correct datatype to use in Postgres to represent a float. Long-term the solution is #207 which would have caught this issue.

**Environment (please complete the following information):**
 - @vendure/core version: 0.6.1
 - Nodejs version ?
 - Database (mysql/postgres etc): postgres

**Comment by rrubio** [comment]
@michaelbromley 

* NodeJS version: v12.10.0
