### ISSUE TITLE
customFields null on graphQl query collection

### ISSUE THREAD

**Issue by getwebM** [vendure-ecommerce/vendure#2171]
**Describe the bug**
customFields is null on graphQl query collection

Product with customFields:
![image](https://user-images.githubusercontent.com/53661314/236754856-0fab1ba8-92c6-4d40-9036-df6dbcb92363.png)

Query:
![image](https://user-images.githubusercontent.com/53661314/236754939-70542a0c-2218-4726-bc3b-32dc7796779a.png)

Response:
![image](https://user-images.githubusercontent.com/53661314/236755072-21891ed2-6be4-4443-aff1-40fc4b4b7e48.png)

**To Reproduce**
1. Create a product with custom Fields
2. Add Product to collection
3. Query Collection with productVariants
4. See customFields are empty

**Expected behavior**
List of customFields as JSON

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.5
 - Nodejs version: 14.21.2
 - Database (mysql/postgres etc): 10.5.19-MariaDB-0+deb11u2 - Debian 11

**Comment by michaelbromley** [comment]
I think the problem here (in both cases) is that the custom fields are being defined on the `Product` entity, but both the `collection` and (I am guessing) your `order` queries are actually querying `ProductVariant` rather than `Product`.

For example, to get the custom fields of the `Product` from the `activeOrder` query you would do:

```gql
query {
  activeOrder {
    id
    lines {
      productVariant {
        product {
          customFields {
            myCustomField
          }
        }
      }
    }
  }
}
```

**Comment by daviddarx** [comment]
Hi @michaelbromley , 

Thanks for your quick feedback. Hum, I guess my query already was correct, see, if I query the product directly by ID, I get its `shortname`: 
<img width="952" alt="01_product" src="https://github.com/vendure-ecommerce/vendure/assets/10694809/92d5f2f6-81dc-4a2d-a47b-a7d5f48e095f">

On the other hand, If I have the product in my order lines with `order` or `orderByCode`, the `shortname` is there null. 
<img width="952" alt="02_order" src="https://github.com/vendure-ecommerce/vendure/assets/10694809/6daa2e28-db33-4510-84b7-bc72ae7143c5">
<img width="952" alt="03_orderByCode" src="https://github.com/vendure-ecommerce/vendure/assets/10694809/00488cde-c37e-4615-8622-6626446a10d4">

Am I missing something? 
Thanks in advance!

**Comment by michaelbromley** [comment]
@daviddarx ok yeah your queries look correct so this seems like a potential bug then. I will investigate at the next opportunity.

Alternatively let's try putting a bounty on it to incentivize others to have a go at solving it:

/bounty $40

**Comment by daviddarx** [comment]
@michaelbromley Great thanks!
