### ISSUE TITLE
Docs: incorrect link text on step 7 of "Writing A Vendure Plugin"

### ISSUE THREAD

**Issue by wuichen** [vendure-ecommerce/vendure#220]
**Describe the bug**
The documentation of graphql plugin seems misleading on step 7 for creating graphql plugin. shouldnt it be shopApiExtentions? or is shopApiExtension currently unavailable?

https://www.vendure.io/docs/developer-guide/plugins/writing-a-vendure-plugin/

Step 7: Extend the GraphQL API
Now that we’ve defined the new mutation and we have a resolver capable of handling it, we just need to tell Vendure to extend the API. This is done with the adminApiExtensions metadata property. If we wanted to extend the Shop API, we’d use the adminApiExtensions metadata property instead.

**Comment by michaelbromley** [comment]
Aha, good catch! This is probably a copy-paste error. Will fix in next update.

**Comment by wuichen** [comment]
this is an awesome library! keep up with the good work
