### ISSUE TITLE
Disable anonymous access

### ISSUE THREAD

**Issue by Szbuli** [vendure-ecommerce/vendure#221]
**Describe the solution you'd like**
Use vendure config to disable anonymous access.

**Additional context**
Support private webshops in which new users have to have their identity validated.

**Comment by michaelbromley** [comment]
Do you mean *all* Shop API queries/mutations should require authentication in this mode?

**Comment by Szbuli** [comment]
Yes, the application is private. Only manually added users should be able to use it.

**Comment by michaelbromley** [comment]
Have thought about this a bit more and it could potentially be implemented without too much change. Right now the authorization checks are performed in the AuthGuard middleware:

https://github.com/vendure-ecommerce/vendure/blob/337762eeddb2a8a35b42c0c50dff115ae2b8612c/packages/core/src/api/middleware/auth-guard.ts#L33-L53

Line 36 introspects the particular GraphQL resolver being used to see what permissions are required (as defined by the `@Allow()` decorator . For "public" operations this will return undefined, meaning all are allowed.

We could introduce a `defaultPermissionRequirement` config option, which would default to undefined, but would *could* be set to e.g. `Permission.Authenticated`. 

So in the case that line 36 above is `undefined`, the `defaultPermissionRequirement` will be used.

I'll have to test this out in practice to see if it works, but at least in my head it seems like a possible solution.

**Comment by michaelbromley** [comment]
I'm closing this as it is not on our roadmap to support out of the box. Custom solutions are possible using middleware.

**Comment by arrrrny** [comment]
it would be nice to have for mobile e-commerce apps and great for anti-scrape. I will check what I can do

**Comment by arrrrny** [comment]
@Szbuli @michaelbromley There are 2 benenfits to this. Prevent bot/scraping and allow private stores. In my case, being mobile only, this is crucial.

https://github.com/vendure-ecommerce/vendure/pull/2990
