### ISSUE TITLE
Postgres Migration for Money columns still using 4 byte int

### ISSUE THREAD

**Issue by ayushkamadji** [vendure-ecommerce/vendure#2212]
**Describe the bug**
In reference to issue #838. The GraphQL part is fixed in v2.0. But default Postgres migration is still using 4 byte int for money columns which leads to error when adding items to cart which will set the new total > 21,474,836.47. 

**To Reproduce**
1. Add items to cart until total would be set to something > 21,474,836.47
2. Get error message something went wrong

**Expected behavior**
Should be able to add more than 21,474,836.47 total into cart

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.0
 - Nodejs version: v18.12.1
 - Database (mysql/postgres etc): Postgres 13

**Additional context**
Discord help: https://discord.com/channels/1100672177260478564/1116266274452942918

**Comment by michaelbromley** [comment]
This is by design - the [DefaultMoneyStrategy](https://docs.vendure.io/typescript-api/money/default-money-strategy/) aims to replicate the behaviour of Vendure v1.x. You should switch over to the [BigIntMoneyStrategy](https://docs.vendure.io/typescript-api/money/big-int-money-strategy/).

**Comment by ayushkamadji** [comment]
Ah yes I went in and tested with BigInt strategy but since there are products already, the migration fails due to price column for existing data being null. This is because the migration generator does a simple drop column and add new column.

I guess this should be a rare case since people should set their money strategy upfront before adding any products. 

It's a minor issue when adding the populateProducts option during `@vendure/create` having populated products assuming the DefaultStrategy. Probably documentation note will suffice.

For those who encounter the same problem:
1. When generating your vendure project do not choose to populate products
2. Set BigIntMoneyStrategy for your entityOptions.moneyStrategy in vendure config, see [doc](https://docs.vendure.io/typescript-api/money/money-strategy/)
3. run `yarn migration:generate <some_name_for_migration>`
4. Run the app normally and it should automatically migrate the database
