### ISSUE TITLE
Customer list doesn't show customers in the customers section

### ISSUE THREAD

**Issue by habibullahturkmen** [vendure-ecommerce/vendure#2213]
**Describe the bug**
When created a new customer, it doesn't show in the admin panel. The customer list is empty after creating multiple customers from the admin panel and the storefront. But when I add a customer to the customer group, I can only see it in the customer group list but cannot see it in the customers list.

**To Reproduce**
1. Go to the Customers Section
2. Click on "Customers"
3. Then click on the "Create new customer" button,
4. Fill out the form and create a customer
5. Go back to the customers section by clicking the "Customers" tab.
6. The Customers list is empty

**Expected behavior**
After creating a new customer, the new customer should be visible in the customers list.

**Environment (please complete the following information):**
 - @vendure/core version: v2.0.0
 - Nodejs version: v18.16.0
 - Database (mysql/postgres etc): PostgreSQL

**Additional context**

**Comment by patrickalima98** [comment]
The same problem here

**Comment by oidt** [comment]
When adding an address to the customer it become visible to the admin dashboard.
