### ISSUE TITLE
vendure 2.0: Multivendor, 'mark as shipped; error

### ISSUE THREAD

**Issue by tlodge** [vendure-ecommerce/vendure#2215]
**Describe the bug**
I have tested a full workflow for a multivendor order, and it is very nearly there, but once shipping addresses have been selected and an order placed, the orders are split between sellers as I expect.  But when I then go into an order and click on fulfil, then 'mark as shipped', I get the following server error:

```
[run:server] error 6/9/23, 8:38 AM - [Vendure Server] {
[run:server]   "message": "INTERNAL_SERVER_ERROR: ORDER_STATE_TRANSITION_ERROR",
[run:server]   "variables": {}
[run:server] }
[run:server] Error: ORDER_STATE_TRANSITION_ERROR
[run:server]     at transitionOrderIfStateAvailable (/[home]/vendure2/packages/core/src/config/fulfillment/default-fulfillment-process.ts:136:23)
[run:server]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[run:server]     at async handleFulfillmentStateTransitByOrder (/[home]/vendure2/packages/core/src/config/fulfillment/default-fulfillment-process.ts:144:13)
[run:server]     at async Promise.all (index 0)
[run:server]     at async Object.onTransitionEnd (/[home]/vendure2/packages/core/src/config/fulfillment/default-fulfillment-process.ts:115:9)
[run:server]     at async awaitPromiseOrObservable (/[home]/vendure2/packages/core/src/common/utils.ts:76:18)
[run:server]     at async Object.onTransitionEnd (/[home]/vendure2/packages/core/src/service/helpers/fulfillment-state-machine/fulfillment-state-machine.ts:80:25)
[run:server]     at async awaitPromiseOrObservable (/[home]/vendure2/packages/core/src/common/utils.ts:76:18)
[run:server]     at async finalize (/[home]vendure2/packages/core/src/common/finite-state-machine/finite-state-machine.ts:64:25)
[run:server]     at async FulfillmentService.transitionToState (/[home]vendure2/packages/core/src/service/services/fulfillment.service.ts:181:9) 
```

**To Reproduce**
1.  Create two sellers and add a product to each of them through the GraphQL frontend (as specified in the multivendor.plugin `README.md`

2. Login with a customer
3. Add items to an order (one from each seller)
4. Set the order shipping address
5. Query the appropriate shipping methods
6. Set the order shipping methods for each different seller
7. Checkout the order
8. Login to the admin interface and select either one of the seller's channels
9. Select the newly created order
10. Click on fulfil order and give it a fufilment method and tracking code 
11. Click on mark as shipped.

I'm guessing that there should have been some state transition that hasn't occurred.   The fulfilment state is marked as 'Pending' - and looking at the `default-fulfilment-process.ts` it looks like that should be fine:

```
 transitions: {
        Created: {
            to: ['Pending'],
        },
        Pending: {
            to: ['Shipped', 'Delivered', 'Cancelled'],
        },
        Shipped: {
            to: ['Delivered', 'Cancelled'],
        },
        Delivered: {
            to: ['Cancelled'],
        },
        Cancelled: {
            to: [],
        },
    },
```

And the specific line that throws the error is:

```
const result = await orderService.transitionToState(ctx, order.id, state);
```

In the case where there is an error, the state that I'm transitioning to is 'Shipped' but the order that I'm transitioning from is in state 'PaymentSettled'. Should it be in the state 'Pending'?

**Expected behavior**
I expect that when I mark an order as shipped, the whole order will be placed into the PartiallyShipped state.

**Environment (please complete the following information):**
 - @vendure/core version:2.0
 - Nodejs version: 19.2
 - Database (mysql/postgres etc): postgres

**Additional context**
Running the dev-server on the master branch of 2.0

**Comment by michaelbromley** [comment]
Thanks for the report!

The issue turns out to be that a required relation was not loaded. In the `mv-order-process.ts` file, change line 92 to add the `fulfillment.lines.fulfillment` relation:

```ts
async function findOrderWithFulfillments(ctx: RequestContext, id: ID): Promise<Order> {
    return await connection.getEntityOrThrow(ctx, Order, id, {
        relations: ['lines', 'fulfillments', 'fulfillments.lines', 'fulfillments.lines.fulfillment'],
    });
}
```

**Comment by tlodge** [comment]
Many thanks again @michaelbromley
