### ISSUE TITLE
[v2.0.0] Create a new channel

### ISSUE THREAD

**Issue by oidt** [vendure-ecommerce/vendure#2217]
**Describe the bug**
I try to create a new channel but nothing happens.

**To Reproduce**
1. Go to 'Settings -> Channels'
2. Click on 'Create new channel'
3. Fill in the form
4. When I click on 'Create' nothing happens.

**Expected behavior**
I expect to have a new channel with my settings in the form

**Environment (please complete the following information):**
 - @vendure/core version: v2.0.0
 - Nodejs version: v18.14.0
 - Database (mysql/postgres etc): mysql/sqlite

**Additional context**
In the chrome developer tab I do see this but sure if it is related.

`DevTools failed to load source map: Could not load content for http://localhost:3000/admin/settings/channels/action-bar.component.ts-angular-inline--1.css.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

**Comment by patrickalima98** [comment]
Hi, the same to me

**Comment by nonlinearcom** [comment]
hi, same here, in my case the error message shows:
```ERROR ApolloError: null value in column "defaultCurrencyCode" of relation "channel" violates not-null constraint```

**Comment by patrickalima98** [comment]
@nonlinearcom  the same to me when use GraphQL Api:

```graphql
mutation CreateChannel {
    createChannel(
        input: {
            code: "Test",
            token: "clipdmi57000008jv4if664do",
            defaultCurrencyCode: BRL,
            trackInventory: true,
            pricesIncludeTax: false,
            sellerId: "1",
            defaultTaxZoneId: "5",
            defaultShippingZoneId: "5",
            defaultLanguageCode: en,
            availableCurrencyCodes: [BRL]
        }
    ) {
        ... on LanguageNotAvailableError {
            errorCode
            message
            languageCode
        }
        ... on Channel {
            id
            createdAt
            updatedAt
            code
            token
            defaultLanguageCode
            availableLanguageCodes
            currencyCode
            defaultCurrencyCode
            availableCurrencyCodes
            trackInventory
            outOfStockThreshold
            pricesIncludeTax
            customFields
        }
    }
}


```

Server response:

<img width="1453" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/17622137/6e0d18a8-1fe9-4a5a-9da0-43ad28cc1c5e">

**Comment by nonlinearcom** [comment]
@patrickalima98  I managed to create a channel with the following mutation, using `currencyCode` instead of `defaultCurrencyCode` :
```gql
mutation CREATECHANNEL {
	createChannel(
		input: {
			code: "test"
			token: "test"
			defaultLanguageCode: en
			availableLanguageCodes: [en]
			pricesIncludeTax: true
			currencyCode: EUR
			availableCurrencyCodes: [EUR]
			trackInventory: true
			defaultTaxZoneId: 2
			defaultShippingZoneId: 2
		}
	) {
		code
	}
}
```

**Comment by patrickalima98** [comment]
@nonlinearcom thanks for you reply. 

I can confirm, it worked here too

**Comment by oidt** [comment]
@michaelbromley It still goes wrong when not flipped: Prices include tax for the default Zone

**Comment by habibullahturkmen** [comment]
I'm facing the same issue with Vendure 2.0.1. It works when "Prices include tax for the default Zone" is flipped on.

**Comment by michaelbromley** [comment]
actually_fixed_v2_2-final.psd coming soon!
