### ISSUE TITLE
Unable to add facet value

### ISSUE THREAD

**Issue by Granga** [vendure-ecommerce/vendure#222]
**Describe the bug**
I am unable add facet value on either new or existing facet.

**To Reproduce**
1. Open admin panel.
2. Click on the Facets in the left menu.
3. Click Edit on any of the listed facets.
4. Scroll down to see the `Add facet value` button
5. Try to add facet value by clicking the button.
6. Nothing appears as a form for adding facet value.

**Expected behavior**
A form for adding facet value to appear.

**Environment (please complete the following information):**
 - @vendure/core version: 0.64
 - Nodejs version: 10.15.3
 - Database (mysql/postgres etc): postgres

![image](https://user-images.githubusercontent.com/6062311/70194509-efdf8c80-1702-11ea-9fc0-3b457a502894.png)

**Comment by Granga** [comment]
![image](https://user-images.githubusercontent.com/6062311/70194483-d8080880-1702-11ea-89c5-ec3e1fce8aa1.png)

**Comment by michaelbromley** [comment]
Thanks for the report. I've been able to reproduce this and it will get fixed in the next release.
