### ISSUE TITLE
[v2.0.0] Admin UI - roles - enabled vs. disabled rights readability

### ISSUE THREAD

**Issue by mpacary** [vendure-ecommerce/vendure#2224]
**Issue description**
The current colors for enabled & disabled rights icons are very close, making them difficult to be told apart.

**To Reproduce**
1. Login to admin UI as a superadmin
2. Go to section Settings > Roles
3. Create or modify a role

**Version**
Vendure v2.0.0

In the example below, all CRUD rights are enabled on **Catalog**, and only Read on **Channel**. Others are disabled (AFAICS 😅).
![image](https://github.com/vendure-ecommerce/vendure/assets/705663/ba267295-eb9d-4331-b667-5f61475cfb4c)

This is rather a UX issue than a bug ; feel free to modify the labels of course.

**Comment by michaelbromley** [comment]
Thanks for the report - and good point!

In the next patch this will be improved to look like this: 
![image](https://github.com/vendure-ecommerce/vendure/assets/6275952/e86f08f8-339a-4e8a-80db-4efc6d54155a)
