### ISSUE TITLE
setBranding does not change the top left logo display in AdminUI

### ISSUE THREAD

**Issue by cdev-enter** [vendure-ecommerce/vendure#2225]
**Describe the bug**
Custom Logo is not used when specifying the small logo path with setBranding().

It copies the file in the to admin/dist/assets/logo-75px.png but the angular component (https://github.com/vendure-ecommerce/vendure/blob/master/packages/admin-ui/src/lib/core/src/components/app-shell/app-shell.component.html#L4) references "assets/logo.svg"
 
**To Reproduce**
Follow the steps according to the documentation:
https://docs.vendure.io/plugins/extending-the-admin-ui/admin-ui-theming-branding/

**Expected behavior**
The logo should change

**Environment (please complete the following information):**
 - @vendure/core version: 2.0

**Comment by habibullahturkmen** [comment]
I'm facing the same issues with Vendure v2.0.2
