### ISSUE TITLE
Error NG0402 with custom compiled admin ui

### ISSUE THREAD

**Issue by jbanety** [vendure-ecommerce/vendure#2230]
**Describe the bug**
I migrated my app to version 2.0.1 and since then, I can compile thr admin ui but I have an error in browser.

Error message in the browser: 
`Error: NG0402: A required Injectable was not found in the dependency injection tree. If you are bootstrapping an NgModule, make sure that the `BrowserModule` is imported.`

**To Reproduce**
`vendure-config.ts` :
```ts
        AdminUiPlugin.init({
            route: 'admin',
            port: 3002,
            app: customAdminUi({ recompile: true, devMode: true }),
        }),
```

`compile-admin-ui.ts` :
```ts
export function customAdminUi(options: { recompile: boolean; devMode: boolean }) {
    if (options.recompile) {
        return compileUiExtensions({
            outputPath: path.join(__dirname, '../dist/admin-ui'),
            extensions: [],
            devMode: options.devMode,
            additionalProcessArguments: options.devMode ? ['--allowed-hosts', (process.env.VENDURE_APP_PUBLIC_URI ?? "").replace("https://", "")] : [],
        });
    } else {
        return {
            path: path.join(__dirname, 'admin-ui/dist'),
        };
    }
}
```

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.1
 - Nodejs version : 16.15.1
 - Database (mysql/postgres etc): postgres

**Comment by buisine** [comment]
@jbanety 
Hi, stucked with the same error, how to get rid of it ?

**Comment by jbanety** [comment]
Hi @buisine,
if I remember correctly, you need to make sure you have the same versions of your dependencies in all your packages
