### ISSUE TITLE
V2 - Move to top level collection

### ISSUE THREAD

**Issue by hirenreshamwala** [vendure-ecommerce/vendure#2236]
**Describe the bug**
I have installed the v2 with the sample data. I accidentally moved `Electronics` collection into the `Sports & Outdoor`. Now I want to move back to the top-level category again which I can't do. 

**To Reproduce**
1. Go to 'Collections'
2. check any collection
3. Click on 'Move Collections' inside 'with selected options'
4. Select any category in which you want to move
5. Now try to make all collections the same as before

**Expected behavior**
There should be an option to move to the root

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.1
 - Nodejs version: v16.15.1
 - Database: mysql

**Comment by michaelbromley** [comment]
Good point! Will add this for the next patch version.
