### ISSUE TITLE
clr-modal inside vdr-card not working as expected

### ISSUE THREAD

**Issue by dalyathan** [vendure-ecommerce/vendure#2244]
**Describe the bug**
When a custom angular component is used for an entity's `customField`, in most(if not all) times it will be contained inside [`vdr-card`](https://github.com/vendure-ecommerce/vendure/blob/master/packages/admin-ui/src/lib/core/src/shared/components/card/card.component.ts). When such component contains a [`clr-modal`](https://clarity.design/documentation/modals) and the modal is launched, it will be displayed as in the following image:

![image](https://github.com/vendure-ecommerce/vendure/assets/39517388/163d655d-d2ab-4685-a7e4-bd8a006f2da1)
which is, obviously, not expected. 

**To Fix it**
Other fixes may be applicable, but we can apply a `display: inline list-item` to [`vdr-card`](https://github.com/vendure-ecommerce/vendure/blob/master/packages/admin-ui/src/lib/core/src/shared/components/card/card.component.scss) like this:
```
:host {
    display: inline list-item;
   ...
```
instead of
```
:host {
    display: block;
   ...
```
which seems to fix the issue.

![image](https://github.com/vendure-ecommerce/vendure/assets/39517388/d24412f9-9892-4515-a8cd-3afee48dedc8)

**Comment by michaelbromley** [comment]
Hi,

thanks for the report. The idiomatic way to do modals in the Admin UI is to use our [ModalService](https://docs.vendure.io/admin-ui-api/providers/modal-service/), which will display as expected.

**Comment by dalyathan** [comment]
Ok I will look into that. Thanks
