### ISSUE TITLE
Changing order during transition is not persisted

### ISSUE THREAD

**Issue by Lennix** [vendure-ecommerce/vendure#2247]
**Describe the bug**
We are trying to add a surcharge during a transition. The order is updated by addSurchargeToOrder, but once the transition finishes, the order is reverted to its original state.

I guess the problem lies here:
https://github.com/vendure-ecommerce/vendure/commit/7b2daa6217bc9150543beaa162f6d11ecfe94285#diff-ddc432c4392054b0d16b826194ca9e408576cee61292c9176f678919af6deb6fR968

The order is saved again after finalize() was called overwriting any change.

**To Reproduce**
1. Create a transitionStart/End callback and change order there

**Expected behavior**
The order should be updated

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.2
 - Nodejs version
 - Database (mysql/postgres etc): postgres

**Additional context**
Here's my code:
```typescript
async onTransitionEnd(fromState, toState, data) {
  if (fromState === 'AddingItems' && toState === 'ArrangingPayment') {
    await orderService.addSurchargeToOrder(ctx, order.id, {
      description: 'Test',
      listPrice: 42,
      listPriceIncludesTax: false,
    );
  }
},
```

**Comment by michaelbromley** [comment]
Yes, mutating the order during a transition hook is quite tricky to guarantee. There are a _lot_ of moving parts in this process, so the result can be race conditions as you see here.

An safer potential alternative would be to use the EventBus to subscribe to [OrderStateTransitionEvent](https://docs.vendure.io/typescript-api/events/event-types/#orderstatetransitionevent) and take action in the event subscriber. This is guaranteed to execute after all open DB transactions related to the order have completed.

A future solution could lie in a proposal I have for a new API to intercept order operations, which I have detailed here: 

- https://github.com/vendure-ecommerce/vendure/issues/2123

**Comment by Lennix** [comment]
I had the time to look into your suggestion, but I fear it has the same problem that I described above.

`        await this.connection.getRepository(ctx, Order).save(order, { reload: false });
        this.eventBus.publish(new OrderStateTransitionEvent(fromState, state, ctx, order));
        await finalize();
        await this.connection.getRepository(ctx, Order).save(order, { reload: false });`

The order is saved after the Event is published. That could trigger the same race condition.

Why is the order saved twice? Once again, I'm referring to this commit: https://github.com/vendure-ecommerce/vendure/commit/7b2daa6217bc9150543beaa162f6d11ecfe94285#diff-ddc432c4392054b0d16b826194ca9e408576cee61292c9176f678919af6deb6fR968

**Comment by michaelbromley** [comment]
OK I just looked into this a bit more. Simply commenting out the second call 

```ts
// await this.connection.getRepository(ctx, Order).save(order, { reload: false });
```

results in 76 e2e test failures. So it is clearly needed currently. Here's why:

the `finalize()` call is actually running all the `onTransitionEnd()` functions for all configured order processes. If any of those function mutate the `order` object, those changes need to be saved, which is what that second call is doing.

This means that in your case, it should be possible to get it working how you intend if you do something like this:

```ts
async onTransitionEnd(fromState, toState, data) {
  if (fromState === 'AddingItems' && toState === 'ArrangingPayment') {
    const { surcharges } = await orderService.addSurchargeToOrder(ctx, order.id, {
      description: 'Test',
      listPrice: 42,
      listPriceIncludesTax: false,
    );
    order.surcharges = surcharges;
  } 
},
```

The main issue with this is that the mutation & saving of the `order` object is implicit. It even took me a little while to look over the source code again to figure out what is going on. So perhaps some kind of explicit API for mutating the order might be warranted here. Or at least, better documentation.
