### ISSUE TITLE
NodeMailer debug/logs

### ISSUE THREAD

**Issue by msj121** [vendure-ecommerce/vendure#2253]
Having issues connecting nodemailer (ie: mailplugin) to outlook365. Is there a way to get output from the nodemailer connection and sent emails? I have put:

```
            transport:{
                type: 'smtp',
                host: 'smtp-mail.outlook.com',
                port: 587,
                secure:false,
                // secureConnection: false,
                // service: "outlook",
                auth: {
                   user: "user",
                   pass: "pass"
                },
                tls: {
                    ciphers: 'SSLv3',
                    rejectUnauthorized: false
                },
                logging: true,
                debug: true
            }
```

I don't see any logs in npm run dev though. Is there an argument I might be missing? Thanks.

**Comment by msj121** [comment]
It appears that "devMode:true" must be removed... I did not realize that... have been working on transport layer and I didn't get any heads up. Even just a comment in the vendure-config would be a good idea imo. Will put a simple PR if you'd like.

**Comment by michaelbromley** [comment]
Thanks for bringing this up. I'll add a warning log if devMode is set to true and a transport is also defined. Hopefully that should save people the confusion.
