### ISSUE TITLE
Back Office rights for inventory and order managers

### ISSUE THREAD

**Issue by charleshopfnerCoexya** [vendure-ecommerce/vendure#2254]
**Describe the bug**
When I connect to the back office with a profile that has the predefined role of "Inventory Manager", I am instantly logged out with this error message :
 "You are not currently authorized to access "metricSummary". Either you lack permissions, or your session has expired"

When I connect as Order Manager, i'm logged out less then a minute after being logged in with this error message :
" You are not currently authorized to access "pendingSearchIndexUpdates". Either you lack permissions, or your session has expired."

**To Reproduce**
1. Log in to the back office as superadmin
2. Create a new administrator with "Inventory Manager" role / with "Order Manager" role
3. Log out and log in with the new profile

**Expected behavior**
Inventory Manager should have access to the back office without seeing the metrics summary tab.
Order Manager should not be disconnected.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.2
 - Nodejs version 16.20.0
 - Database (mysql/postgres etc): SQLite

**Additional context**
running on localhost

**Comment by michaelbromley** [comment]
Hi,
Thanks for the report. This was fixed last week here: https://github.com/vendure-ecommerce/vendure/commit/3353c6ed190f9a0bdc6c6f90bc3ebdb6eddaa9e0 and will be part of the next patch release.

In the mean time it is possible to override the permissions of the metrics widget if you are using ui extensions, by adding this to a shared ui extension:

```ts
        // TODO: can be removed after updating to Vendure v2.0.3
        registerDashboardWidget('metrics', {
            title: 'dashboard.metrics',
            supportedWidths: [6, 8, 12],
            loadComponent: () => OrderChartWidgetComponent,
            requiresPermissions: ['ReadOrder'],
        }),
```
