### ISSUE TITLE
Using the new `EmailPlugin` `TemplateLoader` does not support subject localisation

### ISSUE THREAD

**Issue by StampixSMO** [vendure-ecommerce/vendure#2269]
**Describe the bug**
The new `TemplateLoader` is the recommended way to load email templates, using `addTemplate` is marked as deprecated. However, the `setSubject()` function on the handler accepts only a string and does not allow for localisation.

**To Reproduce**
1. Integrate the EmailPlugin
2. Attempt to translate the subject :) There's no way to do it (at least not straightforward)

**Expected behavior**
The `setSubject()` function to accept another function that can read out a context or event to set the subject based on that (e.g. localisation).

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.2
 - Nodejs version: 18
 - Database (mysql/postgres etc): Postgres

**Comment by martijnvdbrug** [comment]
@michaelbromley you can assign this to me

**Comment by rein1410** [comment]
Is there any progress on this? I need this feature badly.

**Comment by martijnvdbrug** [comment]
Haven't gotten to it. I could help you get started if you'd like to make an attempt at creating a PR yourself? Otherwise I can try and pick this up somewhere in the next weeks (no promises :-) )

**Comment by rein1410** [comment]
Sure, let me try making a PR for this.

**Comment by rein1410** [comment]
#2863 here
