### ISSUE TITLE
Logo not visible when hideVendureBranding is set true

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#2273]
smallLogoPath and largeLogoPath under the setBranding function of vendure, doesn't work when 'hideVendureBranding' is set to true.

**Comment by BeepLoveKarki** [comment]
When its true, also largelogopath doesn't work.

**Comment by oidt** [comment]
https://github.com/vendure-ecommerce/vendure/issues/2225 there is already an open issue for this

**Comment by michaelbromley** [comment]
Will track in #2225
