### ISSUE TITLE
asset-plugin: VipsJpeg: Invalid SOS parameters for sequential JPEG error

### ISSUE THREAD

**Issue by Draykee** [vendure-ecommerce/vendure#2275]
**Describe the bug**
When I try to upload an image I get this error.
```
Could not create Asset preview image: VipsJpeg: Invalid SOS parameters for sequential JPEG
```
- The image was apparently generated by using the image editor on a Samsung Galaxy S20. After some research, I believe that the problem is a new JPEG format that is not accepted by the current sharp version yet.

**To Reproduce**
1. Use the attached image for a file upload
![Screenshot_20230705_004952_Chrome](https://github.com/vendure-ecommerce/vendure/assets/19676051/1c177f3d-471a-4d7a-9bb6-bb25d01632ae)

**Expected behavior**
The image should successfully upload. Is a version upgrade of sharp maybe already enough?

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.6
 - Nodejs version: node:16-slim (in Docker)

**Additional context**

**Comment by michaelbromley** [comment]
Looks like it is related to a bug in Samsung's firmware. Discussed here:

- https://github.com/lovell/sharp/issues/2780
- https://github.com/lovell/sharp/issues/1578
