### ISSUE TITLE
Bug: Rich HTML editor removes `target="_blank"`

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#2281]
**Describe the bug**
We would like some links in the product descriptions to open in a new tab, but the rich-html-editor removes the tag `target="_blank"` after we click `update` (see screenshot).

**To Reproduce**
1. Go to a product detail
2. Create a link via the link button in the toolbar
3. Click the arrow with "Edit HTML"
4. In the popup window, add `target="_blank"`  in the anchor tag
5. Click "update"
6. Click "Edit HTML" again
7. The tag has been removed

**Expected behavior**
I would expect the `target="_blank"` tag to stay on the anchor tag after updating.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.2
 - Nodejs version 16
 - Database (mysql/postgres etc): mysql

**Additional context**
![image](https://github.com/vendure-ecommerce/vendure/assets/6604455/f1f8e85f-e7e1-445b-a843-f593f701d9d5)

**Comment by michaelbromley** [comment]
I went one better and added a UI control for the target 😉  
![image](https://github.com/vendure-ecommerce/vendure/assets/6275952/81a46155-3cf2-426e-96e0-42e758f040bc)

**Comment by martijnvdbrug** [comment]
Ohh sweet! Thats nice :ok_hand:
