### ISSUE TITLE
CustumFields Tag in UI admin component doesn't work

### ISSUE THREAD

**Issue by nicolasF4A** [vendure-ecommerce/vendure#2295]
**Describe the bug**
When  I add a custonmField with ui component the tag doesn't work. In Admin UI they display always custom fields

**To Reproduce**
```typescript
 customFields: {
    Product: [
      {
        name: "gtin",
        type: "int",
        ui: { component: "numbers-form-input", tab: "Infos" },
      },
    ],
    Channel: [
      {
        name: "latitude",
        type: "float",
        ui: { component: "numbers-form-input", tab: "Geolocation" },
      },
      {
        name: "longitude",
        type: "float",
        ui: { component: "numbers-form-input", tab: "Geolocation" },
      },
    ],
    ProductVariant: [
      {
        name: "orginalPrice",
        type: "int",
        ui: { component: "currency-form-input", tab: "Price" },
      },
    ],
  },
``` 

**Expected behavior**
I would like to have seperate tab in my Admin UI

**Environment (please complete the following information):**
    "@vendure/admin-ui-plugin": "2.0.4",
    "@vendure/asset-server-plugin": "2.0.4",
    "@vendure/core": "2.0.4",
    "@vendure/email-plugin": "2.0.4",
    "@vendure/ui-devkit": "^2.0.4",
    "dotenv": "16.3.1",
    "pg": "8.11.1",
    "typescript": "^5.1.6"
 - Nodejs version: v16.17.0
 - Database (mysql/postgres etc): Postgres

**Additional context**

**Comment by nicolasF4A** [comment]
![Capture d’écran 2023-07-18 à 15 40 30](https://github.com/vendure-ecommerce/vendure/assets/105633446/d16502f3-5fa8-48b4-9752-64bdc4726d34)

**Comment by nicolasF4A** [comment]
![Capture d’écran 2023-07-18 à 15 41 31](https://github.com/vendure-ecommerce/vendure/assets/105633446/8151ab82-95af-4984-8ab7-1e8ce79e6c68)

**Comment by oidt** [comment]
A tab will only be visible if there is more than 1.
Is this a feature request to show the tab always?

**Comment by nicolasF4A** [comment]
No it's ok thanks you.
