### ISSUE TITLE
Circular Depency Found

### ISSUE THREAD

**Issue by Yuri-Lima** [vendure-ecommerce/vendure#2297]
I was actually wondering if all those 531 circular decency would affect something in future. 
I've run that command to check for and i got that result in ./packages/core 

`npx madge --circular --extensions ts ./`

Please, let me know if maybe it would be fixed in future or if actually it not a real problem  or maybe that analizy is wrong👍

**Comment by michaelbromley** [comment]
Hi,

can you provide any further details? Is there some output that shows where the cycles are?

I'm inclined to say that any cycles are not a problem, based on the fact that everything builds ok and the tests all pass.

**Comment by Yuri-Lima** [comment]
Yeah, sure. Let me give you some inputs.

![CD1](https://github.com/vendure-ecommerce/vendure/assets/9964218/801ebaf3-f74a-4a57-9b23-4ea3182c7e51)

That is the command, from https://github.com/pahen/madge Ive used that since in NestJs Course recommended. Then i decided to test in you project. 

Its showing 
![Screenshot 2023-07-19 at 14 42 30](https://github.com/vendure-ecommerce/vendure/assets/9964218/ead54c2d-851f-414e-bf2b-a8d22fc90786)

And much more, have a try when it possible. 

Bty, thanks for you reply.

**Comment by Yuri-Lima** [comment]
@michaelbromley Did y have any time to check? Just let me know if we could just ignore those. 👍

Thank you

**Comment by michaelbromley** [comment]
Hi,

Yes, these are safe to ignore. Occasionally there _are_ real issues with circular dependencies, but when they occur, the Vendure server will simply fail to start. So the ones found by that tool are the ones that are safe.
