### ISSUE TITLE
Price field deletes entire value when pressing non-numeric keys.

### ISSUE THREAD

**Issue by erosai** [vendure-ecommerce/vendure#2301]
Describe the bug

When attempting to enter a price in the price field on Vendure Admin UI, pressing any key that is not a number causes the entire price value to be deleted, including the decimal point or comma required for prices.

To Reproduce

  1. Go to the product page in the Admin UI and try to create a new product.
  2. Click on the price field to activate it.
  3. Attempt to enter a price by typing any non-numeric key, such as a letter or symbol.
  4. Observe that the entire price value is deleted instead of allowing the non-numeric character.

**Environment :**
 - @vendure/core version: 2.0.4
 - Nodejs version : 20.4.0
 - Database (mysql/postgres etc): Postgres

**Comment by michaelbromley** [comment]
I just tested this on the latest version (2.2.x) and it seems that the issue has been resolved.
