### ISSUE TITLE
Admin UI: Product create page disallows `.` in the name

### ISSUE THREAD

**Issue by skid** [vendure-ecommerce/vendure#2304]
This happens on all versions of Vendure (AFAICT). Try to create a new product, and type a period `.` in the product name. The "create" button becomes disabled. If you create the product without the dot, you can later edit the name and put the dot back in.

This is very confusing for users, since there's no explanation why the create button is disabled, especially since there is no real validation error - dots are actually allowed.

**To Reproduce**
1. Go to the admin UI -> create new product
2. Start typing a name, then finish it with a period `.`

**Expected behavior**
Dots in the product name should not have any special effects.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.1, 1.9.X

**Comment by oidt** [comment]
looks like a slug problem
https://github.com/vendure-ecommerce/vendure/blob/0feddd81e099272c9f3c3c7b611a55cda0c21f10/packages/admin-ui/src/lib/catalog/src/components/product-detail/product-detail.component.ts#L84C41-L84C41 maybe this slug check?

**Comment by michaelbromley** [comment]
Yes it's the period being disallowed by the validator. But actually, periods are OK in URLs so we should allow them in slugs:

> 2.3.  Unreserved Characters
>
>   Characters that are allowed in a URI but do not have a reserved
   purpose are called unreserved.  These include uppercase and lowercase
   letters, decimal digits, hyphen, period, underscore, and tilde.
>
>      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"

source: https://www.ietf.org/rfc/rfc3986.txt
