### ISSUE TITLE
Tax Rate 0 Not Working

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#2312]
Adding Tax Rate 0% while creation of new tax rate in admin UI, doesn't work.

**Comment by oidt** [comment]
I can confirm that it is not working. Workaround: create with 1% and update to 0% afterwards.
Nothing happens on chrome dev tools

**Comment by michaelbromley** [comment]
Thanks for the report! Should be a simple fix.
