### ISSUE TITLE
Manually created orders (via Admin UI) show "Invalid Date" in Dashboard

### ISSUE THREAD

**Issue by yasserlens** [vendure-ecommerce/vendure#2321]
**Describe the bug**
Manually created orders (via Admin UI) show "Invalid Date" in Dashboard.
The order details page shows the date the order was placed, but the dashboard fails to do so. 
See attached images.
**Note** the last order in the screenshot was not created via Admin UI, that's why the date shows fine.
**Also Note** the order has a valid date (seen when navigating to the Order Details page).

**To Reproduce**
1. Create an order manually
2. Check the dashboard (admin UI)

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.0
 - Nodejs version: v18.11.0
 - Database (mysql/postgres etc): Postgres

**Additional context**
See how the date field has "invalid date"
<img width="723" alt="Screenshot 2023-07-27 at 11 30 03 a m" src="https://github.com/vendure-ecommerce/vendure/assets/2945770/4359a34b-67f8-4805-8809-51ec0dbb7e2b">

An image showing the date of the order when navigating to the order details page (the order history log section at the bottom)
<img width="221" alt="Screenshot 2023-07-27 at 11 28 34 a m" src="https://github.com/vendure-ecommerce/vendure/assets/2945770/e610aecd-4bc1-4a79-af4f-ca1c9ec0f574">

**Comment by michaelbromley** [comment]
Hi,

I believe this is a duplicate of https://github.com/vendure-ecommerce/vendure/issues/2105, which was fixed in v2.0.4. Can you update and see if that fixes it for you?

**Comment by yasserlens** [comment]
Hey Michael

I just updated and pushed live - the dates still show up as invalid. Would this only apply to new orders made after the 2.0.4 upgrade? Or was it an AdminUI update that wasn't reading the creation date correctly?

(side note: would be fantastic to show the Vendure version that's running on the System Status page.)

**Comment by michaelbromley** [comment]
Yes, it will only apply to new orders.

Good idea with the version number.

**Comment by yasserlens** [comment]
Thanks Michael - I'll mark this as closed for now since it seems like a duplicate. I'll re-open if it arises.
