### ISSUE TITLE
Issue with long header empty table

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#2323]
Why does this issue occur, only when the table is empty?
<img width="1440" alt="Screenshot 2023-07-27 at 22 18 33" src="https://github.com/vendure-ecommerce/vendure/assets/29729738/4f72251e-36d5-4a67-90e8-401cdb0861ed">

**Comment by BeepLoveKarki** [comment]
yes

**Comment by oidt** [comment]
when there are no results for that table the table got the layout fixed.

https://github.com/vendure-ecommerce/vendure/blob/cf20adee0415c1085c7ee8a30c24c7613ca4397d/packages/admin-ui/src/lib/catalog/src/components/collection-data-table/collection-data-table.component.html#L8

that is why.
