### ISSUE TITLE
Maximum usage of a coupon

### ISSUE THREAD

**Issue by PKarics** [vendure-ecommerce/vendure#2330]
**Is your feature request related to a problem? Please describe.**
We would like to maximize coupon usage for a marketing campaign, where the first 100 user can use the coupon. Per customer coupon usage cannot handle that.

**Describe the solution you'd like**
Add usage limit to the promotions like per customer usage limit, but it counts the coupon usage globally.

**Comment by michaelbromley** [comment]
Will be in v2.1. Thanks for the work on this!
