### ISSUE TITLE
More actions under add widget translations hardcoded

### ISSUE THREAD

**Issue by wpplumber** [vendure-ecommerce/vendure#2334]
**Describe the bug**
When visiting dashboard with RTL Arabic the more actions under add widget button items' text hardcoded. (see screenshot)

![image](https://github.com/vendure-ecommerce/vendure/assets/52907282/b921f9b1-089e-4246-a7cf-12f48b58fcfd)

**Comment by wpplumber** [comment]
@michaelbromley, what is the best way to work on this issue?

**Comment by michaelbromley** [comment]
Hi! Thanks for bringing this to my attention. I just took a look and saw that we are failing to use the `title` property in that list. This will be fixed in the upcoming patch release.

**Comment by wpplumber** [comment]
What are the term in case I want to participate with Angular contribution, is it best to create an issue and wait for feedback or going straight to PR?

**Comment by wpplumber** [comment]
Clear, thank you.
