### ISSUE TITLE
removeItemFromOrder not directly removing the order line from the order

### ISSUE THREAD

**Issue by nicoes** [vendure-ecommerce/vendure#2345]
**Describe the bug**
The removeItemFromOrder mutation is not always directly removing the order line from the order. When I perform a removeItemFromOrder mutation and getting the order lines from the active order in the response the order lines often still contain the removed order line.

Some notes:
- If I refetch the active order with a query a fraction later, then the order line is removed.
- Promotions on the order are directly updated accordingly. This seems to work as expected.
- If I use adjustOrderLine with an adjustOrderLineQuantity of 0 instead of removeOrderLine, I see exactly the same behaviour. When looking at the source code they also seem to be doing more or less the same thing (when adjustOrderLineQuantity is set to 0) so I think the bug is in that area:

```
    order.lines = order.lines.filter(l => !idsAreEqual(l.id, orderLine.id));
            await this.connection.getRepository(ctx, OrderLine).remove(orderLine);
            this.eventBus.publish(new OrderLineEvent(ctx, order, orderLine, 'deleted'));
            updatedOrderLines = [];
```

Maybe there is some asynchronous operation here?

**To Reproduce**
Could not consistently reproduce it, that is why I've been putting off reporting it. I have a feeling it's something state related.

**Expected behaviour**
Order line is removed and correct active order state is returned on mutation response.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.5
 - Node.js version: 18
 - Database (mysql/postgres etc): mysql

**Additional context**
I can send a demonstration video if deemed useful

**Comment by michaelbromley** [comment]
Hi, unfortunately I am unable to reproduce this locally. I'm wondering whether there could be some custom code that may be related to this issue. Anything like custom OrderProcess, database subscribers etc?

**Comment by martijnvdbrug** [comment]
@michaelbromley We're looking into making a minimal reproduction, I'm pretty sure we don't have any logic that touches the add item to order logic.

**Comment by nicoes** [comment]
@michaelbromley we can't provide any more info to reproduce it. It sometimes happens, and other times doesn't happen. Maybe for now we park this until we can provide more information.

**Comment by nicoes** [comment]
I have reproducable steps now in our specific environement. As soon as we set customer data and the shipping method the removeOrderLine and adjustVariantQuantity start behaving differently. I also notice that promotions and discounts start showing different applied promotions and discounts.

<img width="739" alt="Screenshot 2023-10-11 at 09 56 14" src="https://github.com/vendure-ecommerce/vendure/assets/642209/aa75a4c5-c72a-4b87-8d33-68301115e1f6">

**Comment by michaelbromley** [comment]
@nicoes would you be able to provide a step-by-step instruction to reproduce? Or even better, a failing e2e test (I understand if that's a bit complex).

**Comment by nicoes** [comment]
Hey Michael,
Thanks for getting back. We have attempted to do the reproduction with an e2e test. Unsuccessful thus far.

Since we went live on tuesday I can provide you with steps to reproduce:
1. https://huidpraktijkshop.nl/product/dermaceutic-mela-cream
2. Go to the cart
3. Enter a discount coupon code in the coupon input box (I'll send it in a DM)
4. Expected: The coupon code is applied directly.
5. Remove the coupon code
6. Go to the check-out page.
7. Fill out your check-out data.
8. Shipping methods should appear
9. Go back to the cart.
10. Enter the same coupon code again.
11. Actual: you don't see the discount applied. Expected: You should see the discount applied again like on step 4.
12. Go again to the check-out. It will again fetch shipping methods.
13. Expected: you now should see the discount applied in the order summary in the bottom of the check-out.

It looks like the mutations on the check-out trigger a reevaluation of the applied promotions and fix it. Where I expected it to show in the cart already.

**Comment by nicoes** [comment]
Hey there. Today I also noticed that with the same flow (add 10 products, go to check-out, remove order lines) I can get wrong subtotals. E.g.:

<img width="1010" alt="Screenshot 2023-10-26 at 07 21 15" src="https://github.com/vendure-ecommerce/vendure/assets/642209/22e798f7-4066-4417-a797-4a9c9af5f105">

**Comment by martijnvdbrug** [comment]
In addition to the above: subtotal should be `149.45` instead of `175.00`. I have a feeling this is caused by the incorrect promotions or order lines not being removed.

**Comment by michaelbromley** [comment]
Hi, do you have any custom PromotionActions that might be active here?

And does the `175.00` figure correspond to the subtotal prior to removal of an order line?

I'm wondering whether somehow the line gets removed but the subtotal does not get recalculated? But that should not be possible since the whole operation is done inside a transaction.

**Comment by martijnvdbrug** [comment]
> Hi, do you have any custom PromotionActions that might be active here?
In this case, just free shipping.

> And does the 175.00 figure correspond to the subtotal prior to removal of an order line?
Not sure, I think this order is from a customer, so I don't think we can know what the previous order lines of this order were.

> I'm wondering whether somehow the line gets removed but the subtotal does not get recalculated? But that should not be possible since the whole operation is done inside a transaction.
I have a feeling it's something like this. I'll look into our custom if we accidentally use any TypeOrm stuff directly, bypassing transactions (Don't think so).

We are still looking into creating a minimal reproduction.

**Comment by martijnvdbrug** [comment]
I'm just going to post all my current findings here, in case something pops to mind when you read this:

* The issue seems to be caused by a previously applied promotion still present on `orderLine.adjustments`. In this case it's a promotion that is not applicable anymore for that order line.


:hourglass_flowing_sand: Still investigating, will update here...

**Comment by michaelbromley** [comment]
Thank you so much for the in-depth investigation and findings!

> for some reason removes the order.discounts from the object

I suspect that this has something to do with the fact that `Order.discounts` is a getter rather than a regular property. I'll see if I can create a failing test case that reproduces this behaviour and find a way to make it work properly.

**Comment by michaelbromley** [comment]
@martijnvdbrug I attempted to create a failing e2e test to reproduce the hydration issue, see the commit linked above. However, I can't yet reproduce it.

If you get any time to put together a reproduction test, I'll be able to dig in and get it fixed.

**Comment by martijnvdbrug** [comment]
Will do!

**Comment by michaelbromley** [comment]
@martijnvdbrug In the last release I fixed a bug in the EntityHydrator which might _possibly_ be related, although in my testing it only manifested when using postgres.

- #2546  

worth bearing in mind as you try to make a reproduction

**Comment by mschipperheyn** [comment]
As a post mortem, I'd like to add that `runPromotionSideEffects` uses an optimization, incorrectly in my opinion, that evaluates if a promotion already exists to skip recalculation or removal for some promotion. IMHO if the contents of the cart changes, all promotions need to be completely recalculated, because of possible interdependencies and side effects.
