### ISSUE TITLE
Custom data column UI for customField of type relation

### ISSUE THREAD

**Issue by BijanRegmi** [vendure-ecommerce/vendure#2347]
**Is your feature request related to a problem? Please describe.**
Currently, the data column shows an object tree for fields of relation type. For example, if I had a customField asset in a orderLine then the asset would be shown as object tree in the orderLine table.

**Describe the solution you'd like**
It would be better if the user could define their own UI for such fields.

**Describe alternatives you've considered**
At the moment, I've considered registering a DetailComponent in the order detail page and show a custom table with my own UI implementation.

**Additional context**
Screenshot:
![image](https://github.com/vendure-ecommerce/vendure/assets/55084653/62bea5b3-c610-42d3-b419-06d219758e18)

**Comment by michaelbromley** [comment]
Will be available in v2.1. You can test this out on the `@next` release tag.
