### ISSUE TITLE
Product query doesn't refer only to current channel stock location

### ISSUE THREAD

**Issue by lzzfnc** [vendure-ecommerce/vendure#2356]
We have a multi channel - multi sellers setup, where every seller relies on a different stock location. 
When querying a product there is an unexpected behaviour regarding the stockLevel, that seems to take into account not only the current channel stock location, but also all the others. If there are no saleable units in the current stock location, but they are still available in other locations, the product query will return IN_STOCK. 

### To Reproduce

1. Set up two channels `channel-A` and `channel-B`
2. Create two stock locations` stock-A` and `stock-B`
3. Edit a Product Variant in order to set its available stock
4. `out-of-stock-threshold` is set to 0 as default
5. `channel-A` refers only to `stock-A`, same for the other
6. Set `stock-A` to 0
7. Set `stock-B` to 10
8. Query the product with the shop-api a in the `channel-A` and check for `stockLevel`
9. The query returns `stockLevel: IN_STOCK`
10. Eventually, the product can be added to an order and purchased
11. This allocate 1 item in the `channel-A`, and even to fullfill the order, leading to a negative stock amount. 

### Expected behavior

The query should return `stockLevel: OUT_OF_STOCK`, since `stock-A` has been set to zero.

**Environment (please complete the following information):**
 - @vendure/core version: **2.0.0**
 - Nodejs version: **16**
 - Database: **postgres**

**Comment by michaelbromley** [comment]
Thanks for the report. This behaviour is the responsibility of the `StockLocationStrategy`. 

> The StockLocationStrategy is responsible for determining which {StockLocation}s
should be used to fulfill an {OrderLine} and how much stock should be allocated
from each location. It is also used to determine the available stock for a given
{ProductVariant}.

By default, Vendure uses the `DefaultStockLocationStrategy` which is documented thus:

> The DefaultStockLocationStrategy is the default implementation of the {StockLocationStrategy}.
It assumes only a single StockLocation and that all stock is allocated from that location.

You can see the source here: https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/config/catalog/default-stock-location-strategy.ts#L28

So _technically_ what you report is "working as intended" but yeah, we should probably look at what we can do better here.

I see the following options:

1. Better documentation. I've made a start on this, the new beta docs include a section on stock control which covers this: https://beta-docs.vendure.io/guides/core-concepts/stock-control/#selecting-a-stock-location
2. It should also be covered in the multi-vendor marketplace guide, which it currently isn't.
3. We should make the `DefaultStockLocationStrategy` just handle this automatically.

**Comment by lzzfnc** [comment]
Thanks for the detailed explanation! 
Did you had perhaps the chance to look into the `MultiChannelStockLocationStrategy`?
