### ISSUE TITLE
Minor syntax errors on Plugin docs

### ISSUE THREAD

**Issue by Japhet-github** [vendure-ecommerce/vendure#2359]
- Syntax errors on Plugin beta docs: 
(https://github.com/vendure-ecommerce/vendure/pull/2358)

- In Step 2 (https://vendure-docs-beta.netlify.app/guides/developer-guide/plugins/#step-2-define-an-entity), I have an error in VS Code:
```Module '"@vendure/core"' has no exported member 'EntityId'.ts(2305)```
I have no clue whether it's a syntax error, or is it something that is need for the plugin to work.

**Comment by michaelbromley** [comment]
Hi, I'm gonna close this as the EntityId decorator is now exported from core 👍
