### ISSUE TITLE
With custom order process fulfill order button is not getting enabled

### ISSUE THREAD

**Issue by shaheerrs** [vendure-ecommerce/vendure#2373]
**Describe the bug**
Fulfill Order button in admin-ui is not getting enabled if there are any partial cancellation of the order after payment settled state.

1) Customer place the order
2) Order moved to payment settled status, **_Now starts our custom order process_**
3) Order waiting for approval process form Customer support Agent(CS Agent). CS Agent calls customer to confirm as we are operating on COD heavy geography & Drop ship - in this step order can be cancelled 100% OR can cancel line item. 
4) CSAgent approve the order based on customer response.
5) Fulfillment has to be enabled - (in current code the button is disabled after the step 4)

**To Reproduce**
1) Create a custom order process as follows 
      ```
      transitions: {
              PaymentSettled: {
                  to: ['StockApproved', 'Cancelled'],
                  mergeStrategy: 'replace',
              },
              StockApproved: {
                  to: ['OrderApproved', 'Cancelled']
              },
              OrderApproved: {
                  to: ['Packed', 'Shipped', 'PartiallyShipped', 'Cancelled']
              },
              Packed: {
                  to: ['Shipped', 'PartiallyShipped', 'Cancelled'],
                  mergeStrategy: 'merge'
              },
              Shipped: {
                  to: ['Delivered', 'PartiallyDelivered', 'DeliveryFailed'],
                  mergeStrategy: 'replace',
              },
              PartiallyShipped: {
                  to: ['Shipped', 'Delivered', 'PartiallyDelivered', 'DeliveryFailed'],
                  mergeStrategy: 'replace',
              },
              PartiallyDelivered:{ 
                  to: ['Delivered', 'Closed'],
                  mergeStrategy: 'replace'
              },
              Delivered: {
                  to: ['AmountCollected', 'Closed'],
                  mergeStrategy: 'replace'
              },
              AmountCollected: {
                  to: ['Closed'],
              },
              DeliveryFailed: {
                  to: ['RTO', 'Closed'],
              },
              Completed: {
                  to: []
              },
              Closed: {
                  to: []
              },
              Cancelled: {
                  to: ['Closed'],
                  mergeStrategy: 'replace'
              },
              RTO: {
                  to: ['Closed']
              }
      },
      ```
2) Place order and move order to payment settled state
3) Use cancel / refund option to cancel an item from the order
4) Move order to StockApproved 
5) As next step move the order to Order Approved after the customer call and partial cancellation similar to above step. 

Once we reach the above 5 steps is when we create the Purchase order as we do a lot of Drop Ship orders. Post this is when the fulfillment starts, But as there were partial cancellation in the step 3 / 5 the fulfill button is not enabled and not allowed to do the fulfillment. 

**Expected behavior**
Expected to have Fulfill order button enabled for the above scenario.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.5 & 2.0.6
 - Nodejs version: 16 & 19
 - Database (mysql/postgres etc): postgres

**Comment by shaheerrs** [comment]
@michaelbromley 
What difference I see is in my status transition is after item cancellation I cannot see the **_transition from Pending to Settled_**

**Comment by shaheerrs** [comment]
<img width="929" alt="Screenshot 2023-09-07 at 6 55 20 PM" src="https://github.com/vendure-ecommerce/vendure/assets/45445534/959a3f23-6eef-4d42-9b26-33365ecab1de">

here the refund button is disabled to refund settle, this could be the issue...

**Comment by shaheerrs** [comment]
Thanks @michaelbromley  for the support, and what I was doing wrong was issue with refund and settle. 

Now am able to cancel once, but if I cancel again it cancel the line item and its not processing refund with an error in Backoffice as `{"errors":[{"message":"Cannot return null for non-nullable field Refund.lines.","locations":[{"line":237,"column":5}],"path":["cancelOrder","payments",0,"refunds",0,"lines"]}],`

**Comment by hemantchhonkar** [comment]
I am also facing the same issue. I get the same error if I try to cancel any line item a second time. Works for the very first time.

Help will be much appreciated.

Thanks 


Request -
![image](https://github.com/vendure-ecommerce/vendure/assets/25863836/d3c37049-d125-44bd-9b8b-db0a12185951)


Response- 

![image](https://github.com/vendure-ecommerce/vendure/assets/25863836/03645457-4140-4765-be86-f1dd8b0c1a64)

**Comment by hemantchhonkar** [comment]
Hi, @michaelbromley  this issue has been a blocker for us. I tried everything, but couldn't figure it out. Would really appreciate it if you could help.

Thank you.

**Comment by michaelbromley** [comment]
@hemantchhonkar can you provide an exact sequence of steps to arrive at this error, including any config? Basically if I can take a clean install, and quickly reproduce the issue, then I'll be able to fix it. As it stands I'm not 100% clear on the reproduction steps.

**Comment by shaheerrs** [comment]
This issue is fixed with future releases,
