### ISSUE TITLE
Unable to use the lowercase letter 'f' in the product description field when variants exist

### ISSUE THREAD

**Issue by is0utfitters** [vendure-ecommerce/vendure#2384]
**Describe the bug**
Unable to use the lowercase letter 'f' in the product description field when variants exist

**To Reproduce**
1. Create a product with at least one option
2. Edit the description and press the letter 'f'
3. Observe the variant list filter menu pops up rather than the letter 'f' in the description field
![Screenshot 2023-09-05 at 6 10 25 PM](https://github.com/vendure-ecommerce/vendure/assets/28570944/0137d7a3-f1eb-451e-a5e5-f2874b16d9aa)

**Expected behavior**
The letter 'f' should work in the description field when editing the description rather than attempting to add a variant list filter.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.6
 - Nodejs version: 18.17.1
 - Database (mysql/postgres etc): postgres

**Additional context**
Seems to work fine when initially adding the product, just not after adding options.

**Comment by jyling** [comment]
Reproducible on https://demo.vendure.io/admin/catalog/inventory/47 on 07 Sep 2023
