### ISSUE TITLE
Customize Facets/Categories pages

### ISSUE THREAD

**Issue by bastianhilton** [vendure-ecommerce/vendure#2386]
**Is your feature request related to a problem? Please describe.**
In other ecommerce systems you are able to customize how a category/facet page looks such as with images, text, html, etc. 

**Describe the solution you'd like**
A built in editor to add content would be nice and allow it to be available through the api.

**Describe alternatives you've considered**
The alternative would be to have category pages within another system and have them match up with Vendure's facets when pulled through to the frontend.

**Additional context**

**Comment by michaelbromley** [comment]
Hi,

Currently the Collection entity has a "description", which in the Admin UI is controlled by a rich text editor which is capable of having images and other html elements.

While no similar field exists for Facets, it is possible to add a custom field which works in exactly the same way.

If this does not satisfy your use case, please let me know exactly how you imagine a different system working. If you can include examples (mockups, API suggestions) that makes it easier for me to understand what is being proposed. 👍

**Comment by bastianhilton** [comment]
Ok i misunderstood the use case of Collections and Facets, I think i mixed them up, Collections in this case are more like Categories while Facets act more like Product Types and Product Attributes.

**Comment by michaelbromley** [comment]
Yep exactly. I'll close this now - leave any feedback you have on the docs in the other issue where I linked then 👍
