### ISSUE TITLE
Multi-level facets

### ISSUE THREAD

**Issue by bastianhilton** [vendure-ecommerce/vendure#2387]
**Is your feature request related to a problem? Please describe.**
Would like to have multiple levels of facets such as Music > Radio > Pop

**Describe the solution you'd like**
Deeper levels for Facets such as Apparel > Womens > Shoes

**Describe alternatives you've considered**
Alternatives within Vendure would be to create all facets/categories regardless of their level, gets confusing on the frontend when pulling the data.

**Additional context**

**Comment by michaelbromley** [comment]
Hi, 

For a hierarchical taxonomy like you describe, the usual solution is to use nested Collections. Have you tried that? Like in the demo storefront: https://remix-storefront.vendure.io/collections/electronics

**Comment by bastianhilton** [comment]
Ok i actually misunderstood the use case of Facets and Collections, Collections are like categories while facets are more like product types

**Comment by michaelbromley** [comment]
There is some more info in the new docs which might be helpful:

- Facets: https://beta-docs.vendure.io/guides/core-concepts/products/#facets
- Collections: https://beta-docs.vendure.io/guides/core-concepts/collections

Let me know if that makes it more clear. I'm open to feedback which makes the new docs easier to understand :)

**Comment by dlhck** [comment]
This issue is being closed because further data was needed but was not provided. If you want to continue the thread, comment below with the required information and the issue can be re-opened.
