### ISSUE TITLE
createRefund not taking promotions into account

### ISSUE THREAD

**Issue by jacobfrantz1** [vendure-ecommerce/vendure#2393]
**Describe the bug**
When canceling and refunding a order that has promotions applied. The refundOrderLinesTotal doesn't account for promotions. The payment is properly refunded, but there is an error as it looks for another payment to cover the total, and the refund on vendure's side fails.

From the logs:
```
error 9/7/23, 6:58 PM - [Vendure Server] {
  "message": "INTERNAL_SERVER_ERROR: Could not find a Payment to refund",
  "variables": {}
}
Error: Could not find a Payment to refund
    at PaymentService.createRefund (/home/app/node_modules/@vendure/core/dist/service/services/payment.service.js:253:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async OrderService.refundOrder (/home/app/node_modules/@vendure/core/dist/service/services/order.service.js:1088:16)
debug 9/7/23, 6:58 PM - [Vendure Server] Error: Could not find a Payment to refund
    at PaymentService.createRefund (/home/app/node_modules/@vendure/core/dist/service/services/payment.service.js:253:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async OrderService.refundOrder (/home/app/node_modules/@vendure/core/dist/service/services/order.service.js:1088:16)

```

**To Reproduce**
1.) Cancel and Refund order that has promotions applied.
2.) See Error "Could not find a Payment to refund"

**Expected behavior**
The problem may be wide spread, as order line prices are not calculated properly on placed orders.

The problem is here:
https://github.com/vendure-ecommerce/vendure/blob/bd834d030189c7bcc6d42c8be4439ea4b37c2979/packages/core/src/entity/order-line/order-line.entity.ts#L392-L395
and here:
https://github.com/vendure-ecommerce/vendure/blob/7e2c17a64291bbe26364a376a92d6d9fc279ca98/packages/core/src/entity/order-line/order-line.entity.ts#L407-L409
These function exits early as quantity is 0, but orderPlacedQuantity is not 0.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.6
 - Nodejs version: 16.20.1
 - Database (mysql/postgres etc): postgres 14

**Comment by seminarian** [comment]
Oeh, that's a nasty one! :(

**Comment by jacobfrantz1** [comment]
Something to consider that we encounter is when an order is changed, when need to refund the difference to them, the entire payment can't be considered refunded because if the customer wants to cancel later, they need refunded the part that wasn't refunded previously. I would like the redesign of refunds to allow for partial refunds against a payment.

Something else I want to implement, but don't have a good way to currently, is to have a portion of the order be non-refundable, as we sell custom made-to-order products, and calculating and adding an adjustment every time someone cancels is onerous.

**Comment by michaelbromley** [comment]
@jacobfrantz1 thanks for the input. I definitely intend to allow partial refunds (as long as the underlying payment provider allows it, which is mostly the case).

Right now the big issue for me is that the way Refunds are designed, they have to be related to a particular part of the order that is getting refunded (e.g. an order line item, or shipping). I'm not sure if this is useful or not. I'm wondering whether it would make more sense to just simplify refunds and allow the store operator to decide how much to refund from each payment method. Of course we can calculate what we think the refund _should_ be based on e.g. cancelled items, but beyond that maybe just let the store operator have total control and not have Vendure do its own calculations on what it _thinks_ should be an allowable refund in the backend logic as it does currently.

Any thoughts on that?

**Comment by jacobfrantz1** [comment]
The only use case I can think of for linking refunds to order line items is for statistics, which isn't super important.

I think how the refund amount is determined should be a configurable strategy. That would help my use case, though I'm not sure if enough people would find that useful to justify it.

**Comment by martijnvdbrug** [comment]
I agree that separating refunds from cancellation gives us a lot more freedom on how to do refunds. It also feels a more intuitive for me. We could then just manually refund $10, with a manual note like `Broken product, no return`, correct?

As you already said, you can still have the admin UI do a suggestion for a refund when you cancel an order item.

:question: What happens with the order when you refund $10, but don't cancel any items? E.g:
1. An order is placed with 3 items, with a total of $100
2. A manual refund is created for $10
3. The order still has 3 items

Will the order total still be $100, or will it be $90? I'm thinking about this from an invoice perspective, where the invoice should reflect the actual amount paid. (So, $90 should be on a re-created invoice after refund)

**Comment by michaelbromley** [comment]
Related:

- https://github.com/Pinelab-studio/pinelab-vendure-plugins/issues/103

**Comment by michaelbromley** [comment]
@martijnvdbrug good question. I'm not sure, I'd need to research how other systems handle this.

Here's a video that show's Shopify's refund process - it is very simple and follows the idea I outline above where the system will calculate the refund amount based on the selected products being refunded, but also just allows the amount to be set manually.

https://www.youtube.com/watch?v=Tk0DZd4MSCU&t=64s
