### ISSUE TITLE
Could not find a Payment to refund if we try to refund a  fulfillment order

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#2396]
**Describe the bug**

```
 error 9/15/23, 5:35 PM - [Vendure Server] {
31|kzfoo-s |   "message": "INTERNAL_SERVER_ERROR: Could not find a Payment to refund",
31|kzfoo-s |   "variables": {}
31|kzfoo-s | }
31|kzfoo-s | Error: Could not find a Payment to refund
31|kzfoo-s |     at PaymentService.createRefund (/opt/applications/production/kzfoo-srv/node_modules/@vendure/core/dist/service/services/payment.service.js:253:23)
31|kzfoo-s |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
31|kzfoo-s |     at async OrderService.refundOrder (/opt/applications/production/kzfoo-srv/node_modules/@vendure/core/dist/service/services/order.service.js:1088:16) 
```
**To Reproduce**
1.  Placed an order with two product variant
2. Make a payment settled
3. Create fullfillment , flag it as `delivered`
4. try refund with `cannceled` flag it will throw above error

**Expected behavior**
 can be correct refund also

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.7
 - Nodejs version: 18
 - Database (mysql/postgres etc): mysql

**Additional context**

**Comment by michaelbromley** [comment]
Hi, I just followed the reproduction steps and did not get an error. Are you able to reproduce on a clean install?

**Comment by tianyingchun** [comment]
yes, in my local it seems not reproduction, if i encounter again, i will reopen this.
