### ISSUE TITLE
[docs] Better documentation for WorkerService

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#240]
The documentation for running code on the worker process is quite sparse:

* https://www.vendure.io/docs/developer-guide/plugins/#running-processes-on-the-worker
* https://www.vendure.io/docs/typescript-api/worker/worker-service/

but more explanation is needed e.g. of the role the WorkerMessage plays etc.

**Comment by lsimone** [comment]
Totally agree.

I think it would also be useful for devs to have even a short paragraph about EventBus and Vendure Events in general, maybe with a very small snippet, since they are a powerful tool for building plugins and custom features

**Comment by michaelbromley** [comment]
There's now a complete example of using the WorkerService in a plugin: https://www.vendure.io/docs/plugins/plugin-examples/#running-processes-on-the-worker
