### ISSUE TITLE
Bug: 'f' opens filter in product description field

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#2404]
**Describe the bug**
On the Product detail page in the admin, when I type the letter 'f', it will open a filter menu, which doesn't really make sense on a product page.

**To Reproduce**
1. Go to a product detail in the admin
2. Type the letter 'f' in a product description
3. See the filter menu being opened.

**Expected behavior**

1. I would not expect the filter menu to open on the product page
2. Also, I can not search for anything with the letter 'f' on the product listing page, as that will also open the filter menu! Would it make sense to bind this to ctrl-f or shift-f ?

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.5
 - Nodejs version: 18
 - Database (mysql/postgres etc): mysql

**Comment by michaelbromley** [comment]
The issue with pressing "f" in the product description should be fixed in the latest version, 2.0.7. 

> Also, I can not search for anything with the letter 'f' on the product listing page, as that will also open the filter menu! Would it make sense to bind this to ctrl-f or shift-f ?

Can you provide exact reproduction steps (test on latest version) - I was sure this was fixed.

**Comment by martijnvdbrug** [comment]
Correct, it is fixed indeed! My bad. So, no alternative short key for filtering? (Ffine by me!)
