### ISSUE TITLE
Make @vendure/create generate ESM projects

### ISSUE THREAD

**Issue by stefanvanherwijnen** [vendure-ecommerce/vendure#2407]
**Is your feature request related to a problem? Please describe.**
At the moment, @vendure/create generates a CJS project.

**Describe the solution you'd like**
It would be nice if the generated Vendure app would be an ESM project (i.e. "type": "module") and that the generated dist code is also ESM.
This requires a change to `tsconfig.json` `"module": "ES2022"` and references to things like `__dirname` will have to be changed to `import.meta.url` equivalents.

An advantage is that the generated dist files can be directly edited/replaced by files with a similar syntax to the rest of the project (ESM). This would enable the creation of a Docker image in which `vendure-config.js` can easily be replaced with a Docker volume mapping (https://github.com/vendure-ecommerce/vendure/discussions/2231). 
And the change to ESM will have to be made eventually anyway (in my opinion :smile: )

However, this might break any plugins that depend on things like `__dirname` etc.

**Comment by michaelbromley** [comment]
Hi,

I believe we'd be blocked on this until NestJS has proper support for for ESM. See:

- https://github.com/nestjs/nest/issues/13319

I'm going to close this for now but we can re-open at a future time when it is more practical for the majority of users to have ESM as the default.
