### ISSUE TITLE
Allow custom fields to be added to Vendure tabs

### ISSUE THREAD

**Issue by mschipperheyn** [vendure-ecommerce/vendure#2409]
**Is your feature request related to a problem? Please describe.**
This might be a documentation request or a feature request. 

I have a `originalPrice` custom field that I'm adding to the product variant form. This field should live next to the price field. However, as a custom field, it gets added to a custom field tab. 

**Describe the solution you'd like**
I'm not sure if this is currently possible. If not, I would consider this a nice to have feature request.
If it is possible I would suggest some documentation on how to do this: reference the "system tab names" to put fields there. I couldn't find it in the beta docs. 

**Describe alternatives you've considered**
Perhaps I should actually put a new property to the product model instead of a custom field. 

**Additional context**

**Comment by michaelbromley** [comment]
Hi,

So if I understand correctly you want to be able to add custom fields into this card in the Admin UI?

![image](https://github.com/vendure-ecommerce/vendure/assets/6275952/adc906cb-dd8d-4207-8409-22edfd3a28a1)

If so, then that's not currently possible. Even adding a custom property to the model will not enable you to do this. 

So let's consider this a feature request.

**Comment by dlhck** [comment]
This issue is being closed because further data was needed but was not provided. If you want to continue the thread, comment below with the required information and the issue can be re-opened.

**Comment by dlhck** [comment]
This issue is being closed because further data was needed but was not provided. If you want to continue the thread, comment below with the required information and the issue can be re-opened.
