### ISSUE TITLE
Edit image not working at AssetPickerDialogComponent

### ISSUE THREAD

**Issue by brunoslalmeida** [vendure-ecommerce/vendure#2411]
**Describe the bug**
The button edit from image picker is not working. Clicking it gives the following error:

![Captura de Tela 2023-09-24 às 16 58 25](https://github.com/vendure-ecommerce/vendure/assets/3662370/51bb66cb-085a-47e8-9249-2ac5a5a34137)

**To Reproduce**
using the oficial demo (https://demo.vendure.io/)

1. Go to Inventory
2. Click on Add Asset
<img width="692" alt="Captura de Tela 2023-09-24 às 16 59 35" src="https://github.com/vendure-ecommerce/vendure/assets/3662370/aedbd689-5cb2-4837-aaf7-7b209dad4b25">

3. Select a image
4. Click the edit button
<img width="1136" alt="Captura de Tela 2023-09-24 às 17 00 13" src="https://github.com/vendure-ecommerce/vendure/assets/3662370/40f9fda3-ecc9-4f6a-b2c3-a5a62ddc10dc">

**Expected behavior**
The edit page open

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.7

**Additional context**
The bug can be reproduced at the oficial demo website.

**Comment by brunoslalmeida** [comment]
The error relies at the url formation. Trying to reproduce it from the Asset page from Catalog, it does not happen, but when going to the Asset Dialog, it happens. Check the url at the left down corner.

<img width="1026" alt="Captura de Tela 2023-09-24 às 17 05 48" src="https://github.com/vendure-ecommerce/vendure/assets/3662370/7ddc4772-3d81-4bab-a5d8-6047ecd0d6e9">

<img width="1191" alt="Captura de Tela 2023-09-24 às 17 06 03" src="https://github.com/vendure-ecommerce/vendure/assets/3662370/e702b93d-6bb7-4e81-acdd-39dc440fcf20">

**Comment by brunoslalmeida** [comment]
I am assuming that this might being caused by the relative path used at Asset-Galley component.

[<div *ngIf="selectionManager.selection.length === 1">
    <a [routerLink]="['./', lastSelected().id]" class="button-ghost">
        <clr-icon shape="pencil"></clr-icon> {{ 'common.edit' | translate }}
        <clr-icon shape="arrow right"></clr-icon>
    </a>
</div>](https://github.com/vendure-ecommerce/vendure/blob/0740c8733458207ab12fbccd05cd225c6bb6cca2/packages/admin-ui/src/lib/core/src/shared/components/asset-gallery/asset-gallery.component.html#L48)

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. Yes, your diagnosis is correct - that `routerLink` directive needs to have the full path, not a relative one.
