### ISSUE TITLE
Stripe Payment plugin support "Accept International Payments from India"

### ISSUE THREAD

**Issue by duypv** [vendure-ecommerce/vendure#2412]
**Is your feature request related to a problem? Please describe.**
Stripe for India require: name, billing address, shipping address or description  in paymentIntent
 
**Describe the solution you'd like**
Can be define it in init plugin. Example
![image](https://github.com/vendure-ecommerce/vendure/assets/7984688/ccd99aee-757d-4a96-b94d-743d5eaf9575)

**Describe alternatives you've considered**
I had fork payment plugin and hard in code.
![image](https://github.com/vendure-ecommerce/vendure/assets/7984688/6eccff03-230b-46eb-9d43-0892224e1c8c)

```
const newStripeCustomer = await stripe.customers.create({
                email: customer.emailAddress,
                name: ${customer.firstName} ${customer.lastName},
                address: {
                    line1: customer.addresses[0]?.streetLine1 || order.shippingAddress?.streetLine1,
                    postal_code: customer.addresses[0]?.postalCode || order.shippingAddress?.postalCode,
                    city: customer.addresses[0]?.city || order.shippingAddress?.city,
                    state: customer.addresses[0]?.province || order.shippingAddress?.province,
                    country: customer.addresses[0]?.country.code || order.shippingAddress?.countryCode,
                },
            });

```
 

**Additional context**
Document here: https://stripe.com/docs/india-accept-international-payments
"@vendure/core": "^2.0.6"

**Comment by michaelbromley** [comment]
Thanks for the info on this.

So if I understand correctly, we need to be able to:

1. Customize the API call to Stripe which creates the customer to include additional fields
2. Customize the API call to Stripe which creates the payment intent to include additional fields.

I propose that we expose this functionality in a similar way to how metadata is handled: you can provide a custom function which returns the extra fields to be added. This can be an async function so you can look up any other data you need.

**Comment by duypv** [comment]
yes, that right.

**Comment by michaelbromley** [comment]
This will be in the next pre-release for v2.1 👍
