### ISSUE TITLE
configurable `ui-language-switcher-dialog.component.ts`

### ISSUE THREAD

**Issue by HoseinGhanbari** [vendure-ecommerce/vendure#2413]
**Is your feature request related to a problem? Please describe.**
some default values inside `ui-language-switcher-dialog.component.ts` are not configurable.

**Describe the solution you'd like**
I need to set/overwrite default value for `selectedCurrencyCode` & `currentLocale ` and also limit the items inside `availableLocales` array.

**Describe alternatives you've considered**
 The currency code used (USD) could be already fetched from the current channel's default - that would be a sensible default behaviour. The currentLocale can already be set using
```ts
AdminUiPlugin.init({
  adminUiConfig: {
    defaultLocale: 'XX',
  }
})
```

**Additional context**
By the way it is it really useful if we could customize the default values mentioned above like the ones inside vendure-config or any other way. Also note that when you target specific country or region for an e-commerce you are probably targeting the currency, locale, language etc so it would be nice to reflect these targets on the backend and admin-ui and we should not always consider whether the user browser has the right locale or has visited us before or not.

**Comment by Iamshankhadeep** [comment]
@michaelbromley should I pick this up?

**Comment by michaelbromley** [comment]
Hi @Iamshankhadeep - sorry I missed your message.

Yes, you are welcome to submit a PR for this issue 👍
