### ISSUE TITLE
Create a customer without an email address

### ISSUE THREAD

**Issue by promisetochi** [vendure-ecommerce/vendure#2415]
**Is your feature request related to a problem? Please describe.**
I'm migrating a store from Shopify to Vendure and there are customers without email address.

**Describe the solution you'd like**
Ideally to be able to create a customer without requiring email address.

**Describe alternatives you've considered**
None yet. Not sure how to work around it.

**Additional context**
None.

**Comment by michaelbromley** [comment]
Hi,

Currently the `emailAddress` field of Customer is non-nullable, but is there any other sort of identifier you could put in there? Like a unique ID from Shopify?

**Comment by promisetochi** [comment]
Yes @michaelbromley. That should be a sufficient workaround.
