### ISSUE TITLE
async `getAvailableStock` breaks order process

### ISSUE THREAD

**Issue by lzzfnc** [vendure-ecommerce/vendure#2422]
I need to perform async operations in the `getAvailableStock` method in order to implement a custom StockLocationStrategy, but I'm facing a bug.  

To implement a multi-channel && multi-stock location strategy I'm trying to hydrate the related stockLocation's channels and test them against the context session's active channel. Every channel refers to a precise stock location, so I need to filter the stockLevels array depending on that.  

The [exported interface](https://github.com/vendure-ecommerce/vendure/blob/9b51f4ea871a97757303adf73dbdc6417f42ca30/packages/core/src/config/catalog/stock-location-strategy.ts#L54) seems to accept already async functions, and in fact the custom strategy seems to work. 

This is the `getAvailableStock` I've written to address that behavior. 

```
async getAvailableStock(
	ctx: RequestContext,
	productVariantId: ID,
	stockLevels: StockLevel[]
): Promise<AvailableStock> {
	await Promise.all(
		stockLevels.map(async (sl) =>
			this.entityHydrator.hydrate(ctx, sl, {
				relations: ["stockLocation.channels"],
			})
		)
	);

	let stockOnHand = 0;
	let stockAllocated = 0;

	let stockLevel = stockLevels.find((sl) =>
		sl.stockLocation.channels.some((ch) => idsAreEqual(ctx.session?.activeChannelId, ch.id))
	);

	if (stockLevel) {
		stockOnHand = stockLevel.stockOnHand;
		stockAllocated = stockLevel.stockAllocated;
	}

	return { stockOnHand, stockAllocated };
}
```

With this code, the storefront works fine, and it displays currectly the availability of a product when switching between channels. When it comes to placing an order, however, the state gets stuck and cannot proceed to the `ArrangingPayment` status, even though I'm able to perform the payment and Stripe currectly receives the money.  

Could this be a problem related to the async state of the method? Even with debug level of logging, I get no errors printed in the console.

**Comment by michaelbromley** [comment]
Hi,

In the storefront, when you execute this mutation, what is the result?

```gql
mutation Transition {
  transitionOrderToState(state: "ArrangingPayment") {
    ... on Order {
      id
      code
      state
      total
    }
    ... on ErrorResult {
      errorCode
      message
    }
    ...on OrderStateTransitionError {
      transitionError
      fromState
      toState
    }
  }
}
```

**Comment by lzzfnc** [comment]
Hey there! I returned on this after some time adjusting these two methods as follow:

```
async getAvailableStock(ctx: RequestContext, productVariantId: ID, stockLevels: StockLevel[]): Promise<AvailableStock> {
	await Promise.all(
		stockLevels.map(async (sl) =>
			this.entityHydrator.hydrate(ctx, sl, { relations: ["stockLocation.channels"] })
		)
	);
	let stockOnHand = 0;
	let stockAllocated = 0;
	for (const stockLevel of stockLevels) {
		let channels = stockLevel.stockLocation.channels.map((ch) => ch.id);
		if (!channels.includes(ctx.channelId)) continue;
		stockOnHand += stockLevel.stockOnHand;
		stockAllocated += stockLevel.stockAllocated;
	}
	return { stockOnHand, stockAllocated };
}
```

```
async forAllocation(ctx: RequestContext, stockLocations: StockLocation[], orderLine: OrderLine, quantity: number): Promise<LocationWithQuantity[]> {
	await Promise.all(
		stockLocations.map(async (sl) =>
			this.entityHydrator.hydrate(ctx, sl, { relations: ["channels"] })
		)
	);

	let location = stockLocations.find((sl) =>
		sl.channels.map((ch) => ch.id).includes(ctx.channelId)
	);

	if (!location) {
		throw new InternalServerError("Location not found");
	}

	return [{ location, quantity }];
}
```

And it seems to work fine! I can complete the order process, and the quantity gets allocated from the correct stock location.

I'm not sure if throwing an error when the location is not found for allocation is the right approach, do you have any suggestion on that?

**Comment by michaelbromley** [comment]
Hi,

In this situation, if you don't throw, then the alternative is to return an empty array, in which case no allocations will be made. If that is not what you want to allow, then throwing is the best option as it indicates some exceptional circumstance that needs to be known and handled.

Other than that, is this issue OK to close now?

**Comment by lzzfnc** [comment]
thanks Michael!
yes, we can close the issue
