### ISSUE TITLE
tsx is not supported in admin UI extensions

### ISSUE THREAD

**Issue by brmk** [vendure-ecommerce/vendure#2425]
**Describe the bug**
We need to extend Admin UI with React components using `registerFormInputComponent`. Currently, it causes a typescript crash when it tries to build the admin UI with the error like this:

```
./src/extensions/e459fa3f5f647b3889ca1606f55b01ea15ca708aaeeb9efb340caec2603f1652/product-option-input/product-option-input.component.tsx - Error: Module build failed (from ../node_modules/@ngtools/webpack/src/ivy/index.js):
Error: /Users/ihorbarmak/workspace/coosh/coosh-api/admin-ui/src/extensions/e459fa3f5f647b3889ca1606f55b01ea15ca708aaeeb9efb340caec2603f1652/product-option-input/product-option-input.component.tsx is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
``` 

**To Reproduce**
1. Create an admin UI extension with React components tsx files in the module
2. Build the admin UI

**Expected behavior**
Successful build

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.9
 - Nodejs version: v16.17.0 
 - Database (mysql/postgres etc): postgres

**Additional context**

The fix is pretty easy and just requires `"tsx": "react"` here in the scaffold `tsconfig.json`:
https://github.com/vendure-ecommerce/vendure/blob/9b51f4ea871a97757303adf73dbdc6417f42ca30/packages/ui-devkit/scaffold/tsconfig.json#L25

Docs: https://www.typescriptlang.org/tsconfig#jsx

**Comment by michaelbromley** [comment]
Hi,

Please note that React/JSX support is only introduced in v2.1 - the beta docs have this note: 
![image](https://github.com/vendure-ecommerce/vendure/assets/6275952/fb36aae4-d9fc-41fa-a0e5-f37134e5614f)

Please try with the latest pre-release, v2.1.0-next.x

**Comment by brmk** [comment]
closing it then. looking forward to 2.1.0 :)

great job!
