### ISSUE TITLE
yarn start error

### ISSUE THREAD

**Issue by ironynet** [vendure-ecommerce/vendure#243]
**To Reproduce**
1. npm init @vendure my-app
2. Running it without changing anything is perfect.
3. start error after edit vendure.config.ts. 
AdminUiPlugin.init({ port: 3002 }) 
==> 
AdminUiPlugin.init({ port: 3002, watch: true }),

error log:
...
...
[run:server] info 1/10/20, 11:40 AM - [Vendure Server] Admin UI live reload: http://localhost:3000/sockjs-node/ -> http://localhost:3002/sockjs-node 
[run:server] info 1/10/20, 11:40 AM - [Vendure Server] ================================================= 
$ ng serve -c=plugin --port=3002 --poll=1000
[run:server] ℹ ｢wds｣: Project is running at http://localhost:3002/webpack-dev-server/
[run:server] ℹ ｢wds｣: webpack output is served from /admin
[run:server] ℹ ｢wds｣: 404s will fallback to /admin/index.html
[run:server] 
[run:server] chunk {main} main.js, main.js.map (main) 1.86 kB [initial] [rendered]
[run:server] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 160 kB [initial] [rendered]
[run:server] chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 505 kB [initial] [rendered]
[run:server] chunk {runtime} runtime.js, runtime.js.map (runtime) 6.09 kB [entry] [rendered]
[run:server] chunk {scripts} scripts.js, scripts.js.map (scripts) 202 kB [entry] [rendered]
[run:server] chunk {styles} styles.js, styles.js.map (styles) 1.97 MB [initial] [rendered]
[run:server] chunk {vendor} vendor.js, vendor.js.map (vendor) 341 kB [initial] [rendered]
[run:server] Date: 2020-01-10T02:41:09.109Z - Hash: 63ca82cf032b6eca6cd9 - Time: 9063ms
[run:server] ** Angular Live Development Server is listening on localhost:3002, open your browser on http://localhost:3002/admin **
[run:server] 
[run:server] ERROR in app/data/data.module.ts:84:9 - error TS2322: Type 'ResolverDefinition' is not assignable to type 'Resolvers | Resolvers[] | undefined'.
[run:server]   Type 'ResolverDefinition' is not assignable to type 'Resolvers'.
[run:server]     Property 'Mutation' is incompatible with index signature.
[run:server]       Type '{ [name: string]: GraphQLFieldResolver<any, ResolverContext, any>; }' is not assignable to type '{ [field: string]: Resolver; }'.
[run:server]         Index signatures are incompatible.
[run:server]           Type 'GraphQLFieldResolver<any, ResolverContext, any>' is not assignable to type 'Resolver'.
[run:server]             Types of parameters 'info' and 'info' are incompatible.
[run:server]               Type '{ field: FieldNode; fragmentMap: FragmentMap; } | undefined' is not assignable to type 'GraphQLResolveInfo'.
[run:server]                 Type 'undefined' is not assignable to type 'GraphQLResolveInfo'.
[run:server] 
[run:server] 84         resolvers: clientResolvers,
[run:server]            ~~~~~~~~~
[run:server] 
[run:server]   ../../../apollo-client/ApolloClient.d.ts:25:5
[run:server]     25     resolvers?: Resolvers | Resolvers[];
[run:server]            ~~~~~~~~~
[run:server]     The expected type comes from property 'resolvers' which is declared here on type 'ApolloClientOptions<any>'
[run:server] 
[run:server] ℹ ｢wdm｣: Failed to compile.

**Environment (please complete the following information):**
 - @vendure/core version: 0.7.0
 - Nodejs version: 12.14.0
 - Database (mysql/postgres etc): mysql

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. At first glance it looks like it could be related to some incompatible typedefs, perhaps some of the typings changed in a recent version of a dependency (possibly Apollo Client or graphql-js).

I'll take some time to try to reproduce when I get a chance (I'm on vacation for the next 2 weeks, so probably after that).

**Comment by ironynet** [comment]
@michaelbromley 
Thank you for the reply. I will test and post again if there is a solution.
Have a nice vacation ...

**Comment by michaelbromley** [comment]
Just looked into this, and it appears to be as expected - in development I am on apollo-client v2.6.4, whereas the latest 2.x version is 2.6.8, which made a change to the type definition of `ApolloClientOptions.resolvers` in this PR: https://github.com/apollographql/apollo-client/pull/4943

I'll attempt to update and pin the apollo-client version to fix this issue. Long-term, I plan to re-work the ui extensions feature once Angular 9 is released so that hopefully this UI app compilation step is no longer needed.

**Comment by ironynet** [comment]
@michaelbromley Thank you for the comment. I will refer to it. The angular version upgrade is also very exciting.
