### ISSUE TITLE
Unable to create fulfillment on orders referencing deleted ProductVariant

### ISSUE THREAD

**Issue by jacobfrantz1** [vendure-ecommerce/vendure#2434]
**Describe the bug**
I have some older orders that our fulfillment integration failed to create a fulfillment for at the time. Currently, I'm unable to create a fulfillment due to the referenced productVariant having been soft deleted. The message in the admin-ui is "No ProductVariant with the id "1de533de-e1d4-40d7-9902-90ab8b4d85d2" could be found".
The order line with the deleted product variant displays correctly in the admin-ui.

**To Reproduce**
1. Get an order to PaymentSettled state
2. Delete the ProductVariant associated with an order line in the order
3. Try creating a fulfillment on the order

**Expected behavior**
Fulfillment should still be created even if ProductVariant is deleted

**Environment:**
 - @vendure/core version: 2.1.0-next.7
 - Nodejs version: 16.20.1
 - Database: postgresql 14

**Comment by rubensmit93** [comment]
Any updates on this?
