### ISSUE TITLE
Allow for partial truncation of test data

### ISSUE THREAD

**Issue by mschipperheyn** [vendure-ecommerce/vendure#2436]
**Is your feature request related to a problem? Please describe.**
The testserver is very useful but it's an all or nothing deal. Also, it doesn't clean the database after each test to level it was after initialData and products were inserted. That makes writing consistent tests more difficult. I want to clear out certain test data for each test. Custom tables I create as part of my plugin. In order to do that, easy access to the connection is needed, which is not sooo easy. 

**Describe the solution you'd like**
I would like the Testserver to expose a retrievable db connection so I can truncate the tables that I created as part of my plugin for each test. Alternatively, I would like direct access to the Services. Having to interact on everything through the Graphql api is cumbersome. Doing that also requires me to effectively write "test specific resolvers" to open up the api functionality I need. E.g. deleting all records of type X is something you would only do in a test scenario. So, it would never be part of the normal api. 

The "auto magical" nature of the dependency injection approach makes it hard to access certain features outside of the container.

**Describe alternatives you've considered**
Creating a custom Testserver with delete options
Creating a little utility dependency injection container that opens up access to Services
Having an option on the test server that, when enabled, truncates all data inserted after initialData and products. It could also be a kind of on the fly image replacement.
Just deleting the test server after each test and accepting the performance loss
Extending TestServer and see what I can get away with accessing

**Additional context**

**Comment by michaelbromley** [comment]
The test server exposes the "app" object, which is an instance of the Nest application and therefore allows you to grab _any_ internal provider and use it directly in your e2e test suite file:

```ts
    beforeAll(async () => {
        await server.init({
            initialData,
            productsCsvPath: path.join(__dirname, 'fixtures/e2e-products-minimal.csv'),
            customerCount: 1,
        });
        
        // Here you can grab a reference to the TransactionalConnection
        // provider (or any other provider for that matter)
        const connection = server.app.get(TransactionalConnection);
        

        await adminClient.asSuperAdmin();
    }, TEST_SETUP_TIMEOUT_MS);
```

**Comment by mschipperheyn** [comment]
Love it!
