### ISSUE TITLE
Expose pre/post - processing events to allow developer to run actions before and after vendure default event handling

### ISSUE THREAD

**Issue by lsimone** [vendure-ecommerce/vendure#245]
**Is your feature request related to a problem? Please describe.**
In order to perform some actions before or after vendure processes an event and make all the needed DB changes, it would be great for developers to have hooks to be used.

i.e: if you want to listen to `OrderStateTransitionEvent` to generate an invoice when an order is paied, actually you cannot use this event, because when it's fired, DB changes due to the transition to a new state have not been done yet by vendure. 
So developer cannot rely on them and does not have a way to (unless it just use a delay to wait for them...that's not a solid strategy, obviously).

**Describe the solution you'd like**
It would be useful to have either pre/post events for [any of the events vendure exports](https://www.vendure.io/docs/typescript-api/events/event-types/), or a way to specify that the listener will fire after/before vendure full event processing.
i.e: 
```
new EmailEventListener(ORDER_SHIPMENT_MAIL)
  .on(OrderStateTransitionEvent, 'afterProcessing|beforeProcessing')
```

**Comment by michaelbromley** [comment]
I've spent a bit of time looking at how the events are published, and in general it seems to be the case that an event is fired _after_ the entity has been modified and persisted to the DB. Example:

https://github.com/vendure-ecommerce/vendure/blob/8c970bf214dc7a04953500cc256057faff6e5e55/packages/core/src/service/services/product.service.ts#L144-L161

The exception to this rule currently is that the `OrderStateTransitionEvent` is currently published _prior_ to the Order being persisted. Also for the other events governed by a finite state machine - namely `PaymentStateTransitionEvent` and `RefundStateTransitionEvent`.

I suspect that the simple fix here is to publish the `OrderStateTransitionEvent` etc. _after_ persisting the Order, following the general rule. This would solve the issue that you had and is much, much simpler than getting into pre/post hooks.

If there are other reasons for pre/post hooks for each event type, then I would re-think this issue, but for now I would go for the simpler option of just always publishing the event _post_ DB update.

**Comment by lsimone** [comment]
yes, definitely my use case would be solved if the event is published after persisting in DB, as you said.

**Comment by michaelbromley** [comment]
Good, so I'll close this issue then 👍
