### ISSUE TITLE
issue with @EntityId decorator

### ISSUE THREAD

**Issue by bhusal-rj** [vendure-ecommerce/vendure#2452]
**Describe the bug**
According to the plugin creation documentation of vendure the @vendure/core exports UserId decorator but there is no export of UserId decorator in @vendure/core

**To Reproduce**
1. Go to entity
2. Try to import UserId

**Expected behavior**
There must be the proper  export of UserId. ALthough the entites can be generated without UserId so it must be removed from the vendure documentation

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.0
 - Nodejs version 20.1.0

**Comment by michaelbromley** [comment]
Hi,

> exports UserId decorator

I assume you mean `EntityId` as in the issue title?

If so, this is exported in v2.1.0+. For 2.0.x versions, you can do a deep import from `@vendure/core/dist/entity/entity-id.decorator`

**Comment by michaelbromley** [comment]
This is now exported in the latest versions.
