### ISSUE TITLE
`addActionBarItem` option's `onclick` handler receiving `VendureUiDevkit` as parameter

### ISSUE THREAD

**Issue by lsimone** [vendure-ecommerce/vendure#247]
**Is your feature request related to a problem? Please describe.**
When you are customizing the admin-ui, it is useful to add buttons with even complex logic triggered through the onclick button.

Currently vendure just give access to `event` and `activatedRoute` parameters.
No `vendureUiDevkit` (or similar tool) can be accessed.

**Describe the solution you'd like**

IMHO it would save a lot of developers' effort to give more power/utils in the `onClick` handler, like having the `vendureUiDevkit` (or its features in other ways, BTW).

It would be useful to receive the `section entity` without the need of subscribing to a nested and not yet documented parameter (but this is not a priority IMHO)

```
        navBuilderService.addActionBarItem({
            requiresPermission: 'Authenticated',
            onClick: function(event, activatedRoute, vendureUiDevkit) {
                     activatedRoute.snapshot.data.entity.subscribe((order: Order) => {
                               VendureUiDevkit.graphQlQuery(orderDependantQuery, params).then((res) => {
                                        // do some awesome stuff
                               })
                     })

            },
            id: 'invoice-download',
            label: 'Invoice',
            locationId: 'order-detail',
            buttonStyle: 'outline',
        })
```

**Comment by michaelbromley** [comment]
> IMHO it would save a lot of developers' effort to give more power/utils in the onClick handler, like having the vendureUiDevkit (or its features in other ways, BTW).

In this case, the UiDevkit itself is not appropriate, since it is designed to work across an iframe boundary. However, we could expose the same capabilities - i.e. the GraphQL client and the Notifications service. 

> It would be useful to receive the section entity without the need of subscribing to a nested and not yet documented parameter (but this is not a priority IMHO)

Yes, this makes sense when adding buttons to a detail view. For list views, the current page of list items would make sense. I'd have to think a bit about a good, maintainable API for these features.
