### ISSUE TITLE
Specifying a particular channel on ProductVariantPriceInput is not possible

### ISSUE THREAD

**Issue by floze** [vendure-ecommerce/vendure#2472]
**Describe the bug**
I have an issue regarding price updates via the GraphQL API. As far as I can tell there is the `UpdateProductVariantInput` which allows me to set its `prices` field using an array of `ProductVariantPriceInput`. This input however does not let me choose the particular channel I want to update, although the docs tell me so: https://docs.vendure.io/reference/graphql-api/admin/input-types/#productvariantpriceinput
Looking further into this input's mechanics, the channel seems to be solely selected by the currency code. Am I missing something here? Because I would really like to be able to update a specific channel's prices only, i.e. in my case there might be several channels with the same currency code that can't be intertwined otherwise.

**To Reproduce**
1. Update a variant via GraphQL API using `UpdateProductVariantInput`
2. Set the `prices` field using an array of `ProductVariantPriceInput`
3. Channel can't be set

**Expected behavior**
Being able to select the price's particular channel on `ProductVariantPriceInput `.

**Environment (please complete the following information):**
 - @vendure/core version: v2.1.0

**Comment by michaelbromley** [comment]
Hi,

the channel is set by the channel token header. These docs describe it in the Shop API but it works exactly the same for the Admin API: https://docs.vendure.io/guides/storefront/connect-api/#specifying-a-channel

**Comment by floze** [comment]
Ah, I discovered this as I was delving deeper into the API, this makes total sense of course. I only wished it would have been documented more prominently as I was actually dealing with the Admin API and thus haven't yet looked in the storefront guides... Thank you very much however!

**Comment by michaelbromley** [comment]
I noticed we already do have this documented on the "channels" page: https://docs.vendure.io/guides/core-concepts/channels/#specifying-channel-in-the-graphql-api

I'm open to suggestions of additional places to document it which might make it more easily discoverable.

**Comment by floze** [comment]
Yes, this looks fine indeed. I guess my problem arouse from the other way around; what threw me off (because I was skipping lessons, heheh) was the two sentences of the API reference linked above (https://docs.vendure.io/reference/graphql-api/admin/input-types/#productvariantpriceinput):
`Used to set up update the price of a ProductVariant in a particular Channel.
If the delete flag is true, the price will be deleted for the given Channel.`
So if anything needs improvement it would be my bad habit of skipping lessons, and maybe a hint in the reference comment that the channel is not explicitly set (or "given") in the input object, but in the token header instead...
