### ISSUE TITLE
POST body missing, invalid Content-Type, or JSON object has no keys

### ISSUE THREAD

**Issue by dalyathan** [vendure-ecommerce/vendure#2473]
**Describe the bug**
When calling `SimpleGraphQLClient.query` the above error happens

**Reproduction Steps**
Let's say we are testing an api endpoint that needs `superadmin` privileges. In order to do that we would do something like this
```ts
import {
...  
createTestEnvironment,
  ...
} from '@vendure/testing';
....
const  { server, adminClient, shopClient } = createTestEnvironment(config);
.....
await adminClient.asSuperAdmin()
```
The call `adminClient.asSuperAdmin()` seems to be resulting in the error.

**Expected behavior**
It should run fine and return result
**Environment (please complete the following information):**
 - @vendure/testing version: 2.1.1
 - Nodejs version 20.8.1
 - Database (mysql/postgres etc): sqlite

**Additional context**
The problem seems to come from the private method `SimpleGraphQLClient.fetch` that does the actual network call

**Comment by mschipperheyn** [comment]
I have this as well, both on 2.1.0 and 2.1.1.

**Comment by michaelbromley** [comment]
Hi, can you provide some more context around this? How are you using it? Reproduction steps?

The `SimpleGraphQLClient.query` method is uses in all our e2e tests, and they are all passing in CI, so I'm wondering what the circumstances are that produce this error.

**Comment by is0utfitters** [comment]
@dalyathan - you will likely notice that if you comment out the offending plugin, the issue goes away.  For example, the current version of the StripeSubscriptionPlugin - if you don't include it in the Vendure plugin configuration, the issue disappears.  Hope that helps.

**Comment by dalyathan** [comment]
Description update @michaelbromley

**Comment by dalyathan** [comment]
It turns out the error stops happening when body parser middleware is removed from plugins which had them. Since it is not a vendure core issue, I will be closing it.

**Comment by martijnvdbrug** [comment]
For future readers, when removing body-parser is not an option: This seems like a similar issue https://github.com/vendure-ecommerce/vendure/pull/2454/files

**Comment by martijnvdbrug** [comment]
Ran into this again, so for future readers, this is my fix:

```diff ts
import { json } from 'body-parser';

@VendurePlugin({
  imports: [PluginCommonModule],
  controllers: [MyCustomController],
  configuration: (config) => {
  // Don't add body-parser anywhere!
-    config.apiOptions.middleware.push({
-      route: `/incoming-hook`,
-      beforeListen: true,
-      handler: json(),
-    });
    return config;
  },
})
```
