### ISSUE TITLE
[admin-ui] promotion validation does not allow to discount the whole catalog

### ISSUE THREAD

**Issue by lsimone** [vendure-ecommerce/vendure#248]
**Describe the bug**
When you create a promotion for the whole catalog, you have to select and deselect a facet to save it.

**To Reproduce**
1. Go to 'create new promotion'
2. Click on 'add condition'
3. Select 'If order total is greater than 0'
4. Click on 'add action'
5. Select 'Discount products with these facets by 10%' without selecting any facet

**Expected behavior**
'Create' button should be enabled.
Actually it isn't, until you select any facet and deselect it. No other ways to save it.

**Additional context**
Before selecting/deselecting facet:
![image](https://user-images.githubusercontent.com/3266650/72723775-d777e400-3b81-11ea-974b-445e4bb116ee.png)

After selecting/deselecting facet:
![image](https://user-images.githubusercontent.com/3266650/72723822-f7a7a300-3b81-11ea-95a1-f23532523417.png)

**Comment by michaelbromley** [comment]
Duplicate of #239 right?

**Comment by lsimone** [comment]
right, sorry, I didn't remember :-)
