### ISSUE TITLE
Missing inheritFilters field for Collection for InitialData

### ISSUE THREAD

**Issue by rsat** [vendure-ecommerce/vendure#2484]
**Describe the bug**

When importing data or populating there is no option to set inheritFilters to false. Probably this was kept from before the inheritFilters was introduced

https://github.com/vendure-ecommerce/vendure/blob/218561f04cbaf738c0f18302b67b1b077a056a7f/packages/core/src/data-import/types.ts#L23-L33

https://github.com/vendure-ecommerce/vendure/blob/218561f04cbaf738c0f18302b67b1b077a056a7f/packages/core/src/data-import/providers/populator/populator.ts#L137-L152

**To Reproduce**
1. Import data with collections
2. All collections are set to InheritFilters to true by default when importing data.

**Expected behavior**

Imported Collections should keep setting inheritFilters to true by default but should be able to set as false if desired.

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.1
 - Nodejs version 16.20
 - Database (mysql/postgres etc): postgres

**Additional context**
Could create the pull request with the fix for approval

**Comment by michaelbromley** [comment]
Hi Ricardo!

You're right - the format has not been updated when we added the inheritFilters toggle in v2. If you are willing to make a PR then that would be very welcome!

**Comment by bhardwajakshit** [comment]
@michaelbromley, Raised a PR for this: https://github.com/vendure-ecommerce/vendure/pull/2534

**Comment by michaelbromley** [comment]
@bhardwajakshit thanks for the fix!
