### ISSUE TITLE
Issue on clean startup (dbempty) and superadminCredentials.identifier with a least one character uppercase

### ISSUE THREAD

**Issue by giosueDelgado** [vendure-ecommerce/vendure#2485]
Describe the bug
When attempting a clean startup with the "dbempty" flag, and having at least one uppercase character in the superadminCredentials.identifier, an issue occurs.

To Reproduce

Go to 'the startup configuration file'.
Set the dbempty flag to true.
In the superadminCredentials.identifier, use a string with at least one uppercase character, for example "Admin".
Attempt to start up Vendure.
See error.
Expected behavior
The expected behavior is for Vendure to start up cleanly, regardless of the case of characters in the superadminCredentials.identifier.

Environment (please complete the following information):

@vendure/core version: 2.1.1
Nodejs version: 16.17.0
Database (mysql/postgres etc): postgres

**Comment by giosueDelgado** [comment]
FYI  @lorenzorottigni

**Comment by michaelbromley** [comment]
Hi,

What's the `dbempty` flag you refer to? I'm not sure how to reproduce what you have run into but I just tested with this config:

```ts
    authOptions: {
        disableAuth: false,
        tokenMethod: ['bearer', 'cookie'] as const,
        requireVerification: true,
        customPermissions: [],
        cookieOptions: {
            secret: 'abc',
        },
        superadminCredentials: {
            identifier: 'Admin',
            password: 'admin',
        },
    },
```

and repopulated the server from scratch and was then able to login with the provided superadmin credentials.

**Comment by giosueDelgado** [comment]
Sorry I be more clear: there isn't a emptydb flag but is to setup an empty database.
Using the version 2.1.1 we were unable to start the database using the string admVendure because the logic was creating the user admvendure (lowercase) so it continue to create user and not find that was existing because not exist in the database with an uppercase..
