### ISSUE TITLE
ReactDataTableComponentProps should use generics so that rowItem is T instead of any

### ISSUE THREAD

**Issue by mschipperheyn** [vendure-ecommerce/vendure#2486]
**Is your feature request related to a problem? Please describe.**
The typescript definition for ReactDataTableComponentProps returns `rowItem` as `any`, which is a flexible default.
But using `T` is more correct and offers code insight. 

**Describe the solution you'd like**
ReactDataTableComponentProps<T> possibly but not necessarily defaulting to `any`

```
export const Label: React.FC<ReactDataTableComponentProps<Address>> = ({ rowItem }) => {
    const street = rowItem.street;
    const phone = rowItem.phneNumber; // error
    return (
        <a href={`https://example.com/address/${rowItem.id}`} target="_blank">
            {street}
        </a>
    );
}
```

**Describe alternatives you've considered**
One could create a wrapper to provide the behavior

**Additional context**
`any` in Typescript is a v1.0 quickie. It defeats the purpose of Typescript. V1.1 should imho remove it.

**Comment by michaelbromley** [comment]
This is a good point. Would you be interested in submitting a pull request to rectify this? The file in question is located here: https://github.com/vendure-ecommerce/vendure/blob/master/packages/admin-ui/src/lib/react/src/register-react-data-table-component.ts#L48

**Comment by barakamwakisha** [comment]
@michaelbromley, I want to work on this

**Comment by michaelbromley** [comment]
@barakamwakisha Great! Thanks for jumping in 👍
