### ISSUE TITLE
Channels, facets and multiSeller ?

### ISSUE THREAD

**Issue by buisine** [vendure-ecommerce/vendure#2493]
Vendure 2.1

I am inserting my facetValues for a certain facet, using a command :

```
...

  const channel = new Channel({
    token: "2l0d7yyr6dgtg23sx1",
  });

  const ctx = new RequestContext({
    apiType: "admin",
    channel,
    isAuthorized: true,
    authorizedAsOwnerOnly: false,
    session: undefined,
  });
  
  ...
  
            const inserted = await facetValueService.create(
              ctx,
              facet,
              facetValueInput
            );
```
So the facetValues are created as expected, BUT as the channel is mandatory, the inserted facets are only available on that channel.

It make sense, except for a multi-seller standpoint because in my case, these facetValues needs to be shared accross sellers using the platform.

Is there a string value to pass as a token to make it available to all channels/users ?

```
    /**
     * @description
     * A unique token (string) used to identify the Channel in the `vendure-token` header of the
     * GraphQL API requests.
     */
    token: string;
```

**Comment by buisine** [comment]
```
class Facet extends VendureEntity implements Translatable, HasCustomFields, ChannelAware {
    constructor(input?: DeepPartial<Facet>)
    name: LocaleString;
    @Column({ default: false })
    isPrivate: boolean;
    @Column({ unique: true })
    code: string;
    @OneToMany(type => FacetTranslation, translation => translation.base, { eager: true })
    translations: Array<Translation<Facet>>;
    @OneToMany(type => FacetValue, value => value.facet)
    values: FacetValue[];
    @Column(type => CustomFacetFields)
    customFields: CustomFacetFields;
    @ManyToMany(type => Channel)
    @JoinTable()
    channels: Channel[];
}
```
channels ? its an array, so maybe listen to new channel/seller event and put that new channel for the facet ?

UpdateFacetInput has no arg for channels ...

**Comment by michaelbromley** [comment]
You can inject the `ChannelService` and after creating the facet value entity, you can call the [assignToChannels method](https://docs.vendure.io/reference/typescript-api/services/channel-service/#assigntochannels) and pass an array of channel ids.

**Comment by buisine** [comment]
Great thanks, I will have a look at it.
My facet will have around 100,000 distinct values (artists names for 4
centuries) with 2 custom fields per value, this is why i'm importing them.
Will this duplicate the facet and facetValues inside the relation tables,
for any given channel ? 😁



Le mer. 1 nov. 2023 à 13:55, Michael Bromley ***@***.***> a
écrit :

**Comment by michaelbromley** [comment]
No, assigning a facet to a channel just adds a row to the (`facetId, channelId`) relation table, essentially adding a pointer from the facet to the channel.

**Comment by buisine** [comment]
Looks wonderful then.
Thank you

Le mer. 1 nov. 2023 à 15:51, Michael Bromley ***@***.***> a
écrit :

**Comment by buisine** [comment]
const assignToChannel = await channelService.assignToChannels(ctx,Facet,'36', [3,2])
  
  Returns this :

```
Facet {
  createdAt: 2023-09-20T09:09:16.862Z,
  updatedAt: 2023-10-28T15:54:26.000Z,
  isPrivate: false,
  code: 'artiste-createur',
  id: 36,
  customFields: CustomFacetFields { required: true },
  channels: [
    Channel {
      token: '2l0d7yyr6dgtg23sx1',
      createdAt: 2023-09-13T10:41:35.616Z,
      updatedAt: 2023-09-13T10:41:39.000Z,
      code: '__default_channel__',
      description: '',
      defaultLanguageCode: 'en',
      availableLanguageCodes: [Array],
      defaultCurrencyCode: 'USD',
      availableCurrencyCodes: [Array],
      trackInventory: true,
      outOfStockThreshold: 0,
      pricesIncludeTax: false,
      id: 1,
      sellerId: 1
    },
    Channel {
      token: '454545DZQSQZED',
      createdAt: 2023-09-13T19:46:49.586Z,
      updatedAt: 2023-09-13T19:46:49.586Z,
      code: 'KTZ',
      description: '',
      defaultLanguageCode: 'en',
      availableLanguageCodes: [Array],
      defaultCurrencyCode: 'EUR',
      availableCurrencyCodes: [Array],
      trackInventory: true,
      outOfStockThreshold: 0,
      pricesIncludeTax: false,
      id: 2,
      sellerId: 2
    },
    Channel {
      token: 'aaa',
      createdAt: 2023-11-01T21:08:36.546Z,
      updatedAt: 2023-11-01T21:08:36.546Z,
      code: 'TEST',
      description: '',
      defaultLanguageCode: 'en',
      availableLanguageCodes: [Array],
      defaultCurrencyCode: 'EUR',
      availableCurrencyCodes: [Array],
      trackInventory: true,
      outOfStockThreshold: 0,
      pricesIncludeTax: false,
      id: 3,
      sellerId: 4
    },
    Channel {
      token: '454545DZQSQZED',
      createdAt: 2023-09-13T19:46:49.586Z,
      updatedAt: 2023-09-13T19:46:49.586Z,
      code: 'KTZ',
      description: '',
      defaultLanguageCode: 'en',
      availableLanguageCodes: [Array],
      defaultCurrencyCode: 'EUR',
      availableCurrencyCodes: [Array],
      trackInventory: true,
      outOfStockThreshold: 0,
      pricesIncludeTax: false,
      id: 2,
      sellerId: 2
    }
  ],
  translations: [
    FacetTranslation {
      createdAt: 2023-09-20T09:09:16.858Z,
      updatedAt: 2023-09-20T09:09:16.000Z,
      languageCode: 'en',
      name: 'artiste-createur',
      id: 36
    }
  ]
}
Command execution completed.
```
So i can see the facet on 3 channels admin-ui, but only on default there is the values, on the other two channels, no values.

Table facet_channels_channel shows the relations.
I am worried  that relation should also appear in facet_value_channels_channel.

**Comment by michaelbromley** [comment]
Yes, this is correct. You'd also need to assign each facet value to the target channels too.

**Comment by buisine** [comment]
Thanks, so it is as i understood it.
So for a multi-seller platform, we need to do this behind the scenes, which is fine
But for X sellers/channels it will increase the relations table, in my specific case it will be 100.000 * X .

What could be another approach ?
Create my custom entity available as a custom field for products ?
Then i think i will lost facetValue filtering implementation.

**Comment by buisine** [comment]
Maybe better to globally override the facet and facetValue services,
to not take in account the channel inside the ctx, and return all facets and their values for any channel in the admin.
I think it can be done with a plugin ?

**Comment by michaelbromley** [comment]
Maybe you can just stick to the current way of doing things and see if there is any performance issue to fix? I don't know how many channels you expect to have, but databases can usually handle a very large number of rows ok.
