### ISSUE TITLE
Auto reload feature admin UI pages on update/creation

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#2497]
Can we add some auto-reload feature ideas or any concept for reloading the page in the admin UI when U want? Specifically for actions like updating customers, orders, or anything else.

Some UI are job queue dependent for which I really wish to have this functionality. May be with some custom JS injections or so?

**Comment by michaelbromley** [comment]
Please describe some idea of an API you'd like to see.

**Comment by BeepLoveKarki** [comment]
May be we can add some custom JS injection for frontend events like
beforecreate, aftercreate, beforeupdate and so.

**Comment by BeepLoveKarki** [comment]
Any update on this?

**Comment by michaelbromley** [comment]
There's not enough information here to work with.

> Please describe some idea of an API you'd like to see.

If you can provide some example code using an API you'd like to see added, then we can start discussing how feasible/desirable it would be to add such APIs. As it stands, this feature request is just too general to be actionable.

I'm going to close, but if you want to provide more explanation, we can consider re-opening.
