### ISSUE TITLE
Expose API for defining custom alerts in Admin UI

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#2503]
**Is your feature request related to a problem? Please describe.**
The Admin UI features an alerts area, which is driven by the `AlertsService` internally. This is currently not documented, so if users want to add their own alerts, they need to reverse-engineer our internals.

**Describe the solution you'd like**
Expose a provider function like `registerAlert()` which can be added to the `providers.ts` array to make it easy to define alerts.

A docs page will also need to be added with a complete guide for how to do this.

**Comment by timcv** [comment]
Hello Michel, do you have any updates regarding this feature?

**Comment by michaelbromley** [comment]
@timcv it's done! Will be available soon in v2.2.0.
