### ISSUE TITLE
Allow customers to be updated on existing orders

### ISSUE THREAD

**Issue by kyunal** [vendure-ecommerce/vendure#2505]
**Is your feature request related to a problem? Please describe.**
We've had multiple occasions now where recurring customers mistyped their e-mail address, resulting in two (otherwise identical) customers to be created. As far as I understand, it currently isn't possible to merge two customers or to change the order's customer, making this a chore to make right with the customer.  
This also leaves the wrong order isolated from the original customer, meaning it won't ever show up in their history etc. in case they have an account or are making an account in the future with the correct e-mail address.

**Describe the solution you'd like**
The API and Admin UI should allow an order's customer to be changed.

**Describe alternatives you've considered**
Merging the customers would also be an option, but most likely more difficult to implement.

**Additional context**
I think this isn't really a special use-case, as I said it happened multiple times to us and really is painful to deal with. We don't want to touch the database, hence we have always found other workarounds such as asking the customer for a second e-mail address they have, but this is really customer unfriendly.
In an ideal world we could also just re-send the e-mails prior to this event, but I think this would necessitate re-triggering an event, which is probably a dangerous thing to do.

**Comment by michaelbromley** [comment]
Coming in the next minor: 


https://github.com/vendure-ecommerce/vendure/assets/6275952/83cb00e0-b26f-40c7-bad9-0e43bacd9801

**Comment by martijnvdbrug** [comment]
We have a plugin that does that: https://pinelab-plugins.com/plugin/vendure-plugin-change-order-customer/

@michaelbromley If there are any plans to include this in core, feel free to merge our plugin into @vendure/core, and we can maintain it in core instead of a separate plugin
https://github.com/Pinelab-studio/pinelab-vendure-plugins/tree/main/packages/vendure-plugin-change-order-customer

**Comment by martijnvdbrug** [comment]
> @martijnvdbrug Yes, this is now in core and will be part of v2.2. I didn't know about your plugin, but it is very similar - the new implementation just does some extra things like checking channel membership and also adding an order history entry.

It was published today😅 I wasn't aware of this being in core...
