### ISSUE TITLE
Bad displaying of success message on the marketplace page

### ISSUE THREAD

**Issue by Stefanyshyn** [vendure-ecommerce/vendure#2529]
**Describe the bug**
I wanted to sign up for notifications on [the marketplace page](https://www.vendure.io/marketplace), but after successfully registering I got a poor success message

<img src="https://github.com/vendure-ecommerce/vendure/assets/40523220/156843b8-a84e-4982-8571-8cbdf5862aee" width="300">

**Comment by michaelbromley** [comment]
Thanks for the report!

@davidhoeck a little detail here on the website can be improved if you get time 👍
