### ISSUE TITLE
updateSearchIndex job stuck in pending

### ISSUE THREAD

**Issue by getwebM** [vendure-ecommerce/vendure#2532]
**Describe the bug**
The jobs from the queue are not processed
<img width="842" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/53661314/8356f47e-667d-47e9-a24b-ba069e9539f8">

**Expected behavior**
Job change stages until its completed

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.3
 - Nodejs version: 16.14.0
 - Database (mysql/postgres etc): 10.6.12-MariaDB-0ubuntu0.22.04.1 Ubuntu 22.04

**Additional context**
    DefaultJobQueuePlugin.init({ useDatabaseForBuffer: false }),
    DefaultSearchPlugin.init({ bufferUpdates: false, indexStockStatus: true }),

I also tried to call runPendingSearchIndexUpdates, response is success:true but stage from job still not change.

**Comment by michaelbromley** [comment]
Hi,

Can you confirm that the worker process is running? Reference: https://docs.vendure.io/guides/developer-guide/worker-job-queue/

**Comment by getwebM** [comment]
Yes indeed, I had overlooked that in the documentary. After I started the index-worker.js, the SearchIndex was executed and all emails were sent.
