### ISSUE TITLE
[UI Plugin][Angular] CanDeactivate is not working with SantandAlone mode

### ISSUE THREAD

**Issue by brunoslalmeida** [vendure-ecommerce/vendure#2535]
**Describe the bug**
CanDeactivate is not working with SantandAlone mode

This is failing because, when you use the registerRouteComponent helper, it's actually wrapping your component in the [AngularRouteComponent](https://github.com/vendure-ecommerce/vendure/blob/0db5d4d5ac0b533fdd5c6eebc4e08d8c97d69739/packages/admin-ui/src/lib/core/src/extension/components/angular-route.component.ts#L11), which is why Angular cannot see the canDeactivate method from your component.

**To Reproduce**
1. Create a new Detail Entity page
2. Add CanDeactivate to the route
3. Try to leave with modification before updating

**Comment by michaelbromley** [comment]
This was fixed in v2.2.7: https://github.com/vendure-ecommerce/vendure/commit/6d9af1d0fba6c23dd185e832ad6963d23f05b9ef
