### ISSUE TITLE
Products asset component stuck, has no accept or cancel button in admin UI

### ISSUE THREAD

**Issue by princetc** [vendure-ecommerce/vendure#2537]
When adding a new product in the admin UI, the assets section for the thumbnail and other images gets stuck as there is no back button, accept button, or cancel button. There is no option to pass the stage, and hence one gets stuck on that stage when attempting to create a product.

**Comment by michaelbromley** [comment]
Hi, thanks for the report. I suspect this may be due to screen size - the button gets cut off at the bottom when the screen is not high enough. Will fix that.

**Comment by princetc** [comment]
Thank you for the quick response
