### ISSUE TITLE
admin-ui code templates have syntax errors

### ISSUE THREAD

**Issue by tschortsch** [vendure-ecommerce/vendure#2544]
**Describe the bug**
The code templates (shown in the admin ui after pressing `CTRL+U`) have errors in the syntax.

**To Reproduce**
1. Go to admin backend
2. Press on CTRL+U
3. Copy a code template
4. See syntax errors

**Expected behavior**
The code templates shouldn't have syntax errors.

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.3
 - Nodejs version: 18

Here you'll find the PR which fixes the syntax errors: https://github.com/vendure-ecommerce/vendure/pull/2545

**Comment by michaelbromley** [comment]
Thanks for the report and fix! 👍
