### ISSUE TITLE
Order totalQuantity, total and shippingLines not updated after an OrderLine is removed

### ISSUE THREAD

**Issue by giacomozr** [vendure-ecommerce/vendure#2548]
While working on the checkout flow, we discovered that the order is not updated correctly after an `orderLine` is removed from an `Order`.

**To Reproduce**
* Add two items from two different sellers.
* Assign the shipping methods from the eligible shipping options.
* Remove one of the `orderLines`.
* The response will return successfully, but with some properties not correctly updated, such as `subTotalWithTax` or `totalQuantity`.

**Expected behavior**
The response should return the updated order with the correct information

**Environment:**
 - @vendure/core version: 2.1.4
 - Nodejs version: 18.16.0
 - Database PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**Additional context**
Possible solution: 
Remove the "orphans" `shippingLines` and update the `Order` in the database before calling the `applyPriceAdjustments` method."

I have tried to implement a fix:
```typescript
/**
 * @description
 * Removes the specified OrderLine from the Order.
 */
async removeItemFromOrder(
    ctx: RequestContext,
    orderId: ID,
    orderLineId: ID,
): Promise<ErrorResultUnion<RemoveOrderItemsResult, Order>> {
    const order = await this.getOrderOrThrow(ctx, orderId);
    const validationError = this.assertAddingItemsState(order);
    if (validationError) {
        return validationError;
    }
    const orderLine = this.getOrderLineOrThrow(order, orderLineId);
    order.lines = order.lines.filter(line => !idsAreEqual(line.id, orderLineId));

    // Remove shippingLines not valid for this order
    const orderLineShippingLineIds = order.lines.map(line => line.shippingLineId);

    // Get all the shippingLines that are not included in the order lines
    const shippingLinesToDelete = order.shippingLines.filter(
        shippingLine => !orderLineShippingLineIds.includes(shippingLine.id),
    );

    // In case some shippingLines are founded, remove it
    if (shippingLinesToDelete.length) {
        await this.connection.getRepository(ctx, ShippingLine).remove(shippingLinesToDelete);
    }

    // Update the order before Hydration
    await this.connection.getRepository(ctx, OrderLine).remove(orderLine);
    const updatedOrder = await this.applyPriceAdjustments(ctx, order);
    this.eventBus.publish(new OrderLineEvent(ctx, order, orderLine, 'deleted'));
    return updatedOrder;
}
```

**Comment by giosueDelgado** [comment]
Related: https://github.com/vendure-ecommerce/vendure/issues/2540
