### ISSUE TITLE
BullMQ config type error when using v1 as directed in docs

### ISSUE THREAD

**Issue by pevey** [vendure-ecommerce/vendure#2549]
Vendure version: 2.1.4
Docs link: https://docs.vendure.io/reference/core-plugins/job-queue-plugin/bull-mqjob-queue-plugin

Steps:
Install bullmq per the directions in the link (adding "@1" to limit the major version to 1), and then add configuration options as described:

```
		BullMQJobQueuePlugin.init({
			connection: {
				port: 6379
			},
			workerOptions: {
				concurrency: 3, // default is 3
				removeOnComplete: {
					count: 500, // default is 5,000
				},
				removeOnFail: {
					age: 60 * 60 * 24 * 7, // 7 days; default is 30 days
					count: 1000, // default is 5,000
				}
			},
		}),
```

The result is a Typescript error.  I dont think v1 is compatible with the example configuration options show in the docs.  The type Vendure uses is imported directly form bullmq, and v1 does not include removeOnComplete or removeOnFail.

If I remove the "@1" and install the latest version of bullmq, the typescript error goes away.  I'm waiting to see if using the latest version produces other errors.  It might be that the plugin has since been updated, and the docs just need to be updated to remove the "@1".

**Comment by pevey** [comment]
![error](https://github.com/vendure-ecommerce/vendure/assets/7490308/4bb8a669-c073-410e-868d-4888e1492811)
The specific error for reference.

**Comment by michaelbromley** [comment]
Yes a single PR to master with all the docs fixes would be great 🙏
