### ISSUE TITLE
JIT Compilation error - Angular custom List View

### ISSUE THREAD

**Issue by margamorais** [vendure-ecommerce/vendure#2552]
**Describe the bug**
I created a custom List View component (Angular component) called ApproveProductsWidgetComponent, following this [documentation](https://docs.vendure.io/guides/extending-the-admin-ui/creating-list-views/.) 
When running the project I get the following error.

![image](https://github.com/vendure-ecommerce/vendure/assets/118457456/3254b10d-5917-49ee-b811-45b126ee88a6)

**To Reproduce**
1. compile the code: npm run build `"build": "tsc"`
2. run the code: npm run start 
```
"start:server": "node ./dist/index.js",
    "start:worker": "node ./dist/index-worker.js",
    "start": "concurrently npm:start:*"
```
3. Go to page with ApproveProductsWidget Component

**Expected behavior**
ApproveProductsWidgetComponent should be rendered

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.2
 - Nodejs version: v20.9.0 
 - Database: postgres

**Comment by michaelbromley** [comment]
Hi, can you please share a minimal reproduction repo so I can see the exact code being run?

**Comment by margamorais** [comment]
Of course, [here](https://github.com/margamorais/vendure-bug-report) is a repo with the example. Thank you for your help!

**Comment by michaelbromley** [comment]
Thanks for the repo. I can confirm that I see the same thing. Investigating what's going on....

**Comment by margamorais** [comment]
It worked! Thank you very much for your help!
