### ISSUE TITLE
Docs typo in "custom-field-type" : "localText" should be "localeText"

### ISSUE THREAD

**Issue by NadimD** [vendure-ecommerce/vendure#2553]
**Describe the bug**
There is a typo in the auto-generated types of "**custom-field-type**".

**To Reproduce**
1. Go to https://docs.vendure.io/reference/typescript-api/custom-fields/custom-field-type
2. Available in 3 files : https://github.com/search?q=repo%3Avendure-ecommerce%2Fvendure%20localText&type=code

**Expected behavior**
"**localText**" should be "**localeText**"

**Comment by michaelbromley** [comment]
Hi, thanks for the report! This will be fixed.
