### ISSUE TITLE
Load facetvalues faster in the Admin UI

### ISSUE THREAD

**Issue by Caryntjen** [vendure-ecommerce/vendure#2576]
**Is your feature request related to a problem? Please describe.**
I have about 1800 facetvalues spread over 12 facets.
The biggest one has 500+ facetValues and the Admin UI takes 10+ seconds to load locally with postgres v16.
Any way to improve this?
I am running the latest vendure 2.1.4

**Describe the solution you'd like**
Faster loading speeds of facet values

**Describe alternatives you've considered**
remark from @michaelbromley in discord: Currently we are eager-loading all values when you open the facet detail view. The pagination is then done in-memory. The solution to this is that we need to implement server-side pagination over the values. You can open an issue for this.

**Additional context**
None

**Comment by giosueDelgado** [comment]
Need also for us
