### ISSUE TITLE
Handlebars cant resolve property

### ISSUE THREAD

**Issue by Szbuli** [vendure-ecommerce/vendure#259]
**Describe the bug**
Handlebars cant resolve some properties.

**To Reproduce**
Generate Order Confirmation test email

**Additional context**
Log:

> Handlebars: Access has been denied to resolve the property "totalPrice" because it is not an "own property" of its parent.
> You can add a runtime option to disable the check or this warning:
> See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details

**Comment by michaelbromley** [comment]
Thanks for report. V4.6.0 of Handlebars has a breaking change (https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v460---January-8th-2020). Classic SemVer problems 😂
