### ISSUE TITLE
CreateProductOptionGroupInput nor UpdateProductOptionGroupInput does not let you add/update productId

### ISSUE THREAD

**Issue by Caryntjen** [vendure-ecommerce/vendure#2598]
**Describe the bug**
The db entity has a table for productId. But CreateProductOptionGroupInput/UpdateProductOptionGroupInput does not has the ability to add or update it.

**To Reproduce**
From codegen
```
export type CreateProductOptionGroupInput = {
    code: Scalars['String']['input'];
    customFields?: InputMaybe<Scalars['JSON']['input']>;
    options: Array<CreateGroupOptionInput>;
    translations: Array<ProductOptionGroupTranslationInput>;
};
```
**Expected behavior**
I can at least update the productId, but also add it during creation of the ProductOptionGroup.

**Environment (please complete the following information):**
@vendure/core version: 2.1.4
Nodejs version 20.10.0
Database (mysql/postgres etc): postgres

**Additional context**
All done programatically through the server in a CLI script.

**Comment by michaelbromley** [comment]
The way this is done is that you first create the ProductOptionGroup, and then use `ProductService.addOptionGroupToProduct()` to assign that group to a product.

**Comment by Caryntjen** [comment]
Ok thanks, got that resolved. Had the empression you could do it as once.
