### ISSUE TITLE
Multiple Cancellations on a same line item not allowed from admin UI

### ISSUE THREAD

**Issue by shaheerrs** [vendure-ecommerce/vendure#2608]
** Multiple Cancellations on a same line item not allowed from admin UI  **

**To Reproduce**
1. Go to 'https://demo.vendure.io/'
2. Create and order with 2 items of 3 quantity each
3. Add payment to order
4. Use Refund or cancel 2 quantity from 1st item and 1 quantity from second item.
5. Trigger refund
6. Now try to use Refund or cancel option to cancel the one quantity remaining in the first item. (_you can see the option is disabled_)

**Expected behavior**
The Customer support should be able to cancel multiple times on line item until it reaches 0.

**Environment (please complete the following information):**
 - @vendure/core version: Vendure2.1.0
 - Nodejs version - Node 18
 - Database (mysql/postgres etc): Postgres

**Additional context**
In the above mentioned scenario see the item where I cannot select refund / cancel to proceed with full item cancellation from Admin UI
<img width="1155" alt="Screenshot 2023-12-29 at 7 45 23 AM" src="https://github.com/vendure-ecommerce/vendure/assets/45445534/b200f99f-5a78-4c39-a554-4cf50d64c163">

**Comment by shaheerrs** [comment]
@michaelbromley  I was debugging the code and it seems the following code is the root cause of the issue
`lineCanBeRefundedOrCancelled(line) {
        const refundedCount = this.order.payments
            ?.reduce((all, payment) => [...all, ...payment.refunds], [])
            .filter(refund => refund.state !== 'Failed')
            .reduce((all, refund) => [...all, ...refund.lines], [])
            .filter(refundLine => refundLine.orderLineId === line.id)
            .reduce((sum, refundLine) => sum + refundLine.quantity, 0) ?? 0;
        return refundedCount < **line.quantity**;`

Here the line.quantity will always get reduced with cancellation, so the check is always against the remaning quantity in the order than the order placed quantity.

**Comment by michaelbromley** [comment]
Thanks for the report & the advice on the location of the bug. You are correct! This will be fixed in the next patch.
