### ISSUE TITLE
[Question] Tax and Shipping plugins/integrations

### ISSUE THREAD

**Issue by AshotN** [vendure-ecommerce/vendure#261]
I've tried looking around the documentation. But I can't seem to see a way to integrate with sales tax calculator, or a shipping calculator. Is there any such plugins currently?

I was hoping to at least find an NPM package and follow the documentation for making a plugin. But UPS has really crappy documentation so it'll be a mission.

**Comment by michaelbromley** [comment]
Hi,

So for shipping, you need to implement a [ShippingCalculator](https://www.vendure.io/docs/typescript-api/shipping/shipping-calculator/) and add that to your VendureConfig object in the [ShippingOptions](https://www.vendure.io/docs/typescript-api/shipping/shipping-options/). You can use the [default shipping calculator](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/config/shipping-method/default-shipping-calculator.ts) as a guide.

There are currently no ready-made plugins at this point. Crappy API documentation from shipping providers is unfortunately a universal truth. Hopefully you don't need to use XML 😅.

Likewise for taxes, you can define your own [TaxCalculationStrategy](https://www.vendure.io/docs/typescript-api/tax/tax-calculation-strategy/), see the [default strategy](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/config/tax/default-tax-calculation-strategy.ts) as an example. Unfortunately the major limitation at this time is that the calculation function is synchronous, so if you want to call out to an external API you'll have trouble. I plan on making async possible in a future release.

**Comment by AshotN** [comment]
Alright, I'll probably try to see if I can integrate the tax calculator first as there are decent APIs for that. Granted they are paid but no real choice for that.

A couple things I've got a few more questions about but I don't want to spam a bunch of issues.

I can't seem to find a way to delete Tax categories/rates, and same with shipping methods. I tried deleting them from the SQL database, it worked but caused some issues with the default products, I assume some relation is messed up now. 

Also, I'm in the US and typically we don't have the tax included in the price which Vendure seems be doing. Is there an option to list the price and tax separately? This may be out of scope, since I haven't dived into the Diety code.

Sorry for the barrage of questions, but a business I started work for has their own custom eCommerce system, and it's an absolute mess. I wanted to replace it and hopefully transfer their existing data.

**Comment by michaelbromley** [comment]
Hey, no problem with the Qs, but a better venue to ask is our [slack workspace](https://join.slack.com/t/vendure-ecommerce/shared_invite/enQtNzA1NTcyMDY3NTg0LTMzZGQzNDczOWJiMTU2YjAyNWJlMzdmZGE3ZDY5Y2RjMGYxZWNlYTI4NmU4Y2Q1MDNlYzE4MzQ5ODcyYTdmMGU).

> I can't seem to find a way to delete Tax categories/rates, and same with shipping methods. I tried deleting them from the SQL database, it worked but caused some issues with the default products, I assume some relation is messed up now.

Yep, this is missing from the UI right now. Please create a separate issue and I may be able to work that in to the next release.

> Also, I'm in the US and typically we don't have the tax included in the price which Vendure seems be doing. Is there an option to list the price and tax separately? This may be out of scope, since I haven't dived into the Diety code.

There is an option in the Channel detail page "Prices include tax for the default Zone" - check that, it should be switched off in your case. If this is the case, then both the price with and without tax is available via the Shop API:

```
query {
  products(options: { take: 3 }) {
    items {
      id
      variants {
        price
        priceWithTax
        priceIncludesTax
      }
    }
  }
}
```

**Comment by AshotN** [comment]
I'll hop on slack, I think I have an account. 

I'll create a separate issue for the missing UI elements.

I'll leave this issue open until either I or anyone else creates some sort of plugin to interface with tax/shipping services.

**Comment by chanmathew** [comment]
May I suggest a Taxjar integration at some point? It’s been amazing with our store and super user friendly.

**Comment by michaelbromley** [comment]
Closing in favour of #307
