### ISSUE TITLE
Address country resolves to Afghanistan (the first in the list)

### ISSUE THREAD

**Issue by mschipperheyn** [vendure-ecommerce/vendure#2614]
**Describe the bug**
I store an address with a US countryCode. It is stored in the database correctly. However, when I retrieve the address with the country through graphql, the country resolves to Afghanistan, the first available country.

I looked for an address-entity.resolver.ts in the code base and didn't find one. So I'm guessing this is the issue.

**To Reproduce**
- Store an address with a country code other than the first in the database

```

mutation {
  updateCustomerAddress(input: {
     id: 1,
     city: "INDIANAPOLIS",
     countryCode: "US",
     postalCode: "12345",
     province: "IN",
     streetLine1: "Adams Drive 123",
     phoneNumber: "3112345678",
  }) {
    id
    country {
      id
      code
      name
    }
  }
}

```

**Expected behavior**
Retrieve the correct address through an entity resolver

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.4
 - Nodejs version
 - Database (mysql/postgres etc): postgres

**Additional context**

**Comment by michaelbromley** [comment]
Hi,

I cannot reproduce this on the demo.vendure.io instance. Are you able to reproduce from a clean install?

![image](https://github.com/vendure-ecommerce/vendure/assets/6275952/074eb4d9-2db7-4b38-a695-504aa3c2bc61)
