### ISSUE TITLE
Missing delete TaxRate, TaxCategory UI

### ISSUE THREAD

**Issue by AshotN** [vendure-ecommerce/vendure#262]
**Is your feature request related to a problem? Please describe.**
There is currently no way in the Admin UI to remove 

- [ ] Tax Categories
- [ ] Tax Rates
- [ ] Payment Methods

Feel free to add something I missed

**Comment by michaelbromley** [comment]
Payment methods work a little differently - they are automatically created/removed according to the [`paymentMethodHandlers` config option](https://www.vendure.io/docs/typescript-api/payment/payment-options/#paymentmethodhandlers), therefore there is no "create" or "delete" option in the UI.

TaxCategories and TaxRates should be deletable though. Care will have to be taken to preserve the integrity of related entities when deleting either of these though, i.e. attempting to delete a TaxCategory that is referenced in one or more TaxRates would raise an error.
