### ISSUE TITLE
registerPageTab doesn't work for specific detail pages

### ISSUE THREAD

**Issue by wayne12366** [vendure-ecommerce/vendure#2623]
**Describe the bug**
I've tried to add new tab under seller-detail page and I used the `registerPageTab` function with following locationId.
`seller-detail`
but it doesn't show any tabs under seller-detail page.
So i checked the source code, especially packages/admin-ui/src/lib/settings/src/settings.routes.ts.
and I found that some data is wrong in this file.
![image](https://github.com/vendure-ecommerce/vendure/assets/154095434/13040d9f-7a68-4eae-b680-132a1907d79b)

As you can see in screenshot, data.locationId ( seller-list ) is same for seller-detail and seller-list components.
then, i used that locationId to register new tab and now, the tab is shown under seller-detail page.
but i could also see the tab in seller-list page.
![image](https://github.com/vendure-ecommerce/vendure/assets/154095434/2632fddf-f2c4-4e79-a4fa-e1b2bca01072)
![image](https://github.com/vendure-ecommerce/vendure/assets/154095434/b1b4395f-0dc0-4a9c-8f5d-26b758168b4e)

I can see such errors in stock-location, channel.

I'm sure this is minor issue and it will be fixed soon.

**Comment by michaelbromley** [comment]
Thanks for the report! This will be fixed in the next patch version.
