### ISSUE TITLE
Switching to BullMQJobQueuePlugin causes many "Pending" jobs that won't expire or retry

### ISSUE THREAD

**Issue by JamesLAllen** [vendure-ecommerce/vendure#2625]
**Describe the bug**
Connecting to a Redis and using BullMQJobQueuePlugin causes many jobs to start piling up where 0 time has been spent on them, they are still in "Pending" state, but they never stall or are retried.

**To Reproduce**
1. Deploy using BullMQJobQueuePlugin
2. Click on Job Queue
3. Witness lots of pending jobs

**Expected behavior**
Jobs to either time out or be completed.

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.5
 - Nodejs version: v20
 - Database (mysql/postgres etc): postgres / Redis

<img width="713" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/209582/daebd9c4-da73-4471-a395-3cd8af07a90e">

**Comment by michaelbromley** [comment]
Hi James,
Since we discussed this at length via Discord, can you clarify whether this is still an issue or whether it can be closed?

**Comment by JamesLAllen** [comment]
Yes, I think this specific issue can be closed, however I think it presents an interesting challenge that if a worker has failed, to notify the admin would be nice.  Come to think of it, it would be great to see how many workers are running and what jobs they're doing, etc.  But that's a feature improvement not a bug :)
