### ISSUE TITLE
Pause, Resume, Kill/Cancel a Running Job

### ISSUE THREAD

**Issue by JamesLAllen** [vendure-ecommerce/vendure#2650]
**Is your feature request related to a problem? Please describe.**
I would like the ability to pause, resume, and kill/cancel a job that is currently running and events that we can listen for our own custom jobs.

**Describe the solution you'd like**
Currently when I try to cancel a running job, like a full re-index which takes a very long time, it gives me an error saying I can't stop a job while it's running.  I would like the ability to pause a job and then resume it, or cancel it altogether.

**Describe alternatives you've considered**
I'm not sure what alternatives there would be.

**Comment by michaelbromley** [comment]
Agreed, the inability to kill a running job can be a pain. especially when they occasionally get into a false "running" state and there's no easy way to evict it from the queue.

> I would like the ability to pause a job and then resume it

This sounds like it might be rather complex to get right, since once the `process` function begins execution, I don't know of a general way to "pause" that execution. I don't know of any prior art on a job queue system supporting this kind of functionality. Do you?

**Comment by JamesLAllen** [comment]
I need to know more about the events within the underlying job queue system, specifically how do you pass along percentage updates?

I might be wrong here but it doesn't look like we assign a unique ID to each job, so there's currently no way to modify it once it's been kicked off, right?  I think this is how I might tackle this specific improvement:

1. Assign a unique ID for all jobs.
2. Assign a unique ID for the worker that accepts a job.
3. Add job status columns or a table and expose hooks for jobs that are created to update, modify, cancel and delete.
4. Worker is responsible to check back periodically for changes.
5. In addition, Server would also check as it does on running jobs to ensure nothing has timed out or errored.  If the job hasn't responded in a while, then Server assumes the job has stalled and releases the worker, freeing it up to be taken by another worker or cancelled depending on rules that are set by the admin (some jobs should be restarted infinitely, others should be cancelled, others only restarted a set number of times).

**Comment by michaelbromley** [comment]
Related:

- https://github.com/vendure-ecommerce/vendure/issues/1127
