### ISSUE TITLE
Admin UI creates duplicate facet values

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#2658]
**Describe the bug**
The admin UI creates previously created facet values again after the `update` button is clicked.

**To Reproduce**
1. Go to a facet
2. Click on 'Add facet value' and create a facet value `test1`
3. Click on `update` to save the facet value. The `CreateFacetValue` mutation is called for `test1`
4. **Without refreshing the page**, click on 'Add facet value' again and create `test2`
5. Click on `update`
6. The `CreateFacetValue` mutation is called for `test1` and `test2`, but test1 was already created before. The result is that we have two facet values named `test1` now.

![image](https://github.com/vendure-ecommerce/vendure/assets/6604455/bd47277d-a12e-4740-9497-34adbced74ee)
(Duplicate `test1` facet values)

**Expected behavior**
Only `test2` should be in the `CreateFacetValue` mutation 

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.5
 - Nodejs version: 18
 - Database (mysql/postgres etc): MySQL

**Comment by AleksanderBondar** [comment]
I think problem is in facet-detail.component.ts. After `save()` we should remove all temps ids from the form.

```ts
const valuesFormRecord = this.detailForm.get('values') as FormRecord;
if (valuesFormRecord) {
  Object.values(valuesFormRecord.controls).forEach(control => {
   if (this.isTempId(control.value.id)) {
     valuesFormRecord.removeControl(control.value.id);
   }
 });
}
```

Do it make sense?

**Comment by michaelbromley** [comment]
In the upcoming v2.2 (`minor` branch) I completely overhauled the way this is handled, related to https://github.com/vendure-ecommerce/vendure/issues/2576.

In the new implementation we do away with this "tempId" stuff, which makes everything super complicated. Instead, we actually create the new FacetValue directly in the backend.

**Comment by martijnvdbrug** [comment]
Awesome, good to hear this is being addressed! I'll leave it up to you if you want to keep this issue open :-)

**Comment by michaelbromley** [comment]
I'll close because I don't think I will address this for the 2.1.x branch.
