### ISSUE TITLE
PriceRange includes prices of soft deleted product variants

### ISSUE THREAD

**Issue by oncode** [vendure-ecommerce/vendure#266]
**Describe the bug**
The PriceRange also includes the prices of the soft deleted product variants when using the search query.

**To Reproduce**
1. Add a new product with just the default variant and set the price to "10"
2. Use "Manage variants" to add a new option and fill up with two option values (creates two variants) and set both their prices to "20" and save (confirm the "Delete default variant" dialog) -> the variant with the price "10" will be soft deleted
3. Execute a search query to the the prices of the product.
```
query (...) {
  search(...) {
    items {
      price {
        ... on SinglePrice {
          value
        }
        ... on PriceRange {
          min
          max
        }
      }
    }
  }
}
```
Outputs:
```
...
"price": {
   "min": 1000,
   "max": 2000
 }
...
```

**Expected behavior**
The prices of soft deleted product variants should be ignored/excluded. The output should be:
```
...
"price": {
   "min": 2000,
   "max": 2000
 }
...
```

**Environment (please complete the following information):**
 - @vendure/core version: 0.8.0
-  elasticsearch plugin installed
 - Nodejs version: 12.4.1
 - Database: mysql

**Comment by michaelbromley** [comment]
Thanks for the report. Can reproduce when using the ElasticSearchPlugin. DefaultSearchPlugin handles this correctly.
