### ISSUE TITLE
Pressing enter in input fields removes facets

### ISSUE THREAD

**Issue by oncode** [vendure-ecommerce/vendure#267]
**Describe the bug**
When I'm editing a product and press enter inside an input field, a facet gets removed if there is at least one.

**To Reproduce**
1. Go to edit page of a product
2. Add a facet, if there is none
3. Set focus to any input field on the page
4. Press enter key
5. Facet has been deleted

**Expected behavior**
No facet should be removed. The product should be saved or no action should happen.

**Environment (please complete the following information):**
 - @vendure/core version: 0.8.0

**Comment by michaelbromley** [comment]
Can reproduce and oh my..what a ridiculous bug! Will be fixed in the next release.
