### ISSUE TITLE
order.customer.group is undefined

### ISSUE THREAD

**Issue by getwebM** [vendure-ecommerce/vendure#2674]
**Describe the bug**
In my custom promotion condition check function: order.customer.groups is undefined. In the admin UI is the customer assigned to the customer group "Mitarbeiter"

**To Reproduce**
1. Create custome promotion condition
2. Use order.customer.groups in the check functions, it should be undefined

**Expected behavior**
An array of customer groups

**Environment (please complete the following information):**
 - @vendure/core version: 2.1
 - Nodejs version 16.14.0

**Comment by michaelbromley** [comment]
Hi,

This is a case where you'd need to use the [EntityHydrator](https://docs.vendure.io/reference/typescript-api/data-access/entity-hydrator/) to manually ensure the relations you require are present.
