### ISSUE TITLE
Re-design admin-ui architecture for easier extensibility

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#269]
## Current situation

The AdminUiPlugin allows "extensions" to be specified, which are Angular modules containing custom UI components / routes. When extensions are specified, the whole admin ui app will be re-compiled using the Angular CLI and a new compiled bundle will be produced.

### How this works

The `@vendure/admin-ui` package actually ships with the full TypeScript source code for the admin ui app, and also lists `@angular/cli`, `@angular/compiler` etc. as _dependencies_ and not _devDependencies_. In this way, the end-user has the entire infrastructure needed to rebuild the admin ui app from source. 

In addition, there is a [compileAdminUiApp](https://github.com/vendure-ecommerce/vendure/blob/8b91a592eb4459131a70e1c7918b52779dbdfa39/packages/admin-ui/src/compiler/compile.ts) function which will copy any ui extension sources over into the admin-ui source tree (into `./node_modules/@vendure/admin-ui/src/extensions/`) so that they can be included in the ng-cli compilation.

Meanwhile, the `@vendure/admin-ui-plugin` app is responsible only for passing the ui extensions config over to the `compileAdminUiApp` function and also for setting up a simple static Express server & proxy to serve the compiled admin ui from `host:port/admin`

### Problems

1. After upgrading to Angular 9, this method of compiling ui extensions no longer works. The Angular compiler sees that there are TS source files in the "node_modules" dir and throws an error. It also throws due to finding TS files not included in the tsconfig "files" array ([see relevant part of angular-cli source](https://github.com/angular/angular-cli/blob/1c1f1cde652dcea6bd8cc50822512def7bd37d82/packages/ngtools/webpack/src/angular_compiler_plugin.ts#L1203-L1216))
2. The current setup make it difficult to set a clear boundary on the public API available to ui extension developers. Currently we use [this barrel file](https://github.com/vendure-ecommerce/vendure/blob/8b91a592eb4459131a70e1c7918b52779dbdfa39/packages/admin-ui/src/index.ts) and some [tsconfig paths trickery](https://github.com/vendure-ecommerce/vendure/blob/8b91a592eb4459131a70e1c7918b52779dbdfa39/packages/admin-ui/tsconfig.json#L29) to make it possible for ui extension authors to do `import { ... } from '@vendure/admin-ui/src'`. However, this approach is currently incompatible with using ahead-of-time (AOT) compilation due to [this issue](https://github.com/angular/angular/issues/20931)
3. Currently _all_ ui extensions are lazy-loaded in a single bundle at the `/extensions` route. This is inefficient since ui extension bundles could get very large and it would be better to lazy-load each extension seperately.
4. It is not currently possible to run the admin ui in "stand alone" mode, i.e. decoupled from the Vendure server itself.
5. Compiling the admin ui  takes up to a few minutes, and delays the bootstrap process of the Vendure server. This makes re-deploys / changes difficult and disruptive.

## Proposal

Here is an idea for a new approach to the problem:

### 1. Split the "public API" into a separate library

The public API for ui extension develops consists of:

* The `SharedModule`. This contains shared components, pipes etc. Using these components makes the ui extensions blend in seamlessly with the rest of the admin ui app.
* Some core providers from `CoreModule` such as `DataService`, `NotificationService`, `ModalService`.
* A few base classes e.g. for handling list/detail views.

These elements could be split into a separate library which is then consumed by _both_ the admin-ui _and_ any ui-extensions. This should solve the issues related to our hacky use of barrel files and tsconfig paths. It also means that we can pre-compile these parts which should speed up re-compilation of the app.

### 2. Do not compile deep in node_modules

As described above, copying the ui extension sources deep into "node_modules" no longer works. It also seems wrong somehow to rely on modifying the contents of "node_modules".

Instead, we should *copy* the admin-ui sources _from_ "node_modules" up to a top-level (or user-specified) directory into which we can also copy the ui extension sources.

### 3. Provide a method for stand-alone compilation

Add a function which performs the compilation outside the context of the Vendure bootstrap process. The end result would be a directory with the compiled bundles. This could then be served using any static web server.

## Challenges

The main challenge I see is how exactly to split out the common parts into a library:

* How to support i18n translation extraction across both the library and the admin ui app?
* How to physically structure the project? Create a "library" angular cli project inside the existing "admin-ui" lerna package? How then do we publish a separate npm packge from that?
* How to avoid duplication of dependencies such as apollo-client, graphql, angular cdk etc. That could be really messy to maintain.

Another thing to consider is keeping the existing single "admin-ui" lerna package, but setting up the angular.json config to generate _both_ a compiled app _and_ a library version of the app. This is something I'll need to explore further.

**Comment by maku** [comment]
@michaelbromley Just to be curious. Would be the usage of https://nx.dev/angular an option?

**Comment by michaelbromley** [comment]
@maku I don't know - I've never used it so I cannot judge whether it makes more or less sense than the current Lerna-based setup. If you are experienced with Nx I'd be happy to hear about any potential benefits!

**Comment by maku** [comment]
@michaelbromley  I use nx in my day job as well as in side projects as freelancer. To be honest I have no experience with lerna. But in nx you share your dependencies (=1 package.json)  for all apps / libs. And the reuse of shared artefacts in different libs and apps is really easy.

**Comment by michaelbromley** [comment]
@maku Ok, thanks for the info. I'd have to look into Nx further to see if it is worth considering. The main thing about Lerna is that it makes it easier to manage several inter-related npm packages. E.g. it allows you to bump the version number with 1 command and takes care of modifying all the package.json files in each package.

**Comment by michaelbromley** [comment]
This issue can be closed with the release of v0.10.0 - see the [release announcement blog post](https://www.vendure.io/blog/2020/03/announcing-vendure-v0.10.0/)
