### ISSUE TITLE
Unable to query roles due to "role.channels is not iterable"

### ISSUE THREAD

**Issue by jyling** [vendure-ecommerce/vendure#2693]
**Describe the bug**
Hi, Vendure developers, I recently updated my backend to the latest v2.1.7, however, I encountered a weird behaviour when querying roles from the admin-api. I keep on getting this error. I'm also able to reproduce this by running `npx @vendure/create xxxx` to run on a new vendure instance
```
role.channels is not iterable
```

**To Reproduce**
1. Go to 'http://localhost:3000/admin-api'
2. Query roles
```graphql
query roles($options: RoleListOptions) {
    roles(options: $options) {
      items {
        id
        code
        description
        permissions
        createdAt
        updatedAt
      }
    }
  }
  ```
3. See error
```
{
  "errors": [
    {
      "message": "role.channels is not iterable",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "roles"
      ]
    }
  ],
  "data": null
}
```

**Expected behavior**
I expect I should be able to get the roles.

**Workaround**
Running the query with channels seems to solve the issue.
```graphql
query roles($options: RoleListOptions) {
    roles(options: $options) {
      items {
        id
        code
        description
        permissions
        createdAt
        updatedAt
        channels { id }
      }
    }
  }
  ```

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.7
 - Nodejs version: 18.19.0
 - Database (mysql/postgres etc): postgres 15.3

**Additional context**

**Comment by michaelbromley** [comment]
Likely related: https://github.com/vendure-ecommerce/vendure/commit/fc5d9810a930fbf2ce60819fcabd556c679385ad
