### ISSUE TITLE
EntityHydrator always refetches customFields

### ISSUE THREAD

**Issue by jnugh** [vendure-ecommerce/vendure#2696]
**Describe the bug**
The `EntityHydratorService` checks wether or not certain fields need to be fetched from the database or are already available locally. Therefore the relation path is split by dots and each segment is being checked for existence.

However there is a special case for `customFields`:
```ts
const parts = !relation.startsWith('customFields') ? relation.split('.') : [relation];
```

In case of custom fields the complete path would need to exist (e.g. `entity['customFields.myCustomField']` instead of `entity.customFields.myCustomField`.
I removed the special case and the code seems to be working just fine. Maybe this was related to a bug in a previous version of TypeORM?

**To Reproduce**
1. Create a custom field
2. Fetch the base entity including the custom field
3. Use entityHydrator to hydrate the custom field

**Expected behavior**
The first query should be sufficient however the relation is being fetched again.

**Environment (please complete the following information):**
 - @vendure/core version: latest (master)
 - Nodejs version: 20
 - Database (mysql/postgres etc): postgres

**Additional context**
I also noticed that a relation will always marked as not fetched if there is a null value on the path because null would mean the relation has been fetched but does not exist (in contrast to undefined).

If this was indeed a workaround for an old bug I could create a PR for this.

**Comment by michaelbromley** [comment]
Hi @jnugh, since this is a very old issue, do you happen to know whether it is still a problem with the latest v2.2.x version?

**Comment by jnugh** [comment]
The code did not change:

https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/service/helpers/entity-hydrator/entity-hydrator.service.ts#L203C17-L203C103
There is still a special case for customFields using `['customFields.xyz']` instead of `['customFields', 'xyz']` as path and `entity['customFields.xyz']`will never exist thus `customFields.xyz` will be refetched.

We applied a custom patch that replaces the special case with:
```ts
const parts = relation.split('.');
```

and did not notice any issues.
