### ISSUE TITLE
worker - MQTT transport type

### ISSUE THREAD

**Issue by Szbuli** [vendure-ecommerce/vendure#270]
**Is your feature request related to a problem? Please describe.**
MQTT transport type is not working

**Additional context**
1) there is an error handling in bootstrap.ts which breaks other transport types.
2) for other transport types connect should be called on the client?
3) for message toPromise() should be called?

not sure about the last 2 step

https://stackoverflow.com/questions/54291285/how-to-use-nestjs-redis-microservice/54293468#54293468
https://stackoverflow.com/questions/52964076/whats-a-valid-messagepattern-for-nestjs-mqtt-microservice

**Comment by michaelbromley** [comment]
Thanks for the pointers, I'll take a look into this after the next release most probably.

**Comment by michaelbromley** [comment]
I fixed the bootstrap issue, and I was then able to get MQTT working but had to use `hostname` rather than `host` in the transport options.
