### ISSUE TITLE
Search product by collection id with product entity

### ISSUE THREAD

**Issue by Faiyyaz** [vendure-ecommerce/vendure#2700]
Hi,

Currently if you use review plugin as described in the document then it works awesome for products but when we try to fetch by collection id we only get productvariant entity which is not same as product entity so we are not able to get rating and review which is a custom field of product entity.

Can we have a filter on products where we can give collection id and it will give product for that collection id with the possibility of pagination

**Comment by michaelbromley** [comment]
You can create your own custom query which implements this functionality. Take a look at the `customPropertyMap` feature of the ListQueryBuilder: https://docs.vendure.io/reference/typescript-api/data-access/list-query-builder/#custompropertymap
