### ISSUE TITLE
To make edit option page(/catalog/products/:id/options) be customized

### ISSUE THREAD

**Issue by choim4389** [vendure-ecommerce/vendure#2705]
**Is your feature request related to a problem? Please describe.**
Currently, in order to customize the product detail page, you need to override everything from the product list page to the Manage Variant page and the Edit Option Page (to make the breadcrumbs link into /extensions).
However, it is very difficult to modify the Edit Option Page, so it is actually very difficult to customize product-related pages.

**Describe the solution you'd like**
I don't know what the appropriate method is, but I think it would be possible to override it by adding a route like a custom List Page or Detail Page.

**Describe alternatives you've considered**
I can't figure out any other the solution

**Additional context**

**Comment by michaelbromley** [comment]
Note to self: this should be possible if we add "prefix" option to the ui extension API, and have it default to "extensions" (to mirror current behaviour). This allows the developer to set a prefix of `''` which would then allow them to override specific built-in routes.

**Comment by choim4389** [comment]
There seems to be a similar problem on the manage-variants page. 
This problem must be considered a very serious problem because it makes customization of built-in pages virtually impossible.
