### ISSUE TITLE
Feat: Expose more session cookie options

### ISSUE THREAD

**Issue by pevey** [vendure-ecommerce/vendure#2714]
This request is related to https://github.com/vendure-ecommerce/vendure/issues/436

I know this is quite an old issue, but for some reason maxAge and expires were left out when exposing the underlying express session cookie options through the config.  

As a result, all cookies use the default of 'Session' for expiry, which causes them to expire when the browser is closed (or in the case of iOS, sometimes if just the user switches to another app).

Requesting that maxAge and expires be added to the config options.  🙏

**Comment by michaelbromley** [comment]
Agreed on the above. Would you like to make a PR to the minor branch?

**Comment by pevey** [comment]
When I dug into it, I found this was user error / incomplete understanding.

The reason my session cookies were not persisting was because I was not sending the "rememberMe" boolean in the login mutation.  With the boolean set to `true`, the cookie maxAge already defaults to the session length.  

It is working as intended.
