### ISSUE TITLE
Need text only product attributes

### ISSUE THREAD

**Issue by itsgauravjain22** [vendure-ecommerce/vendure#273]
**Is your feature request related to a problem? Please describe.**
A majority of time, business products needs additional product text attributes. For eg. Weight, length, width, height. ISBN, UPC, ASIN, books pages, etc.
These attributes can't be made as facet. I have checked the online demo but found that functionality to add additional product attributes missing.

**Describe the solution you'd like**
A physical product must have weight, weight_unit, length, width, height, length unit, currency, currency_symbols attribute. These fields will be mandatory for shipping and should be on priority to include in platform.

Other than dimension and currency objects, are optional fields. There should be the ability in the platform to add those text attributes. There may types other than text attributes like multi select, radio type etc but that should be later on.

**Comment by michaelbromley** [comment]
Hi there,

Please take a look at [custom fields feature](https://www.vendure.io/docs/developer-guide/customizing-models/) as this is the mechanism for adding additional attributes to a product in Vendure. Let me know if that covers your needs.

**Comment by itsgauravjain22** [comment]
@michaelbromley Thanks for pointing it the correct solution. It works correctly. But I find adding custom attributes not very intuitive or user friendly. I hope it will be possible to add custom attributes in vendure admin UI.
Plus, I would suggest to have logic of attribute set, similar to that we have in magento. Attribute set can contain multiple number of defined attributes. These attribute set can be assigned to a product facet.
For eg. attribute set of "booksAttributeSet" can be assigned to "Books" category facet. "BooksAttributeSet" contains "ISBN13", "ISBN10", "Authors", "Publisher", "Pages", "Language", etc attributes.

**Comment by michaelbromley** [comment]
> I hope it will be possible to add custom attributes in vendure admin UI.

This will not be supported, since altering custom fields implies a database migration, and is a build-time change rather than run-time.

> Plus, I would suggest to have logic of attribute set, similar to that we have in magento.
This sounds like a useful feature, but will not be implemented for version 1.0. Feel free to create a feature request so the suggestion does not get lost.

**Comment by itsgauravjain22** [comment]
> This will not be supported, since altering custom fields implies a database migration, and is a build-time change rather than run-time.
It's a very much required functionality expected from ecommerce platform. If it's build time, Then I guess there should be serious architectural change need to be made to make them run time.

> This sounds like a useful feature, but will not be implemented for version 1.0. Feel free to create a feature request so the suggestion does not get lost.
I am creating a separate issue regarding that.

**Comment by michaelbromley** [comment]
> It's a very much required functionality expected from ecommerce platform. If it's build time, Then I guess there should be serious architectural change need to be made to make them run time.

The "attribute set", as you describe in #277 is something slightly different from CustomFields. CustomFields should apply to all Products, e.g. if you create a "product reviews" plugin, then you would define a "rating" custom field. They are build-time only because changing them at runtime by an admin would break the data model.

So CustomFields will stay as they are, but the attribute set feature will be considered as a future enhancement.

**Comment by itsgauravjain22** [comment]
@michaelbromley Noted. It makes sense to have custom attributes intact.
