### ISSUE TITLE
Admin-ui styling is broken vendure 2.2.o-next.6

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#2745]
<img width="1425" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/2833251/8e69c5bb-489a-41f3-904d-d083ceb17578">

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 2.2.0-beta
 - Nodejs version: 20
 - Database (mysql/postgres etc):mysql

**Additional context**
no console error, it seems that missed some styles

**Comment by michaelbromley** [comment]
Delete your admin ui dir and any angular cache dir and rebuild.

**Comment by tianyingchun** [comment]
yes i have rebuild the issue  also
```ts
  AdminUiPlugin.init({
      port: 3002,
      route: 'oldAdmin',
      adminUiConfig: {
        brand: 'wedglam',
        hideVendureBranding: false,
        hideVersion: false,
      },
      app: {
        path: getDirname(import.meta.url, '../../admin-ui-vendure/dist'),
      },
    }),
```

the compile scripts
```ts
import {
  compileUiExtensions,
  setBranding,
} from '@vendure/ui-devkit/compiler/index.js';
import { getDirname } from './get-dir-name.js';

export const compileAdmin = () => {
  return compileUiExtensions({
    outputPath: getDirname(import.meta.url, '../vendure-admin-ui'),
    extensions: [
      setBranding({
        // The small logo appears in the top left of the screen
        smallLogoPath: getDirname(import.meta.url, '../theme/logo.png'),
        // The large logo is used on the login page
        largeLogoPath: getDirname(import.meta.url, '../theme/logo.png'),
        // Favicon path.
        faviconPath: getDirname(import.meta.url, '../theme/favicon.ico'),
      }),
      {
        globalStyles: getDirname(import.meta.url, '../theme/theme.scss'),
      },
    ],
  });
};

```
```ts
import { existsSync, rmSync } from 'fs';
import { mergeDirs } from '@armit/file-utility';
import { compileAdmin } from './compile-admin-ui.js';
import { getDirname } from './get-dir-name.js';

const adminUIDir = `vendure-admin-ui`;
const from = getDirname(import.meta.url, '../', adminUIDir, 'dist');

const copyFiles = () => {
  const dist = getDirname(import.meta.url, '../../admin-ui-vendure/dist');
  if (existsSync(dist)) {
    rmSync(dist, { recursive: true });
  }
  mergeDirs(from, dist, 'overwrite');
};

compileAdmin()
  .compile?.()
  .then((result) => {
    copyFiles();
    console.log(result);
    process.exit(0);
  })
  .catch((err) => {
    console.log(err);
  });

```

**Comment by tianyingchun** [comment]
> Delete your admin ui dir and any angular cache dir and rebuild.

where is angular cache dir?

**Comment by tianyingchun** [comment]
i have delete all node_modules, reinstall , rebuild, restart server, build sucecss
<img width="704" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/2833251/6ce57c00-7333-4189-93e9-466852450f6c">

but start server `admin-ui` seems that lose some framework style.

**Comment by michaelbromley** [comment]
The Angular compiler with create a `.angular` directory and cache builds there.

Also delete the ` outputPath: getDirname(import.meta.url, '../vendure-admin-ui'),` directory.

**Comment by tianyingchun** [comment]
`../vendure-admin-ui` has been deleted,  no `.angular ` cache in project found.

**Comment by tianyingchun** [comment]
oh, it seems that `dark` theme is broken, cause of i have `dark` theme
