### ISSUE TITLE
Link to "Discord Community" in website footer 404s

### ISSUE THREAD

**Issue by cmpadden** [vendure-ecommerce/vendure#2794]
Browser: LibreWolf (Firefox)
Version: 124.0.1-1

Confirmed this also happens in Chrome.

---

When on the homepage:

- https://vendure.io/marketplace

Clicking the "Discord Community" link in the footer:

<img width="663" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/5807118/7d5f9c0b-3a74-4a6e-b61c-39ff5e46d17b">

Results in a 404:

- https://vendure.io/discord

<img width="1078" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/5807118/c0a52005-004b-4211-bb12-f6f520269c8d">

**Comment by michaelbromley** [comment]
@davidhoeck can you check this out?

**Comment by davidhoeck** [comment]
@michaelbromley fixed, deployed and live ✅
