### ISSUE TITLE
Link to Vendure Storefront documentation results in "Page Not Found" in web search results

### ISSUE THREAD

**Issue by cmpadden** [vendure-ecommerce/vendure#2795]
The first link when searching for Vendure storefronts results in a "Page Not Found" error. This is the first link when using DuckDuckGo.

<img width="702" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/5807118/32404832-7a79-4231-8eee-b37691d3a5c1">

Clicking the link navigates us to:

- https://docs.vendure.io/storefront

Which results in a "Page Not Found" error:

<img width="1041" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/5807118/62822d9f-fe9a-4103-918a-194455693020">

Confirmed error occurs in both Firefox and Chrome.

**Comment by michaelbromley** [comment]
Docs urls have changed since then, so I'll close this.
