### ISSUE TITLE
findOneInChannel supports only string array type relations key, but accepts objects as well and then fails 

### ISSUE THREAD

**Issue by mschipperheyn** [vendure-ecommerce/vendure#2809]
**Describe the bug**
`findOneInChannel` accepts a typeorm options object to among other things allows you to select additional relations. TypeOrm allows two ways to do it, one the common array of string keys `['relation1', 'relation1.child']`, which is deprecated and the second one which is an object `{ relation1: { child: true } }`.

However, Vendure permits both styles but only processes the string array. The second style results in a confusing error `Cannot read properties of undefined (reading 'propertyPath')`

You can see that [here](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/connection/transactional-connection.ts#L281), only an incoming property array is processed and any passed relations object is passed as is

**To Reproduce**
1. Create a class with a relation
2. Execute a query like 
3. 
```
this.connection
      .findOneInChannel(ctx, Customer, id, ctx.channelId, { relations: {.addresses: true }  })
```

**Expected behavior**
Also process incoming relations object 

**Environment (please complete the following information):**
 - @vendure/core version: 2.2.0
 - Nodejs version 20
 - Database (mysql/postgres etc): postgres

**Additional context**

**Comment by balazsgzoosh** [comment]
Hi @michaelbromley! 
I think the issue persists somewhere deep in the `EntityHydrator` service: 
When I try to hydrate a custom entity's relations, sometimes I'm getting the very same error message: 
`Cannot read properties of undefined (reading 'propertyPath')`

I think it somehow related to the `@OneToMany` relations, in our scenario we have a Company entity, which can have multiple addresses. 
The error only occours when I'm trying to load this type of relation with the entity hydrator. 
If we're loading it directly with a query it works as we would expect.

**Comment by carathorys** [comment]
Hi @michaelbromley! 
I think the issue persists somewhere deep in the `EntityHydrator` service: 
When I try to hydrate a custom entity's relations, sometimes I'm getting the very same error message: 
`Cannot read properties of undefined (reading 'propertyPath')`

I think it somehow related to the `@OneToMany` relations, in our scenario we have a Company entity, which can have multiple addresses. 
The error only occours when I'm trying to load this type of relation with the entity hydrator. 
If we're loading it directly with a query it works as we would expect.

**Comment by michaelbromley** [comment]
@carathorys thanks for the report. If you are able to put together a minimal reproduction, you could create a new issue.

**Comment by carathorys** [comment]
@michaelbromley 
I've created a repository where I'm able to reproduce the issue: 
https://github.com/carathorys/vendure-entity-hydrator-issue
I'm still able to load the relations when I'm loading it with the entity, I've created an example GQL (you can try it out): 
```graphql
query DataWithJoin {
  getDataWithJoin(id: "1") {
    customFields {
      myCustomEntity {
        id
      }
    }
  }
}
```

When I'm trying to load the relations with EntityHydrator, I'll face the issue (example GQL is here)
```graphql
query DataWithHydratrion {
  getDataWithEntityHydrator(id: "1") {
    customFields {
      myCustomEntity {
        id
      }
    }
  }
}
```

**Comment by michaelbromley** [comment]
@carathorys thanks for the update 👍
