### ISSUE TITLE
MolliePlugin >= v2.2.0 may duplicates order items resulting in higher charges

### ISSUE THREAD

**Issue by kyunal** [vendure-ecommerce/vendure#2813]
**Describe the bug**
The updated MolliePlugin that re-uses existing mollie orders rather than creating new ones can cause erroneous charges by not re-using or cancelling order lines correctly. While beneficial to the shop owner unless the customer notices, I do not think this is intentional.  

**To Reproduce**
1. Go to mollie checkout (in our storefront: AddingItems -> ArrangingPayment, then create intent)
2. Return from mollie checkout again (in our storefront: ArrangingPayment -> AddingItems)
3. Go to mollie checkout again (in our storefront: AddingItems -> ArrangingPayment, then create intent)

**Expected behavior**
Only order line items present in the vendure order end up being present in the mollie order.

**Environment (please complete the following information):**
 - @vendure/core version: 2.2.0
 - Nodejs version 18
 - Database (mysql/postgres etc): pg14.9.0

**Additional context**
I haven't debugged the issue but I believe it might stem from here https://github.com/vendure-ecommerce/vendure/blob/7d50b5446d823f933103442ac6ce99f5bd02e5b6/packages/payments-plugin/src/mollie/mollie.service.ts#L486C13-L492C14

If the order lines are equal, the first condition is not met and they will be pushed again into the mollie order by using the add operation, while old order lines are still present. I think for safety reasons it might make sense to simply cancel all old lines and then create new ones rather than to mess with re-using the existing lines, but that is just my gut feeling.

**Comment by casperiv0** [comment]
We're unfortunately also having this issue. We have the exact same reproduction steps as @kyunal. Would it be possible to get this prioritized please 🙏?

cc @jarorobbe

**Comment by casperiv0** [comment]
Looked the lines kyunal sent, I also do think cancelling all the previous mollie order lines, and then adding the new order lines is the better way to go here. WDYT @martijnvdbrug

I'm always up to work on this!

**Comment by martijnvdbrug** [comment]
Completely missed this issue, sorry guys. Looking into this right now!.

**Comment by martijnvdbrug** [comment]
I have not been able to pinpoint the exact issue, but I have a gut feeling something might have changed in the Mollie API side of things. (They also propose we move back to the Payments API now :man_facepalming: , see [this issue](https://github.com/vendure-ecommerce/vendure/issues/2921))

I took @casperiv0 approach, because there is hardly any performance impact, and it's indeed the safer route. [This PR](https://github.com/vendure-ecommerce/vendure/pull/2922) should fix the issue
