### ISSUE TITLE
Channel default currency not updating

### ISSUE THREAD

**Issue by ashishkpaul** [vendure-ecommerce/vendure#2825]
**Describe the bug**
![default_currency](https://github.com/vendure-ecommerce/vendure/assets/16308863/644f46d5-8d3e-4cd3-bb5c-1db6a15853fd)
Hello, I have upgraded to version 2.2.3. When I click on update, it shows that the update was successful. However, when I refresh the page, it reverts back to the default currency. Sometimes, I also see the same message as shown in the above image.
This is a link to a YouTube video: [default currency not updating ](https://youtu.be/JshggI64Trc)

**To Reproduce**
1. Go to 'admin panel'
2. Click on 'settings --> channels, then click on channel and try to update curency'

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version:
 - Nodejs version
 - Database (mysql/postgres etc):

**Additional context**

**Comment by ashishkpaul** [comment]
hi, i rechecked with three db, sqlite, mysql-version-8 and postgres, i face this problem only with mysql-version-8, with you advice you can close it if there is comparability issue with mysql version 8

**Comment by michaelbromley** [comment]
Hi,
mysql v8 should be supported, so I'll look into it when I get time.

**Comment by michaelbromley** [comment]
We actually have a [special clause in the currency update code](https://github.com/vendure-ecommerce/vendure/blob/9c1cb1662e899c62d93f8741f9476f415c721998/packages/core/src/service/services/channel.service.ts#L429) to specifically address this issue.

Please ensure that you have you `dbConnectionOptions.type` set to `mysql` and not `mariadb` if you are using MySQL.
