### ISSUE TITLE
React Component is not working with Admin UI 

### ISSUE THREAD

**Issue by samimhamza** [vendure-ecommerce/vendure#2848]
According to this documentation https://docs.vendure.io/guides/extending-the-admin-ui/defining-routes/

When I create A react component it return this error for all jsx elements

 `'h2' does not exist on type 'JSX.IntrinsicElements'`

**Comment by michaelbromley** [comment]
Please share steps to reproduce

**Comment by samimhamza** [comment]
I have done exactly as the documentation. on this page [](https://docs.vendure.io/guides/extending-the-admin-ui/defining-routes/#example-creating-a-greeter-route) from step 1 up to step 3 to create a new route

and this the react component 

import React from 'react';

export function Greeter() {
    const greeting = 'Hello!';
    return (
        <div className="page-block">
            <h2>{greeting}</h2>
        </div>
    );
}

**Comment by samimhamza** [comment]
One other thing that I want ot mention that defining new route is working perfectly when using angular components but when I try to use React Component it return errors like

`
'h2' does not exist on type 'JSX.IntrinsicElements'
// or
'div' does not exist on type 'JSX.IntrinsicElements'

`

**Comment by samimhamza** [comment]
One other thing that I want to mention that defining new route is working perfectly when using angular components but when I try to use React Component it return errors like

`
'h2' does not exist on type 'JSX.IntrinsicElements'
// or
'div' does not exist on type 'JSX.IntrinsicElements'

`

**Comment by michaelbromley** [comment]
OK. Did you try googling that error message? If so, what potential solutions did you find? Did you try implementing any of those solutions?
