### ISSUE TITLE
Enhance EmailSendEvent with Metadata

### ISSUE THREAD

**Issue by Anddrrew** [vendure-ecommerce/vendure#2849]
**Is your feature request related to a problem? Please describe.**
In version 2.2, the `EmailSendEvent` was introduced, which triggers when an email is successfully sent or fails to send. However, as of version 2.2.4, this event is difficult to handle because it comes with rather general fields. It would be beneficial to have a way to identify the email from its creation, through the handler, and during the processing of the `EmailSendEvent`.

**Describe the solution you'd like**
Add a metadata field that allows us to attach important data so we can identify the email for further processing.

**Additional context**
The discussion on Discord: [Link](https://discord.com/channels/1100672177260478564/1215737707725324429)

**Comment by michaelbromley** [comment]
@Anddrrew would you be interested in attempting to implement this feature?

**Comment by Anddrrew** [comment]
@michaelbromley Yes, I would try. But a little later, sometime after the 17th.

**Comment by Anddrrew** [comment]
@michaelbromley, I just added PR. I forgot a little about this issue, but the necessary changes have now been made. Please, check the docs comments, not sure about it (version especially).
