### ISSUE TITLE
Add eligible promotions query for active order

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#2866]
Having eligiblePromotions for an order is helpful in many business cases

**Comment by michaelbromley** [comment]
Hi,

would you be able to add some more details about how you imagine this API would be used? Please give some use-cases so I understand the feature better.

**Comment by michaelbromley** [comment]
This issue is being closed because further data was needed but was not provided. If you want to continue the thread, comment below with the required information and the issue can be re-opened.
