### ISSUE TITLE
cant use token to auth in graphql playground.

### ISSUE THREAD

**Issue by hanselke** [vendure-ecommerce/vendure#287]
Auth settings:

    authOptions: {
        sessionSecret: 'knn4mtoaw',
        tokenMethod: "bearer"
    }

going to the admin-api graphql, i'm trying to call

```sdl
# Write your query or mutation here
query {
            products(options: { skip: 0  }) {
                totalItems
                items {
                name
                variants {
                    sku
                    name
                    price
                }
                }
            }
        }

I get a response of

{
  "errors": [
    {
      "message": "You are not currently authorized to perform this action",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "products"
      ],
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ],
  "data": null
}
```

tried the standard JWT way of adding 
```
headers: {

  authorization: "bearer tokenfromAttemptLogin",
}
```
as well as 
```
headers: {

   "vendure-auth-token": "bearer tokenfromAttemptLogin",
}
```
they all end up with a forbidden. 
How do i make authenticated graphql calls to the admin-api?

**Comment by michaelbromley** [comment]
Hi there,

I just tested with Vendure 0.10.1 and it works for me. Perhaps the token is incorrect? Where exactly to you get `tokenfromAttemptLogin` from? What does it look like?

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.

**Comment by Psvensso** [comment]
Old issue but Google lead me here when trying to do the same and I can see there seems to be no answer/solution so I'd thought I would just share my solution here. 

Get the token from the response (read more about session token [here ](https://www.vendure.io/docs/storefront/managing-sessions/))

In the "Headers" tab at the bottom of the playground, add your header like so: 
```
{
 "Authorization": "Bearer 61d17e30218bablablabla244c6aba6e9bb0d99bc6"
}
```

**Comment by mpacary** [comment]
To complete @Psvensso 's answer, I'be been able to retrieve an admin auth token in dev environment by running this mutation on the `/admin-api` GraphQL playground:
```
mutation testlogin {
  login(username: "superadmin", password: "superadmin", rememberMe: false) {
    ... on CurrentUser {
      identifier
    }
  }
}
```
Then in the network console, look for a response header `vendure-oauth-token`. Its value is the token.
