### ISSUE TITLE
Extend AuthenticationMethod type to also return the externalIdentifier field from the DB table authentication_method

### ISSUE THREAD

**Issue by LeftoversTodayAppAdmin** [vendure-ecommerce/vendure#2871]
**Is your feature request related to a problem? Please describe.**
The authentication_method table in the DB has a field called externalIdentifier that I required for operations and plugins using an external authentication strategy like Keycloak. 

**Describe the solution you'd like**
Update the packages/core/src/api/schema/common/user.type.graphql AuthenticationMethod type to also return the externalIdentifier field.

**Describe alternatives you've considered**
I have tried to extend the existing AuthenticationMethod type in my plugin, but it would be better if the original type thats part of Vendure core itself is updated to include this field from the DB so all future users can benefit right out of the box. 

**Additional context**

**Comment by michaelbromley** [comment]
Hi,

I don't think we'll expose the `externalIdentifier` by default in the GraphQL API, as it may not be appropriate in all cases. I'd recommend you use a custom field resolver on the type to expose the field for your own case.
