### ISSUE TITLE
Variant creation problem in Generate Product Variants component

### ISSUE THREAD

**Issue by Swampy469** [vendure-ecommerce/vendure#2895]
**Describe the bug**
When trying to create multiple variants from the Generate Product Variants component (inside the product detail component) only one is created, the options and the other variants are ignored.

**To Reproduce**
1. Go to 'Create Product'
2. Fill the required fields (name, slug, sku)
3. Click "Add option"
4. Add the option name and more than 1 option value
5. The equivalent of the option value will be inserted as product variant (es, if you have 3 options you will see 3 variants)
6. Don't change any value of the variant (SKU, price, stock level)
7. Click "Create" product button
8. Only one variant will be created

**Expected behavior**
All the variants with the checkbox "Create" on true bust me created, even if the SKU or any other informations are not touched (Price, Stock Level)

**Environment:**
 - @vendure/core version: 2.2.5
 - Nodejs version: 20.12.2
 - Database (mysql/postgres etc): postgres (PostgreSQL) 15.4 (Debian 15.4-1.pgdg120+1

**Additional context**
I suspect the problem is in the Generate Product Variants that doesn't trigger the method onFormChange when a variant is automatically added through the options value.

**Screenshots**
![image](https://github.com/vendure-ecommerce/vendure/assets/46132382/b107a661-68d6-4d5b-b775-359f15263ada) After step 2
<br>
![image](https://github.com/vendure-ecommerce/vendure/assets/46132382/bb219592-4e1d-4f60-a31c-7969d8045b6a)
After step 5
<br>
![image](https://github.com/vendure-ecommerce/vendure/assets/46132382/3826a989-21e5-4fcd-868b-691240223acd)
After step 7

**Comment by michaelbromley** [comment]
Thanks for the report!

> I suspect the problem is in the Generate Product Variants that doesn't trigger the method onFormChange when a variant is automatically added through the options value.

You are totally correct. The fix is to manually call that method when adding an option. Will be fixed in next patch.
