### ISSUE TITLE
Listing options do not show up when selecting facets, and scrolls multiply when this functionality is found

### ISSUE THREAD

**Issue by DzioszkaUnicorn** [vendure-ecommerce/vendure#2898]
**Describe the bug**
I am a PM managing one of the furniture stores and I, as well as the client, are facing problems when it comes to the UI of the table, which is responsible for adding images to products. Listing options do not show up when selecting facets, and scrolls multiply when this functionality is found.

**To Reproduce**
1. Go to 'Go to product page on admin'
2. Click on 'Add resources'
![image](https://github.com/vendure-ecommerce/vendure/assets/118901030/f9ed2f81-afc2-434b-970d-8e19fd2f9ac9)
3, **You need to click on the last title of the listed faced to show listing options (it is not shown) - 1 bug**
![image](https://github.com/vendure-ecommerce/vendure/assets/118901030/c980dd17-73e7-4581-b00d-bd52671ba225)
When it will appear/or not - it depends, you can choose how many facets will be shown. Lets try with 100...
3. **It is working but it opens multiple scrolls - 2 bug**
![image](https://github.com/vendure-ecommerce/vendure/assets/118901030/4cc0b601-86ac-4fd5-9250-7eb10085ca99)

**Expected behavior**
I want to easily see the listing of facets and be able to easily select the view that satisfies me, as it was so far at the bottom of the table. The moment I select even a listing of 100 components each, I don't want the scrolls to multiply, there should be one.

**Environment (please complete the following information):**
 - @vendure/core version: 2.2.4
 - Nodejs version
 - Database (mysql/postgres etc):

**Additional context**

**Comment by michaelbromley** [comment]
Thanks for the detailed report. The fix for this will be available in the next patch release, likely within the coming week or so.

**Comment by DzioszkaUnicorn** [comment]
Thank You @michaelbromley !
