### ISSUE TITLE
Allow addition of facets & use of new facets on product create page.

### ISSUE THREAD

**Issue by ronthedrummer** [vendure-ecommerce/vendure#290]
**Is your feature request related to a problem? Please describe.**
When creating a new product, I'm needing to add a facet that doesn't exist. 

**Describe the solution you'd like**
Without having to leave the current page and restart the product creation process, I'd like the ability to add a new facet from the create product page.

**Describe alternatives you've considered**
Refresh the available facets used to populate the select when the facet select is opened, this would allow a new facet to be created in another tab, then used in the current tab.

**Additional context**
- EMPTY -

**Comment by dlhck** [comment]
_I am assuming this issue is related with v1._ Therefore this issue is being closed because further data was needed but was not provided. If you want to continue the thread, comment below with the required information and the issue can be re-opened.
