### ISSUE TITLE
Search by collection returns `null` for `productVariantAsset` even though set in admin dashboard 

### ISSUE THREAD

**Issue by casperiv0** [vendure-ecommerce/vendure#2907]
**Describe the bug**
Collection search returns `null` instead of a `Asset` type on `productVariantAsset` even though the product variant has a featured asset set in the admin dashboard.

**To Reproduce**
1. Go to a product and set a featured asset
2. Go to a product variant within that product and set a featured asset
3. Use the query below
4. See that the `productVariantAsset` is `null` and `productAsset` is not `null`.

**Expected behavior**
Should return an Asset type for both assets.

**Environment (please complete the following information):**
 - @vendure/core version: `2.2.4`
 - Nodejs version: `v20.14.0`
 - Database (mysql/postgres etc): postgres

**Additional context**
Sample query:
```graphql
query getCollectionProducts($slug: String!) {
    search(input: { groupByProduct: true, collectionSlug: $slug }) {
      totalItems
      items {
        __typename
        ...CollectionSearchProductItem
      }
    }
  }

  fragment CollectionSearchProductItem on SearchResult {
      productName
      productId
      productVariantId
      # Set in Vendure, returns Asset object ✅ 	
	  productAsset {
        preview
      }
      #  Set is Vendure, returns null via API -> bad ❌ 
      productVariantAsset {
        preview
      }
    }
```

**Comment by casperiv0** [comment]
As a temporary fix, we were able to manually set the `productVariantPreview` and `productVariantAssetId` on `search_index_item` in the database. Obviously, we don't want to do this every time ;)

I tried looking into the cause of this issue, but couldn't fully understand the indexing code in Vendure 😅

**Comment by michaelbromley** [comment]
Is the worker running and updating the search index on changes to the entities?

**Comment by casperiv0** [comment]
Yeah, looks like it ran successfully: 

<img width="1012" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/53900565/380ebc78-c79a-4f28-b058-280b73a9e088">

However, it did not update the search index when running the search query

**Comment by michaelbromley** [comment]
OK, and if you update other properties of the product/variant, such as slug, name, etc, are these successfully reflected in the search result after the worker job completes?

**Comment by casperiv0** [comment]
This is the config we're using:

```ts
// ...
    DefaultSearchPlugin.init({ bufferUpdates: false, indexStockStatus: true }),
// ...
```

It's a weird one, since I remember this working at least a version or 2 ago

**Comment by ankenu** [comment]
@michaelbromley I have the same issue. The key "productVariantAsset" is always null. Clearing the search_index_item table and reindexing products does not help. It turned out to reproduce the problem in a newly created project with pre-installed data in SQLite.
My config for the search plugin:
```
DefaultSearchPlugin.init({ bufferUpdates: false, indexStockStatus: true }),
```

**Comment by michaelbromley** [comment]
Noting this here for later investigation: perhaps this is related to a recent change in the indexing logic, which in turn is being patched by the following PR

- https://github.com/vendure-ecommerce/vendure/pull/2883

**Comment by michaelbromley** [comment]
This was fixed by the PR mentioned above. Will be available in the next patch release.

**Comment by casperiv0** [comment]
Awesome, thank you!!

**Comment by kartikjethani-solidity** [comment]
I am facing the same issue. When can we expect this patch release, please?
