### ISSUE TITLE
Different cookies (shop & admin) don't work anymore with Vendure 2.2.6

### ISSUE THREAD

**Issue by tschortsch** [vendure-ecommerce/vendure#2909]
**Describe the bug**
After upgrading to Vendure 2.2.6 it seems that the two cookies for shop-api and admin-api don't work anymore in parallel. As soon as I log into the backend or the storefront I'm getting logged out on the other api. I have the the two cookie names set via the `cookieOptions`. With Vendure 2.2.5 it works without any issues.

Could this be a regression from this change: https://github.com/vendure-ecommerce/vendure/pull/2880?

**To Reproduce**
1. Go to admin backend (or admin-api)
2. login
3. Go to storefront (or shop-api)
4. login
5. Refresh backend
6. You're logged out from backend

**Environment (please complete the following information):**
 - @vendure/core version: 2.2.6

**Comment by gdarchen** [comment]
Hi @tschortsch, 
We also just noticed that on our side. We will investigate the issue so as to propose another patch as soon as possible 😊

**Comment by michaelbromley** [comment]
@gdarchen thanks for the quick response 👍

**Comment by gdarchen** [comment]
I think I found a patch on this PR:
- https://github.com/vendure-ecommerce/vendure/pull/2911

But it's quite hard to be sure it will work as expected on client projects without packaging a new version of Vendure.
That would be awesome to be able to test it with a canary version!
