### ISSUE TITLE
Password reset request returns Success even without having an account.

### ISSUE THREAD

**Issue by KariNarhi28** [vendure-ecommerce/vendure#2937]
**Describe the bug**
I made a password reset request with the RequestPasswordResetMutation for an email that had no account attached to it.

**To Reproduce**
1. Set up Vendure with the CLI tool `npx @vendure/create app-name`
2. Start it up and go to the URL of the Shop API.
3. Do following mutation and give the email-variable E.g {"emailAddress": "hello.world@email.com"}:
```graphql
mutation RequestPasswordReset($emailAddress: String!) {
    requestPasswordReset(emailAddress: $emailAddress) {
      ... on Success {
        success
      }
      ...ErrorResult
    }
  }
 fragment ErrorResult on ErrorResult {
    errorCode
    message
  }
```
5. There was no error, it got Success but I also did not receive the email.
Here is the response:
```json
{
  "data": {
    "requestPasswordReset": {
      "success": true
    }
  }
}
```

**Expected behavior**
There should be an Error response that there is no account associated with the given email.

**Environment (please complete the following information):**
 - @vendure/core version: 2.2.6
 - Nodejs version: v20.13.1
 - Database (mysql/postgres etc): SQLite.

**Additional context**
N/A

**Comment by michaelbromley** [comment]
Hi,

This is currently working "as intended". You can read more about this in these issues:

- https://github.com/vendure-ecommerce/vendure/issues/746
- https://github.com/vendure-ecommerce/vendure/issues/1790

But as discussed in #1790 it is something I would like to make configurable.

Related PR in progress:

- https://github.com/vendure-ecommerce/vendure/pull/2786

**Comment by KariNarhi28** [comment]
OK, as a side note/question:

If a Customer gets to the "Verify Email" part of the process but for some reason closes the browser or maybe an electrical outage happens (if not on laptop/mobile), can they continue registration with same email since the account is already in the database, just not verified and without password?
