### ISSUE TITLE
Multi Vendor Support

### ISSUE THREAD

**Issue by hyndex** [vendure-ecommerce/vendure#294]
Is this framework supports multi-vendor or multiple sellers? or is there any multi-vendor or multi-seller plugin available?
By the way, the project is awesome

**Comment by michaelbromley** [comment]
Hi, thanks for the kind words :)
Currently multi-vendor is not a supported use-case, see https://www.vendure.io/docs/developer-guide/channels/#multi-tenant-marketplace-support

There is no plugin for that either yet, though a couple of people have expressed interest in building one. If one becomes available I'll make it known on the website.
