### ISSUE TITLE
Rebuild search index with disabled status

### ISSUE THREAD

**Issue by oncode** [vendure-ecommerce/vendure#295]
**Describe the bug**
When I rebuild the search index, the disabled products seem to be indexed as enabled products. I have to resave the products one by one after a full index rebuild.

**To Reproduce**
1. Set a product as disabled and save -> Product is shown as disabled in the list
2. Click on the "Rebuild search index" action
3. The product is now shown  in the product list & indexed in the elastic search index as enabled
4. (When product is opened, it shows as disabled, but has to be resaved to update the search index).

**Expected behavior**
The products should be indexed but with the correct disabled status.

**Environment (please complete the following information):**
@vendure/core version: 0.8.2
elasticsearch plugin installed
Nodejs version: 12.4.1
Database: mysql

**Comment by michaelbromley** [comment]
Confirmed also in the DefaultSearchPlugin.
