### ISSUE TITLE
No longer allowed to migrate due to MissingPrimaryColumnError in JobRecordBuffer

### ISSUE THREAD

**Issue by jakelawrence** [vendure-ecommerce/vendure#2952]
**Describe the bug**
When I spin up a new instance of Vendure and go to migrate, I get an error saying that the entity JobRecordBuffer does not have a primary column. 

**To Reproduce**
Create a new vendure instance using SQLite or SQL.js. Does not matter if there is sample data or not. 
Navigate into vendure project directory and run `npx vendure migrate`

**Expected behavior**
The migration to run

**Environment:**
 - @vendure/core version: 2.2.7
 - Nodejs version: v20.15.1
 - Database (mysql/postgres etc): SQLite or SQL.js

![error](https://github.com/user-attachments/assets/5dbd70cf-267c-4af1-85ea-ea16f5ed5b82)

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. I just tested this on a fresh install of 2.2.7 using SQLite:

1. Added a custom field to Product, `{ name: 'test', type: 'string' }`
2. `npx vendure migrate` to generate a migration
3. `npx vendure migrate` to run pending migrations

Result:
![image](https://github.com/user-attachments/assets/6bcbefd9-97d7-4948-afb4-85a23eb7563b)

I'm not sure what the difference is in your setup. I'm also on Windows but I ran the CLI through git bash, although I can't image that would make a difference.

I have seen that error in the past, but I'm not sure what caused it. Can you run 

```
npm ls typeorm
npm ls @nestjs/core
npm ls @nestjs/typeorm
```

and see if you have any version conflicts causing multiple versions of any of those packages to get installed?

**Comment by jakelawrence** [comment]
Hi,

I went to install a fresh build of Vendure and it prompted me to download the newest version of Vendure 3.0.0 within the CLI. Not sure why it wasn't doing that before but with that, it seems to be working now. Thank you for taking the time to check on that!
