### ISSUE TITLE
Core logic broken with non-English default language

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#296]
**Describe the bug**
In the VendureConfig, one can set the `defaultLanguageCode`. However, this is not actually used in any of the core business logic - instead a `DEFAULT_LANGUAGE_CODE` constant is referenced, which is hard-coded to English.

This causes errors when e.g. creating a new Facet in another language. The mutation will attempt to return the English version (which does not exist) and will result in a gql error:

https://github.com/vendure-ecommerce/vendure/blob/2231505d32e70eed39f807eb6e7506aa18094adb/packages/core/src/service/services/facet.service.ts#L77-L84

**To Reproduce**
1. Set the Admin UI defaultLanguage to e.g. 'de' (by configuring AdminUiPlugin)
2. In Admin UI, use global settings to set the language to 'de'
3. Attempt to create a new Facet
4. See error:

```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Facet.languageCode.",
      "locations": [
        {
          "line": 12,
          "column": 3
        }
      ],
      "path": [
        "createFacet",
        "languageCode"
      ]
    }
  ],
  "data": null
}
```

**Expected behavior**
It should create a new Facet in German.

**Solution**

Get rid of the `DEFAULT_LANGUAGE_CODE` constant, and instead use the `ConfigService.defaultLanguageCode`.

In the Admin UI, there is a bit of confusion between the default UI _display_ language, and the default language for the server. It seems the server defaultLanguage is not exposed via the GraphQL API, but should be added to the `GlobalSettings` type. The Admin UI can then use this value when creating new entities.

**Environment (please complete the following information):**
 - @vendure/core version: 0.10.2
 - Nodejs version: 12.4.0
 - Database (mysql/postgres etc): any

**Comment by agustif** [comment]
Yep I think I've experienced this messing up with Facets, glad it will get fixed in v0.11
