### ISSUE TITLE
AdminUiConfig apiHost and apiPort default values different than what is documented.

### ISSUE THREAD

**Issue by KariNarhi28** [vendure-ecommerce/vendure#2962]
**Describe the bug**

In [the Vendure common-package's shared-types](https://github.com/vendure-ecommerce/vendure/blob/master/packages/common/src/shared-types.ts), the default values are documented in JSDOC as:

```typescript
   /**
     * @description
     * The hostname of the Vendure server which the admin UI will be making API calls
     * to. If set to "auto", the Admin UI app will determine the hostname from the
     * current location (i.e. `window.location.hostname`).
     *
     * @default 'http://localhost'
    */
    apiHost: string | 'auto';
   /**
     * @description
     * The port of the Vendure server which the admin UI will be making API calls
     * to. If set to "auto", the Admin UI app will determine the port from the
     * current location (i.e. `window.location.port`).
     *
     * @default 3000
     */
     apiPort: number | 'auto';
```
However, [in Admin-UI plugin package's plugin.ts](https://github.com/vendure-ecommerce/vendure/blob/master/packages/admin-ui-plugin/src/plugin.ts), the `propOrDefault()`-function handles them like this:

```typescript
     apiHost: propOrDefault('apiHost', 'auto'),
     apiPort: propOrDefault('apiPort', 'auto'),
```

So the actual default values are `auto` for both, not `apiHost: http://localhost` and `apiPort: 3000`.

**To Reproduce**
1. Go to mentioned [common](https://github.com/vendure-ecommerce/vendure/blob/master/packages/common/src/shared-types.ts) and [admin-ui-plugin](https://github.com/vendure-ecommerce/vendure/blob/master/packages/admin-ui-plugin/src/plugin.ts) packages.
2. Check lines 216 - 233 for common and 281 - 282 for admin-ui-plugin.
3. Check `propOrDefault()`-function definition from line 264 onward (admin-ui-plugin).
4. The function clearly shows that the second value is `defaultVal` which is `auto` in the lines 281 - 282.

**Expected behavior**
Either correct the default values to the documented ones or correct documentation to "auto" for both properties.

**Environment (please complete the following information):**
 - @vendure/core version: 3.0.0
 - Nodejs version: v20.13.1
 - Database (mysql/postgres etc): postgres

**Additional context**
N/A

**Comment by michaelbromley** [comment]
Hi,

Yes you are totally correct. We should correct the documentation to show the correct default values.

Would you be interested in making a PR for this?

**Comment by KariNarhi28** [comment]
> Hi,
> 
> Yes you are totally correct. We should correct the documentation to show the correct default values.
> 
> Would you be interested in making a PR for this?

Unfortunately I currently have a tight schedule on a customer project, even though this would be rather simple change.

**Comment by michaelbromley** [comment]
No problem, thanks for the detailed report 👍
