### ISSUE TITLE
GetOrderDetails Query take 10 seconds to load

### ISSUE THREAD

**Issue by arrrrny** [vendure-ecommerce/vendure#2968]
**Describe the bug**
GetOrderDetails Query take 10 seconds to load, this is way north of industry standards < 2s
**To Reproduce**
1. Go to Orders on Admin
2. Click on any order detail
3. Loading takes 10 seconds consistently

**Expected behavior**
It should take less than a sec, since I have only 1 order.

**Environment (please complete the following information):**
 - @vendure/core version: 3.0.0
 - Nodejs version 20
 - Database (mysql/postgres etc): postgres

**Additional context**
I am on M1 Mac

**Comment by michaelbromley** [comment]
Hi, I cannot reproduce this. Here's my test on a local version of v3.0.0 with the normal test data: 

![image](https://github.com/user-attachments/assets/5691bb27-81d9-48be-b42d-115f07dbefea)

On the live version at demo.vendure.io/admin I get similar results, ~100-200ms.

Do you by any chance have relation custom fields defined on the Order or OrderLine entities? If so can you share the config?

**Comment by arrrrny** [comment]
I reproduced it on a brand new setup no customization
![Screenshot 2024-07-22 at 12 29 17 PM](https://github.com/user-attachments/assets/998ce4ac-87ac-49d9-af63-5dc27197cfef)
![Screenshot 2024-07-22 at 12 29 39 PM](https://github.com/user-attachments/assets/8b4cd71b-444e-4215-bfe3-8ddd5f8f4648)
import {
    dummyPaymentHandler,
    DefaultJobQueuePlugin,
    DefaultSearchPlugin,
    VendureConfig,
} from '@vendure/core';
import { defaultEmailHandlers, EmailPlugin } from '@vendure/email-plugin';
import { AssetServerPlugin } from '@vendure/asset-server-plugin';
import { AdminUiPlugin } from '@vendure/admin-ui-plugin';
import 'dotenv/config';
import path from 'path';

const IS_DEV = process.env.APP_ENV === 'dev';

export const config: VendureConfig = {
    apiOptions: {
        port: 3000,
        adminApiPath: 'admin-api',
        shopApiPath: 'shop-api',
        // The following options are useful in development mode,
        // but are best turned off for production for security
        // reasons.
        ...(IS_DEV ? {
            adminApiPlayground: {
                settings: { 'request.credentials': 'include' },
            },
            adminApiDebug: true,
            shopApiPlayground: {
                settings: { 'request.credentials': 'include' },
            },
            shopApiDebug: true,
        } : {}),
    },
    authOptions: {
        tokenMethod: ['bearer', 'cookie'],
        superadminCredentials: {
            identifier: process.env.SUPERADMIN_USERNAME,
            password: process.env.SUPERADMIN_PASSWORD,
        },
        cookieOptions: {
          secret: process.env.COOKIE_SECRET,
        },
    },
    dbConnectionOptions: {
        type: 'postgres',
        // See the README.md "Migrations" section for an explanation of
        // the `synchronize` and `migrations` options.
        synchronize: false,
        migrations: [path.join(__dirname, './migrations/*.+(js|ts)')],
        logging: false,
        database: process.env.DB_NAME,
        schema: process.env.DB_SCHEMA,
        host: process.env.DB_HOST,
        port: +process.env.DB_PORT,
        username: process.env.DB_USERNAME,
        password: process.env.DB_PASSWORD,
    },
    paymentOptions: {
        paymentMethodHandlers: [dummyPaymentHandler],
    },
    // When adding or altering custom field definitions, the database will
    // need to be updated. See the "Migrations" section in README.md.
    customFields: {},
    plugins: [
        AssetServerPlugin.init({
            route: 'assets',
            assetUploadDir: path.join(__dirname, '../static/assets'),
            // For local dev, the correct value for assetUrlPrefix should
            // be guessed correctly, but for production it will usually need
            // to be set manually to match your production url.
            assetUrlPrefix: IS_DEV ? undefined : 'https://www.my-shop.com/assets/',
        }),
        DefaultJobQueuePlugin.init({ useDatabaseForBuffer: true }),
        DefaultSearchPlugin.init({ bufferUpdates: false, indexStockStatus: true }),
        EmailPlugin.init({
            devMode: true,
            outputPath: path.join(__dirname, '../static/email/test-emails'),
            route: 'mailbox',
            handlers: defaultEmailHandlers,
            templatePath: path.join(__dirname, '../static/email/templates'),
            globalTemplateVars: {
                // The following variables will change depending on your storefront implementation.
                // Here we are assuming a storefront running at http://localhost:8080.
                fromAddress: '"example" <noreply@example.com>',
                verifyEmailAddressUrl: 'http://localhost:8080/verify',
                passwordResetUrl: 'http://localhost:8080/password-reset',
                changeEmailAddressUrl: 'http://localhost:8080/verify-email-address-change'
            },
        }),
        AdminUiPlugin.init({
            route: 'admin',
            port: 3002,
            adminUiConfig: {
                apiPort: 3000,
            },
        }),
    ],
};

below is response. 

Vendure is running on host, postgres is on docker.

{
    "data": {
        "order": {
            "id": "3",
            "createdAt": "2024-07-22T06:28:20.903Z",
            "updatedAt": "2024-07-22T06:28:20.903Z",
            "type": "Regular",
            "aggregateOrder": null,
            "sellerOrders": [],
            "code": "WH61PTH2L4NGZDCG",
            "state": "Draft",
            "nextStates": [
                "Cancelled",
                "ArrangingPayment"
            ],
            "active": false,
            "couponCodes": [],
            "customer": null,
            "lines": [],
            "surcharges": [],
            "discounts": [],
            "promotions": [],
            "subTotal": 0,
            "subTotalWithTax": 0,
            "total": 0,
            "totalWithTax": 0,
            "currencyCode": "USD",
            "shipping": 0,
            "shippingWithTax": 0,
            "shippingLines": [],
            "taxSummary": [],
            "shippingAddress": {
                "fullName": null,
                "company": null,
                "streetLine1": null,
                "streetLine2": null,
                "city": null,
                "province": null,
                "postalCode": null,
                "country": null,
                "countryCode": null,
                "phoneNumber": null,
                "__typename": "OrderAddress"
            },
            "billingAddress": {
                "fullName": null,
                "company": null,
                "streetLine1": null,
                "streetLine2": null,
                "city": null,
                "province": null,
                "postalCode": null,
                "country": null,
                "countryCode": null,
                "phoneNumber": null,
                "__typename": "OrderAddress"
            },
            "payments": [],
            "fulfillments": [],
            "modifications": [],
            "__typename": "Order"
        }
    }
}

**Comment by michaelbromley** [comment]
Thanks for providing the extra details. By the way, for code block if you surround it with 3 backticks you get nice formatting: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

So I must assume there is something about your environment that is causing this - I just updated one of our prod apps to v3.0.0 and we area also using postgres. With multiple custom fields (including relations) defined on both Order and OrderLine, I'm seeing response times for that query of around 600ms.

Are any of the other queries slow? On the default test dataset I would consider anything above ~300ms to be slow locally.

**Comment by arrrrny** [comment]
I will try with standalone postgres later. It might be some weird docker thing on m1 silicon. Other queries are normal. I made 56K inserts.
