### ISSUE TITLE
LocaleDate displays incorrect time format for certain locales

### ISSUE THREAD

**Issue by williamrijksen** [vendure-ecommerce/vendure#2970]
**Describe the bug**
The I18n LocaleDate shows a 12-hour format, while in my country it should not show AM/PM, but a 24-hour format instead.

**To Reproduce**
1. Make sure the locale of your browser is set to NL_nl.
1. Login.
1. Open the orders.
1. Notice that the time is shown in the 12-hour format.

**Expected behavior**
I expect the time to be displayed in the format of my locale, which is a 24-hour format.

**Environment:**
@vendure/core version: v3

**Comment by michaelbromley** [comment]
Thanks for opening the issue.

This behaviour is controlled by the [hour12 property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#hour12).

From the MDN docs (my emphasis added):

> Whether to use 12-hour time (as opposed to 24-hour time). Possible values are true and false; **the default is locale dependent**.

Looking at the [localeDatePipe source code](https://github.com/vendure-ecommerce/vendure/blob/master/packages/admin-ui/src/lib/core/src/shared/pipes/locale-date.pipe.ts#L50) I can see that we are explicitly setting `hour12: true,`.

So we should just be able to omit this property and then the correct format will be used for the current locale.
