### ISSUE TITLE
How do I migrate in CI/CD pipeline ?

### ISSUE THREAD

**Issue by meyvan** [vendure-ecommerce/vendure#2976]
**Describe the bug**
Following the docs: https://docs.vendure.io/guides/developer-guide/migrations/ I can create a migration in local.

But how am I supposed to run the migration in an existing running server ?

I CANNOT RUN `npx vendure migrate and select "Run pending migrations"`  because this will run inside Github Actions and how am I suppose to select the option ?

**To Reproduce**
1. Follow https://docs.vendure.io/guides/developer-guide/migrations/
2. Run `npx vendure migrate`  option in Github Actions
3. Option cannot be selected in pipeline

**Expected behavior**
A simple way is to allow sending in arguments like `--run` 

**Environment (please complete the following information):**
 - @vendure/core version: v3.0.0
 - Nodejs version: v18.19.1
 - Database (mysql/postgres etc): postgres

**Comment by jyling** [comment]
> https://docs.vendure.io/guides/developer-guide/migrations/#3-run-the-migration
```
Assuming the migration file looks correct, the next time you start the server, 
the migration will be run automatically. This is because the runMigrations 
function is called in the src/index.ts file:
```

Migration should run automatically when you start the server, unless I misunderstood your issue ?

**Comment by meyvan** [comment]
Automatically updating the DB schema when server is started is a Anti-DevOps principle. We should be able to control when and how we run the migrations. And for that `npx vendure migrate ` command is good, but it is interactive, which cannot(or hard to achieve) in a Github Actions CI/CD pipeline.

A better option is to send in arguments like `--no-interaction` combined with `--runMigration`  or other arguments like that

Nevertheless, I found a way to run the migration separately. 

And to anyone coming here, at the time of writing, copy the

```
import {  runMigrations } from '@vendure/core';
import { config } from './vendure-config';

runMigrations(config)
    .then(() => console.log('Migration Complete'))
    .catch(err => {
        console.log(err);
    });

```

into a separate file and run it using `ts-node migrate.ts`  , whenever and wherever you like

**Comment by michaelbromley** [comment]
@meyvan non-interactive mode for CLI commands is coming in an upcoming feature release.
