### ISSUE TITLE
Admin UI SDK for developing completely custom Admin UI from scratch.

### ISSUE THREAD

**Issue by KariNarhi28** [vendure-ecommerce/vendure#2985]
**Is your feature request related to a problem? Please describe.**

As convenient as the current Admin UI is, there are some bugs or other issues about it here and there or just difference in opinions.

One thing that mostly caught my eye is that the Admin UI is either not fully responsive for mobile-view or that some buttons are placed in weird places or too close to the edge of the screen (most of the Create/Update -buttons are just at the right edge).

These issues wont get fixed until Vendure devs do it or community does it, and that can take time which people do not always have.

Also the theming / UI library choice of Clarity Design System is a bit opinionated, as there is no alternative to use. I believe it is going to be replaced by TailwindCSS in future? (saw that somewhere).

Even so, I'd prefer to have freedom of choice with the UI library, instead of just Clarity or TailwindCSS in the future.

**Describe the solution you'd like**
SDK for creating the Admin UI from scratch, so that people can use whatever front-end solution they want to implement the Admin UI and then connect it with the API.

I personally would like to use a combination of Angular Material and TailwindCSS as I do with the Storefront.

Most likely the SDK should have configurations for setting up the API-connection and any TypeORM / GraphQL -related stuff, whatever way the current Admin UI handles the queries/mutations etc....

**Describe alternatives you've considered**
Make the current Admin UI agnostic about the UI library it uses and expose the Admin UI components so that we can modify them directly, instead of through plugins with the PageLocationId's.

Of course, the plugin-system still can exist, but I believe it would be easier to develop the custom features straight into the component source.

**Additional context**
N/A

**Comment by michaelbromley** [comment]
Hi, thanks for the suggestion. This is covered in an existing issue:

- #2621

That issue focuses on the Shop API but the solution would be applicable to both. So I'll close this and track on the existing issue.

**Comment by KariNarhi28** [comment]
OK. I thought it was only about Storefront, not Admin UI.
