### ISSUE TITLE
How the server and worker are communicating after deployment

### ISSUE THREAD

**Issue by moussaab-moulim** [vendure-ecommerce/vendure#2989]
hello
i deployed Vendure in Railway using the dokerfile
i have the server on the public domain : server-app.example.com
the worker on worker-app.example.com

in the local environment i understand that they run in parallel thay somehow communicate

but i dont understand how that is done after deployment 
i feel like there is a step that i am missing

**Comment by michaelbromley** [comment]
They communicate via the job queue. The server adds jobs to the queue, the worker processes the jobs.

By the way this type of question is best asked in our discord community rather than as an issue on GitHub

http://vendure.io/community
