### ISSUE TITLE
Allow overriding Importer class methods

### ISSUE THREAD

**Issue by yazfield** [vendure-ecommerce/vendure#3000]
Hey,

I'm currently using the `Importer` class but needed to override `getFacetValueIds` as I wanted facets to be imported to a different channel than the product.

But unfortunately the method is `private` see [here](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/data-import/providers/importer/importer.ts#L300C5-L300C12)

Would it be possible to change it to `protected` or is there a reason to disallow this?
This would help me save time by avoiding having to reimplement the whole thing.

Thanks!

**Comment by michaelbromley** [comment]
Yes, I'd be happy to merge a PR that changes the private methods to protected if that makes it more flexible.

**Comment by dlhck** [comment]
@yazfield would you still provide a PR for that?

**Comment by yazfield** [comment]
@dlhck sorry took long for such simple change 😅 looking forward to contributing more

**Comment by dlhck** [comment]
@yazfield no worries! 😄 thank you for the PR. @michaelbromley will take a look asap!
