### ISSUE TITLE
Price calculated wrong with discount coupon

### ISSUE THREAD

**Issue by dfernandesbsolus** [vendure-ecommerce/vendure#3003]
**Describe the bug**
In my exemple i put several units of the same product in the cart, i applied a 10% discount coupon, the correct order value should be $1110.92, but it shows $1110.85

**To Reproduce**
1. Add many units of the same products product
2. Create a cupom with 10% of discount
3. Add this cupom to order
4. Check the order on admin

**Expected behavior**
Value should be $1110.92, but it shows $1110.85 

**Environment (please complete the following information):**
 - @vendure/core version: 2.2.6
 - Nodejs version 20.10.0
 - Database (mysql/postgres etc): postgres

**Additional context**
![image](https://github.com/user-attachments/assets/ac8f340b-9c3e-41cc-be7d-1031d0258716)

**Comment by michaelbromley** [comment]
I think this might be related to the default rounding logic, where small rounding errors will compound when the quantity is high, as it is here. Can you try with this config and see if it makes a difference?

```ts
import { DefaultMoneyStrategy, VendureConfig } from '@vendure/core';

export class CustomMoneyStrategy extends DefaultMoneyStrategy {
    override round(value: number, quantity = 1): number {
        return Math.round(value * quantity);
    }
}
```

```ts
export const config: VendureConfig = {
    // ...
    entityOptions: {
        moneyStrategy: new CustomMoneyStrategy(),
    }
}
```

**Comment by dfernandesbsolus** [comment]
@michaelbromley you're right, it works now :D Thanks, do you want a pull request with this?

<img width="989" alt="image" src="https://github.com/user-attachments/assets/1048f5e5-1784-4c8d-8a49-8f77f07a107a">

**Comment by michaelbromley** [comment]
Great. Yes, I think we should change the default behaviour in v3.1. You can make a PR to the `minor` branch which updates the `DefaultMoneyStrategy.round()` logic as above.
