### ISSUE TITLE
Assign To Channel button disappear when more than 5 channels assigned on Admin

### ISSUE THREAD

**Issue by arrrrny** [vendure-ecommerce/vendure#3019]
**Describe the bug**
Assign to Channel button disappear when there are more than 5 channels assigned to the product. 

**To Reproduce**
1. Go to Product on Admin
2. Click on Assign to Channel and assign it to more than 6 channels
3. Button will disappear

**Expected behavior**
For starter, Button should be kept always up. This prevents overflow. Overflow can be handled by '... more' and when user clicks on '...more' other channels could be viewed and removed.

**Environment (please complete the following information):**
 - @vendure/core version: 3.0.0
 - Nodejs version 20
 - Database (mysql/postgres etc): postgres

**Additional context**
![Screenshot 2024-08-18 at 6 04 49 PM](https://github.com/user-attachments/assets/e0d90e6b-5dec-4739-9d8c-9a676bb5113c)

![Screenshot 2024-08-18 at 6 05 02 PM](https://github.com/user-attachments/assets/8bfbd1dd-b75d-4bb2-9ebd-7114e4e2cd9b)

**Comment by monrostar** [comment]
this is already fixed. I have already made this fix in the new version which will be released soon.

**Comment by arrrrny** [comment]
Thanks @monrostar ! look forward to it.
