### ISSUE TITLE
Show 3 decimals tax rates in tax summary section of order in admin UI

### ISSUE THREAD

**Issue by OlivierPineau-qc** [vendure-ecommerce/vendure#3051]
**Describe the bug**
It is not a bug but a simple fix can help me greatly. I have a store in the province of Quebec, Canada and in Quebec we have two tax rates, 9.975% and 5%. 

I already implemented a plugin to handle all of this on my orders and showing the three decimals in the admin UI in the tax-rates page.

This is how it looks in the admin UI tax rate page. 
![image](https://github.com/user-attachments/assets/4e27fced-53cb-455a-9d32-fd402c7976fa)

The problem is in the order detail page, specifically in the tax summary section. See below
![image](https://github.com/user-attachments/assets/81a1d2ee-7ee7-4a28-86e2-78d5dec0d50b)

I think I already know how to fix this. The tax summary table uses the percentPipe from Angular. The percentPipe supports adding up to three decimals if value provided has three decimals.

The code that needs to be changed is [here](https://github.com/vendure-ecommerce/vendure/blob/master/packages/admin-ui/src/lib/order/src/components/order-detail/order-detail.component.html).

Here is the path for the monorepo if you don't want to click the link : packages/admin-ui/src/lib/order/src/components/order-detail/order-detail.component.html at line 176.

The fix would simply be to replace `percent : '0.0-2'` to `percent : '0.0-3'` and Angular percentPipe will handle the rest :)

Should I create a pull request for this ?

Thanks

**Comment by michaelbromley** [comment]
Hi, thanks for the report and analysis.
I'm currently doing some work for a new release I want to get out today so since it's such a small fix I'll take care of it 👍

**Comment by michaelbromley** [comment]
In attempting to reproduce this, I noticed that I was unable to even set a TaxRate to `9.975` - it would get rounded to `9.98`.

On investigation this is because the `TaxRate.value` column is set with a precision of `2`.

Have you modified this column (eg via an EntityMetadataModifier) in order to increase the precision?

**Comment by michaelbromley** [comment]
Alright thanks, that now makes total sense. OK the fix was just published in v3.0.3, enjoy!

**Comment by OlivierPineau-qc** [comment]
> Alright thanks, that now makes total sense. OK the fix was just published in v3.0.3, enjoy!

Thank you so much !
