### ISSUE TITLE
requestPasswordReset mutation doesn't trigger anything. Not even on query level.

### ISSUE THREAD

**Issue by promartin** [vendure-ecommerce/vendure#3067]
**Describe the bug**
I implemented the `login`, `registerCustomerAccount` methods successfully, but I ran into an annoying issue, that I need help with.

There is a GraphQL mutation called `requestPasswordReset` which does work with Postman and triggers all the Vendure events that should be triggered, creates a new `passwordResetToken` in the database and generates an Email.

But whenever I try to call that endpoint from my web app I get a response saying success, but nothing happens on the backend, nothing gets triggered, no email generation is happening, the `passwordResetToken` field in the database stays empty. Why is that?

**To Reproduce**
1. In my `/app/providers/account/account.ts` file I implemented the GraphQL query like so:
```
gql`
  mutation requestPasswordReset(
    $emailAddress: String!
) {
    requestPasswordReset(
        emailAddress: $emailAddress
    ) {
        __typename
        ... on NativeAuthStrategyError {
            errorCode
            message
        }
        ... on Success {
            success
        }
    }
}
`;
```
2. Ran `yarn generate`
3. Implemented the `requestPasswordReset` method in the same file like so:
```
export const requestPasswordReset = async(
  input: { emailAddress: string; },
  options: QueryOptions,
): Promise<RequestPasswordResetMutation['requestPasswordReset']> => {
  return sdk.requestPasswordReset(input, options).then((res) => res.requestPasswordReset);
};
```
4. Implemented the action for the `requestPasswordReset` method like so:
```
//app/routes/api/user/forgot-password.tsx

import { ActionFunctionArgs, json, redirect } from "@remix-run/server-runtime";
import { requestPasswordReset } from "~/providers/account/account";
import { EMAIL_REGEX } from "~/utils/registration-helper";

export async function action({ params, request }: ActionFunctionArgs) {
  const body = await request.formData();
  const email = body.get('email');
  
  if (!email || typeof email !== 'string' || !email.match(EMAIL_REGEX)) {
    const formError = { form: "Invalid email address" };
    return json(formError, { status: 400 });
  }

    const result = await requestPasswordReset({ emailAddress: email }, { request });

    console.log(result);

    if (!result) {
      const formError = { form: "No response from the server" };
      return json(formError, { status: 500 });
    }

    if (result.__typename === 'Success') {
      return redirect('/success');
    } else {
      const formError = { form: result.message || "An error occurred" };
      return json(formError, { status: 401 });
    }
}
```
5. Created the form from which you can call this action and run the mutation like this:
```
//app/components/form/PasswordForm.tsx

import { Button } from "../ui-custom/MyButton";
import { Input } from "../ui-custom/MyInput";
import { Label } from "../ui/label";
import { Form } from "@remix-run/react";

const PasswordForm = () => {
  return (
    <Form method='post' action='api/user/forgot-password' className='flex flex-col gap-6'>
      <div className='grid w-full items-center'>
        <Label className='mb-1.5' htmlFor='email-address'>
          Email address
        </Label>
        <Input name='email' type='text' id='email-address' />
      </div>
      <div className='flex flex-col gap-4'>
        <Button type="submit">Request new password</Button>
      </div>
    </Form>
  );
};

export default PasswordForm;
```

**Expected behavior**
When I press `Request new password` button, I expect the mutation to trigger all the events, that it triggers when I send the same request from Postman and generate an Email for me the same way.

**Environment (please complete the following information):**
 - @vendure/core version: 3.0.0
 - Nodejs version: v20.14.0
 - Database postgres: v16.4.0

**Additional context**
I logged everything form the beginning to the end, it should be working, the email that I want to get a reset token for does exists in the database.

**Comment by michaelbromley** [comment]
This probably means that you are passing an email address that is not in the system. You can find more information on this behaviour here:

- https://github.com/vendure-ecommerce/vendure/issues/2937

It is something we intend to revisit because it can cause confusion.

**Comment by promartin** [comment]
It turned out that my .env file wasn't configured correctly 😅😅
