### ISSUE TITLE
AuthOptions.sessionDuration does not support actual milliseconds passed as number

### ISSUE THREAD

**Issue by pujux** [vendure-ecommerce/vendure#3078]
The [docs](https://docs.vendure.io/reference/typescript-api/auth/auth-options#sessionduration) say that sessionDuration can be passed as a number or string, using the [ms](https://www.npmjs.com/package/ms) package to convert the string expression to milliseconds... when you actually pass milliseconds though, the `ms` function will convert from milliseconds to string expression which breaks session creation.

I would propose to only convert strings using the `ms` function or change the docs to explicitely say that milliseconds should not be passed as number but as string (as the `ms` package documentation says, strings that just contain a number and not an expression will just be converted to a number) 

https://github.com/vendure-ecommerce/vendure/blob/a735bdf9eaadb83251eec1a135b084569d10e333/packages/core/src/service/services/session.service.ts#L40

**Comment by pujux** [comment]
I'd be fine to provide a PR fixing this in either of the proposed ways of course! 👍

**Comment by dlhck** [comment]
I would propose we do a type check and only use the ms package when a string is passed, as there are still a lot of developers that build durations by multiplication like `30 * 60 * 1000` (30min). @michaelbromley wdyt?

**Comment by michaelbromley** [comment]
Yes, I agree with that approach. And @pujux a PR would be very welcome!

We also have the exact same issue with `verificationTokenDuration` - this can be handled in the same PR.

**Comment by pujux** [comment]
While looking over the other `authOptions` I asked myself if supporting string expressions for `sessionCacheTTL` would be a good idea? What do you think? 

Of course we would need to divide the outcome of the `ms` function by 1000 to retrieve seconds instead of milliseconds but it might be a good thing do have.

**Comment by dlhck** [comment]
@pujux I think that's a great idea, but the number value should represent seconds in case you "manually" define the TTL. Could you please update the docs too? 😄
