### ISSUE TITLE
Administrator-created Orders / editing Orders

### ISSUE THREAD

**Issue by drewniakradoslaw** [vendure-ecommerce/vendure#314]
It's nice as if it was possible to add orders directly from the administration panel. Possibility to edit orders, for example price to pay, invoice or purchased product.

**Comment by chladog** [comment]
I see this as big topic, from my use-case and experience there are some features to consider:

- adding new product variants to the order (& autocomplete search field)
- changing quantities of the OrderLine in the order
- removing OrderLines from the order
- ^ products should be allocated/released accordingly 
- visual feedback of total amount already paid and difference that needs to be refunded or to be charged extra (a button that would do the action of either refunding (surplus) or create a new payment (shortage) to which we could hook an email.
- adding multiple [custom surcharges](https://github.com/vendure-ecommerce/vendure/issues/470#issuecomment-704743664) (#470) with custom description (custom extra fee, product that are not in system, discounts (should be possible to enter negative value)) & selection of their tax category
- promotions should be recaulcated based on changes to the order by administrator (but maybe some use cases would need an option to "freeze" promotions already applied)
- changes should be logged in history timeline stating a person responsible (probably better if there is to be an "edit mode" and do the changes in batch on saving the changes).
- fulfilled items shouldn't be editable (though items from cancelled fulfillments should be)
- changing & adding shipping methods (current data model allows only single shipping per order, but there might be cases when order is needed to be split into 2 independently charged fulfillments)

**Comment by michaelbromley** [comment]
Excellent feedback! Thanks and also I want to cancel this issue now cos it is too complex 😅 /joke

**Comment by michaelbromley** [comment]
One question @chladog regarding this line:

> adding multiple custom surcharges (#470) with custom description (custom extra fee, product that are not in system, discounts (should be possible to enter negative value)) & selection of their tax category

Specifically with a _negative surcharge_ such as a negotiated discount with the customer. From a taxation perspective, how would you expect tax to work on a discount? Do you have a good mental model for this because I get confused thinking about it :D

**Comment by chladog** [comment]
@michaelbromley Sorry, missed this message :-) frankly I wasn't paying as much attention to taxes as I should've (our data goes directly to accounting program). I'm sure after your research on the topic #573 you know more than me in this regards. 
I just know there is a business need for shop managers to be able to apply **custom** discounts and surcharges additionally to changing order contents made out of in-system items (products, shippings).

**Comment by michaelbromley** [comment]
The core parts of order modification are now in place in core & admin-ui. This was a huge task - over 50 hours of work! 

I'm going to close this issue, but it is possible that some of the details are still missing, and there are probably edge-cases that will need to be fixed. But I want to get the feature out there in the next release and then let's take individual bugs/missing features up as we find them, as new separate issues.
