### ISSUE TITLE
Quick jump to variant select has no options after upgrading to 3.0.4

### ISSUE THREAD

**Issue by brmk** [vendure-ecommerce/vendure#3143]
**Describe the bug**
"Quick jump to variant" select has no options.

**To Reproduce**
1. Go to a product variant details page
2. Click on the "Quick jump to variant" select
3. See "No options" placeholder

**Expected behavior**
List of variants should appear in the select

**Environment (please complete the following information):**
 - @vendure/core version: 3.0.4
 - Nodejs version 20
 - Database (mysql/postgres etc): posgres

**Additional context**
Downgrading vendure to 3.0.3 fixes the issue, presenting the regression in 3.0.4. Probably in the UI component, since the Graphql query `GetProductVariantsQuickJump` is present when inspecting the network tab

**Comment by toBeOfUse** [comment]
I noticed this too. Would it be helpful if I created a PR for this next week?

**Comment by michaelbromley** [comment]
@toBeOfUse yes a PR would be very appreciated!
