### ISSUE TITLE
Order designation

### ISSUE THREAD

**Issue by radidas** [vendure-ecommerce/vendure#315]
It is worth adding the options of the numbers themselves in the order to make it easier to communicate with the customer.

**Comment by michaelbromley** [comment]
I'm sorry I don't understand exactly what is being proposed here. Could you clarify? Maybe with an example?

**Comment by radidas** [comment]
There is an order number in the shop demo: L1GG1SVMJXEZ3XNS. It would be easier for the customer to give just the numbers 0023453834940 than numbers and letters. I'm not saying that the options with letters have to be removed, but it would be nice if the administrator had the option to choose this.

**Comment by michaelbromley** [comment]
I understand, thanks. This is already possible via the `generateOrderCode` function which can be specified in your config: https://www.vendure.io/docs/typescript-api/orders/order-options/#generateordercode

Please take a look, and if that satisfies your requirement, you can close this issue :)
