### ISSUE TITLE
VAT on customer destination 

### ISSUE THREAD

**Issue by acerov** [vendure-ecommerce/vendure#3162]
Hi, I looked at the demo and I can't find an answer to the question: does Vendure support VAT by customer address, for example if we have one webshop for the whole of Europe and VAT is calculated by customer address.

I assume that it is supported, but as I did not find it myself, please clarify.

**Comment by michaelbromley** [comment]
Hello,
This is configured using the [TaxZoneStrategy](https://docs.vendure.io/reference/typescript-api/tax/tax-zone-strategy/). By default it is just configured to use whatever the channel's default tax zone is set to, so you'll need to implement a custom strategy that looks at the customer address (if available) to determine the correct zone. The current customer can be derived from the `ctx.activeUserId` property in combination with [CustomerService.findOneByUserId](https://docs.vendure.io/reference/typescript-api/tax/tax-zone-strategy/).
