### ISSUE TITLE
Failure deploying starters remix storefront on Vercel

### ISSUE THREAD

**Issue by johnygold** [vendure-ecommerce/vendure#3180]
When I install the default remix storefront locally, it runs just fine. However deploying it on Vercel gives:

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'i18next-fs-backend' imported from /var/task/build/index.js

Adding it to package.json does not seem to fix it.

Also, npm install i18next-fs-backend does not work, it gives:

npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @remix-validated-form/with-zod@2.0.5
npm error Found: remix-validated-form@5.1.5
npm error node_modules/remix-validated-form
npm error   remix-validated-form@"^5.1.5" from the root project
npm error
npm error Could not resolve dependency:
npm error peer remix-validated-form@"^4.x" from @remix-validated-form/with-zod@2.0.5
npm error node_modules/@remix-validated-form/with-zod
npm error   @remix-validated-form/with-zod@"^2.0.5" from the root project
npm error
npm error Conflicting peer dependency: remix-validated-form@4.6.12
npm error node_modules/remix-validated-form
npm error   peer remix-validated-form@"^4.x" from @remix-validated-form/with-zod@2.0.5
npm error   node_modules/@remix-validated-form/with-zod
npm error     @remix-validated-form/with-zod@"^2.0.5" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error

It only works when adding: --legacy-peer-deps
This also applies to the general npm install, when installing the storefront.

But nevertheless, running: npm install i18next-fs-backend  --legacy-peer-deps

It keeps giving the same error:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'i18next-fs-backend' imported from /var/task/build/index.js

**Comment by michaelbromley** [comment]
Hi,

could you please open this on the project-specific repo? Thanks! 

https://github.com/vendure-ecommerce/storefront-remix-starter/issues
