### ISSUE TITLE
Harden plugin blocks simple query

### ISSUE THREAD

**Issue by Huararanga** [vendure-ecommerce/vendure#3213]
Hi vendure,
harden plugin generates high complexity for simple query for my sitemap.

[HardenPlugin] Query complexity of "anonymous" is 4626, which exceeds the maximum of 650

"Rest of queries seems to be unaffected"

**To Reproduce**
1) Enable harden plugin
import { HardenPlugin } from "@vendure/harden-plugin";

HardenPlugin.init({
  maxQueryComplexity: 650,
  apiMode: process.env.APP_ENV === "dev" ? "dev" : "prod",
}),

2) Add sitemap query:

import gql from 'graphql-tag';
import { sdk } from '../../graphqlWrapper';
import { CollectionListOptions, ProductListOptions } from '~/generated/graphql';

export function getSitemap(
  request: Request,
  collectionOptions?: CollectionListOptions,
  productOptions?: ProductListOptions,
) {
  return sdk
    .sitemap({ collectionOptions, productOptions }, { request })
    .then((result) => ({
      collections: result.collections?.items,
      products: result.products?.items,
    }));
}

gql`
  query sitemap($collectionOptions: CollectionListOptions, $productOptions: ProductListOptions) {
    collections(options: $collectionOptions) {
      items {
        slug
        updatedAt
      }
    }
    products(options: $productOptions) {
      items {
        slug
        updatedAt
      }
    }
  }
`;

3) Execute the query
import { getSitemap } from '~/providers/sitemap/sitemap';
const sitemapData = await getSitemap(request);

**Expected behavior**
Its simple query. Harden plugin should detect low complexity. But generates complexity 4626 

**Environment (please complete the following information):**
 - @vendure/core version:
     "@vendure/core": "^3.0.5",
    "@vendure/harden-plugin": "^3.0.5",
 - Nodejs version: v18.19.1
 - Database (mysql/postgres etc): postgresql 16

**Comment by oidt** [comment]
With the option logComplexityScore on true you can get the exact reason for that score.
Getting all the collections and all the products can be pretty intense so it looks like a simple query but can give large problems on large stores.

**Comment by michaelbromley** [comment]
Hi, you are probably running into this 
![Screenshot_20241119_203648](https://github.com/user-attachments/assets/80caf99d-0728-48d3-bf8a-381364008aaf)

Try adding a "take" input value to the list options and see if that helps.

**Comment by Huararanga** [comment]
That worked, thanks. I didn't get immediately, that I can use this. Maybe the docs could be more straightforward:

... Use { take: 123 } list options to limit size of output and complexity score consequently.

**Comment by martijnvdbrug** [comment]
Closing this, as the config mentioned above solves the issue :)
