### ISSUE TITLE
[FEATURE REQUEST] Add e2e test

### ISSUE THREAD

**Issue by anon-pradip** [vendure-ecommerce/vendure#3215]
**Is your feature request related to a problem? Please describe.**
The repository currently lacks any end-to-end (e2e) tests. I recommend adding e2e tests to the repository to ensure code robustness.

**Describe the solution you'd like**
I propose adding e2e tests to the repository utilizing Playwright and Cucumber. These tools offer a robust framework for Behavior-Driven Development (BDD) testing, allowing us to define test scenarios in plain language and automate interactions with the application.

**Describe alternatives you've considered**
While there are other e2e testing frameworks available, such as Selenium or TestCafe, Playwright offers several advantages, including cross-browser support and improved speed and reliability. Cucumber provides a structured approach to BDD testing, enhancing readability and collaboration among team members.

**Additional context**
Adding e2e tests will significantly enhance the quality of the codebase by identifying potential issues early in the development cycle. It will also increase confidence in code changes and facilitate smoother deployments.

**Comment by michaelbromley** [comment]
I think he might be referring to e2e tests for the Admin UI? That is certainly something we are missing currently.

However, this issue does not relate to a concrete feature or bug, so I'm going to close for now.
