### ISSUE TITLE
currencyCode in the request query parameter is ignored

### ISSUE THREAD

**Issue by mito4ek** [vendure-ecommerce/vendure#3232]
**Describe the bug**
I'm trying to fetch the data with currencyCode in the URL but have no success, only default currency is returned

It is stated in the documentation that: The default strategy is to return the price in the currency of the current session request context, which is determined firstly by any **?currencyCode=XXX** query parameter on the request, and secondly by the defaultCurrencyCode of the Channel.

**To Reproduce**
1. Configure multiple currencies in the channel
2. Add prices on the product variant in different currencies
3. Open postman or any other HTTP client and execute the query

```
http://localhost:3000/shop-api?languageCode=en&currencyCode=EUR
query Search {
    search(input: { collectionId: "12" }) {
        totalItems
        items {
            productName
            price {
                ... on PriceRange {
                    min
                    max
                }
                ... on SinglePrice {
                    value
                }
            }
            currencyCode
            priceWithTax {
                ... on PriceRange {
                    min
                    max
                }
                ... on SinglePrice {
                    value
                }
            }
        }
    }
}
```

Result
`{
    "data": {
        "search": {
            "totalItems": 1,
            "items": [
                {
                    "productName": "standart test product 1",
                    "price": {
                        "value": 2500
                    },
                    "currencyCode": "USD",
                    "priceWithTax": {
                        "value": 2500
                    }
                }
            ]
        }
    }
}`

**Expected behavior**
to get the currencyCode in EUR and price configured in EUR in the admin panel

 - @vendure/core version: 3.0.5
 - nodejs - 20.16
 - postgres 17

**Comment by oidt** [comment]
It is for the search: https://github.com/vendure-ecommerce/vendure/issues/2280

**Comment by michaelbromley** [comment]
Closing in favour of #2280
