### ISSUE TITLE
Occasional Port Conflicts in CI tests

### ISSUE THREAD

**Issue by toBeOfUse** [vendure-ecommerce/vendure#3247]
**Describe the bug**

Tests in CI in Vendure will occasionally fail due to port conflicts:

![image](https://github.com/user-attachments/assets/a8ce4ab7-2ffd-445b-98f3-38fa0e169fb5)

This makes it harder to detect actual errors in CI that might be caused by one particular Node.js version or one particular database being used.

As discussed on Discord, this is probably due to port assignment process, in which a temporary file called `ports.json` is created to store which ports are already in use. If two test suites read this file at the same time, they'll both come up with the same "next available port", and will both try to claim it.

**To Reproduce**
Open a PR and look at the automatic CI tests. Some of them will fail with `EADDRINUSE`.

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 3.0.6
 - Nodejs version: 18.x, 20.x, 22.x
 - Database (mysql/postgres etc): All

**Comment by toBeOfUse** [comment]
My first attempt to fix this failed. I used the VITEST_WORKER_ID environment variable to calculate a unique port number for each test suite that Vitest was running. However, unfortunately, in the Vendure monorepo, lerna runs multiple Vitest processes at once, and VITEST_WORKER_ID is only unique \*within* each Vitest process. The approach could still be used, but it would require restructuring the e2e command so that Vitest is aware of each ["workspace"](https://vitest.dev/guide/workspace) within the project and runs the test suites in parallel itself.

**Comment by michaelbromley** [comment]
Thanks for spending some time on this. I find it really annoying but didn't get a chance to work on it myself yet.

If course the most simple and foolproof method would be to manually assign a different port to each e2e test suite.

But avoiding that if possible would be good.

Maybe we could do something like this:

1. When running the test suite, we get the file name of the test suite
2. We get the contents of the e2e dir ordered by name and determine the current test's index in the array of files.
3. We use that index to add to the base port number.

This would give us a deterministic port value that should never conflict, and can be done synchronous using sync fs operations.
