### ISSUE TITLE
Currency not chaning in admin ui

### ISSUE THREAD

**Issue by ramirezsebas** [vendure-ecommerce/vendure#3257]
**Describe the bug**
When you try to change the currency, it seems like the state isn't being updated.

**To Reproduce**
1. Go to Home
2. Click on SuperAdmin dropdown
3. Click on the current language and see modal
4. Change the currency and click save
5. See currency not changed in metrics

**Expected behavior**
The metrics and everything else should be in the saved currency

**Environment (please complete the following information):**
 - @vendure/core version: 3.0.8
 - Nodejs version: v20.17.0
 - Database (mysql/postgres etc): sqlite

**Additional context**

<img width="1512" alt="Screenshot 2024-12-03 at 9 00 06 PM" src="https://github.com/user-attachments/assets/b6872b22-d92a-447b-8f30-6bcd4f07abd4">

<img width="864" alt="Screenshot 2024-12-03 at 9 00 28 PM" src="https://github.com/user-attachments/assets/fd7a74dd-ef17-48a2-a95e-e3316b778832">

**Comment by michaelbromley** [comment]
Hi,

This dialog is not there for changing the currency of your actual products. It is there to set the display language of the Admin UI app. The reason there is a currency select there is to provide a preview of how each specific currency will be rendered given the selected display language and locale.

The actual currency of the products is set in the channel settings: 
![image](https://github.com/user-attachments/assets/dea32856-9706-45d3-add8-570a8293cbae)
