### ISSUE TITLE
Can vendure support 1 million products?

### ISSUE THREAD

**Issue by chillpilllike** [vendure-ecommerce/vendure#3271]
Hello Team, I have a project that involves migrating about 900,000 products. Can venture support it without backend and frontend lags?

**Comment by Anddrrew** [comment]
Hey. It might be better to ask on the Vendure Discord. It has a more active community, and someone there might share their experience.

https://discord.com/invite/4u2aSCzDDX

**Comment by michaelbromley** [comment]
I know of one project that is operating at around that range, plus they have many translations for each variant, giving (at last count I heard) about 27 million individual language variants. For sure they have to solve certain challenges that come with that scale, but that would be the case for _any_ system.
