### ISSUE TITLE
globalSettings should not require authentications

### ISSUE THREAD

**Issue by mschipperheyn** [vendure-ecommerce/vendure#3273]
**Is your feature request related to a problem? Please describe.**
In multi vendor scenarios, and I imagine others as well, you might want to configure certain client side functionalities based on a configuration that you want to manage in the UI, ie not `.env`. The `globalSettings` is basically the ideal query for that but it requires authentication. I'm not entirely sure why that is the case.

**Describe the solution you'd like**
We need some kind of `serverSettings` style query that allows us to load customFields through a query that doesn't require authentication 

**Describe alternatives you've considered**
I've considered offering this a plugin for htis. But this imho is really a basic concern that Vendure should offer.

**Comment by michaelbromley** [comment]
The GlobalSettings type includes potentially sensitive information that we don't want to expose publicly, such as the full custom fields configuration of your server (which in turn provides strong clues as to which plugins are active), as well as all permissions, order process info etc.

The recommendation here is to create a custom query exposing the specific information needed by your client app.
