### ISSUE TITLE
TypeError: Converting circular structure to JSON when sending emails

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#3277]
**Describe the bug**
When attempting to send certain emails in v3.1.0, a circular JSON error is thrown by the EmailPlugin on the server, preventing the email from getting sent.

**To Reproduce**
1. With a standard installation
2. Go through a regular checkout flow and complete the order
3. When the order confirmation email is triggered, you will see the following error:

```
[server] error 16/12/24, 12:01 - [EmailPlugin] Converting circular structure to JSON
[server] TypeError: Converting circular structure to JSON
[server]     --> starting at object with constructor 'Object'
[server]     |     property 'sessionCacheStrategy' -> object with constructor 'DefaultSessionCacheStrategy'
[server]     |     property 'cacheService' -> object with constructor 'CacheService'
[server]     |     ...
[server]     |     property 'activeConfig' -> object with constructor 'Object'
[server]     --- property 'authOptions' closes the circle
[server]     at JSON.stringify (<anonymous>)
[server]     at Job.asJSON (C:\Development\vendure\vendure\node_modules\bullmq\src\classes\job.ts:446:18)
[server]     at Job.addJob (C:\Development\vendure\vendure\node_modules\bullmq\src\classes\job.ts:1175:26)
[server]     at Function.create (C:\Development\vendure\vendure\node_modules\bullmq\src\classes\job.ts:227:24)
[server]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[server]     at async Queue.add (C:\Development\vendure\vendure\node_modules\bullmq\src\classes\queue.ts:209:19)
[server]     at async BullMQJobQueueStrategy.add (C:\Development\vendure\vendure\packages\job-queue-plugin\src\bullmq\bullmq-job-queue-strategy.ts:162:25)
[server]     at async JobQueue.add (C:\Development\vendure\vendure\packages\core\src\job-queue\job-queue.ts:102:30)
[server]     at async EmailPlugin.handleEvent (C:\Development\vendure\vendure\packages\email-plugin\src\plugin.ts:426:17)
```

**Expected behavior**
No error and the email gets sent

**Environment (please complete the following information):**
 - @vendure/core version: 3.1.0
 - Nodejs version: any
 - Database (mysql/postgres etc): any

**Additional context**
Discussion on Discord: https://discord.com/channels/1100672177260478564/1316447090142085222/1316447090142085222

**Comment by Clemens05** [comment]
I had the same error. A quick fix is to removed the `allCheckers` property from `event.data.shippingLines` in `setTemplateVars` like this:

```ts
const shippingLines = event.data.shippingLines.map(
  (shippingLine) => ({
    ...shippingLine,
    shippingMethod: {
      ...shippingLine.shippingMethod,
      allCheckers: undefined,
    },
  })
);

return {
  order: { ...event.order, shippingLines: shippingLines },
  shippingLines: shippingLines,
  // ...
};
```

Maybe that helps to identify the root cause of the error.

**Comment by michaelbromley** [comment]
Yes - good detective work. The root cause is indeed the shipping method serialization. I'm adding a suite of tests on entity serialization that will address this and catch any similar regressions in the future.
