### ISSUE TITLE
Add slug to Collection entity

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#335]
**Is your feature request related to a problem? Please describe.**
Currently it is only possible to perform a lookup on a Collection by ID. This means that the ID must somehow be encoded in the URL to a particular collection in the storefront, leading to URLs like `http://localhost:4000/catalog/category/4-watercolour-brushes` where the ID `4` is shoved into the URL

**Describe the solution you'd like**
We should support slugs like we do with Products, and provide a way to perform a lookup of collection by slug.

Also look into what would be involved in allowing the `search` query to accept collection slugs as well as IDs to filter on. Otherwise the storefront code becomes more complex for the typical use-case of displaying collection contents via the search query.

**Comment by jonyw4** [comment]
This is an important feature, I look forward for this. 🤩
