### ISSUE TITLE
can't login in admin dashboard

### ISSUE THREAD

**Issue by sambhav2612** [vendure-ecommerce/vendure#338]
**Describe the bug**
We recently deployed Vendure to one of our servers and we can't log in to it anyhow. See attached screenshot for what it says. This is the first time we are using this for any CMS.

![Screenshot from 2020-05-12 12-59-41](https://user-images.githubusercontent.com/19583619/81652120-dd574500-9450-11ea-9dfb-4b448b2413b4.png)

**To Reproduce**
1. Go to http://api.fab-arabian.qa2.xencov.net/admin
2. Enter default login params and click on login
3. See the errors in the network window

**Expected behavior**
It should log in and open the dashboard.

**Environment (please complete the following information):**
 - @vendure/core version: 0.11.1
 - Nodejs version: LTS (12+)
 - Database (mysql/postgres etc): MySQL 5.7

**Additional context**
NaN

**Comment by samundra** [comment]
@sambhav2612 Hi it looks like your server conifg is incorrect. It's returning `localhost:3999` which is not correct.

Look at the screenshot below.

![Screen Shot 2020-05-12 at 15 09 09](https://user-images.githubusercontent.com/760855/81658238-c7eb1680-9462-11ea-992a-cac3becac819.png)

**Comment by sambhav2612** [comment]
> @sambhav2612 Hi it looks like your server conifg is incorrect. It's returning `localhost:3999` which is not correct.
> 
> Look at the screenshot below.
> 
> ![Screen Shot 2020-05-12 at 15 09 09](https://user-images.githubusercontent.com/760855/81658238-c7eb1680-9462-11ea-992a-cac3becac819.png)

How do I point it to my server IP then? I tried writing public IP of server instead of `localhost` in hostname fields, but that didn't work.

**Comment by sambhav2612** [comment]
this is my vendure config:

```ts
import {
    examplePaymentHandler,
    DefaultJobQueuePlugin,
    DefaultSearchPlugin,
    VendureConfig,
} from '@vendure/core';
import {defaultEmailHandlers, EmailPlugin} from '@vendure/email-plugin';
import {AssetServerPlugin} from '@vendure/asset-server-plugin';
import {AdminUiPlugin} from '@vendure/admin-ui-plugin';
import path from 'path';

export const config: VendureConfig = {
    authOptions: {
        sessionSecret: 'hs7exx1ecd8',
    },
    port: 3999,
    hostname: 'localhost',
    adminApiPath: 'admin-api',
    shopApiPath: 'shop-api',
    dbConnectionOptions: {
        type: 'mysql',
        synchronize: true, // turn this off for production
        logging: false,
        database: 'fab_arabian',
        host: 'localhost',
        port: 3306,
        username: 'root',
        password: '',
        migrations: [path.join(__dirname, '../migrations/*.ts')],
    },
    paymentOptions: {
        paymentMethodHandlers: [examplePaymentHandler],
    },
    customFields: {},
    plugins: [
        AssetServerPlugin.init({
            route: 'assets',
            assetUploadDir: path.join(__dirname, '../static/assets'),
            port: 3001,
            hostname: 'localhost'
        }),
        DefaultJobQueuePlugin,
        DefaultSearchPlugin,
        EmailPlugin.init({
            devMode: true,
            outputPath: path.join(__dirname, '../static/email/test-emails'),
            mailboxPort: 3003,
            handlers: defaultEmailHandlers,
            templatePath: path.join(__dirname, '../static/email/templates'),
            globalTemplateVars: {
                // The following variables will change depending on your storefront implementation
                fromAddress: '"example" <noreply@example.com>',
                verifyEmailAddressUrl: 'http://localhost:8080/verify',
                passwordResetUrl: 'http://localhost:8080/password-reset',
                changeEmailAddressUrl: 'http://localhost:8080/verify-email-address-change'
            },
        }),
        AdminUiPlugin.init({
            hostname: 'localhost', port: 3002, adminUiConfig: {
                apiHost: 'http://localhost',
                apiPort: 3999
            }
        }),
    ],
};
```

**Comment by michaelbromley** [comment]
This part is a problem when deploying to your remote server:

```ts
 AdminUiPlugin.init({
            hostname: 'localhost', port: 3002, adminUiConfig: {
                apiHost: 'http://localhost',
                apiPort: 3999
            }
        }),
```

Here you are telling the Admin UI app that the Admin API is at `localhost:3999`. Change it to the remote server hostname, and port 80 since you are not using https.
