### ISSUE TITLE
[docs] Duplicate TOC with Hugo 0.7

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#339]
A user on Slack reported that when compiling the docs using Hugo 0.7, the table of contents were duplicated. We currently use 0.53 and when he downgraded, the problem was gone.

Need to investigate why it breaks on the latest version, and then also include a note in the readme of the current compatible Hugo version.

**Comment by samundra** [comment]
I also have the same issue in hugo 0.7. I have attached screenshot.

Also it looks like `webpack` was needed before build but was not mentioned on hugo dev dependency. So I had to install it manually before running `docs:build`

> `yarn add -D webpack` before running `docs:build`

![Screen Shot 2020-05-13 at 18 41 41](https://user-images.githubusercontent.com/760855/81809649-e0832b80-954b-11ea-8852-eff83a18d1d9.png)
