### ISSUE TITLE
No product in Product tab

### ISSUE THREAD

**Issue by Znerf** [vendure-ecommerce/vendure#342]
**Describe the bug**
Admi-UI is not showing any products in product tab but the collection shows all the products can be edited. Adding product won't add the products product tab but the products are saved in the collection.
 

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 0.12.1
 - Nodejs version: v12.10.0
 - Database (mysql/postgres etc): mysql
![Screenshot from 2020-05-16 16-57-48](https://user-images.githubusercontent.com/4151245/82118338-74e0ce80-9796-11ea-9e25-2e6b862fb2e3.png)

![Screenshot from 2020-05-16 16-57-31](https://user-images.githubusercontent.com/4151245/82118342-7e6a3680-9796-11ea-8b66-1c86ae8d332c.png)

**Comment by Znerf** [comment]
I think there is an error in MySQL integration. I changed the database to PostgreSQL and it worked.

**Comment by michaelbromley** [comment]
Yes, this looks like a manifestation of the MySQL issue described in #331
