### ISSUE TITLE
unable to push to git

### ISSUE THREAD

**Issue by Znerf** [vendure-ecommerce/vendure#344]
**Describe the bug**
The code is getting pushed at my remote repository

**To Reproduce**
git push origin develop1

**Expected behavior**
It shows error as shown below

**Environment (please complete the following information):**
 - @vendure/core version:
 - Nodejs version:6.14.4
 - Database (mysql/postgres etc): postgres

**Additional context**
 PASS e2e/order.e2e-spec.ts (30.845s)
@vendure/core: PASS e2e/collection.e2e-spec.ts (16.374s)
@vendure/core: PASS e2e/product.e2e-spec.ts (13.724s)
@vendure/core: PASS e2e/shop-order.e2e-spec.ts (18.804s)
@vendure/core: PASS e2e/default-search-plugin.e2e-spec.ts (17.464s)
@vendure/core: PASS e2e/shop-auth.e2e-spec.ts (27.423s)
@vendure/core: PASS e2e/order-promotion.e2e-spec.ts (14.456s)
@vendure/core: PASS e2e/customer.e2e-spec.ts (11.361s)
@vendure/core: FAIL e2e/custom-fields.e2e-spec.ts (9.947s)
@vendure/core:   ● Custom fields › validation › invalid datetime
@vendure/core:     Failed: "Should have thrown"
@vendure/core:        6 |         try {
@vendure/core:        7 |             await operation();
@vendure/core:     >  8 |             fail('Should have thrown');
@vendure/core:          |             ^
@vendure/core:        9 |         } catch (err) {
@vendure/core:       10 |             expect(err.message).toEqual(expect.stringContaining(message));
@vendure/core:       11 |         }
@vendure/core:       at Env.fail (../../../node_modules/jest-jasmine2/build/jasmine/Env.js:726:61)
@vendure/core:       at Object.<anonymous> (utils/assert-throws-with-message.ts:8:13)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core: PASS e2e/channel.e2e-spec.ts (15.823s)
@vendure/core: PASS e2e/shop-catalog.e2e-spec.ts (11.068s)
@vendure/core: PASS e2e/facet.e2e-spec.ts (11.431s)
@vendure/core: FAIL e2e/role.e2e-spec.ts (8.947s)
@vendure/core:   ● Role resolver › roles
@vendure/core:     You are not currently authorized to perform this action
@vendure/core:       84 |         } else {
@vendure/core:       85 |             const errorResult = typeof result === 'string' ? { error: result } : result;
@vendure/core:     > 86 |             throw new ClientError(
@vendure/core:          |                   ^
@vendure/core:       87 |                 { ...errorResult, status: response.status },
@vendure/core:       88 |                 { query: print(query), variables },
@vendure/core:       89 |             );
@vendure/core:       at SimpleGraphQLClient.query (../../testing/src/simple-graphql-client.ts:86:19)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:51:24)
@vendure/core:   ● Role resolver › createRole with no permissions includes Authenticated
@vendure/core:     You are not currently authorized to perform this action
@vendure/core:       84 |         } else {
@vendure/core:       85 |             const errorResult = typeof result === 'string' ? { error: result } : result;
@vendure/core:     > 86 |             throw new ClientError(
@vendure/core:          |                   ^
@vendure/core:       87 |                 { ...errorResult, status: response.status },
@vendure/core:       88 |                 { query: print(query), variables },
@vendure/core:       89 |             );
@vendure/core:       at SimpleGraphQLClient.query (../../testing/src/simple-graphql-client.ts:86:19)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:72:32)
@vendure/core:   ● Role resolver › createRole deduplicates permissions
@vendure/core:     You are not currently authorized to perform this action
@vendure/core:       84 |         } else {
@vendure/core:       85 |             const errorResult = typeof result === 'string' ? { error: result } : result;
@vendure/core:     > 86 |             throw new ClientError(
@vendure/core:          |                   ^
@vendure/core:       87 |                 { ...errorResult, status: response.status },
@vendure/core:       88 |                 { query: print(query), variables },
@vendure/core:       89 |             );
@vendure/core:       at SimpleGraphQLClient.query (../../testing/src/simple-graphql-client.ts:86:19)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:92:32)
@vendure/core:   ● Role resolver › createRole with permissions
@vendure/core:     You are not currently authorized to perform this action
@vendure/core:       84 |         } else {
@vendure/core:       85 |             const errorResult = typeof result === 'string' ? { error: result } : result;
@vendure/core:     > 86 |             throw new ClientError(
@vendure/core:          |                   ^
@vendure/core:       87 |                 { ...errorResult, status: response.status },
@vendure/core:       88 |                 { query: print(query), variables },
@vendure/core:       89 |             );
@vendure/core:       at SimpleGraphQLClient.query (../../testing/src/simple-graphql-client.ts:86:19)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:112:24)
@vendure/core:   ● Role resolver › role
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       136 |     it('role', async () => {
@vendure/core:       137 |         const result = await adminClient.query<GetRole.Query, GetRole.Variables>(GET_ROLE, {
@vendure/core:     > 138 |             id: createdRole.id,
@vendure/core:           |                             ^
@vendure/core:       139 |         });
@vendure/core:       140 |         expect(result.role).toEqual(createdRole);
@vendure/core:       141 |     });
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:138:29)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › updateRole
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       144 |         const result = await adminClient.query<UpdateRole.Mutation, UpdateRole.Variables>(UPDATE_ROLE, {
@vendure/core:       145 |             input: {
@vendure/core:     > 146 |                 id: createdRole.id,
@vendure/core:           |                                 ^
@vendure/core:       147 |                 code: 'test-modified',
@vendure/core:       148 |                 description: 'test role modified',
@vendure/core:       149 |                 permissions: [Permission.ReadCustomer, Permission.UpdateCustomer, Permission.DeleteCustomer],
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:146:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › updateRole works with partial input
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       167 |         const result = await adminClient.query<UpdateRole.Mutation, UpdateRole.Variables>(UPDATE_ROLE, {
@vendure/core:       168 |             input: {
@vendure/core:     > 169 |                 id: createdRole.id,
@vendure/core:           |                                 ^
@vendure/core:       170 |                 code: 'test-modified-again',
@vendure/core:       171 |             },
@vendure/core:       172 |         });
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:169:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › updateRole deduplicates permissions
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       185 |         const result = await adminClient.query<UpdateRole.Mutation, UpdateRole.Variables>(UPDATE_ROLE, {
@vendure/core:       186 |             input: {
@vendure/core:     > 187 |                 id: createdRole.id,
@vendure/core:           |                                 ^
@vendure/core:       188 |                 permissions: [
@vendure/core:       189 |                     Permission.Authenticated,
@vendure/core:       190 |                     Permission.Authenticated,
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:187:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › updateRole is not allowed for SuperAdmin role
@vendure/core:     expect(received).toEqual(expected) // deep equality
@vendure/core:     Expected: StringContaining "The role '__super_admin_role__' cannot be modified"
@vendure/core:     Received: "Cannot read property 'find' of undefined"
@vendure/core:        8 |             fail('Should have thrown');
@vendure/core:        9 |         } catch (err) {
@vendure/core:     > 10 |             expect(err.message).toEqual(expect.stringContaining(message));
@vendure/core:          |                                 ^
@vendure/core:       11 |         }
@vendure/core:       12 |     };
@vendure/core:       13 | }
@vendure/core:       at Object.<anonymous> (utils/assert-throws-with-message.ts:10:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › updateRole is not allowed for Customer role
@vendure/core:     expect(received).toEqual(expected) // deep equality
@vendure/core:     Expected: StringContaining "The role '__customer_role__' cannot be modified"
@vendure/core:     Received: "Cannot read property 'find' of undefined"
@vendure/core:        8 |             fail('Should have thrown');
@vendure/core:        9 |         } catch (err) {
@vendure/core:     > 10 |             expect(err.message).toEqual(expect.stringContaining(message));
@vendure/core:          |                                 ^
@vendure/core:       11 |         }
@vendure/core:       12 |     };
@vendure/core:       13 | }
@vendure/core:       at Object.<anonymous> (utils/assert-throws-with-message.ts:10:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › deleteRole is not allowed for Customer role
@vendure/core:     expect(received).toEqual(expected) // deep equality
@vendure/core:     Expected: StringContaining "The role '__customer_role__' cannot be deleted"
@vendure/core:     Received: "Cannot read property 'find' of undefined"
@vendure/core:        8 |             fail('Should have thrown');
@vendure/core:        9 |         } catch (err) {
@vendure/core:     > 10 |             expect(err.message).toEqual(expect.stringContaining(message));
@vendure/core:          |                                 ^
@vendure/core:       11 |         }
@vendure/core:       12 |     };
@vendure/core:       13 | }
@vendure/core:       at Object.<anonymous> (utils/assert-throws-with-message.ts:10:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › deleteRole is not allowed for SuperAdmin role
@vendure/core:     expect(received).toEqual(expected) // deep equality
@vendure/core:     Expected: StringContaining "The role '__super_admin_role__' cannot be deleted"
@vendure/core:     Received: "Cannot read property 'find' of undefined"
@vendure/core:        8 |             fail('Should have thrown');
@vendure/core:        9 |         } catch (err) {
@vendure/core:     > 10 |             expect(err.message).toEqual(expect.stringContaining(message));
@vendure/core:          |                                 ^
@vendure/core:       11 |         }
@vendure/core:       12 |     };
@vendure/core:       13 | }
@vendure/core:       at Object.<anonymous> (utils/assert-throws-with-message.ts:10:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › deleteRole deletes a role
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       268 |             DELETE_ROLE,
@vendure/core:       269 |             {
@vendure/core:     > 270 |                 id: createdRole.id,
@vendure/core:           |                                 ^
@vendure/core:       271 |             },
@vendure/core:       272 |         );
@vendure/core:       273 | 
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:270:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › multi-channel › createRole with specified channel
@vendure/core:     You are not currently authorized to perform this action
@vendure/core:       84 |         } else {
@vendure/core:       85 |             const errorResult = typeof result === 'string' ? { error: result } : result;
@vendure/core:     > 86 |             throw new ClientError(
@vendure/core:          |                   ^
@vendure/core:       87 |                 { ...errorResult, status: response.status },
@vendure/core:       88 |                 { query: print(query), variables },
@vendure/core:       89 |             );
@vendure/core:       at SimpleGraphQLClient.query (../../testing/src/simple-graphql-client.ts:86:19)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:287:39)
@vendure/core:   ● Role resolver › multi-channel › createRole with specified channel
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       309 |                     description: 'multi channel test role',
@vendure/core:       310 |                     permissions: [Permission.ReadCustomer],
@vendure/core:     > 311 |                     channelIds: [secondChannel.id],
@vendure/core:           |                                                ^
@vendure/core:       312 |                 },
@vendure/core:       313 |             });
@vendure/core:       314 | 
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:311:48)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › multi-channel › updateRole with specified channel
@vendure/core:     You are not currently authorized to perform this action
@vendure/core:       84 |         } else {
@vendure/core:       85 |             const errorResult = typeof result === 'string' ? { error: result } : result;
@vendure/core:     > 86 |             throw new ClientError(
@vendure/core:          |                   ^
@vendure/core:       87 |                 { ...errorResult, status: response.status },
@vendure/core:       88 |                 { query: print(query), variables },
@vendure/core:       89 |             );
@vendure/core:       at SimpleGraphQLClient.query (../../testing/src/simple-graphql-client.ts:86:19)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:287:39)
@vendure/core:   ● Role resolver › multi-channel › updateRole with specified channel
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       334 |                 {
@vendure/core:       335 |                     input: {
@vendure/core:     > 336 |                         id: multiChannelRole.id,
@vendure/core:           |                                              ^
@vendure/core:       337 |                         channelIds: ['T_1', 'T_2'],
@vendure/core:       338 |                     },
@vendure/core:       339 |                 },
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:336:46)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core: PASS e2e/shipping-method.e2e-spec.ts (9.455s)
@vendure/core: PASS e2e/promotion.e2e-spec.ts (8.773s)
@vendure/core: PASS e2e/asset.e2e-spec.ts (10.331s)
@vendure/core: PASS e2e/stock-control.e2e-spec.ts (10.26s)
@vendure/core: PASS e2e/import.e2e-spec.ts (11.615s)
@vendure/core: PASS e2e/zone.e2e-spec.ts (9.094s)
@vendure/core: PASS e2e/auth.e2e-spec.ts (14.173s)
@vendure/core: PASS e2e/shop-customer.e2e-spec.ts (11.014s)
@vendure/core: PASS e2e/plugin.e2e-spec.ts (11.367s)
@vendure/core: PASS e2e/product-option.e2e-spec.ts (8.382s)
@vendure/core: PASS e2e/entity-id-strategy.e2e-spec.ts (10.741s)
@vendure/core: PASS e2e/localization.e2e-spec.ts (9.457s)
@vendure/core: PASS e2e/administrator.e2e-spec.ts (11.522s)
@vendure/core: PASS e2e/tax-category.e2e-spec.ts (8.641s)
@vendure/core: PASS e2e/country.e2e-spec.ts (10.482s)
@vendure/core: PASS e2e/tax-rate.e2e-spec.ts (9.165s)
@vendure/core: PASS e2e/list-query-builder.e2e-spec.ts (7.914s)
@vendure/core: PASS e2e/job-queue.e2e-spec.ts (7.657s)
@vendure/core: PASS e2e/apollo-server-plugin.e2e-spec.ts (7.18s)
@vendure/core: PASS e2e/lifecycle.e2e-spec.ts (10.76s)
@vendure/core: PASS e2e/entity-uuid-strategy.e2e-spec.ts (11.686s)
@vendure/core: Summary of all failing tests
@vendure/core: FAIL ./custom-fields.e2e-spec.ts (9.947s)
@vendure/core:   ● Custom fields › validation › invalid datetime
@vendure/core:     Failed: "Should have thrown"
@vendure/core:        6 |         try {
@vendure/core:        7 |             await operation();
@vendure/core:     >  8 |             fail('Should have thrown');
@vendure/core:          |             ^
@vendure/core:        9 |         } catch (err) {
@vendure/core: Database engine: sqljs
@vendure/core:       10 |             expect(err.message).toEqual(expect.stringContaining(message));
@vendure/core:       11 |         }
@vendure/core:       at Env.fail (../../../node_modules/jest-jasmine2/build/jasmine/Env.js:726:61)
@vendure/core:       at Object.<anonymous> (utils/assert-throws-with-message.ts:8:13)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core: FAIL ./role.e2e-spec.ts (8.947s)
@vendure/core:   ● Role resolver › roles
@vendure/core:     You are not currently authorized to perform this action
@vendure/core:       84 |         } else {
@vendure/core:       85 |             const errorResult = typeof result === 'string' ? { error: result } : result;
@vendure/core:     > 86 |             throw new ClientError(
@vendure/core:          |                   ^
@vendure/core:       87 |                 { ...errorResult, status: response.status },
@vendure/core:       88 |                 { query: print(query), variables },
@vendure/core:       89 |             );
@vendure/core:       at SimpleGraphQLClient.query (../../testing/src/simple-graphql-client.ts:86:19)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:51:24)
@vendure/core:   ● Role resolver › createRole with no permissions includes Authenticated
@vendure/core:     You are not currently authorized to perform this action
@vendure/core:       84 |         } else {
@vendure/core:       85 |             const errorResult = typeof result === 'string' ? { error: result } : result;
@vendure/core:     > 86 |             throw new ClientError(
@vendure/core:          |                   ^
@vendure/core:       87 |                 { ...errorResult, status: response.status },
@vendure/core:       88 |                 { query: print(query), variables },
@vendure/core:       89 |             );
@vendure/core:       at SimpleGraphQLClient.query (../../testing/src/simple-graphql-client.ts:86:19)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:72:32)
@vendure/core:   ● Role resolver › createRole deduplicates permissions
@vendure/core:     You are not currently authorized to perform this action
@vendure/core:       84 |         } else {
@vendure/core:       85 |             const errorResult = typeof result === 'string' ? { error: result } : result;
@vendure/core:     > 86 |             throw new ClientError(
@vendure/core:          |                   ^
@vendure/core:       87 |                 { ...errorResult, status: response.status },
@vendure/core:       88 |                 { query: print(query), variables },
@vendure/core:       89 |             );
@vendure/core:       at SimpleGraphQLClient.query (../../testing/src/simple-graphql-client.ts:86:19)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:92:32)
@vendure/core:   ● Role resolver › createRole with permissions
@vendure/core:     You are not currently authorized to perform this action
@vendure/core:       84 |         } else {
@vendure/core:       85 |             const errorResult = typeof result === 'string' ? { error: result } : result;
@vendure/core:     > 86 |             throw new ClientError(
@vendure/core:          |                   ^
@vendure/core:       87 |                 { ...errorResult, status: response.status },
@vendure/core:       88 |                 { query: print(query), variables },
@vendure/core:       89 |             );
@vendure/core:       at SimpleGraphQLClient.query (../../testing/src/simple-graphql-client.ts:86:19)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:112:24)
@vendure/core:   ● Role resolver › role
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       136 |     it('role', async () => {
@vendure/core:       137 |         const result = await adminClient.query<GetRole.Query, GetRole.Variables>(GET_ROLE, {
@vendure/core:     > 138 |             id: createdRole.id,
@vendure/core:           |                             ^
@vendure/core:       139 |         });
@vendure/core:       140 |         expect(result.role).toEqual(createdRole);
@vendure/core:       141 |     });
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:138:29)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › updateRole
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       144 |         const result = await adminClient.query<UpdateRole.Mutation, UpdateRole.Variables>(UPDATE_ROLE, {
@vendure/core:       145 |             input: {
@vendure/core:     > 146 |                 id: createdRole.id,
@vendure/core:           |                                 ^
@vendure/core:       147 |                 code: 'test-modified',
@vendure/core:       148 |                 description: 'test role modified',
@vendure/core:       149 |                 permissions: [Permission.ReadCustomer, Permission.UpdateCustomer, Permission.DeleteCustomer],
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:146:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › updateRole works with partial input
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       167 |         const result = await adminClient.query<UpdateRole.Mutation, UpdateRole.Variables>(UPDATE_ROLE, {
@vendure/core:       168 |             input: {
@vendure/core:     > 169 |                 id: createdRole.id,
@vendure/core:           |                                 ^
@vendure/core:       170 |                 code: 'test-modified-again',
@vendure/core:       171 |             },
@vendure/core:       172 |         });
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:169:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › updateRole deduplicates permissions
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       185 |         const result = await adminClient.query<UpdateRole.Mutation, UpdateRole.Variables>(UPDATE_ROLE, {
@vendure/core:       186 |             input: {
@vendure/core:     > 187 |                 id: createdRole.id,
@vendure/core:           |                                 ^
@vendure/core:       188 |                 permissions: [
@vendure/core:       189 |                     Permission.Authenticated,
@vendure/core:       190 |                     Permission.Authenticated,
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:187:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › updateRole is not allowed for SuperAdmin role
@vendure/core:     expect(received).toEqual(expected) // deep equality
@vendure/core:     Expected: StringContaining "The role '__super_admin_role__' cannot be modified"
@vendure/core:     Received: "Cannot read property 'find' of undefined"
@vendure/core:        8 |             fail('Should have thrown');
@vendure/core:        9 |         } catch (err) {
@vendure/core:     > 10 |             expect(err.message).toEqual(expect.stringContaining(message));
@vendure/core:          |                                 ^
@vendure/core:       11 |         }
@vendure/core:       12 |     };
@vendure/core:       13 | }
@vendure/core:       at Object.<anonymous> (utils/assert-throws-with-message.ts:10:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › updateRole is not allowed for Customer role
@vendure/core:     expect(received).toEqual(expected) // deep equality
@vendure/core:     Expected: StringContaining "The role '__customer_role__' cannot be modified"
@vendure/core:     Received: "Cannot read property 'find' of undefined"
@vendure/core:        8 |             fail('Should have thrown');
@vendure/core:        9 |         } catch (err) {
@vendure/core:     > 10 |             expect(err.message).toEqual(expect.stringContaining(message));
@vendure/core:          |                                 ^
@vendure/core:       11 |         }
@vendure/core:       12 |     };
@vendure/core:       13 | }
@vendure/core:       at Object.<anonymous> (utils/assert-throws-with-message.ts:10:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › deleteRole is not allowed for Customer role
@vendure/core:     expect(received).toEqual(expected) // deep equality
@vendure/core:     Expected: StringContaining "The role '__customer_role__' cannot be deleted"
@vendure/core:     Received: "Cannot read property 'find' of undefined"
@vendure/core:        8 |             fail('Should have thrown');
@vendure/core:        9 |         } catch (err) {
@vendure/core:     > 10 |             expect(err.message).toEqual(expect.stringContaining(message));
@vendure/core:          |                                 ^
@vendure/core:       11 |         }
@vendure/core:       12 |     };
@vendure/core:       13 | }
@vendure/core:       at Object.<anonymous> (utils/assert-throws-with-message.ts:10:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › deleteRole is not allowed for SuperAdmin role
@vendure/core:     expect(received).toEqual(expected) // deep equality
@vendure/core:     Expected: StringContaining "The role '__super_admin_role__' cannot be deleted"
@vendure/core:     Received: "Cannot read property 'find' of undefined"
@vendure/core:        8 |             fail('Should have thrown');
@vendure/core:        9 |         } catch (err) {
@vendure/core:     > 10 |             expect(err.message).toEqual(expect.stringContaining(message));
@vendure/core:          |                                 ^
@vendure/core:       11 |         }
@vendure/core:       12 |     };
@vendure/core:       13 | }
@vendure/core:       at Object.<anonymous> (utils/assert-throws-with-message.ts:10:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › deleteRole deletes a role
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       268 |             DELETE_ROLE,
@vendure/core:       269 |             {
@vendure/core:     > 270 |                 id: createdRole.id,
@vendure/core:           |                                 ^
@vendure/core:       271 |             },
@vendure/core:       272 |         );
@vendure/core:       273 | 
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:270:33)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › multi-channel › createRole with specified channel
@vendure/core:     You are not currently authorized to perform this action
@vendure/core:       84 |         } else {
@vendure/core:       85 |             const errorResult = typeof result === 'string' ? { error: result } : result;
@vendure/core:     > 86 |             throw new ClientError(
@vendure/core:          |                   ^
@vendure/core:       87 |                 { ...errorResult, status: response.status },
@vendure/core:       88 |                 { query: print(query), variables },
@vendure/core:       89 |             );
@vendure/core:       at SimpleGraphQLClient.query (../../testing/src/simple-graphql-client.ts:86:19)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:287:39)
@vendure/core:   ● Role resolver › multi-channel › createRole with specified channel
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       309 |                     description: 'multi channel test role',
@vendure/core:       310 |                     permissions: [Permission.ReadCustomer],
@vendure/core:     > 311 |                     channelIds: [secondChannel.id],
@vendure/core:           |                                                ^
@vendure/core:       312 |                 },
@vendure/core:       313 |             });
@vendure/core:       314 | 
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:311:48)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:   ● Role resolver › multi-channel › updateRole with specified channel
@vendure/core:     You are not currently authorized to perform this action
@vendure/core:       84 |         } else {
@vendure/core:       85 |             const errorResult = typeof result === 'string' ? { error: result } : result;
@vendure/core:     > 86 |             throw new ClientError(
@vendure/core:          |                   ^
@vendure/core:       87 |                 { ...errorResult, status: response.status },
@vendure/core:       88 |                 { query: print(query), variables },
@vendure/core:       89 |             );
@vendure/core:       at SimpleGraphQLClient.query (../../testing/src/simple-graphql-client.ts:86:19)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:287:39)
@vendure/core:   ● Role resolver › multi-channel › updateRole with specified channel
@vendure/core:     TypeError: Cannot read property 'id' of undefined
@vendure/core:       334 |                 {
@vendure/core:       335 |                     input: {
@vendure/core:     > 336 |                         id: multiChannelRole.id,
@vendure/core:           |                                              ^
@vendure/core:       337 |                         channelIds: ['T_1', 'T_2'],
@vendure/core:       338 |                     },
@vendure/core:       339 |                 },
@vendure/core:       at Object.<anonymous> (role.e2e-spec.ts:336:46)
@vendure/core:           at runMicrotasks (<anonymous>)
@vendure/core: Test Suites: 2 failed, 32 passed, 34 total
@vendure/core: Tests:       16 failed, 3 skipped, 509 passed, 528 total
@vendure/core: Snapshots:   15 passed, 15 total
@vendure/core: Time:        417.789s
@vendure/core: Ran all test suites.
@vendure/core: error Command failed with exit code 1.
@vendure/core: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by michaelbromley** [comment]
Hi,
That means the end-to-end tests are failing. Did you make any changes to the code which may have resulted in the failure?

Also you wrote that you are using Node v6.14.4. Vendure only supports v10.13.0 and higher.

**Comment by Znerf** [comment]
Thank you for the reminding me to update my node package. Yeah it solved that particular issue but it still has a problem in email validation. 
 
S
@vendure/email-plugin: FAIL src/plugin.spec.ts (55.184s)
@vendure/email-plugin:   EmailPlugin
@vendure/email-plugin:     ✓ setting from, recipient, subject (609ms)
@vendure/email-plugin:     event filtering
@vendure/email-plugin:       ✓ single filter (309ms)
@vendure/email-plugin:       ✓ multiple filters (334ms)
@vendure/email-plugin:       ✓ with .loadData() after .filter() (359ms)
@vendure/email-plugin:     templateVars
@vendure/email-plugin:       ✓ interpolates subject (192ms)
@vendure/email-plugin:       ✓ interpolates body (176ms)
@vendure/email-plugin:       ✓ interpolates body with property from entity (182ms)
@vendure/email-plugin:       ✓ interpolates globalTemplateVars (180ms)
@vendure/email-plugin:       ✓ interpolates from (138ms)
@vendure/email-plugin:       ✓ globalTemplateVars available in setTemplateVars method (150ms)
@vendure/email-plugin:       ✓ setTemplateVars overrides globals (151ms)
@vendure/email-plugin:     handlebars helpers
@vendure/email-plugin:       ✓ formateDate (137ms)
@vendure/email-plugin:       ✓ formateMoney (139ms)
@vendure/email-plugin:     multiple configs
@vendure/email-plugin:       ✕ additional LanguageCode (243ms)
@vendure/email-plugin:     loadData
@vendure/email-plugin:       ✓ loads async data (145ms)
@vendure/email-plugin:       ✓ works when loadData is called after other setup (139ms)
@vendure/email-plugin:     orderConfirmationHandler
@vendure/email-plugin:       ✓ filters events with wrong order state (454ms)
@vendure/email-plugin:       ✓ sets the Order Customer emailAddress as recipient (141ms)
@vendure/email-plugin:       ✓ sets the subject (140ms)
@vendure/email-plugin:   ● EmailPlugin › multiple configs › additional LanguageCode
@vendure/email-plugin:     TypeError: Cannot read property '0' of undefined
@vendure/email-plugin:       342 |             eventBus.publish(new MockEvent(ctxDe, true));
@vendure/email-plugin:       343 |             await pause();
@vendure/email-plugin:     > 344 |             expect(onSend.mock.calls[1][0].subject).toBe('Servus, Test!');
@vendure/email-plugin:           |                                        ^
@vendure/email-plugin:       345 |             expect(onSend.mock.calls[1][0].body).toContain('German body.');
@vendure/email-plugin:       346 |         });
@vendure/email-plugin:       347 |     });
@vendure/email-plugin:       at Object.<anonymous> (src/plugin.spec.ts:344:40)
@vendure/email-plugin: Test Suites: 1 failed, 1 total
@vendure/email-plugin: Tests:       1 failed, 18 passed, 19 total
@vendure/email-plugin: Snapshots:   0 total
@vendure/email-plugin: Time:        55.285s
@vendure/email-plugin: Ran all test suites.
@vendure/email-plugin: error Command failed with exit code 1.
@vendure/email-plugin: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! Received non-zero exit code 1 during execution
lerna success run Ran npm script 'test' in 6 packages in 179.8s:
lerna success - @vendure/admin-ui
lerna success - @vendure/asset-server-plugin
lerna success - @vendure/common
lerna success - @vendure/core
lerna success - @vendure/elasticsearch-plugin
lerna success - @vendure/email-plugin
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by michaelbromley** [comment]
Hi,

Did you make any changes to the source code before trying to push? 

You can also skip the checks by using the git flag `--no-verify` when you push.

**Comment by Znerf** [comment]
I did not make any changes and --no-verify let me push it to the git but now I am more concerned about the bug rather than the fact that it is working.

**Comment by michaelbromley** [comment]
Since you did not make any changes to the code, then the "bug" may be due to your different environment.

What is your OS? Node version? Does it consistently fail when you run `yarn e2e` from the `/packages/email-plugin` directory?

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.
