### ISSUE TITLE
New added facet unavailable in products

### ISSUE THREAD

**Issue by z46h1** [vendure-ecommerce/vendure#347]
**Describe the bug**
I had to refresh page to have available new added facet on list of facets.

**To Reproduce**
1. Add new facet
2. Go to products
3. Try to add facet - there is no facet on list

**Expected behavior**
I should see facet on list when I added it to the facets without required refreshing page.

**Environment (please complete the following information):**
 - @vendure/core version: 0.12.1
 - Nodejs version: 12.16.3
 - Database (mysql/postgres etc): sqLite

**Comment by michaelbromley** [comment]
Thanks for the report. Will be fixed in the next release :)
