### ISSUE TITLE
[docs]: Order Cancellation [missing]

### ISSUE THREAD

**Issue by zifahm** [vendure-ecommerce/vendure#349]
I think order cancellation is missing in docs.
```
type Mutation {
  cancelOrderLines(input: CancelOrderLinesInput!): Order
}

input OrderLineInput {
    orderLineId: ID!
    quantity: Int!
}

input CancelOrderLinesInput {
  lines: [OrderLineInput!]!
  reason: String
}
```

**Comment by michaelbromley** [comment]
Hi,

Where did you come across that mutation `cancelOrderLines(input: CancelOrderLinesInput!): Order`?

It seems to be from a very old version of the API - it was replaced with `cancelOrder` almost 1 year ago in version 0.1.2-beta.6

**Comment by zifahm** [comment]
I couldn't find a cancel order mutation in the docs, so I went searching for one in the issue page and I found this. https://github.com/vendure-ecommerce/vendure/issues/120
Sorry I should have checked the source code before posting.

**Comment by zifahm** [comment]
Ohh I see now, Cancel order is under the Admin API. I was looking around the store API.
