### ISSUE TITLE
[Demo storefront] Got error while trying to create an account after completing order checkout

### ISSUE THREAD

**Issue by samundra** [vendure-ecommerce/vendure#351]
**Describe the bug**
I was playing with current vendure demo store front and got error when I clicked on create an account at the end of the checkout.

![Demo storefront error](https://user-images.githubusercontent.com/760855/83175941-ecbfd900-a146-11ea-8d23-f72b03073b86.png)

**To Reproduce**
1. Add order to cart
2. Complete order checkout process
3. Click on create an account, you will see an error.

**Expected behavior**
Expected to see Account registration form

**Environment (please complete the following information):**
 - @vendure/core version: 0.12.4
 - Nodejs version: Please refer to Vendure demo storefront (0.12.4)
 - Database (mysql/postgres etc): Please refer to Vendure demo storefront (0.12.4)

**Comment by michaelbromley** [comment]
Fixed by https://github.com/vendure-ecommerce/vendure-demo/commit/a6bbbe4a79201863328b03af337aa9c18da57a97
