### ISSUE TITLE
[admin-ui] name and code going blank after multi facet value update

### ISSUE THREAD

**Issue by zifahm** [vendure-ecommerce/vendure#353]
This happens when you add multiple facet values all at once and press the update button. After pressing the update button the name and code value goes all blank. This is especially frustrating after adding couple of facet names and pressing the update button and things goes all blank.

Other times the code field also goes missing while adding facet value in name. Seems like a binding issue in angular?

**Comment by zifahm** [comment]
I think to reproduce try more than 8 or 10 values

**Comment by michaelbromley** [comment]
Hi,

I need a little more detail so I know what is going on here. Please fill out the "steps to reproduce" from the issue template, be very explicit:

---

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
---

For example, I don't even know which page this occurs on.

**Comment by zifahm** [comment]
Here is a loom video that I made https://www.loom.com/share/21f34c96cff44389bac07b7a33545c3f

**Comment by michaelbromley** [comment]
Got it, thanks.

For future reference (in case the loom video is no longer available): the issue occurs on the "create Facet" page. 

* Create a new facet, give it a name and save it.
* Then add e.g. 10 facet values.
* In the video, one of the facet values has a blank "code" input (first bug)
* Then when pressing "update", a bunch of values disappear from the "name" and "code" inputs.
