### ISSUE TITLE
[shop-api] Product query failing in postgres db 

### ISSUE THREAD

**Issue by zifahm** [vendure-ecommerce/vendure#361]
Error produced when  ```{product(id: 5) {
    id
    name
    collections {
      name
      id
      parent{
        id
        name
      }
    }}}``` is run on a **postgres** database

Error: ```"message": "column child.parentid does not exist"```

_This query does not seem to fail in the demo shop api_

**Comment by michaelbromley** [comment]
I can confirm this issue on the current master branch with Postgres 12.3. Works fine with MariaDB. Will add an e2e test for this and get the fix into the next release.
