### ISSUE TITLE
findByFileName should probably be better documented, renamed or updated

### ISSUE THREAD

**Issue by Tyratox** [vendure-ecommerce/vendure#366]
The function `findByFileName`in

https://github.com/vendure-ecommerce/vendure/blob/571ee552b5c6b1d720a9ae8e63048a8e7a2fa7f1/packages/core/src/service/services/asset.service.ts#L61-L73

sounds like it would search for the file's name but when looking at the function body it's obvious that the lookup is done using the source field. This is probably not what a user expects nor really helpful as for example the default asset plugin is adding random prefixes to the source field that correspond to the local path. As the matching operator '%' is only added at the end, it's not obvious to me what the purpose of the function is.

Ideas:
- Add a '%' matching operator in front of the term as well, e.g.
```typescript
findByFileName(fileName: string, exact: boolean = true): Promise<Asset | undefined> {
  const name = exact ? Like('%' + path.basename(fileName, path.extname(fileName))) : Like('%' + path.basename(fileName, path.extname(fileName)) + '%');
  return this.connection.getRepository(Asset).findOne({
    where: {
      name,
    },
  });
}
```

- Rename the function to something like `findBySource`.
- Otherwise I'd suggest to change the function to
```typescript
findByFileName(fileName: string, exact: boolean = true): Promise<Asset | undefined> {
  const name = exact ? fileName : Like(path.basename(fileName, path.extname(fileName)) + '%');
  return this.connection.getRepository(Asset).findOne({
    where: {
      name,
    },
  });
}
```

If I'm completely missing out on something, I think at least the function documentation should be updated to include a statement that the actual lookup is done on whole `source` column, including any prefixes.

**Comment by michaelbromley** [comment]
Just looked into this and the method is actually not used at all, anywhere! Looking at the history, it was added in this commit (https://github.com/vendure-ecommerce/vendure/commit/089282e9496fa410c98861991c5181a30919bf09) and was only used when populating mock data.

I would be inclined to just delete it and let the use created his or her own "find" function according to their particular needs.

**Comment by Tyratox** [comment]
That works as well 👍
