### ISSUE TITLE
Bug while removing promotion

### ISSUE THREAD

**Issue by zifahm** [vendure-ecommerce/vendure#373]
### Steps to reproduce:
Add 5% discount on a specific facet
Add an Item with the same facet of 5% discount
Apply coupon code for  5% discount => 5% has been deducted per item
Remove coupon code for  5% discount =>  error 5% discount still remains per item

Here is a loom video with two promotions added 
https://www.loom.com/share/98a31e69ccc84bbfab2bf16acc2f51d9

**Comment by zifahm** [comment]
Is this the commit you made for this error @michaelbromley  https://github.com/vendure-ecommerce/vendure/commit/c807d32e522736cd226985b8e75aa9ec1510ffad

**Comment by zifahm** [comment]
I think it is

**Comment by michaelbromley** [comment]
Yep, try upgrading to v0.13.0 and see if your issue is fixed.
