### ISSUE TITLE
Few fields on Order.lines goes null for active customer query.

### ISSUE THREAD

**Issue by zifahm** [vendure-ecommerce/vendure#375]
### Steps to reproduce.
* Place an order and reach the state payment authorised or settled.
* query for activeCustomerQuery 
* fields under Order -> lines -> quantity goes null

Here is a loom video
https://www.loom.com/share/033b1c3a7e704b779a55dd91d41ef154

**Comment by samundra** [comment]
@samundra tagging myself for future notifications

**Comment by michaelbromley** [comment]
@samundra you an also use the "subscribe" feature for this purpose - it should be in the right-hand column on desktop.

**Comment by samundra** [comment]
https://github.com/vendure-ecommerce/vendure/issues/374 could be duplicate issue
