### ISSUE TITLE
Missing product fields in query Order > Lines > ProductVariant

### ISSUE THREAD

**Issue by jonyw4** [vendure-ecommerce/vendure#378]
## Problem
Some crucial fields on `Order.Lines.ProductVariant` are missing, like `slug` and `optionGroup.name` and `optionGroup.code`. I use these fields to create a product link, so i think that fields are really important to user navigate in the storefront

## Solutions
Add these fields in `Order.Lines.ProductVariant` or maybe create a Product field in this resolver to user choose witch fields they want to query.

**Comment by michaelbromley** [comment]
The simplest solution here is to define a `ProductVariant.product` field and an `Option.group` field respectively.

However, there is a danger involved here as we now have some new recursive types, e.g.
```graphql
product {
  variants {
    product {
      variants {
        product {
          id
        }
      }
    }
  }
}
```

This creates a risk described in #381 

The alternative of storing these values directly on the `OrderLine` entity removes that risk, but is inelegant as this is data that should be derived from live values, and is kinda the point of GraphQL in the first place.

I think the way forward is to solve 381 and then implement the fields & resolvers.
