### ISSUE TITLE
Ability to delete multiple assets through Admin Asset Dashboard

### ISSUE THREAD

**Issue by samundra** [vendure-ecommerce/vendure#380]
**Is your feature request related to a problem? Please describe.**
No, it's not related to a problem. It is completely a new feature request. On Assets dashboard, currently we can delete one asset at a time. This feature request is to add new abilities to asset dashboard which will allow admin to delete multiple assets simultaneously.

**Describe the solution you'd like**

- Choose multiple asset by clicking on them.
- Then clicking on delete will delete all of them.

**Describe alternatives you've considered**
- No alternatives so far. Deleting one asset at a time.

**Additional context**
Someone accidently uploaded many assets to dev server (AWS bucket) thinking that they were working on their local. But Local server config was configured to use Dev AWS Bucket. Then we ended up having many assets on dev server which were not used at all.

**Comment by samundra** [comment]
:partying_face:

**Comment by michaelbromley** [comment]
This looks to have regressed in the v2.0 ui refresh.
