### ISSUE TITLE
Relate ProductOption to a FacetValue

### ISSUE THREAD

**Issue by jonyw4** [vendure-ecommerce/vendure#385]
I have a `facet` called `color` with many colors and an `customField` called `colorHex` . Now i want to create a product option that have a color blue and other that have a color green. Today what i can do its relate a facetValue to an variant, witch its very good, but don't work. In this case the product option color information will be duplicated and i will need to add two fields for color name (and color hex), when i could be using the same fields from the facet...

If we have these options and have a relationship between ProductOption with FacetValue we can achieve almost a **attribute configuration** for product variation.

**Comment by michaelbromley** [comment]
Hi,

I want to make sure I understand this feature request properly:

> today what i can do its relate a facetValue to an variant, witch its very good, but don't work

Can you explain what you mean by "don't work"? I.e. what is the desired behaviour that you are trying to achieve?

Perhaps a step-by-step workflow would make it clearer?

**Comment by jonyw4** [comment]
Ok, here an example:

## Example
I am creating a product called Shoe. This product have two colors, blue and pink. I want to add this colors as OPTIONS. So, in this way, the user can choose which color he wants to buy.
![Capturar 7](https://user-images.githubusercontent.com/14056669/85286661-6a86b400-b469-11ea-8bb6-9bdae2cc0da4.PNG)

But the problem here its that i can't filter the product options in search query in Shop API, **the proper way to search its using a facet (which its working)**. 

![Capturar 8](https://user-images.githubusercontent.com/14056669/85286665-6c507780-b469-11ea-9e6b-129ba669c19d.png)

Alright, now should work. Also, **I can add color in Product or in Product Variant**. Its great. BUT...

**Realize that i have duplicate information**, I have in two places the color information. 

In my store its more complicated... I have some products options that change for color too, and i want to display the color in hexadecimal to user in Category Page as filter and in product page as option. To do this i added a field called `colorHex` in facetValue, but to this work properly i have to create a `colorHex` in product option too and add a duplicated information about the color in two places...

## Solution
What i am propose its the ability to relate ProductOption to a FacetValue. Maybe as a optional field, with a relationship `one > one` FacetValue. In this way the users can use the same facet that can be used for search filter and catalog to build their product option.

**Comment by jonyw4** [comment]
Hey @michaelbromley what do you think about this?

**Comment by michaelbromley** [comment]
Hey, sorry for the lack of feedback. I have the feeling that the problem can be solved in a way that requires no modifications to Core.

For example, take the use case: **filter search results based on option name**:

This could be possible with an extension to the ElasticSearch plugin. I think you can already tell it to index the product option name using the [custom mappings](https://www.vendure.io/docs/typescript-api/elasticsearch-plugin/elasticsearch-options/#customproductmappings) feature. The additional step would be to use that in the query, which I think you could do using the [mapQuery](https://www.vendure.io/docs/typescript-api/elasticsearch-plugin/elasticsearch-options/#mapquery) feature.

Then let's consider the use-case: **Display hex color in a storefront filter**:

So from what you wrote it sounds like you already added a `colorHex` custom field to the ProductOption entity? Using the ElasticSearch custom mappings you should also be able to expose this data in your search results.

Let me know if those ideas work for you.

**Comment by jonyw4** [comment]
Alright. I will take a look in these features that you describe and check if this could resolve the implementation.

**Comment by jonyw4** [comment]
The solution that you propose don't work in this case because I will need to access the colorHex information in `Facet` not in `ProductOption`. I will try to explain the case better.

In the storefront I will use all `Facets` and `FacetValues` of a search to make a _sidebar filter_ (like the actual Vendure storefront demo). When facet is `color` **I want to show the color by getting a hex in `FacetValue` `customField`**

## How to get the color and colorHex from a ProductVariation today (Working)
We need to connect a `ProductVariation` to a `FacetValue` and in search shop gql query for facetValue customField

## Problem
In this scenario we need to create a color either in `Facet` and `ProductOption`. (like I demonstrate in previous comment).

## Proposal: A better way to get attributes from ProductOption
When we create a `ProductOption` we could connect / select a `FacetValue`. Doing that we:
- will not have redundant data
- have kind a [Magento EAV](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/attributes.html) way to find and categorize products 
- achive more complex search's by having a one more layer of facets in product. _(Product have facet, ProductVariant have facet, and now ProductOption have facet)_

**Comment by martijnvdbrug** [comment]
Hi @jonyw4, have you found a solution for this?

I think the common approach to this is to create a custom field `hexColor` on `ProductOption`, as Michael described, instead of on a facet value. 

I am closing this for now, since it has been a while since this was openend, but feel free to re-open if you think there is something that needs to change in Vendure core!
