### ISSUE TITLE
Filter by price in SearchProducts Shop API

### ISSUE THREAD

**Issue by jonyw4** [vendure-ecommerce/vendure#386]
Should be nice to filter products by price since these feature its really common in the most Category and Search pages of ecommerce.

Initially I thought use the `PriceRange` typing that have in `price` field from `Product` / `SearchResult`.

**Comment by michaelbromley** [comment]
Hi,

This is already supported by the ElasticsearchPlugin: https://www.vendure.io/docs/typescript-api/elasticsearch-plugin/#search-api-extensions

I don't plan to port it to the DefaultSearchPlugin.
