### ISSUE TITLE
Error fetching products after extending admin ui in plugin

### ISSUE THREAD

**Issue by sirramin** [vendure-ecommerce/vendure#393]
I wrote a new plugin that extends admin ui and add new navigation in dashboard.
But in causes error in fetching some apis.
After disabling the plugin everything backs to normal.

![image](https://user-images.githubusercontent.com/3243902/86044082-d87d3d80-ba5e-11ea-92af-e32cc715b8a6.png)

**Comment by michaelbromley** [comment]
Hi,
What version of @vendure/core are you using? The `facetValueOperator` option was introduced in version 0.13.0

**Comment by sirramin** [comment]
> Hi,
> What version of @vendure/core are you using? The `facetValueOperator` option was introduced in version 0.13.0

I was using version 0.12.5 but ui-devkit version was 0.13.0.
After downgrading to 0.12.5 problem solved
Thank you.
