### ISSUE TITLE
Can plugins have dependencies from NPM

### ISSUE THREAD

**Issue by AshotN** [vendure-ecommerce/vendure#395]
I'm reading through the documentation on https://www.vendure.io/docs/plugins/writing-a-vendure-plugin/

But I can't tell if it's possible for a plugin to have a dependency, for example if one were to write a sales tax plugin using https://github.com/avadev/AvaTax-REST-V2-JS-SDK

**Comment by michaelbromley** [comment]
Yes, they can. If you are not intending to share the plugin as a stand-alone package, just install the dependency as part of your server package.json.

**Comment by AshotN** [comment]
If i wanted to share the plugin would i just instruct the user to install the dependency

**Comment by michaelbromley** [comment]
If you want to distribute the plugin as an npm package, you would again add the dependency to the package.json file, so that when an end-user installs your plugin, they also automatically get the dependency installed too without needing to manually install it themselves.
