### ISSUE TITLE
Await all promises in the same time in method getEligibleShippingMethods in ShippingCalculator 

### ISSUE THREAD

**Issue by jonyw4** [vendure-ecommerce/vendure#397]
I have some plugins using ShippingCalculator that are promises. Would be nice to all promises were loaded at the same time. Currently, the method `getEligibleShippingMethods` awaits the response from the `shippingMethods`  individually.

https://github.com/vendure-ecommerce/vendure/blob/b2f3f082ade6e95374b997651ac517cb2c1a1890/packages/core/src/service/helpers/shipping-calculator/shipping-calculator.ts#L17-L32

A solution would be using [Promises.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all).

**Comment by michaelbromley** [comment]
Good point, we can parallelize both the `test` and the `apply` steps here.

**Comment by jonyw4** [comment]
I am planning to do a pull request for this issue. Do you have any points before I start to develop?

**Comment by michaelbromley** [comment]
No, go ahead and make a PR! 👍

**Comment by jonyw4** [comment]
> Good point, we can parallelize both the `test` and the `apply` steps here.

I create the #407 PR. To solve the problem I created  `checkEligibilityByShippingMethod`. This function waits for `test` and `apply`. So in `getEligibleShippingMethods` we can make an array of many `checkEligibilityByShippingMethod`, and then create a `Promise.all` with everything at the same time. 
How `apply` depends on the response from `test` I put these two in the same function and apply await for `test`. 

https://github.com/vendure-ecommerce/vendure/pull/407/files#diff-cbb33e9a4b6e3276c9cbe802f7161e80
