### ISSUE TITLE
Accept empty as response in ShippingCalculator

### ISSUE THREAD

**Issue by jonyw4** [vendure-ecommerce/vendure#398]
I have some `ShippingCalculator` that requests another server to get the price of the shipping and not always this ShippingCalculator returns a price, because this carrier doesn't ship everywhere. Currently, we can only throw an error, but in this scenario, it's not an error, its just an empty response. Would be nice if the ShippingCalculator accepts an empty response.

**Comment by jonyw4** [comment]
I can do a PR if you approve the idea @michaelbromley 👌

**Comment by michaelbromley** [comment]
Well, this is exactly why we also have the ShippingEligibilityChecker - we have separated the 2 concerns of 

1. Is this carrier valid for this order?
2. If so, what's the price?

The calculator should only get executed if the eligibility checker returns `true`, so your scenario should indeed be an exception.

**Comment by jonyw4** [comment]
Okay, that makes sense in many cases, but in the scenario that I create a ShippingCalculator that uses an external web service/provider and the response it's unknown, how can I resolve? Because I don't know if the shipping address of the customer it's valid for this carrier if I don't ask for the shipping calculator, you got it?

**Comment by michaelbromley** [comment]
The idea is that in your custom ShippingEligibilityChecker, you make the call to the carrier's API, and if you get an empty response, you resolve it with `false`, because that carrier cannot ship this order. If you get a price, then you return `true`. 

I know this means you'll need 2 basically identical calls to their API for the checker + calculator step, but if this is a problem you could e.g. implement caching locally so you do not need to make the second call for the price if you already just asked the API in the checker step.

**Comment by jonyw4** [comment]
I understand but this doesn't feels right...
In this scenario i need to add a custom ShippingCalculator and a ShippingEligibilityChecker to just to configure one shipping calculation / carrier, that can complicate the implementation.
I think that adding a null or empty response for ShippingCalculator its so much easier solution both for developers and to the admin user that will be using the Admin UI.
In addition, if we can return null from ShippingCalculator i can create a custom ShippingEligibilityChecker that can be used for many ShippingCalculator.

**Comment by michaelbromley** [comment]
OK, I get it. So do you propose to change the return type of the `ShippingCalculator.calculate()` method to `ShippingCalculator | undefined`?

If so, I guess the implementation to support it would be as simple as checking for undefined [here](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/entity/shipping-method/shipping-method.entity.ts#L57).

**Comment by jonyw4** [comment]
Yes! That its what i thought 👍

**Comment by michaelbromley** [comment]
OK. If you want to do a PR for this then please go ahead. :+1

**Comment by jonyw4** [comment]
Okay! I will do that

**Comment by jonyw4** [comment]
I add undefined in some places in ShippingCalculator
https://github.com/vendure-ecommerce/vendure/pull/407/files#diff-d152823e22542fa739952451b56c5bbe

**Comment by jonyw4** [comment]
I forget to add `undefined` in `calculate` fn. I sent a PR to fix that
https://github.com/vendure-ecommerce/vendure/pull/418
