### ISSUE TITLE
Admin UI not working in Safari because of DragEvent

### ISSUE THREAD

**Issue by edxds** [vendure-ecommerce/vendure#408]
**Describe the bug**
The absence of the DragEvent variable in WebKit browsers causes the Angular app to crash on start. 

**To Reproduce**
1. Start Admin UI;
2. Open in Safari (macOS or iOS, or any WebKit browser probably);
3. Check console.

**Expected behavior**
The application should run without crashing.

**Environment (please complete the following information):**
 - @vendure/core version: 0.13.1
 - NodeJS version: 12.17.0
 - Database (mysql/postgres etc): Postgres
 - Browser: Safari (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15)

**Additional context**
This issue is caused by a DragEvent variable being put, by Angular I'm assuming, in metadata files, causing a crash in Safari because it doesn't support DragEvent. Changing DragEvent occurrences to Event fixes the problem. I can open a pull request fixing this issue, as I am already patching this in production with `replace-in-file`.

**Comment by michaelbromley** [comment]
Related: #284

**Comment by edxds** [comment]
My bad! This is a duplicate of #284 . Closing!
