### ISSUE TITLE
Add customFields in BillingAddress and ShippingAddress based on Address  

### ISSUE THREAD

**Issue by jonyw4** [vendure-ecommerce/vendure#409]
The `address` has custom fields but `shippingAddress` and `billingAddress` don't. I think that the same fields that we add in `Address` should be in all addresses.

Custom fields in address
![image (1)](https://user-images.githubusercontent.com/14056669/87550388-5ce9d600-c685-11ea-9fbe-3fe23f6daa77.png)
Without custom fields
![image](https://user-images.githubusercontent.com/14056669/87550379-5c513f80-c685-11ea-9034-8b08d578d821.png)

**Comment by jonyw4** [comment]
Hey @michaelbromley, correct me if I am wrong, but i think that to make this work I need to

**Comment by michaelbromley** [comment]
@jonyw4 it's a bit more complex than that. The reason we don't just use the `Address` type/entity everywhere is that the OrderAddress is not a "live" entity - it is a snapshot of a given Address at the time the order is placed. So e.g. if you later update your address, past Orders still correctly contain your old address.

To do this we need to dynamically (at bootstrap-time) add the custom fields to the OrderAddress type. I plan to work on this now to try to get it in 0.14.1
