### ISSUE TITLE
[AdminUI] Pagination for product variants

### ISSUE THREAD

**Issue by Tyratox** [vendure-ecommerce/vendure#411]
**Is your feature request related to a problem? Please describe.**
Some products in the shop I'd like to move to vendure have a lot of variants, that's also the reason I noticed https://github.com/vendure-ecommerce/vendure/issues/328.

One product in particular has about 9 directions * 4 sizes * 3 materials ≈ 100 variants. ([This](https://shop.feuerschutz.ch/de/produkt/rettungswegschilder-2/) is current shop page for that particular product).
The vendure api seems to work fine but the admin ui will obviously have some performance issues when all of these variants are loaded onto the same page.

**Describe the solution you'd like**
To support this many variants, it would probably be a good idea to add some sort of pagination to the variant view, if possible even with a searchbar that fuzzy matches the entered query. This can all be done client side, 100 variants might be a lot of data to visualize but javascript won't have any issues with this.

**Describe alternatives you've considered**
Another idea would be to hide most of the data inside a [collapsible container](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_collapsible) as this reduces the amount of data to display a lot.
The two approaches can even be combined to get even better performance.

**Additional context**
Since I do not have a lot of experience with angular I think it would be better if someone else implemented this. If needed, I'd be happy to help with any general javascript issues, i.e. filtering the variants etc.

**Comment by michaelbromley** [comment]
So currently the `product.variants` connection is not a `PaginatedList` type - I failed to foresee the use-case of hundreds of variants when I was designing the API.

But as you say, I don't think 100s of variants is an issue for in-memory pagination. Fuzzy search is also a good idea. I think both can be fairly simple to implement for the next release (I'll handle this - I wrote a whole lib for pagination in Angular so it's my time to shine 🤣).
