### ISSUE TITLE
validateVariantOptionIds doesn't ignore (soft) deleted variants

### ISSUE THREAD

**Issue by Tyratox** [vendure-ecommerce/vendure#412]
**Describe the bug**
As described in https://github.com/vendure-ecommerce/vendure/issues/328#issuecomment-623290422, validateVariantOptionIds ensures

> that the optionIds array passed in the input to CreateProductVariantInput:
> 
> 1. has a length equal to the number of OptionGroups assigned to that Product
> 2. one option ID from each OptionGroup is specified
> 3. that no existing ProductVariant of that Product already has that exact combination of optionIds.

now the third point obviously shouldn't take into account deleted variants but currently does so.

**To Reproduce**
1. Create a product with an option group and two options with two variants
2. Delete one of the variants
3. Try to create a variant with the just deleted option
4. Using admin ui it's currently not even possible, using the api you'll get an error

**Expected behavior**
(Soft) deleted variants should behave as actually being deleted and thus be ignored by validateVariantOptionIds. 

**Environment (please complete the following information):**
 - @vendure/core version: 0.13.0
 - Nodejs version: v12.16.3
 - Database (mysql/postgres etc): mysql

**Additional context**
It might be worth to look into whether this should be implemented in helpers such as `getEntityOrThrow` directly there might be many more places bug like this are lurking. If I'm not wrong then the order history is actually the only place that still requires them to be present so it might be worth to default to always ignore soft deleted values and just use code to bypass that in the places where access to them is actually desired.

Depending on the native typeorm soft delete behaviour, https://github.com/vendure-ecommerce/vendure/issues/283 might even fix this issue without the requirement any additional work.

**Comment by michaelbromley** [comment]
This particular bug will get fixed but then I think the longer-term solution to preclude other similar bugs is to switch over to the TypeORM native soft delete as you suggest.
