### ISSUE TITLE
Mixed Content HTTP warning for assets page

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#413]
In Assets tab after deployment over HTTPS, I get Mixed content warning due to HTTP serving of assets preview. The secured site changes to insecure and error is thrown in console.

**Comment by michaelbromley** [comment]
Hi, please can you share your `AssetServerPlugin` config?

**Comment by BeepLoveKarki** [comment]
Here you go.

AssetServerPlugin.init({
            route: 'assets',
            assetUploadDir: path.join(__dirname, '../static/assets'),
            port: 3001,
			/*namingStrategy: new DefaultAssetNamingStrategy(),
			storageStrategyFactory: configureS3AssetStorage({
				bucket: process.env.BUCKET_NAME!,
				credentials: {
					accessKeyId: process.env.ACCESS_KEY_ID!,
					secretAccessKey: process.env.SECRET_ACCESS_KEY!,
					},
			}),*/
        })

**Comment by michaelbromley** [comment]
Try using the [assetUrlPrefix](https://www.vendure.io/docs/typescript-api/asset-server-plugin/asset-server-options/#asseturlprefix) option.

**Comment by BeepLoveKarki** [comment]
Thanks Michael
