### ISSUE TITLE
The assets server host is inconsistently included in an asset source URL.

### ISSUE THREAD

**Issue by niazmsameer** [vendure-ecommerce/vendure#417]
It seems that when directly querying for a product like this:
```
query {
  product(id: 2) {
    name
    featuredAsset {
      preview
    }
}
```
The featured asset's preview URL includes the asset server's host. Like this: `"http://localhost:3000/assets/source/5a/kelly-sikkema-685291-unsplash.jpg"`.

But when querying with a search like this:
```
query allProducts {
  search(input: { groupByProduct: true }) {
    totalItems
    items {
      featuredAsset: productAsset {
        id
        preview
      }
    }
  }
}
```
The featured asset's preview URL does not include the asset server's host. Like this: "preview/71/derick-david-409858-unsplash__preview.jpg". Which is quite inconsistent and makes the frontend development a bit confusing.

**Comment by michaelbromley** [comment]
Thanks for the report. Does it include the host when you don't use an alias in your search query?

**Comment by niazmsameer** [comment]
Yes, it does. Is excluding the host when using an alias the intended effect?

**Comment by michaelbromley** [comment]
No, it was just a use-case I did not account for. I'll see if there is a way to make it work when using aliases.

The code that will need to change is this:

https://github.com/vendure-ecommerce/vendure/blob/01214847e68a540abc711b42924df44003d11fdb/packages/core/src/api/middleware/asset-interceptor-plugin.ts#L66-L68

As you can see it is currently testing the name of the property, and expecting it to be "productAsset"
