### ISSUE TITLE
Add Recaptcha to admin ui login

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#419]
Adding recaptcha to admin UI login is a great feature required as per security measure.

It can be like an optional feature configurable via vendure-config file.

Any opinion?

**Comment by agustif** [comment]
ReCatcha has a pretty bad/frustrating UX though, I guess it can be OK for only admin UI.

OTP/2fa would be better security-wise though.

And a custom question can do the same for bots than a recaptcha can without the frustrating ux

**Comment by BeepLoveKarki** [comment]
Yes. Any form of security measure to admin UI will make it secured for vulnerabilities.

**Comment by michaelbromley** [comment]
I think you'd already be able to do this with a custom login page as per https://www.vendure.io/docs/developer-guide/authentication/#configure-a-login-page--admin-ui

**Comment by BeepLoveKarki** [comment]
Thanks
