### ISSUE TITLE
Admin only accessible assets

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#420]
In some scenarios important assets may be stored in assets like customer bills, vendor company documents which may be misused if publicly exposed.

So if we could have an option to make assets admin access only (making it accessible only via admin UI session activation) that would be a great thing.

**Comment by agustif** [comment]
Would these assets be publicly available if one had the link though?

Might be a bad idea to threat private info as assets whhich in my mind are images/css/svg/fonts etc? which are OK exposed as a public resource on the internet

**Comment by BeepLoveKarki** [comment]
Nope. It won't have. We can send unauthorized errors like we do in admin API. A checkbox like "make it admin accessible only" can be a handy feature to assets, making it more flexible.

**Comment by michaelbromley** [comment]
This is not quite as simple as adding a "private" boolean. When requesting an Asset from the AssetServerPlugin, we do not perform a database lookup on the properties of that Asset, we just get the filename, and fetch that file from disk/S3/wherever. Performing a DB lookup would be bad for performance and would also make things like S3 storage much more complex.

One way you could implement this would be to use a custom AssetStorageStrategy which stores asset binaries in different locations depending on e.g. the filename. So if you generate invoices with a specific format of the filename, the strategy could check that and then if it is a "private" filename format, it can store it e.g. in a restricted S3 bucket or some other location you can restrict.

**Comment by michaelbromley** [comment]
Closing this as I think the method given in my last comment is sufficient for the requirement.
