### ISSUE TITLE
Enable History Extension by Plugins

### ISSUE THREAD

**Issue by drewterry** [vendure-ecommerce/vendure#432]
**Is your feature request related to a problem? Please describe.**
Order and Customer History are invaluable tracking tools.  However, in their current state, they cannot be extended by plugins.  

**Describe the solution you'd like**
Ideally, plugins would be able to specify additional HistoryEntryTypes and HistoryEntryData for both Customer and Order.  

This could also include the ability to specify an Admin UI component for each new type.  

**Describe alternatives you've considered**
I have currently worked around this issue by using a `Note` type.

A slightly less flexible, but easier to implement, alternative might be to use the concept of `customFields` in history types, similar to entities.  The developer could specify a title and a data object, which are then rendered by the Admin UI in a standard format (similar to custom fields).

**Additional Context**
See my current workaround [here](https://github.com/drewterry/vendure-favorites-plugin/blob/master/src/api/favorite-shop.resolver.ts#L63).

**Comment by tianyingchun** [comment]
https://github.com/vendure-ecommerce/vendure/issues/1698 

it seems that this is related requiremnet.
