### ISSUE TITLE
Allow full control over session cookie config

### ISSUE THREAD

**Issue by niazmsameer** [vendure-ecommerce/vendure#436]
I'm getting a console warning on Chrome about a cookie not being set as it's SameSite attribute is not explicitly set. Is there any configuration that I could change in order to allow cross-site cookies?
<img width="462" alt="Screenshot 2020-08-14 at 1 13 26 PM" src="https://user-images.githubusercontent.com/46391420/90216014-02809880-de30-11ea-94b8-8c8ead8d2ddc.png">

**Comment by michaelbromley** [comment]
Hi,
Can you provide a bit more information on how exactly to reproduce this?

e.g. 
* What's the browser URL when you see that warning?
* What's the server URL?

plus any other steps to reproduce.

**Comment by niazmsameer** [comment]
I can't exactly reveal the URL at the moment but both URLs are but because I'm waiting for my client to purchase a domain, both the frontend URL and backend URL are plain IP addresses. Could that have to do with anything? Also, I'm unable to call GraphQL mutations from the frontend because of the cookie issue ( I assume ).

**Comment by michaelbromley** [comment]
Is the frontend and server on the same origin? I.e. same IP and port?

PS you can join our [slack workspace](https://join.slack.com/t/vendure-ecommerce/shared_invite/enQtNzA1NTcyMDY3NTg0LTMzZGQzNDczOWJiMTU2YjAyNWJlMzdmZGE3ZDY5Y2RjMGYxZWNlYTI4NmU4Y2Q1MDNlYzE4MzQ5ODcyYTdmMGU) where you can DM me the real URLs so I can take a quick look if you like.

**Comment by niazmsameer** [comment]
They're on different hosts.

**Comment by michaelbromley** [comment]
It should still work like that. I see you joined Slack, so DM me there and I can take a look.

**Comment by michaelbromley** [comment]
This issue can be reproduced locally by running a storefront from "127.0.0.1" whilst pointing to "localhost" for the server. The browser (Chromium) interprets this as different domains (different ports are not enough to trigger this warning) and shows the warning.

Here's the advice given in devtools:

> Because a cookie's SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which will prevent the cookie from being sent in a cross-site request in a future version of the browser. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.

> Resolve this issue by updating the attributes of the cookie:
> Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
> Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests

I think the best way to handle this is to expose some or all of the options from the [cookie-session middleware](https://expressjs.com/en/resources/middleware/cookie-session.html) in VendureConfig so that these settings can be tailored for particular use-cases.
