### ISSUE TITLE
shop-api: Stock on ProductVariant

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#442]
Property of current stock of product variant would be useful on ProductVariant type so it's possible to implement "In stock", "Last x items on stock", "Out of stock" labels for product variant detail pages and/or frontend validation of item quantities being in stock before "add to cart" call.

**Describe alternatives you've considered**
For some shops exact stock level could be sensitive information and not desired to be accessed publicly, therefore it would be nice to have public access to this property configurable in vendure config or be able to create own resolver function.

**Comment by michaelbromley** [comment]
> For some shops exact stock level could be sensitive information and not desired to be accessed publicly, therefore it would be nice to have public access to this property configurable in vendure config or be able to create own resolver function.

Yes, this is the exact reason why I did not include this information by default. It is of course possible to implement your own resolver already using the plugin system, exposing whatever level of detail you feel is appropriate. I'm not sure on what a good "built-in" design for this would be.

Perhaps the ability to specify a transform function in the VendureConfig which takes the ProductVariant as an argument, and returns the stock level information. So you could choose to just directly pass the `stockOnHand` number, or you could use some logic to translate the figure into "In stock", "Low stock" etc.

**Comment by chladog** [comment]
I understand the possibility of writing own resolver with plugin, yet the transform function as you describe for this particular feature which is, from my experience, widely used would be more straightforward.
This concept of transform functions ("pipe") doesn't need to be limited for stockOnHand but any property. E.g. customfields which require some additional mapping/transforms which you don't want to deal with in UI or write plugins which need more context code to implement.

_As we have plugins, it's not critical feature, but would be nice addon from dev productivity perspective._
