### ISSUE TITLE
Make Customers ChannelAware

### ISSUE THREAD

**Issue by hendrikdepauw** [vendure-ecommerce/vendure#446]
As we would like to use Vendure in a multi-tenant environment, we want to make the Customer entity ChannelAware.

Unlike other entities, we feel that Customers should not be aware of this division between Channels. And so, we would like to automatically add a Customer to (all) visited Channels. This makes sure they do not have to fill certain personal information again. On the other hand, particular vendors do not see the information of Customers that have nothing to do with their Channel.

The main question that remains if this approach is used is exactly when a Customer should be assigned to a Channel. We see two options:
- Assign a Customer to a Channel as soon as the Customer visits this Channel. This could be done in the RequestContextService.
- Assign a Customer to a Channel when the Customer executes particular actions on that Channel, like for example creating an Order.

We feel that the first option would be more scalable, but obviously we dislike the performance hit of an additional query to the database every time a request to the server is made. In the second option the developer always has to keep this aspect in the back of the head when extending the API.

We would love to get some feedback on this and hear your thoughts!

**Comment by michaelbromley** [comment]
I agree with the idea that a user should not need to create a new Customer for each channel.

> Unlike other entities, we feel that Customers should not be aware of this division between Channels.

However, I don't clearly understand how this is different from the way in which e.g. Products or Orders are channel-aware. They too are just associated with one or more Channels.

some other thoughts: 

We also need to consider at what point we know which Customer is making a request:

1. If the user is authenticated, then we have a `userId` which can be used to get the associated Customer.
2. If not authenticated, then we have no idea of Customer until the user checks out and we use the `setCustomerForOrder` mutation. At this point, we either create a new Customer or fetch an existing one (based on emailAddress). 

So the two options presented above make sense in the case of an already-authenticated customer. Depending on the way the multi-tenant storefront is implemented, this may or may not be a possibility. I.e. if each tenant is on a separate origin (e.g. `foo.marketplace.com` and `bar.marketplace.com` then the session token may not be shared, at least if using the typical cookie/localStorage methods of storing the session token.

**Comment by hendrikdepauw** [comment]
- If the User is authenticated, there is no issue and we can assign the Channel to the associated Customer
- If the User is not authenticated, we have no Customer to assign a Channel to so there would be no problem. If the customer executes an operation that requires a Customer, one is either created (and we can assign a Channel) or the user logs in (and we can assign a Channel)

Or am I missing something here?

**Comment by michaelbromley** [comment]
> Or am I missing something here?

No, that sounds right to me. The important thing would be an implementation which does not need to make an extra DB call with each request. I leave that to you to think about ;)
