### ISSUE TITLE
[Admin UI] Error logging in

### ISSUE THREAD

**Issue by martavis** [vendure-ecommerce/vendure#448]
**Describe the bug**
I'm getting an internal server error when logging in to the admin ui.

**To Reproduce**
1. Run admin locally
2. Try logging in
3. Observe internal error

**Expected behavior**
I am able to log in or should see a user error such as incorrect credentials

**Environment (please complete the following information):**
 - @vendure/core version: 0.14.0 & 0.15.0
 - Nodejs version: 10.16.2
 - Database (mysql/postgres etc): postgres

**Additional context**
The error I'm getting is:
```
Error: error.native-authentication-methods-not-found
[run:server]     at User.getNativeAuthenticationMethod (C:\Users\deon7\Documents\__auraticd\voni_admin\node_modules\@vendure\core\src\entity\user\user.entity.ts:59:19)
[run:server]     at NativeAuthenticationStrategy.verifyUserPassword (C:\Users\deon7\Documents\__auraticd\voni_admin\node_modules\@vendure\core\src\config\auth\native-authentication-strategy.ts:80:39) 
[run:server]     at process._tickCallback (internal/process/next_tick.js:68:7)
```

I haven't changed any settings before seeing this error. It worked a week ago, then today I see this. I started with 0.14.0 and tried upgrading once I noticed the error. Upgrading to 0.15.0 did not fix the problem. I also tried deleting and reinstalling all packages.

**Comment by michaelbromley** [comment]
Hi. This error indicates that the user you are attempting to log in as does not have an associated NativeAuthenticationMethod in the database. Normally this would only be expected if you upgraded from v0.13.x or lower to v0.14.0 without and explicit migration script to keep user accounts working (v0. 14.0 reworked the way auth is handled). Was this the case for you?

**Comment by martavis** [comment]
Thanks for the quick response. I started with 0.14.0 since installation just over a month ago and I didn't upgrade at all before getting the error. Only then did I attempt to triage the issue by upgrading to 0.15.0.

**Comment by martavis** [comment]
@michaelbromley It seems I posted the wrong error. I only received `error.native-authentication-methods-not-found` once I changed `synchronize` to `false`. The original error is `column "collectionSlugs" contains null values` and I'm not able to start the server. So now I understand that my dev database schema is syncing with Vendure's. Any idea why the column `collectionSlugs` is having an issue?

**Comment by michaelbromley** [comment]
Ok, someone else reported this error over the weekend. It's related to the table `search_index_item`, and the fact that v0.15.0 introduced indexing by collection slug. A fix would be to clear that table of all rows, start the server, and then re-build the search index via the grey icon to the left of the search bar in the products list view.

**Comment by martavis** [comment]
I tried your suggestion but it didn't work, so I decided to drop the database and remove the project, then re-install. It works now. Thank you for your help.
