### ISSUE TITLE
Allow default Permissions to be extended

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#450]
**Is your feature request related to a problem? Please describe.**
Plugins may need to define new customer permissions not covered by the default set. Currently there is no straightforward way to do this. 

**Describe the solution you'd like**
There should be a simple API exposed, e.g. `authOptions.customPermissions`, which accepts an array of custom permission names and then deals with all the wiring-up in the background to make it "just work". 

There also then needs to be a way to get all these available permissions to the Admin UI so a UI can be generated to allow the setting of those custom permissions on roles.

**Describe alternatives you've considered**
Currently you can extends the `Permissions` enum in a plugin, and this gets you part of the way there. However, there is some hard-coded logic which make this impossible in practice:

https://github.com/vendure-ecommerce/vendure/blob/682966f156e239978de4892183a8e147bd32fd72/packages/core/src/service/services/role.service.ts#L192-L202

**Comment by michaelbromley** [comment]
Some initial ideas for the implementation:

* There can be considered to be 2 groups of permissions: CRUD and non-CRUD. CRUD permissions are those like `CreateCatalog`, `UpdateCatalog` etc, where there is a Create, Read, Update, Delete- permission for a specific section. Non-CRUD permissions are e.g. `Authenticated`, `Superadmin`.
* Rather than hard-coding the permissions in a static graphql file ([permission.graphql](https://github.com/vendure-ecommerce/vendure/blob/f129e0cc0b570b637e51cd177d24f07cd8795692/packages/core/src/api/schema/common/permission.graphql)), we can create a run-time function which is used to generate permissions. This would be used internally for the core built-in permissions, and would also be exposed in the VendurePlugin or VendureConfig API.
* Shifting permission creation to TS code would also allow easier creation, e.g.:
    ```ts
    customPermissions: [
      new CrudPermissionDefinition('Review'),
      new PermissionDefinition('ExternalService'),
    ]
    ```
* Additionally, I think it may make sense to make the existing built-in permissions more granular. E.g. The "Settings" CRUD permissions cover disparate things like ShippingMethods, TaxRates and GlobalSettings. I think it would be better to more-or-less split them by entity, i.e. CreateTaxRate, CreateShippingMethod, etc.

**Comment by thomas-advantitge** [comment]
Hi @michaelbromley, just wanted to highlight a totally different approach here. _It will most likely be overkill and less suitable given the current Vendure architecture._

As a company we're putting a lot of research in reusable code blocks and separation of concerns. There are open source and SaaS tools available (e.g. https://github.com/ory/keto) handling the whole auth, identity and permission logic separately from a "main" application. It gives the opportunity to focus more on business logic and have a lot of complex features available (like advanced managing of permissions and roles). 
It is mainly related to the principle of microservices which can help solving scaling and maintaining issues for big applications. In practice, Apollo Federation can handle such architecture for GraphQL APIs.

To be concrete, you would be able to communicate through a BE to BE API to the permission server which controls the permissions. The only part which then still is needed in Vendure itself should be business code which relies on permissions. All the "simple" cases like CRUD could even be blocked by the permission microservice before reaching the resolver in the main application.

However, microservices also introduce a lot of new kinds of problems and change in architecture, which will probably not outweigh the benefits of the approach you indicated, at least in the current phase of Vendure.

**Comment by michaelbromley** [comment]
@thomas-advantitge Thanks for that insight. You are correct that I'd like to keep the baseline architecture as simple as possible. But it would be good to be able to support use-cases like the one you mention, if it is possible without compromising the simple and integrated solution I'm thinking about.

> The only part which then still is needed in Vendure itself should be business code which relies on permissions

As it stands, the permissions layer is rather thin anyway - there is a single point in during the AuthGuard where permissions are checked for the requested operation: https://github.com/vendure-ecommerce/vendure/blob/f129e0cc0b570b637e51cd177d24f07cd8795692/packages/core/src/api/common/request-context.service.ts#L72-L85

All further code, from resolvers to the service layer, have no knowledge of permissions. They just assume that if the user got there, then they are authorized to execute whatever is there.

It would be feasible to make this function configurable e.g. with a `AuthorizationStrategy` which then allows you to call out to some external service to check permissions. I'm not sure if that would be enough to integrate with something like Keto.

I think the more difficult part would be to figure out how to assign these external roles to users. I guess custom fields on the User entity could be fine, and the Admin UI parts which deal with roles would then be redundant (you could create your own UI extensions to integrate with the 3rd party service).

**Comment by michaelbromley** [comment]
The ability to extend permissions in now implemented in the `next` branch. I will leave the ability to integrate with external permissions services (as [discussed above](#issuecomment-715361060)) for now, and it can be made into its own feature request if anyone so desires.
