### ISSUE TITLE
Remove product but ui not update

### ISSUE THREAD

**Issue by wiwatsrt** [vendure-ecommerce/vendure#453]
**Describe the bug**
I deleted product from admin ui but product row didn't hide

**Environment:**
 - @vendure/core version: 0.15
 - Nodejs 12
 - Database postgres

**Comment by michaelbromley** [comment]
Hi, do you have the worker running? Are there any error messages anywhere?

I need a bit more info here to help!

**Comment by wiwatsrt** [comment]
Yes, worker running and no error message but show success delete product.

If refresh app the product will remove from product lists.

**Comment by wiwatsrt** [comment]
I tested with Fast 3G, It's work.
May be service **DeleteProduct** not complete but call service **SearchProduct**

**Comment by michaelbromley** [comment]
Ah that's interesting, I'll have a look to see if there is something I can reproduce by throttling my network.
