### ISSUE TITLE
SVG Asset preview not generated / misbehaves

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#456]
**Describe the bug**
SVG asset image preview is generates corrupted PNG file.

**To Reproduce**
1.) upload any svg image image.svg to Media in Admin UI
2.) query for product with assets { preview }
3.) see that returned url of the file is .../image.svg.png and is corrupted (cannot be opened)

**Expected behavior**
From my POV we don't want to transform SVG to PNG files as SVG is more data efficient and scalable format, however we want to keep same logic when loading the image (query just for preview and not source with additional logic to decide whether source or preview link should be used based on its mimetype). As preview handles resizing, this could work by changing ratio/values of svg container element.
_Additionally if there is any SVG data optimization that could be run by AssetServer when generating SVG preview that would be nice to have._

**Environment (please complete the following information):**
 - @vendure/core version: v15
 - Nodejs version 12
 - Database (mysql/postgres etc): postgres

Additional info: As a workaround for now I check for mimetype and decide whether I should load "preview" for PNG and JPG or "source" for SVG images.

**Comment by michaelbromley** [comment]
Hi,

Regarding the image being corrupted, can you provide an SVG file which demonstrates this? I tried locally with a number of SVG files and the preview png images are viewable.

Regarding the preview behaviour, I'm not totally clear on how this should work (I am no SVG expert). For example, the AssetServerPlugin supports cropping (optionally with a set focal point). Could that also be done by manipulating the SVG source on the fly? If we support keeping SVGs as .svg for the preview image, I'd like the various image transforms to work exactly the same as they do for the raster formats.

> From my POV we don't want to transform SVG to PNG files as SVG is more data efficient and scalable format

If you want a smaller SVG in your storefront for a thumbnail, is there any problem with just loading the source file and scaling it down in your client code?

**Comment by chladog** [comment]
I will investigate and provide SVG that resulted in corrupted PNG file.

In the meantime, yes same transformations would be possible even with SVG format, as there is a way we can manipulate bouding box and clipping masks that would allow same kind of transforms. As well as as "cover" (crop) and "contain" (scale to fit) scaling methods are available in SVG format.

_If you want a smaller SVG in your storefront for a thumbnail, is there any problem with just loading the source file and scaling it down in your client code?_
That is ofc possible and I how I dealt with it for now, however in our case we have mixed formats (listing logos, where we prefer to show nice sharp SVG files where possible, but for some companies we just got PNG/JPG formats) therefore there is need of additional logic on frontend that checkes mime type and decide whether use "preview" or "source"

**Comment by michaelbromley** [comment]
@chladog did you ever find an example svg file that reproduces the issue? If not, let's close this.

Regarding the handling of svg previews by the AssetServerPlugin, you can create a separate feature request issue for that if you like.

**Comment by chladog** [comment]
@michaelbromley  Sorry completely forgot. Actually I found out that no SVG gets transformed to working PNG for us: e.g.: _https://pivovplechu.cz/media/source/c4/logo.svg_
So my frontend app is checking mimetype and if it's SVG then I use **source** and not **preview** for img _src_ attr..
You can see for yourself here: https://pivovplechu.cz/shop-api
with request: 
`query {
  collection(slug: "pivovary") {
    children {
      name
      featuredAsset {
        preview
        mimeType
        source
      }
    }
  }
}
`
None of **previews** that were originally SVG are not working when you try and open them.

**Comment by michaelbromley** [comment]
OK, I finally figured this out - it was tough! When the SVG file dimensions are less than the maxWidth/maxHeight, it means the `SharpAssetPreviewStrategy` does _not_ need to resize the image. Therefore, the default behaviour is to just pass through the source image as the preview. In the case of SVG, this passes the original SVG which then gets renamed to .png. So your corrupt previews are _actually_ just the source SVGs with a .png file extension! 

The solution is to inspect the mime type and in the case of SVG, we _always_ pass it through Sharp, even if resizing is not needed, so that the SVG is always rasterized into a png image for the preview.
