### ISSUE TITLE
Graphql Fragment returns incomplete product.asset.preview url

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#459]
**Describe the bug**
When I query a product without fragment, the asset preview is returned as `http://localhost:3000/assets/source/fc/detjtfuwaaa_trh.jpg`, but when using grapqhl fragments, the asset preview is returned as `preview/ff/detjtfuwaaa_trh__preview.jpg`

**To Reproduce**
1. Go to http://localhost:3000/shop-api
2. Query a product:
```
fragment productFields on Product {
  id
  assets {
    preview
  }
}

{
  product(id: 60) {
    ... productFields
  }
}
```
4. Notice the asset preview being returned without hostname and port.

**Expected behavior**
I expect the results to both return asset preview url with hostname and port.

**Environment (please complete the following information):**
 - @vendure/core version: 0.15.0
 - Nodejs version 12
 - Database (mysql/postgres etc): sqlite

**Additional context**
Fragment query:
```
fragment productFields on Product {
  id
  assets {
    preview
  }
}

{
  product(id: 60) {
    ... productFields
  }
}
```

'Normal' query:
```
{
  product(id: 60) {
      id
      assets {
        preview
      }
  }
}
```

**Comment by martijnvdbrug** [comment]
In `graphql-value-transformers.ts`.`getTypeNodeByPath()` `typeTree.operation.fragmentRefs[]` is empty. There `typeTree.fragments` does hold the fragment data.

**Comment by michaelbromley** [comment]
I've discovered that when the fragment is defined _before_ the query, the URL is not transformed. When the fragment is defined _after_ the query, it works as expected. Very strange! I'll look into how to fix...
