### ISSUE TITLE
When entered prices are including tax, we want unitPrice to be calculated without tax; + taxRate per OrderLine;  + Order: taxBase per taxRate + tax per taxRate

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#467]
When we set channel "Prices include tax for the default Zone" to true. Then have some product with price e.g. 64.00 (it correctly states in admin ui that price is including 21% tax). However queries return price inc. tax in both properties - unitPrice and unitPriceWithTax === 6400;
^^This applies for both OrderItem and OrderLine.

However here would be good to have price without tax per line and taxRate per line. (as for tax reporting and multiple tax rates in one single order we need to know rate per line)
Order totals are calculated both with and without tax correctly.

**Describe the solution you'd like**
We want to unitPrice be always excluding tax.

Additional feature requests:
Very helpful would also be to have new following properties on
**OrderLine**: `taxRate, totalExcludingTax`
currently there is property "lineTax" present on **entity**, it would be good to be added to GQL resolver as well.

**Order**: 
```
taxRates: [
{
taxRate: {{taxRate percentage e.g. 21}},
taxBase: {{tax base = totalExcludingTax of products using this tax rate}},
taxTotal: {{tax total of products using this rate }}
},
...
]
```
This would allow for easy reporting of separate taxes per tax-rate of each sale. - in Czech there are different rates for nonalcoholic and alcoholic beverages for example. And this kind of reporting is mandatory in Czech legislation, probably applies to some other countries as well)

**Comment by michaelbromley** [comment]
Hi,

I want to make sure I understand this part correctly: 

>Order:
>```
>taxRates: [
>{
>taxRate: {{taxRate percentage e.g. 21}},
>taxBase: {{tax base - totalExcludingTax of products using this tax rate}},
>taxTotal: {{tax total of products using this rate }}
>},
>...
>]
>```

So let's say we have an Order with 3 items:

* 1 x Chair, $100 net, with tax rate of 20% = $120 gross
* 2 x Book, $10 net, with tax rate of 10% = $11 gross

So the Order query response would look like:

```
{
  order: {
    taxRates: [
      {
         taxRate: 20,
         taxBase: 10000,  // 1 x Chair @ 10000 cents
         taxTotal: 2000
      },
      {
         taxRate: 10,
         taxBase: 2000,  // 2 x Book @ 1000 cents
         taxTotal: 200
    ]
}
```

Is that what you had in mind?

**Comment by chladog** [comment]
Hi,
yes that's exactly it. Maybe the "-" in taxBase property could be confusing, updated the request with "=".
Your example calculation is exactly what I had in mind.

**Comment by michaelbromley** [comment]
Got it, thanks. I'll consider this. In the mean time it should not be too difficult to add it yourself via a plugin which extends the Order type and implements a resolver for that field.
