### ISSUE TITLE
Payment method calculators (extra fees per payment method)

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#470]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add extra collection fee for "Payment" that would be listed in Order (for invoicing) and eligiblePaymentMethods payload.

**Describe the solution you'd like**
Extending the payment handler with paymentCalculators that would allow calculate and add extra fees per payment method based on order contents and shipping methods. This paymentCalculator should also hold "name" of that fee.
When user selects an payment that has a "price" (e.g. collection fee for "cash-on-delivery", additional fee for more expensive payment service e.g. paypay...) this price would be added to array of `paymentFees: {total: number, name: string}[]` to the order so it can be listed and present in order confirmation and usable for invoicing.
Any calculated fees by the paymentCalculators should also be present in payload when using new "eligiblePaymentMethods" call: 
[New eligiblePaymentMethods method + checking methods to payment handlers #469](https://github.com/vendure-ecommerce/vendure/issues/469#issue-705460988)

**Describe alternatives you've considered**
Incresing of the total amount of order by the collection fee - this results in confusion and "hidden" addition to the order.

**Comment by michaelbromley** [comment]
I've been thinking about a more general solution that would cover this - the idea of "surcharges". These are non-SKU costs that might be added to an order and need to be itemized - extra payment fees being a good example. Other examples:

* extended warranty
* gift wrap service

Implementation-wise, these could use the existing "Adjustments" concept to store the data, which allow an amount and a description to be stored for each adjustment.

**Comment by chladog** [comment]
The solution you describe would be also handy for the other direction - to be able to easily apply general discounts that are not "promotions" (e.g. after personal communication between seller and customer, the seller would be able to apply discount to order via admin ui).

**Comment by michaelbromley** [comment]
I'm going to defer this to v1.0.0 to give me more time to think about it. v0.18.0 is already going to be a massive release and I want to limit the scope a bit so I can get it out! With #583 now implemented you'd be able to do something like this:

```TypeScript
let orderService: OrderService;
const paymentSurchargeProcess: CustomOrderProcess<OrderState> = {
    init(injector) {
        orderService = injector.get(OrderService);
    },

    // The logic for enforcing our validation goes here
    async onTransitionStart(fromState, toState, data) {
        if (fromState === 'AddingItems' && toState === 'ArrangingPayment') {
            const { ctx, order } = data;
            if (order.customFields.paymentType === 'card') {
              // some logic here to ensure you don't double-apply the
              // surcharge ....
              await orderService.addSurchargeToOrder(ctx, order.id, {
                  description: '3% payment surcharge',
                  listPrice: Math.round(order.subTotal * 0.03),
                  listPriceIncludesTax: ctx.channel.pricesIncludeTax,
              });
            }
        }
    },
};
```

**Comment by michaelbromley** [comment]
@chladog Can you let me know whether the new Surcharges functionality introduced in v0.18.0 is sufficient for your needs? If so we could close this.

**Comment by chladog** [comment]
@michaelbromley For our case it fills the need. Thank you.
