### ISSUE TITLE
Do not expose Payment metadata in Shop API

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#476]
**Is your feature request related to a problem? Please describe.**
The `Payment` GraphQL type includes the `metadata` field in _both_ the Admin and Shop APIs. This metadata field can be used (depending on the specifics on the PaymentMethodHandler) to store potentially sensitive data returned by the payment provider. This should not be accessible publicly over the Shop API, even to the owner of that payment.

**Describe the solution you'd like**
Only include it in the Admin API.

**Comment by chladog** [comment]
For some payment providers exatly those metadata are needed for handling the payment on client-side (e.g. URL to gateway, lang, available methods of payment... that we got from server-provider communication but want to pass along to user).

**Describe the solution you'd like**
change metadata object to hold properties `private` (accessible only over AdminAPI) and `public` JSONs so resulting object looks like
```
Payment {
   metadata {
      public { ... }
      private { ... }
   }
}
```

Then developer can decide where each subset of metadata belongs to and the terminology makes clear statement on accessibility.

**Comment by michaelbromley** [comment]
Thanks for the feedback! I'll make sure to include a private/public mechanism in the solution.

**Comment by michaelbromley** [comment]
Hey @chladog I've just started working on this and I'm not 100% clear on the kind of workflow that would require public metadata.

The workflow I know (e.g. PayPal, Braintree) goes like this:

1. Client-side call from storefront to Payment Provider (PP) with card detail. PP processes this and returns a transaction id.
2. Storefront then does `addPaymentToOrder` with that transaction id.
3. On the server, in the `PaymentMethodHandler.createPayment` method, that transaction id is used to verify the transaction securely. At this point the PP provides a ton of metadata relating to the transaction that can be stored in the `metadata` field.

Can you give me an overview that clarifies this in a bit more detail:

> For some payment providers exatly those metadata are needed for handling the payment on client-side (e.g. URL to gateway, lang, available methods of payment... that we got from server-provider communication but want to pass along to user).

Thanks!

**Comment by chladog** [comment]
@michaelbromley 
Hi, for example this payment provider from Czech Republic [GoPay](https://www.gopay.com/en/) which allows many forms of payment (cards, wire transfers, premium SMS etc.), that I've integrated in our e-shop has following flow:
1.) Server establishes payment - that is the call by the server to the provider containing order details, amount, currency, **tax rates** etc... This must be called by server as we authenticate with private credentials, and also have to do taxing calculations prior which is the part that we don't even want to "leave up to a client code".
2.) Provider replies to the server with metadata about this newly established payment - e.g. **transaction id**, payment method, invoice number, info about buyer and **url to gateway**.
3.) Server then sends this metadata to client which is redirected to that gateway.

So actually in Vendure I have implemented payflow little differently than you describe:
1.) When selecting "gopay" in storefront call `addPaymentToOrder`
2.) Payment is created (`createPayment`), server makes round-trip to provider establishing payment and payment goes to "Authorized" state with metadata.
3.) These metadata are passed back to storefront as a response to that `addPaymentToOrder` call and payment gateway is opened.
4.) Once paid, server is notified about payment status change by REST and payment is transitioned to "Settled".

You can also check docs of the payment flows here:
https://doc.gopay.com/en/#standard-payment

**Comment by michaelbromley** [comment]
@chladog thank you for the clear explanation. 

For reference, here are some more examples of similar flows where data from the provider is required in the storefront:

* [Razorpay:](https://razorpay.com/docs/payment-gateway/payment-flow/)
* [Adyen Pay by Link API](https://docs.adyen.com/checkout/pay-by-link#create-payment-links-through-api)
