### ISSUE TITLE
Make order list more friendly to shop managers => filter out orders in "AddingItems" state

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#477]
**Is your feature request related to a problem? Please describe.**
There is going to be huge amount of never completed orders that just stay in AddingItems state forever.
Even though those data are valuable for analytics of customer behavior, on ordinary day those are not orders that interest shop managers who need clear list of orders in the process be it payment states, custom states, partial fulfillment etc...
Current filter filters only by one specific state.

**Describe the solution you'd like**
Allow the current filter to take multiple selects (e.g. multiselect list with checkboxes)
This setting should be persisted per user.

**Describe alternative you've considered**
A filter that can filter **out** any state (meaning all states except those in filter are present).

**Describe addition you've considered**
Some mechanism of tidying anonymous orders that never make it out of "AddingItems" every once in a while

**Comment by chladog** [comment]
Additionally **custom order states are not present in current filter**. Those we would like to have in this new filter implementation present as well.

**Comment by incorvia** [comment]
I think a general solution that could allow a developer to implement custom filters of varying types against custom fields would be ideal as a long term goal. I come from a Rails background and use ActiveAdmin quite a bit. One can quite quickly create a filter against a specific column by defining some backend setting like:

`filter :email, as: :string`

Resulting in a filter like:

![image](https://user-images.githubusercontent.com/386548/95585464-e3a01c00-0a04-11eb-9ee9-f6e0f39b5371.png)

I imagine a tool similar to how one can create custom promotion conditions would be amazing.

**Comment by michaelbromley** [comment]
I have implemented improved filtering in the order list view in the above commit. 

> Some mechanism of tidying anonymous orders that never make it out of "AddingItems" every once in a while

> This setting should be persisted per user.

> a general solution that could allow a developer to implement custom filters of varying types against custom fields 

These are all great suggestions but for the sake of keeping this issue focused, I am considering them out of scope for now. Please feel free to open individual feature requests for the above (I'd say only the first one is something I'd prioritize for v1.0)
