### ISSUE TITLE
If there is error when creating collection, the initially set slug cannot be used anymore.

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#479]
**Describe the bug**
When we provide invalid input for collection creation, the record in table "collection" is correctly not created, however the record in "collection_translation" is created without saving any relation but blocking the slug value for any future records.
If then this slug is used for correctly created collection then "Cannot read property 'id' of null" error is thrown.

**To Reproduce**
1. Create some custom fields that might result in error during creation of collection (in my case that was a string which I didn't set length for)
2. Go go Collections and create collection - fill in the data the way which would result in error (in my case that would be longer string in custom field than column takes)
3. Create new collection with the same slug as that never created collection
4. Try to query that collection using that slug - error is thrown
Further inspection reveals that the relational record of the first attempt to create a collection which resulted in error has been created in "collection_translation" table effectivelly blocking usage of that slug.

**Expected behavior**
Related records of entity should be created only when it's creation has been successful.
"collection_translation" baseId column should be NOTNULL

**Environment (please complete the following information):**
 - @vendure/core version: 15.1
 - Database Postgres

**Comment by michaelbromley** [comment]
In the next minor version all mutations are performed in a transaction which is rolled back in the case that an error is thrown (#242)

This will be available in v0.16.0. I will leave this issue open and revisit it once that is released and we can verify that it has been fixed.

**Comment by michaelbromley** [comment]
I just tested this scenario in the `next` branch (which uses transactions on all mutations) and it is fixed.
