### ISSUE TITLE
Serve uploaded images in next-gen formats for faster storefronts

### ISSUE THREAD

**Issue by edxds** [vendure-ecommerce/vendure#482]
**Is your feature request related to a problem? Please describe.**
It's important to always have a fast and responsive storefront, and one of the keys to achieving that is serving images compressed and/or in next-gen formats, such as WebP.

**Describe the solution you'd like**
A plugin or a change in core that compresses/converts uploaded images into next-gen formats automatically. While serving next-gen formats is great, some browsers, such as Safari, still don't support them, so it's also important to serve potentially larger, but more compatible formats, such as JPEG.

**Describe alternatives you've considered**
The admin-ui users could convert and compress the images themselves, but this is tedious and a perfect opportunity for automation.

**Comment by michaelbromley** [comment]
Another idea I'm just noting here: consider adding support for BlurHash: https://blurha.sh/

This would allow us to store a compact string representation of the blurred image to enable instant color-correct placeholder images while the main images load.

**Comment by edxds** [comment]
I think that would be a great idea. But where would this functionality as a whole be? I know the AssetServerPlugin has the storage strategy option, maybe we could introduce a processing strategy option? I don't know where image processing could exactly fit in this workflow.

**Comment by michaelbromley** [comment]
I think it could be implemented as part of the AssetServerPlugin, as an optional extra which can be switched on.

When enabled, it could add a `blurHash` customField to the Asset entity and then hook in somewhere (maybe via an event listener or TypeORM subscriber) to generate the hash.

**Comment by edxds** [comment]
I think that's a nice approach. Now, what about converting images and serving them in other formats, such  as WebP? I feel like this could be handled in the AssetServerPlugin as well.

**Comment by michaelbromley** [comment]
Yes, it would also come under the AssetServerPlugin. Specifically the [SharpAssetPreviewStrategy](https://github.com/vendure-ecommerce/vendure/blob/master/packages/asset-server-plugin/src/sharp-asset-preview-strategy.ts), but I think we'd need to extend the strategy API a little to allow multiple preview formats.

**Comment by edxds** [comment]
I've done some digging, and I've come up with some conclusions. 

First, the blur hash could be implemented as a plugin that puts the hash in the saved asset entity, when a 'created' AssetEvent is emitted by the AssetService class. Or it could be implemented directly into the AssetService, but I think a plugin would be a better idea.

Second, I've thought of two ideas to serve WebP. One, it could be generated on upload time, with the AssetService (or other related services) saving the original file and a WebP version. The second, which I think may be more viable, although I'm not 100% sure it's "correct", is by implementing a `webp` query param, so that it can be transformed on the fly and then cached, just like resizing is already implemented. 

I would love to hear your thoughts on this, and if the BlurHash plugin should be developed into the core repository or as a standalone NPM package.
