### ISSUE TITLE
Promotion checker condition need response message

### ISSUE THREAD

**Issue by truonghdpk** [vendure-ecommerce/vendure#484]
I'm using PromotionCondition class that has an async check function with return boolean to apply for promotions, another way I think we need to respond to our customer knew the reason we delined apply this, example why not return object { status: true | false, message: "Some message"}

**Comment by michaelbromley** [comment]
PromotionConditions are checked whenever the Order changes. For example, `addItemToOrder`, `adjustOrderLine`, `addCustomerToOrder` will all trigger the calculation of order adjustments.

How would you imagine that the "Some message" would fit in to this? At the moment I can't think of a workable API to accommodate this feature. If you have any suggestions please let me know.

**Comment by michaelbromley** [comment]
I'm going to close this as there is no clear way to support this feature.

If anyone wants to pursue it and has a workable idea of how to implement, feel free to comment here and I'll reconsider.
