### ISSUE TITLE
Wrong UI components of argument data types

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#489]
**Describe the bug**
![wrong comp](https://user-images.githubusercontent.com/15977485/95442680-fb6f9580-095b-11eb-9973-b669d49fb84d.JPG)
Args of the payment method have mixed up their UI components. As seen in the image, there is property "prod" of type boolean but is rendered as text input and other way returnUrl property is of type string but has been rendered as checkbox and I'm currently unable to change this returnUrl string.
However I'm not quite sure why and exactly when it happens. I have no custom code for payment handlers, their args nor components in place and I have tried to disable all custom rendering components to see if I did not introduce problem, but it stays the same..
Just FYI order of args defined in payment methods is completely different than rendered:
`       goid: { type: 'int' },
        clientID: { type: 'string' },
        clientSecret: { type: 'string' },
        devApi: { type: 'string' },
        prodApi: { type: 'string' },
        returnUrl: { type: 'string' },
        prod: { type: 'boolean' },
        eet: { type: 'boolean' }`

**To Reproduce**
1. Define payment handler with args of different data types
2. Compile Admin UI
3. Observe the order and (in)correct mapping of fields and their ui components

**Expected behavior**
Args should be ordered in an order as defined. But mainly their should always render correct ui component for their data type.

**Environment (please complete the following information):**
 - @vendure/core version: 15.2
 - Database (mysql/postgres etc): postgres

**Comment by chladog** [comment]
There is no error shown in console log when this occurs.

**Comment by michaelbromley** [comment]
I've just attempted to reproduce this, both with the bundled Admin UI and also an extended compiled version, but I cannot see the same behaviour.

Can you take a look in the network tab at the `GetPaymentMethod` query and see if the args in the `data.paymentMethod.configArgs` array are in the correct order or not?

**Comment by chladog** [comment]
THe array is in incorrect order - configArgs and definition args orders do not match:

`{
  "data": {
    "paymentMethod": {
      "id": "2",
      "createdAt": "2020-08-25T09:14:36.388Z",
      "updatedAt": "2020-10-20T06:47:49.166Z",
      "code": "gopay",
      "enabled": true,
      "configArgs": [
        {
          "name": "clientID",
          "value": "XXXXXXXXXX",
          "__typename": "ConfigArg"
        },
        {
          "name": "clientSecret",
          "value": "XXXXXXXXXX",
          "__typename": "ConfigArg"
        },
        {
          "name": "devApi",
          "value": "https://gw.sandbox.gopay.com/api",
          "__typename": "ConfigArg"
        },
        {
          "name": "prodApi",
          "value": "https://gate.gopay.cz/api",
          "__typename": "ConfigArg"
        },
        { "name": "prod", "value": "false", "__typename": "ConfigArg" },
        { "name": "goid", "value": "8857811853", "__typename": "ConfigArg" },
        {
          "name": "returnUrl",
          "value": "https://pivovplechu.cz/objednavka",
          "__typename": "ConfigArg"
        },
        { "name": "eet", "value": "false", "__typename": "ConfigArg" }
      ],
      "definition": {
        "args": [
          {
            "name": "goid",
            "type": "int",
            "list": false,
            "ui": null,
            "label": null,
            "__typename": "ConfigArgDefinition"
          },
          {
            "name": "clientID",
            "type": "string",
            "list": false,
            "ui": null,
            "label": null,
            "__typename": "ConfigArgDefinition"
          },
          {
            "name": "clientSecret",
            "type": "string",
            "list": false,
            "ui": null,
            "label": null,
            "__typename": "ConfigArgDefinition"
          },
          {
            "name": "devApi",
            "type": "string",
            "list": false,
            "ui": null,
            "label": null,
            "__typename": "ConfigArgDefinition"
          },
          {
            "name": "prodApi",
            "type": "string",
            "list": false,
            "ui": null,
            "label": null,
            "__typename": "ConfigArgDefinition"
          },
          {
            "name": "returnUrl",
            "type": "string",
            "list": false,
            "ui": null,
            "label": null,
            "__typename": "ConfigArgDefinition"
          },
          {
            "name": "prod",
            "type": "boolean",
            "list": false,
            "ui": null,
            "label": null,
            "__typename": "ConfigArgDefinition"
          },
          {
            "name": "eet",
            "type": "boolean",
            "list": false,
            "ui": null,
            "label": null,
            "__typename": "ConfigArgDefinition"
          }
        ],
        "code": "gopay",
        "description": "GoPay",
        "__typename": "ConfigurableOperationDefinition"
      },
      "__typename": "PaymentMethod"
    }
  }
}
`

**Comment by chladog** [comment]
I have fixed it temporary by matching order of saved values in DB to that of definition. I believe the problem was introduced when additional field to definition was not reflected in DB entry and mixed up the ordering of everything.
