### ISSUE TITLE
Promotions applicable to products/categories

### ISSUE THREAD

**Issue by hendrikdepauw** [vendure-ecommerce/vendure#491]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to know in the FE which products and categories are affected by promotions. We would like to have this information on hand to show to the customer.

**Describe the solution you'd like**
We would like to have a relation between promotions and products/categories. Other entities might be applicable as well if there would be any use case.
Multiple ways exist to implement this feature and we would like your feedback before starting.
- We simply add a ManyToMany field between Promotions and ProductVariant and between Promotions and Categories. When the admin creates a promotion, the admin adds a list of products/categories to the Promotions entity. In the ShopResolver we should exclude Promotions that are not yet active, no longer active or not enabled.
- Because the list of categories or products can sometimes be long, we could implement this list as a function. The function can return a list of products/categories based on other information. In this case a worker would be used that is triggered using events that can construct the relation table between Promotions, Products and Categories based on this function.
- Any other method that is suggested

Additionally, we do not necessarily want to return the Promotion entity itself. With any Promotion entity, a PromotionInfo entity could be associated. This entity can include information such as % discount, or a list of other products that can be used to make a 2+1 promotion for example. A link to an Asset can also be added, to show stickers on the products.

We would love to hear your feedback on this!
Please feel free to reach out with any questions you might have.

**Comment by michaelbromley** [comment]
Hi,

Your suggestion sounds very much like the current implementation of Collections, whereby:

* A configurable set of criteria (filters) are set of the Collection
* This triggers a worker process to populate the Collection <-> ProductVariant relations on save

The key difference (and the real challenge here) is that PromotionConditions do not only operate on the ProductVariant properties. E.g. you can have a promotion that activates if the customer if a member of a particular CustomerGroup, or if the order total is greater than $100. How do we handle the relation in cases such as these?

I'm not sure what a good solution to this would be. Maybe we could somehow mark certain PromotionConditions as "this condition affects the ProductVariant relationship". But I'm not sure I like that approach.

A different way to solve it would be to leverage the existing affordances: 

* create a Collection named "Winter Promotion" and set up the filters to include the ProductVariants you want to include.
* create a Promotion with the sole condition that "must belong to the Winter Promotion collection"

Now you can already access which ProductVariants are members of this collection. You could even store metadata on the collection as custom fields. Would something like that work for your case?

**Comment by hendrikdepauw** [comment]
Hi Michael,

I do like your approach of using Collections to facilitate this. It does include the featuredAsset which we want, it supports CustomFields and is ChannelAware just like promotions.
What I dislike with this approach is the fact that Promotions and their associated Collection would not be connected in the database and it is hence the responsibility of the admin to maintain this relation.

Building upon your solution, we could support some additional, optional parameters in the CreatePromotion Mutation that can be used to automatically create an associated Collection. When the promotion is deleted, this collection is deleted as well. If we want to make it even more complete, collections for expired or not yet valid promotions can be filtered out. I think this could even be achieved in a plugin.

**Comment by michaelbromley** [comment]
> I think this could even be achieved in a plugin.

Yes, I think this would be feasible. And also an ideal outcome, IMO. If we are able to use the existing features to build more complex plugins on top of, then that's a good validation of the design. Let's leave this open and you can update with any blockers that prevent a plugin-based solution.

**Comment by hendrikdepauw** [comment]
Plugin implemented successfully without any blockers, closing this issue.
