### ISSUE TITLE
Custom PaymentMethodHandler created twice on npm start

### ISSUE THREAD

**Issue by ekoto4** [vendure-ecommerce/vendure#492]
**Describe the bug**
When adding a custom payment handler to the Vendure config. The handler is created twice on start.

**To Reproduce**
1. Create a payment method handler and add it to Vendure Config
2. Add a random integer to print out during construction of payment method handler
3. run ```npm start``` 
4. Observe two different random integers print out

**Expected behavior**
That only one random integer is printed out. (Payment Method Handler only created once).

**Environment (please complete the following information):**
 - @vendure/core version: v0.14.0
 - Nodejs version: 12
 - Database: postgres

**Comment by michaelbromley** [comment]
I've just been looking into this and I'm not totally sure what you mean by "Add a random integer to print out during construction of payment method handler". Can you share an example of how you are doing this?

In my testing I have created the following handler:
```ts
import { LanguageCode, PaymentMethodHandler } from '@vendure/core';

console.log('entered test-handler.ts');

const id = Math.random().toString(36).substr(8);

export const myHandler = new PaymentMethodHandler({
    description: [{ languageCode: LanguageCode.en, value: 'just a test' }],
    code: 'test-handler',
    args: {},
    init: injector => {
        console.log('test-handler init()', id);
    },
    createPayment: (order, args, metadata) => {
        return {
            amount: order.total,
            state: 'Authorized',
            transactionId: '1234',
        };
    },
    settlePayment: order => {
        return {
            success: true,
        };
    },
});
```
and then I pass it to my config like:
```ts
//..
  paymentOptions: {
    paymentMethodHandlers: [examplePaymentHandler, myHandler],
  },
//...
```

When I start the server & worker, I see the following output:

```
$ concurrently yarn:run*
$ node -r ts-node/register index-worker.ts
$ node -r ts-node/register index.ts
[run:worker] entered test-handler.ts
[run:worker] Using mysql connection
[run:worker] info 10/15/20, 11:49 - [Vendure Worker] Bootstrapping Vendure Worker (pid: 25428)...
[run:server] entered test-handler.ts
[run:server] Using mysql connection
[run:server] info 10/15/20, 11:49 - [Vendure Server] Bootstrapping Vendure Server (pid: 13500)...
[run:worker] info 10/15/20, 11:49 - [NestMicroservice] Nest microservice successfully started
[run:worker] info 10/15/20, 11:49 - [Vendure Worker] Vendure Worker started with TCP transport at localhost:3020
[run:server] info 10/15/20, 11:49 - [RoutesResolver] HealthController {/health}:
[run:server] info 10/15/20, 11:49 - [RouterExplorer] Mapped {/health, GET} route
[run:server] info 10/15/20, 11:50 - [AssetServerPlugin] Asset server listening on "http://localhost:5002"
[run:server] test-handler init() 37gz9
[run:server] info 10/15/20, 11:50 - [NestApplication] Nest application successfully started
[run:server] info 10/15/20, 11:50 - [Vendure Server] =====================================================================
[run:server] info 10/15/20, 11:50 - [Vendure Server]           Vendure server (v0.16.0) now running on port 3000
[run:server] info 10/15/20, 11:50 - [Vendure Server] ---------------------------------------------------------------------
[run:server] info 10/15/20, 11:50 - [Vendure Server] Shop API:     http://localhost:3000/shop-api
[run:server] info 10/15/20, 11:50 - [Vendure Server] Admin API:    http://localhost:3000/admin-api
[run:server] info 10/15/20, 11:50 - [Vendure Server] Asset Server: http://localhost:3000/assets/ -> http://localhost:5002
[run:server] info 10/15/20, 11:50 - [Vendure Server] Dev Mailbox:  http://localhost:3000/mailbox/ -> http://localhost:5003
[run:server] info 10/15/20, 11:50 - [Vendure Server] Admin UI:     http://localhost:3000/admin/ -> http://localhost:5001
[run:server] info 10/15/20, 11:50 - [Vendure Server] =====================================================================
```

You can see 2 instances of `entered test-handler.ts`, one for the server and one for the worker, but only a single log from the init() method with the random ID:
```
[run:worker] entered test-handler.ts
...
[run:server] entered test-handler.ts
...
[run:server] test-handler init() 37gz9
```

**Comment by ekoto4** [comment]
> I've just been looking into this and I'm not totally sure what you mean by "Add a random integer to print out during construction of payment method handler". Can you share an example of how you are doing this?
> 
> In my testing I have created the following handler:
> 
> ```ts
> import { LanguageCode, PaymentMethodHandler } from '@vendure/core';
> 
> console.log('entered test-handler.ts');
> 
> const id = Math.random().toString(36).substr(8);
> 
> export const myHandler = new PaymentMethodHandler({
>     description: [{ languageCode: LanguageCode.en, value: 'just a test' }],
>     code: 'test-handler',
>     args: {},
>     init: injector => {
>         console.log('test-handler init()', id);
>     },
>     createPayment: (order, args, metadata) => {
>         return {
>             amount: order.total,
>             state: 'Authorized',
>             transactionId: '1234',
>         };
>     },
>     settlePayment: order => {
>         return {
>             success: true,
>         };
>     },
> });
> ```
> 
> and then I pass it to my config like:
> 
> ```ts
> //..
>   paymentOptions: {
>     paymentMethodHandlers: [examplePaymentHandler, myHandler],
>   },
> //...
> ```
> 
> When I start the server & worker, I see the following output:
> 
> ```
> $ concurrently yarn:run*
> $ node -r ts-node/register index-worker.ts
> $ node -r ts-node/register index.ts
> [run:worker] entered test-handler.ts
> [run:worker] Using mysql connection
> [run:worker] info 10/15/20, 11:49 - [Vendure Worker] Bootstrapping Vendure Worker (pid: 25428)...
> [run:server] entered test-handler.ts
> [run:server] Using mysql connection
> [run:server] info 10/15/20, 11:49 - [Vendure Server] Bootstrapping Vendure Server (pid: 13500)...
> [run:worker] info 10/15/20, 11:49 - [NestMicroservice] Nest microservice successfully started
> [run:worker] info 10/15/20, 11:49 - [Vendure Worker] Vendure Worker started with TCP transport at localhost:3020
> [run:server] info 10/15/20, 11:49 - [RoutesResolver] HealthController {/health}:
> [run:server] info 10/15/20, 11:49 - [RouterExplorer] Mapped {/health, GET} route
> [run:server] info 10/15/20, 11:50 - [AssetServerPlugin] Asset server listening on "http://localhost:5002"
> [run:server] test-handler init() 37gz9
> [run:server] info 10/15/20, 11:50 - [NestApplication] Nest application successfully started
> [run:server] info 10/15/20, 11:50 - [Vendure Server] =====================================================================
> [run:server] info 10/15/20, 11:50 - [Vendure Server]           Vendure server (v0.16.0) now running on port 3000
> [run:server] info 10/15/20, 11:50 - [Vendure Server] ---------------------------------------------------------------------
> [run:server] info 10/15/20, 11:50 - [Vendure Server] Shop API:     http://localhost:3000/shop-api
> [run:server] info 10/15/20, 11:50 - [Vendure Server] Admin API:    http://localhost:3000/admin-api
> [run:server] info 10/15/20, 11:50 - [Vendure Server] Asset Server: http://localhost:3000/assets/ -> http://localhost:5002
> [run:server] info 10/15/20, 11:50 - [Vendure Server] Dev Mailbox:  http://localhost:3000/mailbox/ -> http://localhost:5003
> [run:server] info 10/15/20, 11:50 - [Vendure Server] Admin UI:     http://localhost:3000/admin/ -> http://localhost:5001
> [run:server] info 10/15/20, 11:50 - [Vendure Server] =====================================================================
> ```
> 
> You can see 2 instances of `entered test-handler.ts`, one for the server and one for the worker, but only a single log from the init() method with the random ID:
> 
> ```
> [run:worker] entered test-handler.ts
> ...
> [run:server] entered test-handler.ts
> ...
> [run:server] test-handler init() 37gz9
> ```

**Comment by ekoto4** [comment]
Sorry should have been more specific. So i implemented the config instead of directly passing an obect. I created the random integer as follows:

``` class FlutterwavePaymentMethodConfigOptions
  implements PaymentMethodConfigOptions {
  readonly code: string;
  readonly args: FlwConfigArgs;
  readonly description: LocalizedStringArray;
  private id = Math.random();
  private httpService!: HttpService;

  constructor(
    code: string,
    args: FlwConfigArgs,
    descrption: LocalizedStringArray
  ) {
    this.code = code;
    this.args = args;
    this.description = descrption;
    console.log(this.id);
    console.log(this.code);
  }

  init(injector: Injector) {
    this.httpService = injector.get(HttpService);
    console.log(this.httpService);
    console.log(this.id);
  }
}
...
```

Then I created the payment handler as follows:
```
const flutterwavePaymentMethodConfigOptions = new FlutterwavePaymentMethodConfigOptions(
  "flutterwave",
  {
    publicKey: {
      type: "string",
      label: [{ languageCode: LanguageCode.en, value: "Public Key" }],
    },
    secretKey: {
      type: "string",
      label: [{ languageCode: LanguageCode.en, value: "Secret Key" }],
    },
    productionMode: {
      type: "boolean",
      label: [{ languageCode: LanguageCode.en, value: "Production Mode" }],
    },
  },
  [{ languageCode: LanguageCode.en, value: "Flutterwave" }]
);

/**
 * The handler for Flutterwave payments.
 */
export const flutterwavePaymentMethodHandler = new PaymentMethodHandler(
  flutterwavePaymentMethodConfigOptions
);
```

When running it does the following:
1. Prints out two different random integers from the constructor.
2. Prints out only one of the random integers from the init function
3. Prints out null/undefined when you try and settle payment (My guess is that it is trying to use the payment handler in which init was never ran on.)

**Comment by michaelbromley** [comment]
> Prints out two different random integers from the constructor.

Are they being printed both from the server process? Or one from the server + one from the worker? If the latter, then that is expected.

> Prints out null/undefined when you try and settle payment 

Can you show the code for `settlePayment` so I have an idea of what it _should_ be printing?

I am beginning to suspect that the issue may be to do with method binding, related to this approach of instantiating the config object as a class instance. If you provide the complete code of you implementation I can test out this theory myself.

**Comment by ekoto4** [comment]
> Are they being printed both from the server process? Or one from the server + one from the worker? If the latter, then that is expected.

The latter. One from the server + one from the worker.

> Can you show the code for settlePayment so I have an idea of what it should be printing?

My apologies, I meant the createPayment method. Thats were i use the httpService to create a call to the payment provider.

```
async createPayment(
    order: Order,
    args: ConfigArgValues<FlwConfigArgs>,
    metadata: PaymentMetadata
  ): Promise<CreatePaymentResult | CreatePaymentErrorResult> {
    console.log(this.id);
    try {
      // TODO integrity hash
      const payload: FlwStandardRequestData = {
        tx_ref: uuidv4(),
        amount: `${order.total / 100}`,
        currency: order.currencyCode,
        redirect_url:
          "https://webhook.site/9d0b00ba-9a69-44fa-a43d-a82c33c36fdc",
        payment_options: "card",
        customer: {
          email: `${order.customer?.emailAddress}`,
          phonenumber: `${order.customer?.phoneNumber}`,
          name: `${order.customer?.lastName} ${order.customer?.firstName}`,
        },
      };
      console.log(payload);

      const config: AxiosRequestConfig = {
        headers: {
          Authorization: `Bearer ${args.secretKey}`,
        },
      };
      console.log(config);
      console.log(this.httpService);
      const response = await this.httpService
        .post<FlwStandardResponse>(
          "https://api.flutterwave.com/v3/payments",
          payload,
          config
        )
        .toPromise();
      console.log(response);

      return {
        amount: order.total,
        state: "Authorized",
        transactionId: payload.tx_ref,
        metadata: {
          link: response.data.data.link,
        },
      };
    } catch (error) {
      logger.error(error);
      return {
        amount: order.total,
        state: "Error",
        errorMessage: error.toString(),
        metadata: error,
      };
    }
  }
```

**Comment by michaelbromley** [comment]
Thanks for that. Last question: which of those many console.log statements prints null/undefined where you expect some other value?

**Comment by ekoto4** [comment]
> Thanks for that. Last question: which of those many console.log statements prints null/undefined where you expect some other value?

The two I was watching were:
```
console.log(this.id);
```

and:
```
console.log(this.httpService);
```

the id prints out one of the process. The httpService returns undefined/null. So when the function settled payment is called, post is called on null. Think its because init was never ran on the handler that is used for execution.

**Comment by michaelbromley** [comment]
Hi, sorry for the slow follow-up. 

I suspect what might be happening is that this is more of a problem with variable scope, namely the `this` in `this.httpService` is probably not referring to the `FlutterwavePaymentMethodConfigOptions` instance at run time. You can test this theory by adding

```ts
console.log(this instanceof FlutterwavePaymentMethodConfigOptions);
```

If it logs `false` then that's the problem.

**Comment by michaelbromley** [comment]
Hi, closing this because it's stale now. If any similar issue still comes up on the latest version, open a new issue :+1
