### ISSUE TITLE
[Vendure Demo] Admin UI not able to login

### ISSUE THREAD

**Issue by tiagomoucho3** [vendure-ecommerce/vendure#497]
Hello!

I'm not able to login into the admin UI.
The login credentials superadmin are invalid.

![Screenshot_2](https://user-images.githubusercontent.com/25727437/95971851-a45d3b00-0e09-11eb-912e-71d0d25bbce5.png)

**Comment by samundra** [comment]
@tiagomoucho3 Can you please share some context.

- What did you do?
- Was this page working before and then upgrade broke it?
- How did you end up with this state ?

**Comment by michaelbromley** [comment]
This is the public demo. I checked it and can confirm. I guess someone changed the password of the superadmin account. I should probably disable that somehow!

**Comment by samundra** [comment]
A new user role called "demo" that can only showcase the functionalities ?

**Comment by michaelbromley** [comment]
Maybe, but I'd like users to be able to do things like creating channels which is limited to superadmins currently. Thinking of overriding the `updateAdministrator` mutation to disallow changes.

**Comment by michaelbromley** [comment]
Added a plugin to prevent updates to the superadmin account: https://github.com/vendure-ecommerce/vendure-demo/commit/248a03731eb2983d80d70894eab9cc6217625f21
