### ISSUE TITLE
Custom Payment States | Keeping Payment In Created State

### ISSUE THREAD

**Issue by ekoto4** [vendure-ecommerce/vendure#507]
**Is your feature request related to a problem? Please describe.**
It is impossible to return an order to one of the active states (I can tell this is by design). However this has the unfortunate side effect that of a user "abandons" a payment (i.e. changes his mind and cancels, or just doesn't complete a payment). The user is stuck because the order is no longer active. The only option is the cancel the entire order.

**Describe the solution you'd like**
Solution 1. We are able to keep a payment in the "Created" state. which will keep the Order in the active state.
Solution 2. Additionally to make it match similar to Order states, we are able to define custom payment states before "Authorized" or "Settled". These states would not effect the order state and thus keep the order active.

**Describe alternatives you've considered**
The two solutions above are all that I came up with. Im indifferent to either as they would both help my situation. However, Solution 2 follows the Custom Order State pattern and I believe is more future proof, is more adaptable and is more customizable. 

**Additional context**
This change would help me implement Flutterwave standard payment. Currently, best path scenarios work fine, however canceled and abandoned payments are blind and hard to deal with given the current implementation.

This changed needed for payment providers that provide links and we have little control over the the payment link. 

In the backend, we receive a webhook for successful transactions and failed transactions (bad credit card) - However, canceled, and abandoned transactions are not sent via webhook.

In the frontend, we can tell if a payment was successfully competed or not via the payload added to the redirect url. (So by all means, frontend and backend will match at on successful payment.)Thus if a user abandons a payment, it would be easy to transition back to the "AddingItems" state. Something that wouldn't be allowed now as the Order would be in either the "PaymentAuthorized" or "PaymentSettled" state.

**Comment by michaelbromley** [comment]
Thanks for the detailed description. I agree that option 2 (configurable Payment state machine) is preferable, due to being more consistent with other parts and also more flexible.

**Comment by ekoto4** [comment]
Yeah I agree. I was also taking a look at the Custom Fulfillment Process in: https://github.com/vendure-ecommerce/vendure/pull/427/files. Something like CustomPaymentProcess should very doable. 

I would like to work on this/contribute to this over the next week and see if I can make a pull request.

**Comment by michaelbromley** [comment]
Exactly, it would work just like the Fulfillment process. You are welcome to contribute. Make sure you make any PRs against the `next` branch.

**Comment by michaelbromley** [comment]
Related PR: #539
