### ISSUE TITLE
"Created" state for Fulfillment and Order state machines with immediate transition to currently initial states

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#510]
**Is your feature request related to a problem? Please describe.**
Currently we are not able to hook an action to creation of Fulfillment and Order as state machines just start existing with Pending and AddingItems states without firing transition event.

**Describe the solution you'd like**
- Add a new "Created" state to the Fulfillment state machine, which immediately gets transitioned to "Pending". 
- Add a new "Created" state to the Order state machine, which immediately gets transitioned to "AddingItems".
These new states will fire transition event upon creation that we can subscribe to with EventBus.

**Additional context**
E.g. I need to run a process when admin "Fulfills order" and there is no hook to be able to do this.

**Comment by jonyw4** [comment]
I need this feature too, after I sent my PR to Vendure that I realize that problem that @chladog describes.
