### ISSUE TITLE
ChannelAware ProductVariants

### ISSUE THREAD

**Issue by hendrikdepauw** [vendure-ecommerce/vendure#519]
**Is your feature request related to a problem? Please describe.**
Taking the Vendure demo data as an example, we would like to setup multiple sales channels with different product availability. Currently we can assign, for example, the laptop to a specific sales channel. However, there is no option to limit the laptop to only variants with 16GB RAM on a sales channel.

**Describe the solution you'd like**
We would like to have finer control over what products are available on a specific Channel. This would be achieved by making the ProductVariant entity ChannelAware as well. This would work exactly the same as it currently does for the Product entity. The Channels of a Product would then become a combination of all the Channels of the different ProductVariants.

**Describe alternatives you've considered**
We could duplicate a Product and attach only some ProductVariants to it and then assign this duplicated Product to another Channel. Duplicating data is obviously not something we would like to do.

**Comment by michaelbromley** [comment]
> The Channels of a Product would then become a combination of all the Channels of the different ProductVariants.

Are you proposing to get rid of the ChannelAware property of Product, in favour of deriving it from the ProductVariants? Or have both entities be ChannelAware?

**Comment by hendrikdepauw** [comment]
My first thought was to have both of them ChannelAware, but I'm not sure anymore if that is really necessary. Having just the ProductVariants be ChannelAware would achieve the same goal.
I would also leave the current AssignProductsToChannel mutation, but also provide an AssignProductVariantToChannel mutation.

**Comment by michaelbromley** [comment]
I would agree that it would only be necessary to make ProductVariants ChannelAware in that case.
