### ISSUE TITLE
Logging in with an unverified username returns an unexpected error.

### ISSUE THREAD

**Issue by marwand** [vendure-ecommerce/vendure#523]
**Describe the bug**
According to the developer guide, there are two types of errors:
1-Unexpected errors
2-Expected errors

When a user registers using the registerCustomerAccount mutation and immediately tries to login prior to verifying his account, the login mutation returns an unexpected error. As this is a common error, I believe it should be treated as an expected error.

**To Reproduce**
1. Register a new account
```
mutation Register($input: RegisterCustomerInput!) {
        registerCustomerAccount(input: $input) {
            ... on Success {
                success
            }
            ...ErrorResult
        }
    }
fragment ErrorResult on ErrorResult {
  errorCode
  message
}
```

2. Login with the newly registered account
```
mutation SignIn(
  $emailAddress: String!
  $password: String!
  $rememberMe: Boolean!
) {
  login(username: $emailAddress, password: $password, rememberMe: $rememberMe) {
    ... on CurrentUser {
      id
    }
    ...ErrorResult
  }
}

fragment ErrorResult on ErrorResult {
  errorCode
  message
}

```

3. The returned error is of the following format
```
{
  "errors": [
    {
      "message": "Please verify this email address before logging in",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "extensions": {
        "code": "NOT_VERIFIED"
      }
    }
  ],
  "data": null
}
```
**Expected behavior**
Something on the order of:
```
{
  "data": {
    "login": {
      "errorCode": "UNVERIFIED_ACCOUNT_ERROR",
      "message": "Please verify this email address before logging in."
    }
  }
}
```

**Environment:**
 - @vendure/core version: 0.16.1

**Comment by michaelbromley** [comment]
Thanks for the report and you are totally correct! This was already noted by someone else in #500 and will be fixed in the next release.
