### ISSUE TITLE
Add customField in Fulfillment

### ISSUE THREAD

**Issue by jonyw4** [vendure-ecommerce/vendure#525]
**Is your feature request related to a problem? Please describe.**
I have some Vendure plugins to create labels to ship a fulfillment and I need to save that information in Fulfillment.

**Describe the solution you'd like**
Add _customField_ in _Fulfillment_ just like _Orders_.

**Comment by michaelbromley** [comment]
I'm going to add custom field support now, and display custom field data in the fulfillment card in the OrderDetail view of the Admin UI, but I will not make any UI/API changes for inputting custom field data until I've spent more time thinking about #529.

So for now you'll be able to programmatically set and query the custom field values in your own plugin code.

**Comment by jonyw4** [comment]
@michaelbromley Ok, For me for now will resolve. All fields that I need to put in Fulfillment will be used internally by the system
