### ISSUE TITLE
Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

### ISSUE THREAD

**Issue by jreeve-nl** [vendure-ecommerce/vendure#532]
**Describe the bug**
Attempting to launch the web app results in:  "Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm." 

**To Reproduce**
npx @vendure/create my-app

**Expected behavior**
Starts the services.

**Environment (please complete the following information):**
 - @vendure/core version:  0.16.2     
 - Nodejs version.   15.0.1
 - Database (mysql/postgres etc):  both SQLite and the SQLite.js

**Additional context**
It's almost certainly a problem with my environment because no-one else is complaining and also it sounds like some dependency conflict of graphsql module versions.  I am clearly not a Node.js person :-)

**Comment by jreeve-nl** [comment]
Oh and if someone can help point out what the problem is then I'll surely submit a patch to the build system to detect this condition or a superclass of this condition.

**Comment by michaelbromley** [comment]
I think the root cause of this kind of error is when there are multiple `graphql` packages in your dependency tree, and those versions don't play well together.

Can you run `npm ls graphql` and paste the output?

**Comment by michaelbromley** [comment]
Those errors don't look very promising. This might be related to you using Node v15. Could you try with v12 or v14 and see if things work better?

**Comment by jreeve-nl** [comment]
MacOS homebrew install.

I'm considering never doing dev work on anything other than a common Linux
distro 🙂

**Comment by javib94** [comment]
I had the same problem, changing Node version to v12 worked for me, I didn't try with v14. Thanks!

**Comment by abnemo** [comment]
Hello guys,

I tried latest v14 on latest MacOS and it worked. After updating to latest npm (v7.5.3) got the above mentioned problem.

Thanks!

**Comment by michaelbromley** [comment]
I think this is related to the way npm v7 handles peerDependencies. For now, avoid npm v7, i.e use v6 or yarn.

**Comment by megataps** [comment]
I got the same problem on Node `v16.0.0` and npm  `7.11.1`

**Comment by michaelbromley** [comment]
This is currently blocked because of an upstream regression in the nestjs/graphql package (https://github.com/nestjs/graphql/issues/1468) which prevents me from updating to the latest version. As a result, installing with npm v7 will result in multiple conflicting versions of the `graphql` package in the dependency tree, giving the error described above.

As soon as the Nestjs/graphql issue is resolved we can update that package and this issue should also resolve at that point.

**Comment by michaelbromley** [comment]
Added a work-around which allows the update of the nestjs/graphql package. This solves the npm v7 issue!
