### ISSUE TITLE
Edit Collection customFields on Admin UI

### ISSUE THREAD

**Issue by jonyw4** [vendure-ecommerce/vendure#545]
**Is your feature request related to a problem? Please describe.**
I need to edit collection _customFields_ in the _Admin UI_

**Describe the solution you'd like**
Add _customFields_ in _Collection page_

**Comment by jonyw4** [comment]
Related #544

**Comment by michaelbromley** [comment]
Hi, this is already implemented:

![colletion-custom-fields](https://user-images.githubusercontent.com/6275952/98268522-eb63c980-1f8c-11eb-8e9c-10bdcc62af16.jpg)

Can you double-check your config?

**Comment by jonyw4** [comment]
Oh sorry, my bad. I didn't configure correctly. Sorry
