### ISSUE TITLE
Extend CustomFieldConfig by "config" property

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#547]
**Is your feature request related to a problem? Please describe.**
Currently there is no property in [CustomFieldConfig](https://www.vendure.io/docs/typescript-api/custom-fields/) that would allow developer to pass along some data/config object that is needed for example by custom UI component - [CustomFieldControl](https://www.vendure.io/docs/plugins/extending-the-admin-ui/custom-field-controls/). 

**Describe the solution you'd like**
New property `config` OR `data`.
Usually the configs are objects so I propose JSON type for this property, though string would work as well as we can stringify JSON.

**Describe alternatives you've considered**
In the meantime I pass data in "description field, which is not the best soltution (cannot have actual description, and it's localized string)

**Additional context**
E.g. I want to make a custom UI component for customField which needs "schema" and some "config" options.

**Comment by michaelbromley** [comment]
I would like to incorporate this into ideas discussed in #415, so this `data` object would live under a `ui: { ... }` property, since it pertains specifically to the Admin UI representation of the custom field.

**Comment by martijnvdbrug** [comment]
Completed in #415
