### ISSUE TITLE
Plugin UI extensions

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#55]
## UI extensions

Certain plugins may imply extensions to the admin ui. Examples:

* An Algolia search plugin with a UI form for entering the API key
* A recommendations engine plugin with a UI for configuring relationships

## Ideal developer experience

The ideal dev experience would be to `npm install @vendure/some-plugin`, add that to the VendureConfig.plugins array, and then the admin-ui is immediately extended without any further configuration.

## Implementation

There are a couple of possible ways to extend the admin ui:

1. Define a data format for forms which allows dynamic forms to be generated based on a schema made available by the plugin. There would be a GraphQL query which exposes these custom forms / buttons etc. This would work for more simple cases.
2. Some form of lazy-loading an entire new Angular module or component. Currently this does not seem possible, but [this comment](https://github.com/angular/angular-cli/issues/9343#issuecomment-439345350) suggests that it will be a distinct possibility once the Ivy renderer ships. 

A good first step would be to go with #1 and define a basic format which allows a plugin to define:

* An entry in the nav menu
* A list of form fields and types (similar to CustomFields)
* A GraphQL mutation to be executed to submit the form

_Originally posted by @michaelbromley in https://github.com/vendure-ecommerce/vendure/issues/24#issuecomment-448365096_

**Comment by agustif** [comment]
I don't know if you use Heroku for deployment or are familiar with it's products.

I had a great DX while working on primeCMS with the way heroku add-ons handle this with custom ENV VARS, which the add-on automatically prepopulates on activation.

Easy to understand/modify if needs custom tailoring, and wouldn't require you to think about the UI innitially while on alpha/beta, a nice way to ship plugins fast.

You can always document thihs on the docs and leave it to the implementator to pick and choose it's extensions/pluginns

**Comment by michaelbromley** [comment]
> I don't know if you use Heroku for deployment or are familiar with it's products.

Nope, although I recently started using Dokku which claims to be similar.

I'm not sure I fully understand your proposal. Currently we have plugins already working, and they are added and configured in the `VendureConfig` object (https://www.vendure.io/docs/configuration/vendure-config/#plugins). 

This issue is specifically about the situation where a plugin needs some UI component to be added to the admin ui application. Does your proposal apply to this use-case? If so, please explain again cos I didn't get it 🙃

**Comment by michaelbromley** [comment]
### Implementation idea

Got this good idea from discussing the problem with a friend:

* Plugins can provide the source of Angular modules which can then extend the admin UI. 
* When the admin-ui-plugin bootstraps, it looks at the config for any plugins which register a UI extension. If so, it re-builds the UI Angular app with the extensions. This build is then cached so it does not have to be re-built each time the server starts.

This solution has the following advantages:

1. No need to mess around with (likely hacky) solutions for loading components dynamically at run-time
2. We can provide a "plugin UI sdk" which provides styling and common components (e.g. shared module) to make plugin development simpler
3. Plugins will have access to the shared services of the Admin UI (state, apollo client cache etc)

Challenges:

1. What is the minimum source + tooling we need to ship in the admin-ui-plugin package to allow a re-build from source? Or just have it pull in the Angular CLI?
2. Will probably need to re-architect the Admin UI app a little to make it easily extensible.
3. How to extend translations (merge plugin-provided translations with the existing translation files).

**Comment by michaelbromley** [comment]
With the above commits, the UI extensions work well as Angular modules provided to the AdminUiPlugin.

Here is the next part to solve:

## Extending the UI nav menu & adding links

Let's say we created a plugin ProductReviewsPlugin. This plugin adds a new ProductReview entity and  allows reviews to be written and associated with Products.

The UI for this calls for 2 new views: a master ReviewsList listing all reviews with their status (pending, approved, rejected) and then also a ProductReviewsList listing all reviews pertaining to a given Product.

In order for the administrator to access those views we need to add some links to the UI:

1) A new item in the NavMenuComponent (the main nav on the left) linking to the master reviews list.
2) A new link in the ProductDetailComponent linking to the Product-specific reviews

### Prior Art

[Sylius defines preset menu locations](https://docs.sylius.com/en/1.5/customization/menu.html):
```php
sylius.menu.shop.account # For the menu of the MyAccount section in shop
sylius.menu.admin.main # For the Admin Panel menu
sylius.menu.admin.customer.show # For the buttons menu on top of the show page of the Customer (/admin/customers/{id})
sylius.menu.admin.order.show # For the buttons menu on top of the show page of the Order (/admin/orders/{id})
sylius.menu.admin.product.form # For the tabular menu on the left hand side of the new/edit pages of the Product (/admin/products/new & /admin/products/{id}/edit)
sylius.menu.admin.product.update # For the buttons menu on top of the update page of the Product (/admin/products/{id}/edit)
sylius.menu.admin.product_variant.form # For the tabular menu on the left hand side of the new/edit pages of the ProductVariant (/admin/products/{productId}/variants/new & /admin/products/{productId}/variants/{id}/edit)
sylius.menu.admin.promotion.update # For the buttons menu on top of the update page of the Promotion (/admin/promotions/{id}/edit)
```

and uses the [KnpMenu library](https://github.com/KnpLabs/KnpMenu) to allow the developer to add child menu items in those locations.

### Proposal

I propose a system similar to Sylius where we have a pre-defined set of locations in which custom nav links may be defined.

This can be achieved by creating a `CustomNavService` which can be injected into the plugin's NgModule's APP_INITALIZER provider function to set up the custom nav. Example of how this might look:

```ts
@NgModule({
  imports: [ SharedModule],
  providers: [
    // ...
    { provide: APP_INITIALIZER, useFactory: addCustomNav, deps: [CustomNavService], multi: true },
  ]
})
export class ProductReviewPluginModule { }

export function addCustomNav(customNavService: CustomNavService) {
    customNavService.addNavItem({
       location: 'mainNav.catalog',
       routerLink: ['/extensions/reviews'],
       label: 'Product reviews',
      // other properties for styles etc.
     });
}
```

Meanwhile in the admin ui code there would be a corresponding component, `CustomNavComponent` which takes a location string as an input and then displays all configured custom nav items for that location:

```html
    <section class="nav-group" *vdrIfPermissions="'ReadCatalog'">
            <input id="catalog" type="checkbox" />
            <label for="catalog">{{ 'nav.catalog' | translate }}</label>
            <ul class="nav-list">
                <li>
                    <a class="nav-link" [routerLink]="['/catalog', 'products']" routerLinkActive="active">
                        <clr-icon shape="library" size="20"></clr-icon>
                        {{ 'nav.products' | translate }}
                    </a>
                </li>
                 
                <!-- the other default Catalog menu items -->
            </ul>
            <vdr-custom-nav-items location="mainNav.catalog"></vdr-custom-nav-items>
        </section>
```

**Comment by michaelbromley** [comment]
This is done! Docs here: https://www.vendure.io/docs/developer-guide/plugins/extending-the-admin-ui/

Future improvements could include a simplified wrapper for specifying custom controls (it is a bit ugly to use the APP_INITIALIZER stuff. All that could be hidden in a function we provide).
