### ISSUE TITLE
Multiple Channels - Product Not Displayed

### ISSUE THREAD

**Issue by SushamaTangella** [vendure-ecommerce/vendure#556]
**Describe the bug**
Products are not displayed in multiple channels.

**To Reproduce**Steps to reproduce the behavior:

1. Goto ‘/admin/settings/zones’
2. Click on ‘ CREATE NEW ZONE’
3. Enter Name=”US”
4. Click on ‘CREATE ZONE’
5. Goto 'admin/catalog/products.'
6. Click on ‘NEW PRODUCT’
7. Product name=”Product1”, Add Product details 
8. Click ‘CREATE’
9. Repeat the above steps and create “Product2”, “Product3”, “Product4”
10. Goto 'admin/catalog/products.'
11. You will see all 4 products displayed.
12. Go to ‘/admin/settings/channels’
13. Click on ‘CREATE NEW CHANNEL’
14. Enter Code= “Channel-1” 
15. Pick “US” under ‘Default tax zone’ and ‘Default shipping zone’
16. Click ‘CREATE’
17. From the Dropdown (Next to username) pick ‘Channel-1’
18. Goto 'admin/catalog/products.'
19. Click on ‘NEW PRODUCT’
20. Product name=”Product5”, Add Product details 
21. Click ‘CREATE’
22. Goto 'admin/catalog/products.'
23.  Product5 is NOT displayed
24. From the Dropdown (Next to username) pick ‘Default channel’
25. Goto 'admin/catalog/products.'
26. Click ‘Edit’ next to “Product1”
27. Click ‘ASSIGN TO CHANNEL’
28. From the Channel dropdown pick ‘Channel-1’
29. Click ‘ASSIGN TO CHANNEL-1’
30. From the Dropdown (Next to username) pick ‘Channel-1’
31. Goto 'admin/catalog/products.' (Click on Products under Catalog)
32. NO products are displayed.

**Expected behavior**
Expected to see products added to channels and products from default channels assigned to channels to be displayed in the channels.
 
**Environment (please complete the following information):** 
- @vendure/core version: - Nodejs version
 - Database (mysql/postgres etc):

**Additional context**

1. Restart Admin server
2. From the Dropdown (Next to username) pick ‘Default channel’
3. Go to 'admin/catalog/products.'
4. NO products are displayed.
5. Check Database – all products exist in the database.
6. From the Dropdown (Next to username) pick ‘Channel-1”
7. “Product5” is displayed (This is the new product that was added to the channel)
8.  Click on “Actions” -> “Delete” next to “Product5”
9.  Go to ‘/admin/settings/channels’
10. Click on “Actions” -> “Delete” next to “Channel-1”
11 Restart Admin server
12. Goto 'admin/catalog/products.'13. NO products displayed.

**Comment by michaelbromley** [comment]
Thanks for the report! Please just provide this info that was omitted:

@vendure/core version: 
Nodejs version:
Database (mysql/postgres etc):

**Comment by SushamaTangella** [comment]
@vendure/core version: 0.16.1 
Nodejs version:12
Database (mysql/postgres etc): ppstgres

**Comment by michaelbromley** [comment]
I can reproduce some but not all the issues in the latest version. Probably related to #613. Will investigate for next patch release.
