### ISSUE TITLE
admin-ui: Order List Custom filter persistence

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#561]
**Is your feature request related to a problem? Please describe.**
Now users can set up quite complex filters by themselves. It's tedious for them to set the filters they need to use on daily basis on every refresh/navigation to the Custom Filters.

**Describe the solution you'd like**
- store current filter settings as _URL query parameter_ and load the filters from it on navigation
- additionally store latest settings in users persistence either in DB or localStorage (Personally would lean towards localStorage) and load these (to URL query & filter settings) when toggling/navigating to Custom Filters view.

With implementation of both of these features, users would be able:
- save their favorite filter settings as a bookmark
- share their filters with other users
- keep last set filter when navigating out of Custom Filters view
- keep last set filter when reloading the application

**Comment by michaelbromley** [comment]
I agree with all of the above.

Related: I've been thinking of adding a new field to the Administrator type which allows storage of arbitrary UI settings. This would allow e.g. filter settings to be persisted to the backend, meaning they are available even when logging in on another device. The motivation for this concept was being able to customize what widgets to display on the dashboard. But it also would fit this issue nicely as well.

**Comment by chladog** [comment]
As these settings will be stored as stringified JSONs probably then compability with coming features in future releases and merging the settings without loosing the existing settings should be considered.
