### ISSUE TITLE
(Partial) Fulfillment Flow Refinement

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#565]
**Describe the bug**
In a (partial) fulfillment flow there are few refinements needed:
![fulfillments](https://user-images.githubusercontent.com/15977485/99719093-26e1b600-2aac-11eb-8c7d-3ed23a296569.JPG)

### Cancellation of fulfillment
1. Make a Fulfillment
2. Cancel the Fulfillment
3. Observe that you cannot fulfill those items that were part of cancelled fulfillment.

**Expected behavior**
After cancellation of fulfillment the status of items should be set as unfulfilled again, so we can make a new fulfillment with them.- just because we cancel fulfillment doesn't mean we do not want to try to fulfill it again in the future.
_For example we had a inventory mistake and we need to wait until restock, therefore we want to cancel fulfillment (and programmatically cancel that packet with delivery provider API) and make new one in the future._
From my investigation after cancellation of fulfillment the OrderItem in DB still keeps "fulfillmentId" of that fulfillment. When I removed fulfillmentId from it then whole fulfillment in AdminUI disapears (missing visual feedback about cancelled fulfillments this way), though I was able to fulfill item again.

### Partial Delivery
1. Make a fulfillment, but keep some items **unfulfilled** (Partial fulfillment)
2. Mark that fulfillment as **Delivered**
3. Observe that "Fulfill order" button is disabled, even though there are still items to be fulfilled

**Expected behavior**
In anytime there are unfulfilled items and order is in Partially Shipped or Partially Delivered state we should be able to continue with another fulfillments.
From my investigation this is just Admin UI bug as when I removed "disabled" attr on the button in dev tools I was able to create the fulfillment.

**Environment (please complete the following information):**
 - @vendure/core version: v0.17.0
 - Database (mysql/postgres etc): postgres

**Comment by michaelbromley** [comment]
**Cancellation of fulfillment**: This is an interesting problem that is not possible to fix without changing the schema I think. The data model assumes that each OrderItem has a relation to only 1 Fulfillment. Therefore when cancelling, we would have no option but to remove that reference to allow the item to be assigned to a new Fulfillment later. But as you found, once this relation is removed, there is nothing else linking that cancelled Fulfillment to the Order.

So I think the solution would therefore be to make the `OrderItem.fulfillment` into a many-to-many relation, so we can keep a reference to the cancelled Fulfillment whilst also allowing a new one to be added.

In this case I would leave this part of the issue to the next minor version.

**Partial Delivery** This is indeed just a UI bug and can be fixed right away.

**Comment by chladog** [comment]
Understand. If you like to fix the orderflow until next minor, then imho invisible cancelled fulfillments is better behavior than unability to re-fulfill items... though personally I'm not blocked by this for time being.
