### ISSUE TITLE
Option to make tax category default

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#566]
**Is your feature request related to a problem? Please describe.**
We can't set the "default" tax rate that would be always selected when we create a new product variant.

**Describe the solution you'd like**
In tax rate settings screen an option to toggle which rate is default and use that value as initial in product variant editation.

**Describe alternatives you've considered**
Currently the order is alphabetically sorted, so for now it's possible to prefix the rate names with numbers representing the "priority".
This is definitely low priority, but handy enhancement for admin effieciency.

**Comment by michaelbromley** [comment]
Just to clarify, are you referring to tax category, rather than tax rate?

**Comment by chladog** [comment]
Yes, tax category in Product Variant editor.
![Screenshot_20210129-123432_Chrome](https://user-images.githubusercontent.com/15977485/106270526-6bb56600-622e-11eb-956c-c96260004bdb.jpg)
