### ISSUE TITLE
Promotions: add new action to discount order by $ { discount }

### ISSUE THREAD

**Issue by andrewlreeve** [vendure-ecommerce/vendure#579]
**Problem**
The promotional coupons in core have actions to give customers a percentage discount on their order or against a product. It is also common to offer customers coupons with a monetary value instead of a percentage off an order or product. I.e $10 off when you spend over $50.

**Solution**
Create new actions that allow for a monetary variable as the discount to be applied to an order or product.

**Alternatives**
None. This functionality is available in Shopify and Woocommerce core and I believe Vendure would benefit from including it in core.

Monetary value coupons (with minimum spend) are useful when you're trying to incentivise an order value, without causing a linear drop in margin for higher value baskets.

**Comment by michaelbromley** [comment]
Yep, this is already created and coming in the next minor release 👍

**Comment by andrewlreeve** [comment]
Great! Really impressed by Vendure and looking forward to the first RC.

**Comment by michaelbromley** [comment]
Thanks! Hoping to get there in the next ~month or two.
