### ISSUE TITLE
Allow Lists to be sorted / order by

### ISSUE THREAD

**Issue by Logic-Bits** [vendure-ecommerce/vendure#584]
Hi!

is it possible for lists to be sorted?
I cannot sort any requests via API if those are joint properties.

parseFilterParams => Will only allow filtering for columns in that entity.
I would like to be able to sort Customer.addresses for example.

Any Idea?

Thanks!

**Comment by michaelbromley** [comment]
Hi,

There are _a few_ list fields which can be filtered, e.g. `Customer.orders` or `Order.history`, but in general plain arrays are used for fields where there are multiple child objects. 

So at the moment, for most of these fields you'd have to do any sorting/filtering in memory on the client side.

If this proves particularly problematic for certain use-cases, please detail those and we can consider adding support for list filtering & sorting for that case.

**Comment by Logic-Bits** [comment]
Hi, thanks for the quick response!

Once customers have a couple of hundred orders then local order / sort will not be an option anymore.
TypeORM will load the relations correctly, but the order / sort is done before that in ListQueryBuilder.

The parseSortParams would need to be extended to allow joined relations and moved after parseFilterParams and joinEagerRelations (list-query-builder.ts).

I´d like to help but my knowledge for all the things to look out for and consider is not good enough yet.

Thanks!

**Comment by michaelbromley** [comment]
> Once customers have a couple of hundred orders then local order / sort will not be an option anymore.

Yes, that's exactly why the `Customer.orders` field _is_ sortable, filterable & paginated. Or am I misunderstanding something about what you mean here?

**Comment by Logic-Bits** [comment]
Oh ok, I know what you mean. In your case you actually load the orders in a seperate step.

Lets take that example:


    async findByCustomerId(
        ctx: RequestContext,
        customerId: ID,
        options?: ListQueryOptions<Order>,
    ): Promise<PaginatedList<Order>> {
        return this.listQueryBuilder
            .build(Order, options, {
                relations: [
                    'lines',
                    'lines.items',
                    'lines.productVariant',
                    'lines.productVariant.options',
                    'customer',
                    'channels',
                ],
                channelId: ctx.channelId,
                ctx,
            })
            .andWhere('order.customer.id = :customerId', { customerId })
            .getManyAndCount()
            .then(([items, totalItems]) => {
                items.forEach(item => {
                    item.lines.forEach(line => {
                        line.productVariant = translateDeep(line.productVariant, ctx.languageCode, [
                            'options',
                        ]);
                    });
                });
                return {
                    items,
                    totalItems,
                };
            });
    }

Here I would like to get all the Orders but ordered by "lines.items.createdAt"

As far as I understand thats not possible in the ListQueryBuilder currently.

**Comment by michaelbromley** [comment]
Ah right, so if I understand you correctly, you want to sort/filter a list by a property of one of its relations, e.g.

"Give me the first 10 Customers where they have an Address with a postalCode which equals `'12345'`"

In that case, no this is not supported by ListQueryBuilder.

Such functionality _might_ be feasible to implement, but I suspect it would be quite complex to get right.

I'd suggest that the starting point would be to precisely define a desired API at the GraphQL level. How, for example, would you image we specify the above example query? Maybe something like:

```graphql
query {
  orders(options: {
    filter: {
       address_postalCode: {
         eq: "12345"
       }
    }
 }
}
```

**Comment by Logic-Bits** [comment]
Correct!

or for sort smth like this in the options:

```
sort: [
    {field: "address_postalCode", order: "DESC"}
[
```
or similar to existing sort:

```
sort: {
    address_postalcode: SortOrder.DESC
}
```

**Comment by martijnvdbrug** [comment]
This can now be done using a [custom property map](https://docs.vendure.io/reference/typescript-api/data-access/list-query-builder/#custompropertymap)
