### ISSUE TITLE
Global Config

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#59]
Currently there is no place to store global user-configurable settings. We have the `VendureConfig` object, but that is static and requires a modification of the app source.

There are a class of global config settings which the administrator may need to update, such as available languages (see #49). For this we'll need a central config table in the database. There are a couple of ways to store this:

### 1) A single Config entity

Let's say we have a `GlobalConfig` entity with the configurable properties hard-coded into it:

```ts
@Entity()
class GlobalConfig {
  @Column('simple-array')
  availableLanguages: LanguageCode[];
  
  // ... etc  
}
```

Additional properties could be added using the existing CustomFields mechanism. This would mean that the table columns would grow for each additional property added. Also there would be no way to see when (and by whom) an individual property was updated.

### 2) One entity per property

Another way to do it would be to have a `ConfigSetting` entity:

```ts
@Entity()
class ConfigSetting{
  @Column()
  name: string;
  
  @Column('simple-json')
  value: any;
}
```

This would allow finer-grained control over the settings, such as tracking when a setting was changed and by whom, and also potentially allow permissions on a per-property basis.

### Comments

* Here is a discussion of the two approaches: https://stackoverflow.com/questions/2300356/using-a-single-row-configuration-table-in-sql-server-database-bad-idea
* Another https://softwareengineering.stackexchange.com/questions/163606/configuration-data-single-row-table-vs-name-value-pair-table

Reading through the above discussions, the general consensus is that:

* Single row is simpler to work with and has the advantage of proper data types in the DB
* Multiple rows (also named "Entity Attribute Value" or EAV) is more flexible but harder to work with in code and is "stringly typed" meaning types must be coerced after reading from the DB. Is we just JSON.stringify/parsed everything though, that would not be such a big deal.

We will go with the single row approach because:

1. I do not foresee a huge number of global properties being needed
2. The existing CustomFields mechanism can be used to make adding new properties very simple both on the  server side and also in terms of generating forms for the admin-ui.
3. There are plans to extend the CustomFields in various ways (access controls, validation logic etc) which would all work well for the purpose of global config too.

**Comment by SpyrosMourelatos** [comment]
Thank you for the awesome job on this I would just like some documentation on this feature , I am totally new with vendure and I managed to edit my vendure-config.js and add a line like this :
`customFields: {GlobalSettings: [{ name: 'royalMailId', type: 'string' }],},`
Now this custom field is visible on the admin panel and on the admin-api  graphql with a query like :
`query{globalSettings{  customFields{royalMailId}  }}` 
Unfortunately I don't believe these info is inside the shop-api so I don't think it can be accessed via any front end request.
Am I missing something ?
What is the correct procedure I should follow if I want a global setting to be **visible** on the front end and **editable** from the non-developer admin?Thank  you in advance :)

**Comment by michaelbromley** [comment]
Hi @SpyrosMourelatos 
The solution here is to implement a custom graphql query in the shop api as described here: https://www.vendure.io/docs/plugins/plugin-examples/extending-graphql-api/#adding-a-new-query-or-mutation

This allows you to expose only the data that is necessary for the storefront, rather than the entire GlobalSettings object.
