### ISSUE TITLE
Search box for channels drop-down of superadmin

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#594]
Add search box for channels drop-down in top left of the superadmin.![IMG_20201220_105005_155.jpg](https://user-images.githubusercontent.com/29729738/102705587-666d0f00-42b1-11eb-8fe1-c926a3fa6584.jpg)

**Comment by michaelbromley** [comment]
How many channels do you have or expect to have?

**Comment by BeepLoveKarki** [comment]
I am planning to have one channel each seller. Is there any limitations or so on that?

**Comment by michaelbromley** [comment]
No, there is no theoretical limit, but I guess it depends a little on what order of magnitude of sellers you eventually need to support.
