### ISSUE TITLE
Auto refresh on channel change

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#595]
The logistics channel doesn't auto refresh data on changing channel. We need to reload the page. Hope it is fixed.

Also, same thing to be analysed on every channel specific data. Important thing for superadmins.

**Comment by michaelbromley** [comment]
> The logistics channel doesn't auto refresh

Which exact route are you referring to?

**Comment by BeepLoveKarki** [comment]
I mean this route : https://demo.vendure.io/admin/settings/shipping-methods
