### ISSUE TITLE
Can't delete channel: Foreign key violation

### ISSUE THREAD

**Issue by rohanrajpal** [vendure-ecommerce/vendure#597]
**Describe the bug**

Sometimes I am not able to delete a channel. Not sure about the exact steps to reproduce. 

**To Reproduce**
1. Go to Channel
2. Click on Actions->Delete
![image](https://user-images.githubusercontent.com/7023147/102755102-f5525800-4393-11eb-9351-30289250a3f3.png)

**Expected behavior**

The channel should be successfully deleted

**Environment (please complete the following information):**
 - @vendure/core version: 0.17.2
 - Nodejs version: 12.20
 - Database (mysql/postgres etc): Postgres

**Additional context**
This issue was discussed on slack here
https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1608381652092800

**Comment by michaelbromley** [comment]
This issue relates to a version of Vendure that is no longer supported. If the issue persists in the latest version, please open a new issue.
