### ISSUE TITLE
Admin UI's Manage Variants page not working properly

### ISSUE THREAD

**Issue by CleverUpEng** [vendure-ecommerce/vendure#602]
**Describe the bug**
Manage Variants page is not working properly for a newly created product:
1) When adding a second option value (e.g. size: large) in order to create a second product variant a modal appears asking for confirmation that I'm sure I want to add this variant, because **it will erase the default one**. This is not expected as one is just trying to add a new variant besides the default one
2) In another case, when I created a product with 2 variants, after deleting one from "Manage Variants", the options table (bottom part of the page) appeared empty (while it should still show the other variant); also the "add option" button doesn't do anything and I see repeated error in the console stating "type error: cannot read property 'enabled' of undefined" and "type error: cannot read property 'price' of undefined".
Also, after these 2 failing tests, I see in the server console this log line: USER_INPUT_ERROR: error.product-variant-option-ids-not-compatible

**To Reproduce**
1. Go to the admin UI
2. Create a new product with 1 variant (for pt. 1 above) or 2 variants (for pt. 2 above)
3. Try to add a second variant (pt. 1) or remove 1 of the 2 variants (pt. 2)
4. See wrong behaviour and error logs described above

**Expected behavior**
Manage variants page should allow to add and remove product variants

**Environment (please complete the following information):**
 - @vendure/core version: 0.16.2
 - Nodejs version: 12
 - Database (mysql/postgres etc): postgres

**Comment by michaelbromley** [comment]
Hi, thanks for the report. 

1. This is currently a limitation of how the Admin API works. It is not possible to add an option to an existing ProductVariant. Therefore, what happens is that if adding 2 new options (e.g. "small", "large") to a product, then the existing ProductVariant is deleted and 2 new ProductVariants are created. Is this a problem in your case?
2. I could not reproduce this on the current master branch. I note you report this on v0.16.2. Are you able to check if you also have a problem on the latest version (v0.18.1 at this time)?

**Comment by CleverUpEng** [comment]
Hi thanks for your reply.
1. Fine, no it is not a huge problem
2. Ok I don't have a working version on 18.1 but I will try in the next days and report back. By the way this happened to me even using the demo implementation

**Comment by CleverUpEng** [comment]
Hi, sorry for the delay, I could update Vendure and test it only now. The problem is still there even in 0.18.2.
I created a product with 2 variants for the "volume" option (e.g. 250 ml and 500 ml), then I went to "manage variants" and there:
- first of all, again, the options are locked and I can't delete them
- but I successfully deleted the second variant
- after that I tried to insert it again and it prompted that it would erase the default variant
- after confirming, the variants table is shown empty
- if I come back to the product variants tab, I see only one variant, so deletion had worked and the new insertion didn't

Further info:
- in the browser logs I keep seeing that message: `ERROR TypeError: Cannot read property 'price' of undefined` and `ERROR TypeError: Cannot read property 'enabled' of undefined`
- in the server console, I see `[Vendure Server] ENTITY_NOT_FOUND: error.entity-with-id-not-found `

Again, when posting the issue I had tried this in the Vendure demo and I found similar behaviour.

Please let me know if I can help by providing more info, a video showing the issue, or anything else.

Thanks

**Comment by michaelbromley** [comment]
OK, thanks for the detailed description, I can reproduce this 👍
