### ISSUE TITLE
Products without variants don't show up in the admin panel

### ISSUE THREAD

**Issue by BitPatty** [vendure-ecommerce/vendure#609]
**Describe the bug**
Products created via the `createProduct` mutation in the admin api don't show up in the admin panel unless a product variant is created.

**To Reproduce**
1. Create a product with the `createProduct` mutation in the admin-api
2. Go to the admin panel
3. The product is not listed but accessible by specifying the id in the url (though the manage variants view is broken)

**Expected behavior**
It should be possible to create a product without a variant or else require a product variant in the `createProduct` mutation.

**Environment (please complete the following information):**
 - @vendure/core version: 0.18.0
 - Nodejs version 14.15.1
 - Database (mysql/postgres etc): mysql

**Additional context**
`Test Product 123` not showing up in the admin panel:
![image](https://user-images.githubusercontent.com/11077852/103467613-1c743680-4d51-11eb-8d29-45d870c0f012.png)

Broken variant management in the admin panel after accessing the product via its id (`/admin/catalog/products/:id`)
![image](https://user-images.githubusercontent.com/11077852/103467600-fb134a80-4d50-11eb-8a7a-fa28ddfddc5a.png)

**Comment by michaelbromley** [comment]
The underlying reason for this is that the product list view uses the `search` query to get the list of products/variants to display. This in turn in based on the search index, which only knows about ProductVariants.

I'm not yet sure how to solve this, though I agree it needs fixing.

**Comment by Ayzrian** [comment]
Can't we add a "default" product variant to the product when we create it?

**Comment by michaelbromley** [comment]
@Ayzrian Yes, this could be a solution, I'd have to explore the implications of this.

**Comment by michaelbromley** [comment]
Hi, since v2.x we no longer use the `search` query to power the admin ui product list. So the search index is definitely not the issue here.

My first idea is that if you are using multiple channels, maybe they got created in a different channel that what you expect?

**Comment by arjunmurali1993** [comment]
> Hi, since v2.x we no longer use the `search` query to power the admin ui product list. So the search index is definitely not the issue here.
> 
> My first idea is that if you are using multiple channels, maybe they got created in a different channel that what you expect?

Ah you were absolutely correct @michaelbromley. I had created a channel for this particular project but all the graphql mutations had been creating products in the Default Channel. Checked that and sure enough, all the products and facets show up in the admin UI.

Thanks!
