### ISSUE TITLE
Codegen needs Upate

### ISSUE THREAD

**Issue by Logic-Bits** [vendure-ecommerce/vendure#611]
Hi!

just letting you know there is a bug in the graphql-code-generator that is fixed in the newest version:

https://github.com/dotansimha/graphql-code-generator/issues/5239

Thanks!

**Comment by michaelbromley** [comment]
Thanks for the report! Didn't run into this yet I guess because we use a lockfile, but I'll make sure to update.

**Comment by michaelbromley** [comment]
Turns out that in the Vendure monorepo we pin all the `@graphql-codegen` dependencies. I tried updating anyway to the latest versions: 

```
    "@graphql-codegen/add": "2.0.2",
    "@graphql-codegen/cli": "1.20.0",
    "@graphql-codegen/fragment-matcher": "2.0.1",
    "@graphql-codegen/typescript": "1.20.0",
    "@graphql-codegen/typescript-compatibility": "2.0.1",
    "@graphql-codegen/typescript-operations": "1.17.13",
```

but now I seem to be running into a new issue: https://github.com/dotansimha/graphql-code-generator/issues/5352, where input array types are incorrectly typesd:

```diff
export type AddCustomersToGroupMutationVariables = Exact<{
  groupId: Scalars['ID'];
-  customerIds: Array<Scalars['ID']>;
+  customerIds: Array<Scalars['ID']> | Scalars['ID'];
}>;
```

**Comment by Logic-Bits** [comment]
Yeah that sucks - I got it to compile that way for now - guess it can only be fixed completly when @graphql-codegen gets fixed.
