### ISSUE TITLE
Default channel data display bug

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#613]
The default channel doesn't show products of all channels on the "Products" page. Also, similar issues may be in other channel-aware parameters. Please check it and manage them all.

**Comment by michaelbromley** [comment]
Did you create the product in the other channel? Or did you create it in the default channel and then assign it to the other channel?

**Comment by BeepLoveKarki** [comment]
I created via different channel assigned different administration account.

**Comment by michaelbromley** [comment]
Thanks. I think this is a bug, I'll fix it for the next patch release.

**Comment by michaelbromley** [comment]
There are 2 parts to this. First, there is a bug in core where no ProductVariantPrice gets created for the Default Channel. This is fixed for the next patch release.

The second problem is detailed in a new issue #629. That issue will be solved at a later time as the solution is more complex and will require some time to get right.
