### ISSUE TITLE
OrderAddress Admin Type missing customFields

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#616]
**Describe the bug**
[OrderAddress](https://www.vendure.io/docs/graphql-api/admin/object-types/#orderaddress) is missing _customFields_.

**Comment by michaelbromley** [comment]
They are added dynamically if the Address entity has custom fields defined: https://github.com/vendure-ecommerce/vendure/blob/ce656c4b4f9402f92c4f3792382a0063d8e69a2a/packages/core/src/api/config/graphql-custom-fields.ts#L65-L73

**Comment by chladog** [comment]
They are working and present in live schema (in playground as well in JS object itself) so I was able to implement my feature. However Visual Studio Code is not aware of "customFields" property so I had to do _(billingAddress as any).customFields_ when creating feature on the backend.

**Comment by michaelbromley** [comment]
Ah okay, so would it be better to keep the field but type is as `JSON` when there are no customFields defined, as we do with other entities?

**Comment by chladog** [comment]
I believe so, it would be dev-friendlier :-)
