### ISSUE TITLE
Entity based (more granular) permissions

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#617]
Having entity-based custom permissions seems to be needed in some cases. So, allowing to restrict permission to admins on pre-built mutations can be a great feature if that is possible.

**Comment by michaelbromley** [comment]
Hi, can you illustrate the idea a bit more fully. It is not totally clear what you mean from that description. 

Ideally provide some usage examples with code (can be pseudo-code).

**Comment by BeepLoveKarki** [comment]
Sure. Let me clarify with an example.

Suppose an admin is not allowed to delete any payment method. Some form of custom permission that can be assigned to him/her for that restriction.

And similar for any other mutations.

**Comment by michaelbromley** [comment]
OK, so are you asking for more granular permissions, so rather than `UpdateSettings`, we have `UpdatePaymentMethod`, `UpdateTaxRate` etc?

**Comment by BeepLoveKarki** [comment]
Yes exact

**Comment by zorox-1** [comment]
any update on this , this will be great help o restrict some setting access . currently its either having all or nothing
