### ISSUE TITLE
Duplicate name for shipping methods

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#618]
Shipping method should not allow using duplicate names as it is now. An application level checking is required.

**Comment by michaelbromley** [comment]
I decided to postpone this to the 1.0 release because it will involve a breaking API change.

**Comment by oneyed** [comment]
shouldn't it be checked at channel level ?

**Comment by michaelbromley** [comment]
@oneyed yes, that's true.

**Comment by michaelbromley** [comment]
This is a little more complex than it first seemed:

Let's say we implement Channel-level uniqueness checks on the "name" and "code" fields. What happens then when we want to assign a ShippingMethod to another channel which already contains an identically-named ShippingMethod? 

Do we just reject it? Force a name change? This part is unclear.

Furthermore, I am wondering whether this should be enforced by the application at all. Why not just leave it to the admin to give a unique name to each method?

Perhaps @BeepLoveKarki you can explain a bit more about the problem with the current functionality?

**Comment by michaelbromley** [comment]
Closing this as it is not planned at the moment.
