### ISSUE TITLE
Mutation call on onclick of custom action bar button

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#622]
I would like to have a feature to call a mutation or query on clicking on action bar button I create pleasd.

**Comment by michaelbromley** [comment]
This is now supported in the `ActionBarDropdownMenuItem` https://docs.vendure.io/reference/admin-ui-api/action-bar/action-bar-dropdown-menu-item#actionbardropdownmenuitem
