### ISSUE TITLE
Misleading start script in Documentation README.md

### ISSUE THREAD

**Issue by manas2297** [vendure-ecommerce/vendure#623]
**Describe the bug**
DB=<mysql|postgres|sqlite> yarn dev-server:start this is the command mentioned to start the server but is a bit confusing as the directory is not mentioned.

**Expected behaviour**
It should be updated to 
```
cd packages/dev-server
DB=<mysql|postgres|sqlite> yarn start
```
or 
From the root package run
```
DB=<mysql|postgres|sqlite> yarn dev-server:start
```

**Comment by manas2297** [comment]
Hey @michaelbromley do you want me to raise an MR for this?

**Comment by michaelbromley** [comment]
@manas2297 sure, go ahead!
