### ISSUE TITLE
Postgres search improvements

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#63]
Consulted with a postgres expert who gave the following tips:

=====

First: use the setweight function to set the weight of a tsvector rather than calculating a bunch of separate ranks

Second: you probably want to precompute the tsvector and store it somewhere (and then index it with a GIN index) for massively improved performance

 Third: you're not passing a regconfig, so it'll be running in simple mode - this might be what you want, but depending on your target audience 'english' might be an appropriate regconfig because it improves matching for english speakers.

 I'd do "second" in a trigger:
```
create function tg_si_tsvector() returns trigger as $$
begin
  new.tsvector = setweight(to_tsvector(si.sku), 'A') || setweight(to_tsvector(si."productName", 'B') || ...
  return new;
end;
```

create trigger _200_tsvector before insert or update on si for each row execute procedure tg_si_tsvector();

(re. using MIN() to aggregate all cols )
Okay so technically you want a combination of all the tsvectors for the variants

I've never needed that before; but you can do it with `CREATE AGGREGATE`; e.g. https://gist.github.com/glittershark/6286217

 Make sure you read the comments

**Comment by agustif** [comment]
I would love to help developing an algolia-plugin-inntegration, should I open an issue? What would be the best approach to get it?

**Comment by michaelbromley** [comment]
@agustif Yes, an Algolia plugin was something I planned (as well as Elastic). Sure, please do open an issue! We can discuss further there.

**Comment by michaelbromley** [comment]
Update: The Postgres DefaultSearchPlugin implementation is workable and "good enough". For serious, performant search, I expect an external search plugin will be used, e.g. Elasticsearch. So putting more time into this is not worth it for now.
