### ISSUE TITLE
Changes lost when switching between views

### ISSUE THREAD

**Issue by oncode** [vendure-ecommerce/vendure#632]
**Describe the bug**
When switching between details and table view within the product variants tab, changes to the images or price fields are lost (other fields seem to preserve changes).

**To Reproduce**
1. Go to a product edit page
2. Go to the variants tab
3. Add asset to a variant
4. Switch to table view
5. Added asset is not there anymore

**Expected behavior**
Images and price should not be lost when switching between detail and table view. Also switching between "Product details" and "Product variants" tab might should give a warning similar when leaving the site.

**Environment (please complete the following information):**
 - @vendure/core version: 0.18.1

**Comment by michaelbromley** [comment]
Thanks for opening this issue - the product editing experience is much smoother with these changes. Changes are now preserved between the product/variants tab and the variant list/table views.
