### ISSUE TITLE
facet values translation not working

### ISSUE THREAD

**Issue by oneyed** [vendure-ecommerce/vendure#636]
**Describe the bug**
It seems that the update of facet values translation isn't working, tested on local and demo env

**To Reproduce**
1. Go edit a facet
2. Change the language other than default
3. edit a value
4. click on update
5. try to change language and it asks to discard or cancel navigation
6. the default language is updated but not the language selected

**Environment:**
 - @vendure/core version: 0.18.1
 - Nodejs version 12
 - Database (mysql/postgres etc): pg

**Comment by michaelbromley** [comment]
Thanks for the report. I can reproduce this and it'll get fixed in the next release.
