### ISSUE TITLE
Extend ConfigArgs with default, nullable, required

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#643]
**Is your feature request related to a problem? Please describe.**
In new Fulfillment handler feature we are using [ConfigArgs ](https://www.vendure.io/docs/typescript-api/configurable-operation-def/config-args/)to define fields. However some fields we want to set by default to some value (e.g. we want to set pickup date to null - currently datetime picker automatically sets "now"), we want to be able to set value of checkbox, as well as we want to be able to have field not mandatory (e.g. manual fulfillment handler now requires filling both input fields before we are allowed to submit fulfillment form).

**Describe the solution you'd like**
Extend ConfigArgs with properties that would allow similiar functionality as CustomFields:
- required: boolean
- nullable: boolean
- defaultValue: null | _based on type of the field_

Additionally set fields of manual fulfillment handler to requred: false, so it's possible to fulfill an order without tracking code.

Additionally currently I use _boolean_ in ConfigArgs. In the form by default the input is checked (though there is no "default" set - so should be unchecked?), however the submit button is disabled, I have to uncheck and check it again to be able to submit the form (maybe the form validation is not run by this time, or is not possible to submit pristine form?)

**Additional context**
v0.18.1

**Comment by michaelbromley** [comment]
I'm working on this now, and I have a question maybe you can clarify:

What's the difference between "required" and "nullable"? Are they not just the inverse of one another in this context?

**Comment by chladog** [comment]
@michaelbromley You are right.
I guess I mixed my thoughts with "undefined vs null" as JavaScript perceives it, but in this case we do not need undefined state, that would be "null". Therefore just either required or nullable is needed.
