### ISSUE TITLE
Allow requirePermission with extendend features

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#651]
Having requirepermission in a way that it can allow all to view that tab except the ones we want, would be a great handy feature for the development of various scenarios.

We can reproduce this with basic algebric operations (or any other way you think).

For example,

requiresPermission: ! ("SuperAdmin")
requiresPermission: ("SuperAdmin") & ("A role")

**Comment by michaelbromley** [comment]
Might be even more flexible to accept a predicate function so you can use whatever logic you like to decide whether to display the menu item. In that case I would probably make a distinct property like `isVisible: () => boolean`.
