### ISSUE TITLE
OrderItemPriceCalculationStrategy not called

### ISSUE THREAD

**Issue by hendrik-advantitge** [vendure-ecommerce/vendure#660]
**Describe the bug**
When adjusting an orderLine, the orderItemPriceCalculationStrategy is only called when the quantity on the orderLine is increased. This is insufficient, as the orderItemPrice can depend on other things as well (such as customFields on the OrderLine), requiring a recalculation of the price even if the quantity has not changed. 

**To Reproduce**
Error occurs in the `updateOrderLineQuantity( ... )` method in order-modifier.ts

**Expected behavior**
The `orderItemPriceCalculationStrategy` should be called upon every adjustment of an orderLine.

**Environment (please complete the following information):**
 - @vendure/core version: 0.18.1

**Comment by michaelbromley** [comment]
> the orderItemPrice can depend on other things as well (such as customFields on the OrderLine),

> The orderItemPriceCalculationStrategy should be called upon every adjustment of an orderLine.

By "every adjustment" we can enumerate:

* quantity increase
* quantity decrease
* custom field change

Is there any other kind of change you had in mind?

Also, currently we don't calculate price when decreasing the quantity, as we are just removing OrderItems. Can you think of any scenario when we would want to re-calculate item price for the remaining items when decreasing quantity? I can't.
