### ISSUE TITLE
Default enabling/disabling of payment gateways

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#662]
I would like to request a feature where I can have default value of "enabled" in payment gateway.

A simple option under custom payment gateway options like of 'code': <name> can be replicated for it like.

'enabled': true (default) | false 

This can be later changed from admin panel UI. But seems handy for many cases (especially when channel specific payment gateway arises)

**Comment by michaelbromley** [comment]
I'm not sure how this proposal differs from the existing "enabled" property: 
![image](https://user-images.githubusercontent.com/6275952/106261908-82ee5680-6222-11eb-822a-d8c7a73beb3e.png)

Can you clarify?

**Comment by BeepLoveKarki** [comment]
This seems handy in many multivendor cases. So, a small request if possible.

**Comment by michaelbromley** [comment]
I'm sorry, I don't understand what exactly you are requesting in this issue.

You seem to be requesting the ability to enable/disable payment methods. I replied asking how this request differs from the existing "enabled" property of the PaymentMethod entity.

Please can you clarify this point?

**Comment by BeepLoveKarki** [comment]
Oh. I just wanted the case in which the same thing of UI can be done via our code, whenever we need. This is handy in cases of needing default behaviour of payment gateway.

Its defaultly enabled in dashboard. But may be we may need to have it disabled for the first time.

**Comment by michaelbromley** [comment]
Ah I understand, thanks. So this whole mechanism will actually be changing as part of the work I am currently doing on #671. 

The PaymentMethod entities will no longer be automatically populated from the configured PaymentMethodHandlers. Instead, it will work more like ShippingMethods, where you need to explicitly create the PaymentMethod and assign one of the PaymentMethodHandlers to it.
