### ISSUE TITLE
OrderMergeStrategy not working as intended

### ISSUE THREAD

**Issue by hendrik-advantitge** [vendure-ecommerce/vendure#669]
**Describe the bug**
First of all, the OrderMergeStrategies described in the documentation (https://www.vendure.io/docs/typescript-api/orders/merge-strategies/) are not exported and thus not usable in the config. 
Secondly, the strategies do not work as intended. The OrderMerger returns something of this type:
`type MergeResult = {
    order?: Order;
    linesToInsert?: Array<{ productVariantId: ID; quantity: number }>;
    orderToDelete?: Order;
};`
It only gives functionality to insert extra OrderLines, but not remove any. On top of that, only the quantity property is merged, while other customFields might require merging as well.

**Expected behavior**
OrderMergeStrategy should have more control over the resulting Order:
- Remove OrderLines
- Merge CustomFields

**Environment (please complete the following information):**
 - @vendure/core version: 0.18.2

**Comment by michaelbromley** [comment]
Thanks for this report. Can you clarify what you mean by "Merge CustomFields"?

My understanding is that we should take custom fields into account when deciding whether OrderLines are equivalent.

E.g.

Existing Order
```
{
  productVariantId: 1,
  quantity: 1,
  customFields: { foo: 'bar' },
}
```

Guest Order
```
{
  productVariantId: 1,
  quantity: 1,
  customFields: { foo: 'quux' },
}
```

In this case, the OrderLines are not equivalent and merging would result in a new OrderLine being added to the existing Order, with `{ foo: 'quux' }` as the custom fields.

If, however, the guest OrderLine had the _same_ customFields value (`{ foo: 'bar' }`), then the merge would result in no additional OrderLine, but potentially a modification of the quantity of the existing OrderLine.
