### ISSUE TITLE
De-couple PaymentMethod from PaymentMethodHandler

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#671]
The PaymentMethod entity has a "code" field which is supposed to refer to one of the configured PaymentMethodHandlers. However, in the GraphQL API `updatePaymentMethod` mutation, as well as in the Admin UI, this "code" can be edited.

There seems to be no good reason to allow setting this code. Rather, it would make more sense to de-couple the handler and the method, so that you can create a PaymentMethod and then select from one of the configured handlers.

Additionally, the PaymentMethod should have a "name" and "description" field.

Also add some e2e tests for the PaymentMethodResolver.

**Comment by michaelbromley** [comment]
While working on this, also handle these related issues: #469, #662

**Comment by stefanvanherwijnen** [comment]
Could you also add the `name` and `description` on the returned `eligibleShippingMethods`?
https://github.com/vendure-ecommerce/vendure/blob/c3c5888569ce0bc9da6bd68b2837aa393b0626ed/packages/core/src/service/services/payment-method.service.ts#L111-L116

Also, if I understand correctly, `code` is deprecated and could be removed?

**Comment by michaelbromley** [comment]
> Could you also add the name and description on the returned eligibleShippingMethods?

@stefanvanherwijnen could you please open a new issue for this so I don't forget about it? 

> Also, if I understand correctly, code is deprecated and could be removed?

The `code` property is still needed in the addPaymentToOrder() as you pointed out. True, it might be preferable to use the id instead now, as it is more explicit.
