### ISSUE TITLE
Channel aware Assets

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#677]
Currently, assets are shared between channels. If an asset is uploaded to channel1and the user switches to channel2, it will see the same set of assets. To fully support multi-channel shops, it's desirable to have assets that are channel aware.

**Describe the solution you'd like**
Assets that are uploaded in the context of the current channel should only be available in the current channel.

* Focalpoints are global: Changing focalpoints changes the focalpoint for this asset on all channels
* Deleting an Asset in a non-default channel will result in the asset still being available in the default channel
*  Optional `deleteFromAllChannels` boolean for `deleteAsset` mutation to delete asset from all channels

 ```graphql
 input AssetDeletionOptions {
   force: Boolean
   deleteFromAllChannels: Boolean
 }
 ```

**Considered out of scope for now**: Assigning assets to multiple channels via the Admin UI.

~~**Question** Should there be something like global assets?~~

I am currently working on this feature.

**Comment by michaelbromley** [comment]
> Question Should there be something like global assets?

What do you mean by this? Assets that are available by default in all Channels without needing to be explicitly assigned?

**Comment by martijnvdbrug** [comment]
> > Question Should there be something like global assets?
> 
> What do you mean by this? Assets that are available by default in all Channels without needing to be explicitly assigned?

I was thinking about assets that are assigned to multiple channels, which seems like a must have now that I think about it.

**Comment by michaelbromley** [comment]
Yes, they should work just like any of the ChannelAware entities:

* They are _always_ assigned to the default Channel.
* They may be optionally assigned to one or more sub-channels.

**Comment by martijnvdbrug** [comment]
* What is the desired behavior when an asset is deleted from a channel? Should it always stay in the default channel?
* What if an asset is deleted from the default channel, but it's also in other channels?
* I assume focalPoints should be channel-aware aswell?

**Comment by michaelbromley** [comment]
Good questions:

>What is the desired behavior when an asset is deleted from a channel? Should it always stay in the default channel?
What if an asset is deleted from the default channel, but it's also in other channels?

I think we need to provide a choice to the user. Here's the current deletion API:

```GraphQL
deleteAsset(id: ID!, force: Boolean): DeletionResponse!

type DeletionResponse {
  message: String
  result: DeletionResult!
}

enum DeletionResult {
  "The entity was successfully deleted"
  DELETED
  "Deletion did not take place, reason given in message"
  NOT_DELETED
}
```
We make use of the "force" variable e.g. if attempting to delete an Asset which is set as the featuredAsset of a Product. The call to `deleteAsset` will return something like:

```JSON
{ 
  "result": "NOT_DELETED",
  "message": "The selected Asset is featured by 1 Product"
}
```
and only setting "force" to true actually deletes it.

We could do something similar with channels, but we probably would then want a "AssetDeletionOptions" input something like:

```GraphQL
input AssetDeletionOptions {
  force: Boolean
  deleteFromAllChannels: Boolean
}
```

> I assume focalPoints should be channel-aware aswell?

No, I don't think this is necessary. It would be overly-complex and I can't easily think of a scenario where the focal point changes depending on what channel it is in. If you have some use-case in mind, let me know.

**Comment by martijnvdbrug** [comment]
I can't think of any use-case on having channel aware focalpoints, so focalpoints will always be global.

The solution of having `deleteFromAllChannels` seems fine for me, given that you can only use it in the context of the default channel. Maybe we should throw an error when `deleteFromAllChannels=true` is given in the context of a non-default channel?

**Comment by michaelbromley** [comment]
I was thinking that `deleteFromAllChannels: true` in the context of a sub-channel would mean "also delete it from the default channel". I.e. it always means "delete from **all** channels" regardless of which channel it is called from.

Oh, another complication here - we need to take into account whether the current user actually has permissions to delete from other channels! You can't allow "Shop B Admin" who only has permissions on "Shop B Channel" to delete things from the default channel.

**Comment by martijnvdbrug** [comment]
> Oh, another complication here - we need to take into account whether the current user actually has permissions to delete from other channels! You can't allow "Shop B Admin" who only has permissions on "Shop B Channel" to delete things from the default channel.

That's why I was thinking about throwing an error, but that might be unexpected behavior when you have permission to all channels. 
So the right way is checking permissions and only throw an error when the current user does not have permissions.

**Comment by michaelbromley** [comment]
> but that might be unexpected behavior when you have permission to all channels.

Yes exactly. There will be cases where a superadmin-type account is doing work in a sub-channel and would want to be able to just delete assets without switching to the default channel, finding the asset again and then deleting.

**Comment by martijnvdbrug** [comment]
More questions:
* If an asset is assigned to a product in the default channel, and the product is assigned to channel2, should the asset also be added to channel2? I assume so.
* Proposal for the mutations:
```graphql
type Mutation {
    assignAssetsToChannel(input: AssignAssetsToChannelInput!): [Asset!]!
    deleteAsset(input: DeleteAssetInput!): DeletionResult!
    deleteAssets(input: DeleteAssetsInput!): DeletionResult!
}

input AssignAssetsToChannelInput {
    assetIds: [ID!]!
    channelId: ID!
}

input DeleteAssetInput {
    assetId: ID!
    force: Boolean
    deleteFromAllChannels: Boolean
}

input DeleteAssetsInput {
    assetIds: [ID!]!
    force: Boolean
    deleteFromAllChannels: Boolean
}
```

**Comment by michaelbromley** [comment]
1. Yes
2. Agreed
3. Looks good 👍
