### ISSUE TITLE
Sort products by popularity

### ISSUE THREAD

**Issue by timojokinen** [vendure-ecommerce/vendure#678]
**Is your feature request related to a problem? Please describe.**
In many online shops the user can sort by date, price and popularity / trending
Currently vendure does not keep track of what products are trending and provides no functionality to sort products by their popularity. I think this might be a really important feature that's currently missing in vendure.

**Describe the solution you'd like**
Sort by popularity

**Describe alternatives you've considered**
If the vendure sort functionality was easily extendable that would be a great alternative and could also be helpful for other use cases

**Additional context**
Some values that could impact the popularity of a product are creationDate and amount of views and likes on a product.
AFAIK likes / watchlist and keeping track of views per product is not currently implemented in vendure. I'm wondering if this is something you would consider useful to have in the core project.

**Comment by michaelbromley** [comment]
Hi,

This functionality is something that would work well as a plugin. As you touch on, there are many ways of defining "popularity":

* Number of sales in a given time frame
* Number of "add to wishlist" in time frame
* Number of views
* Even more sophisticated algorithm, e.g. taking into account profit margins or idle stock

Some of the above imply extra supporting features to be in place (e.g. watchlist/wishlist, click tracking) so adding it to core would mean considerably expanding the scope of core. My general approach is to include in core only those thing strictly necessary for a basic e-commerce app, plus the means to extend via plugins to cover the rest.
