### ISSUE TITLE
Upload asset with Non-Alphanumeric characters does not work

### ISSUE THREAD

**Issue by ttournie** [vendure-ecommerce/vendure#679]
**Describe the bug**
If you try to upload an asset from the admin-ui with non-alpanumeric characters in the title, you get a file not found.

**To Reproduce**
1 - Log into admin-ui
2- Go to assets
3 - upload an image with non-alpanumeric characters in the title (exemple : Capture d’écran 2021-01-22 à 11.06.53)

**Expected behavior**
The file should be found

**Environment (please complete the following information):**
 - @vendure/core version: 0.18.0
 - Nodejs version : 12.02
 - Database (mysql/postgres etc): Posgres

**Comment by michaelbromley** [comment]
Turns out that it was the "single left quote" character `’` which caused the issue!
