### ISSUE TITLE
Allow custom order filter strategy

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#685]
Have a feature where we can declare our own filter strategy for orders can be a really great tool for high order eCommerce. Various parameters like area, date, the product(s) ordered, etc. effects a lot in process of e-commerce fulfillment.

So strategy based on fields of the order can be a good start or any custom coding access (like custom promotion strategy) can be fine.

**Comment by michaelbromley** [comment]
Just to be clear, is this feature relating to the Admin UI specifically? Because it is already possible to filter Orders by various properties, including custom fields.

**Comment by BeepLoveKarki** [comment]
Yes, this is only for admin UI filtering, not via API.

**Comment by michaelbromley** [comment]
Improved filtering of all lists was implemented in v2
