### ISSUE TITLE
Error while deleting channels

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#686]
I really hope this error gets solved soon.

![Screenshot (710)](https://user-images.githubusercontent.com/29729738/106888809-2eaa1180-670f-11eb-851f-374031bc5373.png)

**Comment by michaelbromley** [comment]
From Slack discussion:

> It means there are Session rows in the DB with foreign key relations to that Channel which you are attempting to delete. This is a bug - the process of deletion should really check for any associated Sessions and delete them first.
