### ISSUE TITLE
Sort by name not working correctly in multilingual project

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#689]
**Is your feature request related to a problem? Please describe.**
List query builder sort's feature on translated properties like "name" of _ProductVariant_ or _Product_ doesn't work correctly, as the query is sorted based on **all** values, not of the current languageCode from _ctx_ object.
E.g. I have list of products (be the number "ID") in EN:
1. Arg
2. Blaigh
3. Dooh

and their translation in DE:
1. Bimbim
2. Kiokio
3. Aant

the result for EN site will wrongly be "Dooh, Arg, Blaigh", and what's worse consequently _skip_ and _take_ stop working it will just return fewer results randomly.

**Describe the solution you'd like**
In my case I joined translation of wanted language on different alias and sort on it, therefore in core I believe switching translation eager settings to _false_ and in query builder leftjoinselect translation with condition based on current languageCode
_qb.leftJoinAndSelect(qb.alias + '.translations', 'translation', 'translation."languageCode" = :langCode', {langCode: ctx.languageCode})_
will fix the issue and we will get better performance as a bonus, but mind the need of providing defaults for those that have missing translation

**Comment by chladog** [comment]
This should be tagged as bug.

**Comment by michaelbromley** [comment]
Good catch.

I want to keep translations as eager - they are _always_ needed and using eager loading quite significantly simplifies a bunch of code.

Anyway, I think I managed to solve the basic issues by adding the following to the `ListQueryBuilder.build()` method:

```ts
const { columns, translationColumns, alias } = getColumnMetadata(rawConnection, entity);
if (translationColumns.length) {
    const languageCode = extendedOptions.ctx?.languageCode || DEFAULT_LANGUAGE_CODE;
    const translationsAlias = qb.connection.namingStrategy.eagerJoinRelationAlias(
        alias,
        'translations',
    );
    qb.andWhere(`${translationsAlias}.languageCode = :languageCode`, { languageCode });
}
```

However, this does not handle the case in which a translation is missing in a given language. In that case, the item with the missing language is omitted from the result set. I'm having trouble coming up with an SQL query which can handle that, the logic being:

```
# pseudo-code

SELECT entity 
LEFT JOIN translations on translations.baseId = entity.id
WHERE translations.languageCode = :languageCode
but include _all_ entities even if no translation exists
```

That is beyond my SQL-fu right now.

**Comment by michaelbromley** [comment]
Getting closer, with a query like:

```sql
SELECT "label", "languageCode", "name"
FROM "test_entity" "testentity"
LEFT JOIN
(SELECT * FROM "test_entity_translation" "testentity_translations" 
  WHERE "testentity_translations"."languageCode" = 'de') t1 
ON "t1"."baseId"="testentity"."id"
```

This gives a row for _each_ of the entity, and `null` values if the translation doesn't exist. Now trying to figure out how to build such a query in an automated way via TypeORM...

**Comment by michaelbromley** [comment]
Finally figured out a way to solve that last aspect of the problem. If the current language is not the default, and a translation doesn't exist in that langauge, then it will fall back to the default language. The SQL used in this case looks like (assuming a default LanguageCode of 'en'):

```sql
WHERE
  "testentity_translations"."languageCode" = 'de'
  OR
  EXISTS (SELECT * FROM "test_entity_translation" WHERE "test_entity_translation"."baseId" = "testentity"."id"  AND "test_entity_translation"."languageCode" = 'en')
  AND NOT EXISTS (SELECT * FROM "test_entity_translation" WHERE "test_entity_translation"."baseId" = "testentity"."id"  AND "test_entity_translation"."languageCode" = 'de')
```
