### ISSUE TITLE
Vendure Hide Branding brand name and hide vendure version not working except first compilation

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#692]
The favicon and version hide of vendure is not working as we define after the first compilation. It works for the first time, but when we restart the server after compilation, it fails and shows VendureAdmin in brand name and also displays the vendure version in the dashboard.

**Comment by chladog** [comment]
You shouldn't run recompilation, or dev server (yarn start) for production...
Build your app with yarn build and then use it with yarn run:server & yarn run:worker for prod env.
Also make sure that you are not recompiling UI for prod - note lines 12 & 65 [here](https://github.com/vendure-ecommerce/real-world-vendure/blob/master/src/vendure-config.ts)

**Comment by BeepLoveKarki** [comment]
Yes I did exactly as U said. But everytime I get VendureAdmin except first time as my brand name, and get vendure version shown. Other all work fine though.
