### ISSUE TITLE
Product SearchResult Type missing customFields

### ISSUE THREAD

**Issue by rahmonzoda** [vendure-ecommerce/vendure#698]
**Describe the bug**
I got an error when I try to query search product

Here is my gql

```javascript
export const SEARCH_PRODUCTS = gql`
  query SearchProducts($input: SearchInput!) {
    search(input: $input) {
      items {
        slug
        productName
        description
        customFields {
          uiColor
        }
        priceWithTax {
          ... on PriceRange {
            min
            max
          }
        }
      }
      totalItems
    }
  }
`;
```

**Environment (please complete the following information):**
 - @vendure/core version: v0.18.4
 - Nodejs version 14
 - Database (mysql/postgres etc): postgres

**Comment by michaelbromley** [comment]
Hi,

The DefaultSearchPlugin does not support custom fields. If you need this, I suggest you take a look at the [ElasticsearchPlugin](https://www.vendure.io/docs/typescript-api/elasticsearch-plugin/), which allows you to define [custom mappings](https://www.vendure.io/docs/typescript-api/elasticsearch-plugin/elasticsearch-options/#customproductmappings).
