### ISSUE TITLE
strictmetadataemit and sourcemap during UI compilation

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#699]
Please make strictmetadataemit false and sourcemap false during the compilation of admin UI. This is useful and to be noted thing during the production of vendure.

**Comment by michaelbromley** [comment]
> This is useful and to be noted thing during the production of vendure.

Do those settings cause a problem?

**Comment by BeepLoveKarki** [comment]
Yes. From security/vulenarability point of view, this is aimed to cause an issue.

**Comment by michaelbromley** [comment]
Do you have any links to more info (or can you explain a bit) about the security/vulnerability issues with these two settings?

**Comment by BeepLoveKarki** [comment]
I don't have any links for sourcemap, but I did penetration testing to my website on the server and the tester was able to view a lot of my component codes and download them to his server. He said sourcemap false will solve it.

And for strictmetadataemit true causes unexpected error is the new warning provided to me during every compilation since v17. It didn't exist before.

**Comment by michaelbromley** [comment]
OK. I'll leave this here and do some more investigation at some point.

**Comment by michaelbromley** [comment]
This issue relates to a version of Vendure that is no longer supported. If the issue persists in the latest version, please open a new issue.
