### ISSUE TITLE
Uploaded files are created, yet remain at zero size indefinetly

### ISSUE THREAD

**Issue by thewhiterabbit** [vendure-ecommerce/vendure#704]
**Description**
Uploaded files are created in the assets, but the data is not transferred into the file. They remain at zero size.

**To Reproduce**
1. Setup Vendure using the create script with production details.
2. Login to the Vendure admin area.
3. Click on Catalog>Assets.
4. Click on Upload Assets button.
5. Select a file to upload (mine was 247 KB)
6. Click Open/Upload

**Expected behavior**
Data from the local file should populate the newly created file on the remote in assets/generated/selected_file_name.ext

**Environment (please complete the following information):**
 - @vendure/core version: Master branch as of 2.11.2021 7:58 PM PST
 - Nodejs version: v15.8.0
 - Database (mysql/postgres etc): MySQL 8.0.23-0ubuntu0.20.04.1
 - Ubuntu 20.04.1
 
**Images**
![Capture2](https://user-images.githubusercontent.com/5334222/107728792-ea38eb80-6ca3-11eb-9796-83dbd196602d.PNG)

<hr>

![Capture1](https://user-images.githubusercontent.com/5334222/107728795-ead18200-6ca3-11eb-81f8-dc2379b38df5.PNG)

**Comment by michaelbromley** [comment]
Hi,

Is there any error in the server console when uploading? I am wondering if this is related to #396 

You can check by downgrading to Node v12.x and seeing if that works.

**Comment by thewhiterabbit** [comment]
I did some investigating and it's the same issue so I came here to close this with a note.

How to fix this: Downgrading node to 12.x will work.

**Comment by michaelbromley** [comment]
Ok thanks for following up. It looks like the next release of Apollo Server will address this issue, at which point I'll update the dependency in Vendure.
