### ISSUE TITLE
Role and administrator link issue leading unable to log in any admin

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#706]
Following procedure leads to not allow any admin log in back to the portal:

1.  Created a new role
2.  Created a new administrator
3.  Assigned the role to the administrator
4.  Deleted the role

This led to auto log out and not able to log back in again using any administrator credential. Seems an important bug to remove, just a warning needed, not such effect.

**Comment by michaelbromley** [comment]
I cannot reproduce this following the 4 steps provided. Is there any step or detail you may have missed out?

**Comment by BeepLoveKarki** [comment]
No. Its the same. I had multiple channels, roles and administrators. May be that is something.

**Comment by michaelbromley** [comment]
OK. I did this - just to verify I am understanding your instructions correctly:

0. logged in as superadmin
1. Created a role named "newRole"
2. Created an admin "test@test.com"
3. Assigned the "newRole" role to "test@test.com"
4. Deleted the "newRole" role.

Result: I am still logged in as superadmin.
