### ISSUE TITLE
Cannot find module './lib/create-vendure-app'

### ISSUE THREAD

**Issue by thewhiterabbit** [vendure-ecommerce/vendure#709]
**Strange Error**
```
Cannot find module './lib/create-vendure-app'
Require stack:
- /home/username/.npm/_npx/63015/lib/node_modules/@vendure/create/index.js
```

**To Reproduce**
1. Clone from git
2. Run npx @vendure/create testsite
4. See error above

**Expected behavior**
Prompted for information to create the build

**Environment (please complete the following information):**
 - @vendure/core version: latest via the git repo
 - Nodejs version v12.18.2
 - Database (mysql/postgres etc): mysql 8.0.1

**Additional context**
I'm trying this on a new VPS server. I was able to get this to work on the last server, both running Ubuntu 20.04, MySQL 8.0.1, Node v12.18.2

Doesn't the @vendure/create package install that create-vendure-app module?

**Comment by thewhiterabbit** [comment]
This is very strange to me indeed. I notice that the index.js of `vendure/packages/create` requires `./lib/create-vendure-app`, but the actual path to that file would be `./src/create-vendure-app`, however, it does not error on one server, but it does on the other server.

Is there some node module I'm missing that aliases ./lib to ./src?

Should I change the require statement path in `vendure/packages/create/index.js` to `./src/create-vendure-app` instead of `./lib/create-vendure-app`?

**Comment by michaelbromley** [comment]
Hi,

Can you clarify what you are trying to do here? Cloning this Vendure repo is normally only necessary if you intend to make modifications to the core Vendure code base, e.g. if you plan to contribute some change as a pull request, or create your own private fork with different behaviour.

On the other hand, running `@vendure/create` is done when you want to start a new project built on top of Vendure, without modifying the Vendure source code itself.

Which are you trying to do?

**Comment by thewhiterabbit** [comment]
I'm trying to do all the above. I wanted to be able to contribute, there are some changes I'm trying to test but I couldn't get them to build with @vendure/create so I think it's because of the create package not referencing those added features I'm working on.

I think I have to manually download the node repos then modify them and reupload to a different repo and point my branch to the modified repos.

**Comment by thewhiterabbit** [comment]
This is technically not an issue that would concern the whole project unless my changes are accepted and I can't even test them yet so I'm closing this. I'll figure it out. I'm kinda new to node based projects.

**Comment by michaelbromley** [comment]
> I wanted to be able to contribute, there are some changes I'm trying to test but I couldn't get them to build with @vendure/create

Ok, I see. To test out changes to the core, you should use the `dev-server` package. Full instructions are given here: https://github.com/vendure-ecommerce/vendure#4-set-up-the-server
