### ISSUE TITLE
Make credential not mandatory for configureS3AssetStorage

### ISSUE THREAD

**Issue by ttournie** [vendure-ecommerce/vendure#733]
**Is your feature request related to a problem? Please describe.**
The credential is not mandatory in the aws SDK but it is in Vendure config, so you can not use the s3-storage-strategy from Vendure if you do not need credentials (IAM role for exemple).

**Describe the solution you'd like**
Simply change the type definition and getS3Credentials function

**Describe alternatives you've considered**
For now I have cloned the strategy and made the change

**Comment by michaelbromley** [comment]
Are you proposing this change?
```diff
-  credentials: S3Credentials | S3CredentialsProfile;
+  credentials?: S3Credentials | S3CredentialsProfile;
```

is this the kind of scenario you are working with (https://aws.amazon.com/premiumsupport/knowledge-center/s3-private-connection-no-authentication/)?

**Comment by ttournie** [comment]
Yes this is the change I am proposing. here you can see one example where credential is not needed : https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-iam.html
