### ISSUE TITLE
Jobs stay in 0% running state (Dockerised deployment)

### ISSUE THREAD

**Issue by vmatekole** [vendure-ecommerce/vendure#737]
Throughout development and now in our live environment we have consistently had issues around jobs never completing. We have a Dockerised delpoyment in dev and production. We think it is most likely due to this.... Nonetheless, our  past experience concerning jobs mgmt has been Sidekiq. With Sidekiq it was easy to re-run jobs without concern as long as jobs were implemented idempotently. 

There is nothing notable we can see within the logs but we can see jobs that are stuck(screenshot attached). Being able to re-run them as opposed to just cancelling them is required. Customers have had emails missed and it is hard to do product entry as indexing jobs constantly fail to run without restarting all services and even then, jobs are not re-run but have to be cancelled and products re-indexed manually.

I am not sure if this issue is related to #635 ... On the face of it, it doesn't as at least jobs are actually ran after restarting services. This is becoming a serious production issue so some help in at least a workaround where we can re-run jobs manually would be a great help!

https://www.dropbox.com/s/z1436wj6vp7v0ke/Screenshot%202021-03-01%20at%2015.20.51.png?dl=0 – Stuck jobs

https://www.dropbox.com/s/46i27eohvdkiq82/Screenshot%202021-03-01%20at%2015.22.04.png?dl=0 – Cancelled jobs

Version 0.18.2

**Comment by michaelbromley** [comment]
I'm sorry to hear that this is causing issues in production. 

The entire architecture for the job queue has been re-worked for the upcoming v1.0.0-beta.1 release. I am actually working on merging those changes in right now. This new architecture significantly simplifies the way the job queue executes. 

I cannot say for certain that these changes will solve the issues you ran into, but now that I am actively working on this part of the code, I am keeping an eye out for such issues and will fix what I find, and update this thread with any concrete findings.

**Comment by vmatekole** [comment]
@michaelbromley  will we be able re-run jobs? Example emails? Right now some emails are not going out and we have no mechanism for re-sending them, other than contacting customers manually.

**Comment by vmatekole** [comment]
Is there a way we can re-send order confirmations/shipping notifications?

**Comment by michaelbromley** [comment]
> will we be able re-run jobs
> Is there a way we can re-send order confirmations/shipping notifications?

If you an issue for each of these and include a reference to this issue, I will assign to the 1.0.0 milestone.

**Comment by michaelbromley** [comment]
Closing this as on further investigation there was a mis-configuration (runInMainProcess was set to true)

**Comment by vmatekole** [comment]
@michaelbromley  For your information we fixed the configuration issue and still had the same problem with the Worker. We suspect the issue was related to Docker and Nest's microservice architecture. 

Here is an example of others suffering simliar issue
https://stackoverflow.com/questions/62188374/nestjs-microservices-with-docker

We are now running 1.0 for some weeks now and have no email issues. Version 1.0 no longer depends on network communication with the Worker so we no longer suffer from server being unable to communicate with the Worker. 

Anyone with a Docker deployment and is on anything less than 1.0 will continue to suffer from this issue.

**Comment by michaelbromley** [comment]
OK, thanks for the update, glad all is working with that now 👍
