### ISSUE TITLE
move from session to use JWT

### ISSUE THREAD

**Issue by ttournie** [vendure-ecommerce/vendure#740]
**Is your feature request related to a problem? Please describe.**
It's not really a problem but for scalability it would be nice to avoid using databe/memory stored session for users and use JWT token instead

**Describe the solution you'd like**
Not sur if it's possible to have a setting parameter to switch to JWT. It sounds nice but seems like it's a lot of work

**Comment by michaelbromley** [comment]
See #25 

JWT offers no benefit in our case, only lots of complexity (refresh tokens needed, difficulty in invalidating sessions). The amount of data we require in the RequestContext.session is not practical to store in a JWT, so a lookup is needed anyway on every request to populate the Session.

If scaling is ever an issue, that's you might want to define your own [SessionCacheStrategy](https://www.vendure.io/docs/typescript-api/auth/session-cache-strategy/) and use something like Redis. Are you running into scaling issues where the session handling seems to be the bottleneck?

**Comment by ttournie** [comment]
Ok thanks for the answer :)
