### ISSUE TITLE
Cannot access jobs list due to int values representation error

### ISSUE THREAD

**Issue by Clever-Up** [vendure-ecommerce/vendure#755]
**Describe the bug**
When accessing the job list in the admin panel, I get the following error warning, repeatedly (with different numbers): `Int cannot represent non 32-bit signed integer value: 2336469457`. The error message sometimes appears also in the admin home and throughout other views, but the error seems to be originated from the jobs panel that in fact is always blank, empty due to this error.
The error is similar to what reported in issue #696 but i believe in a different context.

**To Reproduce**
1. Go to the admin panel
2. Access the jobs queue
3. See the error and not the jobs list

**Expected behavior**
Jobs list should appear correctly

**Environment (please complete the following information):**
 - @vendure/core version: 0.18.5
 - Nodejs version: 12.21.0
 - Database (mysql/postgres etc): postgres

**Additional context**
The error was already there when I had deployed the same site with Vendure v. 0.18.3

**Comment by michaelbromley** [comment]
Ah ok, this must be coming from the `Job.duration` field (which is the only Int field on that type). So there must be a job in the list which has a duration of 2336469457ms (which is like 27 days, ouch!). I guess that job is broken and will never complete. For now you can manually remove any jobs with massive duration from the queue in the DB.

**Comment by Clever-Up** [comment]
Ok clear, will do as you suggest. Thank you!!
