### ISSUE TITLE
Support for multi-shops and multi-vendors

### ISSUE THREAD

**Issue by jruillier-afidium** [vendure-ecommerce/vendure#759]
Our company is currently evaluating available open source ecommerce APIs.
We've been looking at Spree, Solidus, etc.

These are nice projects, but we're not Ruby guys.
We're skilled in Angular/Typescript and Flutter/Dart  development, so a NodeJS backend would better fit our needs.

Our project looks like a market place, so we require support for multi-vendors and multi-shops.
Is there any plugin for Venture to achieve that or is it part of the roadmap ?
If not, we may contribute to Venture with this kind of plugin, but what would be the complexity level ?

**Comment by michaelbromley** [comment]
Hi,

Sounds like Vendure is the perfect match tech-wise.

There are actually already a few marketplace apps in development using Vendure. One example is a pretty large project (thousands of sellers, ~60k products listed). In recent months, we've managed to put in place all the parts to make it possible to cleanly separate vendors via our Channels feature. Depending on your exact requirements, the out-of-the-box features may cover your needs.

If you want to discuss this in more detail, I recommend you join our [Slack group](https://join.slack.com/t/vendure-ecommerce/shared_invite/enQtNzA1NTcyMDY3NTg0LTMzZGQzNDczOWJiMTU2YjAyNWJlMzdmZGE3ZDY5Y2RjMGYxZWNlYTI4NmU4Y2Q1MDNlYzE4MzQ5ODcyYTdmMGU) and connect with me there.

**Comment by zorox-1** [comment]
Multi vendors feature is that key feature that will take this project to the next level and give it big advantage over all other scripts
