### ISSUE TITLE
Cannot return null for non-nullable field, recurring error

### ISSUE THREAD

**Issue by stefanvanherwijnen** [vendure-ecommerce/vendure#763]
**Describe the bug**
When querying deeply nested fields in a query, sometimes a `Cannot return null for non-nullable field` error occurs

**To Reproduce**
For example in the admin api:
```
query {
  orders {
  items {
      lines {
        productVariant {
          name
        }
      }
    }
  }
}
```
**Expected behavior**
It should not return an error.

**Additional context**
I guess this is caused by TypeORM not following the relations to a certain level of nested items. This is required to prevent recursion errors, but the question is how to handle this properly.
In the example above, there could be a lot of equal productVariants in the total number of order lines. It would be more efficient to have a separate query for the productVariants, but currently it is not possible to query a list of ID's.

So I think the fix is either:
- Return deeply nested fields
- Create a way to query for a list of ID's on the `List` queries.

I'm curious about what would be the ideal approach.

**Comment by michaelbromley** [comment]
Thanks for the report.

There are 2 factors at play here:

1. As you mention, at the service layer we only selectively join relations based on what is _most likely_ to be needed. Allowing TypeORM to freely join all possible relations *just in case* would be unworkable, performance wise. When a type with relations is queried in GraphQL then, either the relation was already joined in the parent query, or if not, then GraphQL will invoke any _field resolvers_ defined for the relation field. So the first issue is that not all field resolvers have been defined. 
2. In the specific case of the `ProductVariant.name` field, there's another factor: this is a translatable field, which means that the "name" can have many values, one for each defined language. At run-time, we are supposed to inspect the languageCode of the current request context, and use that to select the correct translation and populate the "name" field. This is another thing that needs to be defined in the field resolvers.

The solution is to define field resolvers on all fields that might involve a DB join to populate. This means all relations _and_ all translatable fields.

**Comment by stefanvanherwijnen** [comment]
Makes sense. By 'field resolver', do you mean the [GraphQL Resolver](https://docs.nestjs.com/graphql/resolvers)?

The problem is that [translateDeep](https://github.com/vendure-ecommerce/vendure/blob/2bc37f8ee0b4f77b15dc8c2e3ed31e586d41c6c5/packages/core/src/service/helpers/utils/translate-entity.ts#L81) 'resolves' the `name` field in the Entity, but it is not called on the relations in this case.
`findOne` does perform the translation manually so that works fine, but since the productVariant is joined in the query it is not translated here:
https://github.com/vendure-ecommerce/vendure/blob/d86d17a14c7d38cd66718e0cdf2fb23068ac05d1/packages/core/src/api/resolvers/entity/order-line-entity.resolver.ts#L17-L20

I think the only efficient solution is to manually call translateDeep where it is missing, as in the above commit. Ideally, TypeORM would automatically resolve the name field but I don't think that's possible?

**Comment by michaelbromley** [comment]
>  By 'field resolver', do you mean the GraphQL Resolver?

Yes.

>  Ideally, TypeORM would automatically resolve the name field but I don't think that's possible?

No, TypeORM cannot do this. There was an old thread on the TypeORM repo asking about a native i18n solution but it's not something they want to support. 

So I've just put together a solution which adds field resolvers for every field which is of type `LocaleString`. It basically fetches the translations from the DB and calls `translateDeep`, but also includes a number of optimizations to reduce the number of DB queries that would be required.

**Comment by stefanvanherwijnen** [comment]
I wrongly assumed that `name` might be required internally which would be the reason for not resolving it in the GraphQL layer. Correct me if I'm wrong, but I think the following can now be removed?
https://github.com/vendure-ecommerce/vendure/blob/ae07134185e53b557c88488b475c18c59eb39e35/packages/core/src/service/services/order.service.ts#L199-L204

Works fine now :+1:

**Comment by michaelbromley** [comment]
> but I think the following can now be removed?

Yes, it could be removed from there now, though there is also no harm it being there - the new resolvers perform a check to see whether the localestrings have already been hydrated and skip that work if so.
