### ISSUE TITLE
Muti Currency for same channel 

### ISSUE THREAD

**Issue by zorox-1** [vendure-ecommerce/vendure#769]
currently a channel has only 1 currency. 

it would be great to have a base currency and other converted currencies. this will allow stores to implement currency switcher to display the price with different currencies. (the billing can stay with the default currency)

**Comment by michaelbromley** [comment]
I'd suggest you implement this as a plugin. You could e.g. use custom fields to store the alternate currencies and then have a background job which updates the values daily based on an exchangerates api such as https://openexchangerates.org/.

If there are aspects that you find a plugin cannot handle, and core support is required, let me know.
