### ISSUE TITLE
assets access from limited admin account

### ISSUE THREAD

**Issue by zorox-1** [vendure-ecommerce/vendure#778]
**Describe the bug**
Cannot access Assets on a channel with NO setting permission enabled 

**To Reproduce**
1. create a new role WITHOUT any setting permission selected 
2. create an administrator with the new role
3. login with the new administrator account
4. click on assets 
5. see error 

if i enable any setting permission to the user , then it works fine. i guess "tags" access is somehow linked to the settings permission. However, this should not be the case i guess

**Expected behavior**
should be able to access channels related assets  
**Environment (please complete the following information):**
 - @vendure/core version:
 - Nodejs version
 - Database (sqlite):

<img width="1675" alt="Screen Shot 2021-03-22 at 3 25 22 AM" src="https://user-images.githubusercontent.com/46525762/111924541-9d281080-8abe-11eb-951b-3bd27cd74dad.png">

<img width="1092" alt="Screen Shot 2021-03-22 at 3 31 50 AM" src="https://user-images.githubusercontent.com/46525762/111924698-3525fa00-8abf-11eb-8b64-56a488aafe52.png">

<img width="1675" alt="Screen Shot 2021-03-22 at 3 28 44 AM" src="https://user-images.githubusercontent.com/46525762/111924639-03ad2e80-8abf-11eb-8a11-f17d081728c6.png">

**Comment by michaelbromley** [comment]
Relates to #617. More granular permissions would solve this, or at least make the cause more obvious.
