### ISSUE TITLE
Collection.breadcrumbs not correctly ordered

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#779]
**Describe the bug**
From a Slack message:

> Hi! Is this the planned behavior in shop-api that breadcrumbs in collection query are returned in reverted sorting at the middle of the list?
For example, collection hierarchy:
collection1 -> collection2 -> collection3 
When we query collection3 breadcrumbs we receive
 [__root_collection__, collection2, collection1, collection3].
As i can see, that occurs due to order of getting ancestors here 

There _is_ currently a passing e2e test for breadcrumb order, but on investigation it appears that it works only because the breadcrumb order matches the order of creation of each collection.

**Expected behavior**
Breadcrumbs should always follow the path from root -> current collection in the correct order.

**Environment (please complete the following information):**
 - @vendure/core version: 1.0.0-beta.4
 - Nodejs version: any
 - Database (mysql/postgres etc): testing with MariaDB, probably affects all.

**Comment by Izayda** [comment]
After detailed investigation, i can confirm, that bug occurs when id of child collection is smaller then id of parent collection.

For example, if collection hierarchy is ordered by id and we try to get breadcrumbs for Pear, everything is fine:
id=3 Electronics
id=4 Computers
id=5 Pear

[Here](https://github.com/vendure-ecommerce/vendure/blob/a740ef9012760062f15bbf00bc1d27ed786282e6/packages/core/src/service/services/collection.service.ts#L282) we get ancestors in reversed order: [4,3]
Then [here](https://github.com/vendure-ecommerce/vendure/blob/a740ef9012760062f15bbf00bc1d27ed786282e6/packages/core/src/service/services/collection.service.ts#L284-L289) ancestors is reordred by id: [3,4] 
So, test case is ok.

if collection hierarchy is not ordered by id and we try to get breadcrumbs for Pear, errors occur:
id=4 Electronics
id=3 Computers
id=5 Pear

[Here](https://github.com/vendure-ecommerce/vendure/blob/a740ef9012760062f15bbf00bc1d27ed786282e6/packages/core/src/service/services/collection.service.ts#L282) we get ancestors in reversed order: [3,4]
Then [here](https://github.com/vendure-ecommerce/vendure/blob/a740ef9012760062f15bbf00bc1d27ed786282e6/packages/core/src/service/services/collection.service.ts#L284-L289) ancestors is reordred by id: [3,4] -- incorrect order
There is no test case for such case.

So, plan is to write test case:
1) Adding "Pear Parent" collection with greater id than 5 with parent collection Computers
2) Move Pear collection to be below "Pear Parent"
3) Get breadcrumbs for Pear
4) Move Pear collection to be below "Computers"
5) Delete "Pear Parent" collection

@michaelbromley maybe you can suggest some more simple test case?
