### ISSUE TITLE
AdminUI: On Product detail switching channels doesn't update model

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#782]
**Describe the bug**
If I remember correctly in previous versions when we switched channel the form fields were automatically updated with data model from the target channel. Now the form stays with data from the initial channel, to see the correct values we need to refresh (F5) the page after toggling the channel.

**To Reproduce**
1. Have multi-channel setup
2. Go to product detail, set different prices in two channels
3. Switch between those channels and observe that model is not updated accordingly
4. Refresh the page when selecting alternate channel to see that channel has actually been toggled

**Expected behavior**
When we switch channel data model should switch immediately when we toggle channel.

**Environment (please complete the following information):**
 - @vendure/core version: v1.0.beta4

**Comment by michaelbromley** [comment]
I think this might be related to #770. I fixed that one and when I try to reproduce in the current master branch, it seems to work. I'll be publishing beta.5 tomorrow so when you get a chance to update, let me know if it is fixed for you.

**Comment by chladog** [comment]
@michaelbromley Indeed, update to beta.5 fixed this issue. 
Closing.
