### ISSUE TITLE
allow selecting Collections & Products in Promotions

### ISSUE THREAD

**Issue by mariusa** [vendure-ecommerce/vendure#794]
**Is your feature request related to a problem? Please describe.**
The current promotions require specific product variants.

**Describe the solution you'd like**
Would like to select Collections and/or Products , to create promotions like

* Buy 1 shirt (from Shirts collection), get a tie or belt at 50% Off (from Ties/Belts collections)
* 10% off all Tops and these 3 pants (any variants)

**Describe alternatives you've considered**
Creating custom promotions with code works, but these should be available built-in

Thanks!

**Comment by michaelbromley** [comment]
Closing for now since as you mention, this is possible via custom promotion conditions/actions. We'd accept PRs however implementing a wider range of defaults.
