### ISSUE TITLE
Can't run start command in Apple Silicon

### ISSUE THREAD

**Issue by luisrudge** [vendure-ecommerce/vendure#803]
**Describe the bug**
When I run the command create on a Macbook AIr with the new M1 Chips, it fails.

**To Reproduce**
1. `npx @vendure/create deposter-whitelabel --log-level verbose`
2. Choose SQL Server
5. `libvips 8.10.5 binaries are not yet available for darwin-arm64v8`

**Expected behavior**
Should be able to install

**Environment (please complete the following information):**
 - Nodejs version: 15.11.0

**Comment by luisrudge** [comment]
I get the error with any other database as well

**Comment by luisrudge** [comment]
According to [this](https://github.com/lovell/sharp/issues/2460#issuecomment-783401553) comment, starting from 0.28.0, the `sharp` package works fine with Apple Silicon. Maybe upgrading [this dependency](https://github.com/vendure-ecommerce/vendure/blob/a740ef9012760062f15bbf00bc1d27ed786282e6/packages/asset-server-plugin/package.json#L36) it will work. 

I can help testing this if you help me figure out how to test it 😬

**Comment by michaelbromley** [comment]
Thanks for the report, and yes, as soon as I read the title I thought it was probably related to Sharp. You can test it by using the [yarn resolutions feature](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) if you have yarn installed.

**Comment by luisrudge** [comment]
@michaelbromley thanks! but I'm running `npx @vendure/create deposter-whitelabel --log-level verbose`, how can I use the resolutions feature running this command? 🤔

**Comment by michaelbromley** [comment]
Go into the directory created by the create command, open up the package.json and add a "resolutions" field with { "sharp": "0.28.0"}. Then run `yarn install` and after that try `yarn start`

**Comment by luisrudge** [comment]
@michaelbromley  Since the create command throws an error, I think the folder is not populated with all the files.
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/941075/113342487-f258f300-9304-11eb-9b03-c2654a2c5858.png">

**Comment by michaelbromley** [comment]
OK, another way then would be to clone https://github.com/vendure-ecommerce/real-world-vendure, follow the setup instructions and also add the resolution for sharp.

In any case, I'll upgrade the sharp version in an upcoming release.

**Comment by luisrudge** [comment]
@michaelbromley that's perfect. Updating to 0.28.0 works! I'll leave this open until you release the new version and then we can close it out. thanks again for the patience and help!
