### ISSUE TITLE
Admin UI - Collections tab - Cannot take more than 1000 results from a list query

### ISSUE THREAD

**Issue by Izayda** [vendure-ecommerce/vendure#807]
**Describe the bug**
After updating to beta6, trying to visit Collection tab in Admin UI.
Error "Cannot take more than 1000 results from a list query" appears.

**To Reproduce**
1. Login to admin UI
2. Click on Collections tab
3. See error

**Expected behavior**
A list of collections appears

**Environment (please complete the following information):**
 - @vendure/core version: beta6

**Additional context**
Bug can be easily reproduce in master branch on any DB.

**Comment by Izayda** [comment]
![image](https://user-images.githubusercontent.com/8737418/113431925-299ed100-93e5-11eb-82e6-3558b43a0e22.png)

**Comment by michaelbromley** [comment]
Oh damn good catch! OK, work-around for now is to add

```
apiOptions: {
  adminListQueryLimit: 100000,
}
```
to your config. Will fix this in the next release.
