### ISSUE TITLE
product query by slug returns only 1 asset

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#820]
**Describe the bug**
When executing the `product` query with the `slug` argument, only a single Asset is returned. 

**To Reproduce**
1. Set up a Product with multiple Assets
2. Query it using `{ product(slug: "laptop") { assets { id } } }`
3. Only a single asset is returned.

**Expected behavior**
Should return all assets. Querying by `id` behaves correctly.

**Environment (please complete the following information):**
 - @vendure/core version: 1.0.0-beta.7
 - Nodejs version: any
 - Database (mysql/postgres etc): any

**Additional context**
Possibly introduced in commit 2ace0eb0

**Comment by Izayda** [comment]
If there is bug, than there is one more bug in `findByIds` method

**Comment by michaelbromley** [comment]
I don't think that's the case - the issue turned out to be the `.limit(1)` in the SelectQueryBuilder - this was limiting to only a single asset row being returned. The solution was to just to remove that clause. The `findByIds` does not include that clause.

**Comment by Izayda** [comment]
That's intreating! Will look how multiple db rows is merged in one product graphql response. The reason of use limiting is to get only one product after sorting. Probably, now can exists bug, when several products was found. Will test.

**Comment by michaelbromley** [comment]
Hopefully I didn't introduce a new bug - as far as i know the TypeORM `getOne()` method will automatically limit the results of the select to a single entity, even when the query might yield multiple results.

**Comment by Izayda** [comment]
Checked, you are totally right, `getOne() ` operates with `entities`, not `rows`. Sorry for thus bug!
