### ISSUE TITLE
Issue when try to add variants in products 

### ISSUE THREAD

**Issue by Vishnu436** [vendure-ecommerce/vendure#823]
I created a product a few months back ago, now i want to add variants to the product, while i am adding a variants to the product, getting issue "Transaction already started for the given connection, commit current transaction before starting a new one" and i am using the sqllite DB for the project. 

 To reproduce
1. Click on Products
2. select any one product
3. click on Manage variants
4. click on option
5. enter the option value
6. check the SKU list
7. Click on add variant
8. 
![image](https://user-images.githubusercontent.com/82510795/114703313-bc733000-9d42-11eb-965f-2857cdbf9f14.png)
9.
![image](https://user-images.githubusercontent.com/82510795/114703342-c8f78880-9d42-11eb-9e8d-7412c3bc87f8.png)
10. after that created  the variants with the lock symbol and unable to edit those variants

**Expected behavior**
variants should add and when adding items to the cart and in preview cart it should have a variants dropdown

**Environment (please complete the following information):**
 - @real-world-vendure
 - @Storefront 
 - Database (sqllite):
 
![image](https://user-images.githubusercontent.com/82510795/114703785-62bf3580-9d43-11eb-8b76-9a403f07ee3e.png)

**Comment by michaelbromley** [comment]
Thanks for the report. 1 further question - can you tell me which driver package you are using for SQLite? Either `sqlite3` or `better-sqlite3`?
