### ISSUE TITLE
Custom fields list issue

### ISSUE THREAD

**Issue by Arechiga13** [vendure-ecommerce/vendure#836]
**Describe the bug**
When I configure customFields in VendureConfig and use the option "list: true" the Entity has lists in the custom field but not in the input, so I can't add the custom field correctly.

**To Reproduce**
1. Add customfield on OrderLine entity with the option "list: true"
2. Check OrderLineCustomFields definition.
3. Check OrderLineCustomFieldsInput.

**Expected behavior**
OrderLineCustomFieldsInput have the same structure in the custom field like OrderLineCustomFields when in configure it like a list.

**Environment (please complete the following information):**
 - @vendure/core version: "0.18.4"
 - Nodejs version: v14.15.1
 - Database (mysql/postgres etc): postgres

**Additional context**

```
customFields: {
        OrderLine: [
            {name: 'seatId', type: 'string', nullable: true, list: true},
            {name: 'seatOwn', type: 'string', nullable: true, list: true},
            {name: 'seatRow', type: 'string', nullable: true, list: true},
            {name: 'seatSection', type: 'string', nullable: true, list: true},
            {name: 'eTicketEmail', type: 'string', nullable: true, list: true},
            {name: 'eTicketName', type: 'string', nullable: true, list: true},
            {name: 'eTicketPhone', type: 'string', nullable: true, list: true},
            {name: 'test', type: 'int', list: true}
        ]
    }
```

```
type OrderLineCustomFields {
  seatId: [String!]
  seatOwn: [String!]
  seatRow: [String!]
  seatSection: [String!]
  eTicketEmail: [String!]
  eTicketName: [String!]
  eTicketPhone: [String!]
  test: [Int!]
}
```

```
type OrderLineCustomFieldsInput {
  seatId: String
  seatOwn: String
  seatRow: String
  seatSection: String
  eTicketEmail: String
  eTicketName: String
  eTicketPhone: String
  test: Int
}
```

**Comment by michaelbromley** [comment]
Hi,

I cannot reproduce this on the current master branch (v1.0.0-beta.10):

I copied your custom fields definitions exactly and here is the type that results -

![image](https://user-images.githubusercontent.com/6275952/115706328-cd88f600-a36d-11eb-9def-a11fce697cc7.png)
