### ISSUE TITLE
[core] Should we purge unused strings in the i18n json files?

### ISSUE THREAD

**Issue by Wanztwurst** [vendure-ecommerce/vendure#839]
I came around strings in the translation files which don't seem to be in use currently. Are these lines to be purged?
Example: errorResult.ALREADY_CANCELLED_ERROR

~~Other strings are only used in the e2e and generated type files – what about those strings? Or am I wrong here and those error codes' names aren't mentioned in the code and still used somehow?~~ Edit: Found the missing link!

**Comment by michaelbromley** [comment]
Yes, that particular error code seems to no longer be used and should be deleted. Would you like to PR this?

**Comment by Wanztwurst** [comment]
Yes, will do together with some improved translations.
