### ISSUE TITLE
Ability to define Product types with its own set of fields

### ISSUE THREAD

**Issue by nbezalwar** [vendure-ecommerce/vendure#843]
Refer to https://docs.saleor.io/docs/dashboard/configuration/products

The grouping of attributes/fields should also be defined within the product types.

eg. there can be groups for 
- Marketing
- Translation
- Shipping

**Comment by Draykee** [comment]
I'm not 100% sure what you need, but I think you can use [collections ](https://www.vendure.io/docs/typescript-api/entities/collection/) for that.

**Comment by nbezalwar** [comment]
we need grouping of custom fields within a product.

**Comment by nbezalwar** [comment]
collections is for grouping products

**Comment by michaelbromley** [comment]
Relates to #724
