### ISSUE TITLE
Bulk product selection in Admin UI

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#853]
**Is your feature request related to a problem? Please describe.**

The Products list in the Admin UI lacks the ability to bulk-select products. This would be useful for things like:

* Bulk delete
* Bulk assign to channel
* Bulk custom actions (defined by ui extensions)

**Describe the solution you'd like**
Make the list items selectable with a checkbox. Also support ctrl/shift multi-selection. One one or more items selected, a "bulk actions" button is displayed. This might be a dropdown that list the available bulk actions. This list should be extendable via ui-devkit.

**Additional context**

It would make sense to implement this for the other list views as well, we could make use of a common infrastructure and extension mechanism.

**Comment by nbezalwar** [comment]
Another useful action would be to bulk sync/clone to another channel.
Most enterprise clients would like to use channel as a pre-prod staging environment where things can be tested before promoting to Prod.

And bulk translate of-course :)
