### ISSUE TITLE
(Option) unique SKU

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#854]
**Is your feature request related to a problem? Please describe.**
SKU is an identificator and as such should be unique. This will help pairing in integrations with external system that use EAN/barcodes as unique ids for example.

**Describe the solution you'd like**
Make SKU property unique. I'm not sure if there is a use case that would need to allow duplicities in SKU - if there's any then at least a configurable option for this.
Mind the softDeletable aspect of product variants.

**Comment by neeraj-spindle** [comment]
This also ties in to replication as that is quite required for enterprise launches.
eg. you setup all your store against a pre-prod channel and once you are happy, clone all products to a PROD channel, and from there on, offer a way to promote/publish products to PROD channel. 

IMO within one channel, all products assigned should have unique SKUs.

Here is an interesting article on it.
https://medium.com/@aleksandrasays/dealing-with-mysql-nulls-and-unique-constraint-d260f6b40e60

**Comment by michaelbromley** [comment]
Note that since v1.6 it is possible to define a unique index on SKU using the EntityMetadataModifier API: https://www.vendure.io/docs/typescript-api/configuration/entity-options/#entitymetadatamodifier

**Comment by michaelbromley** [comment]
Closing this issue because with the increasing use of Vendure in multi-vendor setups, a unique SKU is not always desirable. To enforce this at the DB level one can use the EntityMetadataModifier.
