### ISSUE TITLE
core: ConfigArgService.validateRequiredFields() fails checking ShippingEligibilityChecker with required arg

### ISSUE THREAD

**Issue by Wanztwurst** [vendure-ecommerce/vendure#855]
It seems saving a shipping method with an assigned ShippingEligibilityChecker which has at least one arg with `required:true` and containing a type which can't be parsed by JSON.parse() always fails with the `configurable-argument-is-required` error.

I think the problem is the `validateRequiredFields` method, which checks the value with:
```typescript
let val: unknown;
if (inputArg) {
    try {
        val = JSON.parse(inputArg?.value);
    } catch (e) {
        // ignore
    }
}
if (val == null) {
    throw new UserInputError('error.configurable-argument-is-required', {
        name,
    });
}
```
As `inputArg.value` is a string in my case,  `JSON.parse(inputArg?.value)` throws an error (which is ignored), `val == null` evaluates to true and the validation fails.

Possible types seem to be from `ConfigArgType`: `'string' | 'int' | 'float' | 'boolean' | 'datetime' | 'ID'`. So my proposition is to change the error-evaluation to something like `!inputArg || inputArg.value === null || input.value === ""` to cover all types (not exactly sure on this, peer review please: are all type covered correctly?).

Code here: [config-arg.service.ts#L91](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/service/helpers/config-arg/config-arg.service.ts#L91)

**Comment by Wanztwurst** [comment]
I noticed booleans and null get stringified as well – is this on purpose? The tests show the same behaviour. The solution to string verifying then is to put them in double quotation marks I think.

**Comment by michaelbromley** [comment]
Thanks for the report. The reason that all datatypes get represented as strings is because the GraphQL input type `ConfigArgInput` expects a string value. With GraphQL, allowing for multiple data types in inputs is not really possible in a nice way - the technical reason is that input union types are not allowed - so this is a work around.

I think the e2e test is actually incorrect, and the server should be handling strings which are not JSON stringified. In the Admin UI, when values are submitted from such configurable operations, we apply `(value ?? '').toString()` to get the string value we will send to the GraphQL API.

**Comment by Wanztwurst** [comment]
So either the posted values of type string should be put in two pairs of quotes or the different types should be validated differently.

**Comment by michaelbromley** [comment]
Yes, but I don't want to change the current handling of string types as this would be a breaking change. I think there is a fundamental design flaw here in that every value should be already JSON stringified by the time it reaches the API. If this were the case, then we would know we could reliable apply JSON.parse() and get the correct data type. 

As it stands, there's no way to know now whether the string `"null"` should represent the `null` value, or just a string "null". That's a slight issue but probably will not have any real-world consequences outside some edge cases where "null" is some common e-commerce related word in some other language.

I think the solution should be to keep behaviour as-is, i.e. keep all existing tests passing, but then also handle un-stringified strings too.

**Comment by Wanztwurst** [comment]
`validateRequiredFields()` knows the configured type of the arg, there could be a different validation for types not parseable by JSON.

**Comment by michaelbromley** [comment]
I think the `JSON.parse()` step is actually only really useful for detecting `null` and lists (which get _do_ get JSON.stringified by the Admin UI). Let's consider each supported type, and how the Admin UI would pass it to the mutation:

```JSON
[
  {
    "name": "exampleString",
    "value": "foo"
  },
  {
    "name": "exampleInt",
    "value": "123"
  },
  {
    "name": "exampleFloat",
    "value": "123.45"
  },
  {
    "name": "exampleBoolean",
    "value": "true"
  },
  {
    "name": "exampleDate",
    "value": "2021-05-02T22:00:00.000Z"
  },
  {
    "name": "exampleID",
    "value": "13"
  }
]
```

I actually think you PR was basically correct, and the e2e test needs to be changed to get rid of the extra double quotes around the string, and we should just treat `'null'` as a string. The "throws if a required arg is null" should be changed to "throws if a required arg is empty string".

**Comment by Wanztwurst** [comment]
I think Int, Float, Bool and Null work with JSON.parse(), the others are basically strings and should be checked if they are not empty.

**Comment by michaelbromley** [comment]
That's true, but purely for the purpose of checking for "emptiness" in required fields, I think an empty string check is sufficient.

If we then want to also validate the actual data of each field, then that's another issue and would warrant its own feature request.
