### ISSUE TITLE
Customizable order list sorting in Admin UI

### ISSUE THREAD

**Issue by Markwheeler89** [vendure-ecommerce/vendure#866]
**Is your feature request related to a problem? Please describe.**
The sorting is admin UI is hard coded to a specific states. Ex. Completed is fixed to "Delivered" and "Cancelled". 
Since the order state is completely customizable, it would be better if sorting is customizable too.

**Describe the solution you'd like**
Add an option to to the sorting options to include states that the administrator wants.

**Comment by michaelbromley** [comment]
This was implemented in v2.0 +
