### ISSUE TITLE
is Vendure-ecommerce support for kafka/RabbitMQ integration as like Nestjs with graphql (https://docs.nestjs.com/microservices/kafka)

### ISSUE THREAD

**Issue by sandeepraju538** [vendure-ecommerce/vendure#869]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by michaelbromley** [comment]
I'm going to close this as no response was received. If you'd like to re-open it, please reply with the information requested.
