### ISSUE TITLE
configure a custom Order State so that it shows under "Completed" tab in Admin UI 

### ISSUE THREAD

**Issue by nbezalwar** [vendure-ecommerce/vendure#871]
Michael Bromley  2 days ago

Currently it's not possible to customize this, it is hard-coded to only display the "delivered" and "cancelled" states: https://github.com/vendure-ecommerce/vendure/blob/c1dcb19946add604d58bc8710891ff65[…]src/lib/order/src/components/order-list/order-list.component.ts
order-list.component.ts
                states: ['Delivered', 'Cancelled'],
<https://github.com/vendure-ecommerce/vendure|vendure-ecommerce/vendure>vendure-ecommerce/vendure | Added by GitHub

I think it is something we should support. In fact, since the whole order process is customizable, all the tabs should be somehow customizable, not just "completed"

**Comment by martijnvdbrug** [comment]
Closing this, as the latest versions of Vendure don't have a completed tab anymore, and you can filter by arbitrary states, including custom order states
