### ISSUE TITLE
populate the products of a specific channel

### ISSUE THREAD

**Issue by diegonc** [vendure-ecommerce/vendure#877]
The `Importer`'s method `parseAndImport` 

https://github.com/vendure-ecommerce/vendure/blob/1fb3620ce86cac7a29c747cbd3cf8cb831aa1983/packages/core/src/data-import/providers/importer/importer.ts#L51

receives the following in its second parameter:

```typescript
ctxOrLanguageCode: RequestContext | LanguageCode,
```
which gets used in the `getRequestContext` method:

```typescript
private async getRequestContext(
        ctxOrLanguageCode: RequestContext | LanguageCode,
    ): Promise<RequestContext> {
        if (ctxOrLanguageCode instanceof RequestContext) {
            return ctxOrLanguageCode;
        } else {
            const channel = await this.channelService.getDefaultChannel();
            return new RequestContext({
                apiType: 'admin',
                isAuthorized: true,
                authorizedAsOwnerOnly: false,
                channel,
                languageCode: ctxOrLanguageCode,
            });
        }
    }
```

Currently, using the `populate` interface one can only pass a language code through the `defaultLanguage` property of initialData:

https://github.com/vendure-ecommerce/vendure/blob/1fb3620ce86cac7a29c747cbd3cf8cb831aa1983/packages/core/src/cli/populate.ts#L32

This prevents the `populate` user to provide a `RequestContext` with a specific channel because, in the snippet above, the execution path always goes through the else case.

Is there anything I'm missing to populate the products of a specific channel?

**Comment by michaelbromley** [comment]
Your evaluation is correct - the current code only allows population of the default Channel. It seems like it could be fixed to allow it to take the channel id from the RequestContext.
