### ISSUE TITLE
Sqlite Custom field Changes Primary Key error

### ISSUE THREAD

**Issue by galizhan** [vendure-ecommerce/vendure#880]
**Sqlite Custom field Changes Primary Key error **
When adding custom fields, and we have already added data to database(demo data), It causes `SqliteError: FOREIGN KEY constraint failed
`error

**To Reproduce**
1. Go to 'vendure-config.ts'
2. Add 'customFields'
3. Generate migrations
4. Run migrations

**Expected behavior**
Changes have to migrated to db.

**Environment (please complete the following information):**
 - @vendure/core version:1.0.0-rc.0
 - Nodejs version: 12.0
 - Database (mysql/postgres etc): sqlite3

**Temporary fix**
I know that disableForeignKeysForSqLite function but it seems like doesn't work for this situation, so if you similar problem you can make it like this.
1. Go to 'node_modules/@vendure/core/migrate.js'
2. Find function runMigrations
3. Before try paste this code `await connection.query('PRAGMA foreign_keys=OFF');`
4. At the end of paste this code ` await connection.query('PRAGMA foreign_keys=ON');`

**Comment by michaelbromley** [comment]
Ah ok I think I know what is going on here: the `disableForeignKeysForSqLite` function is only checking for the `sqlite` driver, but since then we moved over to use the `better-sqlite3` driver by default, which would cause the check to fail.
