### ISSUE TITLE
Extending the Vendure-Email-Plugin to accept the Node-mailer "content"  parameter

### ISSUE THREAD

**Issue by Raphael-Bier** [vendure-ecommerce/vendure#882]
**Is your feature request related to a problem? Please describe.**
We want to use attachments alongside the Vendure-Email Plugin using Nodemailer, and we are limited in that manner by the Vendure email plugin since we currently only can use the "path" parameter and we will need to use the "content" parameter to send in a buffer. 

**Describe the solution you'd like**
Since Nodemailer can use the following parameter "content" to pass a buffer it could be a great addition to the email plugin.

**Describe alternatives you've considered**

**Additional context**
Node-Mailer documentation :
https://nodemailer.com/message/attachments/ 

Vendure documentation relating to the email attachments and stating that only the path parameter is available for now : 
https://www.vendure.io/docs/typescript-api/email-plugin/email-event-handler/#setattachments

Feature Request suggestion on the Vendure Slack :
https://app.slack.com/client/TKY7HFU04/CKYMF0ZTJ/thread/CKYMF0ZTJ-1621233428.206000

**Comment by michaelbromley** [comment]
I just realised the reason that I left out support for content as a buffer: email are send via the job queue, and all jobs get serialized when put into the job queue. But this should still be doable since I believe it is possible to serialize and deserialize buffers.
