### ISSUE TITLE
Products listing is not displayed if we change the channel language

### ISSUE THREAD

**Issue by rahulpalresha** [vendure-ecommerce/vendure#883]
Products listing is not displayed if we change the channel language

Assumptions:  Consider default channel language is English (EN)

**Steps to reproduce:**
1. Navigate to Catalog > Products
2. Observe the list of products that are present in the system catalog
3. Now navigate to Settings > Channels
4. Change the Default language to say e.g. German (de) or French (fr) considering they are already added in the languages list for the system
5. Save the changes
6. Now again navigate to Catalog > Products

**Expected behavior**
1. Products listing should not be blank if the channel language is changed

**Environment**
https://demo.vendure.io/

**Comment by michaelbromley** [comment]
What is happening here is that the product list is only showing results which have translations in the default channel language. So in your case, if switching to e.g. French, and no Products have yet been translated into French, then you see an empty list. 

Perhaps an ideal solution would be to display _all_ products, and display them in the default language of the Channel _if available_, else display them in some fallback language. However, this might not be feasible with the current way that the search index works.

Another solution (which is a missing feature anyway) would be to add a language selector to the top of the list, allowing you to set the language manually and view all Products translated into that language. I will add this to the next minor release.
