### ISSUE TITLE
admin-ui: Support custom field controls in FulfillmentDetail & OrderTable 

### ISSUE THREAD

**Issue by Wanztwurst** [vendure-ecommerce/vendure#887]
`order-table.component.html` and `fulfillment-detail.component.html` are not using the component `vdr-custom-field-control` for their custom fields – hence the controls are not configurable to use a different module with `registerCustomFieldComponent()`.

Is this specialized behaviour intentional?

[fulfillment-detail](https://github.com/vendure-ecommerce/vendure/blob/ad5bc2b012852056dff79db8c30ce5f5cb5bf42f/packages/admin-ui/src/lib/order/src/components/fulfillment-detail/fulfillment-detail.component.html#L14-L21):
```html
<ng-container *ngFor="let customField of customFields">
    <vdr-labeled-data [label]="customField.key">
        <vdr-object-tree
            *ngIf="customFieldIsObject(customField.value); else primitive"
            [value]="{ object: customField.value }"
        ></vdr-object-tree>
        <ng-template #primitive>
            {{ customField.value }}
        </ng-template>
    </vdr-labeled-data>
</ng-container>
```

[order-table](https://github.com/vendure-ecommerce/vendure/blob/ad5bc2b012852056dff79db8c30ce5f5cb5bf42f/packages/admin-ui/src/lib/order/src/components/order-table/order-table.component.html#L63-L82):
```html
<div class="order-line-custom-fields">
    <div class="custom-field" *ngFor="let field of customFields">
        <vdr-labeled-data [label]="field.config | customFieldLabel">
            <div class="mt2" [ngSwitch]="field.config.type">
                <ng-template [ngSwitchCase]="'datetime'">
                    <span [title]="field.value">{{ field.value }}</span>
                </ng-template>
                <ng-template [ngSwitchCase]="'boolean'">
                    <ng-template [ngIf]="field.value === true">
                        <clr-icon shape="check"></clr-icon>
                    </ng-template>
                    <ng-template [ngIf]="field.value === false">
                        <clr-icon shape="times"></clr-icon>
                    </ng-template>
                </ng-template>
                <ng-template ngSwitchDefault>
                    {{ field.value }}
                </ng-template>
            </div>
        </vdr-labeled-data>
    </div>
</div>
```

**Comment by michaelbromley** [comment]
I think its like this just because I wanted to at least display the values of the custom fields. But you are right that we should support custom controls here too.

I'll add it to the backlog for the next minor release.
