### ISSUE TITLE
wrong refund total in createRefund method

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#890]
**Describe the bug**
When modifying an order to lower amount with need of a refund then in UI in the preview change and later on in the history entry it shows correct refund amount but the actual value passed to createRefund function differs and doesn't match the calculated total which then results in wrong amount being refunded and impossibile transition from "Modifying" to PaymentSettled due to: _"Cannot transition Order to the "PaymentSettled" state when the total is not covered by settled Payments"_
I have console logged the "amount" parameter in the payment handler createRefund function and there is the wrong amount coming in.

![pvp](https://user-images.githubusercontent.com/15977485/119353405-21f00000-bca3-11eb-995b-cb06b78d724c.png)

Note to say that we have promotion on such order (though the preview window showed correct calculation of everything).

**Environment (please complete the following information):**
 - @vendure/core version: v1.0.0

**Comment by chladog** [comment]
could it be related to this? (was the problem/update applied for refunds as well?) https://github.com/vendure-ecommerce/vendure/commit/1795f487c8f8f0e146718d31b02fda94fc9a5c4c

**Comment by michaelbromley** [comment]
I can reproduce this class of error when the order has a promotion applied, and without a promotion it works as expected. Looks like I missed some code path on the modification logic. Fixing this now.
