### ISSUE TITLE
Pricing issue

### ISSUE THREAD

**Issue by mohamadCh215** [vendure-ecommerce/vendure#891]
I would like to use Vendure for my app, but I need to use a "tiered price".
Is this possible using Plug-in and packages, or not?

**Comment by michaelbromley** [comment]
Hi,

Yes, depending on your exact requirements you should be able to achieve this using a custom [OrderItemPriceCalculationStrategy](https://www.vendure.io/docs/typescript-api/orders/order-item-price-calculation-strategy/), possibly with custom fields on the ProductVariant to hold tier information.

**Comment by mohamadCh215** [comment]
I read your description in Github about the
orderItemPriceCalculationStrategy vs promotions.
In my case, the price depends on the quantity, and I may implement
discounts and special offers.
So, can I do this using promotions?

**Comment by michaelbromley** [comment]
Ah yes, with the quantity this will not apply, you are right. In that case, a promotion with a custom PromotionItemAction may be suitable.

**Comment by mohamadCh215** [comment]
Great, thanks!

**Comment by mohamadCh215** [comment]
Just one more thing,
I'm going to use vendure for e-commerce Business to Business, so I need to
modify the admin interface and add plug-ins for quotations and other b2b
features.
What are the recommended approaches to do this using vendure?

**Comment by michaelbromley** [comment]
See this section of the docs regarding extending the Admin UI: https://www.vendure.io/docs/plugins/extending-the-admin-ui/

and plugins in general: https://www.vendure.io/docs/plugins/
