### ISSUE TITLE
adding a custom field.

### ISSUE THREAD

**Issue by mohamadCh215** [vendure-ecommerce/vendure#897]
I'm new to backend so I go step by step with the documentation.
I write this inside the vendure-config.js:
customFields: {
     Product: [
            { name: 'infoUrl', type: 'string' },
            { name: 'downloadable', type: 'boolean' },
            { name: 'shortName', type: 'localeString' },
        ],
        FacetValue: [{ name: 'icon', type: 'string' }]
  }

but I'm getting error, I didn't modify the code anywhere else yet.
The error:
 no such column: facet__values.customFieldsIcon
 SqliteError: no such column: facet__values.customFieldsIcon at Database.prepare

Doesn't it suppose to create those fields?

**Comment by michaelbromley** [comment]
Hi,
Do you have `dbConnectionOptions.synchronize` set to `true`? If not, Vendure will not create the necessary DB columns automatically.

**Comment by mohamadCh215** [comment]
When running the migrate file, it drop the table than recreated.
But the problem is when you drop it, the relation with the other tables
breaks.

I create a field in "Facet", after the migrate I start receiving an error
of "no translation found"

**Comment by michaelbromley** [comment]
Do you happen to still have the generated migration file? Could you post it?

**Comment by mohamadCh215** [comment]
Yes, I do.

1622206679271-facet-name-field.ts
import {MigrationInterface, QueryRunner} from "typeorm";

export class facetNameField1622206679271 implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(
`CREATE TABLE "temporary_facet_value" ("createdAt" datetime NOT NULL
DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT
(datetime('now')), "code" varchar NOT NULL, "id" integer PRIMARY KEY
AUTOINCREMENT NOT NULL, "facetId" integer, "customFieldsIcongfgfgfff"
varchar(255), CONSTRAINT "FK_d101dc2265a7341be3d94968c5b" FOREIGN KEY
("facetId") REFERENCES "facet" ("id") ON DELETE CASCADE ON UPDATE NO
ACTION)`
, undefined);
        await queryRunner.query(
`INSERT INTO "temporary_facet_value"("createdAt", "updatedAt", "code",
"id", "facetId") SELECT "createdAt", "updatedAt", "code", "id",
"facetId" FROM "facet_value"`
, undefined);
        await queryRunner.query(`DROP TABLE "facet_value"`, undefined);
        await queryRunner.query(
`ALTER TABLE "temporary_facet_value" RENAME TO "facet_value"`, undefined);
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(
`ALTER TABLE "facet_value" RENAME TO "temporary_facet_value"`, undefined);
        await queryRunner.query(
`CREATE TABLE "facet_value" ("createdAt" datetime NOT NULL DEFAULT
(datetime('now')), "updatedAt" datetime NOT NULL DEFAULT
(datetime('now')), "code" varchar NOT NULL, "id" integer PRIMARY KEY
AUTOINCREMENT NOT NULL, "facetId" integer, CONSTRAINT
"FK_d101dc2265a7341be3d94968c5b" FOREIGN KEY ("facetId") REFERENCES
"facet" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`
, undefined);
        await queryRunner.query(
`INSERT INTO "facet_value"("createdAt", "updatedAt", "code", "id",
"facetId") SELECT "createdAt", "updatedAt", "code", "id", "facetId"
FROM "temporary_facet_value"`
, undefined);
        await queryRunner.query(`DROP TABLE "temporary_facet_value"`,
undefined);
   }

}


1622206679271-facet-name-field.js
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P
, generator) {
    function adopt(value) { return value instanceof P ? value : new P(
function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); }
catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); }
catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(
result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next
());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return
t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2
) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() {
return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"
] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1
])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1
]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3
]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t
 = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op
); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0,
done: true };
    }
};
exports.__esModule = true;
exports.facetNameField1622206679271 = void 0;
var facetNameField1622206679271 = /** @class */ (function () {
    function facetNameField1622206679271() {
    }
    facetNameField1622206679271.prototype.up = function (queryRunner) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, queryRunner.query(
"CREATE TABLE \"temporary_facet_value\" (\"createdAt\"
 datetime NOT NULL DEFAULT (datetime('now')), \"updatedAt\"
 datetime NOT NULL DEFAULT (datetime('now')), \"code\" varchar NOT NULL, \"
id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"facetId\" integer, \"
customFieldsIcongfgfgfff\" varchar(255), CONSTRAINT \"
FK_d101dc2265a7341be3d94968c5b\" FOREIGN KEY (\"facetId\") REFERENCES \"
facet\" (\"id\") ON DELETE CASCADE ON UPDATE NO ACTION)", undefined)];
                    case 1:
                        _a.sent();
                        return [4 /*yield*/, queryRunner.query("INSERT INTO
\"temporary_facet_value\"(\"createdAt\", \"updatedAt\", \"code\", \"id\", \"
facetId\") SELECT \"createdAt\", \"updatedAt\", \"code\", \"id\", \"facetId
\" FROM \"facet_value\"", undefined)];
                    case 2:
                        _a.sent();
                        return [4 /*yield*/, queryRunner.query("DROP TABLE
\"facet_value\"", undefined)];
                    case 3:
                        _a.sent();
                        return [4 /*yield*/, queryRunner.query("ALTER TABLE
\"temporary_facet_value\" RENAME TO \"facet_value\"", undefined)];
                    case 4:
                        _a.sent();
                        return [2 /*return*/];
                }
            });
        });
    };
    facetNameField1622206679271.prototype.down = function (queryRunner) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, queryRunner.query(
"ALTER TABLE \"facet_value\" RENAME TO \"temporary_facet_value\"", undefined
)];
                    case 1:
                        _a.sent();
                        return [4 /*yield*/, queryRunner.query(
"CREATE TABLE \"facet_value\" (\"createdAt\"
 datetime NOT NULL DEFAULT (datetime('now')), \"updatedAt\"
 datetime NOT NULL DEFAULT (datetime('now')), \"code\" varchar NOT NULL, \"
id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"facetId\"
 integer, CONSTRAINT \"FK_d101dc2265a7341be3d94968c5b\" FOREIGN KEY (\"
facetId\") REFERENCES \"facet\" (\"id\"
) ON DELETE CASCADE ON UPDATE NO ACTION)", undefined)];
                    case 2:
                        _a.sent();
                        return [4 /*yield*/, queryRunner.query("INSERT INTO
\"facet_value\"(\"createdAt\", \"updatedAt\", \"code\", \"id\", \"facetId\"
) SELECT \"createdAt\", \"updatedAt\", \"code\", \"id\", \"facetId\" FROM \"
temporary_facet_value\"", undefined)];
                    case 3:
                        _a.sent();
                        return [4 /*yield*/, queryRunner.query("DROP TABLE
\"temporary_facet_value\"", undefined)];
                    case 4:
                        _a.sent();
                        return [2 /*return*/];
                }
            });
        });
    };
    return facetNameField1622206679271;
}());
exports.facetNameField1622206679271 = facetNameField1622206679271;

**Comment by mohamadCh215** [comment]
Note: I'm  using SQLite, and I only added 1 line of code:
FacetValue: [{ name: 'icon', type: 'string'}]
dbconnectionoption.synchronize is set to true.

**Comment by michaelbromley** [comment]
Thanks for the info. Looks like it might be related to https://github.com/typeorm/typeorm/issues/5381

The TypeORM SQLite driver seems to have some trouble around migrations. I recommend you try with another DBMS such as Postgres or MySQL.
