### ISSUE TITLE
Error: Initializing server ...

### ISSUE THREAD

**Issue by NuruddinBadawi** [vendure-ecommerce/vendure#90]
I get this error 

when creat app with SQL database, show this error
```
Initializing server
 1: 0x10003c597 node::Abort() [/usr/local/bin/node]
 2: 0x1000bc617 node::Chdir(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 3: 0x10023663f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 4: 0x100235b81 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 5: 0x100235220 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
```

when running the app this error
```
[Nest] 6131   - 04/21/2019, 9:30 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +9652ms
Error: connect ETIMEDOUT
```

node: v10.15.3
Server version: 10.3.14-MariaDB Homebrew
npm: 6.9.0

**Comment by michaelbromley** [comment]
Hi,

The error says that TypeOrm cannot connect to the database. This is usually cause by a wrong configuration. Check your connection settings in the vendure config file.

**Comment by NuruddinBadawi** [comment]
this before creates the project, just I'm trying to create a new one using SQL/MariaDB
![Screen Shot 2019-04-23 at 8 43 31 PM](https://user-images.githubusercontent.com/5736522/56603668-d3c22b80-6608-11e9-9b07-5ae39549d4d0.png)

**Comment by michaelbromley** [comment]
Ok, thanks for the screenshot ,that helps.

I see you are using all the default connection settings. Are you *sure* you are running MariaDB at 192.168.99.100, with the username "root" and no password, and that you have created a database in it named "vendure"? Check all those things because that is how Vendure is trying to connect based on the way you answered the questions in the screen shot.

**Comment by NuruddinBadawi** [comment]
yeh, I thought it's creating the database for me Hahaaha
thank you @michaelbromley

**Comment by michaelbromley** [comment]
Ah ok. I'll add some hint with the error message then to cover this case.
