### ISSUE TITLE
ES plugin to allow arrays in graphQlType 

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#903]
**Is your feature request related to a problem? Please describe.**
In customMappings of ES plugin we set the graphQlType, however it's currently not possible to define array.

**Describe the solution you'd like**
Allow to have an array in customMapping e.g.:
graphQlType: [String!]

**Comment by Izayda** [comment]
@michaelbromley hmm, seems this issue was closed by #1054

**Comment by michaelbromley** [comment]
Indeed, thanks!
