### ISSUE TITLE
DB<postgresql> yarn populate not working

### ISSUE THREAD

**Issue by mohamadCh215** [vendure-ecommerce/vendure#905]
I was following the steps in the github vendure-ecommerce/vendure and everything was working until step 4.3Populate mock data:
 cd packages/dev-server
 DB=<mysql|postgres|sqlite> yarn populate

I'm using postgres13 so my command was:
DB=<postgres> yarn populate

I change the username and password in the dev-config.ts file

Expectation: everything will work
What I got: The system cannot find the file specified.

**Comment by michaelbromley** [comment]
Hi,

Is there any more to the error? E.g. which file cannot be found?

**Comment by mohamadCh215** [comment]
NO, this is everything:



*C:\Users\HP\navybits\b2b_backend_clone\vendure\packages\dev-server>DB=<postgres>
yarn populateThe system cannot find the file specified.*

I skipped step 4.3 and 5 because of this, but this caused me other problems.
Like, after running yarn run (step 6) I have:



*** Angular Live Development Server is listening on localhost:4200, open
your browser on http://localhost:4200/admin <http://localhost:4200/admin>
**√ Compiled successfully.*

But when opening localhost4200 I got

Cannot connect to the Vendure server at http://localhost:3000

**Comment by michaelbromley** [comment]
Try  `DB=postgres yarn populate` (without the angle brackets).

**Comment by mohamadCh215** [comment]
I try it before i contact you
It give:
'DB' is not recognized as an internal or external command, operable program
or batch file.

**Comment by michaelbromley** [comment]
OK. I think this is because you are using Windows and a shell that does not understand setting environment variables in this way. I also use Windows but I use [git bash](https://gitforwindows.org/) when working on the command line. Try that.

**Comment by mohamadCh215** [comment]
No luck yet.

HP@AbouFayssal MINGW64 ~/navybits/b2b_backend_clone/vendure (master)
$ cd packages/dev-server

HP@AbouFayssal MINGW64
~/navybits/b2b_backend_clone/vendure/packages/dev-server (master)
$ DB=<postgres> yarn populate
bash: postgres: No such file or directory

HP@AbouFayssal MINGW64
~/navybits/b2b_backend_clone/vendure/packages/dev-server (master)
$ DB=postgres yarn populate
Internal Error: ***@***.***:.: This package doesn't seem to be
present in your lockfile; try to make an install to update your resolutions
    at J.getCandidates
(C:\Users\HP\navybits\b2b_backend_clone\vendure\.yarn\releases\yarn-berry.cjs:2:348376)
    at n.getCandidates
(C:\Users\HP\navybits\b2b_backend_clone\vendure\.yarn\releases\yarn-berry.cjs:2:337366)
    at
C:\Users\HP\navybits\b2b_backend_clone\vendure\.yarn\releases\yarn-berry.cjs:2:359022
    at Module.w
(C:\Users\HP\navybits\b2b_backend_clone\vendure\.yarn\releases\yarn-berry.cjs:2:418493)
    at C
(C:\Users\HP\navybits\b2b_backend_clone\vendure\.yarn\releases\yarn-berry.cjs:2:358985)

**Comment by mohamadCh215** [comment]
I tried to redo all the steps
yarn work
(yarn help work)
yarn bootstrap didn't work
yarn build didn't work

I'm using git bash

**Comment by michaelbromley** [comment]
Ok. Might be an incompatibility with Yarn v2. You can try it with Yarn v1.x

Also - just to back up a bit - why are you trying to get the development repo building locally? Are you intending to modify the core?

**Comment by mohamadCh215** [comment]
Because I might need to add some log for debugging purposes.

**Comment by michaelbromley** [comment]
ok. You might also want to consider just directly adding the log statements to the compiled JS files in the `node_modules/@vendure/core` dir of your project. That's how I do it if I ever need to debug library code.

**Comment by michaelbromley** [comment]
Hi, I'm going to close this because it seems like an environment issue, and there's no actionable issue I can fix with Vendure here.
