### ISSUE TITLE
Vue Storefront integration

### ISSUE THREAD

**Issue by kibertoad** [vendure-ecommerce/vendure#907]
**Is your feature request related to a problem? Please describe.**

https://www.vendure.io/blog/2021/05/announcing-vendure-v1.0/ mentioned planned integration with Vue Storefront. This ticket could be used to track this effort.

**Describe the solution you'd like**
Seamless, documented, out-of-the-box integration with Vue Storefront.

**Comment by kibertoad** [comment]
We are currently exploring Vendure as a platform and would like to contribute some development resource towards this particular effort. Is there anything we could help with?

**Comment by michaelbromley** [comment]
Hi, there is an ongoing project for an official integration: https://github.com/vuestorefront/vendure

It is still in the early stages, but there are a couple of people from the Vendure community working on it. There is a dedicated Vendure channel in the Vue Storefront discord (http://discord.vuestorefront.io/) where you can coordinate your efforts with those already working on it.

**Comment by kibertoad** [comment]
Thanks a lot!

**Comment by michaelbromley** [comment]
Closing this now. For further discussion see the related discussion thread: https://github.com/vendure-ecommerce/vendure/discussions/694
