### ISSUE TITLE
Some of the generated types are committed

### ISSUE THREAD

**Issue by kibertoad** [vendure-ecommerce/vendure#909]
**Describe the bug**
Some of the generated types are committed to the repo, for an example: https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/common/error/generated-graphql-admin-errors.ts, but there are more.

**Expected behavior**
All generated code is generated on runtime

Are there any reasons why these files are there, or they can be dropped, and .gitignore rule can be added?

**Comment by michaelbromley** [comment]
These need to be committed, because the types from these generated files are used in the core itself. E.g. the resolver functions use generated input types. If we did not commit them, then upon cloning the repo it would be impossible to build the project, and thus impossible to generate the types.

**Comment by kibertoad** [comment]
Got it! Thank you for the clarification.
