### ISSUE TITLE
Compile UI Extensions does not pass --base-href and --outputPath if yarn is not installed

### ISSUE THREAD

**Issue by mattgills** [vendure-ecommerce/vendure#916]
**Describe the bug**
When running `compileUiExtensions` we noticed that the base href was not being passed through to the `npm run build` command.  As a result, the Admin UI would not contain the correct base href.  A manual fix was found and is listed in the Additional Context Section.  We also found that if yarn is installed on the machine, then the error does not occur.  The compiler will automatically select yarn and the build arguments are passed through correctly

**To Reproduce**
1. Remove yarn from your computer
2. Run the compile ui extensions function
3. See that the build command uses `npm` and will no include the `--base-href` and `--outputPath` arguments

**Expected behavior**
The compiler should pass the arguments through for both npm and yarn.

**Environment (please complete the following information):**
 - @vendure/core version: 1.0.1
 - Nodejs version: 12.18.4
 - NPM version: 6.14.6
 - Database (mysql/postgres etc): postgres

**Additional context**
A manual fix could be made by modifying the `node_modules/@vendure/ui-devkit/compiler/compile.js` file:
```
// Old Code Snippet
.spawn(cmd, ['run', 'build', `--outputPath=${distPath}`, `--base-href=${baseHref}`], ... 

// New Code Snippet
.spawn(cmd, ['run', 'build', '--', `--outputPath=${distPath}`, `--base-href=${baseHref}`], ...
```

The addition of the `'--'` allows for the arguments to be passed through to the npm command.

I will attempt to fix this and open a PR.

**Comment by michaelbromley** [comment]
Thanks for the report. I will wait on your PR and it will go in the next release. If for any reason you are unable to make the PR, just let me know and I'll make the fix.

**Comment by mattgills** [comment]
I would definitely like to pursue this, however, I did run into an issue working with the compiler in the repo.  I started a [thread](https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1622662110142600) in the Slack channel, if you are able to provide any feedback there.

**Comment by simpian** [comment]
this is in fact a very important fix for aws ebs to work.

can this be merged anytime soon?

**Comment by mattgills** [comment]
@simpian I haven't had a chance to address this yet, but we do have a docker build work around that modifies that text in the node_modules directory.  Perhaps this is helpful to you in the meantime:
```
RUN sed -i "s/build', \`--outputPath/build', '--', \`--outputPath/" node_modules/@vendure/ui-devkit/compiler/compile.js
```
Not an ideal solution, but has been a reliable option in the short term.
