### ISSUE TITLE
Exchange graphql-iso-date for graphql-scalars

### ISSUE THREAD

**Issue by hendrik-advantitge** [vendure-ecommerce/vendure#919]
**Is your feature request related to a problem? Please describe.**
The graphql-iso-date repo is no longer maintained, see this [commit](https://github.com/excitement-engineer/graphql-iso-date/commit/1a284683e34b1d4d2457b38df4ce620556fcd8c9).
It is advised to switch over to [graphql-scalars](https://github.com/Urigo/graphql-scalars) instead.

**Comment by michaelbromley** [comment]
Thanks for the notice. I'll change deps in the next minor release.
