### ISSUE TITLE
Extending the ConfigurableOperationDefOptions

### ISSUE THREAD

**Issue by Raphael-Bier** [vendure-ecommerce/vendure#930]
We currently can add Custom fields pretty Easily with Vendure on Fulfillment or on Order without the need to Customize the admin UI.

For the fulfillment process we have some API calls that will end up printing some PDF files for labels, and it would be great to be able to use some input-type-button, in the same manner as ConfigurableOperationDefOptions   to regenerate them.

**Describe the solution you'd like**
Adding the same kind of solution that you already implemented for other input type in ConfigurableOperationDefOptions.ui.component 

**Describe alternatives you've considered**
One alternative solution could be to create / Extend the admin UI with the Dev-kit Ui plugin
but we think it could be a helpful

**Comment by michaelbromley** [comment]
Closing this as it was implemented, see https://www.vendure.io/docs/typescript-api/configurable-operation-def/config-args/#ui-component
