### ISSUE TITLE
Incorrect Quantity Adjustments

### ISSUE THREAD

**Issue by WilliamMilne** [vendure-ecommerce/vendure#931]
**Describe the bug**
In two cases, we were getting an incorrect quantity update to an order line item: 
1. When low stock was available, adjusting an order line, THEN adding that same item to order was causing us to get past the hard cap on the stock of that item.
2. The result from `constrainQuantityToSaleable` appears to be two distinct values depending on the situation: if no adjustment is needed, it is the correct new quantity of the item, but if the desired quantity is above the stock limit then it will return the differential between the existing stock in cart and the maximum stock allowed. 

**To Reproduce**
1. Create a product with 2 stock. 
2. Add it to order with quantity 2. (addItemToOrder mutation triggered)
3. Adjust the order line by incrementing by 1. (adjustOrderLine mutation triggered)
4. Add the item to order again. (addItemToOrder mutation triggered again)
5. You will see the line item quantity become 3. 

**Expected behavior**
1. We expect the stock of an item in cart to never exceed the available stock that the store has.
2. We expect the user to try to add 1000 stock of an item to cart. If they do, we want their cart to be filled with exactly the remaining inventory.
3. If the user already has an item in cart and tries to add more than the store has, we want to see the maximum available stock value in their cart. 

**Environment (please complete the following information):**
 - @vendure/core version: 1.0.1
 - Nodejs version 12.20.2
 - Database (mysql/postgres etc): postgres

**Additional context**
We seem to have solved the problem but are having trouble with the PR process. The two fixes required are: 
In order.service.ts: 
1. Change line 451 from: 
``` await this.orderModifier.updateOrderLineQuantity(ctx, orderLine, quantity, order);```
to: 
```await this.orderModifier.updateOrderLineQuantity(ctx, orderLine, correctedQuantity, order);```

2. Change line 403 from: 
```await this.orderModifier.updateOrderLineQuantity(ctx, orderLine, correctedQuantity, order);```
to: 
```
if (correctedQuantity < quantity) {
    const newQuantity = (existingOrderLine ? existingOrderLine?.quantity : 0) + correctedQuantity;
    await this.orderModifier.updateOrderLineQuantity(ctx, orderLine, newQuantity, order);
} else {
    await this.orderModifier.updateOrderLineQuantity(ctx, orderLine, correctedQuantity, order);
}
```
        
This second change must occur because we need to treat the correctedQuantity value differently if it was modified. There is probably a longer-term fix here, but this patch will solve the problem in our experience.

**Comment by michaelbromley** [comment]
Hi, thanks for the detailed report. What trouble are you having with the PR process?

**Comment by WilliamMilne** [comment]
Hi @michaelbromley, I think my issue is that I wasn't building things properly when making the modifications! Then I got really busy with other things for about a month, haha. But I've opened a PR now and would appreciate any and all feedback on it! 

https://github.com/vendure-ecommerce/vendure/pull/983
