### ISSUE TITLE
Add metadata parameter to Logger

### ISSUE THREAD

**Issue by ttournie** [vendure-ecommerce/vendure#936]
**Is your feature request related to a problem? Please describe.**
Right now, it's not possible to use send Json metadata in the Logger (for me I use the context as 'any').
It's really useful to get extra metadata on some log, specially when using Datadog along with Winston

**Describe the solution you'd like**
A new optional parameter 'metadata' in all Logger function that can take an object should do the trick

**Comment by michaelbromley** [comment]
Closing as a duplicate of #1444
