### ISSUE TITLE
Support for graphql federation

### ISSUE THREAD

**Issue by dwelch2344** [vendure-ecommerce/vendure#938]
We’ve been following this project for years and love what we’re seeing here, so first off congrats on 1.0! 

We have some sprints coming up to investigate what a migration to V would look like but one of our biggest questions was if graphql federation is supported. We’re currently running a distributed micro service architecture w GQLFed from Apollo (it’s amazing) so this would be a huge baked in win / something we’d look at contributing if not currently implemented, so figured I’d ask as we didn’t see it in docs / code / issues. 

Has this been looked at before? Any thoughts / comments / appetite for it?

**Comment by michaelbromley** [comment]
Hi, thanks!

I've not looked into federation before as I've not had the need and to be honest I don't have a deep understanding of it or its use cases. I'm happy to look into support for it, maybe you could give me a high level overview of what would need to be done and we can collaborate on getting support implemented.

**Comment by michaelbromley** [comment]
I'm closing this but if anyone has anything to add on this topic feel free to comment and if there's something actionable we can re-open.
