### ISSUE TITLE
Duplicate key violation

### ISSUE THREAD

**Issue by hendrik-advantitge** [vendure-ecommerce/vendure#950]
**Describe the bug**
When running multiple API instances in parallel, race conditions occur in the `assignToChannels` function throwing duplicate key violation errors.

**To Reproduce**
1. Run 2 API instances
2. Create a Product on 1 API instance
3. Simultaneously add a different ProductVariant to the Product on each API instance
4. Sometimes the error will occur

**Expected behavior**
The check and insert in the database should be an atomic operation

**Environment (please complete the following information):**
 - @vendure/core version: 1.0.2
 - Nodejs version: 14
 - Database: postgres

**Comment by hendrik-advantitge** [comment]
https://github.com/typeorm/typeorm/issues/1090#issuecomment-634391487 might hold the solution to this issue

**Comment by michaelbromley** [comment]
Hi,
I'm looking in to this now but it's difficult to reproduce manually. I think I'd have to create a script to do so in order to reproduce the conditions required.

So before I go down that route, is there any more detail you can provide? What is the key that is being violated when it occurs? Are you able to use query logging to provide the query that triggers the violation?

**Comment by hendrik-advantitge** [comment]
Hi Michael
Absolutely, the query we are having trouble with is this one:
`await queryRunner.query('CREATE TABLE "product_channels_channel" ("productId" integer NOT NULL, "channelId" integer NOT NULL, CONSTRAINT "PK_722acbcc06403e693b518d2c345" PRIMARY KEY ("productId", "channelId"))', undefined); `

As far as the setup goes to reproduce this error:
- One SQL database (Postgres in our case)
- Two separate, parallel, Vendure-server instances
- Two Channels should exist, `default` and another one `channel-1`
- One Product (`p1`) with two ProductVariants (`pv1` and `pv2`) should exist on the `default` Channel

To trigger the error, we use the `AssignProductVariantToChannel` mutation. One Vendure instance assigns `pv1` to `channel-1`, the other assigns `pv2` to `channel-1`. 
Both mutations will attempt to assign `p1` to `channel-1`, and that is where we get the error. 

Hope this helps. If you have any more questions do not hesitate to reach out to me!

**Comment by michaelbromley** [comment]
Thanks for the extra detail, but I'm confused about the query - why `CREATE TABLE`?

**Comment by hendrik-advantitge** [comment]
Hi Michael, that is totally wrong on my part. I do sadly not have a log of the query at the moment.

I know however for a fact that the error occurs in the `assignToChannels` function of the `ChannelService`.
```
const entity = await this.connection.getEntityOrThrow(ctx, entityType, entityId, {
    relations: ['channels'],
});
for (const id of channelIds) {
    const channel = await this.connection.getEntityOrThrow(ctx, Channel, id);
    entity.channels.push(channel);
}
await this.connection.getRepository(ctx, entityType).save(entity as any, { reload: false }); <-- error is thrown here
return entity;
```

**Comment by michaelbromley** [comment]
Ok thanks for the clarification. If at some point you get access to the log of the query, post it here.

**Comment by martijnvdbrug** [comment]
@hendrik-advantitge Is still still an issue? There have been quite a few upgrades, including the TypeOrm version.

**Comment by michaelbromley** [comment]
We'll close this - AFAIK Hendrik isn't working on that app anymore.
