### ISSUE TITLE
error TS2307: Cannot find module '@vendure/ui-devkit/compiler' or its corresponding type declarations

### ISSUE THREAD

**Issue by u007** [vendure-ecommerce/vendure#967]
**Describe the bug**
using latest vendure, but when tried to add admin ui plugin, getting this
error TS2307: Cannot find module '@vendure/ui-devkit/compiler' or its corresponding type declarations

**To Reproduce**
```
npm i --save @vendure/ui-devkit
```
add this into vendure-config.ts

```
import { compileUiExtensions } from '@vendure/ui-devkit/compiler';
import { FavoritesPlugin } from "vendure-favorites-plugin";//example
//...
AdminUiPlugin.init({
            route: process.env.ADMINURI || 'admin',
            port: 3002,
            app: compileUiExtensions({
                outputPath: './dist/admin',
                devMode: !process.env.NODE_ENV || process.env.NODE_ENV !== 'production',
                extensions: [
                    FavoritesPlugin.uiExtensions,
                ]
            }),
        }),
```

**Expected behavior**

compileUiExtensions should exists

**Environment (please complete the following information):**
 - @vendure/core version: 1.0.3
 - Nodejs version 14.17.0
 - Database (mysql/postgres etc): mysql 5.7
 - @vendure/ui-devkit: 0.9.0

**Comment by michaelbromley** [comment]
Is there a reason why the ui-devkit package is still on v0.9.0? That's a very old version from 1 year ago.

**Comment by u007** [comment]
i tried to install latest ui-devkit, thats the version im getting

**Comment by michaelbromley** [comment]
The latest version of all `@vendure/...` packages is 1.1.0 at this time. Check https://www.npmjs.com/package/@vendure/ui-devkit and click the "versions" tab.

**Comment by u007** [comment]
okay i think npm audit fix reverted the version
