### ISSUE TITLE
Allow to modify custom fields in address

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#979]
**Is your feature request related to a problem? Please describe.**
If there is any custom field in address like "houseNumber" its currently impossible to modify it via admin.

**Describe the solution you'd like**
Allow to update address custom fields.

**Comment by michaelbromley** [comment]
It _is_ possible to edit custom fields in a Customer's address from the Customer detail page.

Is this issue referring specifically to modifying an address associated with an Order via the order "Modifying" page?

**Comment by chladog** [comment]
Yes exactly, the address in the Order, e.g. change of shipping address of already placed order.
