### ISSUE TITLE
Security: Disallow querying of personal data for guest Customers

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#98]
Currently it is possible to:

1. Use `setCustomerForOrder` with `joe@smith.com`
2. Query `activeOrder.customer.addresses` to get data on any addresses used by `joe@smith.com` in the past.

This is a security hole which would expose details of previous guest checkouts, opening the door to enumeration attacks.

### Mitigation

Disallow access to the `customer` entity unless authenticated. Check for any other possible vectors of a similar nature.

**Comment by heri16** [comment]
This is really bad
