### ISSUE TITLE
Using multiple database connections

### ISSUE THREAD

**Issue by SebTorres** [vendure-ecommerce/vendure#986]
**Is your feature request related to a problem? Please describe.**
Hello! I am planning on creating an e-commerce page to sell cards from collectibles. The regular Product entity is perfect for sealed product such as boxes of sets of cards, etc. However, for the card singles, I am planning on retrieving their information from an external API, and using a Mongodb connection to store stock information about them only.

**Describe the solution you'd like**
I would like to know if Vendure has a way for me to define a new dbConnectionOptions, or if I can access the source TypeORM createConnections method on bootstrap to configure the multiple connections and access them when defining the Card entity.

**Describe alternatives you've considered**
I considered using only one database connection with multiple schemas instead, but I think Vendure is built to benefit from a relational database, whereas the card singles definition as I've thought it out would not work optimally in such a connection.

**Additional context**
I am very new to using Vendure, and I am still feeling my way around it. If I have missed an obvious way of doing this, I would very much appreciate being pointed in the right direction.

**Comment by michaelbromley** [comment]
Hi!

No, currently Vendure is not able to support multiple DB connections. But from your description I'm still not totally clear on why multiple data stores makes sense in this case. For example, you are free to define your own entities (tables) in the database (see [this example](https://www.vendure.io/docs/plugins/plugin-examples/defining-db-entity/)) which can store extra data you might need.

If that doesn't seem suitable, explain a bit more about the problem and maybe I can advise further.

**Comment by SebTorres** [comment]
Hi @michaelbromley!

Basically, what cards are present in the store will be very variable. I will show all cards (from a pool from around 20000), but will have reduced stock that will be marked on the website. Since I will pull the information about the card from an API, I only need to store in my database information about which cards I do have, what quantity, and what quality. I feel that a Document based approach is better for this than that of a relational database, but the rest of the application is much better off in a MySQL or similar DB.

I will keep exploring, and thinking alternatives as well. Thank you for your help!

**Comment by michaelbromley** [comment]
Alright, thanks for the explanation. Well, I'd advise that it might be worth trying to use the primary DB for this. I mean, MySQL/postgres are pretty damn good solutions to most data storage problems. I'm not sure what special performance requirements you have, but I think it is worth considering. Relational DBs can happily handle most challenges.

If for whatever reason you still prefer to use an external document store for that info, you can still do this as part of a plugin, in which your business logic manages its own connection to the datastore.

Anyway, I'll close this issue now, feel free to open a [discussion thread](https://github.com/vendure-ecommerce/vendure/discussions) if you want to discuss further.
